### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#1]
<img src="https://cloud.githubusercontent.com/assets/3409578/18992903/c1d2677e-86ee-11e6-82df-16e57b5ebc18.png" width="200px">

**Comment by TheBrokenRail** [comment]
Can you make a vector version of the scratch cat at the top?

**Comment by DanFessler** [comment]
Just wanted to drop in and say how much I'm loving the design polish :)

**Comment by liam4** [comment]
It's a private Google drive folder 😿

**Comment by herohamp** [comment]
😿

**Comment by dekrain** [comment]
@TheBrokenRail [Here you are!](https://gist.github.com/dekrain/14923dd0dce2044be59275a7be6f9c2c)

**Comment by liam4** [comment]
@dekrain Perhaps that would be better if the bounding box was adjusted and the background wasn't black? :)

**Comment by CosmicWebServices** [comment]
I like the designs... I mean I do not really like flat design but I like scratch 3s design (fingers crossed that I am not about to start a debate)

**Comment by dekrain** [comment]
I made a [review](https://gist.github.com/dekrain/6e425f5278552c635c013a9089a9a9cb) of things what is done now & what should be updated.

**Comment by jupiterio** [comment]
One thing I've noticed, the stage size buttons (beside the fullscreen button) still use the Scratch 2 layout.

**Comment by rschamp** [comment]
Moving to Backlog, otherwise we have to move the milestone every month for a while.

**Comment by TheBrokenRail** [comment]
Can you vectorize the scratch cat at the top again, the one you gave me has a black background and weird offset? Can you also unprivate the other sketches? Thank you.

**Comment by TheBrokenRail** [comment]
I really like the new scratch cat, it really fit's in with the new design, my question is when Scratch 3.0 is released will the new scratch cat be vector?

**Comment by aptitudex** [comment]
I like the new one as well- he looks much plumper than the Scratch Cat of late. I just wanted to say that it's been awesome seeing 3.0 come together, keep up the great work :-)

**Comment by TheBrokenRail** [comment]
Here's what it looks like compiled to a offline editor:
![editor](https://cloud.githubusercontent.com/assets/17478432/22210165/e383e2fe-e156-11e6-92ad-d3644b81ba73.PNG)
I think that area above the scratch blocks workspace is a good place for a menu bar. I compiled this with TheBrokenRail/Scratch3Builder

**Comment by CosmicWebServices** [comment]
@TheBrokenRail Mac support?

**Comment by TheBrokenRail** [comment]
It is supported but the file is too big to upload I'll try and see if it works again


________________________________

**Comment by TheBrokenRail** [comment]
Added mac support, changed compression from .zip to .tar.gz

**Comment by CosmicWebServices** [comment]
I did a little things design wise in #43

**Comment by TheBrokenRail** [comment]
I've changed my offline editor to use Electron, so it now runs fully offline, and supports armv7l!

**Comment by TheBrokenRail** [comment]
Just a question ,what is the current timeline for development, I know that the development is focusing on the chrome, but when do you expect to start working on stuff like the "File" menu?

**Comment by dekrain** [comment]
I'd like to do another try for say bubble. Can anyone give me please sketch for that? I mean this one with padding, sizes, colors, etc.

**Comment by rschamp** [comment]
@dekrain Thank you for offering, but we are going to handle implementing that feature ourselves.

**Comment by rschamp** [comment]
Closing because we're out of the "general design" phase now, so future design updates will be handled through smaller issues.
