### ISSUE TITLE
1000!

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#1000]
💯💯💯💯💯💯💯💯💯💯

**Comment by vutondesign** [comment]
@paulkaplan What's this?

**Comment by towerofnix** [comment]
This is the 1000th issue! (Not the `1000!`'th, though. It'll be a while before we get there. :shipit:)

**Comment by vutondesign** [comment]
Ah, Cool! 🎉

**Comment by Kenny2github** [comment]
@towerofnix I'm pretty sure it would take way more than a while to get to `1000!`

**Comment by GrahamSH-LLK** [comment]
Yay! 1000!
