### ISSUE TITLE
Deleting a procedure definition should remove the call block from the palette

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#1002]
Scratch 2
![scratch-2](https://user-images.githubusercontent.com/654102/33632479-b86f3c52-d9db-11e7-8950-515d7916cf14.gif)

Scratch 3
![scratch-3](https://user-images.githubusercontent.com/654102/33632484-bc026196-d9db-11e7-8b33-4ec658065af1.gif)

Procedure call blocks in the flyout should be flushed when the procedure definition is deleted. 

We may want to handle this directly within scratch-blocks?

**Comment by amazinigmech2418** [comment]
I think there needs to be a JS array that can store all of the blocks and show only the ones that are active in the palette. Maybe something like this to delete the block:
 `var customs=[]; 
function customdelete(block) {
customs.splice(customs.indexOf(block),1);
}` 
Then, adding blocks would just have to add the id to the array "customs" and add a function where if the x position of the block definition is in the palette, it will delete the block with the code.

**Comment by paulkaplan** [comment]
I'm going to close this issue because I think it'll be handled by scratch-blocks, so I moved the issue there https://github.com/LLK/scratch-blocks/issues/1295
