### ISSUE TITLE
Custom procedure can create a disconnected text block

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#1005]
To repro:
1. New custom block
2. switch sprites and switch back
3. Edit custom block, add an input
4. Switch back and forth again.
5. see the input is big, you can drag out the shadow onto the workspace...

![double-shadow-thing](https://user-images.githubusercontent.com/654102/33688098-4a7819c6-daa8-11e7-8a0c-ea3be869d838.gif)

**Comment by amazinigmech2418** [comment]
I think it may be that the edit feature needs to be revised. It seems like the edited version adds the text block also outside of the custom block.

**Comment by amazinigmech2418** [comment]
I just tested it. It seems like a json conversion error or rendering error.

**Comment by paulkaplan** [comment]
I'm going to close this issue as I believe this linked issue is the root cause, and it'll need to be solved over on scratch-blocks: https://github.com/LLK/scratch-blocks/issues/1291
