### ISSUE TITLE
Cannot click "play" button in this 2.0 project

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#1007]
### Expected Behavior

_Please describe what should happen_

After hitting the green flag, hitting the button labeled "play" should start the game.

### Actual Behavior

_Describe what actually happens_

It does not start the game.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Open this project https://llk.github.io/scratch-gui/develop/#177260519
2. Click green flag
3. Click "play"

### Operating System and Browser

Mac 10.12.6, Chrome 62.0.3202.94

-----

Investigating further, I also noticed you cannot open the costume editor for many of these sprites, including the button sprite that also cannot be clicked. There is the `scratch-paint SVG import failed:` error, and similar to the watermelon costume, the svg has these strange prefixed `<svg:svg ...>` tags. I wonder if this is related to not being able to click it, possibly the renderer can render it but is having trouble measuring the bounding box or something?

**Comment by thisandagain** [comment]
This would actually explain quite a few of the compatibility problems we have been seeing on other projects as well. Raising this to `critical`.
