### ISSUE TITLE
Cannot open project with both "X" and "x" variables

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#1008]
### Expected Behavior

_Please describe what should happen_

Should be able to load a project like this one: https://llk.github.io/scratch-gui/develop/#189524895

### Actual Behavior

_Describe what actually happens_

It fails to load with this error: 

```
Uncaught (in promise) Error: Variable "X" is already in use and its id is "Q:(NMDNi+=uGHv?K1nO^-x" which conflicts with the passed in id, "Q:(NMDNi+=uGHv?K1nO^-X"
```

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

I made another repro with a simplified case: try to import a project with an uppercase and lowercase version of the same variable, like this one: 

![image](https://user-images.githubusercontent.com/654102/33719513-fbdfaa72-db2e-11e7-85d0-ab567b40309e.png)

https://llk.github.io/scratch-gui/develop/#191677809

---

Tracking down the root cause, it looks like scratch-blocks is lowercasing variable names to check for uniqueness. Scratch 2 has case-sensitive variable names, so I assume scratch 3 wants to also. We can create an issue on scratch-blocks once we confirm that we want that behavior and it'll be ok to fix it that way in scratch-blocks.

**Comment by mrjacobbloom** [comment]
blockly documentation on case-insensitive naming: https://developers.google.com/blockly/guides/app-integration/best-practices#4_variable_and_function_names
