### ISSUE TITLE
Revise "glide to" block input ordering

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-gui#1014]
The glide block in Scratch previous worded as **glide x secs to x: y:**

The new glide block is ordered similarly: **glide x secs to [random point/Sprite]**

Consider reordering order of inputs to: 
   **glide to [random point/Sprite] for x secs**

Possible Pros: More obvious what block does; More consistent with other blocks (e.g., say, play)
Possible Cons: Breaks previous documentation and translations; Longer block in English (" for ") - will that be too long to show on the palette?

**Comment by davidaylaian** [comment]
Sounds good to me. The function of `glide to ___ for x secs` isn't obvious at first glance.

**Comment by kyleplo** [comment]
You could do the same with the other block: `glide to x: y: in x secs`

Also, I think `in x secs` makes more sense than `for x secs`

**Comment by ntlrsk** [comment]
Decision was made to leave current glide block wording order because of block length.

(Adding "for" or "in" would lengthen by 3 or 4 characters (with spacing), too wide to fit in current palette.) Thanks for all who helped to consider this.
