### ISSUE TITLE
Remove ability to select tab button text

### ISSUE THREAD

**Issue by davidaylaian** [LLK/scratch-gui#1015]
Currently, if you click twice on a tab button, the text is able to be selected, as shown:

![screenshot](https://user-images.githubusercontent.com/22228595/33791137-a92347bc-dc55-11e7-8a02-80d7188b9406.png)

Consider removing this so that the text cannot be selected.

Possible Pros: the text selection can easily be trigged by accident and it doesn't look good
Possible Cons: users cannot copy the text

I already have a [commit](https://github.com/davidaylaian/scratch-gui/commit/ee6086ed2202ffa3a3cf1ae1f4c622f59b26228e) that implements the proposed change. I'm opening this issue for discussion.

**Comment by thisandagain** [comment]
Good catch. Thanks. PR is welcome. :-)

**Comment by Kenny2github** [comment]
@thisandagain might want to label this with something? ;)

**Comment by thisandagain** [comment]
@kenny2github Sorry. I'm traveling (on my phone). I'll catch up with labels and PRs when I get back to my laptop.

**Comment by Kenny2github** [comment]
@thisandagain ahhh, I see. No problem then :D
