### ISSUE TITLE
Lists appear as Variables

### ISSUE THREAD

**Issue by follingeneric17** [LLK/scratch-gui#1016]
### Expected Behavior

Lists, when created, should have a List watcher.

### Actual Behavior

It shows a Variable called data_listcontents and each item is shown with a space.

### Steps to Reproduce

1.  Click "Create a List"
2. Name the list whatever you want.
3. Click "OK"
4. You'll see a variable named "data_listcontents" on the stage.
5. Add 2 or more things to the list.

### Operating System and Browser

Windows 10 Google Chrome

**Comment by mrjacobbloom** [comment]
I think this is a duplicate of #942
