### ISSUE TITLE
Inconsistency in Make a Block input creation

### ISSUE THREAD

**Issue by seotts** [LLK/scratch-gui#1019]
### Behavior

When you add a reporter block input to a block you're creating, the button says "Add an input, number or text" but the default name of the input is "string or number." To me, it feels like the name of the string/text data type should be consistent (so the default name of the input should be "number or text").

![image](https://user-images.githubusercontent.com/4612592/33844127-55f3bfda-de6d-11e7-8f66-d0cc7ec5591b.png)

### Steps to Reproduce

Click "Make a block" and then click "Add an input, number or text"

**Comment by thisandagain** [comment]
Agreed. We should avoid the word "string". This should read "number or text" (match button) rather than "string or number".

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-blocks/pull/1322
