### ISSUE TITLE
Renaming a sound should cause workspace blocks to update

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1020]
### Expected Behavior

When you rename a sound using the sound editor, sound blocks on the workspace that have that sound selected should update to display the new name.

### Actual Behavior

"Start sound" and "play sound" blocks on the workspace do not update (blocks in the toolbox do update).

### Steps to Reproduce

Drag a "start sound" block onto the workspace, with the default "meow" sound selected.
Go to the sounds tab and rename the meow sound to something else
Switch back to the blocks tab, and the "start sound" block still shows "meow"

**Comment by paulkaplan** [comment]
Fixed!
