### ISSUE TITLE
Renaming a costume should cause workspace blocks to update

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1021]
### Expected Behavior

When you rename a costume using the costume editor, blocks on the workspace that have that costume selected should update to display the new name.

Note that this is similar to the bug for sounds, https://github.com/LLK/scratch-gui/issues/1020. Scratch 2.0 _does_ display the functionality expected for sounds (updating blocks in the workspace),  but for some reason it does _not_ do what's described here for costumes. In spite of this I would say we should also implement the update for costumes (unless there's some reason Scratch 2.0 did it this way).

### Actual Behavior

"Switch costume" blocks on the workspace do not update (blocks in the toolbox do update).

### Steps to Reproduce

Drag a "switch costume" block onto the workspace, with the default costume "costume1" selected.
Go to the costumes tab and rename the costume to something else.
Switch back to the blocks tab, and the "switch costume" block still shows "costume1".

**Comment by paulkaplan** [comment]
Fixed
