### ISSUE TITLE
Custom blocks should default to "run without screen refresh" false

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1023]
### Expected Behavior

When you make a custom block, it should run normally.

### Actual Behavior

Custom blocks currently default to having "run without screen refresh" set to true, so they run as fast as possible. If they do not contain a block that yields the VM, no intermediate states are visible, and the blocks are all run instantly.

### Steps to Reproduce

Click "make a block" and click okay
Add blocks to the define block that cause animation to happen, such as:
```
define block name
repeat 10
  turn 15 degrees
```
Click the call block
Notice that the sprite turns instantly by 150 degrees, rather than animating each step

**Comment by fsih** [comment]
If a custom procedure calls itself, it freezes the UI. This is a pretty easy situation to accidentally get into when you are trying to learn about recursive functions. Maybe even if run without screen refresh is on, it should still throttle enough to not freeze the UI?
