### ISSUE TITLE
Can't release broadcast block

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#1027]
### Expected Behavior

I should be able to release the block.

### Actual Behavior

I can't release the block and it keeps following my mouse

### Steps to Reproduce

I don't know. I was just dragging a broadcast block.

### Operating System and Browser

I don't know.

**Comment by Kenny2github** [comment]
Cannot reproduce in any obvious way on Chrome 63 Windows 8. Might have just been a glitch, not a bug.

**Comment by rschamp** [comment]
@amazinigmech2418 This sounds like an issue with dragging blocks. If you can figure out how to reproduce this issue, please open up a bug on LLK/scratch-blocks. We really need to know which browser you're using, so make sure you include that. Here's a website for telling you that information: https://www.whatsmybrowser.org/ (scroll down to find Operating system).

Closing until there are steps to reproduce.

**Comment by amazinigmech2418** [comment]
OK. It may have been a glitch... I know it was on a kindle at the time... It uses silk browser.
