### ISSUE TITLE
unable to save a project with iOS11.1 and iOS11.1.2

### ISSUE THREAD

**Issue by tyreun** [LLK/scratch-gui#1030]
### Expected Behavior

save a project on iPad with safari

### Actual Behavior
 With safari on iPad iOS11.1, iOS11.1.1, iOS11.1.2 and IOS 11.2
![img_1298](https://user-images.githubusercontent.com/1543205/33946700-c03d10a6-e022-11e7-8f51-8ad0d747b6a2.PNG)
![img_1299](https://user-images.githubusercontent.com/1543205/33946706-c3cf2b0a-e022-11e7-8d03-a4124f83aa68.PNG)

I can't save the project

With iOS 11.0.3
![img_0006](https://user-images.githubusercontent.com/1543205/33946721-c9b21aaa-e022-11e7-860b-448a4aa90ab2.PNG)
![img_0007](https://user-images.githubusercontent.com/1543205/33946732-ced7fbbc-e022-11e7-878d-cd10468d291d.PNG)

I can save the project

### Steps to Reproduce

tap on "Save" in safari with an iPad in iOS11.2 or iOS11.1.*
### Operating System and Browser

IOS 11.1.*
IOS 11.2

**Comment by BryceLTaylor** [comment]
Same as https://github.com/LLK/scratch-gui/issues/1783

That one has more comments, so I'll keep it.
