### ISSUE TITLE
Blank costumes in the sprite library

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1031]
### Expected Behavior

All the sprites should be visible in the sprite library.

### Actual Behavior

One of our workshop laptops (a macbook) displayed the sprite library with most of the sprites blank. When you mouse over the sprites, any additional costumes would animate as usual, but the first costume would remain blank.

### Steps to Reproduce

@rschamp will follow up to try to find out what is different about that one laptop.

### Operating System and Browser

TBD

**Comment by paulkaplan** [comment]
I repro'd on that computer. It seems to have cached some kind of invalid response. When I opened up the dev tools and clicked "disable cache", it worked again... Not sure what we can do about that. I think we should just close this 🤷‍♀️
