### ISSUE TITLE
Scratch 3.0 does not render in Microsoft Edge at all

### ISSUE THREAD

**Issue by endapril** [LLK/scratch-gui#1039]
simply open https://llk.github.io/scratch-gui/    in Microsoft Edge, you can see on the right side the screen the Cat is not there. Also Motion column says "Stage selected: no motion blocks"

OS version: windows 10 15063 and 16299

**Comment by paulkaplan** [comment]
Would love some help from Edge users on this one. I tried loading edge in the microsoft provided VM in virtualbox, I don't see any errors in the F12 console or anything :( :(

**Comment by endapril** [comment]
I tried on all my physical machines (win version 15063, 16299). no render, but no error message in console.
Could you try on a physical machine? @paulkaplan

**Comment by paulkaplan** [comment]
Yeah I actually saw the same thing (no render, but with no errors). Sorry my last comment was kind of unclear.

**Comment by endapril** [comment]
probably Scratch-VM problem, test page of VM not working in Edge

**Comment by Grinthy** [comment]
@endapril 1st post:

Motion Blocks are not in because there are no sprites, I think.

**Comment by trafort** [comment]
There are many issues in the LLK/scratch-GUI/ Talking about edge problems.
I think edge can't support blocky the scratch system.

Tell me, if i'm wrong

**Comment by amazinigmech2418** [comment]
Maybe Edge doesn't support critical elements such as canvas.

**Comment by trafort** [comment]
Maybe
