### ISSUE TITLE
How to get all the project's assets?

### ISSUE THREAD

**Issue by alexwenbj** [LLK/scratch-gui#1040]
### Expected Behavior

When I click the "Save" button,save all the project assets include project json file,sprites and sound file,etc,just like in Scratch 2.0.(in a zip file)

### Actual Behavior

Only save the project json file.

### Steps to Reproduce

Visit http://llk.github.io/scratch-gui/ and click Save button.

### Operating System and Browser

Mac OS 10.11.6 Safari 10.0

**Comment by Kenny2github** [comment]
The SB3 format is still under construction, so for now the only thing that is saved is the project.json file.

**Comment by alexwenbj** [comment]
OK,Thank you.

**Comment by thisandagain** [comment]
Tracking in #45
