### ISSUE TITLE
Blurry when in full-screen mode

### ISSUE THREAD

**Issue by vutondesign** [LLK/scratch-gui#1041]
### Expected Behavior

The project should look the same in the new full-screen mode.

### Actual Behavior

It's a bit blurry when in full-screen mode.
![capture](https://user-images.githubusercontent.com/26391179/34033421-167bad38-e172-11e7-85f7-7b4064f8f946.JPG)

### Steps to Reproduce

Use the new full-screen mode with any sprite.

### Operating System and Browser

Windows 8.1, Chrome 63.0.3239.84 (Official Build) (64-bit)

**Comment by griffpatch** [comment]
This is to do with the rasterization of costumes at 100% on creation and
that they are not.
This is being tracked in another issue:
https://github.com/LLK/scratch-render/issues/24

**Comment by vutondesign** [comment]
Ah okay 👍
