### ISSUE TITLE
can't load project json file after changing the default costume

### ISSUE THREAD

**Issue by hecor** [LLK/scratch-gui#1042]
### Expected Behavior

load project json file normally.

### Actual Behavior

error happened and the costume panel are empty.

![bug](https://user-images.githubusercontent.com/1171710/34035046-ae363960-e1bb-11e7-9354-c30db799d929.png)

### Steps to Reproduce

1. open https://llk.github.io/scratch-gui/
2. change costume2 of Sprite1 by adding a circle(or anything else).
3. save the project to a local json file.
4. refresh the web page.
5. load the saved json file.

### Operating System and Browser

Mac OS 10.12.6 Chrome 63.0.3239.84

**Comment by challange** [comment]
l met the same problem

**Comment by thisandagain** [comment]
Tracking in #45
