### ISSUE TITLE
Add keyboard controls for paint editor

### ISSUE THREAD

**Issue by quachtina96** [LLK/scratch-gui#1045]
### Expected Behavior
As someone used to using keyboard controls for editing images and text, I instinctively tried to use
Ctrl + Z to undo changes in the paint editor
Ctrl + C to copy
Ctrl + P to paste

### Actual Behavior
Nothing happens when you use these key controls.

**Comment by fsih** [comment]
Dupe of https://github.com/LLK/scratch-paint/issues/38
