### ISSUE TITLE
Block positions get reset and they pile on top of each other

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1055]
### Expected Behavior

My blocks should have been where I left them

### Actual Behavior

Blocks piled on top of each other when I switched sprites and switched back.

### Steps to Reproduce
I don't have a consistent repro but here is a video of it happening
1. Starts on the watermelon sprite
2. I move the cat sprite around a few times
3. Click back on the watermelon sprite in the info pane to get back to it
4. Nothing obvious in the console
![blocksbug](https://user-images.githubusercontent.com/2855464/34063456-35605fca-e1c0-11e7-8bfa-5d9630a504b6.gif)

### Operating System and Browser

Mac Sierra Chrome

**Comment by davidaylaian** [comment]
I was able to consistently repro this. Create this:
![screenshot](https://user-images.githubusercontent.com/22228595/34066290-ac4fdf74-e1da-11e7-805e-d1baf4f9f359.png)
Now switch sprites and go back. The goto is behind the forever loop.

**Comment by kyleplo** [comment]
I think this just involves the order the blocks were created. It shouldn't mess up the code, and I don't see why you would want to overlap blocks anyway.

**Comment by paulkaplan** [comment]
@davidaylaian I do not think that is the same problem as @fsih originally reported, where all the blocks get moved in XY to be stacked on top of each other. Can anyone repro something that looks more like the gif?

**Comment by vutondesign** [comment]
I can't seem to repro this or anything similar when using the same steps as @fsih. 

MacOS High Sierra - Chrome 63.0.3239.108

**Comment by paulkaplan** [comment]
Closing due to lack of repro
