### ISSUE TITLE
Put extension icons in category button

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1058]
I think the extension category buttons would look better with an extension icon, like this:

![image](https://user-images.githubusercontent.com/31634240/34071215-ddbc2606-e240-11e7-8905-7635e417b4a6.png)

I did this by putting an `<img>` tag with a width and height of 15 in the `scratchCategoryItemBubble` class for the extension.

**Comment by thisandagain** [comment]
We have a design spec for this that @carljbowman and @ericrosenbaum are currently working on implementing.
