### ISSUE TITLE
+ Icons Inconsistent With Window Scale

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-gui#106]
### Expected Behavior

If the window is resized, either panes should move together or should be cut off.

### Actual Behavior

The + icons move, but relevant sprite and backdrop panes do not. Allowing one to have two random + signs floating away from their panes.

![image](https://cloud.githubusercontent.com/assets/8440451/23038100/c7c70088-f456-11e6-88da-0aa3dd2a496d.png)

### Steps to Reproduce

Open https://llk.github.io/scratch-gui/, and resize the window to be much smaller. 

### Operating System and Browser

Ubuntu 16.04, Chrome 56.0.2924.87

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/86
