### ISSUE TITLE
Adding 'Blue Sky' as backdrop causes error

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#1063]
### Expected Behavior

Adding backdrops should not cause type errors.

### Actual Behavior

Adding 'Blue Sky' causes the following error:
`Uncaught TypeError: Cannot read property 'then' of undefined`

### Steps to Reproduce

Open a new project.
Click 'Add Backdrop'.
Select the 'Blue Sky' backdrop.
Observe error in console.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by thisandagain** [comment]
Note for prioritization / triage: this type error does not cause the entire application to crash

**Comment by sjhuang26** [comment]
Note that this error occurs for every backdrop, not just the "Blue Sky" one.

**Comment by davidaylaian** [comment]
On Chrome, I got the same error message that you did.
But on Firefox, I got this one:
```
TypeError: this.props.vm.addBackdrop(...) is undefined
```

**Comment by fsih** [comment]
Because of this error, the backdrop is not automatically being switched to in the paint editor when the backdrop is added.

**Comment by paulkaplan** [comment]
Fixed by https://github.com/LLK/scratch-vm/pull/870
