### ISSUE TITLE
Replace "rotation style" with "size" in sprite info area

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#1064]
We would like to remove the "Rotation" option in the sprite info area with a new selector for "Size" that fits between the "Show" and "Direction" options.

![image](https://user-images.githubusercontent.com/747641/34130680-c5c5ef32-e416-11e7-8e2c-c0b0829b167f.png)

**Comment by carljbowman** [comment]
### Overview
Rotation-style is rather abstract and has hidden state. It does not feel like the right type of thing to include at the surface level within the Sprite Info area. The rotation style can still be set with blocks.

The new size input should adjust the size of the sprite, similar to other inputs in the space, e.g. X position dynamically adjusts the X position of the sprite.

### Mock
I believe we are using flex-box to position elements within the Sprite Info area, hence all the extra space around the Size input.
![sprite-info-update](https://user-images.githubusercontent.com/3409578/34211788-2a70162c-e568-11e7-840c-e05873f75f8f.png)

**Comment by griffpatch** [comment]
Could the rotation mode be bundled into the direction box... a direction of
90 or -90 hardly seems right without the option to switch between
horizontal flipping or rotation. Could the rotation, drop down also have
the three options for static, flip & rotation modes as well as the
direction wheel?

**Comment by thisandagain** [comment]
@griffpatch Would you mind filing that as a separate issue?

**Comment by carljbowman** [comment]
@griffpatch - I have thought about this a little for the angle picker in the blocks (specifically point in direction), but I have some concerns about collapsing two properties that are programable into a single field. 

Color is an example of where we collapse may properties (H+S+B in 3.0 and Hue+Shade in 2.0) into a larger construct and that has always been rather confusing. I'd argue that this type of collapsing is a pattern we would want to avoid.

That said, I do think we should think more about how to highlight the relationships/impacts of compounding properties.
