### ISSUE TITLE
Scratch 3.0 Preview - Extensions Teasers

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#1074]
## Overview
We will have some extensions for Preview, but not a lot of extensions. We'd like to include some more teaser extensions in the library with the label "Coming soon...". 

## List of Extension Teasers
- LEGO WeDo 2.0
- Video Sensing
- Speech
- LEGO Boost 

## Content
**LEGO WeDo 2.0**
Title: `LEGO WeDo 2.0`
Copy: TBD - @ericrosenbaum 
Image: See asset ZIP below

**Speech**
Title: `Speech`
Copy: TBD - @ericrosenbaum 
Image: See asset ZIP below

**Video Sensing**
Title: `Video Sensing`
Copy: TBD - @ericrosenbaum 
Image: See asset ZIP below

**LEGO Boost**
Title: `LEGO Boost`
Copy: TBD - @ericrosenbaum 
Image: See asset ZIP below

**Image Assets**
[extension-images.zip](https://github.com/LLK/scratch-gui/files/1600623/extension-images.zip)

## Sketch
Some elements should be ignored as apart of this work. Eventually we will build out these elements.
Focuses on:
- Create a style of Extension card that is transparent
- Adding "Coming soon..." tag element to the Extension card element

Does not focus on:
- We do not need to add the Extension icon like on Pen and Music
- We do not need to add the requirements section (Wifi icon... the sketch is incorrect)

![extension lib](https://user-images.githubusercontent.com/3409578/34176991-fd74af72-e4cf-11e7-9b3a-d9604f84f72d.png)

**Comment by ericrosenbaum** [comment]
Proposed copy for description fields (going pretty minimal here):

LEGO WeDo 2.0 - Build with motors and sensors.
Speech - Talk to your projects.
Video Sensing - Detect motion with the camera.
LEGO Boost - Build robots and more.

**Comment by mrjacobbloom** [comment]
"Detect motion with the camera" strikes me as fairly clinical next to the other 3

**Comment by mewtaylor** [comment]
@carljbowman the wifi icon and the smaller pen/music icons are not currently on the extensions – should I be adding those in as part of this PR?

**Comment by carljbowman** [comment]
@mewtaylor - Added the Speech extension image to the asset ZIP above.

**Comment by mewtaylor** [comment]
Implemented in #1132

**Comment by maelp** [comment]
Hi, I'm a co-founder of https://snips.ai, we are building a 100% on-device and private-by-design Voice AI platform, which we will open-source over time

Snips allows people to create assistants from our website by typing a few sentences, which we generalize and allow to run wake word detection, speech recognition and NLU on small devices like a Raspberry Pi3, 100% on-device, respecting the privacy of users (which is so important when building tools for the kids)

I'm very interested in the works of Seymour Papert (I coded in Logo as a child :) ) and I wanted to create an extension for Scratch to allow binding to our platform, I was looking at how to do this and I saw that you were looking at speech for the next version of your platform, so there is probably something we can do together! I'd love to know how I can help

We are available for Linux (running on a raspi), osX, iOS, Android, and many other platforms too
