### ISSUE TITLE
Right click menu doesn't close when clicking in another area

### ISSUE THREAD

**Issue by davidaylaian** [LLK/scratch-gui#1081]
### Expected Behavior

If you left click while the scripting area's right click menu is open, the menu should close.

### Actual Behavior

The menu only closes if you left click inside the scripting area.

### Steps to Reproduce

1. Right click in the scripting area
2. Left click in the sprites area
3. The right click menu is still there

### Operating System and Browser

Tested on Chrome 63.0.3239.108 and Firefox 57.0.1, both on Linux

**Comment by vutondesign** [comment]
I can repro this on master and develop, I assume it happens because the custom right-click menu is a separate object from the default menu that you get when you right-click on the sprite area.

> Chrome 63.0.3239.108, Windows 8.1

**Comment by rachel-fenichel** [comment]
To fix call `Blockly.hideChaff`: https://github.com/LLK/scratch-blocks/blob/develop/core/blockly.js#L280

**Comment by chrisgarrity** [comment]
This is a low priority issue with easy work-arounds. The risks associated with fixing it outweigh any benefit, so closing as wontfix.
