### ISSUE TITLE
Rotation Style Menu is Inconsistent with block.

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-gui#110]
### Expected Behavior

_They use the same terms._

### Actual Behavior

_They use different terms that might be confusing._

### Steps to Reproduce

_Go to https://llk.github.io/scratch-gui and look at rotation style block and rotation style menu._

**Comment by thisandagain** [comment]
Tracking in #85

**Comment by TheBrokenRail** [comment]
This isn't about whether they work or not but this:
The Block has:
- don't rotate
- left-right
- all around
The Menu has:
- anchored
- clockwise
- left-right

**Comment by thisandagain** [comment]
Will resolve during the implementation. Current menu is just a stub.
