### ISSUE TITLE
Preview Navigation Bar

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#1105]
We need to get the navigation bar designed and integrated into the GUI (even if most features of the navigation bar are "Coming Soon" for now).

**Comment by carljbowman** [comment]
### Overview
As mentioned above, this version of the toolbar is for the preview and the features will appear as "coming soon," until the features are completed. For a more robust sketches of the toolbar and toolbar states review this issue: [Coming soon...]

### Preview Toolbar Sketch
This particular view of the editor appears as though someone is logged-in and viewing a project that they created.
![toolbar-preview- 1280 x 720](https://user-images.githubusercontent.com/3409578/35736340-ad06b604-07f5-11e8-9860-7c52a4286958.png)

**Elements**
Again most elements will be static with the coming soon tooltip 
- [ ] Nav / Menus
  - [ ] Logo
  - [ ] Menu Selector - Should be modified from the current menu to the icon dropdown like 2.0
  - [ ] File Menu
  - [ ] Edit Menu
- [ ] Project Info
  - [ ] Project name field
  - [ ] Share button
  - [ ] See Community button (previously See Project Page, still working on language here)
- [ ] Give Feedback button (needs to be moved)
- [ ] Logged-in Account Info
  - [ ] My Stuff icon
  - [ ] User Avatar
  - [ ] Username dropdown

**Assets**
[Coming Soon...]

**Comment by towerofnix** [comment]
>Menu Selector - Should be modified from the current menu to the icon dropdown like 2.0

Typo (should be "Language Selector"), I assume?

**Comment by carljbowman** [comment]
@thisandagain - Wasn't sure who was going to implement this, so assigning to you to reassign.
