### ISSUE TITLE
Sound editor captures keystrokes

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#1107]
Should `when key pressed` actions still run when in the sound editor? other places? Currently key presses are captured by the sound editor even when you're not editing the sound label.

Example: wanting to record a sequence of sounds as they play them (where sounds are started by keypress events).

**Comment by paulkaplan** [comment]
I might be misunderstanding this, can you list repro steps? Here is what I tried: 

1. Add "when space key pressed => say hi for 2 seconds" to the workspace
2. Switch to sound editor. space key still triggers "hi" 

![keypress-sound](https://user-images.githubusercontent.com/654102/34267963-f5804168-e64c-11e7-8f81-5dc29e63116e.gif)

**Comment by paulkaplan** [comment]
Closing due to lack of repro
