### ISSUE TITLE
Context Menu creates scroll bar.

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-gui#111]
### Expected Behavior

_It is hidden or goes the other way._

### Actual Behavior

![bug](https://cloud.githubusercontent.com/assets/17478432/23093779/1cc15a98-f5ba-11e6-9c1d-13a7f0383fc1.PNG)

### Steps to Reproduce

_Right click at bottom of workspace._

### Operating System and Browser

_Windows 10 Google Chrome_

**Comment by SillyInventor** [comment]
For some reason in scratch-blockS the ContextMenu.show calls:
`Blockly.WidgetDiv.position(x, y, windowSize, scrollOffset, rtl);`
But creating a div with the height of the original window size below the top requires scrolling. The simplest solution is to just to pass it the height of a menu item * the number of items for height.

**Comment by SillyInventor** [comment]
Does anyone mind if I make this change?

**Comment by bigeyex** [comment]
This is solved in scratch-blocks pr857.
