### ISSUE TITLE
A bug in Collapse Blocks

### ISSUE THREAD

**Issue by chaoqinf** [LLK/scratch-gui#1125]
First i add a block,
![first](https://user-images.githubusercontent.com/32251731/34331754-9068fed0-e964-11e7-8a00-b5ef849c1b6e.png)
then i choose the Collapse Blocks,
![next](https://user-images.githubusercontent.com/32251731/34331769-c042c0dc-e964-11e7-9850-1f6a7649de70.png)
next drag the block(not delete),All block can't drag.
if add a sprite,The console would be wrong.
![finally](https://user-images.githubusercontent.com/32251731/34331841-6436940c-e965-11e7-8b6c-906a1a8dddad.png)
over.
I don't know if it's a bug or I'm working on it.

**Comment by sjhuang26** [comment]
Note that this "collapse blocks" feature is available on the master branch,  but not on the develop branch.

**Comment by thisandagain** [comment]
Resolved in #1082
