### ISSUE TITLE
 Failed to compile

### ISSUE THREAD

**Issue by esijie** [LLK/scratch-gui#1130]
### Actual Behavior

 Failed to compile. 

### Steps to Reproduce

Module build failed: TypeError: Plugin 3 specified in "C:\\Program Files\\nodejs\\node_global\\node_modules\\scratch-gui
\\.babelrc" was expected to return a function but returned "undefined"

### Operating System and Browser

windows10 + NPM

**Comment by esijie** [comment]
Maybe Babel version，i'm using 6，right？

**Comment by paulkaplan** [comment]
@fsih you are on windows 10 right? Any advice? 

Sorry if we are slow to get to this, most of us are away for the holidays!

**Comment by fsih** [comment]
Sorry, I haven't seen this error before.

I am using WSL on Windows 10, so although it's a Windows computer, my setup is like Ubuntu. It has made a lot of things easier for me. If you would like to try it, there are instructions here: https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by esijie** [comment]
Thanks。
Success on Ubuntu。But，for some reason, I have to using win10。I'll try WSL。

**Comment by thisandagain** [comment]
Thanks @esijie. Feel free to re-open this if you continue to have trouble with WSL.
