### ISSUE TITLE
support sprite to rotate, enlarged,shrink

### ISSUE THREAD

**Issue by jiangbo2015** [LLK/scratch-gui#1131]
### support sprite to rotate, enlarged,shrink

I want the sprite can have these functions, like the picture
the pic url: http://i1.bvimg.com/621274/0ba8f0a701f8059d.gif
![Markdown](http://i1.bvimg.com/621274/0ba8f0a701f8059d.gif)
### there is no these features

can you provider some ideas, I want these functions

**Comment by thisandagain** [comment]
You can do that in the paint editor. We have no plans to add that to the top-level "stage" at this point.
