### ISSUE TITLE
Feedback form should include optional project number

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-gui#1142]
For debug purposes it would be great to record project numbers for publicly available projects that exhibit weird behaviour.

**Comment by apple502j** [comment]
The project is not saved now, isn't it?

**Comment by thisandagain** [comment]
@rachel-fenichel Yup! Agreed. I'll add that to the February iteration when we expect to have import from Scratch 3.0 hooked-up.

**Comment by towerofnix** [comment]
>I'll add that to the February iteration when we expect to have import from Scratch 3.0 hooked-up.

Sorry to barge in with a somewhat unrelated topic, but - what's "import *from* Scratch 3.0" mean? I didn't think Scratch 2.0 was going to be able to open 3.0 projects! 😛

**Comment by thisandagain** [comment]
All set.
