### ISSUE TITLE
Implement Help Window

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1143]
The help window has not been added yet. Here is an idea:
![image](https://user-images.githubusercontent.com/31634240/34439424-ea6543de-ec7b-11e7-9fd4-b91af44223df.png)

**Comment by redmangospros** [comment]
:)!

**Comment by thisandagain** [comment]
We are redesigning how the help system in Scratch 3.0 will work. Stay tuned. 😄
