### ISSUE TITLE
Sprites should be added at a random x/y position

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#1148]
### Expected Behavior

- Adding a new sprite from the sprite library should result in the sprite being placed at a random X/Y position

### Actual Behavior

- Sprite is always added at the same position

### Steps to Reproduce

- Open sprite library
- Add "Bat"
- Note sprite position
- Add "Bat" again

**Comment by kyleplo** [comment]
I know it is strange to have all sprites spawn in the same position, but what if we have like 9 positions that were chosen at random:
- 0, 0 - center
- 0, 90 - top
- 0, -90 - bottom
- 120, 0 - right
- -120, 0 - left
- 120, 90 - top right
- 120, -90 - bottom right
- -120, 90 - top left
- -120, -90 - bottom left
I think this would make the positions somewhat helpful, instead of totally random.

**Comment by apple502j** [comment]
OK. I made 2 version.
It is possible. Only change sb2.js!

**Comment by apple502j** [comment]
+1 to thisandagain.

I made 2 branches in my fork.
Difference is only sb2.js.


When the JSON has no 'scratchX' value, the value is chosen from 'defaultX' list at random.
(Y is also.)
kylepro ver https://github.com/apple502j/scratch-vm/blob/with-chosen-position/src/serialization/sb2.js

When the JSON has no 'scratchX' value, the value is chosen at random.
(Y is also.)
thisandagain ver https://github.com/apple502j/scratch-vm/blob/with-random-position/src/serialization/sb2.js

**Comment by apple502j** [comment]
kylepro ver
https://github.com/apple502j/scratch-gui/tree/patch-2
thisandagain ver
https://github.com/apple502j/scratch-gui/tree/patch-1

**Comment by apple502j** [comment]
+1 to thisandagain.
Can someone check my code?

**Comment by bartljak** [comment]
I believe the latest update to develop implemented this feature.

**Comment by dgnball** [comment]
If I duplicate the cat this is what I get:
![image](https://user-images.githubusercontent.com/6998018/41798607-2ef4eb2a-7666-11e8-963f-3f8f221a0e6e.png)
... so it seems to be working. Can you close this ticket if you agree.

**Comment by paulkaplan** [comment]
Yup this has been fixed. Closing.
