### ISSUE TITLE
Use different color for extensions and custom blocks

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1149]
In Scratch 2.0, custom blocks and extensions are different colors. In Scratch 3.0, they are the same. I think this makes them easier to tell apart:
![image](https://user-images.githubusercontent.com/31634240/34456856-f5ba8728-ed6e-11e7-80bd-5fcdb7ca57cc.png)
In this example, extension block fill is `rgb(180, 105, 122)` and stroke is `rgb(180, 51, 85)`.

**Comment by kyleplo** [comment]
Same as https://github.com/LLK/scratch-blocks/issues/1336

**Comment by apple502j** [comment]
+1. Also, "pen" and "music" should be different colors.

**Comment by paulkaplan** [comment]
Custom blocks now have a different color from extension blocks.
