### ISSUE TITLE
enableExtensions in gui.jsx doesn't have any effect

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-gui#1151]
the GUI component has a enableExtensions prop, which I guess is supposed to handle showing/hiding the extensions button, but for now has no effect (it tries to add a CSS class that doesn't exist). Not sure if that's intended, but I found it confusing (and easy to fix).

https://github.com/LLK/scratch-gui/blob/9c9e67e5a7ef0cc403af2d674f0134dbeaf5d9ea/src/components/gui/gui.jsx#L106 

the CSS class was added in:
https://github.com/LLK/scratch-gui/commit/e198fd8ba14b8bfebd6759c375f73036653d43b1#diff-b7242c351b9350e75554ef0411945492R163

but removed here:
https://github.com/LLK/scratch-gui/commit/c1a80ce893521c1fbace2fc8f1516d5fd9822c91#diff-b7242c351b9350e75554ef0411945492 

Adding those 3 lines back solves the issue, but notice that for now the default for enableExtensions is false, so if actually hides the button. 

@ericrosenbaum - is this a bug or intended behavior for now?

**Comment by ericrosenbaum** [comment]
I talked about this with @rschamp. Since we are not planning to use the enableExtensions prop (which was leftover from a prototyping phase), we are going to remove it. Sorry about the confusing state things were in. It sounds like you have a workaround that will do the trick!

**Comment by morantsur** [comment]
Works for me!
