### ISSUE TITLE
Hide text label on "Add" media buttons

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#1160]
### Overview
Currently we display text like "Add Sprite" or "Add Backdrop" on the icons that add various media to the editor. This will not scale well as we localize strings. 

<img width="212" alt="screen shot 2018-01-03 at 2 56 44 pm" src="https://user-images.githubusercontent.com/3409578/34537420-58019942-f096-11e7-8b5b-d042ebfdbaaf.png">

Going forward should hide this label (if possible) rather than deleting it as we may want to use that content in the future. We need to think more about these menus (e.g. Add Sprite via Library, Upload, Camera, Paint Editor) and come up with better solution. Possibly one that opens/collapses (we could show the text when the menu is opened).

### Current locations
Sprite Info Area
- [ ] Add Sprite via Library

Stage Info Area
- [ ] Add Backdrop via Library

Extensions
- [ ] Add Extension via Library

Vector Editor
- [ ] Add Costume via Library
- [ ] Add Blank Costume (coming soon)

Sound Editor
- [ ] Add Sound via Library
- [ ] Record Sound via Microphone

### Concept sketch with text labels hidden
![hidden-labels](https://user-images.githubusercontent.com/3409578/34537529-c9af67e0-f096-11e7-9825-794cb6847a68.png)

**Comment by apple502j** [comment]
+1

**Comment by carljbowman** [comment]
Tracking / Resolving in https://github.com/LLK/scratch-gui/issues/1166
