### ISSUE TITLE
Add resizing elements

### ISSUE THREAD

**Issue by SimaKyr** [LLK/scratch-gui#1165]
Bag if change size browser to small and open music editor
![screenshot_2](https://user-images.githubusercontent.com/28606130/34562463-3679e7c2-f157-11e7-8e25-5bb121460d31.png)

### Steps to Reproduce
Change size browser
Open editor music

### Operating System and Browser
Firefox 57 Windows 10

**Comment by towerofnix** [comment]
This seems to be fixed now?

![Screenshot showing that buttons don't overflow anymore](https://user-images.githubusercontent.com/9948030/35017480-657617a8-faf3-11e7-9e38-d6f8babb3748.png)

(Firefox 58, Debian testing.)

**Comment by vutondesign** [comment]
Also seems to be fixed for me. (MacOS High Sierra, Chrome 63.0.3239.132)

**Comment by Kenny2github** [comment]
@vutondesign if you look at the labels, this is a firefox-only issue - mind testing it there?

**Comment by vutondesign** [comment]
@Kenny2github Whoops, sorry.
