### ISSUE TITLE
Things what can be

### ISSUE THREAD

**Issue by Kukushenok** [LLK/scratch-gui#1168]
### 1. Clone ID (that's most important)
That's do: if you need to cat fighting with mice, cat will go to clone of [Mouse] with Id (ID). 
### 2. All keyboard's keys trigger 
Shift,tab,e.c.t 
### 3. File operations (import (import zone), save). 
Can save the screenshot of the progect and text. I think, with these things Scratch will be better

**Comment by thisandagain** [comment]
Hi @Kukushenok it's pretty hard to understand some of these. Can you please split these requests into three separate issues? Please provide as much description as possible.
