### ISSUE TITLE
Pressing escape in fullscreen should exit fullscreen

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#1171]
### Expected Behavior

Pressing the escape key while viewing a project in fullscreen should switch back to the editor.

### Actual Behavior

Nothing happens; the escape key is not handled.

### Steps to Reproduce

Enter fullscreen (click the right-most button above the corner of the stage) and press escape.

### Operating System and Browser

Debian (testing), Firefox 58.

**Comment by kyleplo** [comment]
Also, can there be a way to do full-fullscreen, like in https://davidwalsh.name/demo/fullscreen.php

**Comment by josiahneuberger** [comment]
@kyleplo #1195 implements requested behavior with 'escape' key; however, your request in comments for a 'F11' type full-screen mode should probably be made in a separate issue. Thanks for pointing out the missing functionality.

**Comment by thisandagain** [comment]
Resolved in #1195
