### ISSUE TITLE
Extension "Some Blocks" don´t  show in develop

### ISSUE THREAD

**Issue by marcotchella** [LLK/scratch-gui#1176]
### Expected Behavior
In window "Extension Library" show extension "Some  Blocks"

_Please describe what should happen_
show extension  icon "Some  Blocks"  and allow load extension

### Actual Behavior
Don´t  show extension  icon "Some  Blocks"

### Steps to Reproduce
1 - https://llk.github.io/scratch-gui/develop/
1 - Click "Extensions"

### Operating System and Browser
Windows 10, Chrome 63

**Comment by thisandagain** [comment]
@marcotchella We do not have an extension in Scratch 3.0 called "Some Blocks" can you please clarify what you are looking for?

**Comment by hedgehog125** [comment]
I think the "Some Blocks" you are talking about used to be there but they were probably just to test extension worked, and have now been removed.

**Comment by marcotchella** [comment]
yes, is a extension example:
https://github.com/LLK/scratch-gui/blob/develop/src/examples/extensions/example-extension.js

I have used to learn about  to work/develop extensions
I could find documentacion on how associate a custom extension to GUI window Library Extensions.
Could you give some directions?
Thanks

**Comment by thisandagain** [comment]
@marcotchella I see. That was simply a test of the extension interface. This is currently not a supported API, but we are working on documentation and hope to share something with the community soon.
