### ISSUE TITLE
Sound recording doesn't work on 0.0.0.0 local demo

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-gui#1193]
@ericrosenbaum @rschamp - as we discussed on Thursday:

When using a local demo (http://0.0.0.0:8601/) chrome doesn't ask for microphone permission, so the sound editor cannot record. First I get this message, and then disabled recorder: 
![image](https://user-images.githubusercontent.com/15109618/34648064-24be0522-f39b-11e7-8771-d7aa3b41e41e.png)
![image](https://user-images.githubusercontent.com/15109618/34648065-2f821fe8-f39b-11e7-9cfb-dc9afdf4fd5e.png)

* Replacing the link to http://localhost:8601/ solves the issue, which is enough for me - just documenting it per your request. 

Chrome version: 63.0.3239.132

**Comment by paulkaplan** [comment]
Yeah, thanks for reporting this. Chrome allows getUserMedia only from https domains, but has an exception for `localhost` (but not `0.0.0.0`).
