### ISSUE TITLE
Add sprite icon overlaps sprites in sprite pane

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-gui#1194]
![image](https://user-images.githubusercontent.com/15109618/34650434-01a69c28-f3ca-11e7-997f-8daa7e1a7615.png)

For example see: https://llk.github.io/scratch-gui/#195369953 (or any project with many sprites)

**Comment by thisandagain** [comment]
Tracking system-level issue in https://github.com/LLK/scratch-gui/issues/1166
