### ISSUE TITLE
Won't load if there's a large project

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#1199]
### Expected Behavior

It should load.

### Actual Behavior

Page not responding error.

### Steps to Reproduce

https://llk.github.io/scratch-gui/#189424083 

### Operating System and Browser

Android 5.1.1 on Silk Browser

**Comment by amazinigmech2418** [comment]
Sometimes it just never loads.

**Comment by amazinigmech2418** [comment]
Never mind. It loaded. The scripts could use intervals instead to decrease lag though.

**Comment by towerofnix** [comment]
Have you tried [a larger project](https://github.com/LLK/scratch-gui/issues/1174)? :)
