### ISSUE TITLE
Design for sprite, costume, and backdrop libraries

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-gui#12]
The implementation should be at a point where some design can be applied, and this is needed for the prototype.

**Comment by thisandagain** [comment]
Let's split this into two passes:
- [ ] Phase I: Basic library for February play test
- [ ] Phase II: Full library design

**Comment by lifeinchords** [comment]
TODO: Safari overflow scroll in SpriteSelector pane

**Comment by lifeinchords** [comment]
TODO: 6 sprites per row, vs 4

**Comment by lifeinchords** [comment]
- [ ] Add a bit of space between rows in sprite library. On hover reveals them side overlapping

**Comment by lifeinchords** [comment]
Related: #89

**Comment by lifeinchords** [comment]
- [ ] Need space between items across rows on hover
- [ ] Width on items are not the same across rows

![12e8bd40-f1e1-11e6-882f-d0b89627eb8a](https://cloud.githubusercontent.com/assets/716168/23275561/f370e310-f9d4-11e6-88ce-2188fc33e154.png)

**Comment by lifeinchords** [comment]
@carljbowman @thisandagain Should we close this? I think these are covered in  LLK/scratch-gui#355 and LLK/scratch-gui#391

**Comment by carljbowman** [comment]
@lifeinchords - Yeah, let's go ahead and close this issue as we have completed an initial pass. We can create issues as needed as we continue to explore filtering and sprite tag/pack stuff.
