### ISSUE TITLE
How are blocks loaded as extensions? (I am writing a forum topic for 3.0 extensions)

### ISSUE THREAD

**Issue by ZenithRogue** [LLK/scratch-gui#1204]
I would like to know how extensions are loaded into the editor, along with where the files are within the repository.  I am currently writing a topic explaining the differences between 3.0 and 2.0 extensions.

**Comment by xys1836** [comment]
I am not very sure the details of how the things work but I could tell you that something I found.

When you click extension icon in the bottom-left corner, you will see the extension library like music, pen. This is defined in the following file:
`scratch-gui/src/lib/libraries/extensions/index.js`
You could add your own library in this file. 

Then you have to realize your library in the follow directory:
`scratch-vm/src/extensions/`
Pay attention on the following codes in the `index.js`, make sure `EXTENSION_ID` return the same string as it in the `scratch-gui/src/lib/libraries/extensions/index.js` 
```
static get EXTENSION_ID () {
        return 'music';   // this should be same as **extensionURL** in the scratch-gui. 
    }
```

Last you have to register the extensions to `extension-manager.js.` This is in 
`scratch-vm/src/extension-support/extension-manager.js`
You need to import(require) the file in `scratch-gui/src/lib/libraries/extensions/index.js` 

Hope this could help you .

**Comment by CoolGames** [comment]
I am not a programmer but am trying to get a working Experimental Extension added to offline.
Working on [ScratchX](http://scratchx.org/?url=https://rolandcom.github.io/gokeys-scratch-extension/gokeys_extension.js#scratch)

It is for new [Firmware Ver.1.21](https://rolandcom.github.io/gokeys-scratch-extension/) at announcement during NAMM 2018 on January 9, 2018

![scratch 3 - extension added - screenshot_2018-02-03_10-53-54](https://user-images.githubusercontent.com/149711/35768904-c5635d70-08d0-11e8-89f9-2b8d277bb734.png)

I am not sure the files are syntactically correct named and located and imported
 in `scratch-gui/src/lib/libraries/extensions/index.js`

Can you give link to topic for details ?
