### ISSUE TITLE
() of () reporter is always missing the last sprite

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1207]
<img width="983" alt="screen shot 2018-01-08 at 12 47 42" src="https://user-images.githubusercontent.com/2855464/34684199-50b973fa-f472-11e7-87a7-7191d0aa6d11.png">

When you first have only the cat and stage, the dropdown only has the stage.
When you add another sprite, say Apple, now the dropdown only shows the stage and Sprite1 (the cat)

**Comment by griffpatch** [comment]
I don't think two sprites should ever 'have' the same name?

**Comment by hedgehog125** [comment]
It could be to do with the sprite names, the names might be used as ids and if they have the same id there's going to be problems.
In Scratch 2.0 if you create a sprite with an name that's already being used then it will add a 2 to the end (or increase the number at the end), this mechanic doesn't seem to exist in the current version so that could be the problem.

**Comment by sjhuang26** [comment]
Yes, and duplicate sprite names are not allowed in Scratch 2 (if you try to change the sprite name to another sprite's name, it won't let you). This behavior should be added to Scratch 3.

**Comment by fsih** [comment]
I discovered that this bug actually doesn't have to do with the duplicate names. I broke out the duplicate names bug to https://github.com/LLK/scratch-gui/issues/1209.

**Comment by amazinigmech2418** [comment]
Maybe the JS array is manipulated incorrectly. Maybe it doesn't show the full array because of a miscalculated loop count. (Should be array.length in for loops)

**Comment by fsih** [comment]
It was actually a mistake that the "() of ()" block had a checkmark next to it. It's working as intended that the sprite that's currently selected is missing from the dropdown for that sprite. This will be resolved by removing the checkbox. Sorry for the confusion everyone.

**Comment by amazinigmech2418** [comment]
OK.
