### ISSUE TITLE
Sprites should never have the same name

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1209]
When you add the same sprite from the library twice, you can have 2 sprites with the same name.
<img width="983" alt="screen shot 2018-01-08 at 12 47 42" src="https://user-images.githubusercontent.com/2855464/34699951-43ce86a8-f4ae-11e7-84df-689da3047b91.png">
Those same named sprites are then confused with each other. For instance, this reporter only reports the stats of one of the objects name 'bell' no matter which 'bell' you pick.

The expected behavior from Scratch 2.0:
One of them should automatically be renamed to 'bell2'.

**Comment by fsih** [comment]
Same issue for backdrops

**Comment by thisandagain** [comment]
This will likely block resolving the SB3 export format. Assigning to @kchadha given that is in scope for this month.
