### ISSUE TITLE
() of () block calls Stage _stage_

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1211]
### Expected Behavior

It should say Stage

### Actual Behavior

It says \_stage\_
<img width="242" alt="screen shot 2018-01-08 at 20 19 29" src="https://user-images.githubusercontent.com/2855464/34701247-0e588f30-f4b5-11e7-8ec8-cdd13671d1a4.png">
That's the secret name. No one must know the secret name.

### Steps to Reproduce

Check the checkbox next to the () of () reporter

### Operating System and Browser

Mac OSX Chrome

**Comment by amazinigmech2418** [comment]
This should be pretty easy to fix... You just need to change the display code for the monitor to say Stage if the stage is selected.
