### ISSUE TITLE
New "Make a Block" in palette appears off screen

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-gui#1212]
### Expected Behavior

When you "Make a Block", the new block is added to the left hand blocks palette and is easily visible.

### Actual Behavior

The new block is added to the left hand blocks palette, but is off the bottom of the screen.

![image](https://user-images.githubusercontent.com/6737342/34710903-0d912a8e-f515-11e7-989f-5259aa8858ac.png)

I wonder if a the blocks palette should have 2/3rds of a screen of blank scrollable area added to the bottom such that when a specific block category is selected, it's relevant blocks can be fully scrolled to the top of the blocks palette? Otherwise the highlighted blocks section is also never correct (see how the Operators category is currently highlighted in the screenshot? I wanted to be on the My Blocks one, but you can't select it - Adding dead space at the bottom of the blocks palette would allow me to scroll them such that you could select the category and keep it selected.)

### Steps to Reproduce

* Scroll to the 'My Blocks' category
* Click "Make a Block"
* Click "OK"

### Operating System and Browser

Windows PC running Chrome

**Comment by ivanixgames** [comment]
Submitted PR https://github.com/LLK/scratch-gui/pull/1439
