### ISSUE TITLE
How will we support Scratch 2.0 projects that have multiple "current ()" monitors?

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1218]
In Scratch 2.0, it was possible to have monitors for "current second," "current minute," "current hour" etc. simultaneously. In 3.0, they will all share 1 monitor. We should figure out how projects with multiple monitors will behave in 3.0.

https://scratch.mit.edu/projects/196922245/

- When I open the project in 3.0, will all of the different monitors still be present, or will they all merge into 1 monitor?
- If I change the value on the dropdown on the "current ()" block, will all of the monitors change? One of them? Will a new monitor appear?

**Comment by CatsAreFluffy** [comment]
Currently, no monitors appear.

**Comment by tomrow** [comment]
I think it should behave like Scratch 1.4's (sensor[v]) block in that it makes a new monitor when the dropdown is changed and the checkbox is ticked.

**Comment by heyitsmeuralex** [comment]
> In 3.0, they will all share 1 monitor

Why

**Comment by towerofnix** [comment]
@heyitsmeuralex In Scratch 3.0 it's only possible for each block to have one monitor (not multiple). There's not a big "why" *design* reason for this - it's just an effect of how it was programmed. (NB: I don't actually know how monitors are programmed, I'm just guesstimating this. :P)
