### ISSUE TITLE
Scratch 3.0 alignment not working, and design suggestion

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-gui#1220]
### Expected Behavior

_Please describe what should happen_
![image](https://user-images.githubusercontent.com/11379161/34755199-5f81992a-f577-11e7-95d2-aca3d010b982.png)

That should be aligned better.

Also, I think that the nav bar text color doesn't go well with its background.

### Actual Behavior

_Describe what actually happens_
The text gets partially hidden
### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Go to https://llk.github.io/scratch-gui
### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

Windows 10 Edge newest I assume Screen Resolution: 1536 X 864

**Comment by GreenBayRules** [comment]
UPDATE: 

I found out that if you put the blocks in to the code editor without connecting them, this happens:
![image](https://user-images.githubusercontent.com/11379161/34755322-32d13060-f578-11e7-8610-5649c05e9d81.png)

But, if you connect one or more blocks, it goes back to normal:
![image](https://user-images.githubusercontent.com/11379161/34755341-4fae033e-f578-11e7-8a3d-356eff180dce.png)


Then if you click the zoom in button once:
![image](https://user-images.githubusercontent.com/11379161/34755355-613b944a-f578-11e7-9ea6-86737690b027.png)
After first zoom in, it's fine.

Zooming out just screws the whole thing up:
![image](https://user-images.githubusercontent.com/11379161/34755382-822dd050-f578-11e7-9203-afa30e343101.png)
As you can see, some of the text is outside of the block.

I think this a problem with my Screen Size, you might have to test on a screen with my size (1536 x 864)

**Comment by chexbox** [comment]
The menu bar will have white text, when the button is enabled.

**Comment by paulkaplan** [comment]
FWIW I can repro this in Edge 14, but not in the most recent version of Edge (16).

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-blocks/pull/1340
We do not support < Edge 16
