### ISSUE TITLE
Selected block category moves up when switching sprites

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#1221]
### Expected Behavior

When switching sprites, the selected block category should remain the same.

### Actual Behavior

When the sprite is switched, the selected category shifts up. Often, it shifts up by one category, but not always, and I think this is related to the size of the category (e.g. how many blocks are in it) and the size of the browser window.

### Steps to Reproduce

Open a new project.
Select or scroll to the `Events` category.
Switch to the `Stage`. Observe that the `Sound` category is now selected.
Switch back to `Sprite1`. Observe that the `Looks` category is now selected.
...and so on

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by rachel-fenichel** [comment]
Is this specific to switching between the stage and a sprite?  It could be because there are no move blocks for the stage.

**Comment by kchadha** [comment]
It happens when switching between any two sprites, not just the stage and a sprite. However, it does not happen when switching between the blocks editor and the costume editor for example.

**Comment by thisandagain** [comment]
![untitled3](https://user-images.githubusercontent.com/747641/36382872-72542698-1558-11e8-901a-0fbd0768b761.gif)

**Comment by kyleplo** [comment]
I think this is an intentional feature to select a random category when sprite changes. But I think this should be removed.
