### ISSUE TITLE
Property menu of "[property] of [sprite]" should differ for sprite vs stage

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1224]
### Expected Behavior

In Scratch 2.0, the contents of the property menu of the sensing block "[property] of [sprite]" change depending on whether a sprite or the stage is selected:

![screen shot 2018-01-10 at 5 04 23 pm](https://user-images.githubusercontent.com/567844/34798016-5ba51e88-f628-11e7-9fd0-71bc94212d17.png)

![screen shot 2018-01-10 at 5 04 32 pm](https://user-images.githubusercontent.com/567844/34798015-5b9c553c-f628-11e7-8d31-dfccea8c0ccd.png)

This actually kind of a sticky problem, because we need to keep this same menu non-droppable. Our current way ([here](https://github.com/LLK/scratch-gui/blob/f129c30af170a670a8909d3de921e0210a7ccd02/src/lib/blocks.js#L10)) of dynamically updating menus can only update shadow blocks that are menus, which are droppable. So I'm not sure how we will implement this.

### Actual Behavior

Currently the property menu just contains all the options, some of which do not make sense.

**Comment by amazinigmech2418** [comment]
I think an if statement is needed to decide what is in the menus.  Maybe something like this:
var menu;
if (dropdown === "Stage") {
menu = ["backdrop #", "backdrop name", "volume"];
} else {
menu = ["x position", "y position", "direction", "costume #", "costume name", "size", "volume"];
}

**Comment by towerofnix** [comment]
This is resolved now, so the issue can be closed.
