### ISSUE TITLE
Implement "share the love"

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1234]
### Expected Behavior

When you drag a block over a sprite, it will add to that sprite

### Actual Behavior

Nothing happens
### Steps to Reproduce

Drag any block over the stage or other sprite

**Comment by hedgehog125** [comment]
I don't think the alternative would work that well, as it would make moving assets between sprites a lot slower because you would have to put it into your backpack (which might already have a lot in) then take it out in the other sprite and then delete it from the backpack.

**Comment by thisandagain** [comment]
Thanks for filing this @kyleplo. We call this feature "share the love". We currently have it scheduled for completion in February.

**Comment by towerofnix** [comment]
Note that share the love also works with sounds and costumes (even dragging sprite costumes to the stage, and stage backdrops to sprites).

**Comment by fsih** [comment]
Thanks @towerofnix! This issue will just be for the feature where you drag blocks to other sprites. We will implement sharing costumes and sound later. I've filed https://github.com/LLK/scratch-gui/issues/1470 for it.
