### ISSUE TITLE
Variable Watchers are not in stage on fullscreen

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1235]
### Expected Behavior

Variable watchers should stay in the same place in or out of fullscreen

### Actual Behavior

They move to the corner instead of stay in the same spot.
#### Normal
![image](https://user-images.githubusercontent.com/31634240/34845578-56b27a5e-f6e3-11e7-8a9f-325a5a891af0.png)
#### Fullscreen
![image](https://user-images.githubusercontent.com/31634240/34845597-682e3b24-f6e3-11e7-8154-8c403de53bcd.png)

### Steps to Reproduce

Create a variable, show it, and open fullscreen

### Operating System and Browser

Chrome 63 Windows 10 Desktop

**Comment by thisandagain** [comment]
@fsih

**Comment by paulkaplan** [comment]
Moving this to february milestone because the dupe issue @rschamp made was in february. Not sure if this is right though, @rschamp?

**Comment by thisandagain** [comment]
Thanks @paulkaplan. Sorry about not catching the dupe during triage.

**Comment by CatsAreFluffy** [comment]
Seems like it's not having its position/size updated when fullscreen is pressed. If you look closely you can see that its relative position to the corner is the same.

**Comment by paulkaplan** [comment]
Yeah it looks like the `.monitorWrapper` class is the wrong size in fullscreen. It should be the same size as the stage. Here are screenshots:

![image](https://user-images.githubusercontent.com/654102/36428223-5bc84646-161d-11e8-9bb8-b115023df2a0.png)
![image](https://user-images.githubusercontent.com/654102/36428226-5d09dede-161d-11e8-8c50-243593abc6d2.png)

I'm going to mark this as help-wanted.

**Comment by mrjacobbloom** [comment]
Could this be moot per #1397?

**Comment by Narulacodes** [comment]
@paulkaplan  What needs to be fixed, where is the code, and when is this due?
I'll be Happy to take this! :)

If not, Then, Thanks for atleast Reading this. :)

**Comment by thisandagain** [comment]
#1397 is *huge* (and may not come until after 3.0 launches) so this fix should not be blocked by that work.

**Comment by fsih** [comment]
@Narulacodes see https://github.com/LLK/scratch-gui/issues/1235#issuecomment-366987622 for Paul's recommended fix. The monitor-wrapper css is in the file scratch-gui\src\components\stage\stage.css

We don't really have due dates. Thanks for helping!

**Comment by Narulacodes** [comment]
@fsih,  do i csn tskr this. thx

**Comment by Narulacodes** [comment]
Where is the source code, what part needs to br fixed in the sorce code/?
