### ISSUE TITLE
Feedback form can't be scrolled on iPad

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#1239]
### Expected Behavior

_Please describe what should happen_

Opening the feedback from and scrolling the form should scroll the form

### Actual Behavior

_Describe what actually happens_

It seems to try to scroll the background.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

I can reproduce this on an actual iPad and the iOS Simulator like so.

![ipad-feedback](https://user-images.githubusercontent.com/654102/34880094-58450fd6-f77d-11e7-9087-8c4d1f6c2206.gif)

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

iPad and the iOS Simulator. Tried on touch chromebook but didn't get the same problem (it scrolled the feedback form just fine).

/cc @mewtaylor I think you made that form? Not sure if this is an issue on google form side or our side.

**Comment by Kenny2github** [comment]
That's probably a problem with the way you embed the form - not really to do with the form itself.

**Comment by amazinigmech2418** [comment]
Actually @Kenny2github , the embedding probably isn't the problem. It's probably that the scroll feature doesn't apply to the form, but does apply to the rest of the page. What would be needed would be a way to read the scrolling and access the scroll in the (probably) iframe embedding.

**Comment by thisandagain** [comment]
This also appears to be happening on our Chrome OS testing devices with touch screens.
