### ISSUE TITLE
Instrumentation for "hard crash" events?

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#1246]
@thisandagain I think it might be a good idea to put some additional GA instrumentation at the error boundary that appears after a hard crash. We'll have other kinds of error reporting, but that might give us a more easily digestible stat since we know exactly what kind of experience it is associated with, whereas with other uncaught errors it is difficult to immediately know the severity. I think having a backstop metric like that would be really helpful for me. A good place would be, for example, here https://github.com/LLK/scratch-gui/blob/develop/src/containers/error-boundary.jsx#L18

**Comment by thisandagain** [comment]
👍
