### ISSUE TITLE
Selecting multiple costumes at a time.

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-gui#1248]
A feature that I sometimes with existed is the ability to select multiple costumes at the same time because it can be frustrating to do something, for example, getting the whole alphabet or parts of the same animation.

**Comment by mrjacobbloom** [comment]
Like shift-click to select multiple in order to delete them or drag between sprites/into the backpack? That could be useful but would break the current paradigm where the selected costume is also the one skinning the sprite

**Comment by CosmicWebServices** [comment]
Yep exactly

**Comment by kyleplo** [comment]
Like #867

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/867
