### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by yijq** [LLK/scratch-gui#1251]
### Expected Behavior

- all packages install successfully

### Actual Behavior

- can't find scratch-vm: 's version: 0.1.0-prerelease.1515771598-prerelease.1515771612, like this:
![error img](https://user-images.githubusercontent.com/26025157/34932373-897761ac-fa0d-11e7-8ccb-d270861cdd1c.png)

### Steps to Reproduce

- `git clone https://github.com/LLK/scratch-gui.git`
- `cd scratch-gui`
- `cnpm i`  ( ps: I'm in China, use `cnpm i` , its registry is ` https://registry.npm.taobao.org/`, I try `npm i` too.)
- After `cnpm i`, the error is emited. I delete `"scratch-vm": "0.1.0-prerelease.1515771598-prerelease.1515771612"` in `package.json`, and run `npm i --save-dev scratch-vm@latest`,after install successfully,  the version is `^0.1.0-prerelease.1500304222` , and the prosject can't start successfully.

### Operating System and Browser

- Window 10  v1073
- node v8.9.1
- npm v5.5.1

**Comment by yijq** [comment]
And run `npm search scratch-vm` , result like this
```
[{
	"name": "scratch-vm",
	"description": "Virtual Machine for Scratch 3.0",
	"maintainers": [{
		"username": "scratch",
		"email": "scratchr-sysadmin@media.mit.edu"
	}],
	"version": "0.1.0-prerelease.1515771598-prerelease.1515771612",
	"date": "2018-01-12T15:41:06.284Z"
}, {
	"name": "jaspy",
	"description": "a Python VM written entirely from scratch in JavaScript with some unique features",
	"maintainers": [{
		"username": "koehlma",
		"email": "mail@koehlma.de"
	}],
	"keywords": ["python", "interpreter"],
	"version": "0.0.4",
	"date": "2016-04-02T16:50:02.902Z"
}]
```

**Comment by yijq** [comment]
There are probably some problems in network environment or cnpm. I cleaned npm's cache , and connected to the Internet, and tried to install it again, it was successful !   
The commands ( the network environment is the Internet, there is limit in our network environment ):  
- `npm cache clean`
- `npm i`
- `npm start` and it will run successfully

But I still don't know why, cnpm or network? or others?

**Comment by thisandagain** [comment]
Great! Thanks for the follow-up @yijq. Sounds like it may have been a caching issue.
