### ISSUE TITLE
Fill Method in Vector Like Bitmap

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#1256]
### Expected Behavior

The fill should fill the shape, not anything surrounding the shape that has the same color.

### Actual Behavior

It fills all surrounding parts with the same color.

### Steps to Reproduce

It always happens

### Operating System and Browser

Windows 10 on Chrome

**Comment by thisandagain** [comment]
As much as I appreciate the request it's not quite possible to have a vector fill tool work exactly the same way as bitmap. We will get started on the bitmap paint editor soon which hopefully should provide an experience more consistent with what you might expect from other bitmap paint editors.

**Comment by amazinigmech2418** [comment]
OK.
