### ISSUE TITLE
Eraser Causes Fill Problems

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#1257]
### Expected Behavior

The eraser should erase stuff.

### Actual Behavior

The eraser also changes the fill in the shapes it's erasing

### Steps to Reproduce

1. Scribble in the backdrop.
2. erase stuff in a straight line across the shape you just made.
3. see that the eraser doesn't work right.

### Operating System and Browser

Windows 10 on chrome

**Comment by amazinigmech2418** [comment]
It not only causes things to fill that weren't already. It also inverts color, inverts what is filled and much more.

**Comment by amazinigmech2418** [comment]
@thisandagain @mewtaylor This is a pretty major costume editor problem.

**Comment by thisandagain** [comment]
This is an inherent problem with the nature of vector graphics and probably not something we will be able to resolve. I hope the bitmap editor once complete will be more to your liking.

**Comment by amazinigmech2418** [comment]
I think you could actually fix it in an easier way and just make it move vector nodes with the eraser. Let's say there's a 10 by 10 square. If part is erased, it will split into 2 layered 10 by 10 squares. Then each square will use an algorithm to move nodes to make a (0,0),(9,0),(0,9) triangle and its inverse needed to complete the square. Did you realize I used 9 instead of 10? That is to take into account the eraser size.

**Comment by amazinigmech2418** [comment]
@thisandagain

**Comment by amazinigmech2418** [comment]
Please respond. This is more info to prevent the glitch.

**Comment by amazinigmech2418** [comment]
@thisandagain Please respond. This is pretty important information. If not you, then @mewtaylor or someone else. Can you please re-open this?

**Comment by thisandagain** [comment]
I think you will need to be more clear in your description of the problem you are trying to solve. Can you please share screenshots (or ideally a GIF) of the issue you are seeing and a complete description of your proposed fix?

**Comment by amazinigmech2418** [comment]
Yes. I can @thisandagain . How do I make a GIF though?

**Comment by amazinigmech2418** [comment]
This is the original scribble in the costume editor: 
![1](https://user-images.githubusercontent.com/33498997/35167388-5720bd70-fd23-11e7-8e26-83cacd4a6e7f.PNG)
Then, I just used the eraser once.
![2](https://user-images.githubusercontent.com/33498997/35167392-61c502f4-fd23-11e7-9134-b2773f4824f8.PNG)
Then, I used it a third time.
![3](https://user-images.githubusercontent.com/33498997/35167404-6977e1f6-fd23-11e7-8fc6-4add50d3080d.PNG)
Some parts of the images were inverted. Some parts had random fills too.

**Comment by amazinigmech2418** [comment]
@thisandagain I just added 3 pictures.

**Comment by amazinigmech2418** [comment]
Sorry. Had to update. I accidentally labelled the 2nd time as the 3rd time since it was the 3rd screenshot.

**Comment by fsih** [comment]
This is probably a more complicated case of https://github.com/LLK/scratch-paint/issues/120, so I will close as a dupe.
