### ISSUE TITLE
Can't trim off the quiet part of 'zoop'

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1259]
### Expected Behavior

The soundless part gets removed

### Actual Behavior

The soundless part remains

### Steps to Reproduce

1. Add sound zoop
2. Try to trim off the soundless bit at the end
![zoop](https://user-images.githubusercontent.com/2855464/35002854-f8f005ec-fab8-11e7-8d21-40eb12d0f735.gif)

### Operating System and Browser
Windows 10 Chrome

**Comment by paulkaplan** [comment]
Rendering of the waveform has been fixed. Closing.
