### ISSUE TITLE
Try it button has a tryit tooltip

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1260]
### Expected Behavior

No tooltip (like other buttons)

### Actual Behavior

Try it! button has a 'tryit' tooltip.

### Steps to Reproduce

Hover over Try it button in the intro modal
![image](https://user-images.githubusercontent.com/2855464/35003825-06a9f60e-fabc-11e7-973c-df143ff83f91.png)

### Operating System and Browser
Everywhere

**Comment by vutondesign** [comment]
I'll have a go at this, I suspect it's because the Try It button has the "tryit" title assigned to it and the other button doesn't.

**Comment by mrjacobbloom** [comment]
Should this be re-opened in the meantime?

**Comment by paulkaplan** [comment]
Component no longer exists. Closing.
