### ISSUE TITLE
Remove "More options" in New Message dialog

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#1262]
### Current Modal
Repo: https://llk.github.io/scratch-gui/develop/
<img width="613" alt="screen shot 2018-01-16 at 1 14 58 pm" src="https://user-images.githubusercontent.com/3409578/35004815-6dbc0d98-fabf-11e7-8fa8-b735a2a75b08.png">

The modal suggests that were will be "More options" in the future for Broadcasts. This will set false expectations around later features. We do not plan to add "More options" to broadcasts.

cc @thisandagain - We may want to pull this out before the Preview. Defer to you. Feel free to remove critical label.

**Comment by mrjacobbloom** [comment]
Or you could add more features! Add narrowcasts, which are like broadcasts but not as wide

**Comment by thisandagain** [comment]
Resolved in #1311
