### ISSUE TITLE
Cannot drag sprites on the stage after duplicating a sprite

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#1263]
### Expected Behavior

1. Add some sprites
2. Duplicate one of the sprites
3. Drag and reposition sprites on the stage

### Actual Behavior

Sprites lose the ability to be repositioned on the stage after a sprite is duplicated in the sprite list.

### Steps to Reproduce

1. Add a few sprites
2. Right-click a sprite in the sprite list and click “Duplicate”
3. Sprites on the stage are no longer draggable

### Operating System and Browser

OS: Windows Pro 10 - V1709 - Build 16299.192
Browser: Microsoft Edge 41.16299.192
Repo: https://llk.github.io/scratch-gui/develop/

and 

OS: macOS 10.11.6
Browser: Chrome Version 63.0.3239.132
Repo: https://llk.github.io/scratch-gui/develop/

-----

cc @thisandagain - We may want to pull this out before the Preview. Defer to you. Feel free to remove critical label.

**Comment by paulkaplan** [comment]
Was fixed in https://github.com/LLK/scratch-vm/pull/894. Looks like it just hasn't been brought in yet.
