### ISSUE TITLE
(Discussion) "JSON Hacked" Projects

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#1267]
_This is not a bug, request, or question. Just discussion._

In Scratch 2.0, we can "hack the project with JSON". For example, "define %m.list" makes a block with list dropdown. Also we can put (var) in "Set () to []" block, like "Set (var) to []".

This technology is very popular, and a lot of projects use it.

However, Scratch 3.0 doesn't allow them. All inputs are put in scratch-blocks, so hacked projects are broken. ST promised that "All Projects work in 3.0".

I also know that hacking is not recommended, but it became popular and they are very useful - For Pen Projects, Cloud List,etc...

What do you think?

**Comment by apple502j** [comment]
https://github.com/LLK/scratch-vm/issues/355
see also

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/767

**Comment by ihadastrok** [comment]
You can't hack scratch 3.0 project's json because st was too lazy to do it (sorry scratch team please I promise I will never do it again)
