### ISSUE TITLE
Uncaught DOMException

### ISSUE THREAD

**Issue by the349** [LLK/scratch-gui#1268]
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22

**Comment by thisandagain** [comment]
Thanks for filing @the349. I believe this is actually in the `scratch-blocks` repo, but we can keep it here until we have an investigation / repro.

**Comment by paulkaplan** [comment]
Yup, filed on scratch-blocks several times, closed there as being tracked in upstream blockly https://github.com/google/blockly/issues/299
