### ISSUE TITLE
Costume and Sounds tabs are not selectable on ChromeOS via touch

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#1283]
### Expected Behavior

- You should be able to select either the "Costumes" or "Sounds" tab via touch on Chrome OS

### Actual Behavior

- You can only select these tabs via the mouse cursor

### Operating System and Browser

Chrome OS | Samsung Chromebook Pro

**Comment by paulkaplan** [comment]
This was fixed by #1732
