### ISSUE TITLE
Handle browser caching.

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#1287]
Currently we rely on the browser refreshing files based on the `Last-Modified` header. This doesn't seem to be enough for Safari, however.

Options:
* Find which headers Safari will respect and use those (may be difficult to discover/configure)
* Use a new filename for all the files during each release, so new content is guaranteed between releases (will cause a proliferation of files in both gh-pages and S3 unless we figure out how to mitigate)
* Others?

**Comment by rschamp** [comment]
On www we use `no-cache` when we upload to S3, so that browsers will use the `ETag` header (an MD5 hash of the file contents) to decide whether they need to update or not: https://github.com/LLK/scratch-www/blob/900207da2da7e4b1371fa18ac91e28aff087a222/Makefile#L4  I think it would be worth trying that out to see if it works for Safari before switching to distinct filenames.  I agree that it's rare for browsers to actually always do the right thing, however we have had some success in convincing them to handle deploys correctly on www.

The trouble with distinct filenames for assets is that it would be hard to know which files are still necessary between deploys. We don't want to delete everything, because if a browser has a previous version of `index.html` cached, then it will still want access to a previously uploaded js file (the point of using this method).  So you're kind of forced to keep every version of every JS file.  This isn't a huge deal technically, since we can just throw whatever into the S3 bucket, but I think it would be less confusing if there was only a single version of the JS you could download and run.  However in a pinch I think this would be the easiest way to get Safari working well if the above doesn't work for whatever reason.

**Comment by CatsAreFluffy** [comment]
[Antimatter Dimensions](ivark.github.io) does this by adding a ?93 (or some other number) to the end of the script URL, which is enough to trick browsers into reloading it. Would probably be applicable here.
