### ISSUE TITLE
Whole border isn't highlighted blue when the second sprite visibility button is selected.

### ISSUE THREAD

**Issue by ktrvs** [LLK/scratch-gui#1288]
### Expected Behavior
When the second button from the sprite visibility section is selected, the whole border around it should turn blue like the first button does.

### Actual Behavior
The left section of the border does not turn not turn blue like the right section of the border does on the first button.

![show1](https://user-images.githubusercontent.com/26391179/35054025-97eec260-fba3-11e7-8801-ba4c92f1606d.png)
![show2](https://user-images.githubusercontent.com/26391179/35054026-9807b05e-fba3-11e7-9060-4d0b6d3e1314.png)

### Operating System and Browser
Mac OS 10.13.2 Chrome 63.

**Comment by thisandagain** [comment]
Resolved in #1293
