### ISSUE TITLE
Input fields work differently on Edge

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1294]
![image](https://user-images.githubusercontent.com/2855464/35066183-c317c8d4-fb9d-11e7-991d-ddb19193eb30.png)

Usually, blocks stretch when text is put into them.
On Edge, after a point, the text starts to scroll in a little window. Also an X appears which you can click to clear the field. (This happens everywhere, not just in blocks)

It doesn't feel too broken, just different? The padding looks a little off.

Windows 10 Edge

**Comment by thisandagain** [comment]
Moved to LLK/scratch-blocks#1349
