### ISSUE TITLE
Scratch 3.0 projects slowly get off sync

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1296]
### Expected Behavior

In 2.0, the actions of the duplicate sprites stay in sync

### Actual Behavior

In 3.0, the costume changes slowly get out of sync, and the speech bubble changes get out of sync faster.

Consider this project:
https://scratch.mit.edu/projects/198464093/
https://llk.github.io/scratch-gui/develop/#198464093

They get out of sync especially fast in Edge, but it happens on other browsers too.
![ezgif com-optimize](https://user-images.githubusercontent.com/2855464/35071086-90a2c632-fbad-11e7-9266-caf35c84e3af.gif)

### Steps to Reproduce

Have a sprite that repeats something every x seconds
Duplicate it
Run them both at the same time

### Operating System and Browser

Windows 10 Edge

**Comment by thisandagain** [comment]
Moved to LLK/scratch-vm#904
