### ISSUE TITLE
'set costume' block's menu on workspace becomes out of sync with costume in paint editor

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#1305]
### Expected Behavior

The 'set costume' block on the workspace should only display costumes that are contained in the sprite.

### Actual Behavior

The costume list that is displayed in the 'set costume' block that is placed on the workspace can get out of sync with the list of costumes in the paint editor. This is consistent with 2.0 behavior.

Costume List in Block
<img width="1280" alt="screen shot 2018-01-18 at 4 41 32 pm" src="https://user-images.githubusercontent.com/3409578/35122950-8084b5dc-fc6e-11e7-85c4-f31024a5bd54.png">

Costume List in Paint Editor 
<img width="1280" alt="screen shot 2018-01-18 at 4 41 24 pm" src="https://user-images.githubusercontent.com/3409578/35122978-922649f4-fc6e-11e7-942f-42c0eda6a544.png">

### Steps to Reproduce

1. Drag out a set costume block 
2. Open the Paint Editor
2. Add some costumes 
3. Delete the original costumes
4. Return to blocks

### Operating System and Browser

OS: ChromeOS
Browser: Chrome

& 

OS: macOS
Browser: Chrome

**Comment by hedgehog125** [comment]
Maybe it could mark it if it doesn't exist? Highlight it red and have a hover message / right click message?

**Comment by thisandagain** [comment]
Agreed that this is a `wont-fix`. Will backlog for now as I'm happy to discuss post release.
