### ISSUE TITLE
Language menu renders differently in Firefox

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#1308]
![image](https://user-images.githubusercontent.com/1786240/35123892-11b78180-fc72-11e7-9931-3f70ddef944a.png)

### Operating System and Browser

Mac OS 10.12.6, Firefox 57.0.2 (64-bit)

**Comment by dgnball** [comment]
Is this a duplicate of #816 ?

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/816
