### ISSUE TITLE
I want to scratch contribute code, recently want to implement stage screenshot function, but access to the canvas of the stage, after using canvas. ToDataURL () to obtain images of base64, but the picture is black, and I want to ask whether my train of thought have a problem, what method can you recommend

### ISSUE THREAD

**Issue by cyTD** [LLK/scratch-gui#1316]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by hedgehog125** [comment]
It could be that you're trying to capture what's onstage before the rendering or something.

**Comment by cyTD** [comment]
But how do I know that the stage is already rendered?

**Comment by thisandagain** [comment]
@cyTD In order to get data from the stage, you will need to access the renderer which is based on WebGL. You can find the source code here: https://github.com/llk/scratch-render

**Comment by liukonghe** [comment]
Have you solved your problem? I have the same problem.

**Comment by liukonghe** [comment]
问题我已经解决了只需要在canvas. ToDataURL ()之前执行renderer.draw();

**Comment by cryanis** [comment]
@liukonghe 请问执行renderer.draw()是不是需要引入 scratch-render

**Comment by luofei614** [comment]
@liukonghe @cryanis    我怎么调用了  renderer.draw()  也还是不行。

**Comment by fsih** [comment]
Maybe this feature of Chrome can help you do what you want:
https://umaar.com/dev-tips/156-element-screenshot/
