### ISSUE TITLE
ReferenceError: TouchEvent is not defined

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#1317]
TouchEvent is not always defined. Reported via Sentry. Doesn't seem to be a crashing error. 

```
ReferenceError: TouchEvent is not defined
  at value (/lib.min.js:35:75460)
  at l (/lib.min.js:1:8318)
```

**Comment by towerofnix** [comment]
Going to quote my (duplicate-of-this) issue:

> The "bad" line follows:
>
> https://github.com/LLK/scratch-gui/blob/fc388b63c89559c4f25d069db84b49912b7a77fc/src/containers/stage.jsx#L203
>
> Any non-left click makes the second condition, `e instanceof TouchEvent`, run. According to [the compatibility section for TouchEvent](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent#Browser_compatibility), it looks like TouchEvent is defined *only* on Windows systems. Yikes!

**Comment by amazinigmech2418** [comment]
@towerofnix Browsers define the JavaScript functions, not the system.

**Comment by amazinigmech2418** [comment]
@towerofnix That says that Windows can now use it. The touch events need to be processed by the browser from the actual event in the hardware. They just updated the event reader.

**Comment by regcole** [comment]
change the line to 
```javascript
   if (e.button === 0 || window.TouchEvent && e instanceof TouchEvent) {
```
