### ISSUE TITLE
Map and Set polyfill may be required

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#1318]
Reported via Sentry on an android browser. Not sure if this browser is supported, but I remember react 16 mentioning needing to polyfill Map and Set for older browser support (they were talking about <IE11 though). 

https://reactjs.org/blog/2017/09/26/react-v16.0.html#javascript-environment-requirements

```
ReferenceError: Map is not defined
```

```
ReferenceError: Set is not defined
```

**Comment by thisandagain** [comment]
@paulkaplan Looking at caniuse, it looks like this may be the Android browser < 4.4 (which we won't support). Can you get any more details about the user agent?

https://caniuse.com/#feat=es5

**Comment by paulkaplan** [comment]
Good point. Closing
