### ISSUE TITLE
Importing a project and reloading "blocks" tab crashes

### ISSUE THREAD

**Issue by Tau5** [LLK/scratch-gui#1327]
### Expected Behavior

Show the sprite blocks normally

### Actual Behavior

Crash

### Steps to Reproduce

1. Import a project (Eg.: `https://llk.github.io/scratch-gui/develop/#199231742`)
2. Select a sprite
3. Go to another tab (Eg.: Sounds)
4. Go to blocks tab

### Operating System and Browser

Firefox 57.0.4 Windows 10 (64 Bits)

**Comment by hedgehog125** [comment]
I can repo in Chrome 63.0.3239.132 on Mac OS X.

**Comment by paulkaplan** [comment]
Hmm can you give the exact steps you took to repro (which sprite you clicked, etc.) I cannot repro this. here is what I am seeing:

![block-rendering](https://user-images.githubusercontent.com/654102/35687751-885e7ea8-073d-11e8-8c0c-b4488f629922.gif)

**Comment by paulkaplan** [comment]
I'm going to close this since I cannot repro it.
