### ISSUE TITLE
Private variables only updating when sprite is selected

### ISSUE THREAD

**Issue by Tau5** [LLK/scratch-gui#1329]
### Expected Behavior

Update the private variable display always

### Actual Behavior

Only updating when sprite is selected

### Steps to Reproduce

1. Create/Import a scratch 2.0 Project with 2 sprites, 1 with a private variable always changing (Like change [var] by 1)
2. Import to Scratch 3.0
3. Run the program and show the private variable
4. Note that when you select the sprite without the private variable the display is not updating

### Operating System and Browser

Firefox 57.0.4 Windows 10 (64 Bits)

**Comment by kchadha** [comment]
@fsih any thoughts on this?

**Comment by paulkaplan** [comment]
Fixed
