### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by wenyiweb** [LLK/scratch-gui#1338]
### Expected Behavior
npm install
### Actual Behavior

`
npm WARN deprecated babel-preset-es2015@6.24.1: ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm ERR! code ETARGET
npm ERR! notarget No matching version found for scratch-vm@0.1.0-prerelease.1516215511-prerelease.1516215524
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'scratch-gui'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kevin\AppData\Roaming\npm-cache\_logs\2018-01-25T11_19_09_620Z-debug.log

`

**Comment by CosmicWebServices** [comment]
@wenyiweb it may help to have the full log...

**Comment by wenyiweb** [comment]
@CosmicWebServices I have solved the problem , thanks

**Comment by wooden1985** [comment]
@wenyiweb how to solve?

**Comment by ballballl** [comment]
> @CosmicWebServices I have solved the problem , thanks

how to solved ? orz

**Comment by benjiwheeler** [comment]
@wenyiweb When you solve a problem you post, please please post what your solution was! Even if it was just an obvious error, it's helpful to know what went wrong, and what might have been missing from instructions.
