### ISSUE TITLE
Using "%s" as an argument name causes unexpected behavior

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#1347]
### Expected Behavior

- Creating a custom procedure with "%s" as an argument name should work

### Actual Behavior

- Causes a number of exceptions that lead to instability

### Steps to Reproduce

- Click the "Make a block" button
- Enter `%s` as the argument name
- Click "ok"

### Demo
![untitled3](https://user-images.githubusercontent.com/747641/35454537-66b4675e-029c-11e8-921c-e70dd9452d13.gif)

### Operating System and Browser
Mac OS 10.13.2  |  Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by amazinigmech2418** [comment]
Whoa! This is a critical issue! Someone could name it that and destroy the whole editor block menu! @thisandagain Please add the label "critical".

**Comment by amazinigmech2418** [comment]
It also causes Scratch 3 to crash if you add an extension such as music.

**Comment by amazinigmech2418** [comment]
%b does it too.

**Comment by Kenny2github** [comment]
@amazinigmech2418 I would assume that %s, %b, %m.asdf, and %i (or is it %n?) would do the same thing, they're all argument placeholders

**Comment by amazinigmech2418** [comment]
@Kenny2github It actually does it for anything starting with "%" even if it isn't an argument placeholder.

**Comment by rachel-fenichel** [comment]
This is a scratch-blocks problem.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-blocks#1368
