### ISSUE TITLE
"Run without screen refresh" label is not properly aligned with checkbox

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#1349]
### Expected Behavior

- Label should be next to the checkbox

### Actual Behavior

- Label has extra padding in relation to the checkbox

![image](https://user-images.githubusercontent.com/747641/35454869-c4c53b7e-029d-11e8-9604-9dc9b34a525e.png)

### Steps to Reproduce

- Open "Make a Block" modal

### Operating System and Browser

Mac OS 10.13.2  |  Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by Narulacodes** [comment]
I can repro this from chromeOs, Chrome Version 63.0.3239.132 (Official Build) (64-bit) the same thing

**Comment by amazinigmech2418** [comment]
This should be pretty easy to fix...

**Comment by amazinigmech2418** [comment]
I think what needs to be done is probably update the CSS to change either the width of the checkbox or the padding/margins of the text.

**Comment by amazinigmech2418** [comment]
I just submitted a PR for this! Hope it helps!

**Comment by paulkaplan** [comment]
Thanks for helping us find the issue @amazinigmech2418. I mentioned on your PR, but I'll put it here too: this actually needs to be fixed as an update to https://github.com/LLK/scratch-gui/pull/1217, so I'm removing help-wanted and assigning to @fsih the original author of that PR.
