### ISSUE TITLE
Color picker block does not work with touch devices

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#1350]
### Expected Behavior

_Please describe what should happen_

Expect to be able to use the eyedropper on a touch device. It isn't 100% clear what the interaction should be, but at the very least it seems like touching down on the sprite should select a color. It doesn't seem to even do that. Testing on an iPad, I can't use the eyedropper in either the blocks/stage or the costume editor. 

### Actual Behavior

_Describe what actually happens_

It seems to dismiss the eyedropper tool without actually choosing a color.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

iPad, try using the eyedropper. 

I'm putting "needs discussion" on this to see if there is a slightly better interaction we can imagine for touch, and what the priority of that is. /cc @carljbowman @thisandagain 

----

Updated title because the eyedropper for the costume editor was fixed to work with touch. Now it is just the stage

**Comment by hedgehog125** [comment]
I can repo in chrome devtools device toolbar.

**Comment by kyleplo** [comment]
@hedgehog125 Me too! There is also a warning in the console.

**Comment by hedgehog125** [comment]
Maybe it should only select when you release your finger from the screen and while you drag it behaves as if you move a mouse.

**Comment by mrjacobbloom** [comment]
That sounds too easy to screw up, I'd rather it keeps the zoom open until you do some other interaction to close the dropper

**Comment by hedgehog125** [comment]
Hmm... maybe there could be a tick underneath the highlighter circle?
