### ISSUE TITLE
Implement long-press for context menus on touch devices

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#1354]
### Expected Behavior
In order to support tablets completely, we can't rely on "right-click". Tablets don't have mouse.

### Actual Behavior
It relies on it.

### Steps to Reproduce
Right-Click. (maybe a menu is shown)

### Operating System and Browser
Firefox 58 and Windows7 HomePremium SP1 64bit

**Comment by vutondesign** [comment]
A lot of things would have to be changed for this, but it is a good point. However, I can't think of many ways that you could implement a right-click style menu while keeping everything as simple.

**Comment by kyleplo** [comment]
Double-click instead?

**Comment by rachel-fenichel** [comment]
FYI scratch-blocks uses long-press for right-click behaviour on touch devices.

**Comment by picklesrus** [comment]
Here are the different context menus I know about:
- blocks (works, except on edge. Tracking here: https://github.com/LLK/scratch-gui/issues/3026)
- workspace (works)
- sprite tile (doesn't work)

**Comment by paulkaplan** [comment]
Closing since we have long press anywhere we have a custom context menu
