### ISSUE TITLE
Not now button should redirect to Scratch 2.0 editor

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-gui#1359]
### Expected Behavior

The not now button should redirect to the Scratch 2.0 editor.

### Actual Behavior

Nothing happens, just remains disfunctional. If it is not supposed to go to the Scratch 2.0 editor, then it should go somewhere else, I don't see the point of a button that doesn't do anything:
![scratchgui](https://user-images.githubusercontent.com/11379161/35487297-d3c1b962-042e-11e8-892e-270a913a98b0.gif)

### Steps to Reproduce

Go to https://preview.scratch.mit.edu and click the button ;)

### Operating System and Browser

Ubuntu 16.04 Chrome latest

**Comment by GreenBayRules** [comment]
Sorry for messed up colors, ubuntu tints everything purple for some reason

**Comment by ktrvs** [comment]
I actually doesn't do *nothing*, if you were on a page and clicked a link/button that took you to the preview, the "Not Now" button will take you back to that original page.

**Comment by amazinigmech2418** [comment]
It works on https://llk.github.io/scratch-gui/ . It must be a location error with the https://preview.scratch.mit.edu/ version.

**Comment by Kenny2github** [comment]
Yeah, the "Not Now" button is more of a "back" button. @amazinigmech2418 it works if I click [this link](https://preview.scratch.mit.edu) and then click the button - I don't think the domain has to do with it.

**Comment by GreenBayRules** [comment]
I'll take this

**Comment by Narulacodes** [comment]
Actully, It works for me. It takes me back to my last tab

**Comment by GAME-STUDIO-SCRIPT** [comment]
this https://beta.scratch.mit.edu/ html error code: ERR_TUNNEL_CONNECTION_FAILED or DNS_PROBE_FINISHED_NXDOMAIN
