### ISSUE TITLE
Add menu items to play sound blocks for "add sound..." and "record sound..."

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1368]
Scratch 2.0 has a menu item "record..." in the play sound blocks:

<img width="167" alt="screen shot 2018-01-29 at 3 57 54 pm" src="https://user-images.githubusercontent.com/567844/35534034-3eb4ca1e-050d-11e8-8383-93111c814f07.png">

We should consider adding options like "add sound..." and "record sound..." to the start sound and play sound blocks, which directly open the sound library or sound recorder modal.

**Comment by mrjacobbloom** [comment]
Should the costume menu parallel that as well?

**Comment by kyleplo** [comment]
Should we include more options:

**Sound**
- record
- add sound
- upload
- surprise

**Costume/Backdrop**
- paint
- add costume/backdrop
- upload
- selfie
- surprise
