### ISSUE TITLE
Stage is blurred in full screen mode

### ISSUE THREAD

**Issue by filips123** [LLK/scratch-gui#1374]
### Expected Behavior
Sprites and Backdrop shouldn't be blurred.

### Actual Behavior
Sprites and Backdrop are not clear and sharp, but blurred in the full screen mode of Stage.
Images:
Scratch 2 https://screenshots.firefox.com/kBNqDEA4MCuDRxcv/scratch.mit.edu
Scratch 3 https://screenshots.firefox.com/wlZogoQPFxFBk77O/preview.scratch.mit.edu

### Steps to Reproduce
Add some Sprites and Backdrops to Stage and click Full Screen Mode.

### Operating System and Browser
Windows 10, Firefox 58, Chrome 63 and 64

**Comment by hedgehog125** [comment]
Can repo in Chrome 64.0.3282.119 (Official Build) (64-bit) on Mac OS X 10.11.6.

**Comment by paulkaplan** [comment]
@cwillisf seems like a https://github.com/LLK/scratch-render/pull/232 needs a follow-up to include the stage itself being resized?
