### ISSUE TITLE
The block input is displayed across all the other windows when is selected.

### ISSUE THREAD

**Issue by filips123** [LLK/scratch-gui#1375]
### Expected Behavior
The block input shouldn't be displayed across all the other windows when is selected.

### Actual Behavior
The block input is displayed across all the other windows when is selected.
Here is image: https://screenshots.firefox.com/3IrP7r6VNC1EoMnG/localhost

### Steps to Reproduce
Create Block with Input. Select Input. Click on Extensions.

### Operating System and Browser
Windows 10, Firefox 58, Chrome 63

**Comment by paulkaplan** [comment]
Closing as a duplicate of https://github.com/LLK/scratch-gui/issues/1129
