### ISSUE TITLE
Testing for Animate a Name Playtest

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#138]
This issue is for organizing test cases/ progress/ questions for the upcoming play-test.

### From discussion in Editor Weekly meeting
These tasks may need to be separate issues; that's up to however the people owning each item want to handle it. For my own organizational purposes, I am including them here.

- [ ] “Testing Studio” - Trim list to focus on specific bugs (Andrew)
- [x] Search for “Animate Your Name” to build a testing list (Julia)
  - https://scratch.mit.edu/studios/3826456/projects/
- [ ] Design & Engineering team stress testing (All)
- [ ] Import and land the serialization / deserialization from Moran (??)

### Questions

1) It sounds like we won't be able to delete sprites by the play-test. However, the cat sprite (default with each new project) is not particularly useful for Animate a Name. You also can't re-order the sprites yet, so the easiest/ most natural place to start a script if you're totally new to Scratch (the cat scripting area) is probably not where you want to start a script for Animate a Name, generally speaking.

2) When you highlight multiple bits of text, you can end up apparently dragging all of them around (they don't actually move, but the image is shown while dragging) - I don't know if we want that?

![out](https://cloud.githubusercontent.com/assets/1320456/23468279/6293a352-fe6e-11e6-82a4-5cfc5a32d2d9.gif)

3) Clicking sprites in sprite pane causes scroll in block pane (bug)

![out2](https://cloud.githubusercontent.com/assets/1320456/23468303/766f1ef6-fe6e-11e6-9032-8fc1c20871fa.gif)

4) Personally, I find it a little hard to use Scratch when I can see so few blocks in the block pane at a time; I end up scrolling a lot

<img width="255" alt="screen shot 2017-02-28 at 2 05 20 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468340/8ef87b16-fe6e-11e6-9ccb-4a641078ca63.png">

5) How do I duplicate a stack of blocks? I can get it to duplicate a block or a loop & its contents, but not the whole stack from hatblock down.

6) Say button does not work - I think that is known

<img width="1277" alt="screen shot 2017-02-28 at 2 36 51 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468397/b52ff6a6-fe6e-11e6-9fa1-293a1af7185e.png">

7) Adjusting browser console causes block pane to scroll (bug)

![out3](https://cloud.githubusercontent.com/assets/1320456/23468412/bfeb7322-fe6e-11e6-8848-3144e2089e69.gif)

8) Opening browser console causes the sprite / backdrop plus buttons to move up the page (bug)

<img width="1280" alt="screen shot 2017-02-28 at 2 43 43 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468428/c8bc352c-fe6e-11e6-930c-eb39833be5aa.png">

9) I dragged a script into another sprite and it (script) was deleted : (

10) What should happen if you put in a value like 15-?

<img width="1280" alt="screen shot 2017-02-28 at 2 47 19 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468500/004a521c-fe6f-11e6-9f7d-08c8a4971718.png">

11) Why am I getting an error about the say block, when I no longer have the say block anywhere?

<img width="1280" alt="screen shot 2017-02-28 at 2 48 27 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468502/00558cb8-fe6f-11e6-9b1b-8b33081d0a55.png">

12) If you have a script controlled by "when space hit" hat block, if you edit a value in the stack, should you have to make that field inactive - click elsewhere - in order for hitting space to start the stack?

13) Something weird happened with location; -150 and 150 were not symmetric around 0, then I changed value of effect block from fisheye to whirl, and the sprite moved to be symmetric

<img width="505" alt="screen shot 2017-02-28 at 3 09 42 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468516/00d92550-fe6f-11e6-94ae-008035ba9e09.png">
<img width="891" alt="screen shot 2017-02-28 at 3 09 56 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468507/00820a5e-fe6f-11e6-8cd2-dc429eb36d90.png">
<img width="792" alt="screen shot 2017-02-28 at 3 10 03 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468505/00686e32-fe6f-11e6-8a8f-89fb73883392.png">

14) Something weird happened with fisheye/ whirl; setting the value to 0 didn't remove the effect until I changed fisheye to whirl

The effect looks like whirl, but I only have fisheye set for this sprite:
<img width="1280" alt="screen shot 2017-02-28 at 2 51 15 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468504/00651052-fe6f-11e6-9233-9f8c6fa229d2.png">
Changing fisheye -> whirl in the set [effect] to 0 block returned the sprite to normal:
<img width="1277" alt="screen shot 2017-02-28 at 2 59 52 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468498/00408354-fe6f-11e6-8485-6656a76003a3.png">

15) It is hard to use the 3.0 editor with the browser console open : )

16) Blocks wrap around other hat blocks (that they are not connected to) (bug)

<img width="512" alt="screen shot 2017-02-28 at 3 03 00 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468501/0054416e-fe6f-11e6-9be4-a4a3b6181233.png">

17) The plus sign over the backdrop pane opens the costume library? (???)

18) Choosing a costume... what happens to my existing costume? How do I get to the various costumes of a single sprite? (Can I only use the blocks to move through them/ see them?)

<img width="930" alt="screen shot 2017-02-28 at 3 07 18 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468513/00ae1cac-fe6f-11e6-8aac-4b00d30e430c.png">

19) Where are all the "story" letter sprites?

20) What happened to abby-d's legs? They are gone?

<img width="216" alt="screen shot 2017-02-28 at 3 05 06 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468503/005fd57e-fe6f-11e6-84ed-6f5067646843.png">

21) I guess I can't add backdrops? How do I add backdrops?

22) Mosaic effect sometimes returns to 0 effect automatically? Why does mosaic stop changing the value? Result of the bug Andrew mentioned that we found during the playtest? 

![out4](https://cloud.githubusercontent.com/assets/1320456/23468497/003edd6a-fe6f-11e6-85e8-70e7562a9c48.gif)

23) I refreshed the page and got an error (play was interrupted by call to pause); not sure if this is expected or not (doesn't seem unreasonable that this would interrupt project playing, but not sure if that's how we want to handle it).

<img width="1280" alt="screen shot 2017-02-28 at 3 19 05 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468517/011bfc36-fe6f-11e6-8be8-54bf743e18d1.png">

24) New sprite won't necessarily show up (I think this is the issue Eric mentioned); when I clicked Next Costume it did show up

<img width="1280" alt="screen shot 2017-02-28 at 3 23 00 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468514/00d17206-fe6f-11e6-8e03-e89a8018c8f6.png">

25) For large values, the script stops working, e.g. I can update how many degrees to turn in a playing forever loop and it will slow down at "1" and go fast at "100", but at "1000000000000000000000" the sprite will stop moving altogether. The limit seems to be "1000000000000000000" for the angle to turn block. The limit for the set size to % block seems to be "10000".

26) In general, it's not obvious to me when to expect a sprite to reset to what it looked like before I started a script for the first time, vs. when I expect it's current state to be preserved. This is true in 2.0 as well.

**More pics of the fisheye/ whirl stuff**

This effect on the J looks like whirl, although whirl isn't being used here. It is being used on another sprite iirc.
<img width="1279" alt="screen shot 2017-02-28 at 3 10 18 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468506/00791db8-fe6f-11e6-8bff-53539e482e83.png">

This effect looks like fisheye.
<img width="841" alt="screen shot 2017-02-28 at 3 10 33 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468511/00a11750-fe6f-11e6-873e-c2c14badfe21.png">

On stopping the project, for some reason the J looks like it has "whirl" on it; resetting fisheye effect to 0 doesn't remove the appearance. But changing fisheye -> whirl in the set to 0 block does.
<img width="469" alt="screen shot 2017-02-28 at 3 10 44 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468510/009fc198-fe6f-11e6-9ffc-362e981f646d.png">
<img width="490" alt="screen shot 2017-02-28 at 3 10 53 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468508/008973fc-fe6f-11e6-87b1-e28b16f8caa6.png">
<img width="452" alt="screen shot 2017-02-28 at 3 10 58 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468512/00a0ea82-fe6f-11e6-99f2-09b020fd48a3.png">
<img width="1012" alt="screen shot 2017-02-28 at 3 11 01 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468509/009ef70e-fe6f-11e6-953b-c3cbf5de8f6d.png">

### Notes

- Pay attention to large values (weird behaviour from playtest)
- (Potentially) after internal playtest, after drag-and-drop is merged, make sure to test thoroughly
- Pay attention to changing values in an active script (weird behaviour from playtest)

**Comment by jwzimmer** [comment]
Studio with animate a name projects that cover a range of functionality: https://scratch.mit.edu/studios/3826456/projects/.

I invited Scratch Team members to curate so they can add projects if they would like to.

**Comment by jwzimmer** [comment]
I removed the projects from the studio that use the "say" or "think" blocks, and the ones that use the  ask/ answer/ username blocks.

1) 147825825
- Project works
- No console output!
2) 103401819

**Comment by thisandagain** [comment]
#### The following already have issues filed
1. #57 
6. https://github.com/LLK/scratch-vm/issues/307
8. https://github.com/LLK/scratch-gui/issues/86

#### My recommendation for which of these items to transform into issues
2, 3, 4 (sorry @carljbowman), 5, 9, 11 (needs repro), 12 (needs repro), 14 (needs repro), 20 (needs repro), 22 (needs repro), 23, 25 (needs repro)

#### Couple I don't quite understand
13, 16

#### These are resolved
17, 18, 19, 21, 24

**Comment by jwzimmer** [comment]
**Clarification on no. 13 & 16:**

13) Something weird happened with location; -150 and 150 were not symmetric around 0, then I changed value of effect block from fisheye to whirl, and the sprite moved to be symmetric. When I switched fisheye --> whirl, the J sprite repositioned itself to be the same distance from W as the Z is.
<img width="714" alt="screen shot 2017-03-02 at 2 34 58 pm" src="https://cloud.githubusercontent.com/assets/1320456/23524454/b4d46a08-ff58-11e6-8ff3-44b53364b610.png">

16) Blocks wrap around other hat blocks (that they are not connected to/ in a script with)
<img width="481" alt="screen shot 2017-03-02 at 2 35 28 pm" src="https://cloud.githubusercontent.com/assets/1320456/23524453/b4d1dae0-ff58-11e6-9f4c-bd9b99a15f13.png">

**Comment by thisandagain** [comment]
Thanks @jwzimmer. I updated my comment above.

**Comment by jwzimmer** [comment]
I created cases for the issues @thisandagain mentioned and linked to them in [this comment](https://github.com/LLK/scratch-gui/issues/138#issuecomment-283754387).

Additional cases:
- https://github.com/LLK/scratch-gui/issues/173

**Comment by jwzimmer** [comment]
### From internal play-testing

27) Errors from @christanbalch:
![screen shot 2017-03-03 at 2 40 28 pm](https://cloud.githubusercontent.com/assets/1320456/23568223/93e53730-0027-11e7-82db-8b5ce43b2bd5.png)
![screen shot 2017-03-03 at 2 40 23 pm](https://cloud.githubusercontent.com/assets/1320456/23568225/93e70196-0027-11e7-8d6e-1ca44f8ae2d0.png)
![screen shot 2017-03-03 at 2 40 11 pm](https://cloud.githubusercontent.com/assets/1320456/23568226/93ed29a4-0027-11e7-9886-baf47a640624.png)
![screen shot 2017-03-03 at 2 40 01 pm](https://cloud.githubusercontent.com/assets/1320456/23568224/93e6e76a-0027-11e7-9f77-feeb95363467.png)
![pasted image at 2017_03_03 03_32 pm-1](https://cloud.githubusercontent.com/assets/1320456/23568321/f85bc940-0027-11e7-9adf-0b5f2f9f97ec.png)
![pasted image at 2017_03_03 03_32 pm](https://cloud.githubusercontent.com/assets/1320456/23568322/f85f40c0-0027-11e7-891f-47ac3ddc49dd.png)

28) Errors from @seotts. She was making about 300 clones.
![pasted image at 2017_03_03 03_01 pm](https://cloud.githubusercontent.com/assets/1320456/23568248/ad72034a-0027-11e7-9893-957b4bddc640.png)

29) Errors from Saskia.
![screen shot 2017-03-03 at 3 08 20 pm](https://cloud.githubusercontent.com/assets/1320456/23568296/e1f80240-0027-11e7-8487-2d07978560af.png)

30) In @christanbalch's project, the lines of the squares are smaller for the cloned squares versus the non-clones. There's no pen size blocks in the scripts.
![screen shot 2017-03-03 at 3 35 27 pm](https://cloud.githubusercontent.com/assets/1320456/23568186/72bc831a-0027-11e7-9f18-22558f7649f9.png)
![screen shot 2017-03-03 at 3 35 17 pm](https://cloud.githubusercontent.com/assets/1320456/23568187/72bca1a6-0027-11e7-9b2a-c3f3b1ff3fd1.png)

**Comment by jwzimmer** [comment]
I think this is a known issue, but since I'm not seeing the case for it, logging it here:

On the first load & play of a 2.0 project in 3.0, the costumes aren't loaded in time to be displayed as expected. On subsequent cycles of next costume/ forever loop, the costumes are displayed as expected. You can get back to the initial behaviour by refreshing the page.

![out](https://cloud.githubusercontent.com/assets/1320456/23804697/fab0ed7c-0588-11e7-9bd8-83fd31e45ee0.gif)

**Comment by jwzimmer** [comment]
**Notes from the cards**
- Block language color effect/ effect color doesn't match what the block says in the editor
- If you just follow the cards, you have a pile of letters for most of the walkthrough (since they're all located by default on top of each other in the middle of the stage)
- If you go from left to right, the 2.0 steps are add backdrop, then add sprite, but the 3.0 steps are add sprite, then add backdrop, leaving you in the backdrop scripting area when you go to add blocks in the next step
- Presence of "when this sprite clicked" for backdrops makes it harder to notice that you're in the backdrop scripting area
- You can't cycle through costumes or backdrops without the blocks; maybe make sure the playtesters are aware of that so they aren't confused by not being able to see them in the UI anywhere
- Some of the 3.0 cards have backdrops, some don't; seems kind of random?
- The locations (x, y) in the blocks don't update automatically in the block pane (I think this is known)

**Comment by jwzimmer** [comment]
### From internal play-testing 3/13/17

* Pick random is default between 0-10, dropping that into Play note doesn't work until you change the range. I was confused by until i added a new Play note block and saw the default there was 60 
*

**Comment by jwzimmer** [comment]
I noticed the difference in between how many stacks can fit in the script pane at default size in 2.0 vs. 3.0. Carl said this is an intentional change. 👍 

<img width="564" alt="screen shot 2017-03-13 at 2 42 18 pm" src="https://cloud.githubusercontent.com/assets/1320456/23870165/f4f2bf9e-07fb-11e7-972c-382856a1eee2.png">
<img width="556" alt="screen shot 2017-03-13 at 2 42 07 pm" src="https://cloud.githubusercontent.com/assets/1320456/23870166/f50d5c46-07fb-11e7-8c0b-d2686b524abd.png">

**Comment by jwzimmer** [comment]
Before closing, last-minute testing:
- I created another animate a name project; it worked as expected
- I made a project using every block; no errors in console, although timer button doesn't work

Closing this case since we're frozen and this has been tested!
