### ISSUE TITLE
Some sprites don't show on the stage after creation

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#139]
### Expected Behavior

- Sprites should appear on the stage after being added from the library

### Actual Behavior

- Some sprites (e.g. "Apple") do not appear on the stage after being added from the library

### Steps to Reproduce

- Create new project
- Add a new sprite
- Select "Apple"

### Operating System and Browser

Mac OS 10.12.3 Chrome Version 56.0.2924.87 (64-bit)

**Comment by SillyInventor** [comment]
Duplicate of #54 ?

**Comment by thisandagain** [comment]
Ah! I thought this was a dupe. Thanks @SillyInventor
