### ISSUE TITLE
Pressing space in sound editor should play selected sound

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#1396]
### Expected Behavior

Pressing space in the sound editor should play the selected sound (if there is one).

### Actual Behavior

Pressing space doesn't do anything. In order to play the sound, I have to select (via tab or click) the play button, then press enter (pressing space while the play button is focused doesn't do anything).

### Steps to Reproduce

Open the sound editor and select a sound. Press the space bar.

### Operating System and Browser

Firefox 59.0, Debian.

**Comment by paulkaplan** [comment]
Implemented!
