### ISSUE TITLE
Selecting a clone put the paint editor into a weird state

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1405]
### Expected Behavior

Maybe you shouldn't be able to "select" a clone at all, or maybe it should cause the parent sprite to be selected (see https://github.com/LLK/scratch-gui/issues/638 and https://github.com/LLK/scratch-gui/issues/721) 

### Actual Behavior

Selecting a clone of the default sprite while the paint editor is open puts the paint editor into a weird state, with the costume rendered in the corner of the editor, the wrong name shown ("backdrop1"),  and only one costume instead of two:

![clone-select-paint-bug](https://user-images.githubusercontent.com/567844/35818997-7d1fd7c8-0a6f-11e8-95e5-38d0387f994f.gif)
 
### Steps to Reproduce

Create a clone of the default sprite
Switch to paint editor
Click and drag the clone to select it

### Operating System and Browser

Mac OS 10.13.2 Chrome 64.0

**Comment by kchadha** [comment]
Also, editing the costume of a clone moves all the clones on the stage as if re-positioning everything.

**Comment by paulkaplan** [comment]
Closed by making dragging select the original sprite.
