### ISSUE TITLE
Slightly moving a sprite switches to it, making it hard to activate "when sprite clicked"

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-gui#1408]
(Noticed in microworlds playtesting)

clicking imprecisely on a sprite on the stage many times moves it a tiny bit, which makes this sprite be chosen, and does not activate "when sprite clicked" - I feel like it's much more sensitive than 2.0 in that.  

This happens to many kids, especially younger ones using a trackpad... 

Maybe consider adding a threshold for drag actions? 

(Similar to #1328, but with a different cause)

**Comment by hedgehog125** [comment]
That would be useful, also you can drag sprites in full screen which is also annoying.

**Comment by hedgehog125** [comment]
By a drag threshold do you mean as a delay or a minimum movement before it's a drag? Also, maybe adding the shadows that are in Scratch 2.0 might be useful as well because then you know when you're dragging.

**Comment by paulkaplan** [comment]
There is a time threshold for drags, it is the same as the threshold for considering two separate clicks as a single double click. And yeah that timing threshold is longer on scratch 3, as in, it allows two clicks separated by a longer amount of time to act like a double click. In scratch 2, it is 400ms [src](https://github.com/LLK/scratch-flash/blob/9fbac92ef3d09ceca0c0782f8a08deaa79e4df69/src/util/GestureHandler.as#L64) and in scratch 3 it is 500ms [src](https://github.com/LLK/scratch-gui/blob/develop/src/containers/stage.jsx#L204)

That timing difference was originally introduced by @rschamp in https://github.com/LLK/scratch-gui/pull/159. Nothing about it was mentioned in the PR, so I think it can safely lowered to 400ms. 

In terms of a distance threshold for drag actions, I cannot find that in scratch-flash, but I'm not the best with that codebase. There could be an explicit threshold, or it could be a combination of other factors.

**Comment by hedgehog125** [comment]
Ok.
