### ISSUE TITLE
List monitor should have same color as list blocks

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#1409]
### Expected Behavior

Title says it all.

### Actual Behavior

List monitor background color is the same as variable blocks.

### Steps to Reproduce

1. Create a new project
2. Create a new list
3. Observe the monitor color.

The fix for this will involve 
1. updating the color list to include a list category here https://github.com/LLK/scratch-gui/blob/develop/src/components/monitor/monitor.jsx#L7-L13
2. using the list category in the opcode label code https://github.com/LLK/scratch-gui/blob/develop/src/lib/opcode-labels.js#L40

**Comment by bartljak** [comment]
I submitted a pull request which has now been merged hence fixing this issue. Could someone close this issue?

**Comment by kchadha** [comment]
Thanks for the fix!
