### ISSUE TITLE
Auto-delete "message1" when a new message is created

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1412]
### Expected Behavior

When you create a message, the message titled "message1" will be deleted.
### Actual Behavior

"message1" is not deleted
 
### Steps to Reproduce

1. Create a message
2. Look at the message menu. There are 2 messages

### Operating System and Browser

Windows 10 Chrome 63.0.3239.132

**Comment by apple502j** [comment]
+1 - Of cource, if message1 is also used, it shouldn't be deleted.

**Comment by kchadha** [comment]
@kyleplo, thanks for reporting this! We decided that in scratch 3.0, it would be sufficient to remove unused messages when the workspace is reloaded (e.g. switching between the blocks/sound/costume editors, or switching sprites). 

This is definitely different from Scratch 2.0 behavior, and should be documented in the compatibility section of our wiki. I'll take care of that.

**Comment by apple502j** [comment]
I added to the Scratch Wiki :"Unused messages won't be deleted automatically."

**Comment by kchadha** [comment]
Updated scratch-vm compatibility wiki with info about [changes to broadcast messages](https://github.com/LLK/scratch-vm/wiki/Compatibility#broadcast-messages).
