### ISSUE TITLE
Full screen sprite not reacting to mouse over/click

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-gui#1416]
### Expected Behavior

When in full screen mode, sprites that detect mouse over and/or clicks should react appropriately

### Actual Behavior

Sprites react as if they are not getting the correct mouse coordinates and therefore do not receive mouse over events and click events.

### Steps to Reproduce

Load the following project:
https://preview.scratch.mit.edu/#170166098
Click green flag
Click full screen mode
Mouse over start/play sprite and attempt to click

### Operating System and Browser

macOS Sierra 10.12.6, Chrome 64.0.3282.140

**Comment by paulkaplan** [comment]
Interesting. It seems to work for me? also mac/chrome.

![game-fullscreen](https://user-images.githubusercontent.com/654102/35942548-070c99b6-0c24-11e8-940a-af7d17495954.gif)

**Comment by colbygk** [comment]
Unable to reproduce myself today... thanks!
