### ISSUE TITLE
"Bat1" and "Bat3" but no "But2"

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#1437]
### Expected Behavior
"Bat1" and "Bat2" exist.
### Actual Behavior
"Bat1" and "Bat3" exist.
### Steps to Reproduce
1.Open sprites library
### Operating System and Browser
windows7 homepremium 64bit sp1
firefox 58.0.1

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-gui/pull/1511
