### ISSUE TITLE
What is the newest iteration of the overall design sketch?

### ISSUE THREAD

**Issue by NitroCipher** [LLK/scratch-gui#1444]
What is the newest iteration of the overall design sketch? I would love to compare it to the current project.

**Comment by NitroCipher** [comment]
?????

**Comment by thisandagain** [comment]
That isn't really how we work. There isn't a "master" design file that governs the project but rather we work back and forth between design concepts and implementation until things feel right.

**Comment by NitroCipher** [comment]
Ok. I had seen a few concept guis pop up in the old s3.0 discussion
