### ISSUE TITLE
The return value of operator block is not accurate when input is a large number

### ISSUE THREAD

**Issue by xys1836** [LLK/scratch-gui#1446]
### Expected Behavior
(11111111111111111 + 1) should return a value of 11111111111111112
(11111111111111111 + 2) should return a value of 11111111111111113
(11111111111111111 + 3) should return a value of 11111111111111114

### Actual Behavior
(11111111111111111 + 1) returns 11111111111111112
(11111111111111111 + 2) returns 11111111111111114
(11111111111111111 + 3) returns 1111111111111111200

The result is not accurate when the input is a large number but not that large.
If the input number is quit large, the result will be convert to scientific notation.
It seems that there is a range of input that the result is neither converted to scientific notation, nor a correct value.

I think this is because of the limitation of javascript.
Is there any way or plan to fix it in the level of Scratch?

### Operating System and Browser
macOS High Sierra version 10.13.3
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by hedgehog125** [comment]
I can somewhat repo in Chrome 64.0.3282.140 (Official Build) (64-bit) on Mac OS El Capitan 10.11.6. Although, interestingly, I get different answers. (see the gif)
![scratch3 maths bug](https://user-images.githubusercontent.com/16543008/36142612-81a10556-10a0-11e8-9442-131b7dc6dec1.gif)

**Comment by xys1836** [comment]
@hedgehog125 
Thank you for your testing and reply. 
After I updated my Chrome from 63.0.3239.132 (Official Build) (64-bit) to Version 64.0.3282.140 (Official Build) (64-bit), I got the same value as yours. (11111111111111111 + 3) = 11111111111111116.

**Comment by hedgehog125** [comment]
I just tested it in the offline Scratch 2.0 editor and I got the same results.

**Comment by apple502j** [comment]
This is a problem of JavaScript, don't worry.

**Comment by mrjacobbloom** [comment]
![image](https://user-images.githubusercontent.com/2879020/36162358-73d69244-10a3-11e8-9ecf-53a27eee115e.png)
hmm....

**Comment by CatsAreFluffy** [comment]
Yep, it's FP rounding errors. Closing.
