### ISSUE TITLE
Input field doesn't follow block and layout of block broken after "undo"

### ISSUE THREAD

**Issue by xys1836** [LLK/scratch-gui#1447]
### Expected Behavior

The input field of a block should follow block when block is moved and the layout of block should not be broken. 

### Actual Behavior

The input field is separated from block and the layout of block is broken after "undo"(or c+z). (as shown in the screenshot Figure 5)

### Steps to Reproduce

To reproduce the actual behavior,
1. drag and drop a block (for example, repeat 10) in the middle of workspace, pay attention on the position of bottom scroll bar and right scroll bar. (Figure 1)
2. drag and drop another block (for example, glide 1 secs...) in the bottom-right corner of workspace, make sure the position of bottom scroll bar and right scroll bar is moved. (Figure 2)
3. drag the second block (glide 1 secs...) to connect to the first block (repeat 10), pay attention on the position of bottom scroll bar and right scroll bar, they are  back to the position in Figure 1. 
4.  click "undo" on context menu, (or c+z) to undo the last operation, the second block(glide 1 secs..) is back to the position in Figure 2. (Figure 4)
5. drag the second block to the top-left corner then drop the block. (Figure 5)
6. the input area does not follow the second block and the layout of second block is broken. (Figure 5)

![screen shot 0030-02-13 at 17 33 46](https://user-images.githubusercontent.com/5347269/36140546-02177550-10e5-11e8-8f65-15fb8d4cb80e.png)
Figure 1

![screen shot 0030-02-13 at 17 34 12](https://user-images.githubusercontent.com/5347269/36140549-0670593c-10e5-11e8-9816-d71bbd84b5b2.png)  
Figure 2  

![screen shot 0030-02-13 at 17 34 30](https://user-images.githubusercontent.com/5347269/36140557-0a095742-10e5-11e8-982f-d83661fc11d5.png)  
Figure 3  

![screen shot 0030-02-13 at 17 34 42](https://user-images.githubusercontent.com/5347269/36140564-0d64b076-10e5-11e8-9cc0-0d185d3b4e20.png)  
Figure 4  

![screen shot 0030-02-13 at 17 35 00](https://user-images.githubusercontent.com/5347269/36140571-0ffbf114-10e5-11e8-8f43-95cdacc461c0.png)  
Figure 5

### Operating System and Browser

macOS High Sierra version 10.13.3
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/1346
