### ISSUE TITLE
Make dynamic menus default to most recently added asset or sprite

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1452]
### Expected Behavior

It would be helpful if (some of) the dynamic menus that list sounds, costumes or sprites defaulted to the most recently added one.

For example, if you add the "duck" sound and return to the blocks, the "start sound" block in the blocks menu would display "duck". 

### Actual Behavior

Currently, these menus are generally sorted with the most recently added sprite or asset at the bottom. So for example after adding a sound, you need to open up the menu to get to it.

This situation is made more complex by the fact that some dynamic menus also have fixed entries (such as "random position"). We should consider the full set of blocks with dynamic menus and how to handle each of them.

**Comment by thisandagain** [comment]
Thanks for filing this @ericrosenbaum. I've seen this cause confusion / frustration so I agree that the behavior in Scratch 2.0 seems more ideal.

**Comment by ntlrsk** [comment]
@thisandagain I'm wondering if this is already on the Backlog or Icebox board? I looked but wasn't able to locate it. Thanks!

**Comment by towerofnix** [comment]
(@ntlrsk What's the "Icebox board"? I figure it means something like issues which are tracked as worth looking back to in the future, but also in the backest of the backlog. But I've never heard or seen of any actual "icebox board", i.e. a way to distinguish things from the rest of the Backlog milestone.)

**Comment by ntlrsk** [comment]
@towerofnix Good question - it's a list elsewhere of issues that are not yet planned.

**Comment by thisandagain** [comment]
@ntlrsk Good catch! *Added*
