### ISSUE TITLE
Right-clicking on stage area throws "TouchEvent is not defined" on Firefox, non-Windows

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#1457]
### Expected Behavior

No error is thrown, and the rest of the code past the "bad" line runs.

### Actual Behavior

The "bad" line follows:

https://github.com/LLK/scratch-gui/blob/fc388b63c89559c4f25d069db84b49912b7a77fc/src/containers/stage.jsx#L203

Any non-left click makes the second condition, `e instanceof TouchEvent`, run. This errors on the current version of Firefox Developer Edition, which does not have the `TouchEvent` object.

~~[`TouchEvent` *is* supported](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent#Browser_compatibility) by Firefox, so this is almost certainly an issue with Firefox, not scratch-gui (since `TouchEvent` does not exist on *any* pages, for me). Checking if this is an issue on non-Dev Edition Firefox would be good, as well as keeping an eye on this and checking if it's still an issue in future versions of Dev Edition.~~

According to [the compatibility section for TouchEvent](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent#Browser_compatibility), it looks like TouchEvent is defined *only* on Windows systems. Yikes!

### Steps to Reproduce

Right-click (or middle-click) on the stage.

### Operating System and Browser

Firefox Developer Edition, v59.0b9 (64-bit). Debian (testing).

This is also a problem on Firefox Nightly, 60.0a1 (2018-02-16), as well as Firefox ESR, 52.3.0. See my updated paragraph in "actual behavior".

**Comment by Narulacodes** [comment]
I can see the promblem. Yikes

**Comment by apple502j** [comment]
I got the same thing
Windows 7 64bit SP1 HomePremium
Firefox 59.0.1

**Comment by towerofnix** [comment]
Dupe of #1317, whoops!
