### ISSUE TITLE
Dialogs are modal now

### ISSUE THREAD

**Issue by CatsAreFluffy** [LLK/scratch-gui#1458]
### Expected Behavior

I can do stuff outside the dialog

### Actual Behavior

I can't do stuff outside the dialog

### Steps to Reproduce

Make a new variable

### Operating System and Browser

Mac OS 10.11.6 Chrome 60

**Comment by thisandagain** [comment]
This is not enough information to understand what you are reporting and/or asking.

**Comment by griffpatch** [comment]
Actually what he's getting at is that the pop up dialogs in scratch 2 are
NOT MODAL. So even when the dialog is popped up to create a new variable,
you can still continue scratching by dragging blocks etc in the
background... In fact you can open any number of create new variable
dialogs all at the same time.

In scratch 3, dialogs are modal and prevent the user interacting with the
page behind until the dialog is closed.

**Comment by thisandagain** [comment]
I see. Thanks for attempting to clarify. Yes, this was by design to help prevent confusion and some edge cases introduced by creating many dialogs (e.g. many "create variable" dialogs) in Scratch 2.0.

**Comment by CatsAreFluffy** [comment]
@griffpatch Yes, that. @thisandagain There are other ways to solve that issue, for example, cap the number of dialogs that can exist at once. I can only imagine the pain of trying to use 3.0 while offline and being spammed with modal dialogs.
