### ISSUE TITLE
Color selection sliders do not respond to touch events

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#1459]
### Expected Behavior

- Color sliders should be manipulable with a touch device

### Actual Behavior

- Color picker sliders do not work with touch input

### Steps to Reproduce

- Open color slider control on Chromebook

### Operating System and Browser

- ChromeOS | Chrome 62

**Comment by Narulacodes** [comment]
i can repro this from my chromeboiok. Yikes, this is a promblem

**Comment by hedgehog125** [comment]
Duplicate of #1350?

**Comment by thisandagain** [comment]
Whoops. Yes it is. Thanks @hedgehog125.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/1350
