### ISSUE TITLE
Scratch 3.0 is missing vector sprites from 2.0 library

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1464]
### Expected Behavior
All vector sprites (and associated costumes) in Scratch 2.0 should be available in 3.0

### Actual Behavior
Some vector sprites are missing from the Sprite Library in 3.0

### Steps to Reproduce

1. Visit High Seas example project in 2.0 (https://scratch.mit.edu/projects/56987002/#editor)
<img width="1651" alt="highseas2 0" src="https://user-images.githubusercontent.com/3812168/36449308-71dcc930-1658-11e8-8440-1e8b14f691df.png">
2. When trying to rebuild High Seas project in 3.0, you'll notice that the penguin sprite (and its 2 costumes) are not available in the Sprite Library
<img width="1586" alt="highseas3 0" src="https://user-images.githubusercontent.com/3812168/36449307-71c92f4c-1658-11e8-8150-8a1be5ae4849.png">

### Operating System and Browser
Chrome 64

**Comment by apple502j** [comment]
duplicate
https://github.com/LLK/scratch-gui/issues/1423

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/1423
