### ISSUE TITLE
Yellow outline around code stack less visible

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1466]
### Expected Behavior
The yellow outline around sprite in 3.0 should resemble the same level of contrast as it does in 2.0. This is useful for users/kids are to understand their code while it is being executed.

### Actual Behavior
The yellow outline around sprite in 3.0 is less visible making it unclear which code stack is being executed.

### Steps to Reproduce
1. Add code stack in 2.0, click the flag and observe the visible yellow outline around the code stack
<img width="1404" alt="2 0visible" src="https://user-images.githubusercontent.com/3812168/36450323-7f9d6c20-165b-11e8-9e8c-e2eb0b114466.png">
2.  Add same/similar code stack in 3.0 and observe less visible outline around the code stack
<img width="1452" alt="3 0notvisible" src="https://user-images.githubusercontent.com/3812168/36450335-872828a4-165b-11e8-872d-77a4998a7d51.png">

### Operating System and Browser
Chrome 64

**Comment by techwonder21** [comment]
2.0 -> https://scratch.mit.edu/projects/56987002/#editor
3.0 -> https://preview.scratch.mit.edu/#56987002

**Comment by towerofnix** [comment]
This is already being tracked in LLK/scratch-blocks#1378, I think.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/1378
