### ISSUE TITLE
"When backdrop switches to" block not showing all options in dropdown list

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1467]
### Expected Behavior
"When backdrop" block should show all backdrops in dropdown list

### Actual Behavior
"When backdrop" block only shows 1 backdrop in dropdown list despite multiple backdrops being in the Scratch project

### Steps to Reproduce

1. Add multiple backdrops to a project in 3.0 
<img width="1548" alt="whenbackdrop2 0" src="https://user-images.githubusercontent.com/3812168/36450841-4094b68a-165d-11e8-94ae-9e52ff52d101.png">
2. Switch to a new sprite and drag out "when backdrop switches to" block
3. Notice backdrop options in dropdown list are missing
<img width="1663" alt="backdrops3 0" src="https://user-images.githubusercontent.com/3812168/36450884-48f3733e-165d-11e8-882c-b0c844b7a9fd.png">

### Operating System and Browser

Chrome 64

**Comment by apple502j** [comment]
duplicate
https://github.com/LLK/scratch-gui/issues/919

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/919
