### ISSUE TITLE
Clicking on a sprite should default to the first costume below the stage

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1473]
### Expected Behavior
Clicking on a sprite should default to the first costume
![scratch_3_0_gui](https://user-images.githubusercontent.com/3812168/36502272-6c5f7376-1717-11e8-8706-1d108f716b56.png)

### Actual Behavior
Clicking on a sprite sometimes default to another costume
![scratch_3_0_gui](https://user-images.githubusercontent.com/3812168/36502355-ac727d5a-1717-11e8-85ff-0aca6756aa9f.png)

### Steps to Reproduce
1. Click on 3.0 project
2. Click on the "Add Sprite" button
3. Select the "Lion" sprite
4. Notice that the Lion sprite defaults to costume "lion-b" instead of "lion-a"

### Operating System and Browser

Chrome 64

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/1471
