### ISSUE TITLE
Viewing projects in full screen mode should not display "say" block text

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1474]
### Expected Behavior
Viewing projects in full screen mode should not display "say" block text
![scratch_3_0_gui](https://user-images.githubusercontent.com/3812168/36502982-944860e4-1719-11e8-9036-fe2299415b9c.png)

### Actual Behavior
Viewing projects in full screen mode sometimes show "say" block text
![scratch_3_0_gui](https://user-images.githubusercontent.com/3812168/36502902-53b12818-1719-11e8-9b26-0059b8c15a8a.png)

### Steps to Reproduce

1. Open a project in 3.0
2. Add a "say" block and type in some text
3. Click inside the "say" block
4. Run the program in full screen mode

### Operating System and Browser

Chrome 64

**Comment by kyleplo** [comment]
I think this only happens when you have the say block in focus.

**Comment by hedgehog125** [comment]
What happens if you inspect it?

**Comment by kyleplo** [comment]
I think I fixed it. Opened a pull request (in LLK/scratch-blocks)

**Comment by rachel-fenichel** [comment]
The solution is to call `hideChaff()` on the Blockly workspace when focusing somewhere else.

**Comment by kyleplo** [comment]
@rachel-fenichel That might be a better idea. My pull request just edits `css.js`

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/1346
