### ISSUE TITLE
Backdrop should automatically switch after adding new backdrop

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1475]
### Expected Behavior

Like sounds and sprites, the new backdrop should become the selected backdrop

### Actual Behavior

Backdrop doesn't switch

### Steps to Reproduce

Add new backdrop from library

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by towerofnix** [comment]
Hmm... I think this already works? When I add a new backdrop, the stage switches to that backdrop. I'm on Firefox 59.0b11, for what it's relevant.

**Comment by kyleplo** [comment]
Also, do you think it would be useful to delete the blank default backdrop if the user doesn't paint on it and they add a new one?

**Comment by fsih** [comment]
Fixed except for add surprise background and add paint background from the stage selector
