### ISSUE TITLE
Monitors should scale with stage size

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1476]
### Expected Behavior

In Scratch 2.0, the monitors are scaled proportionally to the stage size.

### Actual Behavior

In 3.0, the monitors do not correctly change scale when the stage changes size.

For example, when the stage scales to its slightly smaller version when you make the editor narrower, the monitors do not scale. They can end up off the right edge or completely off the bottom edge:

![monitor-scaling](https://user-images.githubusercontent.com/567844/36505180-b3dfc5d0-1720-11e8-836f-9917218099cf.gif)

Full-screen mode also causes trouble with both size and position of the monitors.

**Comment by mrjacobbloom** [comment]
May be affected by fixes for #1397 and #1235

**Comment by kyleplo** [comment]
This is yet another reason why watchers should be moved to renderer.

**Comment by paulkaplan** [comment]
Fixed. Monitors now scale with the stage.
