### ISSUE TITLE
When importing 2.0 projects into 3.0 some costumes are smaller than they should be

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1482]
### Expected Behavior
When importing 2.0 projects into 3.0 all sprites and costumes should appear as the same size

### Actual Behavior
When importing 2.0 projects into 3.0 some costumes are smaller than they should be

### Steps to Reproduce
1. Import a 2.0 project into 3.0
2. Click on a sprite
3. Click on the Costumes tab
4. Review each costume and you'll realize that some sprites are the wrong size (i.e. smaller)
<img width="1656" alt="banners_and_alerts_and_scratch_3_0_gui" src="https://user-images.githubusercontent.com/3812168/36559354-b4126a24-17db-11e8-8eb7-22182e7c54bb.png">

### Operating System and Browser

Chrome 64

**Comment by Narulacodes** [comment]
I can repro this from a Acer Chromebook, running chrome 63. I'm not sure why this is happening. Maybe because of the File types?

**Comment by mrjacobbloom** [comment]
This looks like it might be a duplicate of #762

**Comment by Narulacodes** [comment]
Maybe. That's talks bt thumnails, this is bout a backdrop

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/762
