### ISSUE TITLE
Some sprite icons when imported from 2.0 into 3.0 are cut off

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1488]
### Expected Behavior
Sprites and their sprite icon when imported from 2.0 into 3.0 should be resized appropriately
2.0 -> https://scratch.mit.edu/projects/17753164/#editor
3.0 -> https://preview.scratch.mit.edu/#17753164

### Actual Behavior
Some sprite icons when imported from 2.0 into 3.0 are cut off.
![snipit_-_select_area_to_copy](https://user-images.githubusercontent.com/3812168/36605966-468da9ae-1890-11e8-8f67-0b67317dfdb5.png)

### Steps to Reproduce
Open a 2.0 project in 3.0
Take a look at the sprite icons to see if they are resized appropriately

### Operating System and Browser
Chrome 64

**Comment by hedgehog125** [comment]
I also noticed that one of Scratch cat's legs get slightly cut off. It's easier to see if you go in fullscreen.

**Comment by Narulacodes** [comment]
What are ways to fix this?

**Comment by apple502j** [comment]
Cat problem is also LLK/scratch-render#233

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/762
