### ISSUE TITLE
Add a small blank area at the end of the toolbox

### ISSUE THREAD

**Issue by AnmAtAnm** [LLK/scratch-gui#1489]
### Expected Behavior

To hint that there are no more blocks, add a small blank area at the end of a scrollable toolbox, at least the height of one block.

![screen shot 2018-02-23 at 10 48 48 am editted](https://user-images.githubusercontent.com/9916202/36611287-cb8acb86-1887-11e8-932b-458c02d5b2b3.png)

### Actual Behavior

The last block of the toolbox is at the bottom of the scrollable toolbox.

<img width="337" alt="screen shot 2018-02-23 at 10 48 48 am" src="https://user-images.githubusercontent.com/9916202/36611304-dc41c8b2-1887-11e8-9fb5-d4e11bca0b30.png">

The is little visual difference between a toolbox that is scrolled all the way down, and coincidentally aligned toolbox with similar space on the last visible (but not last) block.

<img width="337" alt="screen shot 2018-02-23 at 10 49 03 am" src="https://user-images.githubusercontent.com/9916202/36611315-e4aecbf8-1887-11e8-93e5-d4fecb6835c6.png">

While the scroll bar is present, it does not stand out at a glance.

### Steps to Reproduce

Look at the toolbox upon opening the Scratch preview. Note how the blocks align with the scroll. Note how that it is dependent upon the user's screen size.

Scroll to the bottom of the toolbox. Compare to the previous state.

**Comment by Narulacodes** [comment]
:D

**Comment by paulkaplan** [comment]
Fixed! Categories now are padded at the bottom.
