### ISSUE TITLE
Dragging and Dropping blocks to copy them doesn't work

### ISSUE THREAD

**Issue by vedk** [LLK/scratch-gui#1492]
### Expected Behavior

When a script is dragged and dropped on another sprite's logo in the area below the stage, the script should be copied into the workspace of the intended sprite.

Doing this should be easy and should not require adjusting too much on behalf of the user.

### Actual Behavior

Currently in the environment described in "Operating System and Browser," the small script is difficult to copy by dragging and dropping into another sprite. It requires *too* much adjusting and precise positioning so that the spite, on which the script hovers, acquires the blue border indicating that the script will be copied successfully.

The closest issue which matches is perhaps #166, but the script could not be found anywhere in the other script's workspace.

**A video of the issue can be found at https://youtu.be/lR8vBza4zEU.**

### Steps to Reproduce

1. Open the preview editor at https://preview.scratch.mit.edu/
2. Make a small script
3. Import another sprite
4. Drag the script onto the other sprite's logo below the stage to copy the script

### Operating System and Browser

Tested at https://preview.scratch.mit.edu/ on **openSUSE Leap 42.3** running **Google Chrome Version 64.0.3282.119 (Official Build) (64-bit)**.

Further information:
```
ved@linux-2nu3:~> lsb_release -a
LSB Version: n/a
Distributor ID: openSUSE project
Description: openSUSE Leap 42.3
Release: 42.3
Codename: n/a
```

And,
```
ved@linux-2nu3:~> uname -a
Linux linux-2nu3 4.4.87-25-default #1 SMP Wed Sep 13 07:19:13 UTC 2017 (3927ef5) x86_64 x86_64 x86_64 GNU/Linux
```

Thank You for creating such an amazing software,

Ved (vedkhandekar on [scratch.mit.edu](https://scratch.mit.edu/))

**Comment by mrjacobbloom** [comment]
I believe this feature hasn't been merged in yet: #1468

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/1234

**Comment by vedk** [comment]
Extremely sorry for opening a duplicate issue, I checked if there were any issues related to "drag and drop" but it did not strike me that the same feature could have a different name.

Sorry once again,

Ved

**Comment by thisandagain** [comment]
No apology needed @vedk! This happens all the time. It's better to have it logged and also helps us get a sense of priority. 😄
