### ISSUE TITLE
Tried to test a Scratch 2.0 project in 3.0

### ISSUE THREAD

**Issue by CoolGames** [LLK/scratch-gui#1496]
### Expected Behavior

[Simple tune plays notes](https://scratch.mit.edu/projects/202646731/) as it does in 2.0

### Actual Behavior

Nothing seems to load and no errors occur just [blank screen
](https://llk.github.io/scratch-gui/#202646731)

No examples in any issue work either.

### Steps to Reproduce

Load the project from [Scratch online](https://scratch.mit.edu/projects/202646731/) or attached zip
[Scratch2Cat.zip](https://github.com/LLK/scratch-gui/files/1756936/Scratch2Cat.zip) following [instructions in wiki
](https://github.com/LLK/scratch-gui/wiki)

### Operating System and Browser

Ubuntu Studio 17.10 
Google Chrome
Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by towerofnix** [comment]
The project loads for me (following your "blank screen" link).

Perhaps a separate issue, but its sounds don't play for me, and many errors like this are logged:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.assets.scratch.mit.edu/internalapi/asset/instruments/10-clarinet/60.mp3/get/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by CoolGames** [comment]
I turned off PRIVACY BADGER and it now works.

**Comment by luofei614** [comment]
the same to me .  what to do ,thinks?
