### ISSUE TITLE
Update Menus on Click

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-gui#150]
### Expected Behavior

_The menus get refreshed when you click them._

### Actual Behavior

_Not Implemented._

### Steps to Reproduce

_Put a switch backdrop block into the workspace, and add a new backdrop, the one in the flyout will update but not the one in the workspace._

### Possible Solution

_In _```src/containers/blocks.jsx```_:_
_Replace_
```js
// Line: 12
options: start.concat(menuOptionsFn())
```
_With_
```js
// Line: 12
options: function () {
    start.concat(menuOptionsFn())
}
```

**Comment by TheBrokenRail** [comment]
I fixed the example solution so that it actually works

**Comment by TheBrokenRail** [comment]
I have a fix for this by only calculating the menu on open. (instead of run the function on jsonForMenuBlock, run it when you open the dropdown

**Comment by TheBrokenRail** [comment]
I updated the example so it is easier to implement.

**Comment by TheBrokenRail** [comment]
Is anyone currently working on this, should I make a PR?

**Comment by rschamp** [comment]
@TheBrokenRail Yes go ahead and make a PR so we can check it out. Thanks!
