### ISSUE TITLE
Add Sprite & Add BG buttons become fixed to the last row of sprites

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#1500]
### Expected Behavior

**This only happens on Firefox**
The menu buttons position should remain fixed to the browser window (with space between the bottom of the window and the button).

### Actual Behavior

Once you have added enough Sprites to cause multiple rows of sprites, the menu snaps to align the bottom of the button with the bottom of the last sprite row. This also breaks the scrolling of the space.
![add sprites](https://user-images.githubusercontent.com/3409578/36752305-af0086d0-1bd0-11e8-8ca4-d07c6eb9257e.gif)

### Steps to Reproduce

1. Add enough sprites to extend beyond the browser workspace
2. Try to scroll the sprite list

### Operating System and Browser

OS: macOS 10.13.3
Browser: Firefox 58.0.1 (64-bit) &  58.0.2 (64-bit

**Comment by towerofnix** [comment]
The buttons actually seem to be fixed so that the bottom of the button is on the same Y-position as the bottom of the last item in the list ("Abby", in the screenshot).

**Comment by bartljak** [comment]
This is not happening for me on macOS 10.12.6 with Firefox 58.0.2 64-bit(the most recent version of firefox). This is what it looks like on my machine:
<img width="407" alt="screen shot 2018-02-27 at 1 38 13 pm" src="https://user-images.githubusercontent.com/6947753/36747649-8d7b692e-1bc3-11e8-887f-81869e060543.png">

Maybe try updating your firefox?

**Comment by towerofnix** [comment]
@bartljak I'm running Firefox Developer Edition, which is the most up-to-date *semi-*stable version of Firefox (59.0b12 right now), so.

Note that I'm running Debian, not macOS.

**Comment by carljbowman** [comment]
@bartljak - Good call. Just updated my version of Firefox to 58.0.2 (64-bit). But I still seeing the problem.

@towerofnix - That's a good thought. The buttons are aligning to the bottom of the row of sprites. As a follow up I tried to add a third row and found something even more bizarre:
![adding sprites](https://user-images.githubusercontent.com/3409578/36750754-4ee23496-1bcc-11e8-9894-698ea7019141.gif)

An even worse side effect of this issue, I could no longer scroll the sprite list when the third row was added and extended beyond the browser window.

**Comment by bartljak** [comment]
@carljbowman I cannot seem to replicate this bug causing the button to get stuck to the bottom of the browser window, but I am experiencing the same problem as you pointed out in the second gif. When I add enough sprites (on firefox only) to extend beyond the browser window, the button disappears and I cannot scroll through the sprites.

**Comment by carljbowman** [comment]
@bartljak - Upon further investigation is looks like it's not fixing to the browser, but instead the bottom of the last row of sprites as @towerofnix pointed out.

Here is a GIF of a larger browser window that demonstrates the issue:
![add sprites](https://user-images.githubusercontent.com/3409578/36752148-2eaa6596-1bd0-11e8-9675-768a1402049b.gif)

**Comment by apple502j** [comment]
#1513
I cannot scroll either

**Comment by kyleplo** [comment]
I'm not getting any of these issues on Windows Chrome

**Comment by Kenny2github** [comment]
@kyleplo this is a Firefox-only issue.

**Comment by technoboy10** [comment]
This issue was resolved in #2309.
