### ISSUE TITLE
Delete Sprite UI appears above Add Sprite Menu

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#1503]
### Expected Behavior

Delete sprite button should appear behind the add sprite menu.

### Actual Behavior

<img width="497" alt="screen shot 2018-02-26 at 12 34 42 pm" src="https://user-images.githubusercontent.com/3409578/36685473-6fd4912a-1af1-11e8-8ec5-9d09f8549192.png">

Also appears above the add sprite button.
<img width="102" alt="screen shot 2018-02-26 at 4 31 22 pm" src="https://user-images.githubusercontent.com/3409578/36696585-9765456a-1b12-11e8-96dc-0c3f1c016a37.png">

### Steps to Reproduce

1. Add enough sprites so the add sprite menu opens over a sprite
2. Open add sprite menu

### Operating System and Browser

OS: macOS 10.13.3
Browsers: 
- Chrome 64.0.3282.167 (Official Build) (64-bit)
- Firefox 58.0.1 (64-bit)
- Safari  11.0.3 (13604.5.6)

**Comment by paulkaplan** [comment]
Fixed!
