### ISSUE TITLE
Importing some 2.0 projects into 3.0 causes text to move or disappear. 

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1512]
### Expected Behavior
Importing 2.0 assets into 3.0 should resemble one another

### Actual Behavior
Importing some 2.0 projects into 3.0 causes text to move or disappear. 
![scratch_3_0_gui](https://user-images.githubusercontent.com/3812168/36695890-8f99d884-1b10-11e8-9b24-f9ca75b0d020.png)

![scratch_3_0_gui](https://user-images.githubusercontent.com/3812168/36695953-c3dc897a-1b10-11e8-86aa-24e6ba39d825.png)

### Steps to Reproduce
1. Open a 2.0 project in 3.0
2. Click on the Stage sprites
3. Click on the Costumes tab
4. Click through the backdrops and notice the text chan

### Operating System and Browser

Chrome 64

**Comment by paulkaplan** [comment]
Looks like this has been fixed, tested using this project: https://llk.github.io/scratch-gui/develop/#20619111
