### ISSUE TITLE
Clicking on a sprite in the Paint Editor only selects specific parts (i.e ungrouped)

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1513]
### Expected Behavior
Clicking on a sprite in the Paint Editor should select the entire sprite (i.e. grouped)
https://preview.scratch.mit.edu/#17753164
![racing_game_example_project_on_scratch](https://user-images.githubusercontent.com/3812168/36696779-2e727806-1b13-11e8-8aae-e64465ae906b.png)

### Actual Behavior
Clicking on a sprite in the Paint Editor only selects specific parts (i.e ungrouped)
https://scratch.mit.edu/projects/17753164/#editor 
![scratch_3_0_gui](https://user-images.githubusercontent.com/3812168/36696889-832fc56a-1b13-11e8-8bc7-452514371f62.png)
### Steps to Reproduce

1. Open 2.0 Project into 3.0
2. Click on a Sprite
3. Click on the Costumes tab
4. Select a sprite in the Paint Editor and notice that the entire sprite is not selectable by default. 

### Operating System and Browser
Chrome 64

**Comment by thisandagain** [comment]
After discussion we are going to move forward with grouping all sprites in Scratch 3.0 (as is the case in 2.0). This may take us a little time to go through every item in the library.

**Comment by techwonder21** [comment]
Thanks for the update! Are you shooting for end of April 2018 for some sprites?

**Comment by thisandagain** [comment]
@techwonder21 Yup. We won't be able to get this done for all sprites by the end of the month, but we'll try for some / most common.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-paint/issues/258
