### ISSUE TITLE
New Sprite/Backdrop button is not available with 6+ sprites

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#1518]
### Expected Behavior
New Sprite/Backdrop Button is always available.
### Actual Behavior
Not so. Maybe they're hidden.
When I view in 70~80%, they are shown.

Movie: https://vimeo.com/258021375
Password is the name of this repository
### Steps to Reproduce
1. Add 6 sprite
### Operating System and Browser
Firefox 58.0.2 and windows 7 64bit sp1 home premium

**Comment by thisandagain** [comment]
@apple502j Can you please provide a screenshot or GIF?

**Comment by bartljak** [comment]
This bug is not happening for me on macOS 10.12.6 with Firefox 58.0.2 (64-bit).
Screenshot:
<img width="410" alt="screen shot 2018-02-27 at 1 43 32 pm" src="https://user-images.githubusercontent.com/6947753/36747898-488526ce-1bc4-11e8-8caf-ab1c0d39ec2a.png">

**Comment by apple502j** [comment]
* 5 Sprites:OK
![](https://i.gyazo.com/ded9ba1f18a12aa7b5f9c795f6165271.png)

* 6 Sprites:
![](https://i.gyazo.com/e9ed6eaa1688dbb74d85ef5d9b31c4e2.png)

* In 80%, 6 sprites:
![](https://i.gyazo.com/fb14782c8f3d2dc52fa411b7a0f7c9bb.png)

**Comment by Kenny2github** [comment]
I cannot reproduce this on Windows 8.1, Chrome latest, screen resolution 1920 × 1080

**Comment by apple502j** [comment]
cannot repro in my Chrome.

+1 I cannot scroll the sprite pane either

**Comment by apple502j** [comment]
Duplicate
