### ISSUE TITLE
Entering a url # with non-numeric gibberish doesn't hit 'Oops page'

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#1527]
### Expected Behavior

Entering an invalid project id in the url should bring up "Oops page".

### Actual Behavior

Nothing loads, and we get the following errors in the console:

![image](https://user-images.githubusercontent.com/1786240/36793778-49597f0c-1c6c-11e8-9341-62e6d967afc7.png)

The project server seems to behave slightly differently on project ids that are numeric vs. non-numeric, doing an extra CORS check on the latter.

### Steps to Reproduce

Navigate to: https://llk.github.io/scratch-gui/develop/#jgdflkgjdogijgoier

Compare the behavior of above to the behavior of the following:

Navigate to: https://llk.github.io/scratch-gui/develop/#34348959403853453

**Comment by hedgehog125** [comment]
It might make more sense if there was a 404 error screen.

**Comment by Narulacodes** [comment]
Debuging and reproing from ISUS transformation book, running windows 8, same promblem

**Comment by paulkaplan** [comment]
No longer a supported way of loading projects
