### ISSUE TITLE
Workspace pattern

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#153]
An initial pattern for the workspace. We certainly should explore more options, but it would be good  to have something in place for the Animate a Name/Word playtest.

![r1 2_gui_animate-prototype](https://cloud.githubusercontent.com/assets/3409578/23512601/2d4cf4de-ff2f-11e6-94d5-41ff35011436.png)

Sample 
<img width="231" alt="screen shot 2017-03-02 at 10 01 47 am" src="https://cloud.githubusercontent.com/assets/3409578/23512632/4a68e10e-ff2f-11e6-82d7-d75cc5a7b8e9.png">

Assets: [patterns.zip](https://github.com/LLK/scratch-gui/files/814153/patterns.zip)
Included a repeatable pattern tile in a few different formats: svg and png. Knowing the workspace we may want to use the png for performance.

**Comment by carljbowman** [comment]
@thisandagain - Feel free to reassign. Just wanted to be tracking the issue.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-blocks#817
