### ISSUE TITLE
Back button on "View a Scratch 2.0 Project" screen can't be activated by the keyboard

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#1530]
### Expected Behavior

Pressing enter (and maybe space) while the back-arrow button is pressed should go back to the welcome screen of the gui.

### Actual Behavior

The only way to activate the button is to click on it.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

Click/activate the "View 2.0 Project" button, then press space or enter after tab-focusing this button:

![Back-arrow button next to "View a Scratch 2.0 project"](https://user-images.githubusercontent.com/9948030/36800853-e3daf6b8-1c86-11e8-8948-e21b34755655.png)

### Operating System and Browser

Firefox 59.0b12, Debian (testing).

**Comment by thisandagain** [comment]
This is temporary UI, so I'm going to backlog this.

**Comment by towerofnix** [comment]
Closing since this is no longer relevant!
