### ISSUE TITLE
Stage gap during responsive UI change

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1538]
### Expected Behavior

The stage stays the same ratio

### Actual Behavior

The stage can be made to have different aspect ratios. The extra space is filled in with a gray gap

### Steps to Reproduce

Have 6 sprites
Resize the browser
![stagegap](https://user-images.githubusercontent.com/2855464/36863752-a361ac3a-1d58-11e8-8598-0f32942a5c60.gif)
Try to ignore the squirrel

### Operating System and Browser
Windows 10 Chrome

**Comment by fsih** [comment]
Update: I'm not seeing the blue bar in the stage anymore. I have this gap instead:
![image](https://user-images.githubusercontent.com/2855464/39322469-f9d85b60-4957-11e8-952e-b421b1f03a6c.png)

**Comment by paulkaplan** [comment]
@fsih is this still happening? I can't repro on mac/chrome

**Comment by fsih** [comment]
Nope!
