### ISSUE TITLE
Too many "surprise" sprites are letters

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1542]
### Expected Behavior

Clicking surprise sprite should give you something that helps you come up with a project idea, such as an animal, vehicle, object, etc.

### Actual Behavior

Because we have such a large number of letter sprites in the library, many times you get a letter. 

Most people do not want to create a story about how Z, Q, and R try to play basketball but discover they have no arms. 

Although now that I think about it maybe I will. It turns out that R can kind of run on his weird legs and head-butt the ball, actually, and Q does a sort of slow-rolling-but-invincible zone defense, but Z (surprisingly) can totally spring up and dunk.

**Comment by apple502j** [comment]
`Z(Glow|Pixel|Block)-.`

Here is the regexp to detect letters.

**Comment by joker314** [comment]
Given all that, do we actually want to remove letters from "Random sprite", or simply decrease the probability of a letter popping up?

I think, as you described, letters _can_ be useful for making projects, just so long as not every single project is about a letter. 

How about the random sprite feature treats all the letters as one sprite for picking purposes, and then if a letter happens to be selected, it _then_ picks a random letter. Thoughts?

**Comment by kyleplo** [comment]
I think all the letter fonts should be combined into one sprite with each letter as a costume. This would reduce the letters down to 3 sprites.

**Comment by benjiwheeler** [comment]
I like @joker314's idea. Maybe an even simpler way to do this would be to have the algorithm pick a random sprite, see if it's a letter/number using an approach like @apple502j's regexp, and if so, make a randomized decision (with 80% or 90% likelihood) to pick again.

**Comment by benjiwheeler** [comment]
And, I heard more reports of wanting this change from LLK's researchers.
