### ISSUE TITLE
"Say [pick random 1 to 10]" displays two decimal places

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1543]
### Expected Behavior

The `pick random` block, when it has integer-only inputs, returns an integer. It should display the integer without decimal places when used in a `say` block.

### Actual Behavior

`Say [pick random 1 to 10]` displays two decimal places:

![image](https://user-images.githubusercontent.com/567844/36910067-b8a787c6-1e0d-11e8-9ba2-ef1143ca3e30.png)

Note that the tooltip when you click on the random block by itself has the correct behavior:

![image](https://user-images.githubusercontent.com/567844/36910176-fe483f82-1e0d-11e8-9857-292570dc2c58.png)
![image](https://user-images.githubusercontent.com/567844/36910193-05c39f9a-1e0e-11e8-836f-c4dd14a18932.png)

**Comment by apple502j** [comment]
Maybe because of #1372 ...

**Comment by thisandagain** [comment]
The PR where this issue was introduced is here:
https://github.com/LLK/scratch-vm/pull/925/files

Note the use of `toFixed`.

**Comment by towerofnix** [comment]
I'm busy so I can't make/test a PR for this myself, but I think that simply adding a `parseFloat()` around `message.toFixed(2)` would do the job. `String(message)` is called right after anyways, so we don't have to worry about accidentally passing along a non-string value.

**Comment by thisandagain** [comment]
@towerofnix Yup. I agree. I think that's probably the right thing ... that and add some unit tests so this doesn't happen again. 😉

**Comment by bartljak** [comment]
Was this fixed? I tried to replicate the bug and it does not happen for me. 
<img width="549" alt="screen shot 2018-03-04 at 9 51 19 pm" src="https://user-images.githubusercontent.com/6947753/36955391-32aa21de-1ff6-11e8-8029-eb682feecf2d.png">

Also, the link above is for the scratch-vm repo not the gui repo.

**Comment by thisandagain** [comment]
No. This was not fixed. I'm able to replicate on the latest `master` and `develop`.

### Master
![image](https://user-images.githubusercontent.com/747641/36976329-2b85afc2-204b-11e8-9e94-85c14d99fee9.png)

### Develop
![image](https://user-images.githubusercontent.com/747641/36976350-3ec4add6-204b-11e8-84e9-c2a404e368ed.png)

**Comment by thisandagain** [comment]
Moved to LLK/scratch-vm#960
