### ISSUE TITLE
Doesn't 3.0 support LEGO® WeDo and PicoBoard?

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#1549]
There are no extensions about these boards. Doesn't 3.0 support them? If so, when will they become supported? If not, what should we do about the projects using them?

Windows 7 Home Premium 64bit SP1, Firefox 58.0.2

**Comment by thisandagain** [comment]
Correct. We do not currently have plans to support the LEGO WeDo 1.0 and Picoboard in Scratch 3.0, but they will continue to be supported in the Scratch 2.0 offline editor.

**Comment by kyleplo** [comment]
But what will happen to projects with them?

**Comment by hedgehog125** [comment]
@kyleplo Good point. There should probably be at least some kind of message so you know you need to use the offline 2.0 editor in order to use it.

**Comment by fatpandaria** [comment]
So if I want to extend support for picoBoard in Scratch,what should I start with?In Scratch2,the support was made possible by loading the ScratchExtension on the window,what should I do with the extension in the scratch3 VM?Anyone has idea?Thanks.

**Comment by thisandagain** [comment]
@fatpandaria Great question. We'll be publishing a new repo called `scratch-link` soon that is used for hardware communication and you should be able to extend that to add support for devices like the PicoBoard. Stay tuned. 😄

**Comment by jcaalzago** [comment]
Where do you communicate the creation of the repo _scratch-link_ . I'm interesting in the compatibility of Scratch 3.0 with Lego Wedo 1.0 (and maybe Arduino).

**Comment by mosfetcity** [comment]
Money, money, money.
