### ISSUE TITLE
Clicking any part of hide/show buttons should hide/show sprite

### ISSUE THREAD

**Issue by Airhogs777** [LLK/scratch-gui#156]
### Expected Behavior
Clicking anywhere inside the border of the button should change the sprite's visibility

### Actual Behavior
User must click the "eye" icon to show/hide the sprite. I assume the same goes for the draggable button

**Comment by CosmicWebServices** [comment]
Working for me. What is your browser?

**Comment by Airhogs777** [comment]
Latest Chrome on latest macOS

**Comment by liam4** [comment]
Can reproduce, and, yeah, it is the same for the draggable button.

**Comment by lifeinchords** [comment]
@Airhogs777, @liam4 I believe #155 fixes this. Can you please take a look and confirm if this is still an issue?

**Comment by lifeinchords** [comment]
Whoops - please disregard that, it's still broken
