### ISSUE TITLE
say bubble goes off of the stage with certain backgrounds

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#1569]
Expected:
If you use a say block with a sprite and it is near the edge of the screen the bubble should move so it stays on screen.

Actual:
The say bubble will stay in the upper right corner of sprite and move off the screen, above or below.

Reproduction steps:
NEEDS REPRO
I saw this in the screen capture from the Chelsea Clubhouse trip on 2/28/18 and pulled the screenshots from that.  Could not reproduce on 3/5/18.

![sayBubbleCutOff2.png](https://codetreeusercontent.s3.amazonaws.com/uploads/7b360327-4108-4e98-8979-f6cfe6572d25/sayBubbleCutOff2.png)

![sayBubbleOffScreen.png](https://codetreeusercontent.s3.amazonaws.com/uploads/7b360327-4108-4e98-8979-f6cfe6572d25/sayBubbleOffScreen.png)

**Comment by Grinthy** [comment]
Hmm, was it an issue in 2.0?
