### ISSUE TITLE
Too many inanimate costumes with faces and legs

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1570]
How many people would make a project about smiling saxophones, walking strawberries and traveling takeout?

**Comment by confiks** [comment]
I was doubtful of my desire to use a Smiling Saxophone, but after seeing the actual sax, my doubts quickly faded.

![Smiling Sax](https://cdn.assets.scratch.mit.edu/internalapi/asset/29751826f768bc1568092f267525ae8b.svg/get/)

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-gui/pull/1511

**Comment by kyleplo** [comment]
What?! How do #1511 resolve this?

**Comment by thisandagain** [comment]
It removes all of the "c" costumes (the ones with the legs, arms, and faces) from all of the new music sprites.

**Comment by kyleplo** [comment]
Oh, I didn't understand
