### ISSUE TITLE
Sprite name is misspelled 

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1571]
### Expected Behavior

Sprite name is spelled correctly

### Actual Behavior

Sprite name is misspelled 
![scratch_3_0_gui](https://user-images.githubusercontent.com/3812168/37053731-fb5ab210-214a-11e8-8d30-02637f80c64a.png)

### Steps to Reproduce
1. Open Scratch 3.0
2. Click "Add Sprite"
3. See that "Gutar-elec" sprite is spelled incorrectly.

### Operating System and Browser

Chrome 64

**Comment by paulkaplan** [comment]
This has been fixed
