### ISSUE TITLE
acces to instance of virtual machine from scratch-gui [question]

### ISSUE THREAD

**Issue by SimonMeysman** [LLK/scratch-gui#1572]
I have a question about the accessibility of the virtual machine from the actual gui. For my masters thesis I've been working at a way to generate tests for scratch projects to automatically generate feedback for exercises. This way a lesson plan of sorts could be created to introduce kids to computational thinking using Scratch in a structured manner. I have been using the old playground in combination with puppeteer to run these tests. This way, I have access to the virtual machine in the console to check the state of the machine, and there is a renderer linked, so I have things like collision detection. However, I would like to use the complete gui in my tests, as it will always contain the latest features, but I seem to be unable to access the virtual machine (This used to be accessible using Scratch.vm in the console). 

Is there a plan to allow access to this vm from the console? Or is there a reason why this would not be preferable? If the scratch-vm repo wasn't open source I would completely understand, but as it is open source, being able to access it from the developer console would be a great help in developing my testing framework.

I'm sorry if this is not the right place to ask this,
kind regards,
Simon

**Comment by mrjacobbloom** [comment]
Even if not, it shouldn't be too hard to fork scratch-gui to give global access to the vm for your personal instance. I'm not too familiar with the code in this repo, but somewhere in [this function](https://github.com/LLK/scratch-gui/blob/develop/src/containers/gui.jsx#L26) you could try adding something like `window.scratchVM = this.props.vm`

**Comment by thisandagain** [comment]
Hi @simonmeysman, we don't have any plans to expose the VM globally, but you are more than welcome to fork GUI and attach a reference VM to `window` as @mrjacobbloom suggests.
