### ISSUE TITLE
Clicking outside the stage area still activates "when this sprite clicked"

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-gui#1580]
### Expected Behavior

Clicks in the coding area should never have an effect on the project

### Actual Behavior

![stage-bug](https://user-images.githubusercontent.com/15109618/37096124-5fbaeaec-2220-11e8-949e-177a46b91b53.gif)

**Comment by Kenny2github** [comment]
I can reproduce this on Chrome 64, Windows 8.1. I suspect that whatever checks the mouse is forgetting about the stage boundaries.

**Comment by kyleplo** [comment]
Some projects, such as [Advanced Sensors by @JuegOStrower]( https://scratch.mit.edu/projects/62770746/) need this feature 

(this project is broken with the new layout though)

**Comment by morantsur** [comment]
@kyleplo this is not exactly the same functionality - it 2.0, even if does track where the mouse is outside the stage, *clicks* on the stage are not considered clicks on a sprite if it's outside the stage area. But wow, that's a cool project!

**Comment by paulkaplan** [comment]
Fixed
