### ISSUE TITLE
Sprites appear out of order

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1588]
### Expected Behavior

Sprites appear in the same order in 3.0 as they do in 2.0
https://scratch.mit.edu/projects/17587338/#editor
![cave_surfing_example_project_on_scratch](https://user-images.githubusercontent.com/3812168/37121595-a1286422-222b-11e8-998d-23e33621a864.png)

### Actual Behavior

Sprites appear out of order
https://preview.scratch.mit.edu/#17587338
![scratch_3_0_gui](https://user-images.githubusercontent.com/3812168/37121577-916c1740-222b-11e8-8943-18e6ffb6960a.png)

### Steps to Reproduce

1. Open 2.0 project
2. Open same project in 3.0
3. Notice sprites being out of order

### Operating System and Browser

Chrome 64

**Comment by hedgehog125** [comment]
Maybe it's intentional? It looks like they're being sorted A-Z?

**Comment by mrjacobbloom** [comment]
Related to #939
