### ISSUE TITLE
Duplicating a sprite does not append +1 to the sprite name

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1593]
### Expected Behavior
Duplicating a sprite should append +1 to the sprite name

### Actual Behavior
Duplicating a sprite does not append +1 to the sprite name
<img width="1638" alt="scratch_3_0_gui" src="https://user-images.githubusercontent.com/3812168/37164010-3365ec56-22c7-11e8-82b3-fb66d1f7c154.png">

### Steps to Reproduce
Duplicate a sprite in 2.0 - https://scratch.mit.edu/projects/20683586/#editor
Duplicate a sprite in 3.0 - https://preview.scratch.mit.edu/#20683586
Notice the sprite name stays the exact same in 3.0

### Operating System and Browser

Chrome 64

**Comment by mrjacobbloom** [comment]
This was fixed in #952. That fix isn't pushed to https://preview.scratch.mit.edu yet but you can see it work at https://llk.github.io/scratch-gui/develop/#20683586
