### ISSUE TITLE
Custom procedure definition (and corresponding substack) disappears with uncaught error

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#1594]
### Expected Behavior

Blocks should not disappear from workspace.

### Actual Behavior

Custom procedure definition disappears with the following error in the console:

`Uncaught Trying to replace a shadow on a custom procedure definition.`

### Steps to Reproduce

Not sure how it happened (**needs repro**). Circumstances involved in producing the error:

- adding a bunch of blocks to the workspace of a sprite
- adding a new sprite via the sprite library
- switching back to the original sprite immediately after adding the new sprite (and then the custom procedure definition was gone)

**Comment by BryceLTaylor** [comment]
I can't seem to reproduce this.  Do you have any other info about how it comes up?  Are you adding a bunch of blocks to the custom procedure, or just randomly on the workspace.  Is there a particular sprite that you've added to get the error?

**Comment by kchadha** [comment]
@BryceLTaylor Unfortunately I don't have much more information. I was trying to add a lot of blocks to the workspace (not in any sensible order necessarily) for testing save and load. I did create a long stack with my custom procedure, and I think I was just working on the cat sprite.

**Comment by ericrosenbaum** [comment]
I think found a repro for this!

![shadow-of-null](https://user-images.githubusercontent.com/567844/46230464-ad6c3400-c336-11e8-9fc1-96a3cb1513d5.gif)

**Comment by kchadha** [comment]
Fixed in LLK/scratch-blocks#1751. CC/ @BryceLTaylor
