### ISSUE TITLE
Hide "unfinished" blocks from the toolbox for EOY prototype

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-gui#16]
This is my accounting:
- say
- say for n secs
- think
- think for n secs
- entire pen category
- show variable/list, hide variable/list.
- when "loudness"/"video motion" > _ (timer works).
- ask and wait
- answer (for ask and wait)
- loudness
- video motion reporter
- turn video on/off
- username
- "more blocks" category

**Comment by TheBrokenRail** [comment]
Maybe iterating through the blocks and checking if they are implemented (if they have a primitive) and hiding the ones that don't.
