### ISSUE TITLE
Say blocks briefly show previous thing that sprite said

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1604]
When a sprite says (or thinks), it briefly shows the last thing said:
![image](https://user-images.githubusercontent.com/31634240/37242490-4dd5c3e6-2438-11e8-8de6-ec80f6eb5557.png)
Here is the same GIF, but slowed down:
![image](https://user-images.githubusercontent.com/31634240/37242499-839458bc-2438-11e8-80f0-511f8d337b71.png)

**Comment by towerofnix** [comment]
@kyleplo I've noticed this as well (Firefox, Debian).

By the way, your "gif"s are actually PNGs.

**Comment by kyleplo** [comment]
@towerofnix Yeah, I realized that. Something weird must have happened (or Github converts gifs to pngs)

**Comment by paulkaplan** [comment]
Issue seems to have been fixed
