### ISSUE TITLE
Color effect inverts colors on iPad 

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1605]
### Expected Behavior

Sprites change color when color effect is changed

### Actual Behavior

Colors get inverted
**Before**
![d1485480-352a-4d7c-8aa7-69496e1ab913](https://user-images.githubusercontent.com/31634240/37255313-245501aa-2521-11e8-9d8b-bf648be60ab4.jpeg)
**After**
![c3576a59-a4d2-453b-975b-3b0972deb177](https://user-images.githubusercontent.com/31634240/37255328-592aaa38-2521-11e8-9af6-ad8b822e031c.jpeg)

### Steps to Reproduce

Change the color effect on an iOS device 

### Operating System and Browser

iOS 11.1 Chrome 64

**Comment by Clark-E** [comment]
I think the heart of this problem lies with scratch-render.

Speaking of, I found an interesting comment that seems to pertain to your issue:
[https://github.com/LLK/scratch-render/blob/develop/src/shaders/sprite.frag](url) line 48


```

// Smaller values can cause problems with "color" and "brightness" effects on some mobile devices
const float epsilon = 1e-4;

```

Maybe you should start there.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-render#245
