### ISSUE TITLE
how to add sprite in the Sprite library

### ISSUE THREAD

**Issue by landysunny** [LLK/scratch-gui#1607]
I want to add some of my sprite by myself in the sprite library ,but I can not find the solution.Could you help me ?

**Comment by Clark-E** [comment]
Uploading your own sprites is not supported. It will be added later.

**Comment by kyleplo** [comment]
You press the ![image](https://preview.scratch.mit.edu/497f797eeffe5fa7e6a626abc0db08a1.svg) button.

It is a bit confusing that the drop-up menu is also a button.

**Comment by landysunny** [comment]
Anyway, thanks for you answer. I hope it can be come ture as soon as possible. best wishes.

**Comment by landysunny** [comment]
{this.getFilteredData().map((dataItem, index) => {
                        const scratchURL = dataItem.md5 ?
                            `https://cdn.assets.scratch.mit.edu/internalapi/asset/${dataItem.md5}/get/` :
                            dataItem.rawURL;

I try to revise the code like that, i hope that i can add spirte from my local environment not from the cdn. finally,i can not be. what the dataItem.md5  stand for ? Is there any solution to solve it?
