### ISSUE TITLE
Sprites cannot say nothing

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1615]
### Expected Behavior

When you use 'say []', the speech bubble disappears 

### Actual Behavior

Nothing happens

### Steps to Reproduce

1. Make a sprite say something with 'say' not 'say for secs'
2. Make a sprite say nothing

### Operating System and Browser
iOS 11 Chrome 64

**Comment by Clark-E** [comment]
I believe this is intentional functionality, considering it appears in 2.0 as well.

If you want to say nothing, try adding a space to the block's input.

Actually, that gives a bug:

![cat](https://user-images.githubusercontent.com/35299276/37312299-dd3d8674-2620-11e8-8c75-30c4fc29e31b.PNG)

**Comment by kyleplo** [comment]
No, I mean using this to hide a speech bubble.

**Comment by paulkaplan** [comment]
Can't repro this, saying "" makes the speech bubble disappear as it should.

**Comment by kyleplo** [comment]
@paulkaplan Oh, I was testing on an older version (or maybe this is an iOS-only bug)
