### ISSUE TITLE
Make it more obvious how to add from sprite library

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1617]
As suggested in #1607, it is hard for some to find the sprite library button because it is also a drop-up menu. I think there should also be a separate button:
![image](https://user-images.githubusercontent.com/31634240/37338144-e7e4b70c-268c-11e8-8187-a71ff1b01c14.png)
*they would probably be in a different order and the tooltip isn't working yet*

**Comment by Grinthy** [comment]
Yeah, I usually just click the just click the main button. That does need to be fixed, or users just need to get used to it. I like that they brought back the random sprite button! _wink_
