### ISSUE TITLE
Some modals not properly optimised for small-screen devices

### ISSUE THREAD

**Issue by python-megapixel** [LLK/scratch-gui#1618]
### Expected Behavior

I should be able to scroll the modals so I can click the buttons on a small-screen device. Even better, it should reduce in size so that I can click _without_ scrolling

### Actual Behavior

If I load the Scratch GUI on my 10" laptop, I can't click the 'Try-it" button without hiding the panel at the bottom of the screen and switching to full-screen mode on my browser. This is because the page seems to be configured so that it doesn't scroll when a modal is open, but the modal is too large to fit on the screen.

### Steps to Reproduce

Go to [preview.scratch.mit.edu](https://preview.scratch.mit.edu) on a desktop computer. Then unmaximise the window and resize it to make it smaller. The content will go off the bottom of the screen with no way to scroll it.

Update: I think this might be OS/browser specific. It can't be reproduced on some systems. 

### Operating System and Browser

Linux Mint 18.3 32-bit / Chromium 64.0.3282.140

**Comment by kyleplo** [comment]
Can't reproduce on Windows 10 Chrome 64.0.3282.186

**Comment by python-megapixel** [comment]
> Can't reproduce on Windows 10 Chrome 64.0.3282.186

I reckon it must be to do with screen size then, maybe you can't reproduce by resizing the browser.

**Comment by kyleplo** [comment]
I still can't on Edge:
![image](https://user-images.githubusercontent.com/31634240/37420803-0c5019a4-278e-11e8-9230-9f8875113484.png)

**Comment by python-megapixel** [comment]
> I still can't on Edge:

It's the first modal you see, which says "We're excited for you to try it"

**Comment by kyleplo** [comment]
> It's the first modal you see, which says "We're excited for you to try it"
Oh, now I see.

**Comment by thisandagain** [comment]
The minimum supported resolution for Scratch 3.0 is currently 1024 wide X 768 tall.

**Comment by python-megapixel** [comment]
> The minimum supported resolution for Scratch 3.0 is currently 1024 wide X 768 tall.
I don't want to be rude, but how is that meant to work with tablets and phones?

**Comment by thisandagain** [comment]
@python-megapixel Scratch 3.0 supports tablets that are 1024x768 or greater (this includes all iPads and most Android tablets). Support for phones will come later.
