### ISSUE TITLE
Highlighted text appears draggable in editor

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#162]
### Expected Behavior

Maybe the ghosted/ transparent text should not be draggable, and whatever you clicked on, e.g. the sprite, should still be draggable?

### Actual Behavior

When you highlight multiple bits of text, you can end up apparently dragging all of them around (they don't actually move, but the image is shown while dragging) - I don't know if we want that?

![out](https://cloud.githubusercontent.com/assets/1320456/23468279/6293a352-fe6e-11e6-82a4-5cfc5a32d2d9.gif)

### Steps to Reproduce

- Highlight text from the sprite pane
- Click on the cat sprite and drag it

### Operating System and Browser

_Mac OS X El Capitan 10.11.6, Chrome Version 56.0.2924.87 (64-bit)_

**Comment by lifeinchords** [comment]
The dragging issue will be fixed in #155 

I agree @jwzimmer it'll look much better if we made it all non selectable. 2 cases come to mind where it might be useful to have them selectable, for:
- the image, it's useful sometimes to easily drag and drop an image to desktop for remixing, editing
- the name, in other languages, some folks might want to highlight it, to copy paste into google for search and/or translate

Are either of these a concern? 
/cc @carljbowman

**Comment by liam4** [comment]
>the name, in other languages, some folks might want to highlight it, to copy paste into google for search and/or translate

Maybe, but I'm not sure I'd really consider it a huge concern, since the sprite info part actually has a text field for the sprite name, which you can copy/paste from.

**Comment by griffpatch** [comment]
It's definitely worth styling any region that have clickable / dragable
items with the no select style to prevent the user initiating a selection
or dragging Dom elements unintentionally. Places that you don't drag are
fine to allow text selection from.

**Comment by carljbowman** [comment]
I agree with @liam4 and @griffpatch . I do not see a use-case that is more important than being able to drag sprites without interruption. There are other ways of getting the information within the sprite tile.

**Comment by lifeinchords** [comment]
Thanks for feedback + thoughts @liam4 @griffpatch @carljbowman 
Icon labels in `SpriteInfo` component fixed in #155. 
Will update the same behavior to sprites next.
