### ISSUE TITLE
Say & Think blocks: Uncaught TypeError: Cannot read property 'warpMode' of null

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1623]
### Expected Behavior

No errors

### Actual Behavior

Uncaught error when using say and think blocks

### Steps to Reproduce

On https://llk.github.io/scratch-gui/develop/
Click on 'say hello for 2 seconds' or 'think hmm for 2 seconds'
After the 2 seconds is up, the error happens.

### Operating System and Browser
Windows 10 Chrome

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/977
