### ISSUE TITLE
I modified scratch-blocks part but how  can I make the new version work well with the scratch-gui part

### ISSUE THREAD

**Issue by hbwxl** [LLK/scratch-gui#1626]
I forked the scratch-blocks repository and modified it. I want to start my scratch-gui with my scratch-blocks part and I modify the package.json file at line 92  like this : " scratch-blocks : git://github.com/jyh129143/scratch-blocks.git". When I start scratch-gui, some error happened. It shows that scratch-blocks module not find. How can I solve it?

**Comment by apple502j** [comment]
You should have scratch-gui clone and modify codes in node_modules/scratch-blocks
You need node.js

**Comment by towerofnix** [comment]
Node doesn't know to use your version of scratch-blocks in scratch-gui; when you do `npm install` from scratch-gui, it just installs the most recent version of -blocks on NPM (which naturally isn't your version).

So, what you need to do is remove the `scratch-blocks` folder from `node_modules` (`$ cd scratch-gui; rm -rf node_modules/scratch-blocks`). Then, create a symbolic link (i.e. an alias) between `node_modules/scratch-blocks` and `/path/to/your/fork/of/scratch-blocks` (`$ cd scratch-gui; ln -s /path/to/your/fork/of/scratch-blocks node_modules/scratch-blocks`).

So in a command line:

```
$ cd scratch-gui
$ rm -rf node_modules/scratch-blocks
$ ln -s /path/to/your/fork/of/scratch-blocks node_modules/scratch-blocks
```

**Comment by hbwxl** [comment]
I tried you method but a new problem arise.

![qq 20180319105901](https://user-images.githubusercontent.com/12251548/37575909-8e1c714c-2b64-11e8-9dd6-5fbda0446604.png)

so what should I do to solve that?

**Comment by hbwxl** [comment]
I really appreciate it that you spend time helping me. I managed to build it but I still come across with the problem released above.

**Comment by thisandagain** [comment]
@hbwxl What version of Node and NPM are you using?

**Comment by hbwxl** [comment]
My version for Node and Npm are v8.9.4 and 5.6.0.I found that I didn't run "npm install" command for scratch-blocks before.Now this problem has been solved.Thanks for your reply.

**Comment by qiansitong** [comment]
I did as you said above but I still  come across with the following problem ! How can I solve it?   I’m truly grateful for your help

![0fbbb7b9-1589-429f-9a67-309aa6e89577](https://user-images.githubusercontent.com/24642743/37968800-b61a374e-3201-11e8-9561-8e111414307d.png)
