### ISSUE TITLE
Is there a way to save the current stage as a png/jpeg file?

### ISSUE THREAD

**Issue by asgaria** [LLK/scratch-gui#1629]
I'm currently working on a project to make a learning tool for kids, using Scratch as the basis. I'm making a projects page for the tool which features all of the projects made, and want to have each project have its own thumbnail. I was hoping to figure out a way to save what is presented on the stage as an image file, and then download that image. Is there a function already made that allows for that?

**Comment by apple502j** [comment]
+1 Right-click (or long-press for touch) stage and "Save picture of stage" - the same as 2.0

**Comment by kyleplo** [comment]
@apple502j That hasn't been implemented yet, but @asgaria you can currently right click and select "Save image as..." in most browsers.

**Comment by paulkaplan** [comment]
You might be able to use `canvas.toDataURL()` on the stages canvas element to retrieve a snapshot of the stage? https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

**Comment by luofei614** [comment]
why canvas.toDataURL()  not work ,   it will  get  a  black  picture @paulkaplan

**Comment by wooden1985** [comment]
@joker314 how to resolve？

**Comment by apple502j** [comment]
I'm on it!
