### ISSUE TITLE
 Clicking sprites in sprite pane causes scroll in the block pane

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#163]
### Expected Behavior

Clicking sprites in sprite pane should not cause scroll in the block pane.

### Actual Behavior

Clicking sprites in sprite pane causes scroll in the block pane.

![out2](https://cloud.githubusercontent.com/assets/1320456/23468303/766f1ef6-fe6e-11e6-9032-8fc1c20871fa.gif)

### Steps to Reproduce

- Click back and forth between two sprites in the sprite pane
- Watch the block pane

### Operating System and Browser

_Mac OS X El Capitan 10.11.6, Chrome Version 56.0.2924.87 (64-bit)_

**Comment by jwzimmer** [comment]
Note: using the X in the upper right of the sprite to delete it also causes the scroll (you are still clicking the sprite).

**Comment by jwzimmer** [comment]
Dragging a sprite across the stage causes the block pane to scroll slightly as well.

**Comment by bigeyex** [comment]
solved with [this pull request](https://github.com/LLK/scratch-blocks/pull/867)
