### ISSUE TITLE
Should more blocks be simultaneously visible (in the block pane)?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#164]
### Expected Behavior

I would like to be able to see more blocks at the same time, in order to be able to easily find the block I want and remember what my options are.

### Actual Behavior

Personally, I find it a little hard to use Scratch when I can see so few blocks in the block pane at a time; I end up scrolling a lot

<img width="255" alt="screen shot 2017-02-28 at 2 05 20 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468340/8ef87b16-fe6e-11e6-9ccb-4a641078ca63.png">

### Operating System and Browser

_Mac OS X El Capitan 10.11.6, Chrome Version 56.0.2924.87 (64-bit)_

**Comment by chooper100** [comment]
Support for less spacing between blocks in the palette - they are already big enough to avoid issues with touch input and accidentally tapping the wrong block

Moreover, once you create a variable in the data category, you'll notice the blocks have less spacing between them than in other categories. I think the spacing there is good but we should have consistency between the other categories
