### ISSUE TITLE
preview doesn't load on 2012 ipad, really slow on iPad Pro 2016

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-gui#1642]
Tried loading preview.scratch.mit.edu on a iPad 2012 with both Chrome 64.0.3282.112 and Safari, and it failed to load (I didn't crash, but I suspect it just never managed to get the resources needed). 

On newer, iPad Pro 2016, it took ~5 minutes, but it did load eventually. 

@rschamp @ericrosenbaum - per our conversation on Monday

**Comment by morantsur** [comment]
Not sure if it's related, but trying to load on another iPad, version 9.1 which connect to dev tools gave me this error:

![image](https://user-images.githubusercontent.com/15109618/37873385-9a8558f8-3024-11e8-8b68-8aa30f2823b7.png)

**Comment by thisandagain** [comment]
We will not be supporting < iOS 11. Closing.
