### ISSUE TITLE
On ipads, opening the sprite library opens the keyboard

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-gui#1644]
On an iPad, when clicking the add sprite / costume/ backdrop button, the library is loaded with the search bar focused, which leads to the keyboard popping up. 

With the smaller screen size, that means you barely see the sprites, as the keyboard takes over half the screen.

@rschamp @ericrosenbaum

**Comment by thisandagain** [comment]
As discussed, it may be a good idea to not focus the search field upon opening a library on touch devices.
