### ISSUE TITLE
On 2012 ipad, the add sprite/backdrop image in not centered

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-gui#1646]
![img_20180306_161137277](https://user-images.githubusercontent.com/15109618/37702598-badafbd4-2cfb-11e8-87b2-c243040b5284.jpg)

Happened on iPad 2012/Chrome 64.0.3282.112 and Safari, didn't happen on iPad Pro 2016/ Chrome 64.0.3282.112 and Safari

@rschamp @ericrosenbaum

**Comment by thisandagain** [comment]
@morantsur What version of iOS is this iPad running?

**Comment by morantsur** [comment]
@thisandagain I've seen it happen with iOS 9.1, and after updating to 11 is was fixed.

**Comment by thisandagain** [comment]
@morantsur Great! That would make sense. It is unlikely that we will support < iOS 11 given our use of WebGL and Web Audio APIs.

**Comment by thisandagain** [comment]
Compatibility matrix tracked in https://scratch.mit.edu/preview-faq
