### ISSUE TITLE
Allow duplication of an entire stack of blocks (from hat block down)

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#165]
### Expected Behavior

I expect to be able to duplicate a stack of blocks, or an individual block.

### Actual Behavior

How do I duplicate a stack of blocks? I can get it to duplicate a block or a loop & its contents, but not the whole stack from hatblock down.

### Repro

I am able to repro this by creating a stack of blocks with a loop and other blocks, e.g. screenshot below. I can duplicate each block and the contents of the for-loop, but not the whole stack.

<img width="283" alt="screen shot 2017-03-03 at 2 55 23 pm" src="https://cloud.githubusercontent.com/assets/1320456/23566802/749ec2de-0021-11e7-963d-f5b4636cda7c.png">

### Operating System and Browser

_Mac OS X El Capitan 10.11.6, Chrome Version 56.0.2924.87 (64-bit)_

**Comment by thisandagain** [comment]
Moved to LLK/scratch-blocks#823
