### ISSUE TITLE
Can Drag in Fullscreen

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#1653]
### Expected Behavior

When in fullscreen, you shouldn't be able to drag a sprite.

### Actual Behavior

When in fullscreen, you can drag a sprite.

### Steps to Reproduce

Make a project
Go to fullscreen
Drag a sprite

### Operating System and Browser

Chrome on Windows 10

**Comment by kyleplo** [comment]
It should drag if the user has used the 
![image](https://user-images.githubusercontent.com/31634240/37874191-a3f6c290-2ff8-11e8-8c53-00b8eae98e75.png) block.

**Comment by unize4** [comment]
I also have this problem.
 I solved this problem temporarily by judging the state of the sprite in the 'onStartDrag' function of 'stage.jsx' when in fullscreen.
like this：
`if (!this.props.vm.editingTarget.draggable) return;`
