### ISSUE TITLE
Add "coming soon" item to extension library for Micro:bit

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#1655]

**Comment by carljbowman** [comment]
**Extension Library Image**
<img width="300px" src="https://user-images.githubusercontent.com/3409578/38524905-4c6d40a8-3c1e-11e8-9617-201f585568a9.png"/>

**Block Icon**
Coming soon... - @carljbowman

**Comment by thisandagain** [comment]
Awesome. Thanks @carljbowman!

**Comment by wwj718** [comment]
I have already finished part ：）

![image](https://user-images.githubusercontent.com/3153878/38566855-54e869c0-3d17-11e8-9d9f-d08ea73913b7.png)

**Comment by wwj718** [comment]
this is the lastest version（add the HAT block）

![image](https://user-images.githubusercontent.com/3153878/38567023-b007182e-3d17-11e8-8f12-3f8b6a0094e0.png)

I make the scratch3-adapter（using zeromq） to  connect  scratch3.0 to hardware，the adapter software is a plugin system and it can run in windows and mac . Developers can can write their own plugins in our scratch3-adapter

We have already made some extension  in scratch3-adapter : extension for cozmo; extension for microbit , extension for BB-8 ; extension for raspberrypi ; extension for mqtt ， and so on

We will put it on github later ：）
