### ISSUE TITLE
When you drag a script onto another sprite, it stays in original sprite's scripting area

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#166]
### Expected Behavior

If I drag a script onto another sprite, it should be added to that sprite's scripting area

### Actual Behavior

I dragged a script into another sprite and the script was dropped into sprite 1's scripting area in the lower right (it looks like it disappears)

![out](https://cloud.githubusercontent.com/assets/1320456/23566488/115d993a-0020-11e7-936b-c1a84776922b.gif)

<img width="820" alt="screen shot 2017-03-03 at 2 48 12 pm" src="https://cloud.githubusercontent.com/assets/1320456/23566631/c775c706-0020-11e7-8982-7f6cf7a9a022.png">

### Repro

- Add a 2nd sprite
- Create a script
- Duplicate the hat block
- Duplicate the loop and join it to the hat
- Now you have a duplicate stack
- Drag it onto the 2nd sprite in the sprite pane
- Let it go
- It disappears from the 1st sprite's scripting area
- Click on the 2nd sprite
- Note that it's not in the 2nd sprite's scripting area
- Return to 1st sprite
- Scroll down to the lower right, there is the duplicate script

### Operating System and Browser

_Mac OS X El Capitan 10.11.6, Chrome Version 56.0.2924.87 (64-bit)_

**Comment by jwzimmer** [comment]
Reported during the internal playtest 3/3/17:
> Tried to drag a stack into a sprite and the stack dissappeared. UPDATE: just kidding! It just went far down into the editor for the original sprite (I had to scroll to find it).

**Comment by Airhogs777** [comment]
Can I propose that when dragging scripts to another sprite, there's as much indication of what's going on as possible? Maybe when hovering over a sprite and dragging a script:

- there's a plus-cursor to indicate that scripts are being added to the hovered sprite
- the sprite in the sprite-selection area is highlighted in some way
- in the scratch-blocks area, the original script is still visible in some way to indicate that it'll be duplicated and still available in the original sprite. It could become semi-opaque or it could be styled like an insertion-marker
