### ISSUE TITLE
Rendering of Scratch 2.0 costumes with text is weird/partially cut off

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#1661]
### Expected Behavior

Costumes should look the same on the stage in Scratch 2.0 and Scratch 3.0.

### Actual Behavior

The following project has the words on each of the 'screens' of the quiz cut off:
https://preview.scratch.mit.edu/#209798686

Examples of Scratch 2.0 vs. 3.0:

In 2.0:

![image](https://user-images.githubusercontent.com/1786240/37849859-9ad70cfa-2eaf-11e8-9f3e-336330fc135f.png)

In Scratch 3.0:
![image](https://user-images.githubusercontent.com/1786240/37849919-d6d6cf88-2eaf-11e8-9f1d-bd930a6a9f88.png)

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/1512
