### ISSUE TITLE
There should not be an Empty Sprite in the sprite library

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#1667]
Expected Behavior
When browsing the sprite library there should not be a blank sprite with the name Empty.

Actual Behavior
When browsing the sprite library there is a blank sprite with the name Empty.

**Comment by mrjacobbloom** [comment]
Not sure this is an enhancement as much as a bug report

**Comment by paulkaplan** [comment]
No longer an empty sprite in the library.
