### ISSUE TITLE
Pen Text Engine not working

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#1673]
### Expected Behavior

Project should run normally:
https://scratch.mit.edu/projects/195483628/

### Actual Behavior

Project loads, but does not run:
https://llk.github.io/scratch-gui/develop/#195483628

### Operating System and Browser

Mac OS 10.13.3  |  Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by Kenny2github** [comment]
Actually, the project does seem to run, but anything involving pen (in this case, everything :stuck_out_tongue: ) seems to not work. I'd imagine that's due to this error:
![image](https://user-images.githubusercontent.com/28599280/37969525-891942f6-3203-11e8-8a4d-a727c3a26b52.png)

**Comment by thisandagain** [comment]
Yup. It appears to be an issue with either the specmap or the pen extension itself.

**Comment by hedgehog125** [comment]
@Kenny2github I've seen that error a lot in pen projects so it's probably that.

**Comment by apple502j** [comment]
Oh, It uses hacking!

**Comment by apple502j** [comment]
#767

**Comment by thisandagain** [comment]
Tracking in #767
