### ISSUE TITLE
Ctrl-Z in the costume editor undoes things in the block editor instead

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-gui#1674]
### Expected Behavior

Pressing Ctrl/Cmd-Z in the paint editor undoes the most recent change in the costume editor (equivalent to clicking the undo button).

### Actual Behavior

The paint editor doesn't handle the undo (no change in the costume).
The block editor handles the undo (blocks move/delete/change) but the user can't see that.

Switching back to the block editor shows that the blocks have changed.

This may explain some of the feedback that says that scripts disappeared after editing costumes.

### Steps to Reproduce

1. Open a new project
2. Add some blocks
3. Switch to the "Costumes" tab
4. Make some changes (e.g. draw with pen)
5. Keyboard undo repeatedly
6. Switch back to blocks tab
7. Notice that your blocks have disappeared

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-paint/issues/38
