### ISSUE TITLE
Value balloon dosen't go away when extension is added.

### ISSUE THREAD

**Issue by flamergamer1234** [LLK/scratch-gui#1680]
### Expected Behavior

Value balloon goes away when the block view scrolls to the extension.

### Actual Behavior

The value balloon stays present.

### Steps to Reproduce

Click on any reporter/boolean block, and add an extension while the balloon is up

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31465218/38048720-2351d924-3294-11e8-9b29-0c4888886ec9.gif)

### Operating System and Browser

OS X 10.11.6, Chrome Version 65.0.3325.181 (Official Build) (64-bit) (Just tried on Windows, also occurs there.)

**Comment by thisandagain** [comment]
@rachel-fenichel Any thoughts on this one?

**Comment by rachel-fenichel** [comment]
Oh nice.  It also does it with the color picker:
![4d4a02cb-532a-4835-96f1-d503a4cf5231](https://user-images.githubusercontent.com/13686399/38054978-526e9a8c-328d-11e8-8c40-b408043c9d7c.gif)


Call `hideChaff()` when opening the extension picker.  It will also fix problems with input editors staying open while the extension picker is open.

**Comment by paulkaplan** [comment]
Fixed by https://github.com/LLK/scratch-gui/pull/2107
