### ISSUE TITLE
Language tooltip looks weird on long tooltips

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1691]
![image](https://user-images.githubusercontent.com/31634240/38112774-f167bc3e-3370-11e8-9a26-2fe443023235.png)
This only happens with longer tooltips such as "Don't worry, we're on it 🐱"

Windows Chrome

**Comment by bartljak** [comment]
What is the expected behavior for this?

**Comment by kyleplo** [comment]
For the tooltip to appear below, not to the side. (or move the arrow to the side)

**Comment by bartljak** [comment]
Would making the tooltip always appear to the right of the language selector(similar to how the tooltip always appears to the left for the scratch-cat icon in the top right) be an appropriate fix for this?

**Comment by bartljak** [comment]
This can be closed now
