### ISSUE TITLE
Sprite jumped from set location to somewhere else (along the X axis)

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#170]
### Expected Behavior

I expect -150 and 150 to be symmetric around 0 on the X axis in the project pane. I expect sprites set to a location to stay at that location.

### Actual Behavior
Something weird happened with location; -150 and 150 were not symmetric around 0, then I changed value of effect block from fisheye to whirl, and the sprite moved to be symmetric.
When I switched fisheye --> whirl, the J sprite repositioned itself to be the same distance from W as the Z is.

<img width="714" alt="screen shot 2017-03-02 at 2 34 58 pm" src="https://cloud.githubusercontent.com/assets/1320456/23524454/b4d46a08-ff58-11e6-8ff3-44b53364b610.png">

### Operating System and Browser

_Mac OS X El Capitan 10.11.6, Chrome Version 56.0.2924.87 (64-bit)_

**Comment by paulkaplan** [comment]
Going to close this since we can't repro.
