### ISSUE TITLE
Point Towards block should have the option Random in the drop down

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#1702]
The Point Towards block has should have a Random Direction option in the dropdown.  

![randomposition2](https://user-images.githubusercontent.com/1088291/38500646-031c7b20-3bd9-11e8-9b7e-56b8cf799e33.png)

This would pick a random number between -180 and 180 and point in that direction.  There is currently a dropdown in the "point towards" block that I think would be a good place to put this option.

**Comment by hedgehog125** [comment]
Shouldn't that be point towards random sprite? Or an option in point in direction?

**Comment by kyleplo** [comment]
Why would you want to do this?

**Comment by hedgehog125** [comment]
@kyleplo do you mean point to a random sprite? Or on the point in direction block?

**Comment by thisandagain** [comment]
@BryceLTaylor Can you please clarify / provide a sufficient description? I'd like to open this up as "help wanted".

**Comment by kyleplo** [comment]
@hedgehog125 Both.

**Comment by BryceLTaylor** [comment]
I have updated the issue above.

I meant point in a random direction, not towards a random sprite.  Let me know if you need more information!

**Comment by kyleplo** [comment]
What about something like this?
![image](https://user-images.githubusercontent.com/31634240/38277063-1f6524f8-3765-11e8-9671-abc1c1177920.png)
![image](https://user-images.githubusercontent.com/31634240/38277092-37986026-3765-11e8-9412-162acd98f387.png)

**Comment by Kenny2github** [comment]
Wording nitpick: I'd say "random direction" would be better than "random position". "point towards random direction" seems more logical than "point towards random position".

**Comment by thisandagain** [comment]
@kenny2github Agreed. @BryceLTaylor can you update the spec?

**Comment by griffpatch** [comment]
"Point towards random direction"? Surely it's "Point *in* random
direction"? :)

**Comment by thisandagain** [comment]
@griffpatch We aren't going to mutate the block based on the menu drop-down. Because "pointer" is the default I recommend we keep it as-is.

**Comment by griffpatch** [comment]
Face Palm... Of course :)

**Comment by BryceLTaylor** [comment]
Sorry, I typed the wrong thing in the above image.
![randomposition2](https://user-images.githubusercontent.com/1088291/38500466-7a9474ce-3bd8-11e8-8006-133fd62594d7.png)

Also it should be in the same font as the existing text.

**Comment by bartljak** [comment]
Is this also going to require a change to code in the scratch-vm repo? I don't see any code in the gui repo that would implement the behavior for this random direction option.

**Comment by thisandagain** [comment]
@bartljak Yes. This will require work in both the blocks and the VM. You may want to wait a week or so as we'll be consolidating both block rendering and the VM opcode definitions completely into the VM.

**Comment by bartljak** [comment]
@thisandagain Ok good to know. In the mean time I think I have created a fix but I'm not really familiar with testing the VM code on my own machine...

**Comment by ianobermiller** [comment]
You can already do this by using the "point in direction" and "pick random" blocks: 
![image](https://user-images.githubusercontent.com/897931/45794674-82a22180-bc4c-11e8-9820-b16b36835836.png)
Is it worth adding this into "point towards" as well?

**Comment by towerofnix** [comment]
@ianobermiller good question. Probably worth considering that there's already "go to (random position)", which is equal to "go to x: (pick random -240 to 240) y: (pick random -180 to 180)".
