### ISSUE TITLE
Consider re-implementing moving sprites to the front when dragged or other non-block method to change ordering

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#1703]
In Scratch 2 dragging a sprite moved it to the front, so you didn't have to use a block to change the order of the sprites.  There may be a better option, but it would be good to give a way to change the ordering without code.

We observed that kids wanted to change the order but didn't know how, possibly because that was how they were used to it working in Scratch 2.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/1870
