### ISSUE TITLE
Prevent accidentally losing trim operation in sound editor

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1709]
### Expected Behavior

It should be clear how to accept a trim operation, and we should try to prevent the error in which people use the trim feature but don't realize that it will not be saved unless they press the "save" button.

### Actual Behavior

We see people adjusting the trim until it sounds right, and then navigating away from the sound editor (which causes the trim to be lost).

We should consider:

- Automatically accepting a trim operation that has not been saved when you navigate away from the current sound in the editor (by switching to another sound or by switching tabs)
- Some other way to make the workflow clearer. For example, the trim button could bring up a modal like the "record" modal, but only for trimming. 

cc @carljbowman @paulkaplan

**Comment by hedgehog125** [comment]
Maybe the other buttons could deactivate while you edit it and there could be a green tick and a red cross to confirm and cancel?

**Comment by hedgehog125** [comment]
On the record modal there could be a tooltip on the x and it could say something like "cancel"? Or, when you click the x it could confirm if you really want to delete it or not.

**Comment by Kenny2github** [comment]
Perhaps a confirmation when switching away? Like "are you sure you want to leave? you haven't finished the trim yet!"

**Comment by kyleplo** [comment]
@Kenny2github 
![image](https://user-images.githubusercontent.com/31634240/38275221-2e9bf7d6-375f-11e8-956a-3b347d943d8d.png)

**Comment by paulkaplan** [comment]
Trim no longer exists, closing!
