### ISSUE TITLE
Whirl effect showed on sprite when only fisheye was set

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#171]
### Expected Behavior

I expect setting an effect to 0 to erase the effect, and I don't expect to see whirl when I have chosen fisheye.

### Actual Behavior

Something weird happened with fisheye/ whirl; setting the value to 0 didn't remove the effect until I changed fisheye to whirl

The effect looks like whirl, but I only have fisheye set for this sprite:
<img width="1280" alt="screen shot 2017-02-28 at 2 51 15 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468504/00651052-fe6f-11e6-9233-9f8c6fa229d2.png">
Changing fisheye -> whirl in the set [effect] to 0 block returned the sprite to normal:
<img width="1277" alt="screen shot 2017-02-28 at 2 59 52 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468498/00408354-fe6f-11e6-8485-6656a76003a3.png">

**More pics of the fisheye/ whirl stuff**

This effect on the J looks like whirl, although whirl isn't being used here. It is being used on another sprite iirc.
<img width="1279" alt="screen shot 2017-02-28 at 3 10 18 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468506/00791db8-fe6f-11e6-8bff-53539e482e83.png">

This effect looks like fisheye.
<img width="841" alt="screen shot 2017-02-28 at 3 10 33 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468511/00a11750-fe6f-11e6-873e-c2c14badfe21.png">

On stopping the project, for some reason the J looks like it has "whirl" on it; resetting fisheye effect to 0 doesn't remove the appearance. But changing fisheye -> whirl in the set to 0 block does.
<img width="469" alt="screen shot 2017-02-28 at 3 10 44 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468510/009fc198-fe6f-11e6-9ffc-362e981f646d.png">
<img width="490" alt="screen shot 2017-02-28 at 3 10 53 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468508/008973fc-fe6f-11e6-87b1-e28b16f8caa6.png">
<img width="452" alt="screen shot 2017-02-28 at 3 10 58 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468512/00a0ea82-fe6f-11e6-99f2-09b020fd48a3.png">
<img width="1012" alt="screen shot 2017-02-28 at 3 11 01 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468509/009ef70e-fe6f-11e6-953b-c3cbf5de8f6d.png">

### Operating System and Browser

_Mac OS X El Capitan 10.11.6, Chrome Version 56.0.2924.87 (64-bit)_

**Comment by thisandagain** [comment]
Moved to LLK/scratch-render#151
