### ISSUE TITLE
Can't find package scratch-paint's version: 0.2.0-prerelease.20180403143543

### ISSUE THREAD

**Issue by luofei614** [LLK/scratch-gui#1712]
when  run npm install    show the error:
Install fail! Error: [scratch-paint@0.2.0-prerelease.20180403143543] Can't find package scratch-paint's version: 0.2.0-prerelease.20180403143543

**Comment by paulkaplan** [comment]
Hmm? It looks like it is published on NPM? https://www.npmjs.com/package/scratch-paint, and running `npm info scratch-paint version` gives that newest version, and it built on travis?

**Comment by paulkaplan** [comment]
Closing due to lack of info.
