### ISSUE TITLE
Cannot add "Video Sensing" extention

### ISSUE THREAD

**Issue by hedgehog125** [LLK/scratch-gui#1719]
### Expected Behavior

As the video sensing extension no longer says it's coming soon you should be able to add it into the project.

### Actual Behavior

The extension doesn't add and there's the following error in the console...
```

videoSensing:1 GET https://llk.github.io/scratch-gui/develop/videoSensing 404 ()
shared-dispatch.js:137 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': DOMException object could not be cloned.
    at https://llk.github.io/scratch-gui/develop/extension-worker.js:721:30
    at new Promise (<anonymous>)
    at WorkerDispatch._remoteTransferCall (https://llk.github.io/scratch-gui/develop/extension-worker.js:710:20)
    at WorkerDispatch.transferCall (https://llk.github.io/scratch-gui/develop/extension-worker.js:647:57)
    at WorkerDispatch.call (https://llk.github.io/scratch-gui/develop/extension-worker.js:614:38)
    at https://llk.github.io/scratch-gui/develop/extension-worker.js:229:30
``` 
I'm guessing given that there's a 404 error, the extension has been enabled but the code isn't yet on the database.

### Steps to Reproduce

Add the video sensing extension.

### Operating System and Browser

Google Chrome 65.0.3325.181 (Official Build) (64-bit) on Mac OS X 10.11.6.

**Note:** I'm just saying this in case it hasn't been noticed.

**Comment by paulkaplan** [comment]
Would you mind trying again, it may have been caught between deployments. I don't see that issue on develop right now.

**Comment by hedgehog125** [comment]
Oops, forgot to close it since then.
