### ISSUE TITLE
Sprites are cut-off, missing, off-center in sprite library

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#172]
### Expected Behavior

I expect all the sprites to be visible, approximately centered/ consistent in size, and not cut-off.

### Actual Behavior

Some of the sprites seem to be missing bits, off-center, or missing.

Initially abby-d's legs seemed to be missing, but now I am seeing them.
<img width="216" alt="screen shot 2017-02-28 at 3 05 06 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468503/005fd57e-fe6f-11e6-84ed-6f5067646843.png">

However, a lot of other sprites are still examples of this issue:
<img width="377" alt="screen shot 2017-03-03 at 1 03 57 pm" src="https://cloud.githubusercontent.com/assets/1320456/23562882/41376d6a-0012-11e7-99a5-6d895da0aae9.png">
<img width="370" alt="screen shot 2017-03-03 at 1 03 49 pm" src="https://cloud.githubusercontent.com/assets/1320456/23562881/41371ac2-0012-11e7-9c32-e9ecb6fd8657.png">
<img width="951" alt="screen shot 2017-03-03 at 1 03 34 pm" src="https://cloud.githubusercontent.com/assets/1320456/23562884/41416b62-0012-11e7-9603-d3e3506e2d0b.png">
<img width="562" alt="screen shot 2017-03-03 at 1 02 55 pm" src="https://cloud.githubusercontent.com/assets/1320456/23562885/414361a6-0012-11e7-9a57-5e1cb21801a5.png">

### Steps to Reproduce

- Look in the costume/ sprite library

### Operating System and Browser

_Mac OS X El Capitan 10.11.6, Chrome Version 56.0.2924.87 (64-bit)_

**Comment by liam4** [comment]
Here's a few cases I found:

![Button1 missing](https://cloud.githubusercontent.com/assets/9948030/23568099/81db0396-002f-11e7-9450-25ed0154f16d.png)

![Dove1 cut off](https://cloud.githubusercontent.com/assets/9948030/23568108/89731a8a-002f-11e7-9238-b372980e0d02.png)

![Muffin missing](https://cloud.githubusercontent.com/assets/9948030/23568121/9178eb24-002f-11e7-8180-ba3477619a40.png)

All of these on Safari 10.0, on macOS 10.12.

**Comment by jwzimmer** [comment]
Also reported during the internal playtest.

**Comment by tmickel** [comment]
The basic problem, I think, is that SVGs are rendered differently by the Scratch 2.0 editor than SVG renderers in-browser.

We started resolving some of these "quirks" in project rendering by transforming SVGs in scratch-render (https://github.com/LLK/scratch-render/blob/develop/src/svg-quirks-mode/svg-renderer.js). But scratch-gui is just using a basic svg-to-canvas with the untransformed SVG.

One way to make the sprite/costume library consistent with the project rendering would be to use this quirks transformer (or even just scratch-render) to render the library tiles. Alternatively, could fix the assets to be readily rendered by the browser.

**Comment by lifeinchords** [comment]
Thanks for reporting @jwzimmer and for sharing how it works @tmickel. Wondering if the bug below, is related to the image sizing:

![screen shot 2017-03-06 at 3 27 01 pm](https://cloud.githubusercontent.com/assets/716168/23628703/29cd8402-0283-11e7-80c8-11ac7169f5a0.png)

**Comment by paulkaplan** [comment]
@rschamp do you think it is worth creating a separate issue for resolving the story letter blocks vs. all of the SVG's? The letter blocks are the most severe (totally invisible) and highest priority (play test Thursday). 

WRT the letter blocks, they are not really missing, all the SVGs in that set just do not have an explicit `width` and `height` parameter, which it seems is important when using svg as the src for an image tag. I believe if you have an SVG with `viewBox="0 0 W H"` that adding `width="W" height="H"` would not impacting anything other than the way browsers render the svg-as-image.

**Comment by rschamp** [comment]
@paulkaplan I think a new issue for the letter blocks would probably be a good idea.

All of these strangely displaying SVGs are similarly odd in their format where they are either missing width/height or view box or both.  Currently they all display correctly in the renderer nonetheless, because of the special SVG rendering implemented there, which fixes a few issues at once. What I was thinking was that I could just render them all in the renderer and save out the fixed SVG file the renderer uses.  I think it would be possible to fix them all at once this way, but probably at first I will just try fixing the letters.

**Comment by rschamp** [comment]
@tmickel I totally missed your comment. @cwillisf and I were thinking in the longer term we should factor out the SVG transformer from scratch-render and use it wherever we need to display Scratch 2.0 SVGs. And also do some sort of conversion when we start saving assets out of 3.0 so that they are the transformed SVGs.

**Comment by jwzimmer** [comment]
Noted by @chrisgarrity during internal playtest 3/13/17: Star1 and Star3 don't show up in the library, but are fine in the editor.

**Comment by jwzimmer** [comment]
The costumes for the story sprites show up tiny & off-center in the editor (not visible in library).

<img width="573" alt="screen shot 2017-03-15 at 3 14 05 pm" src="https://cloud.githubusercontent.com/assets/1320456/23966602/5ad52c88-0992-11e7-951c-c0a2081be430.png">
<img width="575" alt="screen shot 2017-03-15 at 3 13 59 pm" src="https://cloud.githubusercontent.com/assets/1320456/23966601/5ad413c0-0992-11e7-851b-601d27837a44.png">
<img width="602" alt="screen shot 2017-03-15 at 3 13 52 pm" src="https://cloud.githubusercontent.com/assets/1320456/23966603/5ad6ebfe-0992-11e7-85ac-a47a6ddaac5e.png">

**Comment by paulkaplan** [comment]
Ray did a large fix for this. We should file any specific issues for this separately if they still exist.
