### ISSUE TITLE
Costumes don't appear in the paint editor after uploading an sb2

### ISSUE THREAD

**Issue by quachtina96** [LLK/scratch-gui#1734]
### Expected Behavior
An imported costume that is currently focused/selected should also appear in the paint editor. 
### Actual Behavior

An imported costume that is currently focused/selected does not appear in the paint editor:
![image](https://user-images.githubusercontent.com/10423718/38433610-8a8eb4ca-3999-11e8-8efa-5059ef008893.png)

### Steps to Reproduce

- Download Banana Time project. https://scratch.mit.edu/projects/195669255/ 
- upload sb2 file
- go to costumes

### Operating System and Browser

_e.g. Mac OS 10.13.3 Safari 11.03

**Comment by paulkaplan** [comment]
@quachtina96 I believe this is because the bitmap paint editor is not implemented yet, and we do not have converting rasters to vector happening automatically, right @fsih

**Comment by fsih** [comment]
Yes, that sounds right
