### ISSUE TITLE
Change defaults and ordering for > < = blocks 

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-gui#1739]
To help new learners more quickly recognize and use the > < and = operators, suggestion to add default value of 100 on the right-hand side. 
 
In addition, may help to order so that > is first (since that's used most often in projects). One suggestion is to put in the order that they are often said aloud  (at least in U.S.): > < = greater than, less than, equal to. (Currently equal to was put second to help minimize visual confusion so could order that way instead.)

**Comment by hedgehog125** [comment]
Yes, I've also noticed how you can't change the "<" block to a ">" block like you can in 2.0. This is quite a useful feature as it saves you getting out the right one, moving the values and then deleting the old block if you change your mind.

**Comment by hedgehog125** [comment]
@hedgehog125 maybe the same should apply other operators too? E.g and, or etc.

**Comment by hedgehog125** [comment]
There could also be some additional operators too such as >= <= != and maybe XOR? (although XOR might be too confusing for new Scratchers?)

**Comment by Kenny2github** [comment]
@hedgehog125 >=, <=, and != can be worked around with "not <", "not >", and "not =" respectively.

**Comment by hedgehog125** [comment]
@Kenny2github Yes, but they would save time and it could also make some things simpler for new Scratchers.
