### ISSUE TITLE
Mosaic effect quits changing, doesn't change value as mouse pointer moves

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#174]
### Expected Behavior

I expected the sprite to keep changing as I move the mouse pointer.

### Actual Behavior

Mosaic effect sometimes returns to 0 effect automatically? Why does mosaic stop changing the value?

![out4](https://cloud.githubusercontent.com/assets/1320456/23468497/003edd6a-fe6f-11e6-85e8-70e7562a9c48.gif)

### Operating System and Browser

_Mac OS X El Capitan 10.11.6, Chrome Version 56.0.2924.87 (64-bit)_

**Comment by liam4** [comment]
Can reproduce on macOS 10.12, on both Chrome 56 and Safari 10.

**Comment by jwzimmer** [comment]
Thanks @liam4!

**Comment by paulkaplan** [comment]
For context, in scratch 2 we have the same behavior: if you keep adding to the mosaic effect it eventually just stops changing.

Is this the type of effect we want to "wrap"? It is similar in a sense to the pitch effect (not sure if we wrap that or not).
