### ISSUE TITLE
How to run totally offline? where are the sound & pic resources?

### ISSUE THREAD

**Issue by lgh06** [LLK/scratch-gui#1742]
I can view http://localhost:8601/ in my browser.
It worked.
However, when I switch off my WIFI, sounds and pics are gone.

Where can I find pics in "Costume Library" and sounds in "Sound Library"? 
or, how to load static resources locally?
thx.

**Comment by thisandagain** [comment]
We have not yet started work on bundling the resources with the build. They are still loaded remotely.
