### ISSUE TITLE
Nothing in the preview page.

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#1743]
### Expected Behavior

_Please describe what should happen_
There should be text in the preview faq
### Actual Behavior

_Describe what actually happens_
Nothing.
![nofaq](https://user-images.githubusercontent.com/31377746/38492984-36088200-3c23-11e8-9faf-46392cff3a02.PNG)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
open https://scratch.mit.edu/preview-faq
### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_
I don't know where I can submit it, so I submited the issue here.

**Comment by towerofnix** [comment]
You're probably seeing a case of LLK/scratch-www#1829.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-www/issues/1829. Unfortunately the FAQ does not work if Google Docs is blocked. We will resolve this as we get closer to launch.
