### ISSUE TITLE
Remove "camera" from add sprite and add backdrop components

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#1744]
### Expected Behavior

- The "camera" option should only be available from the costume editor

### Actual Behavior

- The "camera" option is available in the costume editor as well as the sprite and backdrop components.

### Reference

![image](https://user-images.githubusercontent.com/747641/38496711-727eba94-3bcc-11e8-9c14-7fc985db2f3d.png)
![image](https://user-images.githubusercontent.com/747641/38496713-774f4f2a-3bcc-11e8-9e0b-f036f153b62c.png)
![image](https://user-images.githubusercontent.com/747641/38496718-7ea331ec-3bcc-11e8-9569-6a8a58c03267.png)

**Comment by apple502j** [comment]
Why?
I think we should keep it
No reason to remove

**Comment by thisandagain** [comment]
@apple502j There are quite a few options in those menus (with another one soon to be added) so removing an item is part of an effort to reduce decision density. In addition, many users do not have a webcam or microphone attached so hierarchically we'd like to deemphasize this. Lastly, there are moderation concerns with capturing from the webcam which is yet another reason to lower it's profile in the editor.
