### ISSUE TITLE
Refreshing page: play was interrupted by call to pause

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#175]
### Expected Behavior

I think it's reasonable that refreshing the page interrupts playing a project, I'm just not sure if the error in the console is how we intended to handle that.

### Actual Behavior

I refreshed the page and got an error (play was interrupted by call to pause); not sure if this is expected or not (doesn't seem unreasonable that this would interrupt project playing, but not sure if that's how we want to handle it).

<img width="1280" alt="screen shot 2017-02-28 at 3 19 05 pm" src="https://cloud.githubusercontent.com/assets/1320456/23468517/011bfc36-fe6f-11e6-8be8-54bf743e18d1.png">

### Steps to Reproduce

- Start a project with green flag
- Refresh the page while the project is playing
- Note content in console

### Operating System and Browser

_Mac OS X El Capitan 10.11.6, Chrome Version 56.0.2924.87 (64-bit)_

**Comment by tmickel** [comment]
long-time upstream blockly error: https://github.com/google/blockly/issues/299
