### ISSUE TITLE
Close buttons should not be over the new sprite menu

### ISSUE THREAD

**Issue by 77Tigers** [LLK/scratch-gui#1753]
### Expected Behavior
There shouldn't be a close button over over the new sprite menu.
![AN IMAGE GOES HERE...](https://user-images.githubusercontent.com/36101478/38550578-c87c2c78-3cae-11e8-84f5-19470317a189.PNG)

### Actual Behavior
Opposite of above.
![Can anyone see this text?](https://user-images.githubusercontent.com/36101478/38550208-b92b0466-3cad-11e8-9c9e-a1c692badc08.PNG)

### Steps to Reproduce

1. Press the sprite so the close button would be under the menu.
2. Hover over the menu.
3. The close button will be above the menu.

### Operating System and Browser

Windows NT 10.0, Chrome 65.0.3325.181

**Comment by bartljak** [comment]
This is a problem with the usage of z-index in the sprite-selector and sprite-selector-item css files. I tried changing the values around to fix this issue and cause the 'more buttons' tray to always appear over the close sprite button, but it causes issues with the unit tests(specifically importing scratch 2.0 projects). Does anyone have any ideas on how to fix this?

**Comment by bartljak** [comment]
@helioh2 Huh I am not sure why the test cases were not passing for me, I think I had set the z-index to 0, and you are setting it to 1, that must be the difference. Your pull request looks good to me!
