### ISSUE TITLE
Pen "clear" may be mistaken to mean "transparent"

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-gui#1756]
The word "clear" for pen is even more ambiguous than it already was. One possibility is to use  "clear all" within these blocks:

1) clear graphic effects, 2) clear sound effects, 3) clear 
would be:
1) clear all graphic effects, 2) clear all sound effects, 3) clear all [within Pen]

![image](https://user-images.githubusercontent.com/4721032/38574439-d18e6f34-3cc6-11e8-8476-24aaeef3d1c8.png)

**Comment by ntlrsk** [comment]
Another possibility is to say:
1) reset graphic effects; 2) reset sound effects, 3) erase all

**Comment by thisandagain** [comment]
Moved to LLK/scratch-vm#1056
