### ISSUE TITLE
Tooltip change "Sprite Library" to "Choose a Sprite"

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-gui#1759]
Kids often ask how they can pick or choose another sprite. So rather than "Sprite Library" on the tooltip  "Choose a sprite" would be more obvious. Same for backdrop.  (This use of the word library isn't so obvious.)

**Comment by mresmres** [comment]
- "Choose a Sprite"
- "Choose a Backdrop"
- "Choose a Sound"
- "Choose a Costume"
