### ISSUE TITLE
Blocks destroyed on mobile

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#1762]
### Expected Behavior

You should be able to drag blocks on any device, 

### Actual Behavior

On a mobile device, the blocks can get destroyed.

### Steps to Reproduce

Go to the gui on a mobile device.
Make a basic script with a loop.
Run the project.
Add a block before the loop.

### Operating System and Browser

I'm not exactly sure.

**Comment by hedgehog125** [comment]
Hmm, I thought you couldn't use it on mobile yet?

**Comment by paulkaplan** [comment]
Can you be more specific about the device that you are using? We have been using iPads on Safari, Microsoft Surface tablets, Android tablets, and have not seen this.

**Comment by paulkaplan** [comment]
I'm going to close this due to lack of activity/information. Feel free to reopen if you have more details, including device/OS
