### ISSUE TITLE
Blocks are positioned below the toolbar while dragged

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#1792]
### Expected Behavior

When you drag a ~~sprite~~ block so that it is touching the toolbar ("file", "edit", "give feedback", etc), the block should display above the toolbar; the block should be on top.

### Actual Behavior

The toolbar is on top; the block is under.

### Steps to Reproduce

Grab a block and drag it to the top of the screen, so that it's above (well, below, currently) the toolbar.

### Operating System and Browser

Debian (testing); Firefox 66.0b6.

---

@dalearn wrote in #959:

> On a similar note, blocks go under the title bar which should be discussed.  Should they go over everything except for the title bar or everything including the title bar?

(This issue was originally created for tracking sprites showing up below the toolbar, but eventually details about blocks being dragged over the toolbar were added; the former was fixed separately, so I edited this issue to track just the latter.)

**Comment by bartljak** [comment]
I know this is the behavior of Scratch 2.0, but I don't understand why it is the desired behavior. Why would a user want to drag a sprite out of the stage boundaries?

**Comment by towerofnix** [comment]
@bartljak I think that, though it would probably make more sense to have the sprite not be able to be dragged past the boundaries of where it can go with the motion blocks, that might be a little confusing to new users. They probably expect that something they're dragging will stick to their cursor. (Ping @paulkaplan since you're the one who implemented the editor drag mode and may have thoughts!)

**Comment by mrjacobbloom** [comment]
The backpack hasn't been implemented yet, but it would make sense for a user to try to drag a sprite from the stage into the backpack

**Comment by towerofnix** [comment]
Funnily enough, the canvas that dragged sprites are drawn in as well as the `blocklyBlockDragSurface` are both at high enough z-indexes that they would display over the toolbar. The trouble is that the overall `flex-wrapper` of scratch-gui's main area, below the nav bar, has `overflow-y: hidden`.

**Comment by benjiwheeler** [comment]
related to z-index (adding this comment in hopes of improving search/findability of related issues)

**Comment by benjiwheeler** [comment]
@towerofnix You're right that this is a rabbit hole! A new stacking context is created by several parents of the `<canvas class="stage_dragging-sprite..." ... />` element, so I don't know how we might change the relative stacking of the draggable element and the navbar, without rearranging the html itself.

**Comment by towerofnix** [comment]
@benjiwheeler Yeah, it's pretty crazy. :P I wonder if LLK/scratch-blocks#1855 is related to this trouble with the overflow property? In general, we're clearly seeing that block dragging is sort of messy with regards to being absolutely correct about z-indexes, overflows, etc (which we evidently aren't getting quite right, per issues like this).

Not that I intend to ask for an unnecessary rewrite of anything, but I wonder if changing the element where dragged elements are placed to be a child of the document body rather than the blockly workspace / component would help clean up these issues?

**Comment by benjiwheeler** [comment]
>  I wonder if changing the element where dragged elements are placed to be a child of the document body rather than the blockly workspace / component would help clean up these issues?

@towerofnix Yeah, I was thinking of that too.

**Comment by chrisgarrity** [comment]
Decided that we don't want to change the current behavior.

**Comment by towerofnix** [comment]
@chrisgarrity I think I agree for this specific issue, it makes some sense not to carry blocks over the toolbar :P

However, note that the pull request LLK/scratch-blocks#1895 actually more specifically fixes *other* aesthetic issues:

> I don't think it's filed, but this fixes an issue with blocks that is the same in principle as LLK/scratch-gui#1791; particularly, fixes the scrollbar showing up when you drag a block past the edge of the screen. Also fixes LLK/scratch-gui#953 (since toggling overflow is no longer necessary).

As far as *this* issue goes, the scratch-blocks PR only provides support for #4530, which was appropriately closed.

Note the comment at the start of the scratch-gui PR as I wrote it in 2019:

> Fixes #1792. Should be merged after LLK/scratch-blocks#1895. **(The other PR's fixes stands fine on their own too, though.)**

Just thought I'd clarify this so the other fixes remain on the table in case they were overlooked!
