### ISSUE TITLE
Crash when uploading file at Costumes screen. 

### ISSUE THREAD

**Issue by hahapang** [LLK/scratch-gui#1795]
Expected Behavior
Upload file successfully. 

Actual Behavior
Oops, something went wrong.

Steps to Reproduce
1.  Click Costumes.
2. Download a file.
3. Upload this file at Costumes screen.

Operating System and Browser

Mac OS 10.12.6
Chrome 
<img width="1062" alt="qq20180417-145006 2x" src="https://user-images.githubusercontent.com/26299904/38853276-54ca5498-424f-11e8-9174-29093b46e8f4.png">
<img width="774" alt="qq20180417-145017 2x" src="https://user-images.githubusercontent.com/26299904/38853286-5b6ddf40-424f-11e8-89d0-93b63df7ac4f.png">

**Comment by kchadha** [comment]
Resolved in #1796.
