### ISSUE TITLE
Version of Scratch-Blocks out of sync?

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#180]
### Expected Behavior

Following this PR landing https://github.com/LLK/scratch-blocks/pull/810 we expect variable blocks not to have left-click menus on them anymore.

### Actual Behavior

Left-click menus are still there.

Is something unexpected happening with the build system?

### Steps to Reproduce

Create a variable.

**Comment by rschamp** [comment]
The npm publish for the build after that PR was merged failed. I just rebuilt it and published, but now I am seeing some other errors in the playground. Investigating those now.

**Comment by rschamp** [comment]
This was a Travis issue, fixed.
