### ISSUE TITLE
Security issue with the View 2.0 Project button

### ISSUE THREAD

**Issue by python-megapixel** [LLK/scratch-gui#1801]
### Expected Behavior

On attempting to load an unshared project via the "View 2.0 Project" button, an error message should be shown.

### Actual Behavior
The unshared project loads normally as if it was a shared project.

### Steps to Reproduce
Try to load an unshared project into the editor by URL.

**Comment by hedgehog125** [comment]
Yes, however this can be useful sometimes. Like if you wanted to try running one of your own projects in Scratch 3.0 to see how well it works. (it's still not ideal though)

**Comment by python-megapixel** [comment]
@hedgehog125 I don't want people viewing my unshared projects this way

**Comment by python-megapixel** [comment]
@hedgehog125 I get your point though

**Comment by hedgehog125** [comment]
@python-megapixel there might be some cases where I would feel the same way. However, this (somewhat) exists already (I mean before 3.0 was indev) there are a few 3rd party tools that let you download projects and also view them in the browser. I suppose at least they wouldn't be able to get hold of the ids in the first place. Maybe it needs a login screen? Hmm...

**Comment by thisandagain** [comment]
We will resolve this when moving to the real project page later this summer.
