### ISSUE TITLE
Dragging a large sprite out of the stage causes cropping

### ISSUE THREAD

**Issue by bartljak** [LLK/scratch-gui#1806]
### Expected Behavior

When you drag a sprite out of the stage, the entire sprite should be visible.
<img width="1680" alt="screen shot 2018-04-17 at 7 19 17 pm" src="https://user-images.githubusercontent.com/6947753/38903735-6cf72ca6-4274-11e8-9c73-fca40ae66e1c.png">
(This is how larger sprites should behave)

### Actual Behavior

When you drag a sprite that is too big to appear fully in the stage, the sprite is cropped from the bottom up when it is dragged out of the stage. 
<img width="1680" alt="screen shot 2018-04-17 at 7 19 43 pm" src="https://user-images.githubusercontent.com/6947753/38903748-7c4521cc-4274-11e8-9d18-147ba65379a4.png">
(Notice how feet are cropped)

### Steps to Reproduce

1. Set a sprite's size to a large number so it no longer fits in the stage. (400 works for the Scratch Cat sprite)
2. Drag sprite out of stage.

### Operating System and Browser

Mac OS 10.13.4  |  64-bit Google Chrome 65.0.3325.181

**Comment by thisandagain** [comment]
Moved to LLK/scratch-blocks#1454
