### ISSUE TITLE
Some alignment issues in Edge

### ISSUE THREAD

**Issue by python-megapixel** [LLK/scratch-gui#1807]
### Expected Behavior

In Microsoft Edge, the text in the blocks in the blocks list should be aligned correctly

### Actual Behavior

In Microsoft Edge, the text in the blocks in the blocks list is too far to the left, meaning that the text goes off the edge of the block.

This is sometimes, but not always, rectified when the block is dragged to the scripting area and clicked several times.

### Steps to Reproduce
Go to [the preview site](https://preview.scratch.mit.edu) using Microsoft Edge.

### Operating System and Browser

Windows 10 Education, MS Edge 38

**Comment by thisandagain** [comment]
Moved to LLK/scratch-blocks#1455
