### ISSUE TITLE
Sprites go behind the pen layer

### ISSUE THREAD

**Issue by NitroCipher** [LLK/scratch-gui#1809]
When you use the block "go to [back]" the active sprite will appear behind the canvas pen layer. (I don't know if this was intended, or if it was a side effect of the new layer blocks.) This seems that it would be confusing to new scratchers who might think their sprite has disappeared, as there is currently no way to control the layering of the pen tool.

There are three ways I think this can be resolved:
 
1. You keep the pen canvas behind all sprites

2. You add a block that allows you to move a sprite above or below another. IE: "move above [sprite1]" "move above [pen layer]"

3. You implement a more extensive pen system as detailed [here](https://scratch.mit.edu/discuss/topic/234935/)

**Comment by hedgehog125** [comment]
The 3rd option could be really useful, I sometimes find myself needing to put pen above sprites but I can't.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/1066
