### ISSUE TITLE
Change in pen size when cloned

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#181]
Reported during internal playtest 3/3/17.

### Expected Behavior

I would expect pen size not to change in the cloned pen drawings, especially since no pen size blocks were used.

### Actual Behavior

In @christanbalch's project, the lines of the squares are smaller for the cloned squares versus the non-clones. There's no pen size blocks in the scripts.
<img width="780" alt="screen shot 2017-03-03 at 3 47 23 pm" src="https://cloud.githubusercontent.com/assets/1320456/23568490/c3c68a98-0028-11e7-97be-e18066f45bef.png">
<img width="781" alt="screen shot 2017-03-03 at 3 47 10 pm" src="https://cloud.githubusercontent.com/assets/1320456/23568491/c3c7a2d4-0028-11e7-93c2-a72c7f993057.png">

### Operating System and Browser

_Mac OS X El Capitan 10.11.6, Chrome Version 56.0.2924.87 (64-bit)_

**Comment by thisandagain** [comment]
Moved to LLK/scratch-vm#493
