### ISSUE TITLE
Variables not shown on stage upon import from Scratch 2 and displayed variables are not removed after loading another project

### ISSUE THREAD

**Issue by MarkusPiotrowski** [LLK/scratch-gui#1812]
### Expected Behavior
A variable in a Scratch 2 project which is selected to be shown on stage, should also be shown on stage after importing the project to Scratch 3. 

Also, a variable which is shown on stage in Scratch 3 should disappear after loading another project. 

### Actual Behavior
Displayed variables from Scratch 2 projects will not automatically be put on stage after import in Scratch 3.

If you display a variable on stage in Scratch 3 and you load another Scratch 2 project, this variable will not disappear from stage and there seems to be no way to remove this variable

### Steps to Reproduce
Make a Scratch 2 project with one variable, let it display on stage and save the project.
Load this project into Scratch 3. The variable will not be displayed automatically on stage.
Manually make the variable visible on stage.
Reload the same or another Scratch 2 project. The old variable stays on stage.

The problem seems to be the same with Scratch 3 projects after download/upload to computer.

### Operating System and Browser
Windows 10 (64 bit) with Firefox 59.02 (64 Bit), also seen on Windows 10 (32 bit) with Chrome.

**Comment by paulkaplan** [comment]
I believe this has been solved. Monitors are now imported from scratch 2 projects, and they are removed when switching projects

**Comment by benjiwheeler** [comment]
Tracking this issue in: https://github.com/LLK/scratch-vm/issues/1758
