### ISSUE TITLE
Sprite Loses Graphics Quality After Being Reset From Large Size

### ISSUE THREAD

**Issue by lovetocode999** [LLK/scratch-gui#1813]
### Expected Behavior

When you increase a sprite's size and set it to 100% again, the sprite should retain the same graphics quality as before.

### Actual Behavior

When you increase a sprite's size and set it to 100% again, the sprite becomes slightly pixelated. The more you increase the size before setting it to 100%, the more noticeable the pixelation becomes.
![scratch 3 0 gui - google chrome 4_18_2018 1_05_03 pm](https://user-images.githubusercontent.com/36867192/38952729-d75ed036-4309-11e8-9f72-2a74c3f744af.png)
Click the image to see up close.

### Steps to Reproduce

Increase a sprite's size and then reset it to 100%

### Operating System and Browser

Windows 10 OS and Chrome 65.0.3325.181 Browser

**Comment by thisandagain** [comment]
Moved to LLK/scratch-render#259
