### ISSUE TITLE
Consider adding sound editing by selection

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1825]
We should consider adding features to the sound editor that allow you to edit a region of the sound by selecting it. Any effects would apply only to that region. We should also consider adding features like these that can apply to the selected region:

- delete
- copy/paste
- silence
- fade in
- fade out

**Comment by apple502j** [comment]
Support. (feedback: https://scratch.mit.edu/discuss/post/3199437/

**Comment by ericrosenbaum** [comment]
Resolved by https://github.com/LLK/scratch-gui/pull/4974
