### ISSUE TITLE
Add temporary way to delete a sprite to the sprite tile

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#183]
Until we focus on building on the contextual menu, we should include the ability to delete a sprite on a selected sprite tile.

![r1 3 1_gui_animate-prototype](https://cloud.githubusercontent.com/assets/3409578/23569138/d5d2869e-002b-11e7-8398-074afc9500cd.png)

1. Click the ( x ) icon on the selected sprite tile
2. Browser should pop an alert to confirm delete action
3. Click 'Okay' in alert

**Comment by TheBrokenRail** [comment]
Why would this be temporary, are you planning on a different way to delete a sprite like a context menu, and how do you make those concept images?

**Comment by carljbowman** [comment]
@TheBrokenRail - We will explore a context menu once we are a little further along with the GUI. You may have noticed we are preparing for a upcoming playtest and as apart of that playtest experience we need a way to delete sprites. This design allows us to prototype the deletion behavior, but not have to build out a whole context menu system.

In regards to concept images, there is a lot of software one can use to create mockups. I use Adobe Illustrator, but there are lots of different tools. Another popular tool for mocks is Sketch.
