### ISSUE TITLE
Argument order in translation

### ISSUE THREAD

**Issue by abee2** [LLK/scratch-gui#1845]
In Japanese, "A of B" is translated as "B の A" normally.
Scratch 1.4 supported this inverted argument order. However, 2.0 is not. So it's very difficult to traslate this kind of sentence in natural Japanese.
I strongly recommend to support it in 3.0. This modification structure is used in some other languages.

**Comment by thisandagain** [comment]
Thanks! We plan to support this in Scratch 3.0.
