### ISSUE TITLE
Pen layer not cleared if you switch projects

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#1850]
### Expected Behavior
If you load a saved (video motion) project from your computer after playing a project that uses pen to draw, the camera should turn on and be visible. Anything drawn by pen in the previous project should be cleared.

### Actual Behavior

First of all, any backdrop is in front of the video layer, so you cannot see the video even though it's active and can be sensed. After removing the backdrop, the video is visible along with any previous pen layer.

### Steps to Reproduce
* load https://scratch.mit.edu/projects/116093633/ and run it to generate trails on the pen layer
* upload a video motion project from a local file (e.g. https://scratch.mit.edu/projects/217939203/)
* Video is running, but is not visible
* edit the backdrop to create a new transparent backdrop
<img width="363" alt="screen shot 2018-04-23 at 12 36 41 pm" src="https://user-images.githubusercontent.com/399209/39140605-1549ef1a-46f3-11e8-9641-0a8f1e53b5e7.png">

### Operating System and Browser

Mac OS 10.13.3 Chrome 66

**Comment by colbygk** [comment]
Another example 
![ezgif-4-12426b7223](https://user-images.githubusercontent.com/192393/39483726-4f6022ba-4d41-11e8-8f3d-48e9a0c128ef.gif)

**Comment by benjiwheeler** [comment]
Another example, from @NitroCipher:

> load this [example](https://llk.github.io/scratch-gui/develop/#248744218), run it (in turbo), and then click File>New
