### ISSUE TITLE
Can't paint new sprites or backdrops

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#1863]
### Expected Behavior
If you click the paintbrush icon in the new sprite thermometer or the new backdrop thermometer it should open the costumes tab and create a new empty sprite/backdrop.

### Actual Behavior
Clicking the paint new sprite/backdrop button causes console errors, the costumes tab doesn't open, and the if you are already on the costumes tab you can see that no new costume/backdrop is created.

You get the same issues if you are on the costume tab and choose new sprite/costume from the bottom of the asset list.

### Steps to Reproduce
Open a new project, then:

Mouse over the "New Sprite" button in the sprite list
Click the paintbrush icon in the thermometer
Note the Actual Behavior from above.

Mouse over the "New Backdrop" button
Click the paintbrush icon in the thermometer
Note the Actual Behavior from above.

Open the Costumes Tab, then:

Mouse over the "New Sprite" button in the sprite list
Click the paintbrush icon in the thermometer
Note the Actual Behavior from above.

Mouse over the "New Sprite" button in the assets list
Click the paintbrush icon in the thermometer
Note the Actual Behavior from above.

### Operating System and Browser

Mac OS 10.13.4 on Chrome 66.0.3359.117

**Comment by thisandagain** [comment]
@fsih @paulkaplan Could you two take a look at this prior to our smoke test on Friday? This seems like something that may block release.

**Comment by paulkaplan** [comment]
Hmmm @BryceLTaylor I can't seem to reproduce? New sprite button seems to add a sprite with an empty costume and automatically switches to the costumes tab. Here is what I'm seeing

![empty-sprites](https://user-images.githubusercontent.com/654102/39251525-85e73cbc-4871-11e8-9c9c-f3b13e13ac75.gif)

**Comment by fsih** [comment]
I wasn't able to repro on Chrome 65.0.3325.181 (Official Build) (64-bit) and Mac 10.12.6 (16G1314), though I do see a lot of console warnings

**Comment by fsih** [comment]
There were some network issues yesterday afternoon; could that have been related?

**Comment by thisandagain** [comment]
@BryceLTaylor Feel free to re-open if you can repro again.
