### ISSUE TITLE
Moving between script areas doesn't preserve the scripts' last locations in the pane

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#187]
Reported via internal playtest 3/3/17.

### Expected Behavior

The view of the scripting area should be persistent; when you leave it and come back to it, the scripts should be in the same place as you left them.

### Actual Behavior

The scripts for a sprite when you click on that sprite don't appear in the workspace where they were when you left that sprite.

### Steps to Reproduce

- Move between sprites with scripts
- Adjust your view of one of the scripts; scroll up or down so the blocks are in a different part of the screen
- Move between sprites
- Note when you go back to the sprite whose script area you adjusted, it's back to its default state

### Operating System and Browser

_Mac & Chrome_

**Comment by paulkaplan** [comment]
This one might be tough to fix. Blockly doesn't provide any kind of event emitting for scroll changes. We can see the `workspace.scrollX/Y` in the `Blocks` react component of the GUI, but without an event emitter there isn't going to be a redux-y way to send that data through React. #helpwanted

**Comment by thisandagain** [comment]
@paulkaplan This would be a good item to discuss with the Google team during our next meeting.

**Comment by rschamp** [comment]
I spoke with Rachel a bit about this and she suggested looking at how the minimap demo hacks in scroll listening.  I think we can do the same until scroll events are available from upstream. https://github.com/google/blockly/pull/965

**Comment by rachel-fenichel** [comment]
I also said that we're looking at providing viewport change events :)
