### ISSUE TITLE
Dragging a sprite should move it to the front

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#1870]
Should we bring back the functionality where dragging a sprite in editor mode would bring that sprite to the front? Originally comment came from https://github.com/LLK/scratch-gui/issues/161

from @jwzimmer 
> In 2.0, you can drag a sprite to reorder it's layer/ z-position relative to the sprites around it. In 2.0, dragging it moves it to the front/ top layer. In 3.0, this doesn't seem to happen. It looks like the layer order is just the order that the sprite was added (for new sprites) or the order they were in in 2.0 (for imported projects).
> 
> It is convenient to be able to reorder the sprites by dragging them around rather than always using the back/ forward blocks, but on the other hand, being able to tweak the positioning of the sprites without then being forced to re-order them is kind of nice (in 3.0). So, I'm not sure which behavior we prefer.

FWIW we also now have more granular layering blocks in looks (go to front/back and go forward/backward N layers)

/cc @carljbowman @thisandagain

**Comment by hedgehog125** [comment]
Another option could be when you drag a sprite is that it brings up some additional options for a few seconds? There could be bring to front, send to back, go forward one layer and go back one layer?

**Comment by kyleplo** [comment]
@hedgehog125 What about a button near the sprite info?

**Comment by hedgehog125** [comment]
@kyleplo yes, that would be good.

**Comment by thisandagain** [comment]
Yes. :-)
