### ISSUE TITLE
List Item Selection Support

### ISSUE THREAD

**Issue by MrBlockCat** [LLK/scratch-gui#1872]
### Expected Behavior

Like in Scratch 2, you should be able to select and copy the contents of a list in the player. This is helpful for load codes for games, for instance.

### Actual Behavior

When you try to select text in a list, it just moves the list with your cursor

### Steps to Reproduce

Create a list with something in it, and make sure the list is showing in the player. Then, move your mouse to the list in the player, and try to select text in the list like you can in Scratch 2. No matter where you click and drag, it always drags the list instead of selecting.

### Operating System and Browser

OS: Windows 10 Home Insider Preview AMD 64-bit, build 17650.1001 (Skip Ahead)
Browser: Firefox Nightly 61.0a1 (2018-04-25) (64-bit)

**Comment by hedgehog125** [comment]
Another option could be for this to become a proper feature as it's used so much. Maybe there could be some way of brining up a dialog for the user to copy.

**Comment by kyleplo** [comment]
This seems to already work for me on Windows Chrome.

**Comment by paulkaplan** [comment]
This has been fixed!
