### ISSUE TITLE
Lists might look too much like Variables

### ISSUE THREAD

**Issue by MsBlockCat** [LLK/scratch-gui#1873]
### Expected Behavior

Perhaps lists could look more like Scratch 2's, where the different items display in their own seperate rows?

### Actual Behavior

Right now, lists look a lot like variables in the player (with a space between each item), which can get confusing if you are working with items with spaces in them, as then you would not easily be able to tell where one item ends and another begins

### Steps to Reproduce

It's just an idea so you can't

### Operating System and Browser

All, it's just an idea

**Comment by PullJosh** [comment]
This is already on the docket in #942.
