### ISSUE TITLE
Allow renaming messages (from "new message") in message/ broadcasting blocks

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#189]
Reported via internal playtest 3/3/17.

### Expected Behavior

You should be able to rename the message to a custom name, and that should show up in the broadcasting blocks' menus.

### Actual Behavior

In broadcasting blocks, "new message" is just "new message" (rather than letting you set the name)

### Operating System and Browser

_Mac & Chrome_

**Comment by thisandagain** [comment]
Moved to LLK/scratch-blocks#822
