### ISSUE TITLE
Paint tooltip doesn't close on chromebook

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#1891]
### Expected Behavior
When you select paint new sprite and the paint editor opens, the 'paint' tool tip on the thermometer menu should close.

### Actual Behavior
Paint stays visible.
![screenshot 2018-04-27 at 12 33 33 pm](https://user-images.githubusercontent.com/399209/39374591-59422948-4a19-11e8-9801-e523f944bcc3.png)

Note - it's related to touch! On mouse move the paint closes.
### Operating System and Browser
Samsung chromebook (black one)
Version 64.0.3282.190 (Official Build) (64-bit)

**Comment by paulkaplan** [comment]
I'm seeing the same thing on iPad mini

**Comment by Kenny2github** [comment]
Can reproduce on Windows 10 Chrome 66, again only with touch:
![image](https://user-images.githubusercontent.com/28599280/40340506-cdfb0ca4-5db1-11e8-82a9-3ff0c07d492e.png)
