### ISSUE TITLE
A click and drag activates on stage clicked

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1892]
### Expected Behavior

Click and drag doesn't activate sprite clicks, so maybe it shouldn't activate stage clicks

### Actual Behavior

Drag activates stage click

### Steps to Reproduce
1. Add a script to the stage, say 'on stage clicked, start sound pop'
2. Click and drag stage
3. On mouse up, pop plays

### Operating System and Browser
Windows 10 Chrome

**Comment by paulkaplan** [comment]
When sprite click now activates the same way on sprites and the stage, so I'm going to close this because they both activate on mouse down.
