### ISSUE TITLE
Click and drag off of a sprite activates sprite click

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1893]
### Expected Behavior

Either it should be dragged or it shouldn't activate the sprite clicked hat

### Actual Behavior

Click and drag sprite sometimes activates sprite clicked instead of dragging

### Steps to Reproduce

![idontknowwhyyousaygoodbyeisayhello](https://user-images.githubusercontent.com/2855464/39375127-4c9d4090-4a1b-11e8-95cd-7cef1468e908.gif)
1. Have the mosaic effect active on the cat
2. Click on one of the transparent pixels and drag the cat
3. Cat does not drag but click hat activates

Note that the stage also had a on click hat on it which did not activate. Because of https://github.com/LLK/scratch-gui/issues/1892 it should have activated, but the cat click activated instead.

This is somewhat inconsistent to repro

### Operating System and Browser
Windows 10 Chrome

**Comment by paulkaplan** [comment]
The behavior is different now, the "when clicked" now activates on mouse down, so this isn't relevant
