### ISSUE TITLE
Can click on stage/sprite through a library

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#1898]
### Expected Behavior

If you have a stack with a "When Stage Clicked" or a "When Sprite Clicked" hat and you bring up a library and click over where the stage/sprite is the stack should not trigger.

### Actual Behavior

It does trigger the hat block

### Steps to Reproduce

Create a project
Select the stage
Add a When Stage Clicked hat
Add a make a sound block to the stage clicked block
Click the Add new Sprite from Library button
Click on the library over the stage but not on an element of the library
Note that a sound is made.

### Operating System and Browser

Chrome on Mac and Edge on Windows

**Comment by paulkaplan** [comment]
Can no longer repro, looks fixed
