### ISSUE TITLE
Perceived lag in libraries

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-gui#19]
These seem to load very slowly.

The basic problem is that they require tons of network requests currently. The sprite library has to request one JSON file per sprite, and then separately one SVG/PNG. The costume library has to request all the images (no JSON), but there are *many* of them.

Two ways we could address this are packaging the metadata into scratch-gui, or by implementing lazy loading.

**Comment by CosmicWebServices** [comment]
Lazy loading seems like a safe option to start out with but who says you cannot do both?

**Comment by rschamp** [comment]
Libraries were bundled in #34
