### ISSUE TITLE
Scripts disappeared from project but project continued to play

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#190]
### Expected Behavior

Scripts should only disappear from within a project if the user deletes them, or their parent asset.

### Actual Behavior

Reported by @christanbalch during internal playtest 3/3/17. The project was being used and edited as usual, then she switched between two scripting areas, and when she came back to the first one, its scripts were not visible. The project still played on greenflag, and you could still interact with it. 

/cc @christanbalch if you remember more details about what happened, could you add them here?

Reported during internal playtest 3/3/17.

<img width="779" alt="screen shot 2017-03-03 at 3 45 05 pm" src="https://cloud.githubusercontent.com/assets/1320456/23568430/71160602-0028-11e7-97a1-5807b28b7d76.png">
<img width="780" alt="screen shot 2017-03-03 at 3 44 57 pm" src="https://cloud.githubusercontent.com/assets/1320456/23568429/71146c66-0028-11e7-89c1-4101370e23b6.png">
<img width="784" alt="screen shot 2017-03-03 at 3 44 47 pm" src="https://cloud.githubusercontent.com/assets/1320456/23568426/7112c96a-0028-11e7-8f5d-7f75995c6b71.png">
<img width="781" alt="screen shot 2017-03-03 at 3 44 37 pm" src="https://cloud.githubusercontent.com/assets/1320456/23568427/7112efa8-0028-11e7-8ece-fb52c71d2ff1.png">
<img width="224" alt="screen shot 2017-03-03 at 3 44 24 pm" src="https://cloud.githubusercontent.com/assets/1320456/23568428/71140c1c-0028-11e7-9906-04bff94698ce.png">

### Steps to Reproduce

I'm not sure how to reproduce this. The project is https://scratch.mit.edu/projects/143627742/#editor.

@ericrosenbaum commented:
> this project has a stage but no sprites, which seems to be causing the problem

### Operating System and Browser

_Mac & Chrome_

**Comment by jwzimmer** [comment]
@christanbalch also saw this issue in this project:

In @christanbalch's project with a lot of clones.
<img width="786" alt="screen shot 2017-03-03 at 3 47 01 pm" src="https://cloud.githubusercontent.com/assets/1320456/23568513/d60e8084-0028-11e7-9327-36b7fe1e9f90.png">
<img width="781" alt="screen shot 2017-03-03 at 3 46 51 pm" src="https://cloud.githubusercontent.com/assets/1320456/23568514/d60fe8ac-0028-11e7-877f-41d09100ad12.png">
<img width="776" alt="screen shot 2017-03-03 at 3 46 43 pm" src="https://cloud.githubusercontent.com/assets/1320456/23568512/d60dad3a-0028-11e7-9461-51507a06ce93.png">

**Comment by jwzimmer** [comment]
@ericrosenbaum also got "cannot read property 'shadow' of undefined" during the internal playtest, 3/13/17: https://github.com/LLK/scratch-blocks/issues/842.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/842
