### ISSUE TITLE
Uploaded jpg images have dark line under them in some positions

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#1902]
### Expected Behavior

If you upload a jpg as a costume for a sprite it should appear on the stage at all positions on the screen without any boarder.

### Actual Behavior

An uploaded jpg costume will have a dark line under it in some positions.  In other positions it will not have a line and in other positions it will have a lighter line.

With Line
![screen shot 2018-04-27 at 4 10 03 pm](https://user-images.githubusercontent.com/1088291/39383252-9d0f2a78-4a36-11e8-9674-90cbb1e7faba.png)

Same sprite moved slightly
![screen shot 2018-04-27 at 4 09 52 pm](https://user-images.githubusercontent.com/1088291/39383270-a853dae6-4a36-11e8-8b29-23f9deaf59ae.png)

I do not see this issue with .png files.

### Steps to Reproduce

Create a jpg image with a white background (using another tool) locally
Create a project
Click the costumes tab on the cat
Hover over the Add Costume button
Select the Upload button from the thermometer menu
Select your created jpg
On the stage click and drag the sprite around.
Note that in some places it has a dark line, in others it's light, and in others it isn't there at all.

### Operating System and Browser

Chrome on Mac and Edge on Windows

**Comment by kchadha** [comment]
@paulkaplan I think it might be the image resizing library I'm using... I think I'm going to possibly switch to drawing on a canvas since that's what we're doing elsewhere and it also might solve our performance problem.

**Comment by paulkaplan** [comment]
@BryceLTaylor @fsih there have been many changes recently on bitmap importing, could someone check if this is still an issue?

**Comment by BryceLTaylor** [comment]
Looks fixed to me!
