### ISSUE TITLE
Sound editor - Cannot trim sounds in the middle

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#1908]
### Expected Behavior

There should be some way, in the sound editor, to get rid of part of the sound that's in the middle. (This is different from normal trimming, where you cut off part of the beginning and/or end.)

You can do so in Scratch 2.0 by dragging over part of the sound visualization; this will make a selection in the middle of the sound, which can then be deleted. (Effects will also only be applied to the selection, but that feature is for a separate issue.)

### Actual Behavior

There's no way to do so.

### Steps to Reproduce

Open the sound editor (with a sound selected). Try to figure out how to cut out part of the middle of a sound. Compare with the Scratch 2.0 sound editor.

This was brought to my attention by [this](https://scratch.mit.edu/discuss/topic/299467/) discussion topic.

**Comment by paulkaplan** [comment]
Fixed
