### ISSUE TITLE
When increasing mosaic effects many times, sprite's image flipped and started becoming bigger again

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#192]
Reported during internal playtest 3/3/17. Similar to https://github.com/LLK/scratch-gui/issues/174 in that both involve the mosaic effect's progression changing unexpectedly.

### Expected Behavior

The mosaic effect should not unpredictably change, and shouldn't cause the image to flip.

### Actual Behavior

When increasing mosaic effects many many times, my image flipped and started becoming bigger again - https://llk.github.io/scratch-gui/#148267026

### Example Project

- https://llk.github.io/scratch-gui/#148267026

### Operating System and Browser

_Mac & Chrome_

**Comment by davidaylaian** [comment]
Can reproduce on Firefox 57.0.1 (64-bit) and Chrome 63.0.3239.84, using Linux for both.

**Comment by paulkaplan** [comment]
This issue actually exists in 2.0, i'm not sure it is really a "bug", I think this should be a #wontfix. 
![image](https://user-images.githubusercontent.com/654102/40447258-f600619c-5e9f-11e8-864a-677629cd17d7.png)
