### ISSUE TITLE
Add `appComponent` prop to GUI component to set up Modals

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#1928]
The `react-modal` component requires a call to `Modal.setAppElement(element)`, but when using GUI from outside of this repo, the `Modal` class is unavailable. Therefore we should pass in the `appElement` so the GUI can set it when it's constructed.  Alternatively we could create a static method on GUI `setAppElement` which would proxy to `Modal`.

This is needed for embedding the GUI on the project page.

**Comment by paulkaplan** [comment]
Done.
