### ISSUE TITLE
Two projects in stage area

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-gui#1929]
### Expected Behavior

Load and run project https://preview.scratch.mit.edu/#210021467
  1) Press spacebar
  2) Allow it complete the wavy pattern (or not)
Modify URL in browser to https://preview.scratch.mit.edu/#1 and hit enter
  1) You should only see the results of project #1 running in the stage

### Actual Behavior

Load and run project https://preview.scratch.mit.edu/#210021467
  1) Press spacebar
  2) Allow it complete the wavy pattern (or not)
Modify URL in browser to https://preview.scratch.mit.edu/#1 and hit enter
  1) See the wavy result of project 210021467 still on "blank" stage background while project #1 is running.

### Steps to Reproduce

Load and run project https://preview.scratch.mit.edu/#210021467
  1) Press spacebar
  2) Allow it complete the wavy pattern (or not)
Modify URL in browser to https://preview.scratch.mit.edu/#1 and hit enter
  1) See the wavy result of project 210021467 still on "blank" stage background while project #1 is running.

### Operating System and Browser

Mac OS 10.13.3 Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by kchadha** [comment]
Looks like this is the same as #1850

**Comment by colbygk** [comment]
Closing as duplicate
