### ISSUE TITLE
TypeError when attempting to drag the stage in player.html

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#1931]
/cc @chrisgarrity @paulkaplan 
I think this started after #1909 

### Expected Behavior

_Please describe what should happen_
No uncaught exceptions

### Actual Behavior

_Describe what actually happens_
I receive many errors in my console:
```
raven.js:429 Uncaught TypeError: Cannot read property 'draggable' of undefined
    at Stage.onStartDrag (stage.jsx:304)
    at Stage.wrapper [as onStartDrag] (index.js:550)
    at Stage.onMouseMove (stage.jsx:169)
    at HTMLDocument.wrapper (index.js:550)
    at HTMLDocument.d (raven.js:425)
```

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
On https://llk.github.io/scratch-gui/develop/player.html try dragging the stage and look in your console. It looks like `target` is undefined here: https://github.com/LLK/scratch-gui/blob/6c7c1c36d57a5840da01f5ac19ccae456586fd6c/src/containers/stage.jsx#L304

**Comment by paulkaplan** [comment]
Yeah, you also see this in fullscreen mode of the full editor.
