### ISSUE TITLE
Bitmap brush tool causes sprites to disappear from stage on Safari

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#1933]
### Expected Behavior

Drawing on a sprite that has been converted to bitmap should make visible changes to the sprite on the stage.

### Actual Behavior

If you convert a sprite to bitmap and draw on it with the paintbrush the sprite disappears on the stage if it is on that costume.

![safaridrawundersprite2](https://user-images.githubusercontent.com/1088291/39491889-c7a05af0-4d5b-11e8-9eaf-1f8d72760745.gif)

If you click "Convert to Vector" the cat and the line appear on the stage.

Alternatively, if you switch to a different costume and then back to the first one, you can draw on it again and it will appear.  I think that that has to do with it being in vector mode again.

There is a related issue where the thumbnail for the costume also goes blank: #1936 

### Steps to Reproduce

Create a new project in Safari
Open the costumes tab
Click "Convert to Bitmap"
With the brush tool draw a line
Note how the cat and line disappear from the stage

### Operating System and Browser

Safari Version 11.1 (13605.1.33.1.2) on Mac OS 10.13.4

**Comment by thisandagain** [comment]
Moved to LLK/scratch-paint#419
