### ISSUE TITLE
Bitmap brush tool causes costume thumbnail to go blank in Safari

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#1936]
### Expected Behavior

If you use the brush tool in bitmap mode of the paint editor the thumbnail for the costume should update to show the changes.

### Actual Behavior

If you draw with the brush after converting to bitmap the thumbnail will disappear.  

![safaricostumethumbnaildisappear](https://user-images.githubusercontent.com/1088291/39494148-48b12e1a-4d63-11e8-911d-92ae26b53a44.gif)

This is related to issue #1933 

### Steps to Reproduce

Create a new project
Select the costumes tab
Click "Convert to Bitmap"
Draw a line on or near the cat
Note that the thumbnail disappears

### Operating System and Browser

Safari Version 11.1 (13605.1.33.1.2) on Mac OS 10.13.4

**Comment by thisandagain** [comment]
Moved to LLK/scratch-paint#418
