### ISSUE TITLE
A bug about "go to mouse-pointer"

### ISSUE THREAD

**Issue by xiaohuang2004** [LLK/scratch-gui#1938]
I found a bug. ![code](https://user-images.githubusercontent.com/38885760/39507521-d6d04930-4e10-11e8-9a58-edce12561275.PNG)
When you are **in full screen control** and run this script, the cat will follow your mouse. But if you **keep the left mouse button down**, the cat will _stop_. This action is different from the script , so I think it is a bug.

**Comment by Kenny2github** [comment]
I can reproduce this on Chrome 65, Windows 8.1. I get the following error message in the console:
![image](https://user-images.githubusercontent.com/28599280/39508975-186bcce2-4e17-11e8-9288-35f94d1e2307.png)

**Comment by paulkaplan** [comment]
I cannot reproduce this on develop, can you make sure to try at https://llk.github.io/scratch-gui/develop/. Feel free to re-open if you are using develop already.

**Comment by Kenny2github** [comment]
I also cannot reproduce on develop (Chrome 66, Windows 7).

**Comment by xiaohuang2004** [comment]
Sorry. I tested it on preview.scratch.mit.edu ,so I find this problem. I tested it on develop and it doesn't have problems.
