### ISSUE TITLE
No YouTube Tutorials

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#1939]
### Expected Behavior
There should not be YouTube Tutorials, because some schools or countries (like China) block it.
### Actual Behavior
There are 8 YouTube tutorials
### Steps to Reproduce
Click ? button at the right top
### Operating System and Browser
Windows 7 Homepremium 64bit SP1
Firefox 59.0.3

**Comment by thisandagain** [comment]
We are working on plans to host videos locally, but they may need to be hosted from YouTube for some time.
