### ISSUE TITLE
Sprite from 2.0 project is cropped in 3.0

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#194]
Reported during internal playtest 3/3/17.

### Expected Behavior

Sprites should be the same in projects loaded in 2.0 & 3.0.

### Actual Behavior

The edges of the sprite are cut-off when you load the project in 3.0.

<img width="1280" alt="screen shot 2017-03-06 at 10 59 41 am" src="https://cloud.githubusercontent.com/assets/1320456/23617828/5bca9f16-025c-11e7-8903-683a67b404bd.png">
<img width="1280" alt="screen shot 2017-03-06 at 10 59 24 am" src="https://cloud.githubusercontent.com/assets/1320456/23617829/5bd18fb0-025c-11e7-9841-b01f8a0da126.png">

### Steps to Reproduce

Load the example project in 2.0 & 3.0.
- https://scratch.mit.edu/projects/148269787

### Operating System and Browser

_Mac & Chrome_

**Comment by thisandagain** [comment]
Moved to LLK/scratch-render#116
