### ISSUE TITLE
Converting from bitmap to vector moves sprite on stage

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#1944]
### Expected Behavior

Converting a costume from bitmap to vector should leave the sprite positioned in the same place it was before and its costume center should stay where it is.

### Actual Behavior

If you convert a sprite from bitmap to vector, switch to a different costume, and then back the sprite appears lower and to the right of where it was before.

![bitmaptovectorchrome](https://user-images.githubusercontent.com/1088291/39531767-f20b4fcc-4df9-11e8-980a-00fe950cb354.gif)

I am seeing this on Chrome and on Firefox.  On Safari the sprite disappears altogether, which I'll put in another issue.

### Steps to Reproduce

Load the 2.0 project 220174550 (you can use others, this one is easy to see it with)
Select the costumes tab
Select the second costume thumbnail
Note that the two costumes appear in the same location on the stage
Click "Convert to Bitmap"
Note that the image doesn't move on the stage
Select the first costume again
Select the second costume again
note that the sprite has now moved down and to the right.

The sprite in the Paint editor appears in the same place that it used to it has just moved on the stage.

This also happens if you start with a vector and then convert it to a bitmap and then back.  You can test that with the default cat.

### Operating System and Browser

Mac OS 10.13.4 on Chrome 66.0.3359.117 
     Firefox 59.0.2 (64-bit)

**Comment by fsih** [comment]
Hmm, this may be related to the issue in the comment in https://github.com/LLK/scratch-paint/pull/412

**Comment by BryceLTaylor** [comment]
Yeah, it does look like the same thing.  Interestingly, the Safari issue seems to have fixed itself in the last five minutes.  Safari is now showing the same results as Chrome and Firefox except that if disappears and reappears briefly during the conversion.

**Comment by fsih** [comment]
The amount that the sprite moves by in the renderer seems to be the rotation center

**Comment by BryceLTaylor** [comment]
It does seem that the costume center has moved and not the sprite:

![spinningsprite](https://user-images.githubusercontent.com/1088291/39533596-776ea698-4dfd-11e8-993f-a66b9b7c5422.gif)

**Comment by BryceLTaylor** [comment]
This seems to have been fixed!
