### ISSUE TITLE
Backdrop in project imported from 2.0 is too small, in lower lefthand quadrant

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#195]
Not sure if this is too similar to https://github.com/LLK/scratch-gui/issues/194, in which a sprite was cropped. In this case, a backdrop was cropped or very small in 3.0.

### Expected Behavior

Backdrops should be identical when loaded in 2.0 or 3.0 editor.

### Actual Behavior

- 54759944
- Project mostly works, but the background/ backdrop is too small
- No console output

### Steps to Reproduce

- Compare in 2.0 vs. 3.0: 54759944
- Project mostly works, but the background/ backdrop is too small

### Operating System and Browser

_Mac & Chrome_

**Comment by thisandagain** [comment]
Moved to LLK/scratch-render#117
