### ISSUE TITLE
Sprite at wrong location if costume center is outside the costume box's border

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#196]
Reported via internal playtest 3/3/17.

### Actual Behavior

If costume center has been chosen outside the bounding box of the costume (as with the heart here), the sprite is placed at the wrong location.

### Example Project

- https://scratch.mit.edu/projects/67538396/#editor

### Operating System and Browser

_Mac & Chrome_

**Comment by jwzimmer** [comment]
Also reported via internal playtest:
> Clones not appearing in correct location (maybe a sprite center problem?)

Example project: https://scratch.mit.edu/projects/129191348/#editor

If this issue is not the same as the issue originally reported here, we can open it as its own case.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-render#118
