### ISSUE TITLE
Fix font in how-to end screen

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1961]
### Expected Behavior

The buttons use a normal font.

### Actual Behavior

The buttons use the default font because Helvetica Neue is not supported. Most likely related to lines 163 and 199 of /src/components/cards/card.css
![image](https://user-images.githubusercontent.com/31634240/39597472-8493ff76-4ee3-11e8-9322-68372f171cc7.png)

### Steps to Reproduce

Open any how-to and go to last screen

### Operating System and Browser

Chrome 66 Windows 10

**Comment by paulkaplan** [comment]
Note also happens in Edge, https://github.com/LLK/scratch-gui/issues/2191
