### ISSUE TITLE
Sign In Into Your Account And Go To Projects Stuff On Scratch 3.0

### ISSUE THREAD

**Issue by MarkRachkov** [LLK/scratch-gui#1963]
Heres a image
![image](https://user-images.githubusercontent.com/38962437/39602651-a2f5bd6e-4eda-11e8-9057-e8a008e18686.PNG)
the feature is coming soon

**Comment by rschamp** [comment]
Don't worry, we're on it!  ![](https://preview.scratch.mit.edu/static/assets/3e83d9d800459175308f0b45b117af16.png) All the things that have a "coming soon" message are logged internally if they're not logged here, so you don't have to file issues for them.

This feature will come along with the preview project page work on https://github.com/LLK/scratch-www
