### ISSUE TITLE
Transparency not consistently working

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#197]
Reported via internal playtest 3/3/17.

### Expected Behavior

Example project where transparency works: https://llk.github.io/scratch-gui/#50919938

### Actual Behavior

- Example project where transparency does not work: https://llk.github.io/scratch-gui/#63714086
- rainbow raindrops - transparency not working

### Operating System and Browser

_Chrome & Mac_

**Comment by thisandagain** [comment]
Moved to LLK/scratch-render#114
