### ISSUE TITLE
3.0 lacks Transportation Category in Sprite Library

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1975]
### Expected Behavior
Show Transportation Category with various sprites in Sprite Library

### Actual Behavior
Transportation Category does not exist
<img width="1583" alt="scratch_3_0_gui" src="https://user-images.githubusercontent.com/3812168/39641834-93d1c3dc-4f9d-11e8-929b-65a85ebd4532.png">

### Steps to Reproduce

1. Add a new sprite
2. Look through categories and notice no transportation category

### Operating System and Browser
Chrome 66

**Comment by thisandagain** [comment]
We will likely not have a transportation category in 3.0.
