### ISSUE TITLE
Visual effects do not reset when clicking on stop - only when clicking on the green flag

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#198]
Reported via internal playtest 3/3/17.

### Actual Behavior

Visual effects do not reset when clicking on stop - only when clicking on the green flag

This case https://github.com/LLK/scratch-gui/issues/171 has examples where stop had not reset the value of the graphic effect. In some of the screenshots, the scripts are not active, but the J sprite still has graphic effects on it.

### Operating System and Browser

_Mac & Chrome_

**Comment by Airhogs777** [comment]
LLK/scratch-vm#139

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/139
