### ISSUE TITLE
Design "How To" icon / menu bar button

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#1982]
The current "How To" icon and menu bar button is temporary and should be properly considered.

### Considerations
- The "How To" icon should attract attention 
- The "How To" icon should help unify the "How To" library button in the menu bar with the "How To" cards in the editor
- The "How To" icon and button should ideally communicate a balance of "help" and "fun stuff to do"

### Reference
![image](https://user-images.githubusercontent.com/747641/39648291-c4289792-4faf-11e8-9e2d-80696dc262c7.png)
![image](https://user-images.githubusercontent.com/747641/39648340-de51303e-4faf-11e8-954b-0b6de603ae7f.png)

/cc @carljbowman @ntlrsk

**Comment by carljbowman** [comment]
Moving into June as we are still evaluating UX and navigation of How To content.

**Comment by thisandagain** [comment]
Bump @carljbowman

**Comment by carljbowman** [comment]
## Locations to Update
There are a few places that we need to update.
- [ ] Toolbar (currently just the question mark icon)
- [ ] Mini-cards Top Nav (currently a question mark icon with "All How Tos")
- [ ] Resource Library (currently reads "How Tos")

### Asset
[tutorials.svg.zip](https://github.com/LLK/scratch-gui/files/2188690/tutorials.svg.zip)

## Toolbar & Mini-Cards Nav
**Toolbar** 
- Change icon to lightbulb
- Include "Tutorials" text to the left of the icon
- Move between "Edit" and Project Title and include dotted line space on each side

**Mini-card Nav**
- Change icon to lightbulb
- Change text to the left of the icon from "All How Tos" to "Tutorials"

![intro card mini-cards](https://user-images.githubusercontent.com/3409578/42634958-b48b570a-85b2-11e8-8d97-58adf8ee2197.png)


## Tutorial Library
- Change text at the top from "How Tos" to "Choose a Tutorial"

![tutorials library](https://user-images.githubusercontent.com/3409578/42635231-80c5d728-85b3-11e8-816a-91f18fe0b86f.png)


cc/ @ntlrsk @kosiecki17
