### ISSUE TITLE
After clicking translated "scratch-cat", Scratch crashed

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#1986]
### Expected Behavior

_Please describe what should happen_
Click on translated "scratch-cat", nothing happens.
### Actual Behavior
![7](https://user-images.githubusercontent.com/31377746/39657767-96da9856-503d-11e8-9107-3dc2a3a4cb84.PNG)

![6](https://user-images.githubusercontent.com/31377746/39657759-7359dc52-503d-11e8-8b87-9c12b76d3f9a.PNG)
![4](https://user-images.githubusercontent.com/31377746/39657798-f6b97332-503d-11e8-9b6e-4975d3933d6c.PNG)
![5](https://user-images.githubusercontent.com/31377746/39657799-f767682a-503d-11e8-86b9-aab70c6bbea2.PNG)

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
1. Use google to translate page into other languages(I translated it into Chinese)
2. Click translated "scratch-cat"
### Operating System and Browser

Chrome 66.0.3359.139
Windows 8

**Comment by chrisgarrity** [comment]
The editor is not expected to work if it has been automatically translated by google translate. We will be supporting Scratch in other languages, including Chinese.
