### ISSUE TITLE
Will Scratch specially designed for the mobile phones?

### ISSUE THREAD

**Issue by ousc** [LLK/scratch-gui#1988]
![image](https://user-images.githubusercontent.com/31619017/39661024-c90155be-507d-11e8-926e-2e83e72d27f2.png)
I think there is a huge demand that a number of people want to use the scratch in mobile phone,an it seems not so good at this moment, will it be specially designed for the mobile phone ?

**Comment by thisandagain** [comment]
Thanks for the interest! We are working to make sure Scratch 3.0 projects can be played on phones, but we are not yet looking at creation on phones.
