### ISSUE TITLE
2.0 pen project does not work in 3.0

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#199]
Reported during internal playtest 3/3/17.

### Expected Behavior

- Press green flag
- See sunflowers, etc.
- Compare to https://scratch.mit.edu/projects/117800110/#editor

### Actual Behavior

- Background somewhat works, but behaviour is different than 3.0 and I don't see sunflowers or sun
- https://llk.github.io/scratch-gui/#117800110

### Operating System and Browser

_Mac & Chrome_

**Comment by thisandagain** [comment]
Can't repro in latest Chrome on Mac OS 10.12.3
