### ISSUE TITLE
Click goes through monitors

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1998]
### Expected Behavior

In Scratch 2.0, touching goes through monitors, but click doesn't
![clickmonitor2](https://user-images.githubusercontent.com/2855464/39709666-82776504-51e8-11e8-821b-1f9ab1c14f03.gif)

### Actual Behavior

In Scratch 3.0, touching and click both go through monitors
![clickmonitor](https://user-images.githubusercontent.com/2855464/39709675-8bb81190-51e8-11e8-926d-bac2ca437ea4.gif)

### Steps to Reproduce
0. Turn on a monitor
1. Move monitor on top of a sprite
2. Click over both the monitor and the sprite
### Operating System and Browser
Windows 10 Firefox

**Comment by paulkaplan** [comment]
Looks like this was fixed
