### ISSUE TITLE
Switching rotation style for a sprite while it's moving (i.e. in a forever loop) makes the stage freeze temporarily

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#200]
Reported during internal playtest 3/3/17.

### Expected Behavior

Stage should not freeze when rotation style is changed.

### Actual Behavior

Switching rotation style for a sprite (i.e. from all around to left-right) while it's moving (i.e. in a forever loop) makes the stage freeze for a bit.

### Operating System and Browser

_Mac & Chrome_

**Comment by paulkaplan** [comment]
No longer happens! Closing.
