### ISSUE TITLE
Focused block inputs are visible in fullscreen view

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#2009]
### Expected Behavior

Focused block inputs should be hidden when the fullscreen button (above the top-right of the stage) is clicked.

### Actual Behavior

Focused block inputs aren't hidden; they're still visible.

### Steps to Reproduce

1. Drag out a block with an input field you can type in.
2. Focus the input field (e.g. by clicking on it).
3. Click on the fullscreen button above the top-right corner of the stage. Notice that the input field is still visible, even though the block it's a part of isn't (since the editor is in fullscreen mode).

### Operating System and Browser

Firefox 61.0b2, Debian (Testing). Reported in [a forum post](https://scratch.mit.edu/discuss/post/3094125/). This is similar to #1129 and probably has the same solution.

**Comment by thisandagain** [comment]
Related to:
https://github.com/LLK/scratch-gui/issues/1129
https://github.com/LLK/scratch-gui/issues/1680
