### ISSUE TITLE
On Safari, adding a Custom Procedure to a sprite will cause some blocks to disappear while running

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2026]
### Expected Behavior

All blocks remain visible in the workspace all the time.

### Actual Behavior

When you add a custom procedure block to the workspace, even if it doesn't have blocks in it, will make some blocks that have code running disappear.

![safaricustomdisappearingblocks](https://user-images.githubusercontent.com/1088291/39879782-c0d58afc-5449-11e8-8b21-7d6a45fcee89.gif)

Which blocks actually appear is slightly complicated and I haven't figured all the way out yet.  It appears to only be blocks that are running that disappear, though.

### Steps to Reproduce

Create a project
Make a simple program
  When green flag clicked
  Move 10 Steps
  If on edge bounce

  When space pressed
  Repeat 10 times
  change y by 3
  Repeat 10 times
  Change y by -3

Run the program
Press space a few times
Note, everything looks normal

Go to My Blocks
Click Make a Block
Hit Enter to create it
Click the green flag
Note that the forever loop stack disappears
Press space
Note the change y by stack disappears for a moment and then returns

### Operating System and Browser

Safari on Mac (Not Chrome)

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/1501
