### ISSUE TITLE
Scratch preview rendering cut off on phones

### ISSUE THREAD

**Issue by RoboErik** [LLK/scratch-gui#2027]
### Expected Behavior

If the screen is too small for Scratch it should extend the bounds off screen and allow scrolling to see the rest.

### Actual Behavior

Only the content that fits on the screen on first load is rendered. Anything outside those bounds is clipped.

### Steps to Reproduce

Open preview.scratch.mit.edu on a pixel phone.

### Operating System and Browser

Pixel phone in chrome
![screenshot_20180510-105933](https://user-images.githubusercontent.com/6395961/39885622-ec512ca2-5441-11e8-8db2-f239e770f9ba.png)

**Comment by MrBlockCat** [comment]
Scratch isn't designed for phones yet, but I think it helps if you scroll using the second bar down (the one with the Costumes, Sounds, and Code tabs)... Try scrolling using different areas of the screen, it can be finicky but it helps in the meantime :)

**Comment by rachel-fenichel** [comment]
Also repros on the Nexus 5x.

**Comment by rachel-fenichel** [comment]
It used to render the whole thing but you'd have to carefully scroll to reach different parts of the screen.  It now just doesn't render whole sections.
