### ISSUE TITLE
Node warning: possible EventEmitter memory leak detected (project with clones)

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#203]
Potentially related to https://github.com/LLK/scratch-gui/issues/186 since those errors were also occurring in the console (Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined).

From internal playtest 3/3/17.

Errors from @seotts. She was making about 300 clones.
![pasted image at 2017_03_03 03_01 pm](https://cloud.githubusercontent.com/assets/1320456/23568248/ad72034a-0027-11e7-9893-957b4bddc640.png)

### Operating System and Browser

_Mac & Chrome_

**Comment by thisandagain** [comment]
This is expected given the clone limit but we should `setMaxListeners` to match the clone limit.

**Comment by bigeyex** [comment]
So what's the clone limit, for most projects of Scratch? 3000? Or wait until the browser gets stuck?
An easier way is let the user be responsible for managing their own clones, and simply remove the warning.

**Comment by chooper100** [comment]
@bigeyex 
The clone limit is 301 (see LLK/scratch-vm#497)
I was under the impression that there was a discussion somewhere over whether a clone limit would still be enforced in Scratch 3, but I can't find it so it might have just been informallly mentioned on the Scratch forums

**Comment by cwillisf** [comment]
While removing the clone limit might be fun for more advanced Scratchers, having a clone limit helps people who make a small mistake -- or just want to see what happens! -- avoid problems if they accidentally write a script that creates clones like crazy. We can certainly consider making the clone limit larger, but I'd like to keep it low enough that it's hard to accidentally freeze a browser with too many clones.

**Comment by bigeyex** [comment]
I created [(a ridiculously simple) pr in scratch-render](https://github.com/LLK/scratch-render/pull/135) to avoid the warning.
the program will stop creating clones after 300, as what it did before.

The warning is shown because the limit of shared skin is 1 less than the limit of clones.
