### ISSUE TITLE
Graphic quality of stamped sprites is very low

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#204]
From internal playtest, 3/3/17.

### Expected Behavior

The stamped sprites shouldn't be appreciably lower-res than the original sprite.

### Actual Behavior

The graphic quality of the stamped sprites is really low.

### Operating System and Browser

_e.g. Mac, Chrome_

**Comment by thisandagain** [comment]
Moved to LLK/scratch-render#124
