### ISSUE TITLE
Clearing a sprite name shifts sprite image

### ISSUE THREAD

**Issue by lifeinchords** [LLK/scratch-gui#205]
![sprite-name mov](https://cloud.githubusercontent.com/assets/716168/23626407/cb7a5fae-027a-11e7-8b31-c7696f18d468.gif)

This is probably due to `flex-box` flow. A couple of options that might work:
- Add top + bottom padding, use margin auto to pull sprite image to top, and push sprite name to bottom. 
- Add a blank placeholder image, same size as sprite

**Comment by rschamp** [comment]
This will probably resolve itself when we start validating sprite names (and disallow empty names).

**Comment by paulkaplan** [comment]
Fixed, can no longer have empty sprite names.
