### ISSUE TITLE
Slider monitors: changing the min and max

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#2053]
Scratch 2.0 has a feature where the min/max of a slider can be changed by right clicking the slider monitor. We are currently importing the custom range from 2.0 projects, but the range is fixed to 0-100 for monitors created in 3.0

![image](https://user-images.githubusercontent.com/654102/39999407-0caa8e36-5757-11e8-9ab8-713a2eb06eee.png)

This overlaps with the issue of decimal monitors, or, setting the "step size" of the sliders, because you can force the sliders to use decimal steps by using decimal min/max in a somewhat complicated way. We may want to make that setting explicit. See step size issue for more details. https://github.com/LLK/scratch-gui/issues/2052

**Comment by apple502j** [comment]
I'm on it (it's not help-wanted, but...)
![](https://i.gyazo.com/62a50534245219833fb8f3b73e6e8ce7.gif)

**Comment by sandboneill** [comment]
Here I am enquiring about the status of the slider variable problem (negative values not possible and range 1-100 too wide). Thanks Seamus O'Neill

**Comment by benjiwheeler** [comment]
@sandboneill Thanks for asking. There's a pull request in the works that should add this functionality soon.

**Comment by sandboneill** [comment]
Thanks for update.

Seamus O Neill
Weandus Ltd.
Education Design Services
Navan
Co. Meath
087 2308320

Teacher No: 42936
www.readysteadycode.ie
www.isfeidirliom.ie
www.celebratelearning.ie

*The Resources Development Service (RDS) c/o Navan Education Centre is a
commissioned/voluntary service offered by Seamus O'Neill, We and Us,
Educational Design Services, Navan

**It is our proud achievement that the ReadySteadyCode fine-line vector
grids have been added into Scratch by the MIT Media Lab, (Boston)
