### ISSUE TITLE
List monitors: importing from CSV, exporting

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#2054]
This is an existing feature in 2.0. 

![image](https://user-images.githubusercontent.com/654102/40000044-bf2afa2c-5758-11e8-8d9d-da1269d1fa8a.png)

If the csv has more than one column, you are prompted to specify a column number.

Exporting is done as a "CSV" with one column, i.e. a newline separated list, it is saved as a `.txt` file. 

@carljbowman already has mockups of this, just has not been prioritized yet.

**Comment by griffpatch** [comment]
This is still a missing feature that I use a lot... can't imagine doing without the import and export of lists to/from file.
