### ISSUE TITLE
List monitors: remove button hidden by scrollbar on Chrome

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#2055]
### Expected Behavior

_Please describe what should happen_

You can see the remove button on list items when there is a scrollbar

### Actual Behavior

_Describe what actually happens_

It gets almost entirely covered up:
![image](https://user-images.githubusercontent.com/654102/40000509-f9b9d3ba-5759-11e8-936f-a7100a34f96c.png)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

Plug in a mouse, make a list with enough items to make it scroll, then click on one of the items and try to click the remove button.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

Mac/Chrome

**Comment by kyleplo** [comment]
Set CSS `overflow` on `.monitor_list-body_2OFZ6` to `auto`.
