### ISSUE TITLE
On Android, Soft Keyboard covers the launch 2.0 project dialog

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2059]
### Expected Behavior

If you select "View 2.0 Project" on the landing modal and then tap the text field on the next dialog, the soft keyboard should not cover the text box you are typing into.

### Actual Behavior

The soft keyboard covers the text field you are typing into, so you can't read what you are typing.  You also can't scroll the background to make the field visible.

![androidsoftkeyboardhuge](https://user-images.githubusercontent.com/1088291/40015749-58ed21a2-5782-11e8-9d15-f45aeac5c19b.png)

### Steps to Reproduce

From the landing modal click "View 2.0 Project"
Tap the text field on the dialog
Note that they keyboard covers the text field

### Operating System and Browser

Android Tablet running Android 7.1.1

**Comment by picklesrus** [comment]
I was able to reproduce this in landscape mode, but not portrait.

**Comment by paulkaplan** [comment]
Well, the component does not exist anymore, so I'm going to close this.
