### ISSUE TITLE
On Android, Switching to Portrait mode doesn't draw right edge of screen

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2061]
### Expected Behavior

Switching to portrait mode should show the whole stage, sprite list, and the stage.

### Actual Behavior

Instead it seems to move the stage to the right position and shrinks the workspace horizontally, but doesn't draw the right edge of the screen.  It does draw the header all the way to the right side of the screen, though.

![androidportraitmode](https://user-images.githubusercontent.com/1088291/40017772-4fe1f65e-5788-11e8-81b7-404f2ba9d6c8.png)

### Steps to Reproduce

Launch the gui
Close the landing modal
Rotate the screen into portrait mode
Note that the right side of the screen is not drawn.

### Operating System and Browser

Android Tablet running Android 7.1.1

**Comment by picklesrus** [comment]
I can't reproduce this anymore... Tried on an android tablet and on my phone.
