### ISSUE TITLE
2.0 project confined to lower right quadrant in 3.0

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#207]
Reported during internal playtest 3/3/17.

### Expected vs. Actual Behavior

The project should play the same way in 2.0 or 3.0. The ribbon spreads out across the middle of the project pane in 2.0 but is stuck in the lower right and has some straight edges in 3.0.

Project in 3.0
<img width="494" alt="screen shot 2017-03-06 at 3 06 20 pm" src="https://cloud.githubusercontent.com/assets/1320456/23627422/b1b618de-027e-11e7-87a2-33c243eed5f7.png">

Project in 2.0
<img width="496" alt="screen shot 2017-03-06 at 3 06 04 pm" src="https://cloud.githubusercontent.com/assets/1320456/23627421/b1b3a8b0-027e-11e7-9412-0fa49aa34832.png">

### Steps to Reproduce

- Press green flag, compare 2.0 & 3.0
- https://scratch.mit.edu/projects/129394845/
- https://llk.github.io/scratch-gui/#129394845

### Operating System and Browser

_Mac & Chrome_

**Comment by paulkaplan** [comment]
This looks like it might have the same root cause as https://github.com/LLK/scratch-vm/issues/520

Both projects have 0x0 costumes and exhibit the same type of "pinning" to the lower right quadrant.

![image](https://cloud.githubusercontent.com/assets/654102/26835410/47342b02-4aa6-11e7-9a3b-6209ba2950dd.png)

**Comment by paulkaplan** [comment]
And here is another one, again with a 0x0 costume: https://scratch.mit.edu/projects/128249399/

**Comment by paulkaplan** [comment]
Closed when https://github.com/LLK/scratch-vm/issues/520 was closed.
