### ISSUE TITLE
Randomize new sprite location

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#2072]
### Expected Behavior

New sprites should get uploaded near center like adding a  sprite from the library.

### Actual Behavior

All new sprites get uploaded exactly at the center (if you upload the same sprite many times, it looks like nothing is happening).

### Steps to Reproduce

Upload sprites via sprite upload button in Sprite add menu.

**Comment by paulkaplan** [comment]
Note that the sprite library also has this problem, it just seems random because the XY positions are baked into the sprite library json. But if you add them from the library over and over they keep going to the same place.
