### ISSUE TITLE
Show block shows old speech/thought bubbles

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2078]
### Expected Behavior

When you run a Show block it should not show speech or thought bubbles that you haven't told to appear.

### Actual Behavior

When you run a show block it will cause the speech or thought bubble that was previously run.

![saybubbleshow](https://user-images.githubusercontent.com/1088291/40071346-7e2dece6-583e-11e8-9948-19723b1957e1.gif)

### Steps to Reproduce

Launch the editor
Drag a "Say hello for 2 seconds" block onto the work area
Drag a "Show" block onto the work area
Click the Show block
Note no speech bubbles appear
Click the Say Hello for 2 seconds block
Note the speech bubble appears and then disappears 2 seconds later
Click the Show block
Note that the say bubble reappears
Note that the say bubble never disappears (unless you stop the program)

This also works with the "Think" block
After getting the thought bubble to appear with the show block you can get it to go away by running the say for 2 seconds block again.

### Operating System and Browser

Chrome on Mac
Also on Firefox on Mac

**Comment by paulkaplan** [comment]
@BryceLTaylor thanks for finding this! fixed in https://github.com/LLK/scratch-vm/pull/1147
