### ISSUE TITLE
2.0 Project doesn't play correctly after refresh/ first visit to project

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#208]
Reported via internal playtest 3/3/17.

### Expected Behavior

Project should play the same way every time.

### Actual Behavior

After a refresh/ when first visiting the project, it doesn't play correctly in 3.0. The sprites don't display.

![out](https://cloud.githubusercontent.com/assets/1320456/23627900/764ea98a-0280-11e7-8eb5-4db9a6d8e1b5.gif)

### Steps to Reproduce

Compare in 2.0 vs. 3.0
- https://llk.github.io/scratch-gui/#114926309

### Operating System and Browser

_Mac & Chrome_

**Comment by cwillisf** [comment]
Can't seem to repro this... seems like it probably amounts to LLK/scratch-gui#827
