### ISSUE TITLE
Dragging sprite on stage causes the sprite to appear "glitched"

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#2080]
### Expected Behavior

The sprite should appear the same when it being dragged as it is when dropped/not being dragged.
![no dragging glitch](https://user-images.githubusercontent.com/3409578/40122329-8abe84da-58f1-11e8-9ec0-44f46281050b.gif)

### Actual Behavior

![dragging-glitch](https://user-images.githubusercontent.com/3409578/40122386-b1311204-58f1-11e8-82cf-4d9f8769441f.gif)

### Steps to Reproduce

1. Add a sprite
2. Drag a sprite on the stage

### Operating System and Browser

Branch: preview.scratch.mit.edu (May 15th, 2018)

MacBook Air (13in, Mid 2013)
OS: macOS 10.11.5
Processor: 1.3 GHz Intel Core i5
Memory: 4GB 1600MHz DDR3
Graphics: Intel HD Graphics 5000 1536 MB

Browser: Chrome 66.0.3359.170 (Official Build) (64bit)

**Comment by paulkaplan** [comment]
Yeah this one seems to be very specific to that hardware, also can't repro on more recent Mac (2016) on more recent OS (10.13.4). 

I'm not sure if it is the hardware or the OS version that is to blame though. We could try updating that computer to find out, but that risks losing our only repro-able computer!

**Comment by carljbowman** [comment]
Sorry I should have clarified that this case is "very specific to" the hardware listed in the original issue.

**Comment by ericrosenbaum** [comment]
Same as: https://github.com/LLK/scratch-gui/issues/1912 

Seen on the same laptop

**Comment by paulkaplan** [comment]
Woops yeah sorry @carljbowman didn't see that this was already filed. Closing, tracking in #1912
