### ISSUE TITLE
Bad tooltips on preview modal buttons

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-gui#2087]
### Expected Behavior

All buttons have either a user-friendly tooltip or no tooltip at all.

### Actual Behavior

The buttons on the "Welcome to the Scratch 3.0 Preview" modal have inconsistent & non-user-friendly tooltips:
- "Not Now" has no tooltip
- "Try It! 😸" displays `tryit` on hover
- "View 2.0 Project" displays `viewproject` on hover

### Steps to Reproduce

1. Load the Scratch 3.0 editor but don't dismiss the preview modal
2. Hover over each button in the modal dialog

### Operating System and Browser

Windows 10.0.17134.48 (Spring 2018 update)
Microsoft Edge 42.17134.1.0

**Comment by fsih** [comment]
Related to https://github.com/LLK/scratch-gui/issues/1260

The tooltips are what the tests use to grab the right element to click, so they're kind of hard to remove

**Comment by cwillisf** [comment]
> The tooltips are what the tests use to grab the right element to click

Ah, makes sense. I guess they should all have human-friendly tooltips then?

**Comment by mrjacobbloom** [comment]
Could the tests use another HTML attribute that the browser won't use as a tooltip?

**Comment by paulkaplan** [comment]
We have the ability to use `formatMessage()` for getting translatable, human readable strings into button title attributes. These should just use that, and then just update the tests to whatever the title text is.
