### ISSUE TITLE
"Play sounds until done" block should highlight when clicked

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#209]
Reported in internal playtest 3/3/17.

### Expected Behavior

- Play sounds until done should highlight when clicked

### Actual Behavior

- Play sounds until done doesn't highlight when clicked
- https://llk.github.io/scratch-gui/#114926309

### Operating System and Browser

_Mac & Chrome_

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-audio/issues/19
