### ISSUE TITLE
Rename the "Jamie" sprite

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#2090]
Because we have a sprite from the 2.0 library with a similar-but-not-identical name, "Jaime," we should consider choosing a different name for the new basketball player sprite currently named "Jamie."

Jaime:
![image](https://user-images.githubusercontent.com/567844/40198433-762e6208-59e4-11e8-9f5d-151ba96df736.png)

Jamie:
![image](https://user-images.githubusercontent.com/567844/40198456-8a3c0142-59e4-11e8-9f2f-409228aa70d5.png)

**Comment by Craig88** [comment]
How about "Jamal" for the new basketball player sprite?

**Comment by DeleteThisAcount** [comment]
how about james because it refrences 
LeBron James
American basketball player

**Comment by Craig88** [comment]
Hey @thisandagain - thanks for taking this suggestion (implemented and merged here: https://github.com/LLK/scratch-gui/pull/2622). I think this issue can be closed now.
