### ISSUE TITLE
Unhandled Error: Error: Tried to serialize a variable field with no variable.

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2094]
### Expected Behavior
No oops

### Actual Behavior
Oops

### Steps to Reproduce
![crash3](https://user-images.githubusercontent.com/2855464/40205972-284628c4-59fc-11e8-9e41-7c7b194b6b35.gif)
1. Go to https://llk.github.io/scratch-gui/develop/#221549537
2. Click on the fourth sprite
3. Click on the third sprite

Now there are some errors:
raven.js:429 Uncaught Error: Variable "Screen" is already in use and its id is "U)^l%k)ew%F=LoUL`jPI-Screen" which conflicts with the passed in id, "cDw3AqT_3chH3kWRAL(I-Screen".
    at Blockly.VariableMap.createVariable (blockly_compressed_vertical.js?./node_modules/imports-loader?this=>window!./node_modules/exports-loader?Blockly&goog:274)

4. Change tabs
5. Change back to blocks

Now there are more errors, one of which is fatal:
gui Unhandled Error: Error: Tried to serialize a variable field with no variable.
    at Object.Blockly.Xml.fieldToDomVariable_ (webpack://ScratchBlocks/./blockly_compressed_vertical.js?./node_modules/imports-loader?this=%3Ewindow!./node_modules/exports-loader?Blockly&goog:827:128)

The original project was created in scratch 2 by putting a few sprites from a different project into the backpack, and then putting the backpacked sprites into a new project.
This was the original project: https://scratch.mit.edu/projects/218507424/

### Operating System and Browser
Windows 10 Chrome

**Comment by paulkaplan** [comment]
It would be really good to have a full repro case of this from end-to-end @BryceLTaylor @fsih

**Comment by paulkaplan** [comment]
I _believe_ this has the same root cause as https://github.com/LLK/scratch-gui/issues/2180, that is, having two sprite-local variables with the same names, but I'll leave them both open because this is another repro case.

**Comment by kchadha** [comment]
No longer causing a crash as of LLK/scratch-blocks#1651.
