### ISSUE TITLE
"Go to x y" block does not update value when sprite is dragged

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#210]
Reported in internal playtest 3/3/17.

### Actual vs. Expected Behavior

"Go to x y" block does not update value when sprite is dragged, but it should

### Operating System and Browser

_Mac & Chrome_

**Comment by navignaw** [comment]
We probably want to update the "slide n secs to x y" block as well.

Is there any existing code for changing the block templates' arguments, or would that have to be implemented?
