### ISSUE TITLE
On Edge, List monitors have two x's to delete an item when selected

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2106]
### Expected Behavior

List monitors should have one x on the right side of list items in list monitors to delete items.

### Actual Behavior

On Edge, there is one x on the far right side of the list item line like in the other browsers, but the editable field has another x.

![2xs](https://user-images.githubusercontent.com/1088291/40312619-5cc30b48-5ce1-11e8-93c2-68983b6644c1.png)

### Steps to Reproduce

Create a new project
Create a new list
Add a few items to the list
Select one of the items in the list monitor
Note that there are two x's on the list

### Operating System and Browser

Edge on Windows

**Comment by paulkaplan** [comment]
This SO answer shows how to hide that 'x' on IE/Edge, looks like it is added in Edge automatically to inputs, but our "x" is there to remove the whole list entry. So I guess we should just hide their "x"

https://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs

If anyone has a computer with Edge and can test it, feel free to fix this issue, just submit before/after screenshots in the PR.
