### ISSUE TITLE
2.0 project doesn't play in 3.0; you get stuck on one of the first sprites and can't progress

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#211]
Reported via internal playtest 3/3/17.

### Actual vs. Expected Behavior

Project doesn't play in 3.0; you get stuck on the logo sprite, no circle comes up for you to use to play the game. The game should play the same way in 2.0 & 3.0.
- https://scratch.mit.edu/projects/71362070/
- https://llk.github.io/scratch-gui/#71362070

### Steps to Reproduce

- Compare 2.0 & 3.0; press green flag, then click the sprite

### Operating System and Browser

_Mac & Chrome_

**Comment by FairPlay137** [comment]
I assume it's because the size never hits 100 in the logo sprite.

**Comment by FairPlay137** [comment]
After some investigation, I found that the size of the logo sprite never hits 100% (it only gets to 96%), so it never goes away.

**Comment by rasmushaglund** [comment]
This is most likely a scratch-vm bug. I found that scratch-vm only set size in integers, while Scratch 2.0 used floats.

I created an issue in scratch-vm: https://github.com/LLK/scratch-vm/issues/521

**Comment by thisandagain** [comment]
Tracking in llk/scratch-vm#522
