### ISSUE TITLE
Little gray square appears in list monitor while dragging it 

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#2110]
### Expected Behavior

No unexpected little gray squares in list monitors??

### Actual Behavior

A little gray square appeared in the upper left corner of the list monitor, while I dragged it:

![image14](https://user-images.githubusercontent.com/1088291/40250340-fa3e90da-5aa3-11e8-88d5-9fcb233b61df.png)

### Operating System and Browser

Chrome OS

**Comment by paulkaplan** [comment]
Fixed by recent monitors fixup.
