### ISSUE TITLE
Clicking the "+" button in list monitors makes the list look like it's being dragged

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#2112]
### Expected Behavior

The list monitor shouldn't look like it's being dragged when the "+" button is clicked. (That is, the list should not be draggable by the "+" button.)

### Actual Behavior

Clicking the "+" button picks up the list monitor (i.e. gives it a drop shadow), and the monitor can then be dragged.

### Steps to Reproduce

Show a list monitor, and click on the "+" button. The effect is especially noticeable if you hold down the mouse when you click the button.

### Operating System and Browser

Firefox 61.0b6, Debian (testing).

**Comment by paulkaplan** [comment]
Solving this should be as simple as using the fixed `.no-drag` class on the "+" button, that will get it to not respond to dragging. You can see a similar thing https://github.com/LLK/scratch-gui/blob/develop/src/components/monitor/slider-monitor.jsx#L22 for reference.
