### ISSUE TITLE
the color of title and placehoulder

### ISSUE THREAD

**Issue by ZhangJoker** [LLK/scratch-gui#2118]
I truly recommend that separate the font color and placeholder in menu bar. As result, user can identify the word they enter and placeholder. Just change css in the menu-bar component like this

```
.title-field {
    border: 1px dashed $ui-black-transparent;
    border-radius: .25rem;
    width: 12rem;
    height: 34px;
    background-color: transparent;
    padding: .5rem;
    color: $ui-white;
    font-weight: bold;
    font-size: .8rem;
}

.title-field::placeholder {
    color: $ui-white-transparent;
}
```

**Comment by thisandagain** [comment]
That field is meant to be a little hard to see because it hasn't been implemented yet.
