### ISSUE TITLE
scratch-blocks@0.1.0 prepublish: `python build.py && webpack`

### ISSUE THREAD

**Issue by ZhangJoker** [LLK/scratch-gui#2119]
I got the problem which is
 
scratch-blocks@0.1.0 prepublish: `python build.py && webpack`

could you give me a help?

**Comment by sjhuang26** [comment]
Do you have Python installed? That might be the problem.

Also, what is the full error message that shows up on your console?

**Comment by ZhangJoker** [comment]
yes. I already install python 2.7.10.  This is the full error message.

```
Traceback (most recent call last):
  File "build.py", line 595, in <module>
    test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scratch-blocks@0.1.0 prepare: `python build.py && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scratch-blocks@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by sjhuang26** [comment]
Check that the file /build/test_input.js exists in your repository.

**Comment by harsh424jan** [comment]
Please explain the complete purpose of this file build.py so that I can contribute to the project.
.

**Comment by ZhangJoker** [comment]
Yes I have that file. Maybe because I use windows? If I add the 4th argument "shell=True" at line 595, I can pass some steps. But it will stop at line 352. I will get "command too long " error if I use the same way. Is that possible there is some different to use "Popen" method between Mac and Windows.

**Comment by apple502j** [comment]
Still have the problem.
Looks like it requires "google-closure-compiler\build\test_input.js" which doesn't exist.
Official Google GitHub didn't have it.
Closure Library GitHub didn't have either.
Downloadable Closure Compiler was a Java program.

All I could say is: "What on earth happened!?"

**Comment by apple502j** [comment]
I gitted google closure library and compiler at scratch-blocks directory (fail)
changed the directory name to "google-closure-library" (fail)

I found that the wrong code was not from Blockly, after checking with WinMerge

**Comment by apple502j** [comment]
@thisandagain I'm sure this is unfixable without re-making build.py from Blockly's one.

**Comment by syslink** [comment]
I also encountered this problem.  Does anybody solve it? Thanks!

**Comment by rahulp100191** [comment]
Hey, any solution to this issue. Can anyone please help, 
Below is error when running npm install
"
Traceback (most recent call last):
  File "build.py", line 595, in <module>
    test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scratch-blocks@0.1.0 prepare: `python build.py && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scratch-blocks@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
"

**Comment by Mfweb** [comment]
This problem still exists.
```shell
$ npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> scratch-blocks@0.1.0 prepublish C:\Users\h\Desktop\scratch-blocks-develop
> python build.py && webpack

Traceback (most recent call last):
  File "build.py", line 574, in <module>
    test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "D:\Python2\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "D:\Python2\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scratch-blocks@0.1.0 prepublish: `python build.py && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scratch-blocks@0.1.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\h\AppData\Roaming\npm-cache\_logs\2019-04-03T09_35_17_555Z-debug.log
```

**Comment by chua1989** [comment]
I have this problem too

**Comment by JevenM** [comment]
Oh my God, does anybody solve this problem?

**Comment by manujdhariwal** [comment]
I got this problem resolved on my Windows 10 machine by:
- 1stly making the Shell=True change (adding a 4th arg to Popens in build.py at two places)
<after doing this step the error changes to errno 2 from errno 1 >
- next I took the two files (blockly_compressed_vertical.js and blockly_compressed_horizontal.js @scratch blocks folder)) from my friend who uses a mac and has evthg working properly ....

these two changes made the errors go away and things are working now .... I have done this multiple times and got it working each time by following these steps .....

**Comment by mikixu** [comment]
> I got this problem resolved on my Windows 10 machine by:
> 
> * 1stly making the Shell=True change (adding a 4th arg to Popens in build.py at two places)
>   <after doing this step the error changes to errno 2 from errno 1 >
> * next I took the two files (blockly_compressed_vertical.js and blockly_compressed_horizontal.js @scratch blocks folder)) from my friend who uses a mac and has evthg working properly ....
> 
> these two changes made the errors go away and things are working now (don't forget to run the 'npm run prepublish' command for scratch blocks)....
> 
> I have done this multiple times and got it working each time by following these steps .....

I particularly hope that  you can give the two files  you took as a link， so all can solve this problem。

**Comment by sansong089** [comment]
1、making the Shell=True change
2、refer to https://blog.csdn.net/weixin_42856280/article/details/90288065

**Comment by tanishk23** [comment]
getting error 
 Entrypoint main = main.js
    [./shim/gh-pages.js] 29 bytes {main} [built]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! scratch-blocks@0.1.0 prepublish: `python build.py && webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the scratch-blocks@0.1.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tanishk\AppData\Roaming\npm-cache\_logs\2020-06-29T05_27_57_543Z-debug.log

help required!!

**Comment by mikixu** [comment]
> getting error
> Entrypoint main = main.js
> [./shim/gh-pages.js] 29 bytes {main} [built]
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! scratch-blocks@0.1.0 prepublish: `python build.py && webpack`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the scratch-blocks@0.1.0 prepublish script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\tanishk\AppData\Roaming\npm-cache_logs\2020-06-29T05_27_57_543Z-debug.log
> 
> help required!!

I got this problem resolved by npm install  the scratch-blocks at linux, and reload it to windows, and npm link at windows, it works fine.

**Comment by soumitya0** [comment]
I have this problem too

any solution ?

**Comment by CodingAvenger** [comment]
> > I got this problem resolved on my Windows 10 machine by:
> > 
> > * 1stly making the Shell=True change (adding a 4th arg to Popens in build.py at two places)
> >   <after doing this step the error changes to errno 2 from errno 1 >
> > * next I took the two files (blockly_compressed_vertical.js and blockly_compressed_horizontal.js @scratch blocks folder)) from my friend who uses a mac and has evthg working properly ....
> > 
> > these two changes made the errors go away and things are working now (don't forget to run the 'npm run prepublish' command for scratch blocks)....
> > I have done this multiple times and got it working each time by following these steps .....
> 
> I particularly hope that you can give the two files you took as a link， so all can solve this problem。

if you install scratch-blocks using npm then the files are available in C:\Users\<username>\node_modules\scratch-blocks. 

I tried this and it gets past the errors. Still gives the command line too long error though
