### ISSUE TITLE
StageWrapper and sub-components should not have padding

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2132]
The stage header and canvas wrapper components include padding to create a .5rem space around the stage. On www the left edge of the stage cannot line up with the left edge of the view because of this padding. 

Currently working around the problem by setting a negative  .5rem margin on the enclosing element on www, but that seems brittle.

**Comment by paulkaplan** [comment]
Yes please. This is also the cause of monitors being slightly misaligned in fullscreen mode.
