### ISSUE TITLE
Scratch 2 project crashes editor

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2137]
### Expected Behavior
Scratch 2 projects are playable

### Actual Behavior
https://scratch.mit.edu/projects/225139422/#editor
This project made in scratch 2 crashes in scratch 3
https://llk.github.io/scratch-gui/develop/#225139422

All it has in it is an empty costume
I think I got the costume into a weird state by switching costumes while using the text tool, but I'm not exactly sure how. I think the empty costume used to have text in it in scratch 2, which doesn't show up anymore.

Stack trace
scratch-vm.js:64134 Uncaught (in promise) TypeError: Cannot read property 'assetId' of null
    at loadCostumeFromAsset (scratch-vm.js:64134)
    at scratch-vm.js:64232
<img width="942" alt="screen shot 2018-05-23 at 14 32 10" src="https://user-images.githubusercontent.com/2855464/40444017-24ca0550-5e96-11e8-9e95-9d3f0d76c573.png">

### Steps to Reproduce
Open the link

### Operating System and Browser
Mac Chrome

### Update
The empty costume has turned back into text and the project works in scratch 3 now! It seems the file was temporarily not available from the server

**Comment by paulkaplan** [comment]
Additionally, it isn't triggering the "Oops" page. 

/cc @chrisgarrity and @rschamp, did something about the redux refactor move around the error boundaries? I'm seeing the oops page on preview, just not develop.

**Comment by paulkaplan** [comment]
@fsih It looks like it has a costume that is pointing to an asset that does not exist on the server. The costume with the name "costume1" has the hash a27258cc5f234b220337021518d77c3b.png, but https://cdn.assets.scratch.mit.edu/internalapi/asset/a27258cc5f234b220337021518d77c3b.png/get/ is 404'd.

**Comment by fsih** [comment]
The Scratch website has been really slow today, maybe something was corrupted?

**Comment by chrisgarrity** [comment]
@paulkaplan @rschamp the error boundary moved out of app-state-hoc into the gui component because app-state isn't used by www. However the gui component is still wrapped by the project-loader-hoc and vm-listener. Possibly they should also have error boundaries. What the overhead of having multiple error boundaries?
