### ISSUE TITLE
IE & Edge - In target pane sprites are blurry and too big

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-gui#214]
### Expected Behavior

_They are not blurry and have adequate padding_

### Actual Behavior

_It doesn't_

### Steps to Reproduce

_Look at the target pane._

### Operating System and Browser

_Windows 10 Edge_

### Screenshot

![bug](https://cloud.githubusercontent.com/assets/17478432/23632795/43a7a8b8-0291-11e7-850a-a20c0f9b6b46.PNG)

**Comment by fsih** [comment]
Fixed by https://github.com/LLK/scratch-gui/pull/1231
