### ISSUE TITLE
External links to youtube

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2155]
Is it weird that we are recommending videos from Scratch that redirect to youtube? Not sure if we are controlling the set of videos that are recommended, or if something weird could show up in this list.

![image](https://user-images.githubusercontent.com/2855464/40554983-85e46d5a-6015-11e8-9aa4-b2b8f97ab604.png)

Repro: finish watching a how to video

**Comment by apple502j** [comment]
ST is going to host these movies at their server.

**Comment by thisandagain** [comment]
We will eventually move these over to our own servers / service.
