### ISSUE TITLE
x in list monitor is too low

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2156]
Expected: x should be centered

Actual: x is lower
![image](https://user-images.githubusercontent.com/2855464/40555202-502188b4-6016-11e8-8a2f-0e8cff245a7f.png)

x can overlap content:
![image](https://user-images.githubusercontent.com/2855464/40555271-8903e816-6016-11e8-9cd0-fd4710c59961.png)

Windows 10 Firefox

**Comment by sjhuang26** [comment]
I will work on this.
