### ISSUE TITLE
Lag while deleting script 

### ISSUE THREAD

**Issue by NitroCipher** [LLK/scratch-gui#216]
### Expected Behavior

No lag.

### Actual Behavior

The editor lags.

### Steps to Reproduce

Create a script (a simple one will be just fine, even just one block works) drag said script into the block pallet. The editor will lag as you try to delete the script.

### Operating System and Browser

Windows 7 Enterprise 32-bit Google Chrome 56.0.2924.87

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/835
