### ISSUE TITLE
Suggestion: Make variables for extensions global

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#2163]
### Expected Behavior

If you load an extension in Scratch 3 through the console, it should work temporarily.

### Actual Behavior

NOTHING HAPPENS BUT AN ERROR.

### Steps to Reproduce

Load an extension through the console.

### Operating System and Browser

It doesn't really matter...

**Comment by amazinigmech2418** [comment]
If you make the variables global, it will allow for console extension development.

**Comment by amazinigmech2418** [comment]
@thisandagain @paulkaplan @LLK Can someone do this so I can test a text to speech extension?

**Comment by amazinigmech2418** [comment]
Also, Git for some reason won't allow me to install it, so this would be the only thing I can do.

**Comment by amazinigmech2418** [comment]
@towerofnix I just open the console and type in the extension code. I have GH repos with my extensions. It works for Scratch 2. With flash, however, so it doesn't crash, while in the console, you have to click "see inside".

**Comment by towerofnix** [comment]
@amazinigmech2418 Ah yeah - basically, Scratch 3.0 is written with totally new code, so extensions written for Scratch 2.0 won't just work with 3.0. (It's like trying to ask a Windows computer to run a Mac app.) You'll have to rewrite your extension to make it work with 3.0. (There will be official documentation on how to do this in the future, [per the FAQ](https://scratch.mit.edu/preview-faq) - "The Scratch Team will be publishing an extensions specification and guidelines later in 2018.")
