### ISSUE TITLE
Scratch-svg-render has been wrong at installation time and cannot find the version number

### ISSUE THREAD

**Issue by qiansitong** [LLK/scratch-gui#2167]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by paulkaplan** [comment]
NPM experienced an outage last week that caused published versions not to show up, that was giving me an error last week. But it should be working now.
