### ISSUE TITLE
Temporarily add collection of sounds to each letter sprite

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#217]
Since we will not have a Sounds tab or way to add sounds to sprites, we should pre-populate all letter sprites with a collection of sounds. 

User can select sounds at the block level in drop downs. 

![r1 3 2_gui_animate-prototype](https://cloud.githubusercontent.com/assets/3409578/23664061/7b4215a6-0322-11e7-8aa5-d8dbbd76850b.png)

**Comment by ericrosenbaum** [comment]
Closed via https://github.com/LLK/scratch-gui/pull/218
