### ISSUE TITLE
Player mode: green flag overlay

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2171]
When the GUI loads in player mode there should be a green flag overlay on the stage.

Clicking the green flag overlay, or the green flag button should hide the overlay and start the project.

The project should not respond to key presses (or any other hat blocks) until the green flag has been clicked.

**Comment by hedgehog125** [comment]
Sometimes it can be useful the hat blocks being able to run before the project starts as it can make the project start before the flag is actually clicked. However, this could also be a downside as it can make the project start unpredictably and do something annoying.

**Comment by towerofnix** [comment]
@hedgehog125 Just out of curiosity's sake, do you have an example project that does that?

**Comment by hedgehog125** [comment]
@towerofnix kind of. I challenged myself not to use the "when flag clicked" block when I made one of my projects. I used the "when timer > than" block as a replacement. See: https://scratch.mit.edu/projects/152979730/ But I could create an example project if you like.

**Comment by chrisgarrity** [comment]
@hedgehog125 if you notice, the sounds and movement of the project do not start when you load the project page until after you click the green flag. If you load it in the editor everything starts immediately. This is the mode that needs to be implemented for Scratch 3.0.

**Comment by towerofnix** [comment]
@hedgehog125 Ah, cool. Although I think that your linked project will work fine in Scratch 3.0. Note that the project doesn't run *before* the flag is *initially* clicked in 2.0 -- that's what chrisgarrity is talking about here, not that scripts won't run at all if the stop button is pressed (the fact that they don't is what your project uses).

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-gui/pull/3882
