### ISSUE TITLE
Stage should not have as many blocks in the Pen extension

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2174]
### Expected Behavior

The stage should match the behavior of Scratch 2 and have just the Erase All (Clear) block in the Pen extension.

### Actual Behavior

The Pen extension has all of the blocks for the stage that it has for a sprite: Erase All, Stamp, Pen Down, Pen Up, set pen color, change pen color by, set pen color to, change pen size by, set pen size.

![stagepenblocks](https://user-images.githubusercontent.com/1088291/40665805-35a7275a-632c-11e8-9d9b-d756679df6cd.png)

Scratch 2:
![stagepenblocksscratch2](https://user-images.githubusercontent.com/1088291/40665856-531102e8-632c-11e8-8d15-dc3db7dbe0ab.png)

### Steps to Reproduce

Add the pen extension
Select the stage
Note: it has all the blocks.

### Operating System and Browser

Chrome on Mac (but all of them.)

**Comment by kyleplo** [comment]
Should the stage be able to stamp?

**Comment by fsih** [comment]
Taking off needs discussion since we discussed in the design meeting

For stamping, we decided that the block shouldn't be in the palette, but if you drag the stamp block into the stage, it should work as it always has in 3.0
