### ISSUE TITLE
how-to resources should not include themselves in the 'other things to try' card

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2176]
### Expected Behavior

The how-to currently being viewed is not included in the list of other things to try on the last card.

### Actual Behavior

'Switch Costumes' appears on the list of things to try when you're viewing the Switch Costumes how-to.

**Comment by thisandagain** [comment]
@SpeakkVisually @kosiecki17 This is something to audit / make sure is resolved before we ship the beta.

**Comment by thisandagain** [comment]
This appears to be resolved.
