### ISSUE TITLE
Opening the backdrop library causes the stage backdrop editor to become selected

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#2188]
### Expected Behavior

_Please describe what should happen_
The backdrop editor should be selected when I choose a backdrop. If I don't do anything in the library, my place in the editor shouldn't change.

### Actual Behavior

_Describe what actually happens_
Clicking the "Choose a backdrop" button and then hitting <kbd>Esc</kbd>, leaves the editor in the Stage's paint editor tab.
![add-backdrop](https://user-images.githubusercontent.com/1512021/40739968-86ffbb14-6415-11e8-9a34-d0cafab841ab.gif)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
In a new project, with a sprite's code tab open, click the "Choose a backdrop" button, then hit <kbd>Esc</kbd> (or otherwise close the library without doing anything).

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_
Not browser related

**Comment by sjhuang26** [comment]
I will work on this.

**Comment by sjhuang26** [comment]
I noticed that the BackdropLibrary component is nested inside the

**Comment by rschamp** [comment]
@sjhuang26 Yes moving that into the root component makes sense, since the state is controlled by Redux anyway, it doesn't need a parent relationship like this.

**Comment by paulkaplan** [comment]
Foxed!
