### ISSUE TITLE
Tutorial cards appear below monitors when brought over the stage.

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#2189]
### Expected Behavior

Tutorial cards should be on top of everything else in the editor.

### Actual Behavior

Tutorial cards appear below monitors when repositioned over the stage.

![image](https://user-images.githubusercontent.com/1786240/40743526-c605b4e4-641f-11e8-858f-a9dd00185371.png)

**Comment by sjhuang26** [comment]
I will work on this.

**Comment by paulkaplan** [comment]
Has been fixed
