### ISSUE TITLE
Green flag and stop are not visible enough

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-gui#219]
### Expected Behavior

It should be easy for kids to find the green flag and stop when they need them. 

### Actual Behavior

From our playtesting with microworlds, we see that kids are not sure where to find them, and tend to not use them because of that.

One idea is to make them larger (they are smaller than in 2.0)

**Comment by thisandagain** [comment]
@carljbowman Thoughts on this? They do seem to get lost a bit in the current hierarchy, but I'm 100% open to opinions on how to resolve.

**Comment by SebCanet** [comment]
Hi,
we have a problem with little kids and interactive whiteboards, they cannot click on green flag because it is t the top and not at the bottom...
Thanks.

**Comment by CosmicWebServices** [comment]
I think that you should work on the coloring so that the green flag and red stop button kind of pops. This may need some design changes throughout the editor but it may help

**Comment by carljbowman** [comment]
Making an initial pass on this issue within the Turbo Mode work: https://github.com/LLK/scratch-gui/issues/332
