### ISSUE TITLE
Tutorial cards can be pushed beyond width

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#2190]
### Expected Behavior

None of the draggable elements on the editor should be able to get pushed beyond the width of the web page.

### Actual Behavior

The tutorial cards can be pushed a little bit off the side of the webpage.
![image](https://user-images.githubusercontent.com/1786240/40743681-40d3a050-6420-11e8-8d98-4c8dfae1758e.png)

**Comment by sjhuang26** [comment]
I will work on this.

**Comment by thisandagain** [comment]
That would be great. Thanks @sjhuang26 !
