### ISSUE TITLE
Allow configuration of the project server backend

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#2197]
### Expected Behavior

_Please describe what should happen_
We should be able to configure where the GUI looks for projects

### Actual Behavior

_Describe what actually happens_
The GUI always looks at the production project server

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Use the GUI

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_
N/A

**Comment by paulkaplan** [comment]
If this includes changes to the `lib/storage` web sources list, it would be good if it could also include the backpack web sources there also.
