### ISSUE TITLE
Safari 9 (iOS 9) shows blank screen

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#2199]
### Expected Behavior

_Please describe what should happen_

Safari 9 should work or show unsupported modal, but it should not show blank screen.

### Actual Behavior

_Describe what actually happens_

Shows a blank screen.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

iOS Simulator, iOS 9.3 on iPad, try to load llk.github.io/scratch-gui/develop 

```
Invariant Violation: [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.

```

--- 
Judging from Sentry, this seems to be a regression, starting around May 24th.

**Comment by rschamp** [comment]
> Judging from Sentry, this seems to be a regression, starting around May 24th.

Maybe due to https://github.com/LLK/scratch-gui/pull/1991?

**Comment by paulkaplan** [comment]
I don't think so, we aren't doing any kind of filtering of browsers for Safari

**Comment by paulkaplan** [comment]
There is a disabled integration test for this, btw. When it is fixed, enable https://github.com/LLK/scratch-gui/blob/develop/test/smoke/browser.test.js#L42
