### ISSUE TITLE
"Story" letter sprites do not display in the sprite library

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#220]
Part of #172 — some SVGs don't display correctly, but these don't display at all. Fix the SVGs associated with these sprites so that they may display in the sprite library.

**Comment by paulkaplan** [comment]
@rschamp which of the solutions discussed in #172 were you thinking for this? Fixing the offending SVG files themselves?

**Comment by rschamp** [comment]
In the short-term, fixing the offending SVG files.

Pulling out the scratch-render's quirks-mode SVG renderer and using it in both the renderer and in the GUI would be good in the longer term.
