### ISSUE TITLE
Browser back button does nothing after opening and closing libraries

### ISSUE THREAD

**Issue by mrjacobbloom** [LLK/scratch-gui#2203]
### Expected Behavior

When a library is open, the browser's back button should close the library. Otherwise, it should give an "Leave site?" alert and then navigate to the previous website. Related to #1858

### Actual Behavior

After a library has been opened and closed with the DOM "<- Back" button, the browser's back button must be clicked twice to get the "Leave site?" and navigate to the previous page.

Note: no matter how many times the library is opened/closed it only takes 1 extra click of the back button to navigate away

Tested with Extensions and Sprites libraries but I imagine this applies to all of them

### Steps to Reproduce

1. Navigate to https://llk.github.io/scratch-gui/ or https://llk.github.io/scratch-gui/develop/
2. Open the Extensions library
3. Click the "<- Back" button in the library title-bar (NOT the browser's back button)
4. Click the browser's back button (nothing happens)
5. Click the button again (you get the "Leave site?" confirmation and can navigate away)

### Operating System and Browser

Windows 10 Enterprise, Chrome 66.0.3359.181 (32-bit)

**Comment by rschamp** [comment]
Unfortunately this is an expected consequence of the way `history.pushState` works — we can't delete the history item after pushing it.  So we need at least one (sometimes) useless history item which we re-use for all the libraries.

**Comment by mrjacobbloom** [comment]
Oh I missed the conversation in the original PR, my bad

**Comment by rschamp** [comment]
No problem! I wish it could work the way you expect, but it is what it is.
