### ISSUE TITLE
Move all z-index values to separate SCSS file

### ISSUE THREAD

**Issue by sjhuang26** [LLK/scratch-gui#2205]
Z-index values are currently scattered between many SCSS files. This leads to conflicts about which element is on top such as #2189, where two elements each have a z-index of 100. Perhaps moving all z-index values into a separate SCSS file would clarify situations like this.

**Comment by sjhuang26** [comment]
I will work on this.

**Comment by rschamp** [comment]
Thanks @sjhuang26! Before you work on this, we should figure out how to structure that change.  Our CSS currently is 1:1 between CSS files and components.  Would you give some more detail on how you were thinking to share the z-indexes?

**Comment by sjhuang26** [comment]
Create a single file called "z-index.css" that contains the z-indices for all the components. Then, import/include this file into each of the CSS files that need it.

**Comment by rschamp** [comment]
Simple enough, thanks!
