### ISSUE TITLE
Clicking away (inside the Stage) from a selected list monitor does not de-select it.

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#2207]
### Expected Behavior

Clicking away from a monitor should de-select it.

### Actual Behavior

This does not happen with a selected list monitor when the click happens elsewhere in the stage.

### Steps to Reproduce

1. Click on a list monitor to select it
2. Click elsewhere on the stage and notice that the monitor is still selected
3. Click elsewhere in the editor and notice that the monitor does get deselected

**Comment by paulkaplan** [comment]
This is a new incarnation of https://github.com/LLK/scratch-gui/issues/412

**Comment by paulkaplan** [comment]
This is going to be fixed with https://github.com/LLK/scratch-gui/issues/3207, so I'm going to close it
