### ISSUE TITLE
Sprite Area - Add Sprite via 'Create in Paint Editor'

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#221]
Breaking out from meta issue: https://github.com/LLK/scratch-gui/issues/53

## Scratch 2.0 Behavior

1. Click 'Paint new sprite' icon 
2. Costumes tab opens with Paint Editor
3. Draw new sprite

![add-sprite-paint-editor mov](https://cloud.githubusercontent.com/assets/3409578/23723546/9ecb2788-0417-11e7-997a-c1d36c8bffae.gif)

**Comment by thisandagain** [comment]
Moving to January and assigning to @carljbowman to resolve the system-level issue here.
