### ISSUE TITLE
If the project is listening for typing letters, typing into list monitor values can trigger those behaviors

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2212]
### Expected Behavior
In 2.0 typing into list monitors does not cause actions in the project

### Actual Behavior
In 3.0 it can

### Steps to Reproduce
1. Have a sprite that does something when space key pressed
2. Type into a list monitor. Type some spaces

### Operating System and Browser

Windows 10 Firefox

**Comment by paulkaplan** [comment]
Fixed
