### ISSUE TITLE
Scroll bars cover text on Windows

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2215]
### Expected Behavior

Scroll bars do not get in the way of UI

### Actual Behavior

Scroll bars cover blocks

### Steps to Reproduce

Be on a small screen, or add a few extensions. A scroll bar appears over the categories.
![](https://user-images.githubusercontent.com/1088291/40558933-f8abd53c-6022-11e8-9194-77f6b9114e3f.png)
On Chrome it covers the first letter of all the blocks. On Firefox it covers the last part of the category name. On Chrome especially it makes blocks hard to use.

### Operating System and Browser

Windows Chrome/Firefox

**Comment by towerofnix** [comment]
Probably the most correct solution here would be to make the scrollbar offset the block editor a little; hiding the scrollbar altogether would definitely not be good for users who have a mouse without a scrollwheel, since they wouldn't have a way to scroll the category list.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/1457
