### ISSUE TITLE
Full screen mode in youtube player doesn't go into full screen on ios

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2219]
### Expected Behavior

When playing a video from the How-To section, the full screen button in the Youtube player should cause the video to fill the whole screen.

### Actual Behavior

The fullscreen button does nothing when clicked.

### Steps to Reproduce

Click the question mark button in the upper right of the gui
Select a how to with a video (such as make a chase game)
Click the video to start it playing
Click the full screen button (bottom right of the player)
Note: nothing happens.

### Operating System and Browser

safari on ipad

**Comment by paulkaplan** [comment]
The new video widget seems to work correctly.
