### ISSUE TITLE
Selecting blue top bar in learning resource selects part of gui underneath it on ipad

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2222]
### Expected Behavior

When you select the blue bar at the top of a learning resource from the How To section you should be able to drag it without affecting anything else on the page.

### Actual Behavior

It selects the region of the gui below the resource in addition to the resource.

![ipadselectresource](https://user-images.githubusercontent.com/1088291/40863670-ab55c4e0-65be-11e8-8a2e-0912ca5359a1.PNG)
![ipadselectresource2](https://user-images.githubusercontent.com/1088291/40863671-ab60e4c4-65be-11e8-93f8-f3079a0c4775.PNG)

### Steps to Reproduce

Launch the editor
Select the question mark in the upper right
Select the a video or set of minicards from the modal
tap and drag the resource by touching the blue bar at the top of it
Note: the area under the learning resource becomes darker

### Operating System and Browser

safari on ipad

**Comment by picklesrus** [comment]
I can't reproduce this on the ipad. I wonder if got fixed when the tutorials got updated.
