### ISSUE TITLE
can't npm start. Can't resolve 'scratch-svg-renderer'.

### ISSUE THREAD

**Issue by Chen-Sanjia** [LLK/scratch-gui#2228]
![image](https://user-images.githubusercontent.com/19686455/40902813-e3b25e66-6807-11e8-9328-1dd102c49789.png)

and some module's version can't find

![image](https://user-images.githubusercontent.com/19686455/40902941-445a5bc4-6808-11e8-8b32-cc20b2113e71.png)

**Comment by ptoska** [comment]
Did you run npm install before npm start?

**Comment by Chen-Sanjia** [comment]
@ptoska I run `npm install`.

![image](https://user-images.githubusercontent.com/19686455/40904000-e35ffa0a-680b-11e8-854b-9996538db2c3.png)

so I use `yarn`.

**Comment by rockyxia** [comment]
I also encountered, how to solve this problem, I am windows

**Comment by thisandagain** [comment]
We do not support using `yarn`. Please `rm -rf node_modules` and run a fresh `npm install`.

**Comment by AngleMAXIN** [comment]
ERROR in ./src/containers/stage.jsx
    Module not found: Error: Can't resolve 'scratch-svg-renderer' in '/home/maxin/Program/WebUI/scratch-gui/src/containers'
     @ ./src/containers/stage.jsx 46:0-67 47:0-72 85:42-54 87:45-60
     @ ./src/components/stage-wrapper/stage-wrapper.jsx
     @ ./src/containers/stage-wrapper.jsx
     @ ./src/components/gui/gui.jsx
     @ ./src/containers/gui.jsx
     @ ./src/playground/blocks-only.jsx
     @ multi (webpack)-dev-server/client?http://0.0.0.0:8601 ./src/playground/blocks-only.jsx
    
    ERROR in ./src/lib/file-uploader.js
    Module not found: Error: Can't resolve 'scratch-svg-renderer' in '/home/maxin/Program/WebUI/scratch-gui/src/lib'
     @ ./src/lib/file-uploader.js 1:0-53 124:26-39
     @ ./src/containers/sound-tab.jsx
     @ ./src/components/gui/gui.jsx
     @ ./src/containers/gui.jsx
     @ ./src/playground/blocks-only.jsx
     @ multi (webpack)-dev-server/client?http://0.0.0.0:8601 ./src/playground/blocks-only.jsx
    
    ERROR in ./src/lib/get-costume-url.js
    Module not found: Error: Can't resolve 'scratch-svg-renderer' in '/home/maxin/Program/WebUI/scratch-gui/src/lib'
     @ ./src/lib/get-costume-url.js 2:0-51 21:30-41
     @ ./src/containers/watermark.jsx
     @ ./src/components/gui/gui.jsx
     @ ./src/containers/gui.jsx
     @ ./src/playground/blocks-only.jsx
     @ multi (webpack)-dev-server/client?http://0.0.0.0:8601 ./src/playground/blocks-only.jsx
    Child html-webpack-plugin for "blocks-only.html":
         1 asset
        Entrypoint undefined = blocks-only.html
        [./node_modules/html-webpack-plugin/lib/loader.js!./src/playground/index.ejs] 1.06 KiB {0} [built]
        [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
        [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {0} [built]
        [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
    Child html-webpack-plugin for "compatibility-testing.html":
         1 asset
        Entrypoint undefined = compatibility-testing.html
        [./node_modules/html-webpack-plugin/lib/loader.js!./src/playground/index.ejs] 1.06 KiB {0} [built]
        [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
        [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {0} [built]
        [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
    Child html-webpack-plugin for "index.html":
         1 asset
        Entrypoint undefined = index.html
        [./node_modules/html-webpack-plugin/lib/loader.js!./src/playground/index.ejs] 1.06 KiB {0} [built]
        [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
        [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {0} [built]
        [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
    Child html-webpack-plugin for "player.html":
         1 asset
        Entrypoint undefined = player.html
        [./node_modules/html-webpack-plugin/lib/loader.js!./src/playground/index.ejs] 1.06 KiB {0} [built]
        [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
        [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {0} [built]
        [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
    Child worker:
                          Asset      Size  Chunks             Chunk Names
            extension-worker.js  51.7 KiB    main  [emitted]  main
        extension-worker.js.map  42.3 KiB    main  [emitted]  main
        Entrypoint main = extension-worker.js extension-worker.js.map
        [./node_modules/babel-loader/lib/index.js?!./node_modules/scratch-vm/src/extension-support/extension-worker.js] ./node_modules/babel-loader/lib??ref--4!./node_modules/scratch-vm/src/extension-support/extension-worker.js 3.5 KiB {main} [built]
        [./node_modules/minilog/lib/common/filter.js] 1.36 KiB {main} [built]
        [./node_modules/minilog/lib/common/minilog.js] 1.55 KiB {main} [built]
        [./node_modules/minilog/lib/web/array.js] 319 bytes {main} [built]
        [./node_modules/minilog/lib/web/console.js] 925 bytes {main} [built]
        [./node_modules/minilog/lib/web/index.js] 1.28 KiB {main} [built]
        [./node_modules/minilog/lib/web/jquery_simple.js] 2.16 KiB {main} [built]
        [./node_modules/minilog/lib/web/localstorage.js] 530 bytes {main} [built]
        [./node_modules/scratch-vm/src/dispatch/shared-dispatch.js] 13.8 KiB {main} [built]
        [./node_modules/scratch-vm/src/dispatch/worker-dispatch.js] 6.69 KiB {main} [built]
        [./node_modules/scratch-vm/src/extension-support/argument-type.js] 523 bytes {main} [built]
        [./node_modules/scratch-vm/src/extension-support/block-type.js] 929 bytes {main} [built]
        [./node_modules/scratch-vm/src/extension-support/target-type.js] 308 bytes {main} [built]
        [./node_modules/scratch-vm/src/util/log.js] 84 bytes {main} [built]
        [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {main} [built]
            + 5 hidden modules
ℹ ｢wdm｣: Failed to compile.

**Comment by AngleMAXIN** [comment]
I want to say "fuck"!!!!

**Comment by PeaceInDream** [comment]
我尝试了几百种方法也没搞定，日！

**Comment by blackcatpolice** [comment]
I Fix It, please replace scratch-gui in package to  "scratch-gui": "0.1.0-prerelease.20190501211108"

**Comment by bygreencn** [comment]
> I Fix It, please replace scratch-gui in package to "scratch-gui": "0.1.0-prerelease.20190501211108"

@blackcatpolice Could you please give a clear information, which file had you changed? Thank you very much!
