### ISSUE TITLE
Sprite Area - Add Sprite via Camera

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#223]
Breaking out from meta issue: https://github.com/LLK/scratch-gui/issues/53

## Scratch 2.0 Behavior

1. Click 'New sprite from camera' icon
2. Camera dialog opens
3. Pose for photo and click 'Save'

![add-sprite-camera mov](https://cloud.githubusercontent.com/assets/3409578/23725259/e0f8f77e-041d-11e7-8918-8e0718986d51.gif)

**Comment by kyleplo** [comment]
![image](https://user-images.githubusercontent.com/31634240/37405454-0653fc32-276b-11e8-9a97-2c4da3429bad.png)

**Comment by kchadha** [comment]
@thisandagain, we're no longer allowing adding a sprite from the camera (due to #1744), right? Users will have to add a blank sprite and then go to the costumes tab and add a new costume from the camera.

**Comment by thisandagain** [comment]
@kchadha Correct. We are allowing adding a costume or backdrop from the camera in the "costumes" tab.
