### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#224]
Breaking out from meta issue: https://github.com/LLK/scratch-gui/issues/53

The context menu system is pervasive though-out the Scratch 2.0 GUI. Different options within the menu appear for different objects. 

One example of many — Context Menu on Sprite:
![screen shot 2017-03-08 at 4 43 58 pm](https://cloud.githubusercontent.com/assets/3409578/23725425/83b89f0a-041e-11e7-8050-3ec419269e17.png)

The context menu can be initiated by a right-click or shift click

**Comment by carljbowman** [comment]
## 3.0 Context Menu
![sprite-tile-context-menu](https://user-images.githubusercontent.com/3409578/28621095-cf148766-71dd-11e7-9803-7b9ef7b19afc.png)

The context menu should generalized for use cases throughout the GUI. Eventually this style should be ported over to the Scratch-Blocks context menus.

------

## Here are some sample 2.0 use cases:

### Sprite _tile_ in Sprite Menu
<img width="488" alt="screen shot 2017-07-26 at 8 41 39 am" src="https://user-images.githubusercontent.com/3409578/28621459-018391e6-71df-11e7-8ff9-2fe273ffc5ab.png">

### Sprite on the Stage
<img width="488" alt="screen shot 2017-07-26 at 8 41 49 am" src="https://user-images.githubusercontent.com/3409578/28621469-0eb15aa6-71df-11e7-8263-4018cb5f9df4.png">

### Stage (we currently do not have this feature, but including for reference)
<img width="490" alt="screen shot 2017-07-26 at 8 41 56 am" src="https://user-images.githubusercontent.com/3409578/28621472-15467ce8-71df-11e7-9647-c7001ac9769c.png">

### Costume in Paint Editor
<img width="441" alt="screen shot 2017-07-26 at 8 42 03 am" src="https://user-images.githubusercontent.com/3409578/28621518-3b1b46d8-71df-11e7-9ee1-962d51d26376.png">

### Sound in Sound Editor
<img width="664" alt="screen shot 2017-07-26 at 8 42 13 am" src="https://user-images.githubusercontent.com/3409578/28621509-3363de50-71df-11e7-87e1-2a83c411c4d1.png">

**Comment by liam4** [comment]
>Eventually this style should be ported over to the Scratch-Blocks context menus.

Would it make more sense to instead have scratch-blocks "request" a scratch-gui context menu? I think it would be troubling to have two entirely different context menu systems (one in scratch-gui, and one in scratch-blocks). (But the gist of what was said there still applies! Context menus from -blocks *should* look like those from -gui.)
