### ISSUE TITLE
Ctrl+Z should not delete the default Variable.

### ISSUE THREAD

**Issue by hahapang** [LLK/scratch-gui#2241]
##  Expected Behavior

Ctrl+Z should not delete the default Variable after open the web.

## Actual Behavior

The default Variable disappeared by pressing Ctrl+Z. 

<img width="426" alt="qq20180605-145540 2x" src="https://user-images.githubusercontent.com/26299904/40960788-63a7a754-68d3-11e8-9302-688183d74e76.png">
<img width="342" alt="qq20180605-145558 2x" src="https://user-images.githubusercontent.com/26299904/40960800-6ae2f276-68d3-11e8-9325-191bcac85544.png">

## Steps to Reproduce

1. Open the website. https://llk.github.io/scratch-gui/
2. Pressing Ctrl+Z.
3. The default variable has been deleted.

### Operating System and Browser

Mac OS 10.12.6  Chrome  66.0.3359.181

**Comment by Kenny2github** [comment]
Can reproduce on Chrome 66.0.3359.181 Windows 10.0.17134.48, on both [master](https://llk.github.io/scratch-gui/) and [develop](https://llk.github.io/scratch-gui/develop).

**Comment by Kenny2github** [comment]
@thisandagain why is this "critical"?

**Comment by thisandagain** [comment]
@Kenny2github Whoops! Good catch.

**Comment by joker314** [comment]
Unable to reproduce. Has this been fixed, or am I doing something wrong?

**Comment by hahapang** [comment]
> Unable to reproduce. Has this been fixed, or am I doing something wrong?

I verified it and this issue has been fixed.
