### ISSUE TITLE
On iOS Safari, sometimes the interface becomes unresponsive

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#2255]
I haven't been able to reproduce this, but on an iPad Pro using iOS 11, I was using the GUI, and got to a state where the blocks panel was not responding to touches at all.  This is here as a placeholder for more details if I or anyone else is able to reproduce the behavior.

**Comment by paulkaplan** [comment]
@rschamp there were a few blocks issues that caused the workspace to freeze that have been fixed recently. Let's re-file if this comes up again.
