### ISSUE TITLE
New variables default to capitalized on iOS Safari

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#2256]
(Note from smoketest doc: _to fix: see https://stackoverflow.com/questions/35513968/disable-auto-correct-in-safari-text-input_)

### Expected Behavior

_Please describe what should happen_
Variables should be lowercased by default

### Actual Behavior

_Describe what actually happens_
The Safari input defaults to capitalizing the first letter

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Create a new variable while using iOS Safari

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_
iOS 11 Safari 11

**Comment by tomrow** [comment]
Does iOS capitalise e-mail and web address fields by default? maybe we could trick iOS into doing what we want if we make the variable input field an URL box in the tag properties.

**Comment by JinXJinX** [comment]
on IOS, all text input has this problem. such as, sprite name and project title (there are 13 input tags in this repo). ..

**Comment by chrisgarrity** [comment]
This is the expected behavior in safari on iOS in general, and at this point is probably what iOS users expect in Scratch. If we hear otherwise it can be reopened.
