### ISSUE TITLE
Glitch with scroll bar

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#2259]
### Expected Behavior

The scroll bar should always appear in the right position.

### Actual Behavior

It doesn't ALWAYS.

### Steps to Reproduce

1. Ctrl+shift+j
2. Type "stop()"
3. Exit console
4. Drag a block on the screen.

### Operating System and Browser

Chrome on Windows 10

**Comment by joker314** [comment]
If you've managed to convince a user to open their console, there are a lot more things you can do than to stop the scrollbar appearing on the right. I don't think there's anything we can do about this.

**Comment by amazinigmech2418** [comment]
@joker314 I know, but what if someone makes an extension once temporary extension loading is allowed that uses the command?

**Comment by joker314** [comment]
Then they shouldn't use the `stop()` function? If an extension has the power to run arbitrary JavaScript in the context of a project, you can't stop someone from messing with the scrollbar.

**Comment by thisandagain** [comment]
The application continuing to work as expected after users modify the state of the program using the console is not something we can reasonably support.
