### ISSUE TITLE
Sprite Area - Add Sprite via Surprise Sprite Button

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#226]
Breaking out from suggestion in meta issue: #53

### Scratch 1.4 Behavior

Click on the 'Get surprise sprite' button – a new sprite randomly picked from the sprite library will appear.

![Demo .gif](https://cloud.githubusercontent.com/assets/9948030/23729428/276bd3ba-0438-11e7-9d43-b64bc7f18c97.gif)

This feature is not present in 2.0.

/cc @carljbowman

**Comment by carljbowman** [comment]
Awesome! Thanks for logging this issue.

**Comment by thisandagain** [comment]
Thanks @liam4. In general we are very excited to come up with ways to add "randomness" back into the GUI. :-)

**Comment by JuegOStrower** [comment]
yeeeee 😄

**Comment by thisandagain** [comment]
Tracking feature implementation in #1166
