### ISSUE TITLE
Inconsistent "Choose an extension" buttons.

### ISSUE THREAD

**Issue by AnmAtAnm** [LLK/scratch-gui#2266]
### Expected Behavior

All extension blocks buttons should have consistent height of the colored background, and consistently display (or not display) the white banner at the top of the button.

### Actual Behavior

Four of the ten buttons do not have a top white banner. Colleagues say this is different for them, but it does not change for me (tested at different window widths and zoom levels).

### Steps to Reproduce

From the Scratch preview, click the extensions button to arrive at this screen:
![screen shot 2018-06-06 at 2 23 08 pm](https://user-images.githubusercontent.com/9916202/41066044-6adb6c5a-6995-11e8-9625-23b521f5c6d8.png)

### Operating System and Browser

Chrome 67 on Mac.

**Comment by kyleplo** [comment]
When I set `display: block` to `.library-item_featured-image-container_1KIHG`, it works fine. Not sure why.

**Comment by sjhuang26** [comment]
I will work on this.
