### ISSUE TITLE
"Choose an extension" buttons fill page height if buttons fit on one row

### ISSUE THREAD

**Issue by AnmAtAnm** [LLK/scratch-gui#2267]
### Expected Behavior

Buttons should never have 80+% white backgrounds.

### Actual Behavior

If the window is wide enough (or the zoom scale is small enough) to fit all the buttons on one row, the buttons become absurdly tall filled with mostly whitespace.

### Steps to Reproduce

Open the preview. Click the extensions button. Zoom out until the buttons fit on one row:
![screen shot 2018-06-06 at 2 27 41 pm](https://user-images.githubusercontent.com/9916202/41066232-112e9366-6996-11e8-863c-89e9387cf069.png)

### Operating System and Browser

Chrome 67 on Mac.

**Comment by sjhuang26** [comment]
I will work on this.
