### ISSUE TITLE
Broadcast loop doesn't stay lit up

### ISSUE THREAD

**Issue by davidaylaian** [LLK/scratch-gui#2283]
### Expected Behavior

In Scratch 2, running the broadcast loop below lights up the script and it stays lit until you stop it. I would expect Scratch 3 to work the same way.

### Actual Behavior

The broadcast loop lights up for an instant and then goes out.

### Steps to Reproduce

Create this script in Scratch 2 and 3, and click on them:
![scratch](https://user-images.githubusercontent.com/22228595/41130237-bfa3fd76-6a83-11e8-9b30-0e5d6a887573.png)

### Operating System and Browser

Linux, tested both Firefox 60.0.1 and Chrome 67.0.3396.79.

I don't think it's related, but it's probably worth noting that if you put a variable counter inside of the loop it runs much slower in 3 than in 2.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-vm#1227
