### ISSUE TITLE
Tentacle is in the wrong place on some of the octopus costumes

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2290]
### Expected Behavior

I think this tentacle should be more attached to the octopus

### Actual Behavior

tentacle detached in several of the octopus costumes
![image](https://user-images.githubusercontent.com/2855464/41168500-26179db6-6b14-11e8-994a-5d94c1fd50b1.png)
This is in the paint editor only, not the stage

### Steps to Reproduce
Add octopus

### Operating System and Browser
Windows Edge
*Not* Firefox and Chrome on Windows.

**Comment by fsih** [comment]
Seeing something similar with the elf, he's balding
![image](https://user-images.githubusercontent.com/2855464/41168702-ba97d8de-6b14-11e8-98a9-e49e4c86f37c.png)

**Comment by fsih** [comment]
Bear's ear :(
![image](https://user-images.githubusercontent.com/2855464/41168813-08b6b0c6-6b15-11e8-9bd0-b06ac888bda8.png)

**Comment by fsih** [comment]
Seems to be a bug in the paint editor

**Comment by fsih** [comment]
![image](https://user-images.githubusercontent.com/2855464/41168881-37837e7a-6b15-11e8-8e6c-3a3be30fde09.png)

**Comment by fsih** [comment]
![image](https://user-images.githubusercontent.com/2855464/41168946-69f8a84e-6b15-11e8-9afa-427c88da1820.png)

I bet this is related to the kitten whiskers one and might be something about svgs from illustrator

**Comment by paulkaplan** [comment]
Trying hard to figure out what is going on, but I can confirm that it is something in the way the SVG is structured, running it through this SVG optimizer (which, among other things, flattens all the transforms), makes it import correctly.

**Comment by paulkaplan** [comment]
Fun update: it is the fact that there are transforms that have the y coordinate = 0. When parsing that transform, the 0 for some reason is not considered a number, causing paperjs to use the same coordinate for y as for x:

![nesting-demo.png](https://codetreeusercontent.s3.amazonaws.com/uploads/6c3c2f92-082f-487b-8722-ea99a5250aa7/nesting-demo.png)
[nesting-test.svg.zip](https://codetreeusercontent.s3.amazonaws.com/uploads/6c3c2f92-082f-487b-8722-ea99a5250aa7/nesting-test.svg.zip)

**Comment by fsih** [comment]
Paul filed paper bug https://github.com/paperjs/paper.js/issues/1487
