### ISSUE TITLE
Adding backdrop (in some cases) results in workspace crashing

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2292]
### Expected Behavior

_Please describe what should happen_
You should be able to click the add backdrop button to select a backdrop from the library.

### Actual Behavior

_Describe what actually happens_
The workspace shows the 'Oops. Something went wrong' error boundary.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
1. Load the [add-backdrop-oops.sb3](https://drive.google.com/open?id=1ihUSbXQk8KySKxHTwTOUlkpTgxexpCVp) project.
2. Start the project running.
3. Click the add backdrop button

### Operating System and Browser

macOS High Sierra version 10.13.4 (17E202) Firefox Quantum 60.0.1 (64-bit)

**Comment by paulkaplan** [comment]
Fixed in newest version.
