### ISSUE TITLE
Missing Some Translation (interface)

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#2307]
### Expected Behavior
They should be translatable.
### Actual Behavior
These are not.
* At the How-To library, the header's "How-Tos"
* categories names of libraries
* descriptions of extensions

### Steps to Reproduce
See Transifex
### Operating System and Browser
Windows 7 Home Premium 64bit SP1
Firefox 60.0.2

**Comment by apple502j** [comment]
>At the How-To library, the header's "How-Tos"
added

**Comment by chrisgarrity** [comment]
I've split this into three separate issues to track them separately - closing this one.
