### ISSUE TITLE
Add the reason that some browsers are blocked

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#2308]
### Expected Behavior
The reason that some browsers are blocked should be shown in the browser modal.

Example:
> We're very sorry, but Scratch 3.0 does not support Internet Explorer, Vivaldi, Opera or Silk because of many crash reports with them. We recommend trying a newer browser such as Google Chrome, Mozilla Firefox, or Microsoft Edge.
(reason from #1460)
### Actual Behavior
https://scratch.mit.edu/discuss/post/3137679/
> even then i don't understand why vivaldi and opera aren't supported because they run using the same engine as chrome.

### Steps to Reproduce
Open 3.0 with Vivaldi or Opera.

### Operating System and Browser
Windows 7 Home Premium 64bit SP1
Firefox 60.0.2

**Comment by python-megapixel** [comment]
I agree.
