### ISSUE TITLE
Theatre vs Theater

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#2310]
Theatre, one of the backdrop, is an UK-English word. In American English, it's "theater". Which should we use?

### Steps to Reproduce
Open backdrops library
### Operating System and Browser
Windows 7 Home Premium 64bit sp1
firefox 60.0.2

**Comment by chrisgarrity** [comment]
Given that we use American spelling throughout the UI (e.g., color), we should use 'Theater' for the backdrop, but include 'theatre' in the tags.

/cc @thisandagain
