### ISSUE TITLE
Text tool shows Asian/Korean characters

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#2332]
@ChampikaF 

### Expected Behavior
Text tool should only show English based characters

### Actual Behavior
Text tool shows Asian/Korean characters
<img width="792" alt="scratch_3_0_gui" src="https://user-images.githubusercontent.com/3812168/41373143-6c914f1e-6f1d-11e8-909d-ad8ee81ee9d3.png">

### Steps to Reproduce
1. Open a 3.0 project
2. Click on the Costumes tab
3. Select the Text tool
4. Select the font dropdown menu
5. See Asian/Korean characters

### Operating System and Browser
macOS High  @Sierra, Chrome 67

**Comment by apple502j** [comment]
**No way!** As a Japanese person, I wanted to have them!
In Scratch 2.0, they are unable to type Chinese/Japanese/Korean characters at all.
They have to write on Inkscape, convert it so that it'll fit on Scratch, and import them.
I'm sure most Japanese, Chinese, and Koreans want these fonts!

And please read this again, please.
> Scratch welcomes people of all ages, races, ethnicities, religions, abilities, sexual orientations, and gender identities.

**Comment by hedgehog125** [comment]
@apple502j I strongly agree. However, it might be confusing especially for younger English Scratchers so maybe it would make sense to only show fonts that support the selected language by default.

**Comment by hedgehog125** [comment]
@hedgehog125 And visa versa.

**Comment by thisandagain** [comment]
@techwonder21 These are the proper names for our new fonts for Chinese (Simplified), Japanese, and Korean. This is not a bug.

**Comment by techwonder21** [comment]
@thisandagain thanks for the context. I was uncertain as these fonts weren't in 2.0 but is glad they're now in 3.0 :)
