### ISSUE TITLE
New sprites are randomly positioned only in top right quadrant

### ISSUE THREAD

**Issue by danfarrow** [LLK/scratch-gui#2340]
### Expected Behavior

When adding or duplicating sprites they should be positioned randomly on the stage

### Actual Behavior

Sprites are only positioned in the top right quadrant of the stage, where X & Y are positive

### Steps to Reproduce

Create a bunch of new sprites and notice that they only appear in the top right quadrant of the stage

### Operating System and Browser

Windows 10, Firefox 60.0.2, MS Edge 42.17

![scratch3-random-sprite-placement](https://user-images.githubusercontent.com/236580/41405840-a9db2e80-6fc2-11e8-83da-4c2c98c9e55d.jpg)

**Comment by paulkaplan** [comment]
For anyone interested in fixing this, the fix would be in scratch-vm, src/sprites/rendered-target in the duplicate method, changing the newTarget.x/y to use `(Math.random() - 0.5)` instead of `Math.random()`

**Comment by towerofnix** [comment]
@paulkaplan PR incoming!
