### ISSUE TITLE
The data is duplicated when inserting a string to a list with Chinese input method.

### ISSUE THREAD

**Issue by hahapang** [LLK/scratch-gui#2341]
##  Expected Behavior

The data should not duplicated.

## Actual Behavior

The data  is duplicated, please see the attach file. This issue doesn’t occur with English input method.  

## Steps to Reproduce

1. Make a new list.
2. Add a string to list.
3. Insert “string” at 1 of list.
4. Modify the “string” with Chinese input method and press “Return” keyboard.
<img width="905" alt="1" src="https://user-images.githubusercontent.com/26299904/41406808-0ae0fe8e-7000-11e8-85dd-f0f0f3b521da.png">
<img width="915" alt="2" src="https://user-images.githubusercontent.com/26299904/41406817-12bb0ee2-7000-11e8-8a83-ebc7653acc1c.png">
<img width="1313" alt="3" src="https://user-images.githubusercontent.com/26299904/41406825-19c727de-7000-11e8-87e1-3e71d41a2532.png">
<img width="892" alt="4" src="https://user-images.githubusercontent.com/26299904/41406831-1eaa9d94-7000-11e8-9f6b-105d9eba9cfe.png">

## Operating System and Browser

Mac OS 10.12.6 Chrom 66.0.3359.181

**Comment by ubertao** [comment]
@hahapang As a work around, you can always press space bar instead of return key to select the first input candidate.
