### ISSUE TITLE
The arrow button on comments sometimes overlaps the comment text

### ISSUE THREAD

**Issue by technoboy10** [LLK/scratch-gui#2352]
### Expected Behavior
Minimized comment descriptions should not overlap with the expand comment button.
<img width="314" alt="screenshot 2018-06-14 13 35 23" src="https://user-images.githubusercontent.com/3019167/41428407-0782231c-6fd8-11e8-9827-2e8094089ecb.png">

### Actual Behavior

Sometimes the arrow button _does_ overlap with a minimized comment's description.
<img width="322" alt="screenshot 2018-06-14 13 34 13" src="https://user-images.githubusercontent.com/3019167/41428436-194d2f60-6fd8-11e8-8996-a37cf1e038d0.png">

### Steps to Reproduce
Go to https://preview.scratch.mit.edu/#228229901 and look at the comments in Sprite1.

### Operating System and Browser

macOS 10.13.5, Firefox Nightly 62, Safari 11.11.1, Chrome 67
Chromebook Chrome 66

**Comment by thisandagain** [comment]
Moved to LLK/scratch-blocks#1602
