### ISSUE TITLE
Block comments don't visually get picked up when the block is dragged

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#2353]
Edit: Probably a better fit for scratch-blocks. Also, related to LLK/scratch-blocks#1554.

### Expected Behavior

Dragging a block that as an attached block comment should bring that comment to the same z-index/layer as the block; for example, dragging the block above the stage should make the comment also be above the stage.

(Looks like there's a "blocklyDragSurface" element that the comment should be pulled into?)

### Actual Behavior

When you drag a block with an attached block comment over the stage (or other elements of the GUI outside of the scratch-blocks part), the comment disappears.

### Steps to Reproduce

Drag out a block and give it a block comment (right click -> add comment). Drag the block over the stage.

Note also that dragging the block over the palette makes the comment show up below the palette (since the comment follows the block's position but doesn't actually come up into the same layer as the block).

### Operating System and Browser

Firefox 61.0b13, Debian (testing).

**Comment by thisandagain** [comment]
Moved to LLK/scratch-blocks#1603
