### ISSUE TITLE
Blocks categories are cropped when scrollbars are present

### ISSUE THREAD

**Issue by filips123** [LLK/scratch-gui#2364]
### Expected Behavior

Scrollbar should be aligned correctly.

### Actual Behavior

Scrollbar hides and crops blocks categories names.

### Steps to Reproduce

1. Open Scratch 3.0 (https://preview.scratch.mit.edu/).
2. Add all available extensions.
3. Minimize browser window.
4. Categories on the right will be hidden under a scrollbar.

### Operating System and Browser

Windows 10
Firefox 60, Chrome 67

### Screenshots
Firefox:
![firefox](https://user-images.githubusercontent.com/16626308/41473414-82865e52-70b9-11e8-99ca-50b8782c1f04.png)

**Chrome:**
![chrome](https://user-images.githubusercontent.com/16626308/41473465-a6ab0954-70b9-11e8-9ba2-b34bb2d6737d.png)

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/1457
