### ISSUE TITLE
Remove block for Vivaldi

### ISSUE THREAD

**Issue by python-megapixel** [LLK/scratch-gui#2370]
[Edited by @thisandagain]

## Issue Scope
Remove block logic for Vivaldi as it is Chromium based and *should* work with Scratch 3.0. The Scratch Team will not officially support Vivaldi, but (for now) there is no reason to explicitly block it (unlike Opera Mini, Internet Explorer, and Silk which we know have breaking bugs).

Also update text in [the modal](https://github.com/LLK/scratch-gui/blob/a991e106087506ac89f2fd2f7d096c1dfc526e32/src/components/browser-modal/browser-modal.jsx#L35) to read:

>We are very sorry, but Scratch does not support this browser. We recommend trying a supported browser such as Google Chrome, Mozilla Firefox, Microsoft Edge, or Apple Safari.

## Original Description by @python-megapixel 
The warning for unsupported browsers claims that users on Vivaldi or Silk should switch to "a newer browser" such as Chrome or Firefox. This is an inaccurate description because Vivaldi was released in 2015 and Silk was released in 2011, while Chrome was released in 2008 and Firefox in 2002.

**Comment by WorldLanguages** [comment]
Isn't Vivaldi Chromium based?

**Comment by python-megapixel** [comment]
@WorldLanguages Yes. Another reason why it seems strange to block it, especially it works perfectly if one removes the block using Inspect Element in Vivaldi.

**Comment by tomrow** [comment]
Vivaldi must be a fork of an old version of Chromium that has not had its UserAgent string updated. I would suggest using an alternative browser, as Vivaldi may be using an out of date engine as well.

**Comment by Cqoicebordel** [comment]
Vivaldi and Opera (at least) are both based on Chromium, and are both (mostly) up to date. Neither of them are forks of Chromium. They use the up to date version of Chromium as engine, and they "just" develop the UI over it.
There is no reasons why those browsers are blocked.
Even the commit blocking Vivaldi doesn't give an explanation (cb8f14568f4448abe4f91e6490aedf5dc8715caa)

To correct it, I think editing https://github.com/LLK/scratch-gui/blob/bdfd22543f520e204ec15f46cf9f33e0fdc20ed3/src/lib/supported-browser.js#L9 would suffice (and of course the text associated to it in scratch-gui/src/components/browser-modal/browser-modal.jsx)

**Comment by thisandagain** [comment]
I'm inclined to agree. I think there is a difference between "we don't officially support Vivaldi" and "we know that this browser doesn't work (e.g. Opera and Internet Explorer) so we are going to block it". I'm open to a PR that removes Vivaldi from the block.

**Comment by infinitytec** [comment]
Looks good. There were people on the beta forums quite confused with this.
