### ISSUE TITLE
Which blocks should be present for a backdrop's scripting area?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#238]
### Expected Behavior

In 2.0, fewer blocks are available to backdrops than to sprites.

### Actual Behavior

In 3.0, all of the blocks are available to backdrops.

### Operating System and Browser

_Mac El Capitan, Chrome 56_

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/682
