### ISSUE TITLE
Soft keyboard should not open by default when switching to a sprite of just comments

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2387]
### Expected Behavior

_Please describe what should happen_
When on a tablet, the soft keyboard should not automatically open when you switch sprites.

### Actual Behavior

_Describe what actually happens_
If the only thing in a sprite's workspace is a comment, it is focused by default and the soft keyboard opens.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
In the browser on Android (probably also iOS), switch to a sprite that has nothing but a comment in the workspace.

### Operating System and Browser

_Android Chrome_

**Comment by paulkaplan** [comment]
Fixed!
