### ISSUE TITLE
Preview Crashing on project 219715238

### ISSUE THREAD

**Issue by colbygk** [LLK/scratch-gui#2392]
### Expected Behavior

Project should load with ~5000+ assets

### Actual Behavior

Immediately crashes

### Steps to Reproduce

Load https://preview.scratch.mit.edu/#219715238

### Operating System and Browser

macOS 10.13.14 Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by paulkaplan** [comment]
Interestingly this isn't a problem with the 5000+ assets, it is actually because of a hacked block buried deep within the project...

Fixed with https://github.com/LLK/scratch-vm/pull/1254
