### ISSUE TITLE
scroll bar covering initial part of blocks in blocks palette

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-gui#2396]
After adding a couple extensions, a scroll bar appears which covers up the first part of the blocks and block category names.

Mac OS 10.13.4 Chrome 67.0.3396.87

![image](https://user-images.githubusercontent.com/4721032/41606197-15f2764a-73b1-11e8-8abd-824faa499246.png)

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/pull/2406 and https://github.com/LLK/scratch-blocks/issues/1457
