### ISSUE TITLE
Variable location and visibility not saved

### ISSUE THREAD

**Issue by chexbox** [LLK/scratch-gui#2398]
When I uploaded a project from my computer (sb3), the variable was hidden and was back to the top left corner. This was the 'my variable' which had been renamed.

Chrome, Raspbian

**Comment by thisandagain** [comment]
Could you share the SB3 file with us and/or project some screen shots?

**Comment by chexbox** [comment]
I save the project:
![2018-06-30-105739_1279x567_scrot](https://user-images.githubusercontent.com/31783961/42126888-b125dca0-7c54-11e8-9725-4508fcd284f7.png)
I re-upload it, without reloading the page:
![2018-06-30-105854_1279x567_scrot](https://user-images.githubusercontent.com/31783961/42126889-b150f67e-7c54-11e8-918e-267deb8682aa.png)
I reload the page, and upload it again:
![2018-06-30-110147_1279x567_scrot](https://user-images.githubusercontent.com/31783961/42126909-24708ec6-7c55-11e8-80bc-b696c68f73b4.png)
Now I show the variable that had been hidden:
![2018-06-30-110158_1279x568_scrot](https://user-images.githubusercontent.com/31783961/42126910-2490a60c-7c55-11e8-80a7-5744fa18fe88.png)

Here is the project:
[translate2.zip](https://github.com/LLK/scratch-gui/files/2151988/translate2.zip)

**Comment by nekketsuuu** [comment]
I also encountered the same issue on https://beta.scratch.mit.edu/ on Aug 2, 2018.

## How to reproduce

1. Create a new project, create one variable, and show the variable.

    ![Variable "test" is shown on the screen](https://user-images.githubusercontent.com/4374702/43581012-4f9303de-9692-11e8-81cc-03d1e14e898f.PNG)

2. Download the project.
3. Upload the project on a new tab. Then the variable is not shown.

    ![Variable "test" is NOT shown on the screen](https://user-images.githubusercontent.com/4374702/43581042-740302a0-9692-11e8-90dd-c9f67a8a5c92.PNG)

Here is the project:

[test.zip](https://github.com/LLK/scratch-gui/files/2253299/test.zip)

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/3086
