### ISSUE TITLE
[temp] Add empty area without keyboard handling

### ISSUE THREAD

**Issue by dekrain** [LLK/scratch-gui#24]
I want this b/c on playground when I trying to open DevTools (F12 in Chrome) it fails because of playground's keyboard handler. It will be only in developing phase.

**Comment by rschamp** [comment]
As of #23 you should be able to use `Ctrl-Shift-I`/`Cmd-Opt-I` for this.

**Comment by dekrain** [comment]
Theoretically this should work, but in practice it still not working.

**Comment by rschamp** [comment]
Would you please open a new issue for that explaining how to reproduce?

**Comment by dekrain** [comment]
It doesn't working with `CTRL+Shift+I`, but I will open it in URL bar in future.
