### ISSUE TITLE
Sprite Tile - Hover state is the same as Selected state

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#240]
![hover-and-active-states](https://cloud.githubusercontent.com/assets/3409578/23860444/5f1dc4a0-07dd-11e7-87e1-fac504580e54.png)

Apart from the Delete icon (which is temporary) there is no indication of which sprite is selected while another sprite retains the hover state. This can lead to confusion of which sprite is being coded.

These states need to be explored further.

cc @ntlrsk @morantsur

**Comment by carljbowman** [comment]
@lifeinchords - Assigning to you. It'd be great to sketch on as you progress with the various libraries.

**Comment by liam4** [comment]
I've no intention to nitpick, but – why was this closed? It doesn't seem to be resolved?

**Comment by mrjacobbloom** [comment]
Potentially because of #514? But you're right, I'm not seeing any changes yet

**Comment by thisandagain** [comment]
Tracking in #514
