### ISSUE TITLE
Variable & list monitors don't display boolean values

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#2409]
### Expected Behavior

Variable monitors that have boolean values (true or false) and list monitors that contain boolean values should display these values correctly (i.e. as the strings "true" or "false").

### Actual Behavior

Variable monitors don't show true/false at all. List monitors only show the value while the list item's input is selected.

### Steps to Reproduce

Create a variable and set its value to a boolean value (e.g. by using a block such as "1 = 1"). Create a list and add a boolean value to it.

### Operating System and Browser

Firefox 61.0b14, Debian (testing).

---

I created [this repro project](https://scratch.mit.edu/projects/229846207/) and compared the results in 2.0 and 3.0:

![2.0 results](https://user-images.githubusercontent.com/9948030/41628539-62ce3720-73fb-11e8-9be8-5aa8c5a9493b.png) ![3.0 results](https://user-images.githubusercontent.com/9948030/41628538-62bf1f10-73fb-11e8-9c2d-06cbc2f9f037.png)

**Comment by thisandagain** [comment]
Yikes! Good catch. Thanks @towerofnix

**Comment by towerofnix** [comment]
Note to self - fix may be needed for all three variable monitor views. Normal and large monitors both are empty, sliders show 0 or 1 (for false or true).
