### ISSUE TITLE
Sprite list is vertical

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2428]
### Expected Behavior
Sprites should fill the space

### Actual Behavior
Sprites are 1 across in the sprite list

### Steps to Reproduce
Go to https://llk.github.io/scratch-gui/develop/#230085524
![image](https://user-images.githubusercontent.com/2855464/41734911-53dcef84-7556-11e8-9524-789dd3075482.png)

### Operating System and Browser
Windows Chrome

**Comment by dgnball** [comment]
When I click your link it behaves the same way using Firefox on Mac OS. What steps did you go through to create this effect?

**Comment by fsih** [comment]
I think it's because the sprite names are so long.

**Comment by fsih** [comment]
Duplicate of https://github.com/LLK/scratch-gui/issues/2430
