### ISSUE TITLE
Spacing varies between sprites in the sprite library (space-between)

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#243]
Reported via internal playtest 3/13/17.

### Expected Behavior

In a row of less than the entire width of the sprite menu, the sprites should all be left-aligned with the same spacing as the rows above.

### Actual Behavior

The sprites are spread out across the row, with too much space between them.

<img width="1125" alt="screen shot 2017-03-13 at 1 27 28 pm" src="https://cloud.githubusercontent.com/assets/1320456/23867229/a4d5d83e-07f1-11e7-826d-6dedf672a036.png">

### Operating System and Browser

_Mac & Chrome_

**Comment by thisandagain** [comment]
This looks like a simple flexbox issue (*should* be simple to resolve).

**Comment by dgnball** [comment]
I can't recreate this using Chrome or FF on Mac OS. Suggest this is closed.
