### ISSUE TITLE
Sprites with long names mess up the sprite list

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2430]
### Expected Behavior

_Please describe what should happen_
When a sprite has a long name it should be truncated in the sprite grid, and the sprite grid should line up as normal.

### Actual Behavior

_Describe what actually happens_
![screen shot 2018-06-21 at 3 51 05 pm](https://user-images.githubusercontent.com/399209/41742253-8139364e-756b-11e8-82bc-15f0e07c163d.png)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
https://preview.scratch.mit.edu/#222183421
The first sprite already has a long name. Change others to see spacing.

### Operating System and Browser

macOS High Sierra version 10.13.4 (17E202) Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by paulkaplan** [comment]
Aha! You figured it out! I was going crazy trying to repro this and couldn't figure it out.
