### ISSUE TITLE
Tab names are incorrectly aligned

### ISSUE THREAD

**Issue by filips123** [LLK/scratch-gui#2435]
### Expected Behavior

Tab names should have the same wide as blocks categories.

### Actual Behavior

Tab names (Code, Costumes, Sounds) are incorrectly aligned. They are wider then blocks categories.

### Steps to Reproduce

1. Open Scratch 3 Preview
2. Look tabs and block categories.

### Operating System and Browser

Firefox 60, Windows 10

### Screenshots

**Firefox:**
![slika](https://user-images.githubusercontent.com/16626308/41771875-dfb52646-7616-11e8-9a0d-01f81777ed5d.png)

**Chrome:**
![slika](https://user-images.githubusercontent.com/16626308/41771904-fb0c11f2-7616-11e8-8946-296513329c13.png)

**Comment by filips123** [comment]
In some translations, the width of the tab is different.

**Comment by mxmou** [comment]
This is intentional according to https://github.com/LLK/scratch-gui/issues/7036#issuecomment-820716297.

**Comment by cwillisf** [comment]
Yep - what @filips123 and @mxmou said. Thanks!

The tabs will get wider and narrower depending on the selected language and other factors. If they happen to line up, that's just luck :)
