### ISSUE TITLE
Gzip the JS when deploying to preview

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#2440]
It would be nice if we could serve gzipped js from the preview domain instead of the plain text version, it'd save people about 5mb of downloading when the hit `preview`. Github pages does this for us automatically, and I noticed the size difference when testing smoke against preview:

Preview 
![image](https://user-images.githubusercontent.com/654102/41787699-3bcdc05a-7617-11e8-9986-f2fd259b86aa.png)

Github pages branch url
![image](https://user-images.githubusercontent.com/654102/41787708-433ffd80-7617-11e8-9dd3-a70610fc092f.png)

**Comment by dgnball** [comment]
According to [Netcraft,](https://toolbar.netcraft.com/site_report?url=https%3A%2F%2Fpreview.scratch.mit.edu%2F#last_reboot) you are hosted on Fastly. You should be able enable gzip compression by following [these](https://docs.fastly.com/guides/basic-configuration/enabling-automatic-gzipping.html) instructions.

**Comment by thisandagain** [comment]
@rschamp Do you mind investigating this? It would be nice to have this resolved before the conference (on both domains).
