### ISSUE TITLE
Sprite tile images disappear after changing zoom and switching sprites 

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#2445]
### Expected Behavior

Sprite tile images shouldn't disappear.

### Actual Behavior

After changing the browser zoom level (e.g. with cmd + or cmd -), clicking a sprite selector tile causes the image to disappear:

![zoom-disappearing-sprite-tiles-bug](https://user-images.githubusercontent.com/567844/41798485-d0b90aca-763b-11e8-8895-dd30e1f879a6.gif)

### Steps to Reproduce

- Add some sprites
- Change browser zoom level
- Switch sprites

### Operating System and Browser

Mac OS 10.13.2 Chrome 66

**Comment by gnarf** [comment]
It's eeven worse now, it seems to lose all the sprites after zoom / any interaction with any of them:

https://clips.twitch.tv/BadMoldyNuggetsTinyFace
