### ISSUE TITLE
Language menu has wrong layer

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#2446]
### Expected Behavior
It should be either

- unclickable
- put on correct layer

### Actual Behavior
It shows "We're working on it" when hovering, but it's clickable and makes a menu on wrong layer!
[![https://gyazo.com/90916c9222e64f5972c7475fac9391d7](https://i.gyazo.com/90916c9222e64f5972c7475fac9391d7.gif)](https://gyazo.com/90916c9222e64f5972c7475fac9391d7)
### Steps to Reproduce
Open *normal* scratch-gui/develop, without ?enable=lang (see #2326)
https://llk.github.io/scratch-gui/develop/

### Operating System and Browser
Windows 7 Home Premium 64bit SP1
Firefox 60.0.2

**Comment by apple502j** [comment]
Have no problem with ?enable=language version

**Comment by thisandagain** [comment]
Please refrain from creating issues for localization / language menu until the feature is fully supported on the `develop` branch. We are still working on things.
