### ISSUE TITLE
Sounds do not play on iOS safari anymore

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#2453]
### Expected Behavior

_Please describe what should happen_

play sound block should play a sound on iOS Safari

### Actual Behavior

_Describe what actually happens_

It does not play a sound. @ericrosenbaum said he was able to get it to play a sound after using the sound recorder, which makes me suspect something about the hack for enabling the audio context isn't working any longer, perhaps due to the audio engine refactor?

---
Filed here but could be due to an issue in one of a number of different repos.

/cc @mzgoddard @gnarf

**Comment by Clark-E** [comment]
It works fine for me on IOS 11.3 in safari.

**Comment by mzgoddard** [comment]
`play sound` block played a sound for me on iOS 11.4 and 10.3. I tested https://preview.scratch.mit.edu https://llk.github.io/scratch-gui/develop/ and a local build.

**Comment by paulkaplan** [comment]
welp, i can't repro either... ¯\_(ツ)_/¯ false alarm I suppose
