### ISSUE TITLE
block comments and workspace comments have different text defaults

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2456]
### Expected Behavior

I'm not sure what's supposed to happen.  It seems that when you create any comment it has a prompt text such as "Say Something..." and when you select the comment it adds a cursor and removes the default text.  Or it could say nothing by default.

### Actual Behavior

Block comments default to having no text while Workspace Comments say "Say Something..." They should probably have the same behavior.  The user must manually delete the "Say Something..." from the workspace before adding their own comment.

![screen shot 2018-06-25 at 10 29 11 am](https://user-images.githubusercontent.com/1088291/41856427-126fa608-7863-11e8-899c-86122d60884f.png)

### Steps to Reproduce

Drag a block out
Right click it
Click "Add Comment" from the context menu
Right click the stage somewhere
Click Add Comment from the context menu
Note: They have different default texts

### Operating System and Browser

Chrome on Mac

**Comment by paulkaplan** [comment]
No longer the case
