### ISSUE TITLE
Implement tab indexing between input fields

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#246]
Reported via internal playtest 3/13/17.

### Actual Behavior

Pressing "tab" to go between inputs in a block works but once you get to the end of the block the tab order goes all over the interface including blocks *above* the one you are editing and the GUI.

### Operating System and Browser

_Mac & Chrome_

**Comment by thisandagain** [comment]
See existing behavior in Scratch 2.0

**Comment by jwzimmer** [comment]
Fixing in https://github.com/LLK/scratch-blocks/pull/1030.
