### ISSUE TITLE
"broadcast and wait" is not working properly

### ISSUE THREAD

**Issue by a49594a** [LLK/scratch-gui#2461]
### Expected Behavior

"broadcast and wait" should wait until the receiver finished

### Actual Behavior

"broadcast and wait" do not wait

### Steps to Reproduce

https://llk.github.io/scratch-gui/master/#217803438
the cat should rotate every 2 second, but it rotate much faster

### Operating System and Browser
windows 10
chrome 67.0.3396.87 64bit

**Comment by paulkaplan** [comment]
@mzgoddard before I start digging deep into this, just wondering if you had any pointers, if anything pops to mind about what might be going on here?
