### ISSUE TITLE
A block with a dropdown menu on its first looks weird

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#2462]
![screenshot_2018-06-26-18-28-24-489_com android chrome](https://user-images.githubusercontent.com/31377746/41905827-de9cebee-796e-11e8-96e3-53ff0572143d.png)

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

Turn language to Chinese, because the “go (front v) (1) layers” is translated into (前移 v)(1)层

### Operating System and Browser

ALL

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/2447
