### ISSUE TITLE
Block dropdown loaded with the wrong size

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2476]
### Expected Behavior
Dropdown should fit the size of the contents

### Actual Behavior
Dropdown is collapsed
![image13](https://user-images.githubusercontent.com/1088291/41791093-b0d0a042-7622-11e8-973d-a6cf6082b42c.png)

### Steps to Reproduce
I don't know how this happened ):

### Operating System and Browser
Windows Firefox

**Comment by BryceLTaylor** [comment]
This could be related to this one: https://github.com/LLK/scratch-gui/issues/2502

**Comment by BryceLTaylor** [comment]
If it is related to that one they do not have the same repro steps.

**Comment by BryceLTaylor** [comment]
I can not reproduce this.  If someone sees this again and adds more information about what they were doing, I'll look into it again.
