### ISSUE TITLE
Some sprites aren't grouped properly

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2478]
### Expected Behavior
It would be helpful to have more natural grouping of sprites

### Actual Behavior
For example, each of the skeleton's bones is separate, and it would help if the entire arm were grouped

**Comment by thisandagain** [comment]
This needs to be more narrowly specified if it is going to be helpful.

**Comment by fsih** [comment]
For the spooky sprites, there is currently no grouping. Here are the top-level groupings that I might expect

For the ghost
![image](https://user-images.githubusercontent.com/2855464/41935055-73f1e000-7956-11e8-942a-5b19acf6b2fc.png)

Frank
![image](https://user-images.githubusercontent.com/2855464/41935197-d34692e4-7956-11e8-9f02-ad1a41c09203.png)

Skeleton
![image](https://user-images.githubusercontent.com/2855464/41935272-109f52ca-7957-11e8-9fbc-82496700b563.png)

Bat
![image](https://user-images.githubusercontent.com/2855464/41935385-850aa632-7957-11e8-9571-8090a9820b92.png)

(also other sprites from this artist)
![image](https://user-images.githubusercontent.com/2855464/41935492-dda06336-7957-11e8-83fa-0b01e6344498.png)

**Comment by kosiecki17** [comment]
These particular issues have been addressed. 

Incremental improvements to sprite grouping will continue in small batches.
