### ISSUE TITLE
Toggles in sprite pane misplaced, text out of container

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#248]
Reported via internal playtest 3/13/17.

### Expected Behavior

<img width="418" alt="screen shot 2017-03-13 at 2 26 46 pm" src="https://cloud.githubusercontent.com/assets/1320456/23869371/1c53fd26-07f9-11e7-9ead-35ea535acd5f.png">

### Actual Behavior

<img width="568" alt="screen shot 2017-03-13 at 2 27 14 pm" src="https://cloud.githubusercontent.com/assets/1320456/23869416/3afc3810-07f9-11e7-82a7-e3b812a4469c.png">

### Operating System and Browser

_Unknown_

**Comment by thisandagain** [comment]
Can't repro in latest Chrome. Closing for now.
