### ISSUE TITLE
Behavior of stop all sounds different from scratch 2

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2482]
### Expected Behavior
Behavior matches scratch 2
It's also more intuitive that stop all sounds only stops the currently playing sound

### Actual Behavior
Stop all sounds also stops future sounds that haven't started playing yet, except not sounds after stop all sounds, or maybe other blocks I haven't tried.

### Steps to Reproduce
Click the stack on the right, then click the stack on the left. As soon as you click the stack on the left, the cymbal sound plays. In Scratch 2 it stops the current sound, and immediately moves on to the next pop. As a wise can once said, once you pop, you can't stop.
![image14](https://user-images.githubusercontent.com/1088291/41791392-9e0873e4-7623-11e8-8c14-a4a44cdcc076.png)

### Operating System and Browser
Windows Firefox

**Comment by ericrosenbaum** [comment]
I'm not able to reproduce this on mac chrome or mac firefox- maybe it's specific to windows firefox?

**Comment by thisandagain** [comment]
Thanks for trying @ericrosenbaum! @BryceLTaylor mind attempting a repro on our Windows machines?

**Comment by BryceLTaylor** [comment]
I can NOT reproduce this on Windows Firefox.  @fsih can you still see this issue.  Or, to be a bit more pedantic, hear it?

**Comment by fsih** [comment]
Yup it does not happen to me anymore
