### ISSUE TITLE
Some (but not all) vector backdrop thumbnails appear messed up

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#2487]
### Expected Behavior
Vector backdrops should be masked to a 4:3 ratio viewbox within the thumbnail representations (e.g. Backdrop Library & Stage Info Area). The viewbox should crop the overflowing shapes/paths to the viewbox (the result should mimic how these backdrops are rendered in the Stage or Vector Editor Workspace). 

An example of where this works properly: 
<img width="180" alt="screen shot 2018-06-26 at 4 34 47 pm" src="https://user-images.githubusercontent.com/3409578/41937762-345115fc-795f-11e8-9709-9a1a18b97c04.png">

### Actual Behavior
Some vector backdrops ignore the viewbox, see below:
<img width="359" alt="screen shot 2018-06-26 at 4 31 14 pm" src="https://user-images.githubusercontent.com/3409578/41937607-c4c9a6cc-795e-11e8-991b-1a83afb57b76.png">
<img width="80" alt="screen shot 2018-06-26 at 4 38 07 pm" src="https://user-images.githubusercontent.com/3409578/41937809-577574ba-795f-11e8-917e-9065820018fe.png">
<img width="87" alt="screen shot 2018-06-26 at 4 38 09 pm" src="https://user-images.githubusercontent.com/3409578/41937822-58eecf1c-795f-11e8-9a7a-baec2ed0319b.png">

### Steps to Reproduce

1. Open Backdrop Library
2. Look at Baseball backdrops thumbnails
3. Add to project to see broken Stage Area rendering and Backdrop List thumbnail rendering in the Vector Editor.

### Operating System and Browser

OS: mac OS 10.13.5
Browser: Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by thisandagain** [comment]
This is now fixed. :-)
