### ISSUE TITLE
The default <position> of <sprite> is x-position of stage, but stage can't change x-position

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#249]
Reported via internal playtest 3/13/17.

### Expected Behavior

The default for <position> of <sprite> is x-position of stage - but it doesn't make sense because the stage can't change x-position. 

In 2.0, the default is the x-position of the active sprite:
<img width="199" alt="screen shot 2017-03-13 at 2 34 35 pm" src="https://cloud.githubusercontent.com/assets/1320456/23869674/3acd8406-07fa-11e7-9c38-9daaca8af186.png">

### Actual Behavior

Whether a sprite or backdrop is active, the value of <position> of <sprite> is x-position of stage.
<img width="244" alt="screen shot 2017-03-13 at 2 30 27 pm" src="https://cloud.githubusercontent.com/assets/1320456/23869627/092c8f0a-07fa-11e7-89a5-e3c9719d1caa.png">

<img width="1138" alt="screen shot 2017-03-13 at 2 30 36 pm" src="https://cloud.githubusercontent.com/assets/1320456/23869603/ef9b5ee0-07f9-11e7-950d-97994854d1d7.png">

### Operating System and Browser

_Mac & Chrome_

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/541
