### ISSUE TITLE
prueba

### ISSUE THREAD

**Issue by TeamPaco** [LLK/scratch-gui#2492]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
This is not a sandbox. Please don't test here.
