### ISSUE TITLE
Translation for How-To Images

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#2493]
### Expected Behavior
Anything should be translated.

### Actual Behavior
There are no ways to translate How-Tos images (thumbnails).
* Example 1
![](https://screenshotscdn.firefoxusercontent.com/images/23be362f-25d6-4a7c-8c00-58af8519a2cf.png)

* Example 2
![](https://screenshotscdn.firefoxusercontent.com/images/6896273a-f916-445b-848e-75e7423db4eb.png)

### Steps to Reproduce
1.Set Language to ja (?locale=ja)
2.Open How-Tos

### Operating System and Browser
Windows 7 HomePremium SP1 Firefox 60.0.2

**Comment by chrisgarrity** [comment]
The How-to images are being replaced and will not have text on them (with the exception of 'Anya', as that's a name).
