### ISSUE TITLE
Localize library tags

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2501]
### Expected Behavior

_Please describe what should happen_
The tags to filter the library should display in the currently selected language. The filtering will still need to be in english since the actual tags on the assets are in english. (part of #2307)

### Actual Behavior

_Describe what actually happens_
![screen shot 2018-06-27 at 10 18 18 am](https://user-images.githubusercontent.com/399209/41980037-7f1a9f56-79f3-11e8-9a30-136b68f6ddec.png)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Switch to French and add a sprite from the library.

### Operating System and Browser

Mac OS 10.13.5 Chrome

**Comment by chrisgarrity** [comment]
@thisandagain CS First needs this for recording videos.... I don't think it can be backlogged.

**Comment by thisandagain** [comment]
@paulkaplan Can you help support @chrisgarrity on this one?
