### ISSUE TITLE
Costume block input can overflow after creating a new sprite

### ISSUE THREAD

**Issue by technoboy10** [LLK/scratch-gui#2502]
### Expected Behavior
Block inputs should never overflow over other block text.

### Actual Behavior
Block inputs sometimes overflow.
![ezgif com-optimize 2](https://user-images.githubusercontent.com/3019167/41980658-03053870-79f5-11e8-92e2-2737dd301b92.gif)

### Steps to Reproduce

Load the default project, and switch to the costumes tab of the Scratch Cat sprite. Create a new sprite. On the new sprite, switch to the code tab and navigate to the looks blocks. 

### Operating System and Browser

macOS 10.13.5 Firefox Nightly 63, Chrome 67, Safari 11.1.1

**Comment by paulkaplan** [comment]
@technoboy10 can you try to repro this on develop? I think it has been fixed, but could you confirm?

**Comment by technoboy10** [comment]
@paulkaplan Can't repro anymore, seems like it's working as expected now!
