### ISSUE TITLE
change default values for > < and = Operator blocks to 50

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-gui#2507]
The current default values for > < = are currently 100.

In testing it, we realized the value of 50 would be better since some sensors don't go above 100.

**Comment by paulkaplan** [comment]
@thisandagain if we want to do this we should make sure it is scheduled for before the end of july

**Comment by thisandagain** [comment]
@paulkaplan Yeah. This is a last minute change. I'll try to get to it on Monday at the latest.
