### ISSUE TITLE
Text space too short (or trnaslation too long)

### ISSUE THREAD

**Issue by Smrman** [LLK/scratch-gui#2518]
Hi,
When the editor is set to French, in some places, the translation is not fully displayed because text is too long or there is not enough space for it...

I've done some screenshot to shot it.
![scratch3bug1png](https://user-images.githubusercontent.com/17651422/42066015-a9749440-7b3e-11e8-83c1-ebb8984e6196.PNG)

![scratch3bug2png](https://user-images.githubusercontent.com/17651422/42066016-a98f1b58-7b3e-11e8-8501-0ff3d87611b2.PNG)

"Mouvemen..." is missing it's "ts" at the end.
Same for "Evenement" where the "s" is not visble.

Some other blocs are also not fully visble like "glisser en () secondes à [position aléatoire]".

It's not a big deal be it could become one with some languages that have very long strings, I know German has some long words sometimes...

Please consider adding a way to make these navbars wider (maybe with a slider?).

Oh, and by the way, some blocks also have a small problem of margin. (see below)
![scratch3bug3png](https://user-images.githubusercontent.com/17651422/42066183-97c42f70-7b3f-11e8-9626-450899d2180b.PNG)

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/1613
