### ISSUE TITLE
Broadcast and wait blocks are not working in 3.0

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#2529]
### Expected Behavior

1. Open 2.0 project in 3.0
2. Run project 
3. Follow the conversation through "broadcast and wait" blocks
https://scratch.mit.edu/projects/94328306/#editor

### Actual Behavior

Notice that the "wait" in "broadcast and wait" doesn't execute correctly. 
https://preview.scratch.mit.edu/#94328306

### Steps to Reproduce

1. Open 2.0 project in 3.0
2. Run project 
3. Notice that the "wait" in "broadcast and wait" doesn't execute correctly. 
4. https://preview.scratch.mit.edu/#94328306

### Operating System and Browser

mac OS High Sierra - Chrome 67

**Comment by techwonder21** [comment]
@ChampikaF

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/2461
Fix in https://github.com/LLK/scratch-vm/pull/1305

**Comment by techwonder21** [comment]
Related bug: https://github.com/LLK/scratch-gui/issues/2685
@ChampikaF
