### ISSUE TITLE
Language selector broken in Firefox

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2538]
### Expected Behavior

_Please describe what should happen_
The language should switch after selecting a different language in the language menu.

### Actual Behavior

_Describe what actually happens_
The language doesn't change

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Try to change language in Firefox.

### Operating System and Browser

_Mac OS 10.13.5 firefox 61.0 (64-bit)_

**Comment by apple502j** [comment]
Can repro on Windows7 HomePremium 64bit SP1 Firefox 61
