### ISSUE TITLE
When active scripting area changes if you drag a sprite in the stage in 2.0 vs. 3.0

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#254]
### Expected Behavior

In 2.0, the scripting area changes from one sprite to another when you let go of the sprite you are dragging across the stage.

### Actual Behavior

In 3.0, the scripting area changes from one sprite to another when you initially click the sprite you are dragging. I'm not sure which is preferable/ if this change was intentional.

### Steps to Reproduce

- In 2.0, add 2 sprites to a project
- Put a block in one of the scripting areas
- Click on sprite A in the sprite pane
- Note sprite A's scripting area should be visible
- Click on sprite B to drag it across the stage
- Note the switch from scripting area A to B happens after you let go of sprite B
- In 3.0, do the same thing
- Note the switch from scripting area A to B happens as soon as you grab sprite B

### Operating System and Browser

_Mac, Chrome_

**Comment by tmickel** [comment]
One sorta-technical reason to do it after dropping/letting go is that loading the blocks for the sprite takes some CPU time; on my computer, starting the drag right now has a little "jolt" while the blocks load. If the blocks loaded after dragging, the jolt wouldn't happen until after the interaction is over.

**Comment by navignaw** [comment]
This is an interesting issue that also spans [scratch-vm](https://github.com/LLK/scratch-vm/).

The offending line is [`setEditingTarget`](https://github.com/LLK/scratch-vm/blob/develop/src/virtual-machine.js#L419) in `VM.startDrag`, which sets the editingTarget to the currently dragged sprite. Unfortunately it's not an easy fix-- we can't simply move the call to `stopDrag` as this causes the old sprite to be visually dragged instead. It looks like editingTarget is used for both the selected [SpriteSelectorComponent](https://github.com/LLK/scratch-gui/blob/develop/src/components/target-pane/target-pane.jsx#L68) and the visual dragging code, so we'd have to decouple them somehow.
