### ISSUE TITLE
Language selector menu appears behind script/costume/sounds tabs

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-gui#2543]
### Expected Behavior

The language selector menu should appear and be accessible.

### Actual Behavior

The menu disappears behind the script/costume/sounds tabs and is inactive:
![image](https://user-images.githubusercontent.com/28599280/42203708-3a496ad6-7ed2-11e8-9890-86cf69f78de8.png)

### Steps to Reproduce

1. Open https://llk.github.io/scratch-gui/develop
2. Click the globe icon

### Operating System and Browser

Chrome 67.0.3396.99 Windows 10.0.17134.112

**Comment by apple502j** [comment]
#2446
(Is dupe of closed issue still so?

**Comment by Kenny2github** [comment]
Oh, yes - it works when `?enable=language` is set.
