### ISSUE TITLE
Example inputs(like apple in join(apple)(banana)) aren't change while switching language

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#2544]
### Expected Behavior

They change to the correct language

### Actual Behavior

They NEVER
![screenshot_2018-07-03-17-54-52-687_com android chrome](https://user-images.githubusercontent.com/31377746/42213489-7935a0e8-7eeb-11e8-896e-df0a97d1f4a7.png)
![screenshot_2018-07-03-17-55-11-297_com android chrome](https://user-images.githubusercontent.com/31377746/42213663-fe322f14-7eeb-11e8-926c-d2d91c7c2834.png)
![screenshot_2018-07-03-17-55-30-089_com android chrome](https://user-images.githubusercontent.com/31377746/42213665-fe98fde8-7eeb-11e8-83bb-4878d7f82cec.png)

### Steps to Reproduce

Switching between languages

### Operating System and Browser

Android Chrome(I guess all?)

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/2070
