### ISSUE TITLE
Stagesize is not working properly

### ISSUE THREAD

**Issue by DivyeshPuri** [LLK/scratch-gui#2553]
### Expected Behavior

Whenever I click on the full-screen the button the stage size should increase and when I exit it should reset to its actual size.
### Actual Behavior

Whenever I click on the full-screen button the screen opens correctly but when closed the stage size increases and it continuous to show this behavior.

### Steps to Reproduce

There is something wrong with setting the size namely STAGE_DISPLAY_SIZES. I don't know exactly what is creating this bug.
### Operating System and Browser

Windows 10

**Comment by paulkaplan** [comment]
Can you make sure you are using the most recent `develop` branch, there was a bug similar to this that was fixed last week. Can you reproduce here? https://llk.github.io/scratch-gui/develop/

Additionally, screenshots would help quite a bit.

**Comment by DivyeshPuri** [comment]
Can you tell me which commit solved this issue? I made a few changes in my local repository and it didn't appear to work. I am using the latest developer branch.
When Scratch starts locally.
![screenshot 53](https://user-images.githubusercontent.com/23422478/42407748-fc78937a-81de-11e8-886d-99bb6011bda6.png)
When I click on the Fullscreen button.
![screenshot 54](https://user-images.githubusercontent.com/23422478/42407752-0a706f3e-81df-11e8-964d-acc5391faa54.png)
When I unFullScreen it.
![screenshot 55](https://user-images.githubusercontent.com/23422478/42407763-2a560872-81df-11e8-8d31-52fa756ff87e.png)
It continues to happen and the image continues to increase the size if I repeat the process.

**Comment by DivyeshPuri** [comment]
@paulkaplan  Got solved. Thanks
