### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#2558]
Please check the official suggestion and bug reporting forum for some useful suggestions. All of my ideas can be found by searching "amazingmech2418 site:https://scratch.mit.edu/discuss/topic/299791/" on google and doing a ctrl+f search for "amazingmech2418" on one of the result links. I've also found quite a lot of other useful suggestions for Scratch 3.0 there. Please check them out.

**Comment by towerofnix** [comment]
I'm guessing they'll probably start paying significant attention to feature suggestions past the initial release. Right now they're focusing on important features that definitely need to be added before the initial release. (For example, these last couple days there's been been lots of work on local variables.)

You'll notice that [all the feature suggestions are backlogged](https://github.com/LLK/scratch-gui/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Afeature+label%3Arequest). Which doesn't mean they're being ignored, or that they're never going to be looked at; just that the ST is prioritizing other things before release.

**Comment by amazinigmech2418** [comment]
@towerofnix There are also a lot of bugs reported there.

**Comment by thisandagain** [comment]
We monitor that forum quite closely and move individual suggestions into Github as warranted. As @towerofnix points out, we will focus on feature additions after the initial release. Right now we are focused on getting Scratch 3.0 to have feature parity with 2.0.
