### ISSUE TITLE
Convert to bitmap/vector in paint editor looks disabled

### ISSUE THREAD

**Issue by ChampikaF** [LLK/scratch-gui#2589]
### Expected Behavior

Expected a brighter blue button indicating it's clickable

### Actual Behavior

![image](https://user-images.githubusercontent.com/2895591/42591744-9b9a4fc8-8515-11e8-8056-de24a93e3e79.png)

### Steps to Reproduce

preview.scratch.mit.edu -> Costumes

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by kyleplo** [comment]
For some reason, it gets `.75` opacity when not active.

**Comment by thisandagain** [comment]
@paulkaplan This should be a quick fix. Do you mind taking this?

**Comment by paulkaplan** [comment]
👍
