### ISSUE TITLE
Tutorial Window: Change "remove" to "hide" or "close"

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#2594]
### Expected Behavior

The close button should be labeled "hide" or "close".

### Actual Behavior

It is labeled "remove," which implies you are deleting something.

### Steps to Reproduce
Look at the close button on how-tos.

### Operating System and Browser

All

**Comment by ntlrsk** [comment]
I agree with this recommendation to change the Tutorials window wording "Remove" to "Close".
