### ISSUE TITLE
Duplicating sprites makes the sounds tab not work

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#2629]
### Expected Behavior

_Please describe what should happen_

Duplicating a sprite should allow you to edit the sounds separately.

### Actual Behavior

_Describe what actually happens_

After duplicating a sprite, the sounds tab does not render, it shows "Oops"

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Right click a sprite, hit "Duplicate"
2. Switch to the sounds tab
3. See "Oops" screen and this in the console:
```
scratch-audioengine SoundBank.getSoundPlayer(rNKiPwqV[xJuS4:k_%QR): called missing sound in bank
TypeError: Cannot read property 'buffer' of undefined
```

**Comment by ericrosenbaum** [comment]
cc @gnarf @mzgoddard
