### ISSUE TITLE
Outfielder has a circle on his face

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#2635]
### Expected Behavior
No strange circle

### Actual Behavior
WHAT IS THIS?
![](https://screenshotscdn.firefoxusercontent.com/images/079c4fda-481e-428b-a497-e232cbddd169.png)

### Steps to Reproduce
1. Load outfielder sprite

### Operating System and Browser
Windows 7 HomePremium SP1 64bit Firefox 61.0.1

**Comment by fsih** [comment]
https://twitter.com/MLBastian/status/766110086083207168/photo/1

**Comment by apple502j** [comment]
@fsih Is it needed?

**Comment by kosiecki17** [comment]
This character has a face underneath the bubble. While it doesn't have a mouth, for the most part it works without the bubble, so kids can delete it.

**Comment by thisandagain** [comment]
It's bubble gum. :-O
