### ISSUE TITLE
Device scan can display devices of the wrong type

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#2636]
### Expected Behavior

When you start a device scan for an extension, it should show list only devices for that extension. 

### Actual Behavior

Sometimes the device scan lists devices of the wrong type. Here it's showing a microbit during an EV3 scan:

<img width="512" alt="screen shot 2018-07-15 at 12 08 14 pm" src="https://user-images.githubusercontent.com/567844/42735765-bf58b192-8827-11e8-9369-6115d38473a5.png">

### Steps to Reproduce

- Turn on a microbit
- Add the microbit extension, and wait until your microbit shows up in the device list
- Close the connection modal
- Add the EV3 extension
- When it starts scanning, the microbit will show up in the list

**Comment by thisandagain** [comment]
Resolved via LLK/scratch-vm#1354

**Comment by ericrosenbaum** [comment]
@thisandagain I'm re-opening. LLK/scratch-vm#1354 did not actually address this issue. @evhan55 was not able to reproduce the issue, but the steps above were reliable for me.

**Comment by cwillisf** [comment]
I added a bit of debug output to my local copy of Scratch Link and I think I see what's going on. Here's my (slightly cleaned up) output:
```
Creating new session with ID 1
Session 1: Discovered 216196281278531
Session 1: Discovered 216196281278531
Session 1: Discovered 216196281278531
Session 1: Discovered 216196281278531
Creating new session with ID 2
Session 1: Discovered 216196281278531
Session 2: Connect 216196281278531
Exception thrown: 'scratch_link.JsonRpcException' in ScratchLink.exe
Invalid Params
```

It looks to me like the extension or related framework is seeing the `didDiscoverPeripheral` from the first session (micro:bit) and interpreting it as if it applies to the second session (not micro:bit).

I suggest two changes:
- If you close the device connection modal without establishing a connection, close the WebSocket, AND
- Make sure that a `didDiscoverPeripheral` message on one socket doesn't get handled by / on behalf of an extension which is associated with another socket.

I believe both of those changes are necessary to get correct behavior.

**Comment by evhan55** [comment]
Thank you so much for the recon, @cwillisf !

**Comment by ericrosenbaum** [comment]
I'm re-opening this because we are seeing the issue again, using the original repro steps.

**Comment by evhan55** [comment]
I'll assign to myself unless someone else wants to take it

**Comment by evhan55** [comment]
@ericrosenbaum Do you remember which OS you were on when you saw this issue again most recently?

I am seeing it on Windows 1803 but not on Mac Mojave, and wanted to see what OS was doing it for you, thanks.

**Comment by thisandagain** [comment]
@evhan55 Eric and I were both able to reproduce on MacOS (I'm on 10.14.2).

**Comment by evhan55** [comment]
@thisandagain okay, thanks!
