### ISSUE TITLE
Toolbar too wide for ipad, cuts off username

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2641]
### Expected Behavior

The toolbar should contain the username and not scroll

### Actual Behavior

The username is too far to the right and wraps to a new line.  It also overlaps the edge of the screen making it not all visible.  This causes the whole screen to be scrollable to the right.

<img width="1024" alt="ipadnamecutoff" src="https://user-images.githubusercontent.com/1088291/42768271-106932d0-88ed-11e8-821c-fdd86f0a7290.png">
<img width="1024" alt="ipadcanscrollhorizontally" src="https://user-images.githubusercontent.com/1088291/42768279-14330b3e-88ed-11e8-8dac-49706477ede2.png">

### Steps to Reproduce

Launch the editor
Look at the upper right of the screen
Scroll to the right

### Operating System and Browser

IOS 11.0.3 Safari

**Comment by kyleplo** [comment]
Steps of hiding when screen is too small.
1. Hide icon on "See community" and "Tutorials"
2. Shrink project title field
3. Hide user profile picture
4. Show icon on "See community" and "Tutorials" and hide text
5. Show user profile picture and hide username
6. Change Scratch logo to Scratch S

![image](http://kyleplo.com/media/pictures/all-steps.gif)

**Comment by Kenny2github** [comment]
Perhaps the first best step is to allow the project title field's size to be flexible? i.e. make the "share", "see community", "my stuff", and username fields float to the right, the "Scratch", language, "file", "edit", "tutorials", and project title fields to float to the left, and unfix the project title field's length.

**Comment by tomrow** [comment]
Perhaps the project title could be changed through a Save As option in the File drop-down. Also the folder icon could be moved to the user drop-down.

**Comment by LiFaytheGoblin** [comment]
We decided on making the project title field flexible in it's width

**Comment by LiFaytheGoblin** [comment]
My fix will work down to a width of 980px which is sufficient for the iPad. For smaller screens we would need to think about sth other than shrinking the title field because I think it should still show a bit of the title.
<img width="988" alt="screen shot 2018-09-11 at 12 40 45 pm" src="https://user-images.githubusercontent.com/5471273/45374390-f5156080-b5bf-11e8-9c43-1ea6c4635aeb.png">

**Comment by kyleplo** [comment]
@LiFaytheGoblin We won't have to worry about the "Give Feedback" button because the final version probably won't have it.
