### ISSUE TITLE
Deleting Sprite/costume/sound causes browser tabs to appear permenantly

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2644]
### Expected Behavior

After confirming the deletion of a sprite/costume/sound the window should return to the same state it was in where you can't see the tabs/url bar.

### Actual Behavior

After confirming that you've deleted a sprite, costume, or sound the tabs and url bar appear at the top of the screen and won't go away until you reload the page.  This causes the New Sprite and New Backdrop buttons to be covered by the bottom of the screen.
![androiddeletebug1](https://user-images.githubusercontent.com/1088291/42777518-56583848-8908-11e8-8ff7-d028c15207f4.png)
![androiddeletebug2](https://user-images.githubusercontent.com/1088291/42777522-5989a2a4-8908-11e8-80ca-96e309aff74a.png)
![androiddeletebug3](https://user-images.githubusercontent.com/1088291/42777527-5c20ef18-8908-11e8-8a22-97c4a8a3bbc1.png)

### Steps to Reproduce

Start a new project 
Press the x on the cat sprite in the sprite list
Confirm the deletion of the sprite
Note: the tabs and url bar appear at the top of the page
You could get the same results by deleting a costume or a sound from the cat.

### Operating System and Browser

Chrome on Android

**Comment by Kenny2github** [comment]
I get the feeling that if the GUI didn't use builtin JavaScript prompts for this kind of thing then the tabs wouldn't appear. A modal would look and function better than the default JS dialog box.

**Comment by paulkaplan** [comment]
Confirm here no longer exists
