### ISSUE TITLE
Safari device connection modal device list displays incorrectly 

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#2652]
The device tile is rendering incorrectly, in such a way that the "connect" button is invisible.

The tile background is also the wrong size, without rounded corners, and the RSSI indicator is hidden too.

<img width="515" alt="screen shot 2018-07-17 at 1 39 54 pm" src="https://user-images.githubusercontent.com/567844/42836100-32b52958-89c8-11e8-8fae-6388825cb90f.png">

Safari 11.0.2 Mac OS 10.13.2

**Comment by thisandagain** [comment]
@paulkaplan Could you help @ericrosenbaum with this one?
