### ISSUE TITLE
Safari doesn't render transparent gradients well

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2654]
### Expected Behavior

_Please describe what should happen_
This project https://preview.scratch.mit.edu/#222183421 should look like:
![screen shot 2018-07-17 at 5 57 00 pm](https://user-images.githubusercontent.com/399209/42847701-de080e02-89ea-11e8-80e2-ae71eca72e9f.png)

### Actual Behavior

_Describe what actually happens_
On Safari:
![screen shot 2018-07-17 at 5 55 30 pm](https://user-images.githubusercontent.com/399209/42847682-be3f6a2a-89ea-11e8-8631-662b99c7f2e3.png)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
View  https://preview.scratch.mit.edu/#222183421

### Operating System and Browser

_e.g. Mac OS 10.13.5 Safari 11.1.1_

**Comment by thisandagain** [comment]
Moved to LLK/scratch-render#315
