### ISSUE TITLE
Toolbox placeholder values are being recycled when language switches

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2656]
### Expected Behavior

_Please describe what should happen_
When the language switches all the default text values (e.g. "Hello", "Hmm...") should switch to the new language in the toolbox. In the workspace it's assumed that they've set the value.

### Actual Behavior

_Describe what actually happens_
The default value is one language behind.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Start in English, switch to French - the say block will still say 'hello'
Switch to Chinese - the say block will say 'bonjour'

### Operating System and Browser

_e.g. Mac OS  Safari and Chrome_

**Comment by chrisgarrity** [comment]
There have been several PRs that fix things related to updating the toolbox area. One of them appears to have fixed this issue. I can't reproduce it any more. It would be good for that to be verified.

**Comment by paulkaplan** [comment]
@chrisgarrity @BryceLTaylor i can still repro this on develop

**Comment by BryceLTaylor** [comment]
This appears to be fixed on develop and preview.
