### ISSUE TITLE
Replace language select with scrolling menu

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2658]
### Expected Behavior

_Please describe what should happen_
Clicking the language selector should show a menu/list of languages for the user to select from. It should scroll to show all the languages.

### Actual Behavior

_Describe what actually happens_
The language selector opens a menu that contains an HTML select box that contains the list of languages.

**Comment by kyleplo** [comment]
See https://kyleplo.github.io/c/demos/language-select

**Comment by chrisgarrity** [comment]
@kyleplo, could you submit a PR for that change. In the long run, it would be nice to have a fancy styled scrolling menu, but simply opening the select instead of having to open two menus would be an improvement.

**Comment by kyleplo** [comment]
@chrisgarrity I'll try, but it looks to me like it is a lot harder than it sounds. I'm worried that relative positioning will change in different browsers, and `<label>` doesn't do what we want. I'll give it a try.

**Comment by kyleplo** [comment]
@chrisgarrity Actually, I think I found a way to extend the `menu` component to make a scrolling menu.
