### ISSUE TITLE
Backdrops tab is titled "Costumes" when Stage is selected

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#267]
### Expected Behavior

The tab between "Scripts" and "Sounds" is titled "Backdrops" when the Stage is selected, as in Scratch 2.0.

### Actual Behavior

The tab is titled "Costumes", irregardless of whether a sprite or the stage is selected.

### Steps to Reproduce

Select the stage in the sprite/stage browser.

### Operating System and Browser

Chrome 57.0.2987.110 on macOS 10.12.

**Comment by thisandagain** [comment]
Good catch! Thanks for documenting @liam4

**Comment by towerofnix** [comment]
This doesn't look to have a patch? PR #376 (which was the patch to this previously) is now closed.
