### ISSUE TITLE
The delete icon of a costume tile displays on top of the open color picker menu

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#2672]
### Expected Behavior

Open menus should be on top of parts of other parts of the UI that don't change.

### Actual Behavior

The delete icon on a costume tile displays on top of the color picker menu if the two elements overlap.

![image](https://user-images.githubusercontent.com/1786240/42903104-b99b5722-8a9e-11e8-82f7-260318491b05.png)

**Comment by kyleplo** [comment]
Duplicate of #2394

**Comment by kchadha** [comment]
Tracking in #2394.
