### ISSUE TITLE
Yellow outline around code blocks not showing for "when I receive" blocks

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#2685]
### Expected Behavior
The yellow outline should appear around both the "broadcast and wait" blocks and the "when I receive" block stacks as well.
https://scratch.mit.edu/projects/94328306/#editor

### Actual Behavior
The yellow outline only appears for the "broadcast and wait" blocks
https://preview.scratch.mit.edu/#94328306

### Steps to Reproduce
Open the project below and notice the missing yellow outline
https://preview.scratch.mit.edu/#94328306

### Operating System and Browser
macOS High Sierra 
Chrome 67

**Comment by techwonder21** [comment]
Feel free to reference this bug:
https://github.com/LLK/scratch-gui/issues/2529
@ChampikaF

**Comment by techwonder21** [comment]
Is there an estimated timeline on when this bug will be fixed within the Backlog?

**Comment by thisandagain** [comment]
Thanks @techwonder21. I'm adding this to the September milestone to understand what is going wrong here and hopefully get out a fix.

**Comment by techwonder21** [comment]
New bug that is probably related:
https://github.com/LLK/scratch-gui/issues/2967
