### ISSUE TITLE
I want to build a standalone sb3 player.

### ISSUE THREAD

**Issue by wufeng87** [LLK/scratch-gui#2687]
Since I found this project could export sb3 file and load sb3 file and play it in the web browser, I want to know if I could serve sb3 file on my own website? 
If I could, then I need to dig into the source code.
Sorry to post here, since I could not post on https://scratch.mit.edu/discuss.
Best regards.

**Comment by kyleplo** [comment]
Try `https://llk.github.io/scratch-gui/develop/player#PROJECT-ID`

**Comment by wufeng87** [comment]
Where could I get the #PROJECT-ID? Not found any docs about this branch(gh-pages)~ How could I build the player.html and player.js ... I need to learn more~~ Thanks.

**Comment by wufeng87** [comment]
wow. I found the player.html is in the build directory. : )

**Comment by kyleplo** [comment]
I don't know much about it either, but project ids come from the Scratch website. The id is the number in the URL. For example, in _scratch.mit.edu/projects/**236165720**/_,  **236165720** is the id.

**Comment by kyleplo** [comment]
Also, currently loading projects by project id is broken, according to #2580. For now, use `https://rschamp.github.io/scratch-gui/bugfix/player-loader/player.html#PROJECT-ID`

**Comment by wufeng87** [comment]
@kyleplo Wow. project 236165720 is a 2.0 project, and we could load 2.0 project in scratch 3.0, you did the 2 to 3 transformation in the backend, am I right?

**Comment by towerofnix** [comment]
@wufeng87 2.0 to 3.0 conversion is done automatically by the Scratch 3.0 editor (really the VM), so most 2.0 projects should work in 3.0 without any extra effort from the project creator.
