### ISSUE TITLE
The stage can talk!

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#2688]
### Expected Behavior

When you share to love a say block to the stage, it doesn't work.

### Actual Behavior

When you share to love a say block to the stage, it works! A speech bubble appears in the middle of the stage.

### Steps to Reproduce

Using share the love, move a say block to the stage and run it.

### Operating System and Browser

Windows 10 Chrome 67.0.3396.99

**Comment by thisandagain** [comment]
It's a little unclear if this is a bug. I think we are going to keep this for now.
