### ISSUE TITLE
Should upload tooltip be consistent for sprite, costume and backdrop?

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2690]
Question that came in via translator:
The tool tips for uploading a costume or backdrop are "Upload costume" and "Upload backdrop", but the tool tip to upload a sprite is just "Upload". 

Should it be "Upload Sprite" for consistency?

**Comment by Kenny2github** [comment]
Yes.

**Comment by thisandagain** [comment]
Agreed. We should probably change this to be "Upload Sprite".
