### ISSUE TITLE
Cannot edit blocks that require the "full" soft keyboard on Android Chrome

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#2692]
### Expected Behavior
- Clicking on any block should open either the numeric or "full" soft keyboard on Android Chrome

### Actual Behavior
- Blocks which require the "full" soft keyboard, briefly display the keyboard and then immediately dismiss it

### Steps to Reproduce
- Click on the value input on the "set [variable] to (value)" block

### Operating System and Browser
Android 6 | Chrome Latest

**Comment by picklesrus** [comment]
This is probably the same as https://github.com/LLK/scratch-blocks/issues/1345, but I'm not 100% which repo it belongs in and it is pretty critical sure so keeping both for now.

**Comment by picklesrus** [comment]
This should be fixed!
