### ISSUE TITLE
Want to make Video sensing blocks as default blocks

### ISSUE THREAD

**Issue by DivyeshPuri** [LLK/scratch-gui#2695]
### Expected Behavior

Since I am using video sensing blocks I want to make that block in my default blocks coming when Scratch starts, It will save me the trouble of going over video sensing extension again and again.

### Actual Behavior

I can't find a way to make it in default block.

**Comment by thisandagain** [comment]
You'll want to look at the way blocks vs. extensions are initialized in the Scratch Virtual Machine:
https://github.com/LLK/scratch-vm
