### ISSUE TITLE
Delete confirmation pop up is not translatable

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2697]
### Expected Behavior

_Please describe what should happen_
When you delete a sprite the pop-up asking for confirmation should be translated into the scratchers language.

### Actual Behavior

_Describe what actually happens_
The alert is always in English - it's not wrapped in a localization call.
https://github.com/LLK/scratch-gui/blob/89dc5c0781100091650966babf5364ff07c63e9b/src/containers/sprite-selector-item.jsx#L80

**Comment by paulkaplan** [comment]
If anyone wants to implement this, it requires a few things. You can use a component like the `playback-step.jsx` for reference
1. Import the formatMessage, injectIntl, intlShape, defineMessages from react-intl [example](https://github.com/LLK/scratch-gui/blob/develop/src/components/record-modal/playback-step.jsx#L7)
2. define the message using defineMessage [example](https://github.com/LLK/scratch-gui/blob/develop/src/components/record-modal/playback-step.jsx#L14-L19)
3. Use this.props.formatMessage inside the alert to translate the message [example](https://github.com/LLK/scratch-gui/blob/develop/src/components/record-modal/playback-step.jsx#L81)
4. Declare the intl shape in the proptypes [example](https://github.com/LLK/scratch-gui/blob/develop/src/components/record-modal/playback-step.jsx#L115)
5. Wrap the component in `injectIntl` before exporting [example](https://github.com/LLK/scratch-gui/blob/develop/src/components/record-modal/playback-step.jsx#L129)

**Comment by apple502j** [comment]
Working on it, but export default is only allowed once...

**Comment by paulkaplan** [comment]
You can change the bottom of the file to something like
```

export default connect(
    mapStateToProps,
    mapDispatchToProps
)(injectIntl(SpriteSelectorItem));
```

**Comment by apple502j** [comment]
@paulkaplan thanks!
