### ISSUE TITLE
Deleted costume is not deleted from the stage.

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2698]
### Expected Behavior

_Please describe what should happen_
Reported by a translator: If a costume is deleted from a sprite while that costume is visible on the stage, the stage should update to the next existing costume.

### Actual Behavior

_Describe what actually happens_
Here are the images sent by the translator. Sprite1 has two costumes - the first one has been modified. It also looks like the mosaic effect has been applied. In the paint editor he deleted the first modified costume. The costume is deleted, but the stage still shows the mosaic with the modified costume.

![delete-s](https://user-images.githubusercontent.com/399209/43076188-6515c5fa-8e51-11e8-99c4-b3c5ab20af9d.png)
![render](https://user-images.githubusercontent.com/399209/43076199-6a85a1d6-8e51-11e8-98cf-bfc3e000f76a.png)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
I wasn't able to repro on the latest version, but maybe someone else can.

**Comment by BryceLTaylor** [comment]
I can not reproduce this at all on Chrome (Mac & Windows), Firefox (Mac & Windows), Safari (Mac), or Edge (Windows).

Steps to NOT reproduce:
Create a new project
Change language to Dutch
Add a `Set Mosaic Effect` block to the workspace enter 10 into the text field
Run the block
Open the costume tab
Add some circles to the first cat costume
Delete the first cat costume
Note: The stage updates correctly to the second (unmodified) cat costume with the mosaic effect

I think we should close this and look out for others reporting this behavior.
