### ISSUE TITLE
Using sound editor makes the screen move a bit

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#2709]
### Expected Behavior
The position won't change.

### Actual Behavior
![](https://i.gyazo.com/b0a0a4141daea48d5c72884020c4ed8f.gif)
It moves a bit.

### Steps to Reproduce

1. Open sound editor
2. Play a sound
### Operating System and Browser
Windows 7 HomePremium 64bit SP1
Firefox 61.0.1

**Comment by towerofnix** [comment]
I think this is the same issue as #2069. Probably best to keep this one open but anybody who wants to have a go at this can read that one for some extra info:

>The sidebar grows a little bit (a few pixels) after various actions - pausing, playing, and enabling the trimmer all adjust the size.
>
>Note that it doesn't continue to grow -- that is, it only grows once or twice, until it seems to reach some "target width".
>
>This almost certainly has something to do with how CSS flex is used. A dumb workaround would be to just set a target width in pixel units; otherwise, I imagine that the issue is actually the sound editor waveform element changing in size for some reason.
