### ISSUE TITLE
Remove "-b" from Odesong-b

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#2710]
### Expected Behavior
"-b" should be used when 2 have the same name
### Actual Behavior
Odesong-a doesn't exist

### Steps to Reproduce
1. open sound library
2. search for "odesong"

### Operating System and Browser
any (me:Windows 7 HomePremium 64bit SP1 Firefox 61.0.1)

**Comment by towerofnix** [comment]
Note odesong-a, alongside odesong-c, was used in [Ode to Code - Make Your Own Dance](https://scratch.mit.edu/projects/76322168/), but doesn't exist in the sound library (in either 2.0 or 3.0).
