### ISSUE TITLE
Scratch 3.0 not having sound support for webkit 2.20.3 Linux

### ISSUE THREAD

**Issue by samswag** [LLK/scratch-gui#2711]
Usually the Scratch 3.0 prompt the user for permission to accept audio playback or audio recording using Chrome, Firefox and even a webkit based browsers like Safari. I was doing some testing, as I am currently working on a Linux (Sugar Desktop) version of the Scratch v3. I ran into some audio problems while working on the Sugar Desktop [Browse](https://github.com/sugarlabs/browse-activity) and also since I am developing using Fedora 28, I had same issue with [Gnome Web](https://wiki.gnome.org/Apps/Web).

Latest version of [Webkit](https://apps.fedoraproject.org/packages/webkit2gtk3/overview) for Fedora which I currently have on my system.
<img width="1280" alt="screen shot 2018-07-24 at 3 56 37 am" src="https://user-images.githubusercontent.com/6048601/43115182-a5301eb6-8efa-11e8-89a6-9daf23b43d84.png">

<img width="1280" alt="screen shot 2018-07-24 at 3 53 28 am" src="https://user-images.githubusercontent.com/6048601/43114900-21b08f90-8ef9-11e8-99f3-1d206794151a.png">

**Comment by tomrow** [comment]
Please use a supported browser such as Chrome or Firefox

**Comment by samswag** [comment]
Yes, I can easily do that. But, i am trying to build a linux(Sugar OS) version of the Scratch 3.0 by embedding the source code of the Scratch with an open source browsers as those mentioned above. As least the most realistic and easiest way to do it, is by making the Scratch 3.0 to support those native browsers. I guess, the goal of the Scratch community with the 3.0 is to make Scratch far more accessible compare to previous generations. 

So I will like to get a pointer, on how at least I could get permissions off from the unsupported browsers or look for a way to solve it.

**Comment by paulkaplan** [comment]
Does webkitgtk support getUserMedia and webAudio? If not, I don't think we can help.
