### ISSUE TITLE
Sound and costume "menus" are not as wide as the toolbox (250px)

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-gui#272]
### Expected Behavior

_They are_

### Actual Behavior

_They are not_

### Steps to Reproduce

_Look at the difference in width_

**Comment by TheBrokenRail** [comment]
The code that causes this is right here:
https://github.com/LLK/scratch-gui/blob/develop/src/components/asset-panel/selector.css#L5

**Comment by thisandagain** [comment]
These tabs are rough WIP. We'll open up new issues as work progresses.
