### ISSUE TITLE
Speech bubble can show cut off

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#2721]
@kchadha, @fsih and I have all seen instances where a "say" bubble can be cut off. I saw it in the test "all the blocks" project, but haven't been able to repro it. Does anyone know how to reproduce this consistently?

**Comment by thisandagain** [comment]
@BryceLTaylor Do mind attempting to create a repro for this?

**Comment by BryceLTaylor** [comment]
Yes, I reproduced it on Safari.

![screen shot 2018-07-31 at 4 25 09 pm](https://user-images.githubusercontent.com/1088291/43485270-c338106e-94de-11e8-9cf4-275b03c5fbf4.png)

Repro steps:
Load this project: https://llk.github.io/scratch-gui/develop/#228228816
Click the green flag
Let it play through until it tries to say the costume number
Note: the speech bubble is cut off

**Comment by BryceLTaylor** [comment]
Here is the relevant part of the code:
![screen shot 2018-07-31 at 4 29 48 pm](https://user-images.githubusercontent.com/1088291/43485371-09f5276c-94df-11e8-8b02-75e2db62037d.png)

**Comment by BryceLTaylor** [comment]
I also just reproduced it on Firefox, where it's even weirder.  The first time I ran it it didn't say the costume number at all.  When i ran it again it DID say it but it was cut off.

First time run:
![alltheblocksfirefox3](https://user-images.githubusercontent.com/1088291/43485998-b8dad262-94e0-11e8-91b5-0e2a8380dbd5.gif)
Second time run:
![alltheblocksfirefox2](https://user-images.githubusercontent.com/1088291/43486021-c0ffb5c0-94e0-11e8-99e9-f65dc3bc0def.gif)

If you reload the page it behaves as if it's the first time.  (Note: the gif for the first time is actually the gif after reloading.)

**Comment by BryceLTaylor** [comment]
And actually, on Chrome it just NEVER says that say block:
![alltheblockschrome1](https://user-images.githubusercontent.com/1088291/43486324-8e5963b8-94e1-11e8-89fb-8ccf6651ba12.gif)

**Comment by paulkaplan** [comment]
@BryceLTaylor would it be possible to trim down the repro project to just the relevant blocks/sprites? It is pretty hard to tell what is going on based on that project.

**Comment by BryceLTaylor** [comment]
These blocks here are the culprit:
![screen shot 2018-08-01 at 1 38 13 pm](https://user-images.githubusercontent.com/1088291/43538491-32aa8358-9590-11e8-9c55-f738285cfef7.png)

Say (Costume Number) basically doesn't work on chrome.  If you run that the cat doesn't say anything.

**Comment by BryceLTaylor** [comment]
Hold on, it's working now.  Let me look into it.

**Comment by thisandagain** [comment]
@BryceLTaylor Any updates?

**Comment by fsih** [comment]
I found that it always does 1 of 2 things:
1. Goes from showing "Hmm..." straight to the cut off "costume number: 2". It's supposed to show "First backdrop!!!" in between. Sometimes you can see it say that for a split second in between.

I think the length of the cut off speech bubble matches the length the speech bubble should be when showing "First backdrop!!!", so I suspect it's getting the measurement for that and accidentally applying it to the other.
![](https://user-images.githubusercontent.com/1088291/44666672-e8511400-a9e6-11e8-84ea-bc96b95c1530.gif)

2. Shows "Hmm..." followed by "First backdrop!!!", then entirely skips "costume number: 2" to go to "costume name: costume2":
![](https://user-images.githubusercontent.com/1088291/44666696-f9018a00-a9e6-11e8-8d89-7e67379568a7.gif)

It never shows all of the speech bubbles correctly.

**Comment by BryceLTaylor** [comment]
I've made a simpler repro case in this project:
[say-cut-off-repro.sb3.zip](https://github.com/LLK/scratch-gui/files/2337698/say-cut-off-repro.sb3.zip)
You have to hit the space bar a few times and then you'll see it.  Often it has been four times.  It usually won't do it a second time.

I can't reproduce it every time.
