### ISSUE TITLE
Remove huge text-encoder dependency

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#2731]
The text-encoder dependency is nearly 600kb, but is used to encode only the default SVG assets for the default project. If we could have that encoding happen via a webpack plugin, we wouldn't have to load the text-encoder dependency.

![image](https://user-images.githubusercontent.com/654102/43222399-02705bee-901e-11e8-9f76-0963fa632f5f.png)

**Comment by paulkaplan** [comment]
Oh wait it is also used by VM and storage :(

**Comment by rschamp** [comment]
We need this for all our SVG assets I believe, I don't think there's a way around this. One of the benefits of building all the scratch-* dependencies together when we build the GUI is that they can all share the same `text-encoder` dependency, saving us ~1200kB.
