### ISSUE TITLE
ios 9 shows blue screen 

### ISSUE THREAD

**Issue by xiaomak** [LLK/scratch-gui#2742]
### Expected Behavior

ios 9 shows blue screen

### Actual Behavior

access https://preview.scratch.mit.edu is ok

![image](https://user-images.githubusercontent.com/1825679/43386432-2d0dac48-9416-11e8-8bf6-f40972ffb403.png)

but access https://preview.scratch.mit.edu/#1 ios 9 shows blue screen

![image](https://user-images.githubusercontent.com/1825679/43386336-ea16d0fe-9415-11e8-8b75-4b78c1bba00d.png)

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/1825679/43386336-ea16d0fe-9415-11e8-8b75-4b78c1bba00d.png)

### Operating System and Browser
ios 9.3 
simulator iphone 6s plus && iphone 6s

**Comment by kyleplo** [comment]
The blue screen is actually the "oops! something went wrong!" screen, just cut off.

**Comment by xiaomak** [comment]
@kyleplo How do I solve?

**Comment by paulkaplan** [comment]
iOS 9 is not fully supported, [the FAQ](https://scratch.mit.edu/3faq) says iOS/Safari 11+, this is because many needed features, such as WebAudio and access to webcam/microphone were not available in Safari 9.
