### ISSUE TITLE
Device disconnection alert modal

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#2747]
When a hardware device such as a microbit or EV3 becomes disconnected from Scratch (e.g. because it was turned off), we should notify the user. The blocks menu's status indicator changes states, but it may be invisible for many reasons. We'd like to have a "global" notification modal that pops over the UI.

**Comment by carljbowman** [comment]
@thisandagain - Happy to get started on this whenever. Def looking forward to circling back on this.

**Comment by benjiwheeler** [comment]
This is implemented: 

![image](https://user-images.githubusercontent.com/3431616/48749238-07f38380-ec48-11e8-86a7-64b34a224ea2.png)

We will also revisit this in: https://github.com/LLK/scratch-gui/issues/3837
