### ISSUE TITLE
Rotation Styles and Direction Dial Control

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#2748]
### Overview

We received a lot of feedback during ISTE and the Scratch Conference that folks would like to bring back an easy way to set rotation styles. Having to set the rotation style in a block feels too obscure. Powerful concepts like flipping a character in a story have now been made harder.

This felt like an opportunity to improve the UX and provide a more tinkerable means of understanding direction and rotation style. Our original reason for moving rotation styles to a block was because it's hidden state and does not appear to have an effect until rotation or direction is applied. 

### Tinkerable UI
![v1_rotation open](https://user-images.githubusercontent.com/3409578/43477473-43ff9b92-94c9-11e8-8906-2c21acc80b4d.png)
 
This UI allows the use of the direction dial to set the direction, but also toggle the rotation style. This way there is a tinkerable relationship between the two concepts.

The rotation style icons should act like the block and set the rotation style for the sprite.

**Comment by kyleplo** [comment]
What about a lock icon for "don't rotate"?

**Comment by carljbowman** [comment]
We discussed a lock icon. That was the original icon suggested for "don't rotate", but folks felt that that the lock implied that the rotation and _direction_ would become locked, instead of what is happening: rotation of the sprite becomes locked, but the sprite can still travel in any direction.
