### ISSUE TITLE
Builds on LLK branches (e.g. develop & master) take 25 minutes to run

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#2753]
Builds on develop/master take 25 minutes to run, but they only take about 7 minutes for PR branches, so something funky is going on. @rschamp it seems like it has be related to the branch pruning stuff?

**Comment by rschamp** [comment]
I cleaned out the `greenkeeper/` directory on the `gh-pages` branch to help this... the prune script still needs to be fixed though.
