### ISSUE TITLE
Paint editor should scale to fill available space

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#2754]
### Expected Behavior

The paint editor should fill up as much space as is available in the Costumes/Backdrops pane.

### Actual Behavior

It is fixed to being 480 pixels wide and 380 pixels tall unless you zoom in your browser.

### Steps to Reproduce

Open the paint editor (click the Costumes tab).

---

This is a very common feature request in the 3.0 beta forums, usually along the lines of "the paint editor is way too small".

(Sorry if this is a duplicate! I couldn't find one, but I somewhat remember seeing one before.)

**Comment by rschamp** [comment]
Moved to LLK/scratch-paint#601
