### ISSUE TITLE
Render windows is resized when I drag a block

### ISSUE THREAD

**Issue by marius851000** [LLK/scratch-gui#276]
### Expected Behavior

Render windows is resized when I drag a block

### Actual Behavior

A bar appear at the right side of the editor, that resize the render area, and also Sprite and Stage zone.

### Steps to Reproduce

1. drag a block to the script area

### Operating System and Browser

Chrome 56.0.2924.87 (official build) (32 bits)

**Comment by thisandagain** [comment]
I'm also seeing this. Thanks for reporting @marius851000 !

**Comment by thisandagain** [comment]
@rschamp Feel free to reassign.

**Comment by rschamp** [comment]
I'm not seeing this, does this still exist for you @thisandagain?

**Comment by thisandagain** [comment]
No. Looks like this has been resolved.
