### ISSUE TITLE
Can't open a comment when it contains many CJK characters

### ISSUE THREAD

**Issue by nekketsuuu** [LLK/scratch-gui#2766]
### Expected Behavior

I can open a comment when clicking the button on the left side of the comment.

### Actual Behavior

If a comment message contains some amount of CJK characters, the characters cover the open button. So I cannot open the comment.

![I can't open a comment whose message is "あいうえお" x 10.](https://user-images.githubusercontent.com/4374702/43584007-223e39bc-969c-11e8-9974-a2aa08c5554e.gif)

This bug does not happen when the message is long "abcdef...".

![I can open a comment whose message is many "abcdef"s.](https://user-images.githubusercontent.com/4374702/43584294-ff4a1c86-969c-11e8-85d7-20dabb84f8db.gif)

### Steps to Reproduce

1. Create a (block- or workspace-) comment.
2. Copy and paste many `あいうえお`.
3. Close the comment.
4. Try to open the comment.

### Operating System and Browser

Windows 10 Home, Google chrome 67.0.3396.99 (Official Build) (64 bit)
I tried on https://beta.scratch.mit.edu/ on Aug 2, 2018.

**Comment by apple502j** [comment]
Can repro on Windows 7 HomePremium SP1 64bit/Firefox 61.0.1 with the Japanese longest name `じゅげむ　じゅげむ　ごこうのすりきれ　かいじゃりすいぎょの　すいぎょうまつ　うんらいまつ　ふうらいまつ　くうねるところにすむところ　やぶらこうじのぶらこうじ　ぱいぽ　ぱいぽ　ぱいぽのしゅーりんがん　しゅーりんがんのぐーりんだい　ぐーりんだいのぽんぽこぴーの　ぽんぽこなーの　ちょうきゅうめいのちょうすけ`

**Comment by rschamp** [comment]
Moved to LLK/scratch-blocks#1680
