### ISSUE TITLE
Sprite selector doesn't render in target pane

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#278]
### Expected Behavior

_Please describe what should happen_
Should see the sprite selectors render
### Actual Behavior

_Describe what actually happens_
![image](https://cloud.githubusercontent.com/assets/654102/24362975/6c9fb76e-12dc-11e7-9f9e-835087c3a708.png)

---

This is because of a change to what the VM reports when we introduced `scratch-storage`. It used to report `skin` on the costume, which was a full URL, but now it doesn't.

**Comment by cwillisf** [comment]
Note that once we have a paint editor we'll need the GUI to handle the case where a costume has just been modified and the project hasn't been saved yet. In this situation the costume is only in memory so there's no URL, though we could make a data URI if necessary.
