### ISSUE TITLE
Costumes don't transfer correctly

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#2780]
### Expected Behavior

All costumes should look the same as in 2.0.

### Actual Behavior

Costumes end up stretching, growing in certain parts, and rounded squares become normal squares.

### Steps to Reproduce

Open any project with the marker font and/or rounded squares.

### Operating System and Browser

Windows 10 on Chrome

**Comment by kyleplo** [comment]
On what project(s)?

**Comment by thisandagain** [comment]
@amazingmech2418 A few sample cases / projects for repro would be very helpful.

**Comment by BryceLTaylor** [comment]
This has been filed as two separate issues:
Rounded corners: https://github.com/LLK/scratch-gui/issues/2866
Text getting cut off: https://github.com/LLK/scratch-vm/issues/1477

Thanks for pointing out the vector gradient method of rounding corners.  I've added that info into the issue 2866.
