### ISSUE TITLE
Typo in closed caption for "Add a backdrop" tutorial

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#2781]
### Expected Behavior

There is no typo

### Actual Behavior

There is a typo around 33 seconds:
![image](https://user-images.githubusercontent.com/31634240/43650951-18c6e082-970f-11e8-9761-d9594847e890.png)

### Steps to Reproduce

Look at 33 seconds of the "Add a backdrop" video

### Operating System and Browser

All

**Comment by SpeakkVisually** [comment]
I'll fix this now, thanks!
