### ISSUE TITLE
Say bubble overlapping other sprites

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#2789]
### Expected Behavior
Say bubbles should not show on top of another sprite
https://scratch.mit.edu/projects/238080690/#editor

### Actual Behavior
Say bubbles overlaps other sprites
https://beta.scratch.mit.edu/#238080690
![oqej4f7souv](https://user-images.githubusercontent.com/3812168/43658893-2add7ed4-9728-11e8-8a24-6ae9e2e9efa1.png)

### Steps to Reproduce
Open 2.0 project in 3.0
Click the green flag
Notice that the say bubbles overlap other sprites

### Operating System and Browser
macOS High Sierra
Chrome 68

**Comment by techwonder21** [comment]
@ChampikaF

**Comment by paulkaplan** [comment]
Just updated the title to be a bit more specific, it is correct for say bubbles to generally appear above other sprites, this is a case where a 2.0 project required the bubble showing on the right and the slightly larger 3.0 bubbles flip it to the other side.

**Comment by paulkaplan** [comment]
Patch for this is in https://github.com/LLK/scratch-vm/pull/1427, thanks for reporting it!
