### ISSUE TITLE
When user saves project, show save is in process

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#2811]
Somewhat a duplicate of https://github.com/LLK/scratch-gui/issues/3035

When we implement saving in Beta, and user saves, we should give the user some indication that the save is in process.

Some possibilities: we could use some kind of popup modal/dialog, info in the nav bar, some kind of spinner/progress bar, and/or "Saving..." text.

**Comment by carljbowman** [comment]
@kathymakes - Specced out some examples of a flash message system. "Save process" was included as an example of this system. See https://github.com/LLK/scratch-gui/issues/2956 for more info.

@benjiwheeler - Please let us know if you have any addtional questions.

**Comment by kathymakes** [comment]
Some images of a potential "save process" design:

![saving flow 1](https://user-images.githubusercontent.com/8203939/44741225-76ea9180-aaca-11e8-89a1-bb9e1f268643.png)
![saving flow 2](https://user-images.githubusercontent.com/8203939/44741330-b6b17900-aaca-11e8-9681-09b055173775.png)

**Comment by benjiwheeler** [comment]
Question: what tentative text should i use for alerting the user that the project was saved or created?

@kathymakes used "Successfully saved." above, which I like

**Comment by benjiwheeler** [comment]
Oh, and I guess we need svgs for that checkmark, and also for the progress spinner?

**Comment by kathymakes** [comment]
@benjiwheeler Here's the checkmark as a .svg
[checkmark.svg.zip](https://github.com/LLK/scratch-gui/files/2526373/checkmark.svg.zip)

Here's the loading animation I made (click the button, "download")
https://codepen.io/kathymakes/pen/BPXxWB

**Comment by kathymakes** [comment]
@benjiwheeler 
Here is the spinner spec: https://github.com/LLK/scratch-www/issues/2264

Let me know if you have questions :)
