### ISSUE TITLE
Add title prop, onUpdateTitle, UI for changing title

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#2815]

**Comment by carljbowman** [comment]
Here is a sketch of these states within the Editor's title field
![title states 2x](https://user-images.githubusercontent.com/3409578/44742753-a56a6b80-aace-11e8-998a-bb10199ae734.png)

**Comment by LiFaytheGoblin** [comment]
CSS is at https://github.com/LiFaytheGoblin/scratch-gui/tree/rename_title

Tested for MacOS: Chrome, Safari, Firefox
