### ISSUE TITLE
This Sprite Clicked through a ghosted sprite behaves differently in 3.0

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2820]
In this project on Scratch 2.0: https://scratch.mit.edu/projects/236788917/#editor 
You can click one sprite through a 100% ghost effected second sprite.  This seems to be used to hide the splash screen rather than with the hide block. 

In 3.0 you can't do this, so the project appears to be completely unresponsive.  You can fix this by hiding the splash screen sprite or moving the "bar" sprites to the front.

There are some conditions in 2.0 in which you can NOT click through a ghosted sprite and others where you can.

Repro steps:
Create a project
Add `When This Sprite Clicked` `play sound meow` to the cat
Paint a new sprite that is a large filled in square
Position the square over the cat
Add a `Set Ghost Effect to 100` to the square
Run the ghost effect block
Click the cat
Note: the cat meows

Repro steps for when you CAN'T click through a ghosted sprite
Create a project
Add `When This Sprite Clicked` `play sound meow` to the cat
Add a new sprite from the library (I nice big one such as Creature 1 so it covers the cat)
Position the sprite over the cat
Add `When This Sprite Clicked` `change color effect by 25` to the second sprite
Add a `Set Ghost Effect to 100` to the new sprite
Run the ghost effect block
Click the cat
Note: nothing meows
Set the ghost effect for the second sprite back to 0
Note: it has changed colors

It seems that the order you do things in and maybe whether you choose the sprite from the library or draw it yourself affects whether or not you can click through a sprite.  I think this is enough to start discussion, but what SHOULD the behavior be?

This is related to https://github.com/LLK/scratch-render/pull/325#issuecomment-410348923

**Comment by thisandagain** [comment]
From conversation with @kchadha and @BryceLTaylor we have decided to *not* resolve this issue as the behavior in Scratch 2.0 seems unexpected and broken in various contexts. 

The issue in https://scratch.mit.edu/projects/236788917/#editor is not directly related to this issue but rather is a problem with the tolerance for "clicking through" a sprite:
![image](https://user-images.githubusercontent.com/747641/47037998-652e7d80-d14e-11e8-92d3-b096ef807032.png)

This will be filed separately by @BryceLTaylor
