### ISSUE TITLE
Sprite / BG Watermark on blocks workspace

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#2826]
## Overview
We would like to add back the watermark of the selected sprite or backdrop. This was a feature in 2.0 that helped to clarify which sprite or backdrop was selected. 

#### Sizing and Positioning
The watermark should have max size of 48px by 48px (or 3rem by 3rem) and be position relative to the top-right corner.  This element should also be right-aligned to the zoom controls. More detailed specs below.

#### RTL
Features are are absolute positioned on the right of a container element (e.g. Add Sprite button) need to have an RTL tag so they they are properly handled when switching to a Right-to-Left language. Talk to @chrisgarrity if you have any questions

#### Opacity
Let's try 35%, but we may need to tweak. 

#### Z Index
Ideally replicate 2.0 (below blocks), but not a dealbreaker.

## Mocks
![dino - watermark](https://user-images.githubusercontent.com/3409578/43903225-f375c00a-9bb9-11e8-82dc-791bd7f69589.png)

![bear - watermark](https://user-images.githubusercontent.com/3409578/43903229-f62d9872-9bb9-11e8-9aba-8451f78296dd.png)

![stage - watermark](https://user-images.githubusercontent.com/3409578/43903232-f8b14dfa-9bb9-11e8-83d4-500f64b6959b.png)

## Specs
![dino - watermark - guides](https://user-images.githubusercontent.com/3409578/43903038-874a49d2-9bb9-11e8-9bee-8b0ce095b94e.png)

![bear - watermark - guides](https://user-images.githubusercontent.com/3409578/43903036-84fee502-9bb9-11e8-8940-0d2240fc472a.png)

![stage - watermark - guides](https://user-images.githubusercontent.com/3409578/43903035-834dc214-9bb9-11e8-95ae-0d777a4ba365.png)

**Comment by fsih** [comment]
@carljbowman Just a thought, my first impression was that it's very small. I had a costume that was all text, and it became just some dots.
