### ISSUE TITLE
where is the build folder?

### ISSUE THREAD

**Issue by xxhong** [LLK/scratch-gui#2837]
ℹ ｢wds｣: Content not from webpack is served from /Users/xxhong/Documents/xxhong/scratch/scratch30_code/scratch-gui/build

Whether added to the ignore directory？

**Comment by xxhong** [comment]
When I run   npm start

**Comment by apple502j** [comment]
Did you run `npm install`?

**Comment by javascriptzpt** [comment]
you should npm run build. when you run start ,you will not find the build folder.
