### ISSUE TITLE
Wierd if on edge bounce pixel issue

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-gui#284]
### Expected Behavior

When sprite touches edge with an if on edge bounce going forever it should not be Pixley.

### Actual Behavior

Before scripts and green flag clicked:
![screenshot 2017-03-28 at 8 43 31 pm](https://cloud.githubusercontent.com/assets/10731781/24433578/b41a3e2c-13f7-11e7-9c81-32378fa5dc24.png)

Before moved to edge:
![screenshot 2017-03-28 at 8 44 38 pm](https://cloud.githubusercontent.com/assets/10731781/24433597/d9e13fb6-13f7-11e7-9717-4269774cff33.png)

When moved to edge with the script:
![screenshot 2017-03-28 at 8 44 01 pm](https://cloud.githubusercontent.com/assets/10731781/24433607/edffd0b6-13f7-11e7-9bbc-3545c245701a.png)

### Steps to Reproduce

1. Make script shown in screenshots.
2. Click green flag.
3. Move sprite to edge.
4. Watch and be amazed. 

### Operating System and Browser

Chromebook Latest Version

BTW I do not know where this should go? I think this is the right place...

**Comment by SillyInventor** [comment]
Dupicate of LLK/scratch-render#77 ?

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-render/issues/77
