### ISSUE TITLE
 Poor quality of vector images

### ISSUE THREAD

**Issue by SimaKyr** [LLK/scratch-gui#2847]
### Expected Behavior

Good anti-aliasing

### Actual Behavior

Incorrect anti-aliasing

### Steps to Reproduce

1.Open Scratch 3.0
2.Click on full screen

![x](https://user-images.githubusercontent.com/28606130/43994373-8e3fda1c-9da4-11e8-8682-8419c601f39f.png)

### Operating System and Browser

Windows 10, Chrome v.68.0.3440.106

**Comment by thisandagain** [comment]
Moved to LLK/scratch-render#334
