### ISSUE TITLE
Bug:opportunity to scroll

### ISSUE THREAD

**Issue by SimaKyr** [LLK/scratch-gui#2848]
### Expected Behavior

here is an opportunity when you transfer the sprite to the left

### Actual Behavior

should not be able to scroll

### Steps to Reproduce
![3](https://user-images.githubusercontent.com/28606130/43994520-11982656-9da7-11e8-9d80-b75f03966fe1.png)

try to move the sprite to the right

### Operating System and Browser

Windows 10, Chrome v.68.0.3440.106

**Comment by towerofnix** [comment]
Thanks for the report! This is, if I'm correct, a duplicate issue of #1791. If that describes the same problem, it would be best to close this issue. Keeping track of each issue in its own unique topic helps keep everything organized.

**Comment by SimaKyr** [comment]
Ok, i'm close it issues
