### ISSUE TITLE
Add GET block

### ISSUE THREAD

**Issue by SimaKyr** [LLK/scratch-gui#2849]
You could add the ability to make GET, POST, PUT requests at least 10 seconds (or 1440 requests per day)

**Comment by kyleplo** [comment]
There's no way they are going to add this.

**Comment by joker314** [comment]
This could be used

- As a vector for CSRF against Scratch
- As a way of spamming sites (e.g. DOS)
- As a way of displaying unpredictable content (which could bypass bad-word filters)

There are plenty of benefits, of course, but they need to be balanced against some of the flaws. 🙂

**Comment by SimaKyr** [comment]
But why if add limit?

**Comment by joker314** [comment]
@SimaKyr That, unfortunately, would only resolve the second issue.

**Comment by Kenny2github** [comment]
@SimaKyr Especially the third problem is the most dangerous. Scratch doesn't allow some things to be shown to people; a block like this could show the forbidden things randomly, and make it a lot harder for the Scratch Team to deal with.

**Comment by thisandagain** [comment]
Thanks for the suggestion. This has significant security, privacy, and safety implications that make it unlikely to be added. In the future, we recommend that you make suggestions for new blocks here:
https://scratch.mit.edu/discuss/57/
