### ISSUE TITLE
Scratch Link disappears after a few minutes

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#2850]
### Expected Behavior

After running the installer, Scratch Link works.

### Actual Behavior

After clicking "Finish" on installer, nothing happens.

### Steps to Reproduce

Download and run the installer

### Operating System and Browser

Windows 10.1709 (64-bit) Chrome 68.0.3440.106

**Comment by apple502j** [comment]
Did you run it via Start Menu?

**Comment by Kenny2github** [comment]
Yeah, did you actually try to run it after installing it? It's not every installation wizard that includes an option to run after installation.

**Comment by kyleplo** [comment]
@apple502j It's not in the start menu

**Comment by apple502j** [comment]
@kyleplo C:\Program Files (x86)\Scratch Link\ScratchLink.exe
Does it exist?

**Comment by kyleplo** [comment]
@apple502j Yes, but when I run the exe, it appears for a minute or two like this:
![image](https://user-images.githubusercontent.com/31634240/44092448-73ca9996-9f9e-11e8-877f-97cd92583bbb.png)
Then it disappears. Clicking on it does nothing.

**Comment by ericrosenbaum** [comment]
Sorry you're having trouble @kyleplo. It sounds like there are multiple issues here:

- Scratch Link does not automatically launch after installation. We are in the process of getting Scratch Link into the Mac and Windows app stores, which we hope will improve this (at least by providing a way to immediately launch the app from the app store).
- Once you launched Scratch Link manually, it disappears. This sounds like a bug where Scratch Link has crashed. I'm going to update the issue title to focus on this one. Thanks for reporting it!

**Comment by kyleplo** [comment]
This is still a bug even after I re-installed scratch link. Why is this closed?

**Comment by cwillisf** [comment]
@kyleplo just a few hours ago we released a new version of Scratch Link with a ton of fixes -- and a new greenish icon! ;)

We'll usually close an issue if we've fixed it internally, but it can take some time to release the fix even after we have the code written. There's a bunch of reasons for this, including testing and other parts of our development process and scheduling.

Anyway, thanks for the feedback! Please try the new version and, if you still see this issue, let us know. Thanks!

**Comment by kyleplo** [comment]
@cwillisf Where is the new download link? Same as the old one?

**Comment by cwillisf** [comment]
@kyleplo Yep - same place. Here's a direct link:
https://downloads.scratch.mit.edu/link/windows.zip
https://downloads.scratch.mit.edu/link/mac.zip

**Comment by kyleplo** [comment]
@cwillisf UPDATE: Now, when I run ScratchLink.exe in C:\Program Files (x86)\Scratch Link, it does appear and stays there for a while. Some suggestions for Scratch Link:
- Make it easier to start, such as a desktop shortcut or a button in Start
- Make clicking on the icon do something, because it confused me when clicking did nothing, I thought it was broken
