### ISSUE TITLE
Weird behavior when clicking a stacked translate blocks.

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#2861]
### Expected Behavior
It pops a text and stop.
### Actual Behavior
![translatebug](https://user-images.githubusercontent.com/31377746/44069726-b8ce0ea6-9fb2-11e8-8ced-0d5ec87255b9.gif)
### Steps to Reproduce
Stack blocks like this
![tb2](https://user-images.githubusercontent.com/31377746/44069779-fde61c9a-9fb2-11e8-9480-96468c4e8739.PNG)
### Operating System and Browser
Win 8, Google Chrome 68

**Comment by Kenny2github** [comment]
Can reproduce on develop with Chrome 68 Windows 10.
Note: Steps to reproduce in issue description did NOT work, only the configuration in the "Actual behavior" section showed this problem.

### Actual Steps to Reproduce
1. Stack blocks like so:
![image](https://user-images.githubusercontent.com/28599280/44079214-0de6a7fe-9fdb-11e8-8636-0c26c15b8de7.png)
2. Click on any block in the stack.

Important part is that there MUST be a reporter block in the input.
### OS, Branch, and Browser
Windows 10, [develop](https://llk.github.io/scratch-gui/develop), Chrome 68
I noticed that the language is irrelevant to the issue, setting the language to Simplified Chinese or English made no difference.

**Comment by picklesrus** [comment]
This stack trace that seems to happen when clicking an individual translate block is perhaps related?
raven.js:429 Uncaught TypeError: Cannot set property 'null' of null
    at e.exports (lib.min.js:114)
    at e.value (lib.min.js:114)
    at e.value (lib.min.js:114)
    at A.value (lib.min.js:47)
    at lib.min.js:47
    at d (raven.js:425)
e.exports @ lib.min.js:114
value @ lib.min.js:114
value @ lib.min.js:114
value @ lib.min.js:47
(anonymous) @ lib.min.js:47
d @ raven.js:425

**Comment by picklesrus** [comment]
Fixed by https://github.com/LLK/scratch-vm/pull/1853
