### ISSUE TITLE
language block returns “中文(简体)” when using the "にほんご" language

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#2862]
### Expected Behavior
it returns "にほんご"

### Actual Behavior
it returns “中文(简体)” (My computer is Chinese so I'm not sure what will it return on other languages' computer.)
Also, the language in the drop down menu is also Chinese.
### Steps to Reproduce
1.change the language to  "にほんご"
2. use the google translate extension and click "げんご"
### Operating System and Browser
Win 8, Google Chrome 68

**Comment by cyx2015s** [comment]
Some other languages have the same behavior:Azeri, Espanol Latinoamericano, Maori, Portugues Brasileiro, 繁体中文
Languages that the "language" block returns a short code:the first language, Norsk bokmal, Norsk nynorsk,

**Comment by apple502j** [comment]
In Japanese computer it returned "日本語"
also in Traditional

I think "custom languages" are buggy.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/1561
