### ISSUE TITLE
Is there a way to save the current stage as a png/jpeg file

### ISSUE THREAD

**Issue by luofei614** [LLK/scratch-gui#2865]
Is there a way to save the current stage as a png/jpeg file

**Comment by ScratchDiogoh** [comment]
{offtopic}I think someone should close this, this is not a problem :-1: {/offtopic}

**Comment by joker314** [comment]
Good question @luofei614! I see you asked a question in #1629, shall we keep discussion there? It's okay that the other issue is closed, project maintainers will still get notified of your question.

**Comment by joker314** [comment]
Maybe I was wrong. It's harder to track closed issues. Feel free to re-open it unless a developer tells me I'm mistaken?

Sorry for the confusion!
