### ISSUE TITLE
Vector shapes with rounded corners imported with sharp corners

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2866]
Some vector sprites have shapes with rounded edges in 2.0 that are possibly imported from other software.  In 3.0 they will be imported with straight edges.

Examples:
The play button and white background pattern on the title screen in here:
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#203392290

<img width="998" alt="screen shot 2018-08-14 at 11 08 27 pm" src="https://user-images.githubusercontent.com/1088291/44129775-0a4821da-a018-11e8-9a2c-c287cb82b9de.png">

The shape of the tank parts in this project
https://llk.github.io/scratch-gui/develop/compatibility-testing.html#132801606
![screen shot 2018-08-14 at 4 50 02 pm](https://user-images.githubusercontent.com/1088291/44129840-63b3ffd2-a018-11e8-9137-921200b372cd.png)

**Comment by SAODTHEKING** [comment]
not only that! alot of them have weird collision boxes.
try this project in 2.0 then 3.0
https://scratch.mit.edu/projects/198901436/
you will see u cant move in 3.0 thats because the collision boxes of the level are larger than normal

**Comment by BryceLTaylor** [comment]
From this issue: https://github.com/LLK/scratch-gui/issues/2780#issuecomment-414357278
I have figured out how to reproduce creating rounded corners in 2.0

Create a new sprite
Convert it to Vector
Choose the Square tool
Ensure that the square is in the hollow mode
Increase the Stroke Thickness
Choose the paint bucket tool
Set it to one of the gradient options (it doesn't matter which, but it can't be the solid color)
Set both colors to the same color
Click on the Stroke of the box
Note: the corners become round

When importing projects like this into 3.0 the corners are not drawn rounded.

**Comment by BryceLTaylor** [comment]
Here is a project teaching people how to do this: https://scratch.mit.edu/projects/140325920/
It has a few extra steps (like holding shift to keep the shape square).  My repro steps above are a more minimal set.

**Comment by BryceLTaylor** [comment]
It seems that if you "gradient trick" a line, the line doesn't appear on the stage in 3.0.  See this project:
https://beta.scratch.mit.edu/#240180579
![screen shot 2018-08-23 at 9 59 45 am](https://user-images.githubusercontent.com/1088291/44529933-4e722a00-a6bb-11e8-9dd6-5864e8517387.png)

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-paint/issues/394
