### ISSUE TITLE
I want to use these blocks to generate python code. I can't find an interface to generate code. What should I do?

### ISSUE THREAD

**Issue by javascriptzpt** [LLK/scratch-gui#2867]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by ScratchDiogoh** [comment]
convert them to java script, and then to python :blush:

**Comment by javascriptzpt** [comment]
But，i dont know how to convert them to javascript，Could you tell me more about it，millions of thanks

@ScratchDiogoh

**Comment by ScratchDiogoh** [comment]
@javascriptzpt  I only know a few blocks for javascript, but you can refer to this guide:
https://en.wikipedia.org/wiki/JavaScript_syntax

**Comment by javascriptzpt** [comment]
who can help me?

**Comment by wwj718** [comment]
@javascriptzpt You can refer to [Generating Code](https://developers.google.com/blockly/guides/create-custom-blocks/generating-code)
Please take a look at [my demo](https://github.com/wwj718/blockly_dev/blob/master/src/scratch-blocks_hello_world/readme.md)

**Comment by javascriptzpt** [comment]
@wwj718 我看到你的工程里“scratch-blocks_hello_world”这个项目，但我没找到生成代码的部分在哪里呀。

**Comment by wwj718** [comment]
@javascriptzpt 生成代码的关键是[自定定义generator](https://github.com/wwj718/blockly_dev/blob/master/src/scratch-blocks_hello_world/readme.md#%E8%87%AA%E5%AE%9A%E5%AE%9A%E4%B9%89generator)

这部分和blockly文档没有差异，可以先读一些blockly的文档

**Comment by thisandagain** [comment]
We do not officially support "generators" with Scratch Blocks are rather encourage folks using our open source code to use the Scratch Virtual Machine available here:
https://github.com/LLK/scratch-vm
