### ISSUE TITLE
npm install return error

### ISSUE THREAD

**Issue by iburning** [LLK/scratch-gui#2878]
### Expected Behavior

npm install

### Actual Behavior

Error: [scratch-svg-renderer@0.2.0-prerelease.20180712223402] Can't find package scratch-svg-renderer's version: 0.2.0-prerelease.20180712223402

### Steps to Reproduce

git clone git@github.com:LLK/scratch-gui.git
cd scratch-gui
npm install

### Operating System and Browser

npm -v
5.6.0

**Comment by liuzy0404** [comment]
Don't use taobao npm, use official npm with vpn proxy.
