### ISSUE TITLE
"restore" was not translated

### ISSUE THREAD

**Issue by ScratchDiogoh** [LLK/scratch-gui#2880]
### Expected Behavior
"restore" should be translated
### Actual Behavior
the word remains intact (untranslated)
### Steps to Reproduce
go to another language and click "edit" in the specific language
### Operating System and Browser
possibly all

**Comment by chrisgarrity** [comment]
@ScratchDiogoh the 'restore' command is new, and was not yet translated by translators. It should start to be in other languages next week depending on which translators have translated it.
