### ISSUE TITLE
Dynamic Menu does not display string items properly

### ISSUE THREAD

**Issue by Affonso-Gui** [LLK/scratch-gui#2891]
### Expected Behavior

_Dynamic Menus displays items the same way as Static Menus._

### Actual Behavior

_In Dynamic Menus, only the initial letter is displayed for string items._

### Steps to Reproduce

_Minimal extension code below, used from forked `scratch-vm`._

```javascript
const ArgumentType = require('../../extension-support/argument-type');
const BlockType = require('../../extension-support/block-type');

class Scratch3TestBlocks {

    constructor() {}

    testMenu() {};
    _initMenu() {
	return ['THIS', 'IS', 'A', 'TEST'];
    }
    _initMenu2() {
	return [{data: 'THIS', text:'THIS'},
		{data: 'IS', text:'IS'},
		{data: 'A', text: 'A'},
		{data: 'TEST', text: 'TEST'}];
    }
    getInfo() {
	return {
	    id: 'test',
	    name: 'test',

	    blocks: [
		{
		    opcode: 'testMenu',
		    blockType: BlockType.COMMAND,

		    text: '[MENU]',
		    arguments: {
			MENU: {
			    type: ArgumentType.STRING,
			    menu: 'menu',
			}
		    }
		}
	    ],
	    menus: {
		menu: '_initMenu'         // doesn't work (displays initials: [T, I, A, T] )
		// menu: this._initMenu() // this is fine
		// menu: '_initMenu2'     // this also works
	    }
	}
    }
}

module.exports = Scratch3TestBlocks;
```

### Operating System and Browser

_Ubuntu 16 and Chromium, Firefox_

**Comment by thisandagain** [comment]
@cwillisf Any thoughts on this one?

**Comment by cwillisf** [comment]
The [spec](https://github.com/LLK/scratch-vm/wiki/Scratch-3.0-Extensions-Specification) isn't very explicit about what a dynamic menu function should return but I think the natural assumption is that it could return any value which would be valid for a static menu.

In particular, I think it's reasonable to assume that these two cases from the example above should behave the same:
```js
menus: {
  menu1: '_initMenu'      // doesn't work (displays initials: [T, I, A, T] )
  menu2: this._initMenu() // this is fine
}
```

All of that is to say that I agree that this is a legitimate issue. Thanks for bringing it to our attention, @Affonso-Gui!

**Comment by Affonso-Gui** [comment]
Fixed in https://github.com/LLK/scratch-vm/pull/1871
