### ISSUE TITLE
How to add my own blocks In the default toolbox。

### ISSUE THREAD

**Issue by javascriptzpt** [LLK/scratch-gui#2901]
How to do it in scratch-GUI not in scratch-blocks

**Comment by thisandagain** [comment]
In your fork of Scratch GUI you will need to add your blocks to both Scratch Blocks and Scratch VM and then edit the default toolbox to add your blocks:
https://github.com/LLK/scratch-gui/blob/2c6b5bc8da45e449fae446750d742fa11887734c/src/lib/make-toolbox-xml.js
