### ISSUE TITLE
Rotation Only Working Every 45 Degrees

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#2911]
### Expected Behavior
Turning 1 degree and moving 1 step constantly should create a circle
### Actual Behavior

It makes an octagon.

### Steps to Reproduce

Create a script where you turn 1 degree and move 1 step constantly.

### Operating System and Browser

Chrome on Windows 10 

It was also reported by henry27q on Scratch.
https://scratch.mit.edu/discuss/topic/299791/?page=277#post-3223192 is where it was reported.

**Comment by towerofnix** [comment]
Here is a screenshot of the repro case described:

![pen down, repeat 360, turn 1 degrees, move 1 steps](https://user-images.githubusercontent.com/9948030/44294907-2fb40380-a275-11e8-9a51-f8b0b9ca2f29.png)

*Ceci n'est pas un circle.*

**Comment by fsih** [comment]
@mzgoddard 
@rschamp

**Comment by SAODTHEKING** [comment]
Yes! i was about to open this exact issue.
its annoying, broke some of my games that make a semicircle speedometer/health

**Comment by thisandagain** [comment]
Agreed with @fsih that this is a major regression that should be hotfixed ASAP.

/cc @BryceLTaylor

**Comment by amazinigmech2418** [comment]
@thisandagain I posted a few PRs for it. 1 in scratch-gui and 1 in scratch-vm. 1 fixes the glitch and the other rounds in the input boxes. The rounding in the inputs isn't needed, but could be used. The problem is that it is rounding even during the change x by _ blocks and move _ steps blocks.

**Comment by thisandagain** [comment]
Thanks @amazinigmech2418. We'll take a look today. 😄
