### ISSUE TITLE
176021042 and 172111618 loads incorrectly

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#2912]
### Expected Behavior

All scripts will change to scratch 3.0 properly

### Actual Behavior

Most of them disappeared.

### Steps to Reproduce

Go to
https://beta.scratch.mit.edu/#176021042
https://scratch.mit.edu/projects/176021042/
and
https://beta.scratch.mit.edu/#172111618
https://scratch.mit.edu/projects/172111618/
### Operating System and Browser

Win 8, Chrome 68

**Comment by cyx2015s** [comment]
I guess is because of the hacked blocks.

**Comment by SimaKyr** [comment]
This is because one block is not loaded, it disappears, the other can not find it and disappears and so with others it also happens

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/1030
