### ISSUE TITLE
Color Picker can't pick color in editor

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#2914]
### Expected Behavior

It can pick color in Scratch editor (as Scratch 2 does)

### Actual Behavior

Only available inside stage
### Steps to Reproduce
1 pick color in editor
2 it doesn't work
### Operating System and Browser
WIndows 10/Firefox 61.0.2

**Comment by kyleplo** [comment]
That's impossible with HTML5

**Comment by thisandagain** [comment]
This is unfortunately not something we can do in HTML5 / Javascript given what is available from browser APIs.
