### ISSUE TITLE
Wrong displays sprite

### ISSUE THREAD

**Issue by SimaKyr** [LLK/scratch-gui#2916]
![5](https://user-images.githubusercontent.com/28606130/44310472-8dfcf580-a3df-11e8-974a-3c9cc34f035a.png)
### Expected Behavior

Blurred sprite when it cost

### Actual Behavior

Must be displayed correctly

### Steps to Reproduce

Try to move the mouse straight and it ceases to be stretched and becomes clear

### Operating System and Browser

Windows 10, Chrome v.68.0.3440.106
Maybe work on any

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-render/issues/332 and https://github.com/LLK/scratch-render/issues/334

Please check for existing issues before filing new issues. Otherwise, please use the "Scratch 3.0 Beta" forum to avoid creating extra work for the Scratch Team.
