### ISSUE TITLE
Copy block and right click, the block sticks with mouse. 

### ISSUE THREAD

**Issue by hahapang** [LLK/scratch-gui#2918]
### Expected Behavior

The blocks should not stick with mouse.

### Actual Behavior

The block always stick with mouse, left click or right click doesn't work. 

### Steps to Reproduce

1. Right clicking and copy a block.
2. DO NOT move mouse and right click again.

### Operating System and Browser

Mac OS 10.12 Chrome 68.0.3440.106

**Comment by SimaKyr** [comment]
![1](https://user-images.githubusercontent.com/28606130/44333267-05319880-a477-11e8-96b1-e928f0ac1997.gif)
Linux Mint Cianamon 19 64bit, Chromium/67.0.3396.99

**Comment by hahapang** [comment]
Please don't move mouse after duplicate blocks.  Right click again.

**Comment by hahapang** [comment]
![qq20180820-180215](https://user-images.githubusercontent.com/26299904/44334121-45a70b80-a4a3-11e8-8b39-e6bf6147ab8f.gif)

**Comment by SimaKyr** [comment]
![ezgif-2-96c1533c20](https://user-images.githubusercontent.com/28606130/44337219-8b071100-a482-11e8-8664-5c927b949535.gif)
I first duplicate the right key and then quickly press the left

**Comment by thisandagain** [comment]
This is actually by design. This feature also exists in Scratch 2.0
