### ISSUE TITLE
Projects playing on top of one another

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#2927]
### Expected Behavior

Switching projects (via hash in url or any other means) should clear out old project and load new project.

### Actual Behavior

In the smoke test on 08/10/18, I somehow got into a state where one project got loaded on top of the other and both projects were playing when I clicked the green flag.

The two projects in question were: 
238746871 and 236345336

Note: these are both pen projects, but this is not the same as #1850.

I was using an Android tablet during the smoke test.

**Comment by thisandagain** [comment]
@rschamp Is this something we should prioritize (aka does this impact the project page work in any way)?

**Comment by kchadha** [comment]
@thisandagain, @rschamp, I think this issue still needs repro because I wasn't able to get it to happen again.

**Comment by BryceLTaylor** [comment]
Apparently this was seen on an android tablet according to @kchadha 
I'm still tracking it down.

**Comment by BryceLTaylor** [comment]
I can not reproduce this on the Samsung tablet "Bran Muffin" number 30.

**Comment by BryceLTaylor** [comment]
I also can't reproduce it on number 25 "muesli" (which has no identifying marks other than "designed by google, made in China")
