### ISSUE TITLE
All the blocks project does not load on Edge

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2929]
### Expected Behavior
Projects should eventually load

### Actual Behavior
Go to http://bit.ly/alltheblocks on Edge
The page freezes. Eventually the browser says "llk.github.io is not responding." and gives an option to force quit.

The console contents: 
```
CONSOLE1810304: console.memory is not implemented and will return 0 for all attributes. Please use the memory profiler to monitor memory utilization.

 WEBAUDIO17050: An unknown decoding error occured.
```
Note that the webaudio error shows up on many projects though, including projects that load.

### Steps to Reproduce
1. Go to http://bit.ly/alltheblocks on Edge

### Operating System and Browser
Windows 10 Edge

**Comment by thisandagain** [comment]
This is going to need a more minimal repro to track down the source. @BryceLTaylor You mind taking a look?

**Comment by BryceLTaylor** [comment]
I've confirmed that the project doesn't load on two other machines.  Currently I'm being blocked by this issue https://github.com/LLK/scratch-gui/issues/3294 which is preventing me from uploading other variants of the project to research further.

**Comment by fsih** [comment]
Nooooooo edge!!!

**Comment by fsih** [comment]
Here is a hack that you can put in the console on beta.scratch.mit.edu
document.getElementsByClassName("menu_menu_3k7QT menu_right_3PQ4S")[0].setAttribute('style','z-index:10000');

**Comment by BryceLTaylor** [comment]
It seems to be loading just fine now. Hooray!
