### ISSUE TITLE
 Right edge of stage is a few pixels too far to the right, in editor

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#2932]
Observed by Linda in 8/17/18 smoke test

![screen shot 2018-08-20 at 11 52 12 am](https://user-images.githubusercontent.com/3431616/44351274-838a3c80-a46f-11e8-952e-d64288ca7a53.png)

**Comment by thisandagain** [comment]
Related to https://github.com/LLK/scratch-gui/issues/2022

**Comment by LiFaytheGoblin** [comment]
I did some experimenting: I removed the border box stuff, and it was still there. Setting the stage width to auto _would_ solve it, but then the size of the stage will be 480 minus the border width and if I understood correctly this is not what we want?

**Comment by mxmou** [comment]
#5508 fixed this.

**Comment by benjiwheeler** [comment]
Thanks for the help, @mxmou
