### ISSUE TITLE
Sprites are weirdly pixelated/blurry when the browser starts off at non-100% zoom

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2936]
### Expected Behavior
Stage should look crisp even if the browser is zoomed

### Actual Behavior
Stage gets fuzzy and has some jaggedly rendered lines
Here is Chrome on Windows at 100% vs 90% zoom. It gets much blurrier and the shoulder and ear have jagged lines.
![image](https://user-images.githubusercontent.com/2855464/44355222-0617f980-a47a-11e8-98f5-6cae1fcb1ce6.png)

Note that if you load the page at 100% zoom and then change to 90% zoom, it looks correct:
![image](https://user-images.githubusercontent.com/2855464/44355317-47a8a480-a47a-11e8-99d9-74a46293b1ca.png)
And if you load the page at 90% zoom and then change to 100% zoom, it stays blurry and jagged:
![image](https://user-images.githubusercontent.com/2855464/44355395-7d4d8d80-a47a-11e8-84d9-f2d5857bd582.png)

Here are some examples of distortion from different zoom levels:
![image](https://user-images.githubusercontent.com/2855464/44355629-1da3b200-a47b-11e8-91ec-16e9d1e24c5d.png)
![image](https://user-images.githubusercontent.com/2855464/44355642-24cac000-a47b-11e8-8b46-1f58c9cb62c7.png)

### Steps to Reproduce
1. Set the browser zoom to 90% before navigating to Scratch
2. Go to the beta
I think this may have to do with the fact that my screen is 1920x1080, as I don't see it on high DPI screens

### Operating System and Browser
Windows, issues seen on Chrome, Firefox, and Edge, though they each look a bit different

**Comment by towerofnix** [comment]
This is probably the same as #1462. (I also have always used a 1920x1080, non-hi-DPI screen.)

**Comment by thisandagain** [comment]
Thanks for catching that. Agreed. Tracking in https://github.com/LLK/scratch-gui/issues/1462
