### ISSUE TITLE
lib.min.js is too big after packing

### ISSUE THREAD

**Issue by joy-yi0905** [LLK/scratch-gui#2951]
### Expected Behavior

When i open [scratch](https://beta.scratch.mit.edu/)  project, And In debugging tools I found `lib.min.js` only `3.9M` :

![build-official](https://user-images.githubusercontent.com/10655307/44440839-85353b00-a5fc-11e8-808a-5ba44f5e0809.png)

### Actual Behavior

But When I packed it locally, I found the file was very large. I really wonder is there some content that needs to be separately configured?

![build-custom](https://user-images.githubusercontent.com/10655307/44440830-7cdd0000-a5fc-11e8-8f82-9cf609de9497.png)

### Steps to Reproduce

- git clone `https://github.com/LLK/scratch-gui` develop branch
- `npm run build`

### Operating System and Browser

Window10 Chrome 68.0.3440.106

**Comment by joy-yi0905** [comment]
Oops, sorry ! Webpack must config `set NODE_ENV=development`  , and server client must open the `gizp` option

**Comment by oddstar** [comment]
I set NODE_ENV=production, and npm run build; but it's also too big; How to minmize lib.min.js ???

**Comment by acegank** [comment]
楼上的老铁，我也是这样的，即便production后依然有13M，开启gizp有差这么多吗？

**Comment by hu19940121** [comment]
> I set NODE_ENV=production, and npm run build; but it's also too big; How to minmize lib.min.js ???

you can  use a plugin in webpack, name compression-webpack-plugin,  then your server client needs open the gzip.

**Comment by shenfyjames** [comment]
How to minmize lib.min.js? it's too big
