### ISSUE TITLE
The result of comparing Japanese characters is different from Scratch 2.0 and 3.0.

### ISSUE THREAD

**Issue by abee2** [LLK/scratch-gui#2952]
### Expected Behavior
It should be followed the Unicode, I guess.
This problem was found by watashida.
https://scratch.mit.edu/discuss/topic/258450/?page=36#post-3225461

### Actual Behavior
<[こ] = [コ]> returns 'false' on Scratch 2.0.
And it returns 'true' on Scratch 3.0.
'こ' is 0x3053 and 'コ' is 0x30B3.

<[界] < [丁]> returns 'false' on Scratch 2.0.
And it returns 'true' on Scratch 3.0.
'界' is 0x754C and '丁' is 0x4E01.

### Steps to Reproduce
Click the above blocks.

### Operating System and Browser
I tested the following environment. But it might be happen on all platfomes. 
My browser / operating system: Windows NT 10.0, Chrome 68.0.3440.106, Flash 30.0 (release 0)

**Comment by cyx2015s** [comment]
I can't repro.
Win8, Chrome 68.

**Comment by cyx2015s** [comment]
<[あ] < [字]>
In Scratch 2: true
In Scratch 3: false

**Comment by joker314** [comment]
(I think) moved to LLK/scratch-vm#1526

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/1526
