### ISSUE TITLE
Alerts for hardware and other info: overall design

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-gui#2956]
## Overview

We need a way to tell Scratchers when their hardware extension device loses connection.
This design is for an alert message which directs users to the device modal.

## Current Scope

The alert appears when an extension device loses connection.
Clicking "x" dismisses the alert.
![device is disconnected 1](https://user-images.githubusercontent.com/8203939/44667868-f6546400-a9e9-11e8-9c12-3fb5b81a93bf.png)

Clicking "reconnect" triggers the device modal. The original alert should disappear.
![device is disconnected 2](https://user-images.githubusercontent.com/8203939/44667877-ff453580-a9e9-11e8-9264-f1a50c42f142.png)

The alert can also appear in full screen stage mode.
Clicking "reconnect" takes you back to the editor page w/ device modal.
![full screen alerts 1](https://user-images.githubusercontent.com/8203939/44667895-0b30f780-a9ea-11e8-967b-4fddc57bd84d.png)

More than one alert can appear at once. Multiple alerts should stack.
![multiple alerts 3](https://user-images.githubusercontent.com/8203939/44667919-184de680-a9ea-11e8-82b9-b2b2cad9fa41.png)

Stacking behavior persists in full screen stage.
![full screen alerts 2](https://user-images.githubusercontent.com/8203939/44667963-361b4b80-a9ea-11e8-9e21-66b3e5431fdc.png)

Although multiple alerts case is probably rare... the stacking solution isn't ideal. We might revisit a solution that doesn't dominate the entire workspace. 

# Future Considerations

### Extensibility
Alerts could also be useful in other use cases:
- Downloading/uploading confirmations
This case includes a "progress" alert and a "success" alert. 
![download flow 2](https://user-images.githubusercontent.com/8203939/44667987-49c6b200-a9ea-11e8-8741-86dc3039d625.png)
![download flow 3](https://user-images.githubusercontent.com/8203939/44667988-49c6b200-a9ea-11e8-889d-ea41d7cdb56c.png)

(Success alert should disappear on a timer.)

- Lost wifi connection
![wifi is disconnected 1](https://user-images.githubusercontent.com/8203939/44668019-5e0aaf00-a9ea-11e8-9f21-243fe7e9fb28.png)

### Other Extensions Messaging
There are a couple situations where we should communicate that hardware is not connected, with or without alerts.
- What happens if a Scratcher loads a project with hardware extensions, without a device already connected?
- Is this useful for other extension errors, e.g. video sensing?
- **How does this system work with the project page?**

## Specs

**Sizing + Colors**
Minimum width is 448px. For the smaller size, min width is 200px. 
Ideally, text shouldn't be longer than one line. If it needs to, it can wrap to a 2nd line.
![spec](https://user-images.githubusercontent.com/8203939/44669202-4123ab00-a9ed-11e8-9586-791706410f4b.png)

**Positioning**
Alerts are centered within the code stage.
First alert is 64px from the top of the page.
Multiple alerts have 8px of spacing between them.

![multiple alerts 3](https://user-images.githubusercontent.com/8203939/44669263-716b4980-a9ed-11e8-969f-d8f28057f9ed.png)

When the code stage stage shrinks, the alert is centered within the entire window instead, so that it doesn't lose width.
![responsive](https://user-images.githubusercontent.com/8203939/44669257-6d3f2c00-a9ed-11e8-98a1-02f94bb870b8.png)

R1 Animation: [https://codepen.io/kathymakes/pen/BPXxWB](url)
R1 Mockups: [https://projects.invisionapp.com/d/main#/projects/prototypes/15193635](url)

**Comment by carljbowman** [comment]
@kathymakes - Looks great! Thanks for speccing this out!

**Comment by chexbox** [comment]
@kyleplo also the "Internet not connected - project cannot be saved" message.

**Comment by kathymakes** [comment]
Reupdated spec & images.

**Comment by evhan55** [comment]
Progress is being made via PR https://github.com/LLK/scratch-gui/pull/3143.

Still to do in further PR's:
- hook up a Reconnect button to enable reconnecting to a disconnected peripheral
- multiple alerts
- add icons (for peripheral and for close button)
- add string localization
- add custom styling for different types of alerts (i.e., error, success, etc)

**Comment by evhan55** [comment]
Progress continue via PRs https://github.com/LLK/scratch-gui/pull/3209 and https://github.com/LLK/scratch-vm/pull/1607.

Still to do in further PR's:
- hook up a Reconnect button to enable reconnecting to a disconnected peripheral
- add string localization (i.e. `formatMessage` compatible)
- add an API for different types of alerts? (e.g. `this._runtime.emitPeripheralError(this._extensionId)`)
- add custom styling for different types of alerts

**Comment by evhan55** [comment]
Some styling notes from @kathymakes:

- the x has an icon that we can use instead of a typed "x"
- the dropshadow should be 0 y offset and 0 blur, and some amount of spread... maybe 4 px?

**Comment by kathymakes** [comment]
Thanks @evhan55 !
Here's the "X" icon, which is the same svg "X" we use for modals.

> **[X Icon.svg.zip](https://github.com/LLK/scratch-gui/files/2425840/X.Icon.svg.zip)**

**Comment by evhan55** [comment]
Thanks very much @kathymakes !

**Comment by evhan55** [comment]
@kathymakes do you know if the orange close icon appears elsewhere in the GUI already?

Also, does this border work for you:

<img width="475" alt="screen shot 2018-09-28 at 2 01 16 pm" src="https://user-images.githubusercontent.com/699840/46225389-07fd9400-c327-11e8-842e-5ecbf3343bc7.png">

**Comment by kathymakes** [comment]
@evhan55 Yeah, border looks good! :) 

Hm, we do have an existing "X" in all of our modal windows... 
It's contained in a circle like this:

<img width = "300" src = "https://user-images.githubusercontent.com/8203939/46292519-22ba4d80-c55f-11e8-9cce-f4a47b4ab14b.png">

I checked our components and the two "X"s **appear to be** the same... although they look different in screencaps. For reference, the "X" in the modal is 12px by 12 px.

I'm thinking it might be good to make them the same, for consistency. Do you think we could try styling it with the same circle as in the modal? 

These sketches have a 28x28 circle with orange at 20% opacity.

<img width = "500" src = "https://user-images.githubusercontent.com/8203939/46292632-63b26200-c55f-11e8-8255-8dd204a816a4.png">

**Comment by kathymakes** [comment]
@evhan55 
I'm thinking it might also be good to style the "X"s same as the modal, for consistency.

Do you think we could try it with the circle?
These sketches have a 28x28 circle with orange at 20% opacity.

<img width = "500" src = "https://user-images.githubusercontent.com/8203939/46292632-63b26200-c55f-11e8-8255-8dd204a816a4.png">

**Comment by evhan55** [comment]
@kathymakes Sure thing!  Circle for consistency sounds good.
@rschamp , is it cool for me to make changes to [CloseButton](https://github.com/LLK/scratch-gui/blob/develop/src/components/close-button/close-button.jsx) and it's [CSS](https://github.com/LLK/scratch-gui/blob/develop/src/components/close-button/close-button.css) to add an orange mode?

**Comment by evhan55** [comment]
@kathymakes How is this?  When you hover over the x button, it grows the same way it grows on other close buttons:

<img width="497" alt="screen shot 2018-10-02 at 7 31 35 pm" src="https://user-images.githubusercontent.com/699840/46382613-d9125580-c679-11e8-9a60-b7d0ed33f1e5.png">

**Comment by kathymakes** [comment]
@evhan55 Ah so sorry I never saw your message, it got lost in my notifications! Yeah, that sounds good for consistency - and it's looking really nice

**Comment by evhan55** [comment]
Unassigned myself as @benjiwheeler is taking over the generalized alerts system now

**Comment by benjiwheeler** [comment]
Closing because these are implemented in code; next, they need to have their CSS brought into line with this spec.
