### ISSUE TITLE
Yellow outline around multiple blocks not showing

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#2967]
### Expected Behavior
All blocks should show a yellow outline to indicate what code is being run when the green flag is clicked

### Actual Behavior
The following blocks do not show a yellow outline. There are probably others that are missing from this list. When flag clicked +

- Think for seconds
- Play sound until done
- Change pitch effect by
- Change pitch effect to 
- Change volume by
- Set volume to
- Wait
- Wait until
- Stop all
- Ask and wait

<img width="863" alt="screen shot 2018-08-23 at 12 50 21 pm" src="https://user-images.githubusercontent.com/3812168/44539835-25f62a00-a6d3-11e8-900e-aba8905a54cf.png">

### Steps to Reproduce

1. Add a "when flag clicked" block
2. Attach one of the blocks above
3. Click the green flag on the stage
4. Notice that a yellow outline DOES NOT show

### Operating System and Browser
Chrome 68, macOS High Sierra

**Comment by kchadha** [comment]
@techwonder21 Are you currently seeing this issue on https://llk.github.io/scratch-gui/develop?

I just briefly tested the stack you had in the top right of the screenshot it worked for me:

![image](https://user-images.githubusercontent.com/1786240/44542929-34950f00-a6dc-11e8-8600-a56a086ac9ec.png)

**Comment by techwonder21** [comment]
No; only on the beta website.

**Comment by thisandagain** [comment]
@techwonder21 When we close an issue that means that it should be resolved on `develop` during the next release. We did release to `master` (beta.scratch.mit.edu) this morning however. Can you please try again?

**Comment by techwonder21** [comment]
That makes perfect sense. The issue is now resolved on beta :)
