### ISSUE TITLE
Projects that don't lag in 2.0 sometimes lag in 3.0

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#2971]
### Expected Behavior

All projects should work well in both versions.

### Actual Behavior

Projects like the one at https://llk.github.io/scratch-gui/develop/#240227214 (Scratch 3.0 link) lag so much, it can't carry out all tasks.

### Steps to Reproduce

Open https://llk.github.io/scratch-gui/develop/#240227214.
Start the project.

### Operating System and Browser

Chrome on Windows

**Comment by thisandagain** [comment]
This is too vague for Github. We are handling performance issues on a case-by-case basis and addressing each.
