### ISSUE TITLE
Going directly to a beta.../#projectid url should not show "Welcome to 3.0" modal

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#2981]
### Expected Behavior

Click on a link like https://beta.scratch.mit.edu/#239284997 . The beta site should load and let you begin editing; or perhaps it should show a version of the modal that gives a single "Try It!" option.

### Actual Behavior

You are presented with the "Welcome to 3.0" modal and its "Not Now" and "View 2.0 Project" options, which is confusing.

**Comment by carljbowman** [comment]
This sounds great! Let's make it so that the intro modal should not show if you are visiting URL with a project id already appended to the URL.
