### ISSUE TITLE
CrashMessageComponent text is not localized

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#2984]
### Expected Behavior

_Please describe what should happen_
People should be able to translate the 'Oops...' message

### Actual Behavior

The text is a literal in the jsx instead of translated text. Initially the crash message was outside the IntlProvider context, so it could not be translated. At this point it should be possible to include react-intl and use FormatMessage.

### Steps to Reproduce

Set the browser locale, and do something that will cause an error. ;)

**Comment by Wgil** [comment]
Hello,

This is my first collaboration to the Scratch project :)

**Comment by apple502j** [comment]
you can close it now

**Comment by chrisgarrity** [comment]
Thanks @Wgil
