### ISSUE TITLE
Adding reporter to block and then switching to costume or sound tab and back causes crash

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#2991]
### Expected Behavior

It doesn't crash

### Actual Behavior

It crashes

### Steps to Reproduce

1. Drag out any block with an input
2. Drag a reporter into the input
3. Switch to costumes or sounds tab
4. Switch back to code tab - crash message

### Operating System and Browser

Windows 10 Chrome 68.0.3440.106
![ezgif com-optimize](https://user-images.githubusercontent.com/31634240/44628827-ab691c80-a915-11e8-86ad-a866f7808ab9.gif)

**Comment by towerofnix** [comment]
Yikes. I can't repro this on Firefox 62.0b20/Linux, though (on develop). Are there any errors in your console when this happens?

**Comment by ScratchDiogoh** [comment]
https://github.com/LLK/scratch-vm/issues/1496
Duplicate

**Comment by kyleplo** [comment]
@towerofnix Yes, two errors:
![image](https://user-images.githubusercontent.com/31634240/44629933-57196900-a924-11e8-94bb-0e929ce7ec8e.png)
and
![image](https://user-images.githubusercontent.com/31634240/44629938-6d272980-a924-11e8-98c2-6d660b904b73.png)


Also, I can't repro on develop but I can on master

**Comment by towerofnix** [comment]
@kyleplo As a rule of thumb, if you can repro on master but not develop, it means they recently fixed the issue - which indeed they did, in https://github.com/LLK/scratch-blocks/pull/1698, which was merged just four days ago (so it's not in master yet).
