### ISSUE TITLE
Sprite Info Area and Background selector have different colored borders

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#3009]
### Current Overview
The unselected state of the Background selector has a different border color than Sprite Info Area.
![image15](https://user-images.githubusercontent.com/1088291/44282093-e9848300-a227-11e8-9000-78c6a4570e7d.png)

These should be the same color. We use a 15% transparent black for our borders, both element uses the correct HSLA... The problem looks to be with how we are setting `box-sizing`.

In the case of the Sprite Info Area the boarder is on the outside of the element, such that the transparent black is appearing over the cool gray background color.

In the case of the Background selector the border is on the inside of the element, so rather than appearing with the cool gray background, it appears over the white.

### Next Steps
Ideally the `box-sizing` positioning of the border on each of these elements should be the same. As far as which is correct, Sprite Info Area appears as it should. The Background selector's border should appear as it does on the Sprite Info Area.

That said, `border-box` has been rather troublesome, so we should be open to alternative solutions.

**Comment by LiFaytheGoblin** [comment]
It might have to do with background-clipping.

**Comment by LiFaytheGoblin** [comment]
Sprites info box border is displayed this way because it's background is hsla(215, 75%, 95%, 1). The stage info box background is white.

**Comment by LiFaytheGoblin** [comment]
Setting .stage-selector {
    background-clip:padding-box; } solves the problem
