### ISSUE TITLE
many directions (excluding 90º, 180º, -90º and 0º) are of bad quality

### ISSUE THREAD

**Issue by ScratchDiogoh** [LLK/scratch-gui#3012]
### Expected Behavior

"tilted" directions are of good quality
### Actual Behavior

"tilted" directions are of bad quality
### Steps to Reproduce
choose some direction (excluding 90º, 180º, 0º and -90º)
### Operating System and Browser

Windows 10, Googe Chorme 68

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-render/issues/334

**Comment by towerofnix** [comment]
Fixed by LLK/scratch-render#385.
