### ISSUE TITLE
Thermometer Menu only shows tooltip on the first time you select a tool on ipad

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3017]
### Expected Behavior

If you click an option in the thermometer menu it shows you a tooltip

### Actual Behavior

After the first time you choose an option, i.e. upload a sprite, paint a new sprite, or surprise sprite it will bring up a tool tip describing that tool.  Then if you select it again it causes an action to happen.  (As expected).  However if you choose it again it will not bring up the tool tip.

If the option brings up a modal, such as the choose sprite from library, it WILL bring up the tool tip the next time.

### Steps to Reproduce

Open a new project
Tap on the new sprite button
Tap on the Surprise Sprite option
Note: It brings up the tool tip
Tap the Surprise Sprite option again
Note the thermometer closes
Tap on the New Sprite button again
Tap on the Surprise Sprite button again
Note: It adds a new sprite without giving a tool tip

### Operating System and Browser

Safari on iPad

**Comment by thisandagain** [comment]
Related to https://github.com/LLK/scratch-gui/issues/3018

**Comment by picklesrus** [comment]
Consolidating into https://github.com/LLK/scratch-gui/issues/2720 since there are a handful of these filed in various forms.
