### ISSUE TITLE
Tapping an item in the thermometer menu should bring up a tool tip on Android

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3018]
### Expected Behavior

Tapping an option in the thermometer menu should show you the name of the tool and not choose the option until you tap it again.

### Actual Behavior

It does not show you the tool tip and instead selects the option on the first tap.

### Steps to Reproduce

Tap the new sprite button
Tap Surprise Sprite
Note: No tool tip appears and a new sprite is created.

### Operating System and Browser

Chrome on Android

This is NOT an issue on ipad (ios)

**Comment by picklesrus** [comment]
There are quite a few of these issues filed in various forms. Consolidating into  https://github.com/LLK/scratch-gui/issues/2720
