### ISSUE TITLE
Edge on touch device, tapping a thermometer menu selects it a second time

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3025]
### Expected Behavior

If you tap an action menu (new sprite, new costume, new backdrop, new sound) it should open the thermometer menu and not select anything else until you tap it.

### Actual Behavior

After a few seconds, it will select the choose from library option as if you had tapped it in the same place a second time.  

### Steps to Reproduce

Open a new project in Edge on a touch windows device
Tap the new sprite button
The thermometer menu should open
Wait a few seconds
Note: It opens the library

You don't see these results on Chrome

### Operating System and Browser

Windows (touch) on Edge

**Comment by picklesrus** [comment]
Consolidating into https://github.com/LLK/scratch-gui/issues/2720
