### ISSUE TITLE
Use messaging system for save state confirmation

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#3035]
Somewhat a duplicate of https://github.com/LLK/scratch-gui/issues/2811

Follow up for https://github.com/LLK/scratch-gui/pull/3021#discussion_r213715593

Use the messaging components needed for showing hardware status changes in order to show the save status (in progress, completed, errored)

**Comment by kyleplo** [comment]
I think it should only show when errored, because it would be annoying if every time it autosaves, a message pops up.

**Comment by benjiwheeler** [comment]
This was basically closed by https://github.com/LLK/scratch-gui/pull/3638 .

The only non-closed aspect is the display of errors, which is tracked in https://github.com/LLK/scratch-gui/issues/3324 .

@kyleplo , you're right! So per https://github.com/LLK/scratch-gui/pull/3638 , auto-saves are not using the alert system.
