### ISSUE TITLE
In RTL, dragging asset tiles is broken

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#3041]
### Expected Behavior

While dragging an asset tile (to re-order sprites, costumes or sounds), I should see the tile being dragged, and the insertion marker should appear correctly.

### Actual Behavior

In RTL, the the sprite, costume or sound tile being dragged is not visible.

Also, when dragging a sprite tile, the insertion marker appears in an unexpected place (looks like the order is reversed?):

![sprite-tile-dragging-rtl](https://user-images.githubusercontent.com/567844/44869669-29059300-ac5c-11e8-8e96-78de6499c9a2.gif)

### Steps to Reproduce

- Open GUI in RTL mode (e.g. https://llk.github.io/scratch-gui/develop/?lang=he)
- Add several sprites
- Try dragging them around

**Comment by thisandagain** [comment]
@chrisgarrity This one would be good to look at over the next couple months.

**Comment by fsih** [comment]
![dragging rtl](https://user-images.githubusercontent.com/2855464/83159998-a3cf3c80-a0d4-11ea-9430-5691fb8d321a.gif)

**Comment by ericrosenbaum** [comment]
Sprite re-ordering was fixed by https://github.com/LLK/scratch-gui/pull/6021, so I've opened a new issue just for the invisible tiles: https://github.com/LLK/scratch-gui/issues/6104
