### ISSUE TITLE
Some default block input strings are not translated

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#3042]
### Expected Behavior

All default block input strings should be translated.

### Actual Behavior

In Hebrew, we see the English default strings for these blocks:

- ask
- join
- letter of
- length of
- contains

**Comment by thisandagain** [comment]
@chrisgarrity Is this general or just an issue with some missing strings? If the later I recommend we close this as it is tracked in Transifex.

**Comment by chrisgarrity** [comment]
@thisandagain this is general - they're not translated for languages other than Hebrew as well. I'm pretty sure we actually have the strings in Transifex, so they're just not getting used correctly.

**Comment by chrisgarrity** [comment]
Looks like it may have been a delay between fixing the bug and getting translations. Closing because it's working now.
