### ISSUE TITLE
Gui should set lang attribute for accessibility

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#3049]
### Expected Behavior

_Please describe what should happen_
When we set the gui locale, we should also update the lang attribute to indicate the default language of the page.
```
document.documentElement.lang = ...;
```

It should definitely be done for GUI standalone. It may need some work for everyone to play nice when gui is embedded in www.

**Comment by LiFaytheGoblin** [comment]
I did something that sets the lang attribute in GUI and it does work in standalone and www but...
1) I am not sure if it's actually a stylistically good place to manipulate the attribute. 
2) The lang from www does not get imported into gui, so if you changed to german in www and see inside a project from the preview page, it defaults to english. It seems like the initial state of the language is always set to english, maybe this should first check if it received a prop that could be passed by www and take that if available?

I am going to push my branch to my fork and maybe you could take a look @chrisgarrity

**Comment by LiFaytheGoblin** [comment]
https://github.com/LiFaytheGoblin/scratch-gui/tree/3049/set-lang-attribute Here is the branch

**Comment by chrisgarrity** [comment]
@LiFaytheGoblin GUI doesn't yet accept a locale prop from www, but eventually it will. There's just more to be done in terms of making the www and gui localization compatible. Having the document attribute set in the render seems a bit odd.  It might be better to set it in the constructor and in the change handler.
