### ISSUE TITLE
Page taller than screen

### ISSUE THREAD

**Issue by MasterOfTheTiger** [LLK/scratch-gui#3074]
### Expected Behavior

The page should have the maximum height of the screen. Thus, it should not be taller than the screen. 

### Actual Behavior

The page is taller than the screen whenever the available space is less than 640px.

![peek 2018-09-05 15-35 2](https://user-images.githubusercontent.com/16640496/45125123-ee9b6a80-b121-11e8-9336-4b1efc5262ef.gif)

### Steps to Reproduce

1. Resize the browser window to less than 640px high
2. Click "try it"
3. See the scrollbar

### Operating System and Browser

Fedora GNU/Linux 28, Chrome and Firefox.

### Other information
I was able to get it working fine by modifying  the "max-height" attribute under .app in the playground/index.css file. Here is what it looks like:
```
.app {
    /* probably unecessary, transitional until layout is refactored */
    width: 100%;
    height: 100%;
    margin: 0;

    /* Setting min height/width makes the UI scroll below those sizes */
    min-width: 1024px;
    min-height: 640px; /* Min height to fit sprite/backdrop button */
}
```
When it is changed to less than 640px, the player works fine. Except for the following:
![screenshot from 2018-09-05 15-44-03](https://user-images.githubusercontent.com/16640496/45125259-9d3fab00-b122-11e8-85ef-0e78333e3b40.png)
The buttons are not aligned.

**Comment by thisandagain** [comment]
@MasterOfTheTiger It looks like your screen is smaller than our minimum height. What was the resolution of that window?

**Comment by MasterOfTheTiger** [comment]
Yes, you are right. I do not know the resolution right now (shortly less). However, it would be good to have the ability to have the editor adjust to even smaller screen sizes.

**Comment by MasterOfTheTiger** [comment]
Another issue was just opened that is better to track. It is very similar and I will close this in favor of #3708
