### ISSUE TITLE
Any drag started on the stage will pick up the first sprite it moves over

### ISSUE THREAD

**Issue by liam4** [LLK/scratch-gui#308]
### Expected Behavior

Sprites only get picked up (drag/drop) when a mouse drag starts on that sprite, as in Scratch 2.0.

### Actual Behavior

Any drag that is started anywhere on the stage picks up the first sprite the cursor moves over.

### Steps to Reproduce

Begin a drag (mouse down) on the stage, not above any sprite. Move the mouse (while mouse down) over a sprite. The sprite gets picked up (it follows the mouse until the mouse is released).

### Operating System and Browser

macOS 10.12.3, Chrome 57.0.2987.133.

**Comment by thisandagain** [comment]
Great catch! Thanks @liam4
