### ISSUE TITLE
Unable to select multiple costumes at once in 3.0

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#3083]
### Expected Behavior
In 2.0, users can select multiple costumes at once in the Costume library
<img width="1651" alt="scratch 2 select multiple costumes" src="https://user-images.githubusercontent.com/3812168/45166716-a766b580-b1c5-11e8-88bc-6ac3372ae852.png">

### Actual Behavior
In 3.0, users cannot select multiple costumes at once in the Costume library

### Steps to Reproduce
1. Go to beta website
2. Open up the costume library
3. Try to select multiple costumes by holding down the Shift key
4. Notice you're unable too.

### Operating System and Browser
Chrome 69, macOS High Sierra

**Comment by techwonder21** [comment]
@ChampikaF

**Comment by techwonder21** [comment]
@thisandagain looks like this bug was already filed back in 2017 a few times. Do you have an ETA on the fix?

https://github.com/LLK/scratch-gui/issues/1248
https://github.com/LLK/scratch-gui/issues/867

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/867

**Comment by pugsforlifebruh12** [comment]
That version of chrome,
Nice,
