### ISSUE TITLE
"When key pressed" block doesn't run when variable slider is also being used

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#3084]
### Expected Behavior
Once the project starts, key press events should execute at all times. 

### Actual Behavior
Right now, the "when key pressed" event only works BEFORE the variable slider is changed to a new value. Once the slider changes to a new value, the "when key pressed" block no longer works.

### Steps to Reproduce
1. Open project in 3.0: https://beta.scratch.mit.edu/#19152054
2. Click the green flag
3. Press the spacebar
4. Change the variable slider to a different value
5. Press the spacebar (again)
6. Notice the code does not execute

### Operating System and Browser
Chrome 69, macOS High Sierra

**Comment by techwonder21** [comment]
@ChampikaF

**Comment by techwonder21** [comment]
@thisandagain

**Comment by Mr-Dave2** [comment]
![db09f2b9-0154-45c2-8120-b3fb88c02a8c](https://user-images.githubusercontent.com/35544966/46049863-7d365280-c0f6-11e8-814c-2ac533e2e8df.gif)

Just wanted to add another observation.  The slider, after it was used, became selected when the “a” key was pressed.  The “a” key was able to be used again after I clicked on the orange part of the watcher display.

Running scratch 3.0 on a Linux system. Chromium 69.0.3497.81

My program, which is a test case for several monitor issues is here: 
https://preview.scratch.mit.edu/#243934645

**Comment by apple502j** [comment]
Duplicate of #2796

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/2796
