### ISSUE TITLE
Tap leaves the "mouse" where you last tapped until you tap somewhere else

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3085]
I expect the mouse position to not remain where I tapped on the stage for the purposes of `distance to mouse pointer` blocks.  I'm not sure if I'm right, but currently the "mouse" stays where you last tapped until you tap somewhere else.

### Steps to Reproduce

Build the following stack on a sprite:
![screen shot 2018-09-06 at 11 43 30 am](https://user-images.githubusercontent.com/1088291/45168794-2362fc80-b1ca-11e8-8d3e-10235882ede9.png)
tap the sprite
Note: it pixelates even if you have moved your finger off of it.
Tap somewhere that isn't the sprite
Note: it stops pixelating

### Operating System and Browser

Safari on ipad

**Comment by picklesrus** [comment]
I think this is the same underlying issue as https://github.com/LLK/scratch-vm/issues/1265. Consolidating discussion to the other issue.
