### ISSUE TITLE
Re-uploading project doesn't persist which variables are shown

### ISSUE THREAD

**Issue by brianyu28** [LLK/scratch-gui#3103]
### Expected Behavior

If a user enables the checkbox next to a variable so that the variable's value is shown on stage, and then downloads and re-uploads their project, the variable should still be visible on stage. This is the way Scratch 2 currently behaves.

### Actual Behavior

In Scratch 3, after re-uploading the project, the variable is no longer visible on stage.

### Steps to Reproduce

1. Create a new Scratch 3 project
2. Click "Variables"
3. Check "my variable" (Notice that "my variable" is now visible on the stage)
4. File -> Download to your computer
5. File -> Upload to your computer (choose the same file)

Notice that now, "my variable" is no longer visible on stage.

### Operating System and Browser

macOS 10.13.6 with Google Chrome 69.0.3497.81

cc @dmalan

**Comment by joker314** [comment]
Thanks for reporting -- and sorry that this is happening.

Possibly tracking in:
https://github.com/LLK/scratch-gui/issues/3086#issuecomment-419239642

> a known issue about the monitors since no information about monitors is saved. That work is upcoming, I believe.

**Comment by chexbox** [comment]
#2398

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/3086
