### ISSUE TITLE
Ability to flip characters horizontally or vertically missing from 3.0

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#3131]
### Expected Behavior
Two characters/sprites should be able to face each other in Scratch when having a conversation

### Actual Behavior
Inability to add a character sprite and have it face different directions (horizontally or vertically like in 2.0
![t8qsrjq34jq](https://user-images.githubusercontent.com/3812168/45505704-46a62280-b75b-11e8-98eb-b065ed7f0918.png)

### Steps to Reproduce
1. Open 3.0
2. Add 2 characters
3. Try to have 1 character face another character
4. Notice flip feature is missing entirely

### Operating System and Browser

Chrome 69 macOS High Sierra

**Comment by towerofnix** [comment]
The options are there for me:

!["Flip Horizontal" / "Flip Vertical" buttons](https://user-images.githubusercontent.com/9948030/45505881-2b8be080-b764-11e8-86ae-716307f622ad.png)

The problem is that you have the paintbrush tool selected. Change to the cursor and those options will be there.

**Comment by techwonder21** [comment]
Thanks for the explanation. This works for me. Feel free to resolve.
