### ISSUE TITLE
Translations for extensions-provided messages

### ISSUE THREAD

**Issue by cor3ntin** [LLK/scratch-gui#3139]
`src/examples/extensions/example-extension.js` mention the `translation_map` and `intlDefineMessage` facilities to define extensions provided localized messages. 
However, I found no references to either of these symbols anywhere else.

Are they supposed to work? Otherwise, do you plan to implement them at some point? What would be the recommended way to plug an extension into react-intl in the meantime?

Thanks!

**Comment by cwillisf** [comment]
Right now these only work for "internal" extensions -- those written by the team and included in the `scratch-vm` repository. If this is what you're doing, maybe in a fork of the `scratch-vm` repository, then you can find examples in the `src/extensions/` directory. Look for calls to `formatMessage(...)`.

Some time in 2019 we'll be building out the rest of our support for extensions that aren't built into `scratch-vm`, and part of that work is adding the necessary runtime localization support. If this is what you're doing, I would recommend supporting only one language for now. You could attempt to handle localization within your extension but you may have difficulty matching your extension's language to that used by the rest of Scratch.

**Comment by chrisgarrity** [comment]
Also, referencing the comment about scratch-l10n repo in https://github.com/Mobsya/scratch-vm/issues/1. If you're in a fork of scratch-vm, you definitely don't need the l10n repo. It's a convenience for us to combine messages from all our repos (vm, paint, gui...). You could extract and sync your translations with whatever service you use.

But if your goal is to work as a 3rd-party (non-internal) extension in Scratch, then I'd echo @cwillisf and recommend waiting for us to build the rest of the localization support.

**Comment by hyansuper** [comment]
I add a few lines of translations for my own extension in scratch-l10n. but it don't work.

I also change files of 'scratch-l10n/locales/extensions-msgs.js' and 'scratch-l10n/editor/extensions/en.json', directly edit the locale of built-in extension. but when I npm start scratch-gui, the ui does not reflect my change, why is that?

**Comment by chrisgarrity** [comment]
@hyansuper scratch-gui will automatically build using the released scratch-l10n unless you `npm link` to your local instance of scratch-l10n. Extension translations are handled in scratch-vm. Like scratch-gui scratch-vm will always use the released scratch-l10n unless you link to the local copy. Hope that helps.
