### ISSUE TITLE
Gradients are incorrect when importing 2.0 projects

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#3147]
### Expected Behavior
All images are equal

### Actual Behavior
Scratch 2.0:
![](https://i.gyazo.com/a054b0d457a24d1a9baf1d85bfddb84a.png)
3.0:
![](https://screenshotscdn.firefoxusercontent.com/images/581c75dc-dd9b-48a3-ba0c-816e7aa5505e.png)

### Steps to Reproduce
1. Open https://scratch.mit.edu/projects/246547916/ and https://llk.github.io/scratch-gui/develop/#246547916
2. See stage

### Operating System and Browser
Windows 7 Home Premium 64bit SP1
Firefox 62

**Comment by LiFaytheGoblin** [comment]
Related https://github.com/LLK/scratch-gui/issues/1974 and maybe https://github.com/LLK/scratch-gui/issues/2866

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-render/issues/236
