### ISSUE TITLE
Add method for getting a snapshot of the stage

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#3166]
We need a way to get project thumbnails when we save the project to the project server.

**Comment by wooden1985** [comment]
this.props.vm.runtime.renderer.draw();
        let canvas = this.props.vm.runtime.renderer._gl.canvas;
        canvas.toBlob(function(blob){
            
           

        });

**Comment by zhu-xb** [comment]
I use  `this.props.vm.runtime.renderer._gl.canvas;` to snapscreen。but `canvas.toDataURL()` why is black screen？

**Comment by paulkaplan** [comment]
There is now a way to do this, see https://github.com/LLK/scratch-gui/blob/ab31d36251e21fd78aac34983ede6a75e9f1ff71/src/lib/project-saver-hoc.jsx#L66
