### ISSUE TITLE
Passing negative or non-numeric tutorial id causes error

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#3167]
### Expected Behavior

The GUI loads as normal, with no error or tutorial

### Actual Behavior

The GUI never loads, and there are errors in the console.

### Steps to Reproduce

Visit https://llk.github.io/scratch-gui/smoke/?tutorial=-1 or https://llk.github.io/scratch-gui/smoke/?tutorial=waffles

### Operating System and Browser

Windows 10 Chrome 69

**Comment by joker314** [comment]
Introduced in #3153

#### Why this is happening

https://github.com/LLK/scratch-gui/blob/b1d133a54dfb960a4e1a8f3be20dc1773a29f861/src/lib/tutorial-from-url.js#L38

The regular expression is `null`, so it does `null[1]`. This is an error.

#### How the protections are failing
https://github.com/LLK/scratch-gui/blob/b1d133a54dfb960a4e1a8f3be20dc1773a29f861/src/lib/tutorial-from-url.js#L37

This is designed to stop the regular expression from becoming `null`.

To cause an error, the querystring must:
- contain `tutorial=`
- but not have a number directly after `tutorial=`

Therefore, these URLs also crash:
- ?tutorial=
- ?tutorial=nonnumeric

#### How to fix
The check in the `if` must match the regular expression perfectly.

The best way to do this is probably:

```javascript
const urlTutorialIdString = window.location.search.match(/(?:tutorial)=(\d+)/);
if(urlTutorialString) {
  const urlTutorialId = urlTutorialIdString[1]
  // do things
}
```

#### Are any other pieces of code affected?
Yes, the `locale` querystring is parsed in a similar pattern:
https://github.com/LLK/scratch-gui/blob/f2f0496013bfed302589fe5dc9675a7ec623beda/src/lib/detect-locale.js#L26-L28

Hence, placing a character which does not match either `\w` or `-` will crash. The easiest way to do this is to leave it blank:

- https://llk.github.io/scratch-gui/develop/?locale=

As a side note, it might be reasonable to create a utility to parse querystrings, things it's now being done in two places, and possibly more in future?
