### ISSUE TITLE
Add data and more blocks panels

### ISSUE THREAD

**Issue by CatsAreFluffy** [LLK/scratch-gui#317]
To make testing those easier.

**Comment by rschamp** [comment]
These categories will come in as we implement the features underlying them, variables, lists, and custom procedures. Those features have been captured elsewhere.

**Comment by CatsAreFluffy** [comment]
I'm fairly certain that custom blocks already work...

**Comment by rschamp** [comment]
You're right that the VM can run existing custom blocks, but the blocks themselves render strangely, and we haven't built the interface for creating them yet.
