### ISSUE TITLE
Can't resize comments on Firefox

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#3194]
### Expected Behavior

You should be able to resize variables on Firefox.

### Actual Behavior

You can't, and the drag cursor doesn't even appear!

I also noticed that, while moving the mouse over a *workspace* comment, the cursor would show the "grab" cursor along all the edges (and the text cursor on the inside). On a *block* comment, the cursor is a little finnicky, showing the grab cursor but only within a pixel or two from the edges, whereas the workspace comment had at least a few more pixels of space where the cursor would be the grab one.

### Steps to Reproduce

1. Create a comment - the issue happens for both workspace and block comments.
2. Try to resize it by dragging at the bottom right corner of the comment.

### Operating System and Browser

Firefox 63.0b7, Debian.

**Comment by dgnball** [comment]
This is a problem with LLK/scratch-blocks, which you can re-create by opening the tests/vertical_playground.html file in FF. Looks like a good starting point would be core/workspace_comment_svg.js.

**Comment by dgnball** [comment]
So there's a function in core/workspace_comment_svg.js called addResizeDom_ that creates this icon:
![image](https://user-images.githubusercontent.com/6998018/47186637-1db01900-d329-11e8-8abc-67739dfda7ff.png)
This appears in Chrome and Safari and not FF. Not sure if this a z-index thing but the CSS for this is:
```css
  '.blocklyResizeSE {',
    'cursor: se-resize;',
    'fill: #aaa;',
  '}'
```

**Comment by towerofnix** [comment]
I can't repro this in Firefox anymore. The actual resize handle is still pretty small, but it's definitely there. Its size is a separate issue (and applies to all browsers, not just Firefox).
