### ISSUE TITLE
Plans for extent of 3rd party extension support?

### ISSUE THREAD

**Issue by PullJosh** [LLK/scratch-gui#3202]
I've recently taken an interest in creating extensions for Scratch 3.0. Most of the default extensions are very powerful, interacting with relatively low-level areas of Scratch.

However, upon further investigation, it seems that most of the true functionality of these extensions is built into the base of Scratch itself. For instance, the video and pen layers are already defined in `scratch-vm/src/engine/stage-layering.js`. A 3rd-party extension could not achieve the same effect because it can't create its own layers. Similarly, the matrix input for the mico:bit extension (which is very cool!) is already built-in to Scratch, although it seems to be specifically tailored for a single use case.

My question is this: **Are there plans to allow 3rd parties to implement extensions of the same caliber as the defaults, or will Scratch-team-created extensions continue to have extra privileges?**

I ask this not out of frustration with the current system (which is already fantastic), but out of excitement for a potential future. Opening the doors to allow outside developers to interact heavily with the Scratch system could allow some beautiful tools and toys to be created.

**Comment by thisandagain** [comment]
It is likely that "official" and "core" extensions will have access to parts of the VM that will not be available to "unofficial" or "experimental" extensions which will likely be run in a sandboxed environment for security. That said, we are also really excited about the possibilities here and are still discussing what features these extensions will have access to. Stay tuned and expect more information next year! :-)
