### ISSUE TITLE
How to load stage by .sb file?

### ISSUE THREAD

**Issue by zhouzh11** [LLK/scratch-gui#3203]
How to load stage by .sb file?

**Comment by apple502j** [comment]
Scratch 1.4 files are not supported yet.

**Comment by towerofnix** [comment]
Yes, 1.4 projects won't open yet. See LLK/scratch-vm#128. The Scratch Team has said they are definitely working on supporting 1.4 projects before the release of Scratch 3.0, though.

**Comment by thisandagain** [comment]
Tracking in LLK/scratch-vm#128
