### ISSUE TITLE
Inputs in blocks don't lose focus on click on stage

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3207]
### Expected Behavior

After typing in an input, when I click on the stage, I expect the input to lose focus.

### Actual Behavior

Input keeps focus!!!??

![focus](https://user-images.githubusercontent.com/3431616/45906473-3678ed80-bdc2-11e8-8e1c-f143418284e7.gif)

**Comment by picklesrus** [comment]
Whoops, Somehow I missed this bug. No. I don't think it will break the android soft-keyboard fix. I think we should call Blockly.hideChaff when someone clicks on the stage. Given that clicking on other non-blocks/workspace things (e.g. sprite info panel, costume tab) seems to drop focus on the field, I think we just need to mimic that and hideChaff should do the trick.

**Comment by fsih** [comment]
Very impressed with the captioning

**Comment by picklesrus** [comment]
@paulkaplan you were right. 

This is the result of a preventDefault on the stage. In particular, this one: https://github.com/LLK/scratch-gui/blob/develop/src/containers/stage.jsx#L255
Removing it certainly fixes this particular bug, but I can't say that I understand the consequences of doing so.  It was put there in https://github.com/LLK/scratch-gui/commit/63ad6983b3ef8a5b83693fd1d156b13142afcf74 which does mention touch events...

Another option would be to call Blockly.hideChaff() in that mouse down (that would close dropdowns and context menus too). I do see a call to ScratchBlocks.hideChaff here https://github.com/LLK/scratch-gui/blob/develop/src/containers/blocks.jsx#L134 so sounds like it happens... but not nearly as much as I thought it would.

Any thoughts?
