### ISSUE TITLE
bitmaps in vector form cause projects to run slowly when open in paint editor

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3235]
### Expected Behavior

Projects should run quickly all of the time.

### Actual Behavior

With a project running, if you open the paint editor and select a costume that has been converted from bitmap to vector in a scratch 2.0 project, the project will slow down tremendously.  

### Steps to Reproduce

I'm still working on repro steps to make a project that has this effect.  There are two projects that I know of that have this behavior already.  [Space Giraffe](https://llk.github.io/scratch-gui/develop/#247578672) (here it is in [2.0](https://scratch.mit.edu/projects/247578672/#editor))and [Geometry Dash](https://llk.github.io/scratch-gui/develop/#105500895) (here it is in [2.0](https://scratch.mit.edu/projects/105500895/#editor))

Load one of the above projects
Click the green flag
Open the Paint Editor
Select a the "background" sprite in Geometry Dash or the "cover" sprite in Space Giraffe
Note: the project runs incredibly slowly

### Operating System and Browser

Chrome on Mac

**Comment by fsih** [comment]
From Z:

The space giraffe gui issue relates to the paint wrapper being rerendered every game frame and part of updating it is re-decoding the svg from binary into utf8. Most of the time is that re-decoding. We can make a quick change to scratch-storage to use browser-implemented TextDecoder and TextEncoder. Some quick testing in Chrome shows the browser-implemented TextDecoder is 10x faster than the JS implemented TextDecoder.

Probably also want to change the gui, to relax re-rendering scratch-paint if it isn’t making changes when the vm is actively running.

https://github.com/LLK/scratch-storage/pull/44 (edited)
