### ISSUE TITLE
Should File->New warn user in beta/playground? 

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3243]
We are currently working on a feature to allow the user to choose File->New to create a new project.

When scratch-gui is embedded in the full website, this will mean auto-saving the current project before replacing it.

But in beta playground, users aren't currently able to log in, so we don't currently have the ability to save to a user's account.

Should we do something to prompt users to confirm, or download to their computer, before replacing their current work? 

And what should it look like? A standard modal? A popup warning message?

**Comment by chexbox** [comment]
Opening it in a new tab might work.

**Comment by thisandagain** [comment]
@benjiwheeler I would not want to enable this feature in the Beta (Playground) without some sort of prompt to ensure that users do not loose work.

**Comment by benjiwheeler** [comment]
Resolved in https://github.com/LLK/scratch-gui/pull/3303
