### ISSUE TITLE
Can not display monitors ???

### ISSUE THREAD

**Issue by maomao225** [LLK/scratch-gui#3247]
when the monitors can be available?

**Comment by maomao225** [comment]
// @todo consume from VM, but need to store until there are APIs to update vm

in  src/containers/monitor.jsx   line:34

**Comment by apple502j** [comment]
You can, can't you?
I can.

Which monitor?

**Comment by maomao225** [comment]
step1: check  block "x position" 
step2: save the project 
step3: open the project
you will find out that the block of "x position" has disappeared

**Comment by Mr-Dave2** [comment]
Based on your problem description perhaps a better title would be "Monitors do not retain show state when project is downloaded and uploaded".

**Comment by joker314** [comment]
Thanks for reporting. This issue is being tracked in #2398

**Comment by maomao225** [comment]
> Based on your problem description perhaps a better title would be "Monitors do not retain show state when project is downloaded and uploaded".

Thanks, english is not my mother tongue

**Comment by thisandagain** [comment]
Tracking in #2398
