### ISSUE TITLE
Monitor colors are sometimes confused

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#3248]
![monitor](https://user-images.githubusercontent.com/31377746/46210391-297c7100-c363-11e8-9fe7-17ec67822065.PNG)
They're both orange

**Comment by joker314** [comment]
If you have a sprite called 'Music', then both the music extension and variable monitors look the same. This can be a little confusing.

Would it be a good idea to make the music monitor pink, to match the native music monitors? (or at least distinct to the colour of variable monitors)?

In addition, to aid those who have difficulties differentiating colours, some other icon could show it's a music monitor, such as a musical note icon?
