### ISSUE TITLE
Make preview modal tooltips translatable by translators

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#3252]
Unfortunately the babel tool that automatically extracts localization messages only recognizes `defineMessages(...)` and `<FormattedMessage ... />`

Uses of `intl.formatMessage(...)` won't throw an error, but the string definition will not get extracted by the tool and therefore will not be available to be translated. For example:
https://github.com/LLK/scratch-gui/blob/2753c00a14e998fe30e2b0f2caa2568f64c8fc96/src/components/preview-modal/preview-modal.jsx#L55-L59

Instead we should move the message definition into a `defineMessages` call, and then call `intl.formatMessage` with the data from the messages object.

**Comment by apple502j** [comment]
I do!

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-gui/pull/3257
