### ISSUE TITLE
GIF import to multiple costumes/backdrops

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#3254]
When you choose a GIF as a new costume or backdrop, each frame should be imported as an individual backdrop or costume. They should be imported in the same sequence as the frames of the GIF.

**Comment by MasterOfTheTiger** [comment]
Isn't this the 2.0 behavior?

**Comment by Kenny2github** [comment]
@MasterOfTheTiger It is, but this hasn't yet been implemented in 3.0.

**Comment by carljbowman** [comment]
Tracking here https://github.com/LLK/scratch-gui/issues/3541

Links with issue pertaining to uploading multiple images.

**Comment by techwonder21** [comment]
I'm glad someone already filed this bug. The CS First HOC Activity "Gumball" relies on this feature heavily.

https://csfirst.withgoogle.com/c/cs-first/en/gumballs-coding-adventure/the-signal/introduction.html

@ChampikaF @rschamp @thisandagain
