### ISSUE TITLE
Blocks stop reacting to key press after adding an asset from one of the libraries.

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#3269]
### Expected Behavior

Running project with if key pressed being checked in a loop should continue responding to key press events when working in other parts of the editor.

### Actual Behavior

If you have a project running e.g. ‘if key pressed’ in a loop under the green flag clicked hat, and you add a backdrop, sprite, costume, or sound **using the library** (this step is very important), the project stops reacting to key presses until you switch back to the blocks tab. 

This is not the case w/adding a surprise backdrop for example.

**Comment by paulkaplan** [comment]
This appears to be another case of things like buttons/inputs having focus (buttons keep focus after they have been clicked) preventing keyboard events from making it to the VM.
