### ISSUE TITLE
Sound/costume scroller "fade" effect should not cover scrollbar

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#3278]
### Expected Behavior

The fade effect should be adjacent to the scrollbar; it should not actually cover it.

### Actual Behavior

The scrollbar covers it. This does not look good and causes difficulty as described below.

### Steps to Reproduce

Simply open the "Costumes" or "Sounds" tab while the scrollbar is visible. Note that the fade effect covers the scrollbar.

If there are a lot of items in the sidebar, the scrollbar handle can become very short and actually be *covered* by the fade effect. This makes it impossible to grab the scroll handle, and some other scrolling method must be used (e.g. keyboard, mouse wheel, or clicking elsewhere in the scroll bar - but the important part is that this is *not* how a user might usually scroll, and in that case is annoying).

Here is a screenshot of the scrollbar handle covered by the fade effect:

![The scrollbar handle, relatively short because the scroller has 110 sounds in it; entirely covered by the fade effect](https://user-images.githubusercontent.com/9948030/46321470-d18b7780-c5b9-11e8-8b3d-62f3b03e45ea.png)

### Operating System and Browser

Firefox 63.0b10, Linux. (The scrollbar is blackish because I'm using the Arc Dark theme.)

**Comment by benjiwheeler** [comment]
Thanks, I was able to reproduce this on Mac Chrome. We should definitely fix it.

**Comment by benjiwheeler** [comment]
Ran into this again... impossible to click on scrollbar. Should fix!

**Comment by towerofnix** [comment]
So, design question - do we want to have the scrollbar be positioned above the space the button takes up, ala this...

![a costume at the bottom of a scrolled-down costume list. the scrollbar's visual bottom edge is above the space behind the add-costume button](https://user-images.githubusercontent.com/9948030/64048836-47d98680-cb49-11e9-9c9f-b56c75aa08ff.png)

Or would we rather do something more like the scratch-blocks toolbox, adding padding to the end of the scrollable area?

The question is actually more a matter of this:

1) Separate scrollbar area and button area: this introduces a new visual border which the tiles are cut off at. The add button is never visually above any element (so the tile at the bottom of the scroll area is always easily selectable (provided at least a few pixels of it are visible from scrolling)).

2) Add padding to the bottom of (inside) the scrollable area: no new visual border, but the add button still always covers one tile—except, key point here, when you've scrolled to the very bottom. This allows you to access the last tile (hence resolves the issue).

I'd guess #2 is the direction we'd want to go (keeps it most similar to the current appearance), but I'd like input on which is wanted before fixing this!

/cc @benjiwheeler

(PS: I noticed you only labelled this help wanted / mini after running into it a second time... I know this naturally led you, one of the developers, to more closely consider the solution, but the fact is that it's been affecting other people - everyone really - for as long as 3.0's been released; and if it were labelled earlier, it likely would've been fixed much more quickly. This issue is from October, so it might've even been fixed before release!

Of course, this issue's date means what I'm suggesting may have been more of an issue back then, or this could've just coincidentally missed out, but still: maybe there are more issues, relatively small bugs—and features!—which haven't received the attention that would allow them to be fixed/implemented, benefiting not just the people who notice and comment on GitHub but everyone who uses Scratch? It seems to me it'd be worth it to consider issues a little more closely before letting them remain in the backlog of unlabelled issues for months (nearly a year, here) before they're recognized by an ST member and resolved, either by labeling them "help wanted" or having an ST dev implement it themselves—both resulting in effort that could've been put in by a community member as soon as they were given the go-ahead. Just thinking out loud about Scratch's 'way' of open source! Curious about your own thoughts.)

**Comment by thisandagain** [comment]
Thanks @towerofnix ! Let's go with option number two.
