### ISSUE TITLE
Sprite thumbnails don't load consistently

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#328]
### Expected Behavior

_Please describe what should happen_
All sprites should have a thumbnail when a project loads.

### Actual Behavior

_Describe what actually happens_
Sometimes sprites are missing their thumbnails, like this:
![image](https://cloud.githubusercontent.com/assets/1512021/25354208/212ff354-2900-11e7-9647-587ec0afa21d.png)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Clear your cache and load the default project at https://llk.github.io/scratch-gui/. Intermittently, the project will load without a thumbnail for Sprite1.

**Comment by paulkaplan** [comment]
@rschamp I can't repro this. Perhaps something in the last month fixed it? Can you double-check that this is still a problem?
