### ISSUE TITLE
Switching languages make Scratch crash

### ISSUE THREAD

**Issue by mbonani** [LLK/scratch-gui#3280]
### Expected Behavior

simply change language

### Actual Behavior

it crashes

### Steps to Reproduce

It is in a fork  https://github.com/Mobsya/scratch-gui 

gui Unhandled Error: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at DOMElementRenderer.render (http://localhost:8601/lib.min.js:297687:20)
    at finishClassComponent (http://localhost:8601/lib.min.js:85526:31)
    at updateClassComponent (http://localhost:8601/lib.min.js:85503:12)
    at beginWork (http://localhost:8601/lib.min.js:85878:16)
    at performUnitOfWork (http://localhost:8601/lib.min.js:87877:16)
    at workLoop (http://localhost:8601/lib.min.js:87941:26)
    at HTMLUnknownElement.callCallback (http://localhost:8601/lib.min.js:78195:14)
    at Object.invokeGuardedCallbackDev (http://localhost:8601/lib.min.js:78234:16)
    at invokeGuardedCallback (http://localhost:8601/lib.min.js:78091:27)
Component stack: 
    in DOMElementRenderer (created by StageComponent)
    in div (created by Box)
    in Box (created by StageComponent)
    in div (created by StageComponent)
    in StageComponent (created by Stage)
    in Stage (created by Connect(Stage))
    in Connect(Stage) (created by StageWrapperComponent)
    in div (created by Box)
    in Box (created by StageWrapperComponent)
    in div (created by Box)
    in Box (created by StageWrapperComponent)
    in StageWrapperComponent (created by StageWrapper)
    in StageWrapper (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in MediaQuery (created by GUIComponent)
    in GUIComponent (created by Connect(GUIComponent))
    in Connect(GUIComponent) (created by InjectIntl(Connect(GUIComponent)))
    in InjectIntl(Connect(GUIComponent)) (created by GUI)
    in GUI (created by Connect(GUI))
    in Connect(GUI) (created by VMListener)
    in VMListener (created by Connect(VMListener))
    in Connect(VMListener) (created by ProjectLoaderComponent)
    in ProjectLoaderComponent (created by Connect(ProjectLoaderComponent))
    in Connect(ProjectLoaderComponent) (created by InjectIntl(Connect(ProjectLoaderComponent)))
    in InjectIntl(Connect(ProjectLoaderComponent)) (created by ErrorBoundaryWrapper)
    in ErrorBoundary (created by Connect(ErrorBoundary))
    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)
    in ErrorBoundaryWrapper (created by TitledComponent)
    in TitledComponent (created by InjectIntl(TitledComponent))
    in InjectIntl(TitledComponent) (created by AppStateWrapper)
    in IntlProvider (created by Connect(IntlProvider))
    in Connect(IntlProvider) (created by AppStateWrapper)
    in Provider (created by AppStateWrapper)
    in AppStateWrapper (created by HashParserComponent)
    in HashParserComponent

### Operating System and Browser

Win 10 Chrome 69.03497.100

**Comment by mbonani** [comment]
probably related to commit 6c94c85c9a37e64d1ceabcda3256ecb1bfbd9501 of scratch-vm

git.exe bisect bad

6c94c85c9a37e64d1ceabcda3256ecb1bfbd9501 is the first bad commit
commit 6c94c85c9a37e64d1ceabcda3256ecb1bfbd9501
Author: Ray Schamp <ray@scratch.mit.edu>
Date:   Tue Sep 18 15:47:28 2018 -0400

Add API for the attached renderer

Resolves #1281

:040000 040000 d1fc1406849c1bbfc1f786686b384854450d2078 0e026c9d53daadd9f56c66740707bd6a3c4368c9 M	src
:040000 040000 fd2b1825bcd04bba250bf9c139d680e8d94023aa 0d654b2beb19d7fa2837b479bcd604e2add32183 M	test

Success (1094 ms @ 02.10.2018 15:26:06)

**Comment by thisandagain** [comment]
@chrisgarrity Any thoughts on this? @mbonani Can you repro this on our `develop` branch? I can't seem to replicate this issue. Unfortunately we don't have the bandwidth to provide support for forks of our project.
