### ISSUE TITLE
Rename "Remove" to "Close" on tutorial window top bar

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-gui#3289]
Change the word "Remove" in the Tutorial window to Close. (The word "Close" seems more accurate and will help make clear that it could be opened again.)

![image](https://user-images.githubusercontent.com/4721032/46356734-536ab780-c631-11e8-8208-2e09afe86e57.png)

**Comment by apple502j** [comment]
I think It is duplicate, help-wanted, and solved by me. #2694
