### ISSUE TITLE
Drag preview not working in project 249899732

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#3292]
### Expected Behavior
It should look like you are moving the sprite around when dragging

### Actual Behavior
There is no drag preview. A random triangle appears in the upper left.

### Steps to Reproduce
Go to
https://beta.scratch.mit.edu/#249899732
In the editor, drag the sprite on the screen.
![draglarge](https://user-images.githubusercontent.com/2855464/46377324-4ae0a400-c666-11e8-9535-b4ee3207f282.gif)

### Operating System and Browser
Windows 10 Chrome

**Comment by joker314** [comment]
The triangle appears to be part of the sprite costume, it's just positioned off the stage. This can be seen in the small thumbnail of the sprite, showing a triangle in the far top left.

**Comment by fsih** [comment]
Another example, drag the sprite in https://beta.scratch.mit.edu/#251658287
It seems to completely disappear

**Comment by BryceLTaylor** [comment]
I can definitely reproduce it following the steps listed above and opening that project.

I can also reproduce it by creating a very large svg in illustrator and uploading the costume.  Then when I drag the sprite around the stage it looks rather strange

![toolargesvg](https://user-images.githubusercontent.com/1088291/49236552-53d1c580-f3ca-11e8-920f-df2a8988c199.gif)

That was using this svg: 
[test image.svg.zip](https://github.com/LLK/scratch-gui/files/2629983/test.image.svg.zip)
I shrank the red box a little in the paint editor before making the gif.

**Comment by evhan55** [comment]
Possibly fixed here: https://github.com/LLK/scratch-render/pull/376

**Comment by evhan55** [comment]
Seems fixed by https://github.com/LLK/scratch-render/pull/376
