### ISSUE TITLE
Need design for modal/prompt/confirm when user will replace contents of current project

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3319]
We need to confirm the user's intention to blow away the current project data loaded in the vm in several situations.

Situations:
1. user is editing a project they own and chooses `File->Upload from computer`; or,
2. user is editing a project in the standalone/beta editor, and chooses `File->Upload from computer`; or,
2. user is editing a project in the standalone/beta editor, and chooses `File->New`

In 2.0, this looks like:

<img width="393" alt="screen shot 2018-10-09 at 1 18 14 pm" src="https://user-images.githubusercontent.com/3431616/46686399-2fc1e700-cbc6-11e8-8fa1-fcea58dd12e2.png">

What should this look like in 3.0? 

Thoughts:
* It might be a single prompt with the same text for all 3 situations. Or it might not.
* It might require the user to click an "OK" button. Or it might do something else.
* It might look like the extension-related messages. Or like the www page modals. Or something else.

**Comment by joker314** [comment]
It might be an idea to add a 'Save and Replace' button to whichever prompt is provided to the user, along with the existing 'Replace' and 'Cancel'. This way, a user would just need to click once instead of thrice to save a project.

**Comment by thisandagain** [comment]
Tracking in a single issue here: https://github.com/LLK/scratch-gui/issues/3509
