### ISSUE TITLE
Turbo Mode

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#332]
As per Scratch 2.0, shift clicking the "Green Flag" button should toggle "turbo mode". @carljbowman any thoughts on design / layout given the new position of the flag / stop buttons?

**Comment by thisandagain** [comment]
Functionality resolved in #334 (HT @fsih) we just need to figure out the visual indication piece of the puzzle now. 

/cc @carljbowman

**Comment by carljbowman** [comment]
Thanks for the heads up. Chatted with @fsih and @rschamp yesterday.

I'll be considering this as apart of https://github.com/LLK/scratch-gui/issues/219

**Comment by carljbowman** [comment]
## Green Flag / Stop States Matrix
**This does not include Animation states. See more robust outline below for animations**

![greenflag states](https://user-images.githubusercontent.com/3409578/27650911-87d8665e-5c04-11e7-842f-2e5e8a034091.png)

---

## Green Flag States
### Green Flag - Resting
<img  width="184" src="https://user-images.githubusercontent.com/3409578/27650974-c0547cb6-5c04-11e7-98dc-ef5cd786223d.png"/>

Opacity: 100%
Size: 100%
Animating: No
Animation Speed: N/A
Background: No
Include Turbo Text: No

### Green Flag - Resting:Hover
<img  width="184" src="https://user-images.githubusercontent.com/3409578/27650998-d5563e4c-5c04-11e7-84e2-de6a6358b936.png"/>

Opacity: 100%
Size: 120%
Animating: No
Animation Speed: N/A
Background: No
Include Turbo Text: No

### Green Flag - Executing
_Timing of animation is temporary, but simply demonstrates that the Turbo should animate faster._
<img  width="184" src="https://user-images.githubusercontent.com/3409578/27651020-eb58aaa4-5c04-11e7-85e2-dac6831fa3f8.gif"/>
Opacity: 100%
Size: 100%
Animating: Yes
Animation Speed: Slower
Background: Yes
Include Turbo Text: No

### Green Flag - Executing:Hover
_Timing of animation is temporary, but simply demonstrates that the Turbo should animate faster._
<img  width="184" src="https://user-images.githubusercontent.com/3409578/27651105-27c60a54-5c05-11e7-9ad1-4456206534bd.gif"/>
Opacity: 100%
Size: 120%
Animating: Yes
Animation Speed: Slower
Background: Yes
Include Turbo Text: No

### Green Flag - Executing:Turbo
_Timing of animation is temporary, but simply demonstrates that the Turbo should animate faster._
<img  width="184" src="https://user-images.githubusercontent.com/3409578/27651134-3d02cde4-5c05-11e7-97f3-1eeaf24cbca0.gif"/>
Opacity: 100%
Size: 100%
Animating: Yes
Animation Speed: Faster
Background: Yes
Include Turbo Text: Yes

### Green Flag - Executing:Turbo:Hover
_Timing of animation is temporary, but simply demonstrates that the Turbo should animate faster._
<img  width="184" src="https://user-images.githubusercontent.com/3409578/27651116-3227e36e-5c05-11e7-9a75-b0da6cce29a3.gif"/>
Opacity: 100%
Size: 120%
Animating: Yes
Animation Speed: Faster
Background: Yes
Include Turbo Text: Yes

## Stop States
### Stop - Resting
<img  width="184" src="https://user-images.githubusercontent.com/3409578/27651329-f0f5680c-5c05-11e7-8d26-a4e083f4308f.png"/>
Opacity: 50%

Size: 100%

### Stop - Resting:Hover
<img  width="184" src="https://user-images.githubusercontent.com/3409578/27651344-fa01e7cc-5c05-11e7-8578-ac384fc6cb12.png"/>
Opacity: 50%

Size: 120%

### Stop - Executing
_Timing of animation is temporary, but simply demonstrates that the Turbo should animate faster._
<img  width="184" src="https://user-images.githubusercontent.com/3409578/27651360-09ff50f6-5c06-11e7-8f68-567880edbe88.gif"/>
Opacity: 100%
Size: 100%

### Stop - Executing:Hover
_Timing of animation is temporary, but simply demonstrates that the Turbo should animate faster._
<img  width="184" src="https://user-images.githubusercontent.com/3409578/27651371-1326b02a-5c06-11e7-8869-506956d2c27a.gif"/>
Opacity: 100%
Size: 120%

### Stop - Executing:Turbo
_Timing of animation is temporary, but simply demonstrates that the Turbo should animate faster._
<img  width="184" src="https://user-images.githubusercontent.com/3409578/27651378-1d23df08-5c06-11e7-83e2-21f389d402c0.gif"/>
Opacity: 100%
Size: 100%

### Stop - Executing:Turbo:Hover
_Timing of animation is temporary, but simply demonstrates that the Turbo should animate faster._
<img  width="184" src="https://user-images.githubusercontent.com/3409578/27651384-235cdf46-5c06-11e7-8070-c54c36888866.gif"/>
Opacity: 100%
Size: 120%

**Comment by carljbowman** [comment]
@paulkaplan - Here are those 'Turbo Mode' specs

`font-size: .625rem;` 
`color: $control-primary` or `color:#FFAB19`

Bolt icon: [turbo-bolt-icon.svg.zip](https://github.com/LLK/scratch-gui/files/1229046/turbo-bolt-icon.svg.zip)

<img width="677" alt="screen shot 2017-08-16 at 1 36 32 pm" src="https://user-images.githubusercontent.com/3409578/29376856-f3b0f34c-8287-11e7-8287-afd4700fc22f.png">

**Comment by paulkaplan** [comment]
So the turbo mode indicator and design updates are done, but not the animation. I'm a bit concerned about the performance implications of the animation, in general the idea of running another animation specifically while the project is executing seems like it might be a bad idea. 

so let's split it off into a separate issue.

**Comment by kyleplo** [comment]
Here is an idea:
Shift clicking the green flag should bring four more buttons between the green flag and stop button
![image](https://user-images.githubusercontent.com/31634240/34437921-b7e36f36-ec70-11e7-9fff-e047d07cc298.png)
From left to right, the buttons are:
- Green flag
- Turbo mode
- Mute/unmute
- Save picture of stage to download
- Save picture of stage as sprite, costume or backdrop
- Stop
