### ISSUE TITLE
Add buttons (filters) to Tutorials library menu

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-gui#3334]
Add buttons to the top of the Tutorial library window to enable filtering of tutorials.

Here are the initial buttons suggested: 
* Animation
* Art
* Games
* Music 
* Stories

**Comment by apple502j** [comment]
What about adding Extensions?

**Comment by thisandagain** [comment]
@ntlrsk @paulkaplan Proposal for tags and assignments:

| Tutorial | Filter(s) | Tags |
| -------- | -------- | ------ |
| Getting Started | Animation, Art, Games, Music, Stories | help, stuck, how, can, say |
| Animate a Name | Animation | spin, grow |
| Make Music | Music | sound, instrument, play, song, band | 
| Make a Clicker Game | Games | click, clicked, score |
| Make a Chase Game | Games | arrow, keyboard, score |
| Add a Sprite | Animation, Art, Games, Stories | character |
| Add a Backdrop | Animation, Art, Games, Stories | background |
| Change Size | Animation, Art, Games, Stories | scale | 
| Record a Sound | Animation, Art, Games, Music, Stories | music, instrument, play, song, band |
| Make It Spin | Animation, Art, Games, Stories | rotate, rotation |
| Hide & Show | Animation, Art, Games, Stories | appear, disappear | 
| Switch Costume | Animation, Art, Games, Stories | paint, edit, change, character, sprite |
| Use Arrow Keys | Art, Games, Stories | game, keyboard |
| Add Effects | Animation, Art, Games, Stories | fx, color, fisheye, whirl, twist, pixelate, mosaic, 8bit, 8-bit, brightness, ghost, transparency, opacity |

**Comment by ntlrsk** [comment]
Here's how we had listed them before seeing this - it will be good to compare! 


NAME | BUTTONS: FILTERS
-- | --
Getting Started | [None]
Animate a Name | Animation, Art
Make Music | Music
Make a Clicker Game | Games
Make a Chase Game | Games
Video Sensing | Games
Create a Story | Animation, Stories
Animate a Character | Animation, Art
Add a Sprite | Art, Games, Stories
Add a Backdrop | Art, Games, Stories
Change size | Animation, Art
Glide around | Animation, Stories
Record a sound | Music, Stories, Games,
Make It Spin | Animation
Hide & Show | Stories
Switch costume | Animation, Art, Games
Use arrow keys | Games
Add effects | Animation, Art

**Comment by ntlrsk** [comment]
@zoebentley @SpeakkVisually @kosiecki

**Comment by thisandagain** [comment]
@ntlrsk No worries! I guarantee you folks spent more time thinking about this than I did. Happy to go with your categories. How do you feel about the tags?
