### ISSUE TITLE
Performance Regression with Geometry Dash

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#3344]
The geometry dash project (https://llk.github.io/scratch-gui/develop/#105500895) is running slow again despite performance issues being fixed recently.

The `Player: FPS` monitor reads out `15` on llk.github.io/scratch-gui/develop, but runs at normal speed (30 FPS) on beta. This means that this change was introduced sometime in the last week (Thursday Oct 4th - Thursday Oct 11th).

**Comment by BryceLTaylor** [comment]
I just did a git bisect.  It would seem that it's a problem in the vm that came in from this commit: 

commit f2c63874f3dc5af5ca329479025670d8d63edbb0
Author: greenkeeper[bot] <greenkeeper[bot]@users.noreply.github.com>
Date:   Wed Oct 10 19:39:15 2018 +0000

    chore(package): update scratch-vm to version 0.2.0-prerelease.20181010193639

:100644 100644 9858b524fad038a981c3764e9945060958f94320 085af975007c79f5a0601726421d8321c1bdf884 M	package.json

**Comment by kchadha** [comment]
It looks like LLK/scratch-vm#1619 is the cause...
