### ISSUE TITLE
Opening broken projects doesn't crash

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#3363]
### Expected Behavior
When loading "broken projects" (which causes "Error! This project failed to load..." in 2.0), it crashes.

### Actual Behavior
It doesn't crash. We can see only the loading animation.

### Steps to Reproduce
Open https://scratch.mit.edu/projects/104279011/ in 2.0 and 3.0

### Operating System and Browser
Windows 7 HomePremium 64bit SP1
Firefox 62

**Comment by kchadha** [comment]
It looks like the project in question is getting a `404` from the projects server.

**Comment by rschamp** [comment]
This seems like an important one to have fixed. It is unclear to the user when something goes wrong while loading a project, especially in the player view. I think we want this to be visible, and at least not show a green flag over the project when there's no project to start.
