### ISSUE TITLE
Can't upload scratch project by double clicking the file

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#3365]
### Expected Behavior
Double clicking in the file selector selects the file

### Actual Behavior
Double clicking in the file selector closes the file selector with no action

### Steps to Reproduce
1. Go to develop
2. File > Upload from your computer an sb3
 - If you double click to select the file, the file dialog closes with no action
 - If you click the file and then press the 'Open' button, it works fine

![upload2](https://user-images.githubusercontent.com/2855464/46958626-3dfd8080-d068-11e8-94bc-09c03740c85a.gif)

Attached the file I'm using in case it's relevant (rename to sb3)
[you totally ca.zip](https://github.com/LLK/scratch-gui/files/2479185/you.totally.ca.zip)
### Operating System and Browser
Windows 10 Firefox

**Comment by benjiwheeler** [comment]
A fix is in progress: https://github.com/LLK/scratch-gui/pull/5450
