### ISSUE TITLE
Goomble Gurt doesn't load in Safari

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3381]
### Expected Behavior

The project Gooble Gurt (211917681) should load on all browsers.

### Actual Behavior

That project stops loading relatively quickly compared to other browsers on the same device and it gives an error page:

<img width="604" alt="screen shot 2018-10-15 at 4 42 50 pm" src="https://user-images.githubusercontent.com/1088291/46977149-618cef00-d099-11e8-952f-458fa04ee4f1.png">

There are errors in the console:

Many many of these:
[Log] storage – "warn" – "Deprecation: BuiltinHelper.cache has been replaced with BuiltinHelper.store." (raven.min.js, line 2)

[Error] Unhandled Promise Rejection: TypeError: Invalid attempt to destructure non-iterable instance
	(anonymous function) (lib.min.js:154:26300)
	promiseReactionJob
[Error] Error: Failed to load project from server [id=#211917681]: TypeError: Invalid attempt to destructure non-iterable instance
value — lib.min.js:47:9457
r — lib.min.js:103:44319
n — lib.min.js:103:52679
i — lib.min.js:103:53000
a — lib.min.js:103:53236
w — lib.min.js:103:56759
I — lib.min.js:103:56496
m — lib.min.js:103:55628
enqueueSetState — lib.min.js:103:45470
setState — lib.min.js:95:1379
(anonymous function) — lib.min.js:154:24672
promiseReactionJob

	(anonymous function) (raven.min.js:2:1257)
	r (lib.min.js:103:54578)
	a (lib.min.js:103:53323)
	w (lib.min.js:103:56759)
	I (lib.min.js:103:56496)
	m (lib.min.js:103:55628)
	enqueueSetState (lib.min.js:103:45470)
	setState (lib.min.js:95:1379)
	(anonymous function) (lib.min.js:154:24672)
	promiseReactionJob

[Log] gui – "error" – "Unhandled Error: value@https://llk.github.io/scratch-gui/develop/lib.min.js:47:945…" (raven.min.js, line 2)

There are other issues with this project as well: https://github.com/LLK/scratch-gui/issues/3380

### Steps to Reproduce

Start to load the project https://llk.github.io/scratch-gui/develop/#211917681
Note: it takes you to an oops page after loading for a few seconds and errors appear in the console

### Operating System and Browser

Safari on Mac

**Comment by kchadha** [comment]
@fsih, it looks like this is project is failing in svg-renderer on [this line](https://github.com/LLK/scratch-svg-renderer/blob/develop/src/svg-renderer.js#L187).

The `if (textElement.transform.baseVal.length === 0)` check that appears earlier fails because `.length` does not seem to exist (there's a `numberOfItems`...), so the LHS in that expression returns `undefined`.

Then when we get to the line linked above, we get an index out of bounds error.

**Comment by fsih** [comment]
Thanks @kchadha! After 9 months and a very painful debugging session with Edge, just implemented your fix! 😂😭
