### ISSUE TITLE
how to create a project like blocky-game with scratch-gui?

### ISSUE THREAD

**Issue by wooden1985** [LLK/scratch-gui#3390]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
Should be closed as "not clear"

**Comment by thisandagain** [comment]
Please do not post duplicate issues.
