### ISSUE TITLE
WebkitBlobRessource error 1 when downloading on iOS

### ISSUE THREAD

**Issue by jubbaho** [LLK/scratch-gui#3392]
### Expected Behavior

On downloading project the browser on iOS should ask where to save the file.

### Actual Behavior

In Safari this error occurs: WebkitBlobRessource error 1
In Chrome nothing happens.

### Steps to Reproduce

1. Start new Scratch 3.0 project on iOS
2. Choose File and Download to your computer

### Operating System and Browser

iOS 11 / 12

**Comment by thisandagain** [comment]
@BryceLTaylor I believe we have this filed already, but I can't find it right now. If you mind the dupe, please feel free to close this.

**Comment by BryceLTaylor** [comment]
This has been reported in this issue: https://github.com/LLK/scratch-gui/issues/1783
