### ISSUE TITLE
Source code for Scratch Link?

### ISSUE THREAD

**Issue by d33tah** [LLK/scratch-gui#3404]
Hi!

I found that I need to have "Scratch Link" to use Scratch 3 with Lego Mindstorms, but I can't find a Linux version nor a source repo so that I'd try to port it myself. Any chance you could point me to one? Here's also a relevant discussion:

https://scratch.mit.edu/discuss/topic/314084/

Thanks,
d33tah

**Comment by thisandagain** [comment]
We are hoping to open source Scratch Link soon (waiting on approval from MIT). Please stay tuned!

**Comment by gengshenghong** [comment]
is there any update on this? or any plan? :)

Thanks,
Shenghong

**Comment by thisandagain** [comment]
@gengshenghong No updates yet. We are still waiting on MIT approval.

**Comment by johannesegger** [comment]
Really? It takes that long? Are you discussing the license type or what (Hint: Use MIT, it's great ;-) )? Could you in the meantime support Win7, because that's what I currently need (I know, I'm old-school).

**Comment by CenTdemeern1** [comment]
Anything?

**Comment by CenTdemeern1** [comment]
> 
> 
> Really? It takes that long? Are you discussing the license type or what (Hint: Use MIT, it's great ;-) )? Could you in the meantime support Win7, because that's what I currently need (I know, I'm old-school).

They said theyre already waiting on MIT.

**Comment by wr200m** [comment]
any news on the MIT approval to open this up?

**Comment by towerofnix** [comment]
@wr200m scratch-link is now open source (it has been as of a few weeks ago): https://github.com/LLK/scratch-link

**Comment by wr200m** [comment]
Thanks.. Sorry I was foolish to post the question before I saw that...

**Comment by towerofnix** [comment]
No problem, and don't worry about it! It was a long while before I noticed too. As far as I know, the Scratch Team didn't announce it anywhere.
