### ISSUE TITLE
Try to reproduce state where file->new on smoke branch does nothing

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3412]
@chrisgarrity writes:

> I was able to get into a state where File...New did nothing (on iPad) on an existing project. But reloading project everything was fine

**Comment by BryceLTaylor** [comment]
This seems to be happening when you have loaded a project by url, such as https://llk.github.io/scratch-gui/develop/#251959006 and then you try to click file new.

It looks like the "new" button is clicked, it gives visual feedback, but nothing changes for the site.  

If you create a project from the default project fie>new loads a new project just fine.
