### ISSUE TITLE
Scrolling Moves Make Block Inputs

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#3419]
### Expected Behavior

If you scroll, the inputs for the make blocks should have a position relative to that of the block you are making.

### Actual Behavior

If you scroll, the input for the block will change relative position.

### Steps to Reproduce

Click "Make a Block"
Scroll either up or down (depends on screen position)

### Operating System and Browser

Windows 10 on Chrome

Note: This may have to do with window.innerHeight and window.outerHeight being different in the GUI.

**Comment by amazinigmech2418** [comment]
I found this: https://github.com/LLK/scratch-gui/pull/1004 . Apparently, the screen size was set to a constant value due to test errors. What needs to be done is setting sizes of objects relative to the screen height. The "fix" just causes more errors when the needed fix is what I just said. That PR needs to be reverted and there needs to be more done.

**Comment by amazinigmech2418** [comment]
Here is a screenshot that explains this bug. 
![bug1](https://user-images.githubusercontent.com/33498997/47244676-5f41d200-d3c4-11e8-8485-e350fbfd08ae.PNG)

**Comment by paulkaplan** [comment]
Thanks for the report. It looks like a couple of things are going on:

1. The modal allows you to scroll the page behind it, which doesn't seem right.
2. The "Make a Block" modal (and actually all of our modals) have an issue where they cannot scroll when they are taller than the page (this would prevent you from accessing the buttons at the bottom, for example). We allow short screen heights to scroll the editor, we should be able to do the same for modals. 
3. For some reason, the scratch-blocks inputs respond to scrolling the page, but ignore the fact that they may be embedded inside a non-scrolling element (like our modal)

The code you referenced in the PR you submitted was not related to this, that is just using a particular screen size to run the tests.

I'm going to look into fixing (2), which should be able to cover for the other issues.
