### ISSUE TITLE
Variable from Previous project appears in New project

### ISSUE THREAD

**Issue by Mr-Dave2** [LLK/scratch-gui#3427]
### Expected Behavior

Clicking on "File" then "New" ought to create a new project with only the default "my variable".

### Actual Behavior

Doing the steps below will cause a variable from a previous project to show up as a local variable in a new project.

### Steps to Reproduce

Open Chrome or Firefox , open URL https://beta.scratch.mit.edu/ , click "Try-it"
Create a new, Global, variable with the name: %-no-pairs
Click File, then "Download to your computer" (and "OK" if using Firefox).
Click File, New, OK
Add a surprise sprite
Click on the Sprite1 sprite to select it and notice that it now has a local variable "%-no-pairs"

### Operating System and Browser

Windows 7;  Chrome: Version 69.0.3497.100 (Official Build) (64-bit) and
                     Firefox: 62.0.3 (64-bit)

**Comment by benjiwheeler** [comment]
I was able to reproduce this on Mac Chrome and Mac Firefox. Even simpler steps to reproduce:

1. Open Chrome or Firefox , open URL https://beta.scratch.mit.edu/ , click "Try-it"
2. create a variable with any name (either global or sprite specific)
4. File->New, OK
5. Click on stage/backdrops thumbnail on right, then back on Sprite 1
6. notice that it now has the variable you created before

**Comment by benjiwheeler** [comment]
Possibly tracking in https://github.com/LLK/scratch-vm/issues/1758

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/1758
