### ISSUE TITLE
about screen shot

### ISSUE THREAD

**Issue by yolo3a525** [LLK/scratch-gui#3428]
i want to get screenshot about all scene.
i don't know why?
somtime the sceen shot is ok
but more time the sceenshot is black.
my code as this:
`       var canvas1 = document.getElementsByClassName("stage_stage_DTWo5")[0];          //find canvas  
        var gl1 = canvas1.getContext("experimental-webgl", {preserveDrawingBuffer: false});
        //var gl1 = canvas1.getContext("2d");
        var screenShot= gl1.canvas.toDataURL();           
`

**Comment by paulkaplan** [comment]
See https://github.com/LLK/scratch-gui/blob/ab31d36251e21fd78aac34983ede6a75e9f1ff71/src/lib/project-saver-hoc.jsx#L66 for the function to use for getting images of the stage.
