### ISSUE TITLE
extension blocks showing up wrong when gui is loaded in project page as player

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3438]
### Expected Behavior

extension blocks should always display correctly in project editor view

### Actual Behavior

There's a bug with extension blocks on scratch.ly and www/gui develop. When you have a 3.0 project that uses extensions, they seem to load and appear normally when you load `preview/:id/editor` directly … but when you start at preview/:id and then click “See inside”, they appear like this:

![screen shot 2018-10-19 at 3 13 55 pm](https://user-images.githubusercontent.com/3431616/47250167-223d0600-d3eb-11e8-9795-15fd0043b2cc.png)

Note that they appear to still function! like, if it’s a music note block, it still plays the music note correctly when you click on it.

Example:
* https://scratch.ly/preview/1000015785/editor
  * will load a project with music/pen extensions fine. But:
* https://scratch.ly/preview/1000015785/ followed by ‘see inside’
  * draws all the extension blocks as red hats as above (and loses the stack on the workspace).

### Steps to Reproduce

1. open a project you own on scratch.ly (or in www in develop)
2. add extension blocks to a sprite's code
3. file->save
4. load the project page: `.../preview/:id/editor`
5. click "See inside"
6. note that the extension blocks display wrong

### Operating System and Browser

Mac Mojave, current Chrome;
Mac Mojave, current Firefox

**Comment by benjiwheeler** [comment]
Seems like the _convertForScratchBlocks code and the onWorkspaceUpdate are each being called once in both cases, and returning the same values. Though of course  onWorkspaceUpdate is called immediately when loading editor directly, vs. called later when you click See Inside.

But e.g. for the microbit extension’s “clear display” block (not a hat, just a regular block), in both cases, onWorkspaceUpdate is getting the same json for it, that should not appear as a hat:

```
info:
arguments: {}
blockAllThreads: false
blockType: "command"
func: ƒ ()
opcode: "displayClear"
terminal: false
text: "clear display"
__proto__: Object
json:
args0: (2) [{…}, {…}]
category: "micro:bit"
colour: "#0FBD8C"
colourSecondary: "#0DA57A"
colourTertiary: "#0B8E69"
extensions: ["scratch_extension"]
inputsInline: true
message0: "%1 %2clear display"
nextStatement: null
outputShape: 3
previousStatement: null
type: "microbit_displayClear"
__proto__: Object
xml: "<block type="microbit_displayClear"></block>"
```

**Comment by benjiwheeler** [comment]
Note that the recent backpack work means that blocks for extensions that are not loaded can be dragged from the backpack into the scripts editor area:

![screen shot 2018-11-02 at 9 46 12 am 2](https://user-images.githubusercontent.com/3431616/47919096-e0996a00-de84-11e8-8671-e96264bb47b8.png)
![screen shot 2018-11-02 at 9 51 09 am](https://user-images.githubusercontent.com/3431616/47919103-e8590e80-de84-11e8-9b8f-47a64f2f76c7.png)
![screen shot 2018-11-02 at 9 48 57 am](https://user-images.githubusercontent.com/3431616/47919108-ebec9580-de84-11e8-9485-f449808fab53.png)

**Comment by ericrosenbaum** [comment]
A minimal repro for this bug, which prevents all projects with extensions from loading correctly in www in editor mode.

This is a simple project with a single pen stamp block which works when you load in the project page:
https://scratch.ly/preview/1300000232/ 

Click "see inside" and note that the "pen stamp" block is missing from the workspace (it should be `when gf clicked / forever / go to random position / stamp`).

Also note that the blocks in the pen category are all red hats.

**Comment by thisandagain** [comment]
@cwillisf Sorry to add this to your plate last minute, but this is a critical bug that we could use your help with.

**Comment by kchadha** [comment]
I think this is possibly caused by a race condition between extensions loading and blocks loading. In the project page e.g. /preview/:id, there is no blocks container. When you click 'see inside' there is suddenly a blocks container, but I'm worried that we are trying to render extension blocks before scratch-blocks knows what they look like. The red blocks become normal extension blocks when causing the workspace to refresh by either switching sprites and back or switching to the costumes/sounds tab and back to code.

I haven't actually dug into the code at all, so take these words with a grain of salt. @cwillisf, I'm happy to pair and help figure out what's going on.
