### ISSUE TITLE
Instead of 

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3443]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
What do you mean?

**Comment by benjiwheeler** [comment]
Sorry, looks like this was created in error when github had a partial outage.

I'm closing it.
