### ISSUE TITLE
Certain costumes glitch in the editor

### ISSUE THREAD

**Issue by Robomandude** [LLK/scratch-gui#3462]
[icon.zip](https://github.com/LLK/scratch-gui/files/2504570/icon.zip)

### Expected Behavior

The costume editor should be able to handle any image generated by scratch 2.0

### Actual Behavior

The editor behaves oddly when loading certain files.
I don't know what causes these files in particular to misbehave.

### Steps to Reproduce

The file I have attached loads as intended in Scratch 2.0, but causes issues in scratch 3.0

This issue seems to only affect the costume editor and work fine if directly loaded from a .sb2 project.

### Operating System and Browser

Windows 7, Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by thisandagain** [comment]
Moved to LLK/scratch-paint#729
