### ISSUE TITLE
Scratch-vm and scratch-gui run the same .sb3 files with different results？

### ISSUE THREAD

**Issue by weijiahui1** [LLK/scratch-gui#3464]
### Expected Behavior

Same operation effect

### Actual Behavior

Operation results are different.

### Steps to Reproduce

1. Scratch-vm the file running target file after packaging.
![image](https://user-images.githubusercontent.com/25278544/47353312-87943e00-d6ee-11e8-9843-3213afda77d3.png)

2. scratch-gui the file running target file after packaging.
![image](https://user-images.githubusercontent.com/25278544/47353337-98dd4a80-d6ee-11e8-964b-064fa5e10dd0.png)

### Operating System and Browser
window10 google

**Comment by thisandagain** [comment]
@weijiahui1 Please provide more details as to what you are seeing that is different. Also please provide a reference SB3 file or project ID that we can use to replicate the issue.

**Comment by weijiahui1** [comment]
This is the address of the Sb3 file I run. You can download this Sb3 file and open it in scratch-gui project.
[https://appd.knowbox.cn/bianchengapi/homework/88879ad1d31486302b608106c5d944fb.sb3](url)
You can see that many small planes fly from different directions to the earth from time to time.

But if you run this file in the scratch-vm project, you can't see the emergence of a small aircraft.

**Comment by weijiahui1** [comment]
This is the same Sb3 file compression package, you can try
[sb3file.zip](https://github.com/LLK/scratch-gui/files/2508664/sb3file.zip)

**Comment by thisandagain** [comment]
@BryceLTaylor Do you mind attempting a repro on this?

**Comment by BryceLTaylor** [comment]
I tried loading it and it just loaded forever.  That sb3 file contains a file called mblock5 that is apparently a Unix executable.

According to @thisandagain this project seems to be made in mblock.
