### ISSUE TITLE
Some tutorial gifs are over 10MB

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#3487]
Most of the gifs in the tutorials are around 100 KB or so. But in the PR ([here](https://github.com/LLK/scratch-gui/pull/3479/files)) that adds the cartoon network and text to speech tutorials, some of the GIFs are very large (a few are over 10MB, i.e. 100 times as large). 

We should probably make a smaller version of any GIF that is over 1MB, and generally consider how to make sure the GIFs are reasonable file sizes without sacrificing clarity.

**Comment by kosiecki17** [comment]
Will work with the resources team to resolve this!

**Comment by thisandagain** [comment]
Thanks @kosiecki! I'm going to mark this as "critical" as it is likely a blocker for launch.
