### ISSUE TITLE
"Add a backdrop" should not switch tabs

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-gui#3500]
Currently clicking "Add a backdrop" button switches the tab to Backdrop tab. That is consistent with 2.0, but we have noticed that many people are disoriented when that happens, and it's usually not what is wanted.
Thus, as we discussed, the recommendation is to have clicking the Add a backdrop button stay on the current tab and not switch.

**Comment by thisandagain** [comment]
@paulkaplan Do you mind taking this one?

**Comment by paulkaplan** [comment]
@thisandagain @ntlrsk I can definitely do this, but I want to make sure this wouldn't be breaking any already-made videos from other resource developers. Is that something you can confirm @thisandagain?

**Comment by thisandagain** [comment]
@paulkaplan It will, but as discussed with the resources team this feels important enough to make the breaking change.
