### ISSUE TITLE
Uploading a project creates a new project, rather than replacing the current project’s data

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3509]
### Expected Behavior

Logged in, viewing a project I own, clicking File->upload from your computer... it should ask me if I want to replace the project's content, and if I confirm, load the uploaded project into the vm, maintaining the id.

### Actual Behavior

Creates a new project with the uploaded content.

Question: there's no way that's the behavior we *want*, is there?

**Comment by Alzter** [comment]
> I agree! Sometimes I want to upload a new project, so I click the upload button but it replaces my old project then I lost my old project!

See, that's what File>Revert is for. That being said it should be more obvious.

**Comment by towerofnix** [comment]
Do note that uploading a project via file -> upload is frequently used for sharing a "new version" of a project. I think the issue acknowledges this.

For example, I have created a large project that I want to share an initial version of; I call this my "alpha" version. I share it, then I click "file -> save a copy"; this creates a version of the project which I do further development on. Then when I want to share *that* version, I *download* it, then in the original "alpha" project, I upload the project downloaded from the dev version. That way I preserve all the comments and stats from the original project, but have the project itself updated for anyone who plays in the future.

I've also seen people do basically the exact same thing for "updates" to projects, e.g. a "1.1.0" update adding a bunch of new things, which was mostly developed in a separate, unshared project, then uploaded over the original "1.0.0" project.

**Comment by thisandagain** [comment]
After discussion we are going to simply change the behavior back to what we had in 2.0:

- Uploading a project from your computer replaces the contents of the current project ID
- If replacing project contents, the user is presented with a prompt:
    - "Replace contents of the current project?"
    - "OK", "Cancel"

**Comment by thisandagain** [comment]
Assigning to @benjiwheeler and @carljbowman to be resolved this iteration.

**Comment by benjiwheeler** [comment]
Current plan:
* Design a confirmation modal
* Change upload code to replace contents as opposed to creating new project
* Make sure filename gets used
* Change “Creating project” to “Loading project” for the blue screen
* We seem to be preferring first showing file picker, then showing warning
* We seem to prefer in-app modal we design, over a browser-default confirm
* See how this feels; we can always consider adding “create new” functionality later

**Comment by benjiwheeler** [comment]
OK, I put up a PR that implements the core UX change: https://github.com/LLK/scratch-gui/pull/4700

* for logged in users, uploading a project gives it the same project id as the current project, rather than creating a new project id.
* sets the project filename from the upload file name
* confirms after showing the upload dialog
* confirm logic for upload is now: show confirm dialog if user owns current project, or project has been changed since it was opened.
