### ISSUE TITLE
Tutorials Modal: Tutorials link v. Close

### ISSUE THREAD

**Issue by kosiecki17** [LLK/scratch-gui#3511]
In response to seeing many users close the Tutorials window almost immediately during play-tests, we'd like the Tutorials link to be more prominent than Close X.

Carl and Andrew mentioned potentially shifting these links below the window.

**Comment by carljbowman** [comment]
Following up on yesterday's discussion. In the near term we will adjust the hierarchy of the "Tutorials" and "Close" button icons in the nav. 

Post-launch (next year), we will take a more holistic pass on the overall design of the tutorial system.

For now, we will address the issue of the lightbulb and "x" icons feeling out of proportion. They should be optically sized, rather relying on the icon's native size. The "x" should become smaller and the "lightbulb" should be larger. 

I'll take a peek at making these changes.
