### ISSUE TITLE
Project froze, "Workspace Update Error: Serialized variable type with id ... had type list, and does not match variable field that references it"

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#3517]
### Expected Behavior
Project doesn't freeze

### Actual Behavior
Project froze with this error in the console
https://pastebin.com/TYLnRadA

### Steps to Reproduce
I don't remember what happened 
):

### Operating System and Browser
Windows Firefox

**Comment by thisandagain** [comment]
Unfortunately not enough info to perform a repro. Closing for now.
