### ISSUE TITLE
Upload the cleaned up scratch cat

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#3519]
The current scratch cat vector has some issues, like empty vector groups and the foot where the stroke is not attached to the fill.

We need to get the new asset and update 1. the SVGs in the default project and 2. The cat sprite (cat a and cat b costumes)

**Comment by fsih** [comment]
@carljbowman sending this to you first for the asset

**Comment by carljbowman** [comment]
Handled by https://github.com/LLK/scratch-gui/pull/3977
