### ISSUE TITLE
Add support for uploading .gif as sprite/backdrop and costumes

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#3541]
### Desired Behavior
From the Upload from Computer option, uploading a .gif would either... 
- For a sprite/backdrop, create a new sprite/backdrop and add each frame of the .gif into an individual costume 
- For a costume, add each frame of the .gif as costumes within a sprite

### Initial UX Considerations
 - In the case of adding costumes to an existing sprite, we would need to think through where in the costume list the new costumes are added.

**Comment by towerofnix** [comment]
This probably closes #3254 by having more information.

**Comment by carljbowman** [comment]
@towerofnix - Thanks for tracking that down.
