### ISSUE TITLE
Add support for uploading multiple images as sprites/backdrops and costumes

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#3542]
### Desired Behavior
From the Upload from Computer option, being able to select multiple image files and upload would...
- For sprites/backdrops, there are conceivable two options. Not clear which is more expected.
  1. Add images as individual sprites
  2. Combine all selected images into a single sprite
- For costumes, add all the selected images as costumes

### Initial UX Considerations
- When we support .gif upload (https://github.com/LLK/scratch-gui/issues/3541), what happens if multiple .gif files are uploaded?
- In the case of adding costumes to an existing sprite, we would need to think through where in the costume list the new costumes are added.

**Comment by paulkaplan** [comment]
Supported
