### ISSUE TITLE
When user creates new project, remixes, and saves as a copy, what alert text should they see?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3545]
What wording should we use to communicate project saving and creating?

Situations:
1. When user has successfully created a new project?
1. When user has successfully remixed a project?
1. When user has successfully saved a project as a copy?
1. When user has manually, or auto, saved?

1-3 are all a form of creation, so they could all have the same message, or different messages.

**Comment by benjiwheeler** [comment]
What about:

1. "Creating new project", "Successfully created new project"
2. "Remixing project", "Successfully remixed project"
3. "Copying project", "Successfully copied project"

**Comment by benjiwheeler** [comment]
Great point, these are clearer!

**Comment by kathymakes** [comment]
@benjiwheeler Actually when I think about it, I wonder if we can avoid having any alerts/title bar text when a new project is created. (Referring to #1, Creating New).

I was remembering this conversation: https://github.com/LLK/scratch-gui/issues/3846
This UX feels clearer to me, and more self-explanatory (uses our existing patterns clearly without alerts.)

![open existing 1](https://user-images.githubusercontent.com/8203939/49096127-e0984a00-f237-11e8-8594-2bc0139d2105.png)

> 1. save current project
> 2. flash the blue loading screen for 1-2 seconds
> 3. show new project (saving)
>
> I think the blue loading screen and "creating" alert are (intending to) communicate the same thing, and having both feels a bit redundant to me

**Comment by benjiwheeler** [comment]
Also, @kathymakes suggested changing saving success message from "Successfully saved" to "Project saved"

**Comment by benjiwheeler** [comment]
So I'm implementing:

- "Saving project…"
- "Remixing project…"
- "Copying project…"
- "Creating new…"

Question: should I use ellipses, or no ellipses?
