### ISSUE TITLE
Windows Edge menu z-index issues

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3563]
@fsih writes:

>  Login is behind the project (File, edit as well)
(while embedded in www)

![47670461-98780000-db83-11e8-92f0-78092cdff077](https://user-images.githubusercontent.com/3431616/47694308-858d1c00-dbd3-11e8-9f80-13d56d4fbc67.png)

**Comment by fsih** [comment]
Looks fixed now!

**Comment by benjiwheeler** [comment]
Maybe this is fixed too? https://github.com/LLK/scratch-gui/issues/3417
