### ISSUE TITLE
Heart costumes are not displaying text

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#3577]
### Expected Behavior
Heart costumes include text
_Please describe what should happen_
![image](https://user-images.githubusercontent.com/2855464/47748603-8d939d00-dc61-11e8-9661-b7afb9e0fc9e.png)

### Actual Behavior
Text isn't appearing on hearts
![image](https://user-images.githubusercontent.com/2855464/47748502-5cb36800-dc61-11e8-878a-4809b8eac87c.png)
![image](https://user-images.githubusercontent.com/2855464/47748543-7785dc80-dc61-11e8-9e72-4233b8fdfd1a.png)

### Steps to Reproduce
Search costume library for "heart"

### Operating System and Browser
All

**Comment by thisandagain** [comment]
@kosiecki17 Is this something you can look at? It appears that the text from the 2.0 costumes is somehow malformed.

**Comment by fsih** [comment]
I just realized that this is (partially) because of https://github.com/LLK/scratch-vm/issues/1773
One of the things that Scratch 2 does wrong when exporting SVGs is it puts the text in the wrong place, and since these are coming from the costume library, the fix isn't getting applied.

Fixing the SVGs should fix the issue, if they don't go through Scratch 2's export process...

**Comment by kosiecki17** [comment]
These files are looking funky when I download them and open them locally. I will fix them and re-upload them.
<img width="903" alt="screen shot 2018-11-29 at 8 59 09 am" src="https://user-images.githubusercontent.com/25378759/49226697-5a097700-f3b5-11e8-9e5a-9f5dc759ba25.png">

**Comment by kosiecki17** [comment]
The workaround was to expand the letters. They are no longer editable as text, but they are displaying correctly in the sprite library and paint editor.
