### ISSUE TITLE
Focused block field appears after switching to sounds or costumes tab 

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#358]
### Expected Behavior

Sounds and costumes tabs should not contain weird eyeball-like ghost-remnants of block input fields.

### Actual Behavior

They do.

### Steps to Reproduce

Drag a block with an input field, such as 'move 10 steps', to the workspace.
Click on the input field.
Click on the costumes or sounds tab.
(this also works for menus on blocks)

<img width="54" alt="screen shot 2017-05-10 at 4 58 22 pm" src="https://cloud.githubusercontent.com/assets/567844/25921091/2c8b6b94-35a2-11e7-883f-0da3d152e642.png">

### Operating System and Browser

Mac OS 10.11.6 Chrome 57.0.2987.133

**Comment by ericrosenbaum** [comment]
oops should this be in scratch-blocks?

**Comment by thisandagain** [comment]
Hmm. Not sure ... might have to do with tab switching. Needs investigation.

**Comment by paulkaplan** [comment]
Yeah I think we should be hiding/showing blockly when switching tabs, something we will have to do in the GUI.

**Comment by fsih** [comment]
#368 mostly fixes this but it hangs around for .25 seconds. Adding https://github.com/LLK/scratch-blocks/issues/893 in scratch blocks for the rest of the bug.
