### ISSUE TITLE
Some png files won't upload

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#3582]
### Expected Behavior
You should be able to upload a png as a new sprite or new costume. A student at my Scratch Club was trying to upload images they had found on the web. Lots were fine, but some just did nothing. They shared one of the files with me and I was able to reproduce the problem.

### Actual Behavior
Uploading some png files doesn't do anything. It doesn't create the sprite, and doesn't give any error feedback. 

In the console:
```
Failed to load resource: the server responded with a status of 404 ()
raven.js:55 vm  TypeError: Cannot read property 'assetId' of null
    at i (lib.min.js:53)
    at lib.min.js:53
a.(anonymous function) @ raven.js:55
lib.min.js:75 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at e.value (lib.min.js:75)
    at e.set (lib.min.js:75)
    at lib.min.js:133
beta.scratch.mit.edu/:1 Uncaught (in promise) Sprite Upload Error: TypeError: Cannot read property 'bitmapResolution' of undefined
```
### Steps to Reproduce
Try uploading this png as a sprite:
![lion_new_pose_normal_eyes](https://user-images.githubusercontent.com/399209/47795161-63d98500-dcf8-11e8-91e0-7ae47ea8a66f.png)

If uploading/downloading from github has somehow 'fixed' the file, I have the original shared with me.

### Operating System and Browser

Seen on HP Chromebook and MacOS (both Chrome)

**Comment by SimaKyr** [comment]
what resolution original image?

**Comment by julescubtree** [comment]
Hi all,

I've actually wondered if uploading was recently broken. I haven't done much testing, but the only graphics I've been able to upload have been graphics that I've downloaded first from the asset server.

It's definitely not just PNG files; [this SVG won't upload either](https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg).

After failed sprite uploads, using the sprite selector to choose and add a sprite results in blank sprites (named after the attempted uploads) showing up. Selecting those blank sprites crashes the GUI.

Please let me know how I can help test things.

**Comment by SimaKyr** [comment]
@julescubtree TypeError: Cannot read property '**** bitmapResolution**** ' of undefined
He try upload png, svg use vector, but console write in error bitmap

**Comment by fsih** [comment]
Note that it's only if you upload it as a new sprite, not as a costume

**Comment by robertsonadams** [comment]
I'm having the same problem with GIF and PNG image files exported w/o metadata from Photoshop on Mac OS with Chrome.

**Comment by fsih** [comment]
@robertsonadams could you open a new issue and attach the files you're having issues with to it?

**Comment by robertsonadams** [comment]
Eventually I got the files to upload using Safari browser instead of Chrome. (I had been running with all extensions OFF in Chrome, and I was saving from Photoshop to PNG format, with file size <10k, no metadata saved, no spaces in filename).
