### ISSUE TITLE
Slider handle on variable monitors should not capture keyboard inputs

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3587]
### Expected Behavior

Variable monitor sliders should not capture keyboard inputs.

### Actual Behavior

If you move a slider on a variable monitor, all keyboard input is then captured by the monitor.  The Left and Right arrow keys move the slider, but the other keys don't do anything and the slider handle glows.  This does not match the behavior in 2.0.

To release the keyboard input you must click on the monitor, but not on the slider handle.  If you click anywhere else in the project it does not release the keyboard input.

![slidermonitorcapturekeyboard](https://user-images.githubusercontent.com/1088291/47818020-7cb05d80-dd2d-11e8-8d84-0f0e015139fb.gif)

### Steps to Reproduce

Create a new project
On the cat add the stack "when right arrow key pressed" "move 10 steps"
Check the monitor for "My Variable"
Double click the monitor until it is a slider
Press the right arrow key
Note: the cat moves
Drag the slider of the variable monitor to the middle
Press the right arrow key
Note: the slider moves to the right and the cat does not.
Click somewhere on the stage
Press the right arrow key
Note: the slider moves to the right and the cat does not.
Click on the monitor, but not on the slider handle
Press the right arrow key
Note: the cat moves to the right.
Change the hat block to "When D key pressed"
repeat the above steps
Note: after the slider is selected the cat doesn't move and the glow on the slider handle is glowing, but the slider handle also doesn't move.

### Operating System and Browser

Mac Chrome

**Comment by Mr-Dave2** [comment]
Duplicate (?) of "When key pressed" block doesn't run when variable slider is also being used #3084

**Comment by paulkaplan** [comment]
@Mr-Dave2 Yup, closing
