### ISSUE TITLE
Make alerts when cloud variable is added, project with cloud variables is loaded

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3598]
Part 1:

This part is being tracked in: https://github.com/LLK/scratch-www/issues/2285

In 2.0, creating a cloud variable gives the user this message:

![image](https://user-images.githubusercontent.com/3431616/47867221-44655980-ddd7-11e8-8af2-ef9346cacf7a.png)

@kathymakes and @carljbowman discussed this and thought it could make sense in the new alert system.

They suggested that instead of a link, there could be a "find out more" or "learn more" button.

The alert would be dismissable.

Part 2:

When a user is not logged in and loads a project that uses cloud variables, she sees:

(on project page)
![screen shot 2018-11-07 at 3 03 32 pm](https://user-images.githubusercontent.com/3431616/48157797-a4a83f80-e29e-11e8-9712-9d8f925ccd13.png)

(in editor)
![screen shot 2018-11-07 at 3 07 00 pm](https://user-images.githubusercontent.com/3431616/48157868-dcaf8280-e29e-11e8-83af-5f20abca7c67.png)

**Comment by DeleteThisAcount** [comment]
just wanted to say
on scratch 2 when loading an extremely cloud used project, that error will show and hide rapidly, making scratch unusable

**Comment by kchadha** [comment]
@DeleteThisAcount could you clarify what you mean by "an extremely cloud used project"? Do you have an example project where you see this issue?

**Comment by DeleteThisAcount** [comment]
> @DeleteThisAcount could you clarify what you mean by "an extremely cloud used project"? Do you have an example project where you see this issue?

try any multiplayer game, because the variables are being set rapidly, it will activate the banner and it gets distracting and in the way:


### **_i haven't tested, i believe this may of been fixed by accident with the creation of the cloud limit_**

**Comment by kchadha** [comment]
cc / @paulkaplan
