### ISSUE TITLE
Not All the Backdrops Have Size / Resolution Info

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-gui#36]
### The Backdrops Don't All Work Because Several of Them Are Missing Size / Resolution Info

I assume you already know this, but talking is fun.

Specifically:

- atom playground
- beach malibu
- bedroom1
- bedroom2
- bench with view

and 74 others have empty "info".

**Comment by SillyInventor** [comment]
The solution should eventually be to get size from the image itself and to calculate it's own scaling, but I added it into the library for the time being if you want a pull request.

**Comment by thisandagain** [comment]
A PR to add it into the library for the time being would be great!

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-gui/pull/38
