### ISSUE TITLE
Clicking 'New' does not clear canvas

### ISSUE THREAD

**Issue by NitroCipher** [LLK/scratch-gui#3612]
After loading with the pen tool, clicking 'File>New' to reset the project, will **not** clear the canvas.

load this [example](https://llk.github.io/scratch-gui/develop/#248744218), run it (in turbo), and then click File>New

**Comment by benjiwheeler** [comment]
Thanks for noticing this!

We are tracking this problem in this issue: https://github.com/LLK/scratch-gui/issues/1850

I'll add your example there.
