### ISSUE TITLE
Language selecter doesn't keep open on Firefox

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#3613]
### Expected Behavior
It should work!

### Actual Behavior
It doesn't keep open. When I click the glove, the menu appears, and soon disappears.

### Steps to Reproduce
Change language on Firefox.

### Operating System and Browser
Windows 7 HomePremium 64bit SP1
Firefox 63

**Comment by benjiwheeler** [comment]
Thanks for catching this. Does it seem worse than before https://github.com/LLK/scratch-gui/pull/3583 was merged (yesterday)?
