### ISSUE TITLE
Remix when project has a cloud variable causes BSOD

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3616]
to repro:
1. in 2.0, as a logged in scratcher, create a project that uses a cloud var, and include a cloud var change block in the scripts area
2. open it in 3.0 as a *different* logged in user
3. remix it
4. BSOD

This might be related to the cloud char?

**Comment by thisandagain** [comment]
@BryceLTaylor @benjiwheeler @kchadha Can you confirm that this is resolved?

**Comment by kchadha** [comment]
I can confirm that this has been resolved. I tried reproing in multiple ways, including remixing a 2.0 project as described above in 3.0 in both the project page view and going to the editor first and then remixing. I did the same where the original project was a 3.0 project and tried remixing that project from both the project page view as well as editor view. I never got a BSOD.
