### ISSUE TITLE
Swap Download and Upload above Save

### ISSUE THREAD

**Issue by kosiecki17** [LLK/scratch-gui#3617]
### Current Behavior
The _Upload from your Computer_ and _Download to your computer_ are at the bottom of the File menu, below the currently non-functioning _Save Now_ and _Save as a copy_ options.

### Desired Behavior
We'd like to move the Upload and Download options above the Save options to increase their visibility unto the Save options are functional.

<img width="417" alt="upload_download" src="https://user-images.githubusercontent.com/25378759/47926955-6246c300-de98-11e8-871e-f5b664c218da.png">

**Comment by benjiwheeler** [comment]
How about not showing the save and save now options at all? I know we want to use the beta to preview the interface so people have a sense of what to expect, but maybe we can leave out save and save now, to clarify that upload/download are what people should use for now?

**Comment by thisandagain** [comment]
@benjiwheeler I think that may be the better way to go. Do you mind if I add this to your plate for the next week or so?

**Comment by benjiwheeler** [comment]
@thisandagain No problem

**Comment by benjiwheeler** [comment]
Spoke to @kosiecki17 and @kathymakes about this, we agreed to take Save now and Save as a copy out of beta for the time being.
