### ISSUE TITLE
Block pane scrolling difficulties (trackpad)

### ISSUE THREAD

**Issue by liam4** [LLK/scratch-gui#362]
### Expected Behavior

Scrolling immediately responds to my trackpad gestures and does not behave automatically.

### Actual Behavior

By "flicking" the trackpad to scroll up (see steps to reproduce), this:

![GIF](https://cloud.githubusercontent.com/assets/9948030/26013247/e0e18448-372d-11e7-8c5d-6339c28fc152.gif)

### Steps to Reproduce

1. Using the mouse, drag the block palette scrollbar down so that the palette is scrolled down all the way.
2. Using a trackpad gesture, "flick" so that the block palette is scrolled up, in the same way you'd quickly scroll up a webpage.

I think this has to do with the Macbook's "smooth" scrolling feature, where the scrolling speed decelerates once the fingers are lifted from the trackpad (instead of immediately stopping). I have no idea where the code causing this issue would be, but I'd guess that the distance scrolled in a single frame is "countered" by some value (perhaps set at the beginning of the scroll gesture), which causes the scrolling to become faster in the opposite direction.

(There's probably already an issue opened for this topic - I remember reading about scrolling issues in this repo recently - but I can't seem to find it..)

### Operating System and Browser

macOS 10.12.4, Chrome 57.0.2987.133. Running on a MacBook Pro. "Scroll direction: Natural" is enabled in the trackpad preferences.

**Comment by chrisgarrity** [comment]
@liam4 is this still happening? We think it may have been fixed in https://github.com/LLK/scratch-blocks/pull/874

**Comment by liam4** [comment]
Nope, none of these issues at all. Scrolling works as expected. :tada:
