### ISSUE TITLE
Costume Tab Pane Doesn't Update on New Costume

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-gui#365]
### Expected Behavior

Should display all costumes of sprite.

### Actual Behavior

Doesn't show last costume added.

### Steps to Reproduce

1. go to https://llk.github.io/scratch-gui/ 
2. go to costumes
3. go to add costumes
4. select costume

### Operating System and Browser

Ubuntu 16.01, Chrome 58.0.3029.110

**Comment by paulkaplan** [comment]
Yup, this is actually a problem with the way events are being emitted from the VM. Should be fixed by this PR on the VM https://github.com/LLK/scratch-vm/pull/568

**Comment by paulkaplan** [comment]
Closing because LLK/scratch-vm#568 was merged which fixes this.
