### ISSUE TITLE
Monitor sliders don't change by 1 when clicked on

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#3668]
### Expected Behavior
In 2.0, clicking sliders to either side of the circle changed the value by 1
![sliderfeature](https://user-images.githubusercontent.com/2855464/48097443-e3c78980-e1e7-11e8-93ab-01e7d1c0b848.gif)

### Actual Behavior
In 3.0, clicking on the slider track moves the slider all the way to that position

### Steps to Reproduce
1. In 3.0, make a variable monitor
2. Double click the monitor to make it a slider monitor
3. Click on the slider monitor track and observe the difference in behavior

### Operating System and Browser
Windows 10 Chrome

**Comment by paulkaplan** [comment]
But... but... that's not how sliders work :( :( 

@thisandagain thoughts on whether we need to conserve this behavior from 2.0?

**Comment by thisandagain** [comment]
@paulkaplan Yeah. This actually feels like a bug in 2.0 rather than a feature. I'm inclined to keep our current behavior.

**Comment by towerofnix** [comment]
Fair judgment, but I have seen several projects which make use of sliders which allow you to easily change by one. But they're not super common.

Aside: Should using the scroll wheel while the mouse is over a slider change its value? It might be an interesting interaction to play with.
