### ISSUE TITLE
Make native packages with electron

### ISSUE THREAD

**Issue by argan** [LLK/scratch-gui#3671]
### Expected Behavior

build native packages with electron 

### Actual Behavior

none.

**Comment by towerofnix** [comment]
Actually the Scratch Team is already working on this. The repository, `scratch-desktop`, is still very new and not quite stable, so it's closed source, but the ST [is planning](https://github.com/LLK/scratch-gui/pull/3200#issuecomment-424078736) to make it open-source later on.
