### ISSUE TITLE
Extensions Library Phase 2

### ISSUE THREAD

**Issue by evhan55** [LLK/scratch-gui#3675]
Create new extension library gui elements based on this design:

<img width="965" alt="screen shot 2018-11-07 at 10 37 50 am" src="https://user-images.githubusercontent.com/699840/48141650-4e74d580-e279-11e8-88dc-06b43e0eac7b.png">

**Comment by evhan55** [comment]
@thisandagain @ericrosenbaum @carljbowman 
For the hardware extensions, do they also require wifi?  In which case, would two icons need to go under 'Requires'?

**Comment by ericrosenbaum** [comment]
The wifi indicator is there specifically to indicate the extensions that use web services to request data, so they won't work in a situation where you have no network connection (i.e. we are using web services for text to speech and translation, and probably other ones in the future). The distinction is only really relevant for the "desktop" version of scratch. With no network connection, you can't use scratch on the web. But you can use the desktop version, in which case you'll be able to use the hardware extensions without a problem, but the web service extensions will not work. 

Does that seem right to you @carljbowman?

**Comment by carljbowman** [comment]
Thanks for following up @ericrosenbaum! All that sounds correct to me. 

It does raise the question of if the wifi icon is the right icon to communicate needing a internet connection for using web services, but for now I think we move forward with the wifi icon and circle back when we have some more time to reconsider.

**Comment by evhan55** [comment]
Thanks @ericrosenbaum and @carljbowman !

@carljbowman are the wifi and bluetooth icons somewhere else in GUI or do I need them from someone?

**Comment by wwj718** [comment]
I have a supplement:  `scratch link` require wifi to use DNS ([device-manager.scratch.mit.edu:20110](https://github.com/LLK/scratch-vm/blob/develop/src/io/ble.js#L2) -> 127.0.0.1:20110) ,  so that all hardware extensions require wifi.

**Comment by carljbowman** [comment]
@evhan55 here are those icons: [requirement-icons.zip](https://github.com/LLK/scratch-gui/files/2562204/requirement-icons.zip)


I exported them at 100% transparency, we should set the opacity to 75% with CSS.

**Comment by evhan55** [comment]
@carljbowman Cool, thanks! Speaking of which, what color/opacity is the 'Requires/Collaboration with' text?

**Comment by carljbowman** [comment]
Same thing opacity as the icons: 75%. You can use `$text-primary` for the color.

**Comment by evhan55** [comment]
@carljbowman Perfect, I will try that, thanks!
