### ISSUE TITLE
Device disconnected alert "reconnect" button seems to do nothing in full screen mode

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#3685]
### Expected Behavior

It's not totally clear to me what should happen in this case: You have a hardware extension device connected, such as a microbit, you're in full screen mode, it becomes disconnected, you see the alert, and you click on the reconnect button. Maybe it should switch you out of full screen mode, so you can interact with the device connection modal? Or maybe the device connection modal should show up on top of the full screen player?

There's a related question for what should happen when you're on the project page.

cc @carljbowman 

### Actual Behavior

Currently, if you have a microbit connected, and you're in full screen, and you get disconnected, and click the "reconnect" button, nothing seems to happen aside from the alert being dismissed. When you manually exit full screen mode, the device connection modal is showing.

<img width="874" alt="screen shot 2018-11-07 at 5 46 13 pm" src="https://user-images.githubusercontent.com/567844/48166134-a4676e80-e2b5-11e8-9bbf-25760bba3ff1.png">

### Steps to Reproduce

- Connect a microbit
- Enter full screen mode
- Disconnect the microbit by switching off its battery and waiting a few seconds
- Disconnection alert should appear
- Click the "reconnect" button

**Comment by benjiwheeler** [comment]
For now, we resolved this by altering the z-index of alerts so they show below fullscreen. Tracking this in https://github.com/LLK/scratch-gui/issues/3837
