### ISSUE TITLE
Make alerts appearance/alignment match spec

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3686]
There's a detailed alerts design spec here: https://github.com/LLK/scratch-gui/issues/2956

But the alerts need some CSS work to make them appear correctly.

As @paulkaplan mentioned in [this comment](https://github.com/LLK/scratch-gui/pull/3559#issuecomment-436633483) on https://github.com/LLK/scratch-gui/pull/3559 :

> there are some pretty rough alignment issues. They were pre-existing, but look much worse with the new alerts because of the icon height... [we should] remove the various top margins, use flex / align-items: center instead

Example of the current wonky look:
![screen shot 2018-11-07 at 6 57 13 pm](https://user-images.githubusercontent.com/3431616/48168842-fb257600-e2be-11e8-9b82-282bea122a17.png)

Also, there are some icons that don't seem to be being used yet, such as the WiFi icon.

**Comment by kathymakes** [comment]
<img width="661" alt="alert re-spec" src="https://user-images.githubusercontent.com/8203939/49898288-9eb9f700-fe26-11e8-95b8-5e583ec1ab74.png">

**Comment by benjiwheeler** [comment]
Reopening per @kathymakes's comment; will hopefully be closed by outstanding PR
