### ISSUE TITLE
Backdrop / Sprite Import

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-gui#37]
### Expected Behavior

Should click new backdrop, and on the new screen, should be able to select import, then select a backdrop

### Actual Behavior

No such import button / function

I will need to add this for the local play test over here. If you all have this in the works, let me know.

**Comment by thisandagain** [comment]
Go for it! We have some work going on right now for the sprite and costume libraries but nothing for backdrops. A PR would be most welcome. 😄

**Comment by thisandagain** [comment]
Tracking in other issues / repos.
