### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by lasiaz** [LLK/scratch-gui#3707]
### Expected Behavior

hide loading

### Actual Behavior

loading

### Steps to Reproduce

1. in chrome open AngularJS Inspecto extension
2. open https://beta.scratch.mit.edu/
3. always loading

### Operating System and Browser

Mac OS 10.13.6 chrome 70

**Comment by ntlrsk** [comment]
I believe this may the same error: On Cynthia S's Macbook Air (early 2014 8 GB) at our workshop in LLK yesterday Chrome remained stuck on the loading screen which seemed to be in an infinite loop (Repeating: Loading sprites, sounds, extensions). 

On Safari the beta opened without a problem. (We tried restarting with nothing else running and it was the same problem in Chrome.) She had recently updated her OS and then installed the patch to see if it helped but it didn't.

To reproduce simply to beta.scratch.mit.edu and click Try it!

Macbook Air 11-inch Mojave OS Version 10.14 
Chrome 70.0.3538.102 (Official Build)(64-bit) - "Google Chrome is up to date"

**Comment by benjiwheeler** [comment]
I have a 2012 11-inch Macbook Air at home, I can try replicating this

**Comment by thisandagain** [comment]
@BryceLTaylor Can you attempt to repro this on one of our older MacOS machines?

**Comment by BryceLTaylor** [comment]
I just tested this on a mac from mid 2011 running 10.11.6 and chrome 67 and it gives the "Your Browser Does Not Support WebGL" message.  It may be an issue with newer ones.
