### ISSUE TITLE
Text clipping after switching tab

### ISSUE THREAD

**Issue by ethanmriley** [LLK/scratch-gui#371]
After switching between Backdrops and a sprite, text in the Scripts tab is shifted over, cutting it off.

![text_clipping](https://cloud.githubusercontent.com/assets/12638154/26177508/e1bed7b4-3b27-11e7-841c-0738ea6fbc8d.gif)

### Steps to Reproduce

1. While a sprite is selected and scripts are not visible, select Backdrops (or vice versa).
2. Click the "scripts" tab

### Operating System and Browser

Windows 10, Firefox 53.0.2 (32-bit)
Ubuntu 16.04, Firefox 53.0 (64-bit)

**Comment by paulkaplan** [comment]
I believe this is the same as this issue: https://github.com/LLK/scratch-gui/issues/270. 

That has been fixed, but has not been deployed to the production version yet.
