### ISSUE TITLE
Tutorials window needs design work

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-gui#3719]
We noticed in a couple of workshops that the tutorials window design is still challenging to use.
Here's an example of the window we're referring to:

<img width="1552" alt="screen shot 2018-11-09 at 6 28 26 pm" src="https://user-images.githubusercontent.com/8203939/48293480-4d949d00-e44d-11e8-8d68-4642ae801219.png">

### Next steps
We should spend some time thinking about:
- The size/positioning of the tutorials, particularly on lower resolution screens
- How to make the video to cards transition easier (the arrow is still hard to notice even after KO added an illustration.)

**Comment by Alzter** [comment]
Maybe there could be a sidebar that has walk-through tutorials you can select from? And I don't just mean a slideshow of the steps to do like in Scratch 2.0, what if it was actually interactive and walked you through the steps? It would be cool if there was a tutorial system that guides you through the basic system of how things work when going into the project editor for the first time but also has more advanced tutorials that cover things like variables, broadcasts and custom blocks for people wanting to learn more.

I also would be really happy if the help icon that let you select anything like from prior versions returned, as well as help for each individual block. (Personally I prefer the Scratch 1.4 block help to the 2.0 ones, it's more detailed.)

**Comment by thisandagain** [comment]
We've made a few updates. Closing this for now pending larger tutorials design pass.
