### ISSUE TITLE
Sprite info number inputs accept text

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#3721]
### Expected Behavior

You shouldn't be able to type text in the sprite info inputs which are expected to only accept numbers, e.g. "size" or "x".

### Actual Behavior

You can type text in those inputs. Once you press enter or de-focus the input, the value will reset to whatever it was before.

### Steps to Reproduce

Type text into any of the number-based inputs in the sprite info area above the sprite palette (any of the ones in the screenshot below).

![The x, y, size and direction inputs in the sprite info area](https://user-images.githubusercontent.com/9948030/48307078-ded24500-e51b-11e8-8da3-ea79081b0eca.png)

### Operating System and Browser

Firefox 64.0b6, Debian (Linux).

---

See also LLK/scratch-blocks#1779, which is similar but not quite the same.

**Comment by ericrosenbaum** [comment]
Update, literally years later: we're looking at this again, and it turns out that our team decided that the current validation behavior of these fields is what we want (i.e. allowing people to type in letters etc. even though they are later validated away).
