### ISSUE TITLE
window 7 cannot watch scratch 3.0 now.

### ISSUE THREAD

**Issue by crouse12** [LLK/scratch-gui#3722]
### Expected Behavior
I hope that scratch 3.0 can be watched online in Win7. 
_Please describe what should happen_

### Actual Behavior
Scratch 3.0 cannot be watched in Win7 Computer now.
_Describe what actually happens_
This site can not be watched if I use win7 computer.
https://beta.scratch.mit.edu/
### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser
Win 7 and chrome
_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
I use Win7 Firefox/Chrome and is working.
Maybe your PC doesn't support WebGL or your chrome is not the latest

**Comment by crouse12** [comment]
I find that the avast antivirus software plugin will block scratch 3.0.
When I stop this plugin of my chrome, I can use scratch 3.0.
