### ISSUE TITLE
Filter for letter sprites in library

### ISSUE THREAD

**Issue by kosiecki17** [LLK/scratch-gui#3726]
Add filter for letter sprites to the top bar of the sprite library. 

This is particularly important for the Animate a Name tutorial.

<img width="856" alt="sprite-filters" src="https://user-images.githubusercontent.com/25378759/48388065-14b32d00-e6c6-11e8-955a-f288d10be374.png">

**Comment by kosiecki17** [comment]
Note: The Letters filter can be added to the end of the list after Fashion.

Thanks!

**Comment by thisandagain** [comment]
@kosiecki Would we like to do this for letter costumes as well?

**Comment by thisandagain** [comment]
@paulkaplan Could you take this?
