### ISSUE TITLE
Alerts phase 2: saving

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3727]
@carljbowman, @kathymakes and @benjiwheeler identified this iteration of alerts-related work:

https://github.com/LLK/scratch-gui/pull/3776 addresses many of the points below:

- [x] editor menu bar should have a place to display messages (PR: https://github.com/LLK/scratch-gui/pull/3776 )
  * this is tracked in: https://github.com/LLK/scratch-www/issues/2275
  - [x] support for different text modes
    - [x] in progress (dim)
    - [x] done (normal/bold)
  - [x] saving should display in menu bar only (creating/remixing/saving copy can still have alerts) 
- [x] alerts should dismiss themselves after a certain amount of time (Issue: https://github.com/LLK/scratch-gui/issues/3763 ; PR: https://github.com/LLK/scratch-gui/pull/3776 )
- [x] when save fails: tracked in https://github.com/LLK/scratch-gui/pull/3835
  - [x] abort navigation
  - [x] message in menu bar about error
  - [x] return to default, showing_with_id state
(low priority)
- [x] tiny saving progress spinner (PR: https://github.com/LLK/scratch-gui/pull/3776 )
- [ ] messages use queue, with minimum display time so it's not too fast (not doing this now; tracking in https://github.com/LLK/scratch-gui/issues/3841

**Comment by kathymakes** [comment]
Thanks for writing this up @benjiwheeler ! We should figure out an amount of time to display "Saved" - how many seconds should it stay up there? if changes _are_ made immediately after, does the message go away, or not? 

Also, I'm kinda partial to making "Saving" bold and "Saved" dimmed - in case we ever add a timestamp modal. ("Saved 4 minutes ago" could be dimmed, for instance.)

**Comment by benjiwheeler** [comment]
Will go with "Saving" bright and prominent, and "Saved" dimmed.

Starting with the "Saved" message staying visible for 5 seconds; let's see how it feels.

With https://github.com/LLK/scratch-gui/pull/3776 , messages will replace each other immediately.
