### ISSUE TITLE
Don't ask user to "replace contents of the current project" if that's not what they're doing!

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3744]
signed in to scratch.ly, looking at someone else’s project, File->New currently pops up “replace contents of current project?” but that’s super misleading… maybe “leave without saving?”

**Comment by Alzter** [comment]
When I first used File>New I thought I had erased everything in the project I was on, not created a new one.

**Comment by benjiwheeler** [comment]
@alzter, do you mean in Scratch 2.0, or in the 3.0 Beta?

**Comment by Alzter** [comment]
In Scratch 2.0
