### ISSUE TITLE
Variables incorrectly displayed on stage

### ISSUE THREAD

**Issue by ethanmriley** [LLK/scratch-gui#375]
### Expected Behavior

Like Scratch 2.0, clicking the check mark next to a variable displays the name and value of that variable on the stage.

### Actual Behavior

Only one variable, "data_variable," is ever displayed on the stage, regardless of the number of selected variables. 
The value of "data_variable" is the value of whichever variable was most recently selected. 

![variable_display](https://cloud.githubusercontent.com/assets/12638154/26269981/3ee3829c-3cc6-11e7-9f97-92b812f4f084.gif)

### Steps to Reproduce

1. Navigate to [the Scratch gui](https://llk.github.io/scratch-gui/).
2. In the "Data" panel, create two variables with different values. 
3. Select one or the other, and the bug is evident. 

### Operating System and Browser

Windows 10, Chrome 58.0.3029.110 (64-bit)

**Comment by TheBrokenRail** [comment]
Also, if you uses a motion of any other category reporter, the monitor still uses the variable colors.
