### ISSUE TITLE
Modal (Alert) when a project or asset fails to save

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#3761]
Part of https://github.com/LLK/scratch-gui/issues/3723

In any case where the project fails to save, we should display a modal to the user while we begin retrying.

The modal should have a button which will download the SB3 of the project to the user's computer.

**Comment by kathymakes** [comment]
BTW, here's one example of how we could do an alert. Can change the language to be more generic. 

This would appear after a few (currently it's 3?) failed saves. The timer will keep counting down in the nav...

![alert_1](https://user-images.githubusercontent.com/8203939/49092785-c1e28500-f230-11e8-83c0-a89b9ed9ee5c.png)

**Comment by kathymakes** [comment]
After talking to @carljbowman and @paulkaplan, decided to go with this UX + language:

### UX for save error

1. The system will keep trying to autosave, and go through this countdown process 3 times...
![1](https://user-images.githubusercontent.com/8203939/49171554-c8dec580-f30c-11e8-8694-95da9ac2b8aa.png)

2. After 3 failed attempts, fire this alert. We should still be checking periodically for reconnection as often as possible, but users have the option to "Try Again" immediately or "Download."
![2](https://user-images.githubusercontent.com/8203939/49171555-c8dec580-f30c-11e8-8270-a1539edccdf9.png)

3. After either clicking "Try Again" or once we can detect reconnection, then fire this alert instead...
![3](https://user-images.githubusercontent.com/8203939/49171556-c8dec580-f30c-11e8-99b6-1ca5bff2ed3f.png)
(If it fails, go back to alert in #2.)

4. Alert disappears. Project immediately saves, using the title bar convention.
![4](https://user-images.githubusercontent.com/8203939/49171557-c8dec580-f30c-11e8-8dbd-29cdc65eef8e.png)

5. If save succeeds, show this after 1-2 seconds. 
![5](https://user-images.githubusercontent.com/8203939/49171559-c8dec580-f30c-11e8-8c3d-b384319a762e.png)
If save fails (for some reason), revert to #1.

**Comment by benjiwheeler** [comment]
A note from discussion with @kathymakes -- we may want to make the #3 "Reconnecting..." alert appear for a set number of seconds, before returning to #2 "Project could not save" alert. This might require setting alerts to specifically only show one at a time (like inline menu bar alerts do)
