### ISSUE TITLE
Handle network timeouts when saving projects

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#3762]
Part of #3723

If there is no network connection while saving a project, we should display a modal to the user (#3761), and we should begin retrying the save, backing off the time between retries exponentially as we wait for a re-connection to a network.

**Comment by benjiwheeler** [comment]
Folded into https://github.com/LLK/scratch-gui/issues/3764

**Comment by apple502j** [comment]
@benjiwheeler @rschamp This should not be folded, that issue says "if we receive an error status as a response from the asset or project servers". Timeouts are not an API response, it's an error saying there was no response.

Currently, [timeout option](https://www.npmjs.com/package/xhr#optionstimeout) is not [specified](https://github.com/LLK/scratch-gui/blob/develop/src/lib/save-project-to-server.js#L18) for project API, meaning there is no timeout.

### Issues
There are a lot of BaG posts saying saving takes forever recently. Those all mention taking long time to save:
* [Fix the saving problem](https://scratch.mit.edu/discuss/post/3871147/) - "5 minutes"
* [Saving issue fix](https://scratch.mit.edu/discuss/post/3871446/) - "forever"
* [Projects will NOT save, at all](https://scratch.mit.edu/discuss/post/3869764/) - "stuck at Saving projects..."
* [Cannot Remix Projects](https://scratch.mit.edu/discuss/post/3871016/) - "for a long time"
* [Why are my projects taking forever to save?](https://scratch.mit.edu/discuss/post/3870396/) - "forever"
* [Saving takes forever](https://scratch.mit.edu/discuss/post/3870688/) - "literally forever"
* [Saving Forever](https://scratch.mit.edu/discuss/post/3870421/)
* [Project Saving](https://scratch.mit.edu/discuss/post/3870446/) - "FOREVER"
* [uhm...](https://scratch.mit.edu/discuss/post/3869902/) - "forever"
* [When I upload a sprite, the project can't save.](https://scratch.mit.edu/discuss/post/3869636/) - "stuck saving"
* [Scratch wont save my project! Only saves when no sprites are in the editor??](https://scratch.mit.edu/discuss/post/3869603/) - "never does the save"
* [Project can't save](https://scratch.mit.edu/discuss/post/3866072/) - "forever"

Those seem to be happening between March 9 and March 13.

**Comment by rschamp** [comment]
@apple502j Thanks for the input. #3764 incorporates network timeout errors if you read the section outlining the types of errors we should handle. To fully resolve it we will need to properly detect and respond to timeouts.

**Comment by griffpatch** [comment]
I can confirm that I have seen a lot of failed saves recently too.
It occurs almost every time I load a scratch project from disk over an
existing project, even for projects that are not very big.
