### ISSUE TITLE
How to determine if the program is loaded?

### ISSUE THREAD

**Issue by abattle** [LLK/scratch-gui#3765]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by thisandagain** [comment]
@abattle Please provide more information so we (and others from the community) can help answer your question.
