### ISSUE TITLE
On iOS, sound editor can get stuck and stop working

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#3773]
@kchadha reports on iOS: "Sound editor waveform playhead stays stuck in one place and play button gets stuck on stop… Also sound doesn’t play… (needs consistent repro)"

**Comment by BryceLTaylor** [comment]
I've been unable to reproduce this.  I would need more information about the conditions where this was seen before I dig any deeper.

**Comment by kchadha** [comment]
I also cannot reproduce.
