### ISSUE TITLE
save project

### ISSUE THREAD

**Issue by crouse12** [LLK/scratch-gui#3781]
In file of menu, I only see "download to your computer". However, "save as a copy" disappears. In the source code,  I find 
                                <MenuSection>
                                    {this.props.canSave ? (
                                        <MenuItem onClick={this.handleClickSave}>
                                            {saveNowMessage}
                                        </MenuItem>
                                    ) : []}
                                    {this.props.canCreateCopy ? (
                                        <MenuItem onClick={this.handleClickSaveAsCopy}>
                                            {createCopyMessage}
                                        </MenuItem>
                                    ) : []}
                                    {this.props.canRemix ? (
                                        <MenuItem onClick={this.handleClickRemix}>
                                            {remixMessage}
                                        </MenuItem>
                                    ) : []}
                                </MenuSection>
Do you implement them in the further?

**Comment by benjiwheeler** [comment]
In beta.scratch.mit.edu, we are not going to enable saving projects.

The `save now` and `save as a copy` menu items will be enabled when we launch in January.
