### ISSUE TITLE
Fail to load several images/sounds when built

### ISSUE THREAD

**Issue by kevster** [LLK/scratch-gui#379]
### Expected Behavior

Expected to clone, build and run scratch-gui with all assets loaded.

### Actual Behavior

After cloning, installing and building scratch-gui, some images and sounds fail to load when opening index.html in a browser. This does not happen if I just run the project locally!

### Steps to Reproduce

1. Clone repo
2. npm install
3. npm run build
4. open index.html from the /build-folder in a browser (Chrome/Safari tested)

If instead of step 3+4 I 'npm start' and open the URL shown in the console (http://0.0.0.0:8061) it works, so I'm guessing there might be a problem with the build-script?

### Operating System and Browser

MacOS 10.12.5 and Chrome 58 / Safari 10.1.1

**Comment by paulkaplan** [comment]
Which assets specifically?

@rschamp @thisandagain correct me if I'm wrong, but I believe that the build directly needs to be served and the index.html cannot just be opened as a file. You can serve the build directly using any kind of http server, for example by entering the build directory and running `python -m SimpleHTTPServer` and going to localhost:8000

**Comment by rschamp** [comment]
Correct. Remote urls are blocked on  pages loaded via `file://` for security reasons.

**Comment by kevster** [comment]
Ah of course, I should've known. It does work when served.
