### ISSUE TITLE
Tutorials library displays incorrectly when "music" filter is selected

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#3790]
### Expected Behavior

Tutorial library tiles should display consistently

### Actual Behavior

The tutorial library displays incorrectly with "music" selected:

<img width="1276" alt="screen shot 2018-11-15 at 3 39 07 pm" src="https://user-images.githubusercontent.com/567844/48580422-304c4c80-e8ed-11e8-85cd-6cba358cd3cc.png">

Actually the bug is that the large-size tiles used in the tutorials and extension libraries display incorrectly when there is only a single row visible (so you can see the issue in other places by e.g. zooming out the browser or making the window wide enough). 

cc @evhan55

**Comment by evhan55** [comment]
@ericrosenbaum @carljbowman 
oooh!  Is there an ideal min-height here?
