### ISSUE TITLE
Loading two projects consecutively can lead to weird state

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#3797]
@rschamp (on Mac Firefox) noted:

> Loading https://llk.github.io/scratch-gui/smoke/#15200040 followed by https://llk.github.io/scratch-gui/smoke/#105250254 leads to a display of the first project’s workspace with the second project’s stage  @rschamp 
![image30](https://user-images.githubusercontent.com/1088291/46353885-3c28cb80-c62b-11e8-950a-e4e62489c269.png)

Found in bug hunt on 09/28

**Comment by BryceLTaylor** [comment]
I'm unable to reproduce this.
