### ISSUE TITLE
error alert design

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3822]
Currently, project saving or creation alerts look like: 

![screen shot 2018-11-16 at 6 42 37 pm](https://user-images.githubusercontent.com/3431616/48652817-75e14600-e9cf-11e8-9f93-a6ff2b176825.png)

Is there an error/warning icon that we could use here? Any other design we want to introduce in this version?

**Comment by kathymakes** [comment]
@benjiwheeler It would be good to consider this together with the conversation about "network connectivity error" modal...  More info: https://github.com/LLK/scratch-gui/issues/3761

My gut reaction is we could reuse this same messaging? What do folks think?

Here's the image. It gives you an option to "try again" or "download": 

![image](https://user-images.githubusercontent.com/8203939/49098386-bf862800-f23c-11e8-8932-9f79445a7058.png)

**Comment by benjiwheeler** [comment]
@kathymakes and I discussed this. If it's possible to distinguish between saving errors caused by connectivity, and errors that have other causes, it may still be good to have a distinct error alert design to use.

**Comment by kathymakes** [comment]
From what I understood, this message wants to cover cases unrelated to saving... such as trying to create, remix, or save a copy. This should ideally appear *right after* someone has tried to perform one of these actions (and we aren't able to process their request for some reason.) 

This error doesn't really give someone a good way forward, so should be used as sparingly as possible. (Someone from here might only be able to refresh the page for examples)

![rare error](https://user-images.githubusercontent.com/8203939/49228974-8b387600-f3ba-11e8-8815-8984e2d19f0c.png)

**Comment by DeleteThisAcount** [comment]
mabye some kind of page should be created to have more details?

Something went wrong. Please try again. If this problem persists please read _insert page here_
