### ISSUE TITLE
Story not in Letters

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#3827]
"Story" letters are not in Letters category.

https://github.com/LLK/scratch-gui/blob/develop/src/lib/libraries/costumes.json#L11232
Making it `letters` will solve this.

**Comment by thisandagain** [comment]
@kosiecki17 Can you take a look at this while you are doing other work in the libraries?

**Comment by kosiecki17** [comment]
The tags have been updated on the Story letter sprites.

**Comment by apple502j** [comment]
@kosiecki17 not fixed yet
