### ISSUE TITLE
Load Button Surroundings Don't Open Dialog

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-gui#383]
### Expected Behavior

Clicking on highlighted area should open dialog

### Actual Behavior

You must click on text of load to open dialog

### Steps to Reproduce

1. Go to https://llk.github.io/scratch-gui/
2. Hover over load
3. Click area around but not on load

### Operating System and Browser

Ubuntu 16.01, Chrome 58.0.3029.110

**Comment by paulkaplan** [comment]
Those buttons are gone, and the ones that replaced them do not have this problem
