### ISSUE TITLE
3.0 disappears when language is toggled to Spanish

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#3838]
### Expected Behavior

All sounds should be available across languages

### Actual Behavior

When the disconnect sound 

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by paulkaplan** [comment]
Thanks for the report, unfortunately I do not understand what is being reported. The title is "3.0 disappears", but that doesn't seem to be true... I suspect this is more fleshed out in https://github.com/LLK/scratch-gui/issues/3839, so I'll close this.

**Comment by techwonder21** [comment]
You can ignore this. I originally thought the "disconnect" sound appeared in English but not other languages. After doing some testing, I realized that the "disconnect" sound had been removed entirely from Scratch 3.0.
