### ISSUE TITLE
What should the messaging/UX be for creating new project?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3846]
Currently, File->New for a logged in user does:

1. saves current project (messaging in menu bar)
2. shows blue loading project screen
3. shows creating alert
4. shows successfully created alert
5. saves new project (messaging in menu bar)

![new](https://user-images.githubusercontent.com/3431616/48787970-d7e3c900-ecb7-11e8-951a-2294f3336921.gif)

Question: can this be streamlined or simplified? How can the action be made more clear and intuitive to the user?

**Comment by kathymakes** [comment]
Thanks for making this issue Ben! My take is that it'd be great to:

1. save current project
2. flash the blue loading screen for 1-2 seconds
3. show new project (saving)

We could even change the "Loading Project" string to "Creating Project" if that would make it more clear. I think the blue loading screen and "creating" alert are (intending to) communicate the same thing, and having both feels a bit redundant to me

**Comment by benjiwheeler** [comment]
From discussion, @kathymakes and I agreed that using the blue loading screen is better than using popup alerts for this.

It also relates to https://github.com/LLK/scratch-gui/issues/3902
