### ISSUE TITLE
An error page is displayed when access the landing page

### ISSUE THREAD

**Issue by zarknight** [LLK/scratch-gui#3860]
### Behavior

After I download the source code and run it according the README guides, no compile errors on the command line, everything seems ok. But when I access the page with http://0.0.0.0:8601/ in my browsers, I will see an error page with messages:

>Oops! Something went wrong.
>
>We are so sorry, but it looks like Scratch has crashed. This bug has been automatically reported to the Scratch Team. Please refresh your page to try again.

And I saw some error message in the browser's DevTool console:

> Uncaught TypeError: this.renderer.setLayerGroupOrdering is not a function
    at Runtime.attachRenderer (lib.min.js:251852)
    at VirtualMachine.attachRenderer (lib.min.js:276157)
    at new Stage (lib.min.js:313381)
    at constructClassInstance (lib.min.js:106110)
    at updateClassComponent (lib.min.js:107594)
    at beginWork (lib.min.js:107980)
    at performUnitOfWork (lib.min.js:109979)
    at workLoop (lib.min.js:110043)
    at HTMLUnknownElement.callCallback (lib.min.js:100297)
    at Object.invokeGuardedCallbackDev (lib.min.js:100336)
lib.min.js:109502 The above error occurred in the <Stage> component:
    in Stage (created by Connect(Stage))
    in Connect(Stage) (created by StageWrapperComponent)
    in div (created by Box)
    in Box (created by StageWrapperComponent)
    in div (created by Box)
    in Box (created by StageWrapperComponent)
    in StageWrapperComponent (created by StageWrapper)
    in StageWrapper (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in div (created by Box)
    in Box (created by MediaQuery)
    in MediaQuery (created by GUIComponent)
    in GUIComponent (created by Connect(GUIComponent))
    in Connect(GUIComponent) (created by InjectIntl(Connect(GUIComponent)))
    in InjectIntl(Connect(GUIComponent)) (created by GUI)
    in GUI (created by Connect(GUI))
    in Connect(GUI) (created by InjectIntl(Connect(GUI)))
    in InjectIntl(Connect(GUI)) (created by CloudManager)
    in CloudManager (created by Connect(CloudManager))
    in Connect(CloudManager) (created by VMManager)
    in VMManager (created by Connect(VMManager))
    in Connect(VMManager) (created by VMListener)
    in VMListener (created by Connect(VMListener))
    in Connect(VMListener) (created by ProjectSaverComponent)
    in ProjectSaverComponent (created by Connect(ProjectSaverComponent))
    in Connect(ProjectSaverComponent) (created by ProjectFetcherComponent)
    in ProjectFetcherComponent (created by Connect(ProjectFetcherComponent))
    in Connect(ProjectFetcherComponent) (created by InjectIntl(Connect(ProjectFetcherComponent)))
    in InjectIntl(Connect(ProjectFetcherComponent)) (created by QueryParserComponent)
    in QueryParserComponent (created by Connect(QueryParserComponent))
    in Connect(QueryParserComponent) (created by FontLoaderComponent)
    in FontLoaderComponent (created by ErrorBoundaryWrapper)
    in ErrorBoundary (created by Connect(ErrorBoundary))
    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)
    in ErrorBoundaryWrapper (created by LocalizationWrapper)
    in IntlProvider (created by Connect(IntlProvider))
    in Connect(IntlProvider) (created by LocalizationWrapper)
    in LocalizationWrapper (created by Connect(LocalizationWrapper))
    in Connect(LocalizationWrapper) (created by TitledComponent)
    in TitledComponent (created by HashParserComponent)
    in HashParserComponent (created by Connect(HashParserComponent))
    in Connect(HashParserComponent) (created by AppStateWrapper)
    in IntlProvider (created by Connect(IntlProvider))
    in Connect(IntlProvider) (created by AppStateWrapper)
    in Provider (created by AppStateWrapper)
    in AppStateWrapper
>React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ lib.min.js:109502
lib.min.js:118859 [react-ga] called ga('send', fieldObject);
lib.min.js:118859 [react-ga] with fieldObject: {"hitType":"event","eventCategory":"Error","eventAction":"Top Level App","eventLabel":"this.renderer.setLayerGroupOrdering Is Not a Function"}
lib.min.js:118859 [react-ga] with trackers: undefined
lib.min.js:87912 gui Unhandled Error: TypeError: this.renderer.setLayerGroupOrdering is not a function    at Runtime.attachRenderer (http://0.0.0.0:8601/lib.min.js:251852:21)    at VirtualMachine.attachRenderer (http://0.0.0.0:8601/lib.min.js:276157:20)    at new Stage (http://0.0.0.0:8601/lib.min.js:313381:22)    at constructClassInstance (http://0.0.0.0:8601/lib.min.js:106110:20)    at updateClassComponent (http://0.0.0.0:8601/lib.min.js:107594:9)    at beginWork (http://0.0.0.0:8601/lib.min.js:107980:16)    at performUnitOfWork (http://0.0.0.0:8601/lib.min.js:109979:16)    at workLoop (http://0.0.0.0:8601/lib.min.js:110043:26)    at HTMLUnknownElement.callCallback (http://0.0.0.0:8601/lib.min.js:100297:14)    at Object.invokeGuardedCallbackDev (http://0.0.0.0:8601/lib.min.js:100336:16)Component stack:     in Stage (created by Connect(Stage))    in Connect(Stage) (created by StageWrapperComponent)    in div (created by Box)    in Box (created by StageWrapperComponent)    in div (created by Box)    in Box (created by StageWrapperComponent)    in StageWrapperComponent (created by StageWrapper)    in StageWrapper (created by MediaQuery)    in div (created by Box)    in Box (created by MediaQuery)    in div (created by Box)    in Box (created by MediaQuery)    in div (created by Box)    in Box (created by MediaQuery)    in div (created by Box)    in Box (created by MediaQuery)    in MediaQuery (created by GUIComponent)    in GUIComponent (created by Connect(GUIComponent))    in Connect(GUIComponent) (created by InjectIntl(Connect(GUIComponent)))    in InjectIntl(Connect(GUIComponent)) (created by GUI)    in GUI (created by Connect(GUI))    in Connect(GUI) (created by InjectIntl(Connect(GUI)))    in InjectIntl(Connect(GUI)) (created by CloudManager)    in CloudManager (created by Connect(CloudManager))    in Connect(CloudManager) (created by VMManager)    in VMManager (created by Connect(VMManager))    in Connect(VMManager) (created by VMListener)    in VMListener (created by Connect(VMListener))    in Connect(VMListener) (created by ProjectSaverComponent)    in ProjectSaverComponent (created by Connect(ProjectSaverComponent))    in Connect(ProjectSaverComponent) (created by ProjectFetcherComponent)    in ProjectFetcherComponent (created by Connect(ProjectFetcherComponent))    in Connect(ProjectFetcherComponent) (created by InjectIntl(Connect(ProjectFetcherComponent)))    in InjectIntl(Connect(ProjectFetcherComponent)) (created by QueryParserComponent)    in QueryParserComponent (created by Connect(QueryParserComponent))    in Connect(QueryParserComponent) (created by FontLoaderComponent)    in FontLoaderComponent (created by ErrorBoundaryWrapper)    in ErrorBoundary (created by Connect(ErrorBoundary))    in Connect(ErrorBoundary) (created by ErrorBoundaryWrapper)    in ErrorBoundaryWrapper (created by LocalizationWrapper)    in IntlProvider (created by Connect(IntlProvider))    in Connect(IntlProvider) (created by LocalizationWrapper)    in LocalizationWrapper (created by Connect(LocalizationWrapper))    in Connect(LocalizationWrapper) (created by TitledComponent)    in TitledComponent (created by HashParserComponent)    in HashParserComponent (created by Connect(HashParserComponent))    in Connect(HashParserComponent) (created by AppStateWrapper)    in IntlProvider (created by Connect(IntlProvider))    in Connect(IntlProvider) (created by AppStateWrapper)    in Provider (created by AppStateWrapper)    in AppStateWrapper
./node_modules/minilog/lib/web/formatters/minilog.js.logger.write @ lib.min.js:87912

### Steps to Reproduce

1. clone the repo (master branch)
2. install the npm dependencies
3. startup the app with runing npm start

### Operating System and Browser

Mac OS 10.14.1 
Chrome 70.0.3538.102 
Safari 12.0.1 (14606.2.104.1.1)

**Comment by rschamp** [comment]
Sorry you're having trouble. I've never seen this issue before. Would you please paste the output of `npm ls`?

**Comment by zarknight** [comment]
> Sorry you're having trouble. I've never seen this issue before. Would you please paste the output of `npm ls`?

I found this issue has already gone after I pull the latest code.

**Comment by rschamp** [comment]
Glad to hear it’s resolved itself.
