### ISSUE TITLE
Project 236086960 loads with no blocks

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#3871]
### Expected Behavior
This project has some custom blocks.

### Actual Behavior
No blocks appear. XML error occurs when loading it.

### Steps to Reproduce
Open https://beta.scratch.mit.edu/#236086960
2.0: https://scratch.mit.edu/projects/236086960/#player

### Operating System and Browser
On Windows 10 Firefox 63

This should be tagged as [critical]: This is one of the example programs for elementary school students and may be used in class.

This is also reproduceable on https://beta.scratch.mit.edu/#236209309

**Comment by kyleplo** [comment]
Can't repro on Windows 10 Chrome, but can on Firefox. Must be a Firefox-only bug

**Comment by thisandagain** [comment]
Looks like this may be an issue with special characters in custom procedures.

**Comment by kchadha** [comment]
If this is a special character issue, then it is probably also related to

https://github.com/LLK/scratch-vm/issues/1077

and the two should be solved together.

**Comment by kchadha** [comment]
Closing this issue as it was resolved by the PRs mentioned in LLK/scratch-vm#1077.
