### ISSUE TITLE
Compatibility - Safari 10

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#388]
### Expected Behavior

Scratch-gui should run in Safari.

### Actual Behavior

A user reported in freshdesk no. 82535 that:
> I have found that the scratch-gui can’t run properly in Safari;
> When I looked at the code, I found that the code in 'scratch-audio／src／index.js’ 237 line may be  incompatible.
> I changed the code like this:
<img width="576" alt="screen shot 2017-05-24 at 2 13 36 pm" src="https://cloud.githubusercontent.com/assets/1320456/26418712/403ff54e-408b-11e7-95a3-2a70a7e968d6.png">

> And then it works;

### Steps to Reproduce

It sounds like the repro would be using scratch-gui in Safari, but I'm not sure what else exactly.

### Operating System and Browser

_Unknown_

**Comment by ericrosenbaum** [comment]
Looks like we have multiple issues with the GUI in safari right now, and we're deferring those until later. So lets backlog this for now.

For future reference: @paulkaplan suggested there may be a version incompatibility with the web audio API, and the newer version of decodeAudioData that returns a promise is not available yet in safari.

**Comment by thisandagain** [comment]
https://llk.github.io/scratch-gui/develop/ is working well enough in Safari / Mobile Safari that I think this can be closed. We should track individual issues from here on out.
