### ISSUE TITLE
Uploading project and then changing language loads new project

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3892]
### Expected Behavior

1. start with a new project in playground/beta.
2. make any change.
3. download it
4. upload it
5. change language

The project should not change, except to reflect the language change.

### Actual Behavior

...the project will show a blue "loading" screen and the project will reset to the default.

### Operating System and Browser

Mac OS, Chrome

**Comment by BrightLin** [comment]
Did you resolve it?

**Comment by benjiwheeler** [comment]
@BrightLin Not yet.

**Comment by chrisgarrity** [comment]
@thisandagain working with @benjiwheeler we figured out that it was a project state that was missing from set_project_id. Patch is on the way.

**Comment by thisandagain** [comment]
@chrisgarrity @benjiwheeler That's great!
