### ISSUE TITLE
Save project thumbnail when the project data is saved

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3899]
There have been some reports from the Scratch team that suggest project thumbnails aren't being created consistently or correctly; this might be related to autosave not being implemented yet.

Need to confirm that project thumbnails are being created correctly.

**Comment by rschamp** [comment]
Requires https://github.com/LLK/scratch-api/issues/641

**Comment by paulkaplan** [comment]
This has been implemented!
