### ISSUE TITLE
Creating a new sprite while code tab not selected causes blocks to not run in the workspace

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3906]
### Expected Behavior

Clicking a block in the workspace should cause it to run

### Actual Behavior

If you have the sound or costume tab open and you add a new sprite, the blocks no longer run from the workspace, but they do in the flyout.

You can add a sprite either by random, uploading, or from the library, but not from painting a new one, to get this effect 

### Steps to Reproduce

Create a new project
Open the costumes tab for the cat
Add a surprise sprite
Drag a "go to random position" block to the workspace
Click the "go to random position" block
Note: nothing happens

### Operating System and Browser

Chrome on Mac

**Comment by rschamp** [comment]
Fixed by https://github.com/LLK/scratch-gui/pull/3907
