### ISSUE TITLE
MakeyMakey extension broken

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#3912]
### Expected Behavior

The extension loads

### Actual Behavior

It never loads, and there is an error in the console:
> Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': DOMException object could not be cloned.
    at https://llk.github.io/scratch-gui/develop/extension-worker.js:789:20
    at new Promise (<anonymous>)
    at WorkerDispatch._remoteTransferCall (https://llk.github.io/scratch-gui/develop/extension-worker.js:772:14)
    at WorkerDispatch.transferCall (https://llk.github.io/scratch-gui/develop/extension-worker.js:711:45)
    at WorkerDispatch.call (https://llk.github.io/scratch-gui/develop/extension-worker.js:679:32)
    at https://llk.github.io/scratch-gui/develop/extension-worker.js:253:20

### Steps to Reproduce

Try to add it

### Operating System and Browser

Windows 10 Chrome 70

**Comment by ericrosenbaum** [comment]
Thanks @kyleplo. @paulkaplan also noticed this- we should have it fixed shortly (just need to update the VM version)

**Comment by ericrosenbaum** [comment]
Fixed!

**Comment by griffpatch** [comment]
Hey guys, I just updated my local build to pull in the latest changes to scratch-gui & scratch-vm and am now getting the same error reported here when trying to use my physics extension? Is there something I can do to fix this, or is it a change in the extension framework? Thanks

**Comment by griffpatch** [comment]
Not to worry - It appears this exception is always thrown if there is a problem in the extension being loaded. In this case... the extension was not actually being compiled, and therefore didn't exist ;). An issue with me pulling the latest code and the package-lock.json being messed up and my npm links being broken. I reverted it, relinked and all is good. Sorry for bugging you :)
