### ISSUE TITLE
Outputs from blocks need translation

### ISSUE THREAD

**Issue by python-megapixel** [LLK/scratch-gui#3918]
The attached screenshot shows the Scratch 3.0 GUI in German. The issue I have noticed is that in languages other than English, "true" and "false" remain in English. I assume that these should be translated:
![image](https://user-images.githubusercontent.com/34344190/49293202-41798980-f4a7-11e8-8b0a-038b93f6df58.png)

**Comment by joker314** [comment]
Thanks! Duplicate of LLL/scratch-blocks#1685

**Comment by python-megapixel** [comment]
Whoops, sorry
