### ISSUE TITLE
Can't load projects on Edge in any way

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#3919]
### Expected Behavior
Edge is supported

### Actual Behavior
Poor Edge

### Steps to Reproduce
- Try loading project by ID on scratch.ly or develop. I always get "Oops, something went wrong", even on project page.
- Try uploading any sb2 or sb3 and uploading it to scratch.ly or develop. I always get “Project failed to load”
- Possibly related, try remixing from the project page. Nothing happens.

Console
https://pastebin.com/rTdSMy0j

### Operating System and Browser
Windows Edge

**Comment by paulkaplan** [comment]
I believe the cause of this is that `Promise.finally` is not available in Edge right now. We can polyfill it, we already have the package `core-js` included in the package.json, we just need to add this to the polyfill list: `import 'core-js/fn/promise/finally'`. 

However I noticed the polyfills are only being included in the standalone (playground) build, not in the node module. That means we need to either include the polyfills in www as well, or export the node module with the polyfills. @rschamp do you have an opinion about which to do?
