### ISSUE TITLE
Slider monitors take focus after change, and prevent when key pressed block from running correctly

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#3934]
### Actual Behavior

Title says it all.

Affects this project: https://llk.github.io/scratch-gui/develop/#118805754

### Steps to Reproduce

1. Load the project listed above
2. Click the green flag
3. Change one of the slider monitors
4. Paint something onto the nail by clicking on it
5. Press the "Clear" button on the stage
6. Press "C" on your keyboard; Observe that the info window telling you about the key options does not disappear.

**Comment by kchadha** [comment]
In a bug hunt on 10/19/18, @kathymakes and @knandersen noted:

> Press clear button, the pressing C to clear doesn’t work
> Clear button doesnt work. Blocks are being executed, but don't function

I am assuming that these are related to this issue.

**Comment by apple502j** [comment]
Duplicate of #2796

**Comment by kchadha** [comment]
Tracking in #2796
