### ISSUE TITLE
Make alerts height bigger?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3941]
Alerts height (and maybe other aspects of formatting) may need revision

![image](https://user-images.githubusercontent.com/3431616/49451161-93bef100-f7ac-11e8-8cd0-e112de3fd799.png)

**Comment by kathymakes** [comment]
Made some notes here:

<img width="661" alt="screen shot 2018-12-04 at 11 17 51 am" src="https://user-images.githubusercontent.com/8203939/49456047-4a739f00-f7b6-11e8-8765-227cc3a37370.png">

Happy to pair on this more :)

**Comment by paulkaplan** [comment]
Closing because of #4051
