### ISSUE TITLE
Update Sign-in text when in the Scratch Editor

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#3947]
### Expected Behavior

Sign-in text should be the same across both the Project Page and Scratch Editor
![projectpage](https://user-images.githubusercontent.com/3812168/49457121-4ba5cb80-f7b8-11e8-8266-21861be97f30.jpg)

### Actual Behavior

Sign-in text on the Scratch Editor is different than the Project Page
![scratcheditor](https://user-images.githubusercontent.com/3812168/49457131-51031600-f7b8-11e8-9027-cca890472768.jpg)

### Steps to Reproduce

1. Visit a Scratch project in 3.0
2. Change "project" to "preview"
https://scratch.mit.edu/preview/237965780/editor/
4. Click the "Sign in" button while in the Scratch Editor and notice the text "general.username, general.password, general.signIn, login.needHelp"
5. Click the "See Community" button, then click the "Sign in" button and notice the correct sign-in text.

### Operating System and Browser
Chrome 70, macOS High Sierra

**Comment by techwonder21** [comment]
@ChampikaF @rschamp @thisandagain

**Comment by thisandagain** [comment]
@benjiwheeler @chrisgarrity I feel like this is already being tracked, but couldn't find it. Can you please prioritize?

**Comment by benjiwheeler** [comment]
https://github.com/LLK/scratch-gui/issues/3601 exists; this should have been solved by https://github.com/LLK/scratch-gui/pull/3602
