### ISSUE TITLE
projectChanged dirty state is set to true even when project has not changed

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#3967]
### Expected Behavior

1. Make a change to a project you own in editor and save.
2. Click "See Community".
3. Click "See inside".
4. Should see nothing in title bar.

### Actual Behavior

Hm, seems like it's unnecessarily showing "Save Now"...

![dec-06-2018 09-05-50](https://user-images.githubusercontent.com/3431616/49593161-e29d8f80-f940-11e8-85aa-0631dc9c3bfe.gif)

**Comment by thisandagain** [comment]
@rschamp Could you take a look at this one? This could cause some headaches at launch so I'm marking this as critical.
