### ISSUE TITLE
Paint editor bug - Gradients persist in solid fill mode

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-gui#3970]
Notice how the fill swatch does not contain a gradient, but the fill preview does. 
Fill preview should match the swatch.

![image](https://user-images.githubusercontent.com/8203939/49596172-b6d1d800-f947-11e8-8953-00656de1163c.png)

To repro:

1. Select the paint bucket tool
2. Change the fill mode to gradient
3. Change the 1st gradient color to any color
4. Change the 2nd gradient color to "no fill"
5. Change the fill mode to solid
6. See what happens when you paint bucket that color onto anything

My specs:
Google Chrome
Version 70.0.3538.102 (Official Build) (64-bit)
MacOS High Sierra
Version 10.13.14

**Comment by thisandagain** [comment]
Moved to LLK/scratch-paint#783
