### ISSUE TITLE
See exact middle of object when selected

### ISSUE THREAD

**Issue by DeleteThisAcount** [LLK/scratch-gui#3976]
### Expected Behavior

Should show a circle in the exact center of selected object, like in scratch 2:

![](https://i.gyazo.com/6972b4b4ff857e8c13ef2973ead6d0d3.png)

### Actual Behavior

Does not:

![](https://i.gyazo.com/6c13c2deac447ae02299450cfdd4c203.png)

### Steps to Reproduce
Open paint editor
Select object
Notice missing circle 

_this is a repost of llk/scratch-paint#607_

**Comment by DeleteThisAcount** [comment]
as an animator who used scratch, a lot. this is not really good. for example if i want to rotate my drawing using the motion blocks it will pivot completely off of where I want it to, if I don't have a way to see where my drawing is.

**Comment by hedgehog125** [comment]
Maybe there could also be a way of setting the centre of a sprite to the centre of an object or selection

**Comment by towerofnix** [comment]
Note that in Scratch 2.0, you can drag this dot (while holding shift or ctrl I believe) to actually adjust the individual shape's rotation center (not that of the whole costume). That was a very obscure feature that I doubt was frequently used, though.

**Comment by Kenny2github** [comment]
@towerofnix 😮 I had no idea that existed! I just knew that dragging the dot (no shift or ctrl) provided a failsafe way to drag the whole selection instead of a member of a group in vector.

**Comment by adroitwhiz** [comment]
@DeleteThisAcount This can be closed now
