### ISSUE TITLE
I made a script that uses a NPM module (nativefier) to compile a offline version of Scratch

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-gui#40]
This could be used for the offline version, or for testing design for the offline version.

Links:
https://thebrokenrail.github.io/Scratch3Builder
https://github.com/TheBrokenRail/Scratch3Builder

I couldn't do mac because of GitHub file upload limits.

**Comment by thisandagain** [comment]
That's great! We'll likely use Electron (the underlying software that `nativefier` is using) to build the offline version of Scratch 3.0 as well.
