### ISSUE TITLE
 When I convert stage canvas to png, sometimes the image is full with black

### ISSUE THREAD

**Issue by Jingbeishui** [LLK/scratch-gui#4001]
I use` toDataUrl` to convert stage canvas to png, but sometimes the image is all black and with nothing else. Miraculously, there are times when the image displays the contents of the canvas normally. Does anyone know why?

Here is my code:
```
const canvas = document.querySelector('.stage_stage_1fD7k');
const image = canvas.toDataUrl('image/png');
const link = document.createElement('a');
link.href = image;
link.download = 'balabala.png';
const event = document.createEvent('MouseEvents');
event.initMouseEvent('click', true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
link.dispatchEvent(event);
```

**Comment by Jingbeishui** [comment]
@summerscar Thank you for your help

**Comment by Jingbeishui** [comment]
@summerscar I use requestSnapshot () to push the callback function to the array, and then I use draw () to execute the callback function. But the photo I got is all white and with nothing else.Do I make a mistake again?😭

**Comment by summerscar** [comment]
https://github.com/LLK/scratch-gui/blob/ffa2e878241daa05f564f22f0e9128dd4ae4e63a/src/lib/project-saver-hoc.jsx#L273

**Comment by summerscar** [comment]
https://github.com/LLK/scratch-gui/blob/ffa2e878241daa05f564f22f0e9128dd4ae4e63a/src/lib/project-saver-hoc.jsx#L273
上面是官方的做法 @Jingbeishui ，在这个requestSnapshot pr提出之前，我是这样子做的，toDataURL先调用下draw方法。不过还是优先使用官方的做法吧
```
   this.props.vm.runtime.renderer.draw();
   const base64 = this.props.vm.runtime.renderer._gl.canvas.toDataURL('image/png')
```

**Comment by paulkaplan** [comment]
See https://github.com/LLK/scratch-gui/blob/ab31d36251e21fd78aac34983ede6a75e9f1ff71/src/lib/project-saver-hoc.jsx#L66 for the right way to capture stage images
