### ISSUE TITLE
File menu should close after (or while?) file uploads

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#4014]
### Expected Behavior

You click File. You click "load from your computer". You pick a file. It uploads.

The menu should be closed now.

### Actual Behavior

The menu is open!

### FIx

I made a fix for this like: 

![screen shot 2018-12-10 at 5 35 26 pm](https://user-images.githubusercontent.com/3431616/49766091-380bd080-fca2-11e8-8517-2c12031951f6.png)

...which seems like it should work.

But instead, it broke lots of stuff; in particular, I couldn't upload .sb2 files successfully at all!

Seems like maybe it's an issue with dispatching from within this anonymous HOC?

**Comment by rschamp** [comment]
I saw this before too and I thought I wrote up the problem in an issue, but it was just this commit: https://github.com/LLK/scratch-gui/commit/7e3b53a11159e8239b3eb18b1cd5ad0cc70c73e9

**Comment by thisandagain** [comment]
Tracking the larger / global issue here: https://github.com/LLK/scratch-gui/issues/2525
