### ISSUE TITLE
Can not delete blocks on toolbox label

### ISSUE THREAD

**Issue by BrightLin** [LLK/scratch-gui#4016]
### Expected Behavior

Delete block on toolbox & flyout

### Actual Behavior

The block layout on toolbox label.

### Steps to Reproduce

![can not delete](https://user-images.githubusercontent.com/15828392/49773544-836ac100-fd2c-11e8-8e7d-cb172fd507ea.gif)

### Operating System and Browser

Win10 x64, Google Chrome - 71.0.3578.80

**Comment by BrightLin** [comment]
Hi, I found a way to resolve this issue.
> Modify the css class named "blocklyToolboxDelete" ('scratch-blocks/src/core/css.js')：Add "pointer-events: none;"
![image](https://user-images.githubusercontent.com/15828392/55051182-0d962580-508f-11e9-97a1-d624e10e0719.png)

When the user drag a block, the toolbox added css class named "blocklyToolboxDelete". 
Maybe mouse event dispatched to div "scratchCategoryMenu" cause the delete event cannot be emit?

**Comment by paulkaplan** [comment]
This appears to be fixed
