### ISSUE TITLE
Move 'new message' to top

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-gui#402]
### Actual Behavior
When clicking on the dropdown in the broadcast block, new message appears at the bottom of the dropdown.
![before](https://cloud.githubusercontent.com/assets/24476881/26670328/d3415f64-46e3-11e7-901f-a7406c9958f2.png)

### Suggested Behavior
The new message should be at the top of the dropdown. Why? When you get a lot of broadcasts it can be a pain to scroll down (time consuming too) and there are no negatives to this change.
![after](https://cloud.githubusercontent.com/assets/24476881/26670336/da320b66-46e3-11e7-97f9-28fee1773ca1.png)

### Forum Discussion
[here](https://scratch.mit.edu/discuss/topic/222224/)

**Comment by liam4** [comment]
Of note, from Paddle2See:

> Great idea!  It would also be more consistent with “New Variable” and “New Block”, which appear at the top, before the list of already created items.

**Comment by ewilligers** [comment]
I can work on this.

**Comment by nterray** [comment]
Isn't this issue related to scratch-blocks repository instead of scratch-gui?

**Comment by rschamp** [comment]
@nterray Yes, but since in the future we won't be defining these dropdowns in `scratch-blocks`, we should leave the issue filed here for now.
