### ISSUE TITLE
ios safari after downloading a project fails you leave the page and lose work

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#4030]
@kathymakes writes:
Because downloading doesn’t work on iOS devices, you get redirected to a safari error screen and you lose your work :( Ideally it should open a new tab -or- tell the user download doesn’t work -or- maybe do nothing

### Steps to Reproduce

on ipad create a new project
make a few changes
Choose File>download to your computer
Note: you are taken to an error page
Your project is now gone

### Operating System and Browser

Safari on ios

**Comment by tomrow** [comment]
Possibly if we wanted to be really lazy we could just make the project save before attempting the download

**Comment by kchadha** [comment]
Dupe of #1783
