### ISSUE TITLE
Navbar Menus appear under alerts

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#4049]
### Expected Behavior

Menus should appear above alerts

### Actual Behavior

The menus appear behind the alerts

### Steps to Reproduce

Sign in 
Create a project
Turn off your internet connection
Make a change to the project
Click Save Now
Note: an alert appears
Click your username in the navbar
Note: the menu appears
Shrink the window so the menu and the alert overlap
Note: the menu is in front of the alert
<img width="687" alt="screen shot 2018-12-12 at 5 29 38 pm" src="https://user-images.githubusercontent.com/1088291/49903010-b186f880-fe33-11e8-9629-102417771c22.png">

This may be more of a problem on smaller screens

### Operating System and Browser

Mac Chrome

**Comment by benjiwheeler** [comment]
related to z-index (adding this comment in hopes of improving search/findability of related issues)
