### ISSUE TITLE
issues with project id 269088736

### ISSUE THREAD

**Issue by DeleteThisAcount** [LLK/scratch-gui#4063]
### Expected Behavior

_Please describe what should happen_

the game plays normally

### Actual Behavior

_Describe what actually happens_

many issues

the brigtness effect when hovering over the play button and menu items doesnt work as they do in scratch 2.

the text is much smaller

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

visit in scratch 2 and then in scratch 3 to spot differences.

https://scratch.mit.edu/projects/269088736/#player
https://llk.github.io/scratch-gui/develop/#269088736

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by thisandagain** [comment]
Thanks. In order for this type of issue to be actionable we need to reduce the issue down to specifically what is behaving differently. Ideally a smaller project could be created that focuses on one specific compatibility difference. I'm going to close this pending additional details and information.
