### ISSUE TITLE
Project cannot be renamed in the editor standalone build

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#4064]
Beta: 
![image](https://user-images.githubusercontent.com/654102/49953978-5d305700-fecd-11e8-91e0-9d142a535f35.png)

Develop
![image](https://user-images.githubusercontent.com/654102/49953982-60c3de00-fecd-11e8-8107-66ddc525bfb4.png)

I believe this was introduced by https://github.com/LLK/scratch-gui/pull/4035

**Comment by paulkaplan** [comment]
Should I mark this as critical? it means you can't rename projects in the offline editor

**Comment by thisandagain** [comment]
@paulkaplan Yup. Marked.
