### ISSUE TITLE
The number in a cloud variable monitor is vertically misaligned

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#4073]
From @carljbowman 
The vertical alignment of the number in monitors is offset. The number appears too high 
![image6](https://user-images.githubusercontent.com/1088291/49960374-fb2c1d80-fedd-11e8-85ce-e2d5546ac5e9.png)

### Steps to Reproduce

Create a new project
Add a cloud variable
Note: the number inside the monitor is aligned with the top of the box for the number and there is too much space below it.

### Operating System and Browser

Mac Chrome

**Comment by heironimus** [comment]
This is because the cloud character "☁" causes the variable name container to be slightly taller. 

You can reproduce this with a non-cloud variable by copying and pasting ☁ from here and adding it to a regular variable name, which results in the same misalignment.
