### ISSUE TITLE
Block gets stuck when dragging over category menu

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#4079]
### Expected Behavior

Blocks should get deleted when dragged to the left of the workspace over the toolbox or the category menu.

### Actual Behavior

Block gets stuck if your cursor is over a category on the category menu while dragging.

![block-gets-stuck](https://user-images.githubusercontent.com/1786240/49966187-50236000-feed-11e8-8ba3-5f322090281a.gif)

### Steps to Reproduce

1. Drag a block from the flyout (you have to start dragging to the right)
2. (Optional) Drop the block onto the code workspace
3. Drag the block back to the left, over the flyout, and pause with your cursor over one of the category menu buttons
4. Drop the block
5. Notice that it is stuck

From this state, if you click anywhere on the blocks workspace, the block will actually get deleted.
If you don't do this, and you switch tabs or you save and load the project, the block will be back.

**Comment by picklesrus** [comment]
Fixed by https://github.com/LLK/scratch-blocks/pull/1831
