### ISSUE TITLE
draggable sprites (in .sb3 file) are not draggable when loaded into gui

### ISSUE THREAD

**Issue by julescubtree** [LLK/scratch-gui#4093]
### Expected Behavior

_Please describe what should happen_

When loading an .sb3 file, the draggability of sprites should be preserved.

### Actual Behavior

If sprites are draggable (in the fullscreen/player view) in the .sb3 project file, they are not draggable in the gui after the file is loaded.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

Upload a file with a draggable sprite, such as this one (unzip first): [draggable.sb3.zip](https://github.com/LLK/scratch-gui/files/2682053/draggable.sb3.zip)
(This file was generated by importing this Scratch 2.0 [project](https://scratch.mit.edu/projects/270697731/), then downloading it to my computer in the Scratch 3.0 editor.)

Switch to fullscreen/player view, and attempt to drag the sprite. It won't.

### Operating System and Browser

macOS 10.13.6, Firefox 64.0

**Comment by paulkaplan** [comment]
Fixed in vm#1850
