### ISSUE TITLE
When a list's name is modified, the list monitor does not show the modified name

### ISSUE THREAD

**Issue by jialiren** [LLK/scratch-gui#4098]
### Expected Behavior

After the list name is modified, the stage synchronizes the modified name

### Actual Behavior

When the list name is modified, the stage cannot synchronize the modified name

### Operating System and Browser

chrome

**Comment by thisandagain** [comment]
@jialiren This isn't quite enough info for us to be able to reproduce or understand the behavior you are seeing. Please provide a comprehensive list of steps for us to reproduce the issue.

**Comment by ericrosenbaum** [comment]
It looks like @jialiren is saying that, if you change the name of a list, the name displayed on the list monitor does not change. This is in fact a bug.

It works correctly for variables: if you change the name of a variable, the variable monitor updates. It just doesn't work for lists.

Steps to repro:
- Make a list. List monitor appears.
- Right-click the list reporter in the blocks menu to rename it.
- Note that the list monitor still shows the old name.
  
![list-rename](https://user-images.githubusercontent.com/567844/50117678-a78e3c80-021b-11e9-9e73-fb7b45c8e671.gif)

**Comment by jialiren** [comment]
Yes, forgive me for not making it clear, @ericrosenbaum  is right.
