### ISSUE TITLE
Default GUI to 30fps "compatibility mode"

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#41]
For compatibility testing it would be helpful if the GUI ran in 30fps by default.

**Comment by TheBrokenRail** [comment]
Would there be a way to test in 60fps?

**Comment by TheBrokenRail** [comment]
maybe the switch could be in the file menu?

**Comment by TheBrokenRail** [comment]
I think I chould implkememnt it to be on by default by setting ```js vm.setCompatibilityMode(compatibilityMode); ``` in the gui.jsx file, should I make a PR?

**Comment by rschamp** [comment]
@TheBrokenRail Yes! Please make a PR for that.  Eventually we will want to switch the compatibility mode based on the project, but we have not planned out how that will work yet.

**Comment by thisandagain** [comment]
Resolved in #51
