### ISSUE TITLE
Extra line appeared in Scratch Cat's foot

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#410]
### Expected Behavior

Scratch Cat, the default sprite, should always look the same when opening a new project.

### Actual Behavior

Reported by Saskia during Catch Game internal playtest (6/2/17).
> Scratch Cat's foot (paw?) looks weird upon opening the editor.

This was right after opening the gui; she hadn't done anything with the project yet. Zoom was set to 100%.

<img width="172" alt="screen shot 2017-06-05 at 2 46 23 pm" src="https://cloud.githubusercontent.com/assets/1320456/26798378/32414e44-49fe-11e7-8689-58c6fab54dfb.png">

### Steps to Reproduce

Unknown

### Operating System and Browser

_Mac OS, Chrome_

**Comment by fsih** [comment]
This happens to me on my monitor. It seems to have something to do with the
sampling rate; as you move the sprite around it doubles up different lines.

**Comment by jwzimmer** [comment]
(Closed as a dupe of https://github.com/LLK/scratch-render/issues/143)
