### ISSUE TITLE
One of the sprite "Abby"'s costumes renders wrong

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#4101]
This costume renders incorrectly:
https://cdn.assets.scratch.mit.edu/internalapi/asset/2193cf08f74b8354f7c4fac37a06ea24.svg/get/

@fsih thinks the view box on the svg is set wrong.

cc @kosiecki17

**Comment by paulkaplan** [comment]
Can you clarify specifically _where_ abby renders wrong? Currently, the only place I see it rendering wrong is the costume/sprite library. In the editor, I see it rendering correctly everywhere.

**Comment by kosiecki17** [comment]
I think I may have fixed the issue with the Abbey-d costume. 
The grouping that included the arms and torso created a box that cut across the upper thighs. I've eliminated this.
