### ISSUE TITLE
Dark outlines appear around the edges of some sprites

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#4103]
Some sprites / costumes appear to render with a small black outline around them.

### 2.0
![image](https://user-images.githubusercontent.com/747641/50105990-66d2fb00-01fc-11e9-85d5-86807b036319.png)

### 3.0 (Develop)
![image](https://user-images.githubusercontent.com/747641/50105943-3a1ee380-01fc-11e9-947b-923b18a1a228.png)

** NOTE: This project is currently not shared, please check with me if you'd like the project ID **

**Comment by thisandagain** [comment]
Assigning to @BryceLTaylor to create a small repro case.

**Comment by fsih** [comment]
Might be https://github.com/LLK/scratch-render/issues/237

**Comment by thisandagain** [comment]
@fsih I thought we had an issue for this already! Thanks!

**Comment by thisandagain** [comment]
@fsih This does appear to be fixed on this project. Any thoughts as to where / how this was resolved?

**Comment by fsih** [comment]
@thisandagain no unfortunately...

**Comment by thisandagain** [comment]
Agreed. We verified this during testing today as well.
