### ISSUE TITLE
translate file->new confirm alert

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#4106]
It should be translated into other languages; instead, it seems to always be English. Maybe translations just haven't been updated?

Was introduced in: https://github.com/LLK/scratch-gui/pull/3974/files

LLK Brazil team reported that they couldn't find the string on Transifex, and I can't either

cc: @chrisgarrity

**Comment by chrisgarrity** [comment]
Fixed in Transifex
