### ISSUE TITLE
Deleting a sprite moves the focus to the background, instead of a different sprite

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#411]
### Expected Behavior

In 2.0, the focus shifts to a different sprite instead of the backdrop.

### Actual Behavior

Reported by @morantsur during the Catch Game internal playtest (6/2/17):
> Deleting a sprite moves the focus to the background, instead of a different sprite.

### Steps to Reproduce

Compare in 2.0 & 3.0:
- Add 2 sprites to your project (and at least 1 backdrop)
- Delete the first sprite
- Note focus shifts to either the 2nd sprite (2.0) or backdrop (3.0)

### Operating System and Browser

_Mac OS, Chrome_

**Comment by paulkaplan** [comment]
I believe this is a dup of https://github.com/LLK/scratch-gui/issues/294 ?

**Comment by jwzimmer** [comment]
Thanks @paulkaplan, closing this in favor of #294.
