### ISSUE TITLE
When user uploads a project, give them choice between overwriting current project, and creating new project?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#4119]
### Expected Behavior

Some users who upload a project expect it to create a new project.
Other users expect it to overwrite the current project.

### Actual Behavior

Currently, it creates a new project. But that makes some workflows by users impossible; if they work on a project offline, that project can never be used to update the content of an existing project they have comments, likes, and favorites on.

### Design challenge

How can we design the UX so there is a minimum of confusion/surprise/frustration?

**Comment by DeleteThisAcount** [comment]
yes

**Comment by towerofnix** [comment]
> Currently, it creates a new project. But that makes some workflows by users impossible; if they work on a project offline, that project can never be used to update the content of an existing project they have comments, likes, and favorites on.

Yikes, yup. Very :+1: on this - that case is super important but I can definitely see people accidentally overwriting their projects when there's no choice.

**Comment by griffpatch** [comment]
This issue is getting rather frustrating... I never work on a shared project if I can help it, always creating a copy and then downloading it and uploading it over the shared project to avoid breaking the live project. This is not possible until this issue is addressed.

**Comment by IamTregsthedev** [comment]
Yep.

**Comment by thisandagain** [comment]
Closing as per discussion in https://github.com/LLK/scratch-gui/issues/3509
