### ISSUE TITLE
Clicking stage to deselect text field does not work

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#412]
### Expected Behavior

Clicking elsewhere including the stage should deselect the text field.

### Actual Behavior

Reported by @fsih during Catch Game internal playtest (6/2/17):
> When you have a text field selected and you try to defocus it by clicking on the project window, it doesn't work

### Operating System and Browser

_Mac OS, Chrome_

**Comment by fsih** [comment]
This issue is like https://github.com/LLK/scratch-gui/issues/270 but for the workspace instead of the flyout

**Comment by paulkaplan** [comment]
This is going to be fixed with https://github.com/LLK/scratch-gui/issues/3207, so I'm going to close this
