### ISSUE TITLE
Overlapping block text

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#413]
### Expected Behavior

Text in the blocks should not overlap.

### Actual Behavior

Several people - including @lifeinchords & @morantsur - during the internal playtest reported the text in the blocks displaying incorrectly, so it overlapped with other text:
> Text in textboxes is weird (see image -->) after adding a few costumes, and coming back to code

Examples:

<img width="437" alt="screen shot 2017-06-05 at 3 19 31 pm" src="https://cloud.githubusercontent.com/assets/1320456/26799149/6e4f5af8-4a02-11e7-9f0f-6240041d65ed.png">

<img width="542" alt="screen shot 2017-06-05 at 3 21 37 pm" src="https://cloud.githubusercontent.com/assets/1320456/26799243/bf5fdd3c-4a02-11e7-9df9-56347ff26d72.png">

### Operating System and Browser

_Mac OS, Chrome_

**Comment by fsih** [comment]
This issue is like https://github.com/LLK/scratch-gui/issues/270 but for the workspace instead of the flyout

**Comment by paulkaplan** [comment]
@fsih could you figure out a way to reproduce this in the scratch-blocks vertical playground?

**Comment by paulkaplan** [comment]
FWIW Here is a simple way I just found:

1. Add "touching mouse pointer" from sensing.
2. Change to the background 
3. Change tabs to costumes
4. Click on the first sprite
5. Change back to scripts tab

![image](https://user-images.githubusercontent.com/654102/26881014-3028e6a0-4b64-11e7-98bf-150155bc7d9c.png)

**Comment by paulkaplan** [comment]
Yup I think you are right on. Here is how to do it in the vertical playground:

1. Add the "touching mouse-pointer" block.
2. Click "Export to XML"
3. Remove that block so it is empty.
4. Click "Hide"
5. Click "Import from XML"
6. Click "Show"

Then you see the same thing. 

It looks like `setVisible` should be causing a re-render. Not sure why it isn't recalculating the widths. May want to file this on scratch-blocks and reach out to them?

**Comment by fsih** [comment]
Moved issue to scratch blocks
