### ISSUE TITLE
Asset library regressions

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#4137]
Following the "super mega library update" https://github.com/LLK/scratch-gui/pull/4133, we'll use this issue to track regressions.

This is comparing the state of the sprite, costume, backdrop and sound libraries in the current form to what they contained before that PR.

**Sprite Library** 
- [x] Penguin is missing from "animals" category (missing tags)
- [x] Polar bear is missing from "animals" category (missing tags)
- [x] Zebra is completely missing
- [x] Devin changed from vector to bitmap

**Backdrop Library**
- [ ] Backdrop1 was added- it's blank, should not be there
- [ ] Woods thumbnail shows up incorrectly (quarter size)

**Comment by apple502j** [comment]
Sprite:

[ ] Convertible 3 should be Convertible 2
[ ] Tag Convertible 3 as car
[ ] Tag motorcycle as bike

**Comment by Kenny2github** [comment]
@apple502j checkboxes need a hyphen before the [ ]
- [ ] Convertible 3 should be Convertible 2
- [ ] Tag Convertible 3 as car
- [ ] Tag motorcycle as bike
