### ISSUE TITLE
Stop/Go buttons usability observation

### ISSUE THREAD

**Issue by earth2marsh** [LLK/scratch-gui#417]
When I first went to run a program, it wasn't obvious to me that the green flag was `run`. A more traditional ▶️ might have helped me.

Also, a dim button becomes bright when you hover over it, which makes it less clear that it isn't yet active. Since these two states are exclusive, consider making this more like a toggle element, like a light switch.

**Comment by carljbowman** [comment]
Resolving some of the state issues as apart of the work on Turbo Mode: https://github.com/LLK/scratch-gui/issues/332

As far as the play button goes we will continue to use the Green Flag as that has been apart of Scratch since the launch.
