### ISSUE TITLE
Character limit on custom blocks

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#4177]
@kathymakes notes in a bughunt:

> We should cap the character count on make a block….
![image25](https://user-images.githubusercontent.com/1088291/48022633-abea1480-e109-11e8-92a7-a219637d81fa.png)

**Comment by towerofnix** [comment]
Duplicate of LLK/scratch-vm#577.

**Comment by kchadha** [comment]
Good catch @towerofnix! Tracking in LLK/scratch-vm#577.
