### ISSUE TITLE
scratch may produce a broken project file when choosing sprites in the sprite library under a bad network condition

### ISSUE THREAD

**Issue by QinJhonny** [LLK/scratch-gui#4179]
### Expected Behavior
when choosing a sprite in the sprite library, whether it's in a good or bad network condition, whenever I save the project file, scratch would gurantee not produce a broken project file.

### Actual Behavior
but if the network is very bad, scratch may save me a broken project file sometimes.

### Steps to Reproduce

first open https://beta.scratch.mit.edu/  ,  when the user interface is completely loaded, open the console, then click the tab "network",and then choose "offline".  (choose offline to simulate the bad network). now click to choose a  sprite to open the sprite library modal, and then select a sprite that is not  done loaded, and after this, you would notice that the sprite you've just selected doesn't appear in the target panel, and then save the project to your computer . right now you should get a broken file.
the reason that causes this problem is that the sprite info has been written into the project. json, but the aasets to it haven't been downloaded together with it. You can unzip the sb3 file and checkout the project.json, there's something like this," costumes: [ ]".  It's supposed not to be a empty array.

### Operating System and Browser

macbook 10.13.6  chrome 7.0

**Comment by thisandagain** [comment]
@BryceLTaylor Can you confirm this? If a repro is found, we should push towards a fix ASAP.
