### ISSUE TITLE
Block code doesn't appear in editor

### ISSUE THREAD

**Issue by VeerD** [LLK/scratch-gui#418]
### Expected Behavior

See project block code as in https://scratch.mit.edu/projects/160049362/#editor

(Scratch 2.0):
1) Navigate to https://scratch.mit.edu/projects/160049362/#editor
2) Click on "Ramen Cup" sprite
3) See code in project editor

### Actual Behavior

JS console warning/error:
(warning) Ignoring non-existent input VARIABLE in block data_hidevariable
(error) lib.min.js:6 Uncaught TypeError: Cannot read property 'isConnected' of null

Nothing shows up in the code editor.

### Steps to Reproduce

(Scratch 3.0):
0) Open Chrome developer tools (console)
1) Navigate to https://llk.github.io/scratch-gui/#160049362
2) Click on "Ramen Cup" sprite
3) See JS errors in the console; see blank code editor space

### Operating System and Browser

Mac OS 10.12.5
Chrome 58

**Comment by ivanixgames** [comment]
I just tried to reproduce the issue with the latest code of the past few days.
Seems to work ok.
@VeerD   are you still seeing the issue with the latest code in github?

![screenshot at 2018-02-13 09 47 56](https://user-images.githubusercontent.com/858678/36129669-4f91f478-10a3-11e8-88f4-0a1695617300.png)

**Comment by VeerD** [comment]
Yeah, looks like this is fixed.
