### ISSUE TITLE
On Firefox, Importing a list by opening "Choose file for importing" makes strange file input input below

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#4188]
### Expected Behavior
No file input field

### Actual Behavior
![image](https://user-images.githubusercontent.com/33279053/50373007-9ed2a780-061b-11e9-8c32-0d1436ea70c6.png)
File input field appears

### Steps to Reproduce
1. Open Firefox
2. Make a list
3. Right-click the monitor and choose "import"
4. It appears!

### Operating System and Browser
Firefox 64.0 on Windows 7

**Comment by benjiwheeler** [comment]
That might just be what your version of Firefox uses for the `prompt()` alert type; for several types of alert, confirm and prompt, we are just calling the browsers' alert functions and letting the browser determine how the alerts look.

Can you say more about what is confusing about this interface?

**Comment by apple502j** [comment]
@benjiwheeler The file-input button appears at the bottom of the page.

**Comment by BryceLTaylor** [comment]
I've been completely unable to reproduce this.  I tried on Mac and on Windows 7 and in both cases Firefox opened the normal file browser window.
