### ISSUE TITLE
Text size differes from scratch 2

### ISSUE THREAD

**Issue by DeleteThisAcount** [LLK/scratch-gui#4189]
### Expected Behavior

_Please describe what should happen_
the text in scratch 3 and in scratch 2 is the same sizes

### Actual Behavior

_Describe what actually happens_
scratch 3 differes
### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
view: https://scratch.mit.edu/projects/269088736/ (Scratch 2)
 and then view in scratch 3.

notice that the variables are misalignment due to this
### Operating System and Browser

windows 10 chrome

**Comment by thisandagain** [comment]
This is an unfortunate side effect of the licensing issues for many fonts in Scratch 2.0 which lead to us needing to switch to alternatives in Scratch 3.0. Quite a bit of work was done to get them to be as close as possible, but they will never be a perfect match.

/cc @fsih
