### ISSUE TITLE
Unicode 'BACKSPACE' stop to read project

### ISSUE THREAD

**Issue by yokobond** [LLK/scratch-gui#4190]
### Expected Behavior

Should be open and run project in v3 as v2.

### Actual Behavior

If a project contains Unicode character 'BACKSPACE' (\u0008), it will not run on Scratch 3.0 beta. The scripts are disappeared after the character and not editable in v3.0 any more. 

### Steps to Reproduce

[Unicode Character 'BACKSPACE' (\u0008) ](https://scratch.mit.edu/projects/273360075/)

[Unicode Character 'BACKSPACE' (\u0008)  on Scratch 3.0 beta](https://beta.scratch.mit.edu/#273360075)

### Operating System and Browser

MacOS 10.13.6
Chrome 70.0.3538.110

**Comment by apple502j** [comment]
Related to #3871 , LLK/scratch-vm#1077 , LLK/scratch-blocks##1822
However, this should be tagged as critical and fixed before the release, since it will affect for most of Mac users.

**Comment by apple502j** [comment]
To reproduce this, you need to type in Japanese input method.
1) type some character into 2.0's string argument
2) press Space (to execute IME)
3) **BEFORE PRESSING ENTER KEY**, press Delete
4) Done.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-vm#1873
