### ISSUE TITLE
How can I add spacers in custom extensions?

### ISSUE THREAD

**Issue by cotestatnt** [LLK/scratch-gui#4191]
### Expected Behavior

I would like to obtain the same "appereance" with spacer between similar blocks  also for the custom extensions
![image](https://user-images.githubusercontent.com/27758688/50382754-d0dd1b80-06a6-11e9-9c68-51fdb7481d6a.png)

I tried to search the wiki available but without success. Is this possible?

### Actual Behavior
![image](https://user-images.githubusercontent.com/27758688/50383030-5b744980-06ac-11e9-83cb-acdf14fa6093.png)

**Comment by towerofnix** [comment]
Scratch 3.0 actually already supports separators in extensions - just specify `'---'` in place of two blocks, for example like this:

```js
blocks: [
    {opcode: 'clear' ...},
    '---',
    {opcode: 'stamp' ...}
]
```

This results in a separator:

![The blocks "erase all", "stamp", "pen down"; there is a larger space between erase-all and stamp.](https://user-images.githubusercontent.com/9948030/52236955-a930c400-289e-11e9-84e9-eb22657f51d8.png)

**Comment by cwillisf** [comment]
Thanks, @towerofnix!
While more thorough extension documentation should be coming later this year, I've added this to the [documentation that we have now](https://github.com/LLK/scratch-vm/wiki/Scratch-3.0-Extensions-Specification).
