### ISSUE TITLE
Cannot get /

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#4193]
Windows 7, Firefox 64
node v8.9.4, npm 5.6.0

When running `npm start`, it says `i ｢wdm｣: Compiled with warnings.`
However, when I go to localhost:8601, it says `Cannot get /`
I tried again, and it changed to the list of directories.

When I ran that command, build and dist folders were not created, but translations did.

What I tried:
* `npm run build` - success
* deleting translations and running it again - didn't fix
* making build folder by myself - failed when `npm start`
* changed port - didn't fix

**Comment by joker314** [comment]
@apple502j did you mean to close this? If so, could you let us know how you managed to fix the issue, as it might help others too
