### ISSUE TITLE
Spacing between green flag and stop button.

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-gui#42]
### Expected Behavior

There should be spacing between the green flag and stop button.

![screenshot 2017-01-23 at 11 33 48 am](https://cloud.githubusercontent.com/assets/10731781/22212803/03166b38-e160-11e6-9e86-4aa733b5e47e.png)

### Actual Behavior

There is no spacing between them

### Steps to Reproduce

Open Scratch GUI

### Operating System and Browser

Chromebook

**Comment by liam4** [comment]
>Open Scratch API

[scratch-gui](http://llk.github.io/scratch-gui)?

**Comment by CosmicWebServices** [comment]
lol sorry

**Comment by CosmicWebServices** [comment]
I fixed this in https://github.com/LLK/scratch-gui/pull/43
