### ISSUE TITLE
Uploading project from computer leads to a failed request to /projects/undefined 

### ISSUE THREAD

**Issue by picklesrus** [LLK/scratch-gui#4202]
Projects appear to upload and work correctly but the following request is made and 404s:

`PUT https://<domain>/projects/undefined`

Steps to repro:
1. Open the js console or the network tab
2. Upload a project 

There's also the following API response error logged but I think it is just because of the 404:

(anonymous) | @ | projects.bundle.js:31
  | i.write | @ | common.bundle.js:22
  | t | @ | common.bundle.js:11
  | emit | @ | common.bundle.js:22
  | n.write | @ | common.bundle.js:22
  | t | @ | common.bundle.js:11
  | emit | @ | common.bundle.js:22
  | n.write | @ | common.bundle.js:11
  | r.error | @ | common.bundle.js:22
  | e.exports.previewReducer | @ | projects.bundle.js:42
  | (anonymous) | @ | common.bundle.js:38
  | d | @ | common.bundle.js:16
  | (anonymous) | @ | projects.bundle.js:120
  | (anonymous) | @ | common.bundle.js:38
  | dispatch | @ | common.bundle.js:38
  | (anonymous) | @ | projects.bundle.js:42
  | (anonymous) | @ | common.bundle.js:6
  | (anonymous) | @ | common.bundle.js:38
  | i | @ | common.bundle.js:16
  | t | @ | common.bundle.js:16
  | A | @ | projects.bundle.js:31
  | XMLHttpRequest.send (async) |   |  
  | (anonymous) | @ | projects.bundle.js:31
  | i | @ | common.bundle.js:16
  | a | @ | common.bundle.js:16
  | r | @ | common.bundle.js:6
  | e.exports | @ | common.bundle.js:6
  | (anonymous) | @ | projects.bundle.js:42
  | (anonymous) | @ | common.bundle.js:38
  | updateProject | @ | projects.bundle.js:160
  | value | @ | projects.bundle.js:160
  | n | @ | common.bundle.js:6
  | value | @ | projects.bundle.js:160
  | n | @ | common.bundle.js:6
  | (anonymous) | @ | projects.bundle.js:160
  | Promise.then (async) |   |  
  | value | @ | projects.bundle.js:160
  | A | @ | projects.bundle.js:47
  | load (async) |   |  
  | value | @ | projects.bundle.js:160
  | mountClassInstance | @ | common.bundle.js:22
  | beginWork | @ | common.bundle.js:22
  | o | @ | common.bundle.js:22
  | i | @ | common.bundle.js:22
  | u | @ | common.bundle.js:22
  | b | @ | common.bundle.js:22
  | A | @ | common.bundle.js:22
  | batchedUpdates | @ | common.bundle.js:22
  | Q | @ | common.bundle.js:22
  | ke | @ | common.bundle.js:22
  | A | @ | projects.bundle.js:31

**Comment by benjiwheeler** [comment]
This was resolved by #4700 , which changed uploading to use the current project id.

However, note that if we ever move to a UX where the user is able to choose between upload-in-place and upload-to-new-file, we'll want to revisit this.
