### ISSUE TITLE
Argument of sensing () of () gets untraslated after being dragged from palette

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#4209]
### Expected Behavior
It should be translated

### Actual Behavior
After dragging the block, it gets untranslated.
![](https://i.gyazo.com/9b3574bbf5395b7cf208c78f52c5dd94.gif)

### Steps to Reproduce
1. Change language to anything other than English
2. Drag the () of () sensing

### Operating System and Browser
Windows 7 Firefox 64

**Comment by chrisgarrity** [comment]
fixed in https://github.com/LLK/scratch-gui/pull/5392
