### ISSUE TITLE
Entering fullscreen mode when logged out adds /projects/0/ to the url

### ISSUE THREAD

**Issue by picklesrus** [LLK/scratch-gui#4212]
### Steps to Reproduce
1. log out
2. Go to /projects/editor/
3. Click the fullscreen button
4. Notice that the url is now /projects/0/fullscreen/

This doesn't seem to cause any serious problems, but I think it is unexpected for /projects/0/ to end up in the URL.

**Comment by paulkaplan** [comment]
@benjiwheeler @BryceLTaylor i remember you mentioned trying to figure out how the url got to be this, this is a way!
