### ISSUE TITLE
remove the entry of lin.min, and to use react react-dom of cdn, but the result doesn't work

### ISSUE THREAD

**Issue by kwslimerence** [LLK/scratch-gui#4213]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

> [

![Uploading Screen Shot 2018-12-28 at 3.31.34 PM.png…]()

](url)

**Comment by kwslimerence** [comment]
`
<img width="408" alt="screen shot 2018-12-28 at 3 31 28 pm" src="https://user-images.githubusercontent.com/24387213/50506897-fd81a080-0ab5-11e9-8049-263403d4361e.png">
<img width="766" alt="screen shot 2018-12-28 at 3 31 34 pm" src="https://user-images.githubusercontent.com/24387213/50506903-03778180-0ab6-11e9-9b0c-bad549adb596.png">

`

**Comment by thisandagain** [comment]
Please complete the issue template and provide sufficient information for us to understand your issue or question.
