### ISSUE TITLE
Audio trim controls don't act as expected on Firefox

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#4224]
### Expected Behavior
Here's what trimming a sound looks like on chrome, it's a bit laggy, but if you click and drag a handle the trim bars follow the mouse:
![sound-edit-ok](https://user-images.githubusercontent.com/399209/50607835-a7877100-0e98-11e9-96b6-f0e735f5f068.gif)

### Actual Behavior
Here's what it looks like on Firefox. When you click on the handle you drag that around. When you release the handle, the trim bars react to the mouse until you click again.
![sound-edit](https://user-images.githubusercontent.com/399209/50607854-b837e700-0e98-11e9-999a-14393c84a24e.gif)

### Steps to Reproduce

Record a sound in Firefox.

### Operating System and Browser

Mac OS High Sierra 10.13.6 (17G65), Firefox 64.0 (64-bit)

**Comment by towerofnix** [comment]
Can repro on Linux. Note this is only an issue when you're dragging by the handles -- dragging over the highlighted area works like expected.

**Comment by paulkaplan** [comment]
Fixed with the new sound editor handles update
