### ISSUE TITLE
Alert containers should be the width of the alert. Right now, the container prevents you from clicking other parts of the UI.

### ISSUE THREAD

**Issue by kathymakes** [LLK/scratch-gui#4226]
### Expected Behavior

You should still be able to click on parts of the GUI (like stage controls) when alerts are fired.

### Actual Behavior

You can't click on stage controls or anything "under" the invisible alert container.

![bug](https://user-images.githubusercontent.com/8203939/50608438-aeaf7e80-0e9a-11e9-884f-5e2afd11a847.gif)

### Steps to Reproduce

Trigger an alert; this can be by turning the internet off, then trying to save or create a project.

### Operating System and Browser

Mac OS 10.13.4
Chrome Version 70.0.3538.102 (Official Build) (64-bit)

Arbitrarily assigned @benjiwheeler , feel free to change/reassign!

**Comment by benjiwheeler** [comment]
Related to https://github.com/LLK/scratch-gui/issues/4428

**Comment by BryceLTaylor** [comment]
I believe this has been fixed
