### ISSUE TITLE
Scratch Desktop has no share button

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#4227]
### Expected Behavior

There should be a share button.

### Actual Behavior

There isn't one.

### Steps to Reproduce

Look in Scratch Desktop.
### Operating System and Browser

Windows, Scratch Desktop (installed from windows store)

**Comment by towerofnix** [comment]
This is noted in the Scratch Desktop FAQ (on the download page):

> **Can I share from Scratch Desktop?**
>This isn’t supported currently. For now, you can save a project from Scratch Desktop, upload it to your Scratch account, and share it there. In a later version we will add the ability to upload to your Scratch account directly in Scratch Desktop.

This feature is probably being tracked in the scratch-desktop repository, but that's closed source for now (I think they plan on open-sourcing it later).

**Comment by thisandagain** [comment]
Moved to LLK/scratch-desktop#25
