### ISSUE TITLE
scratch-gui goes over the navbar

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#4230]
### Expected Behavior
Everything should be under the navbar.

### Actual Behavior
![](https://screenshotscdn.firefoxusercontent.com/images/8d7bab4d-cf8a-4528-914c-20c7a03356ed.png)
It goes over the navbar

### Steps to Reproduce
1. Open a project with stage monitor, in project view
2. Scroll
### Operating System and Browser
Firefox 64 on Windows 7

**Comment by apple502j** [comment]
can repro with sprites

**Comment by towerofnix** [comment]
Related to or maybe a duplicate of #4164, btw.

**Comment by benjiwheeler** [comment]
related to z-index (adding this comment in hopes of improving search/findability of related issues)
