### ISSUE TITLE
Too slow display of the "Sign in" button on the top page.

### ISSUE THREAD

**Issue by kwaka1208** [LLK/scratch-gui#4231]
### Expected Behavior
"Sign in" button is not displayed on top page when signed out
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/1939982/50618586-44005080-0f37-11e9-9ff3-54ef1f73a168.png">

### Actual Behavior
It should be displayed on top page.

### Steps to Reproduce
1. Sign out from Scratch site.
2. Access https://scratch.mit.edu/

### Operating System and Browser
macOS 10.14.2 Firefox 64.0, Chrome 71.0.3578.98, Safari 12.0.2 (14606.3.4)

**Comment by kwaka1208** [comment]
Sorry, I understood that it is only taking time to display button.

**Comment by thisandagain** [comment]
This was an issue with our backend systems on the day of launch due to some issues with the rollout.
