### ISSUE TITLE
Block category colour-circles aren't perfectly vertically centered

### ISSUE THREAD

**Issue by liam4** [LLK/scratch-gui#424]
### Expected Behavior

The colour-circles placed beside category labels are perfectly vertically centered, so the center of the circle crosses the center of the text.

These two imaginary lines should cross over each other:

![Annotated screenshot – horizontal lines across centers of colour-circle and label](https://cloud.githubusercontent.com/assets/9948030/26828626/bd03611c-4a98-11e7-89c5-6d9f2e8552dd.png)

These two imaginary lines should be equal in length:

![Annotated screenshot – vertical lines above and below circumference of colour-circle](https://cloud.githubusercontent.com/assets/9948030/26828786/4e31167a-4a99-11e7-898c-30f52416b7ac.png)

### Actual Behavior

The colour-circles aren't aligned correctly, instead with the bottom of the circle sitting on the same imaginary line the bottom of the label is on.

![Palette category screenshot](https://cloud.githubusercontent.com/assets/9948030/26828651/d4f27ed4-4a98-11e7-8571-51e352e89a0f.png)

### Steps to Reproduce

Open the editor. The issue is clearer when the browser zoom is greater.

### Operating System and Browser

macOS 10.12.5, Chrome 58.0.3029.110.

**Comment by paulkaplan** [comment]
Good eye!

Can you refile this in the scratch blocks repo https://github.com/llk/scratch-blocks? Closing this issue here, since it cannot be fixed from the GUI.
