### ISSUE TITLE
No menu for changing the min and max value of the slide monitor

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#4240]
I can't change the min or max value of the slide monitor. Some of my old projects have the old settings and still work, but some of them are resetted to 0 ~ 100.
I know this issue has been metioned, but I'm not sure if the feature is adding.

**Comment by benjiwheeler** [comment]
Thanks, @cyx2015s! We're tracking this issue in #2053, and we're hoping to address it soon.
