### ISSUE TITLE
Some svg images that made in Inkscape can't be drawn correctly.

### ISSUE THREAD

**Issue by mochitochi** [LLK/scratch-gui#4242]
### Actual Behavior
When I uploaded a svg image that made in Inkscape,it was drawn as this screenshot
![](https://u.cubeupload.com/masa2004/5c71ff.png)
Also,all of svg images whose source code is [valid](https://validator.w3.org) that I tested were drawn correctly.
### Steps to Reproduce
Upload SVG image that made in Inkscape.I don't know about Illustrator.
I use this [image(GoogleDrive)](http://bit.ly/2C0aUP8).
Maybe,If the image is smaller than  a certain size,you can't reproduce this bug.

### Operating System and Browser
Windows10Home
I faced this bug both Desktop and Chrome71.

**Comment by mochitochi** [comment]
> ### Expected Behavior
> Some svg images that made in Inkscape can't be drawn correctly.
> 
> ### Actual Behavior
> When I uploaded a svg image that made in Inkscape,it was drawn as this [screenshot](http://u.cubeupload.com/masa2004/5c71ff.png)
> Also,all of svg images whose source code is [valid](https://validator.w3.org) that I tested were drawn correctly.
> 
> ### Steps to Reproduce
> Upload SVG image that made in Inkscape.I don't know about Illustrator.
> I use this [image](http://bit.ly/2C0aUP8).
> Maybe,If the image is smaller than a certain size,you can't reproduce this bug.
> 
> ### Operating System and Browser
> Windows10Home
> I faced this bug both Desktop and Chrome71.

**Comment by BryceLTaylor** [comment]
I think that this issue is now better documented here https://github.com/LLK/scratch-gui/issues/4711, so I'm closing.
