### ISSUE TITLE
Reports that iPad hardware keyboards are not triggering Scratch keypresses

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#4244]
See discussion: https://scratch.mit.edu/discuss/topic/329379

![image](https://user-images.githubusercontent.com/3431616/50651712-3906e980-0f52-11e9-9af7-1b123045daff.png)

**Comment by paulkaplan** [comment]
I was able to repro some issues with an apple bluetooth keyboard connected to an iPad. specifically:
- The keypressed reporter reports false until i hit the key, then it stays "true" forever afterwards (i.e. it never sees keyup). this is true for all keys
-  I was not able to confirm the second comment, the "when down arrow key pressed" seems to work correctly for me.

**Comment by paulkaplan** [comment]
Wow this is very new to me. The bluetooth keyboard `keyup` event does not contain the `key` property, instead it sets the `key="Dead"`... but it does send the correct keyCode. We are already sending both `key` and `keyCode` to the VM, but the VM only uses `key`. We should be able to use the `keyCode` if the `key==="Dead"`. Bizarre...

**Comment by lihongtao2012** [comment]
Did the blogger solve it? I downloaded your project. It's not easy to use
