### ISSUE TITLE
Pressing escape in library browser should cancel dialog

### ISSUE THREAD

**Issue by liam4** [LLK/scratch-gui#425]
### Expected Behavior

Pressing the escape key while the library browser dialog is visible should close the dialog, like in the "create variable" dialog.

### Actual Behavior

The escape key does nothing in the library filter dialog. This is inconsistent with the "create variable" dialog and most system popup behaviour I know (e.g. pressing the escape key in the "open" system dialog cancels the open operation).

### Steps to Reproduce

Open the library browser in any way (e.g. clicking on the "add costume" button). Press the escape key.

### Operating System and Browser

macOS 10.12.5, Chrome 58.0.3029.110.

**Comment by paulkaplan** [comment]
Definitely agree! Submitted a patch for this, https://github.com/LLK/scratch-gui/pull/427
