### ISSUE TITLE
Can only add sprites from backpack to limited area in sprite listing area

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#4254]
### Expected Behavior
The user should be able to add a sprite from the backpack to a project by dragging the sprite into any part of the sprite listing area

### Actual Behavior
The user can only add a sprite to the project by dragging into a limited area

### Steps to Reproduce
- Add sprite to backpack
- Create a new project
- Attempt to add sprite to the project by dragging it to the bottom of the sprite listing area

### Reference
![2](https://user-images.githubusercontent.com/747641/50693566-55b02980-1005-11e9-808e-14805d01dcba.gif)

### Operating System and Browser
Mac OS 10.14.1 | Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by apple502j** [comment]
My sister also found that we cannot add sprites via backpack if there are no sprites.
