### ISSUE TITLE
When timer > 0 or (some small number) can cause a non-fatal error

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#4257]
### Actual Behavior

A simple project with just this stack

![image](https://user-images.githubusercontent.com/1786240/50699285-71233080-1015-11e9-95af-9f3f6b862ac9.png)

 will cause an error in the console because the blocks are being run before the stage exists. Since broadcast messages are stage variables, and the stage doesn't exist yet, running the broadcast block causes the following error:

Uncaught TypeError: Cannot read property 'lookupBroadcastMsg' of undefined

**Comment by BonfireScratch** [comment]
Currently it causes a DOMException on raven.min.js and a message("Trying to cancel a gesture recursively")

**Comment by kchadha** [comment]
After some investigation, it looks like executableTargets gets populated during target creation, well before the targets are fully installed. `executableTargets` was introduced by LLK/scratch-vm#1617, replacing the runtime's list of targets on [this line](https://github.com/LLK/scratch-vm/pull/1617/files#diff-38d875e1d50b3158dc96404b65275a54R1254). 

Thus, this is an issue introduced by this PR where scripts are running on sprites/the stage before the sprites/stage fully exist and are ready to be used on the runtime.
