### ISSUE TITLE
Remove preview modal from codebase

### ISSUE THREAD

**Issue by 439bananas** [LLK/scratch-gui#4263]
### Expected Behavior

The repository should I believe be for the most recent version of Scratch 3.0

### Actual Behavior

On open of http://localhost:8601/, Scratch 3.0 beta popup appears.

### Steps to Reproduce

-Follow instructions for Scratch 3.0 development version install
-Go to http://localhost:8601/
-Observe

### Operating System and Browser

My browser / operating system: Windows NT 10.0, Chrome 71.0.3578.98

**Comment by towerofnix** [comment]
^ See my post in there:

> The [scratch-gui] repository does contain all the exact same code that is deployed onto the Scratch website (as far as I can tell). The reason the repository behaves differently from the website when you run it is that, since it is not connected to the website, there is some functionality that it simply cannot do. For example, auto=save does not get performed when you are running the repository, even though all the code for auto-saving is present in this repository; there simply is not a notion of auto-saving when you are not logged into an account to auto-save to. (And of course, you cannot log into Scratch from inside the editor; the editor simply enables auto-saving if it has account data passed to it, which is done so by the scratch-www repository, but not when you run the repository locally.)

**Comment by benjiwheeler** [comment]
Thanks, @towerofnix. Great explanation.

Seems to me that we should change some of that popup modal's language, now that 3.0 is launched, to focus on it being the standalone version, rather than a beta.

**Comment by thisandagain** [comment]
I would rather completely remove the modal as it is no longer needed and simply in the way for most development.
