### ISSUE TITLE
Copied costumes don't automatically go to the bottom

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#4264]
### Expected Behavior
In Scratch 2, copied costumes always go to the bottom of the costume list.
### Actual Behavior
They don't.
When I try to drag them to the buttom, I found that scrolling and draging does't work. 
The video showed how did I drag a costume from top to bottom(clipped)
[造型拖曳的bug.zip](https://github.com/LLK/scratch-gui/files/2728990/bug.zip)
### Steps to Reproduce
Try to drag a costume within a long costume list.
### Operating System and Browser
Win 8, Chrome 70

**Comment by towerofnix** [comment]
I Think duplicated costumes appearing right below the selected costume is a feature, but not being able to reorder costumes downwards (like in your video) is definitely a bug.

**Comment by thisandagain** [comment]
Agreed. @cyx2015s do you mind editing this or creating a new issue that focuses on the dragging issue you are seeing?
