### ISSUE TITLE
PTE scripts lost

### ISSUE THREAD

**Issue by BonfireScratch** [LLK/scratch-gui#4265]
### Expected Behavior

it should render pen-generated text.

### Actual Behavior
PTE text is not rendered. In fact, PTE scripts don't even exist!

### Steps to Reproduce

Find a project that uses a PTE.
Press see inside.
Go to the PTE sprite

### Operating System and Browser

_Windows 7 Chrome 71.0.3578.98_

**Comment by BonfireScratch** [comment]
@apple502j I don't know. I use the Machinumps' and -Rex-'s. But I have realised that djpro's PTE works

**Comment by towerofnix** [comment]
For reference to anyone reading, a PTE is a "pen text engine" (a sprite that uses pen lines or stamps to draw text as requested).

**Comment by BonfireScratch** [comment]
@towerofnix Indeed. @apple502j it seems like I'm using hacked blocks

**Comment by BonfireScratch** [comment]
@griffpatch @apple502j does any of you know whether there will be hacked blocks on 3.0? It can be done, currently there has to be JavaScript file preventing them to be rendered

**Comment by towerofnix** [comment]
@BonfireScratch see LLK/scratch-vm#1882 for a brief picture of the issue. There is no simple fix - [see discussion here](https://scratch.mit.edu/discuss/post/3381960/). And see LLK/scratch-vm#1030 for a review of other things regarding hacked blocks that are broken now, and discussion/efforts to fix these.

That said, scripts not showing up at all seems more like an instance of LLK/scratch-vm#1077.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/1030
