### ISSUE TITLE
Why git repo seems not the same as scratch 3.0 release ?

### ISSUE THREAD

**Issue by ysun** [LLK/scratch-gui#4268]
### Expected Behavior
Repo has exactly the same version as 3.0 release.
_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
Duplicate of #4263
