### ISSUE TITLE
Ask box should appear over monitors

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#4269]
### Expected Behavior

The box that shows up from "ask and wait" should show up above monitors.

### Actual Behavior

It doesn't:

![Ask box below a variable monitor](https://user-images.githubusercontent.com/9948030/50726909-b3b63d00-10e9-11e9-8063-da637f785b24.png)

This makes it difficult to enter a value, and it can even conceal the question if the asking sprite is hidden and the monitor is positioned above the question label.

### Steps to Reproduce

Show a monitor and position it around the bottom of the screen, then click on an "ask and wait" block.

### Operating System and Browser

Firefox 65.0b7, Linux (Debian).

**Comment by benjiwheeler** [comment]
related to z-index (adding this comment in hopes of improving search/findability of related issues)
