### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by beitaz** [LLK/scratch-gui#4272]
For the end user, all projects should be an out-of-the-box application, rather than having to compile from source every time.

### Expected Behavior

Download -> Run

### Actual Behavior

Download -> **Build** -> Run

### Steps to Reproduce

1. Create project
2. Share my project
3. Open shared project -> Downloading resources -> Building -> Project running
4. Refresh browser -> Downloading resources -> Building -> Project running

### Operating System and Browser

All platform.

**Comment by towerofnix** [comment]
I'm confused - I don't see this "downloading resources" and "building" step, are you talking about the loading screen? (Those are just "fake" messages that more or less describe what is going on, but don't accurately represent it step-by-step.) To be clear, Scratch is an interpreted programming language, not a compiled one, so there is no concept of out-of-the-box or an all-in-one compiled binary of the project.
