### ISSUE TITLE
"Define" feature missing

### ISSUE THREAD

**Issue by DrDingleberry** [LLK/scratch-gui#4273]
### Expected Behavior
Right-clicking on a custom block in the code side-bar brings up a context menu. There should be two options, "edit..." and "define". The "define" option would take the user to the point in the project where that custom block was defined at.
### Actual Behavior

The only option that appears is the "edit..." option.

### Steps to Reproduce

Right-click on a custom block in the code-sidebar.

### Operating System and Browser

Firefox 64.0 (64 bit) Windows 10

**Comment by towerofnix** [comment]
Duplicate of LLK/scratch-blocks#1136, which has a to-be-reviewed PR that implements this: LLK/scratch-blocks#1834.

**Comment by DrDingleberry** [comment]
Ah. Good to hear!

**Comment by thisandagain** [comment]
Tracking in LLK/scratch-blocks#1136
