### ISSUE TITLE
How to compile scratch-gui to window scratch desktop

### ISSUE THREAD

**Issue by crouse12** [LLK/scratch-gui#4274]
May I know how to compile Scratch-GUI to Scratch Desktop worked on Windows?

**Comment by apple502j** [comment]
Scratch Desktop's code is not public yet.

**Comment by SheepTester** [comment]
I think you can simulate Scratch Desktop by adding `?isScratchDesktop=true` to the URL

**Comment by crouse12** [comment]
So, scratch gui cannot be compiled to an exe file.
May I know when the scratch desktop's code is public?

**Comment by SheepTester** [comment]
Quite sure this repository is Scratch Desktop as well

**Comment by thisandagain** [comment]
We have not open-sourced Scratch Desktop yet, but will in the near future.
