### ISSUE TITLE
Unexpected behaviour in Catch Game - falling apple went super fast, score incremented super quickly

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#428]
Splitting this off from https://github.com/LLK/scratch-gui/issues/415 since it seems like a separate issue from issue with the order in which the stacks are run.

### Expected Behavior

Following the Catch Game cards, the apple should fall from top of screen to bottom repeatedly, score should increment when apple + cat touch. The apple's movement should not be super fast.

### Actual Behavior

- **Mysterious:** Somehow I got in a state towards the end of trying these things that caused the green flag not to work to restart the project even if I clicked on another stack in the project, which had worked consistently previously to "fix" the project
  - The stack that moves the apple did start working again eventually when I clicked it, but it caused the apple to move very quickly over the screen and the score to increase very quickly. 
  - There weren't any new errors in the console, other than the ones I had seen consistently already.
  - Once I was in this state, clicking that stack would always make the apple & score go crazy, but if I clicked green flag when the stack was active, it would return the project to acting "normally"
  - Green flag continued not to work to start the project unless that particular stack was active; clicking another stack, then green flag, does not start the project
  - **Very weird**: the project was consistently working normally then going crazy cyclically if I clicked red stop sign, both stacks (the one that moves the apple up and down and the one next to it), then the green flag; and if I clicked the green flag then clicked both stacks
    - I started to screen record this, but Google Calendar stole attention from the gui
    - When I came back to the gui to continue recording, the project seemed to have fixed itself
    - I'm back to only seeing issues 1 & 2 (https://github.com/LLK/scratch-gui/issues/415#issuecomment-306819572)

**The apple & score going crazy**
![out](https://user-images.githubusercontent.com/1320456/26885722-6b89e35e-4b71-11e7-8379-71620f56283a.gif)

**The state of my project during this issue**
- Note stop all block is not connected to a stack
- Note score is 0
- Note that green flag does not work to restart project
- Unless I click the stack that moves the apple up and down, then click green flag while that stack is active

<img width="1280" alt="screen shot 2017-06-07 at 11 09 05 am" src="https://user-images.githubusercontent.com/1320456/26885884-dbc34958-4b71-11e7-8327-4d7de214c0c8.png">
<img width="1280" alt="screen shot 2017-06-07 at 11 08 57 am" src="https://user-images.githubusercontent.com/1320456/26886018-482879f6-4b72-11e7-831a-ccdf1ab05e27.png">
<img width="1280" alt="screen shot 2017-06-07 at 11 08 47 am" src="https://user-images.githubusercontent.com/1320456/26885883-dbb80b42-4b71-11e7-8849-c5e010031e56.png">

### Steps to Reproduce

I'm not sure, I only got into this state after messing around trying to repro & looking into https://github.com/LLK/scratch-gui/issues/415 for a while.

### Operating System and Browser

_Mac, Chrome_

**Comment by rschamp** [comment]
@paulkaplan If you have extra time could you look at this?

**Comment by paulkaplan** [comment]
@rschamp I haven't been able to reproduce. @jwzimmer is it ok to close this until/unless it comes up again?

**Comment by jwzimmer** [comment]
@paulkaplan fine with me, thanks 👍
