### ISSUE TITLE
Change behavior for "Browser Incompatible" state

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#4297]
## Background
We are seeing lots of reports of fatal errors from users who (upon further investigation) are using older versions of browsers that are not supported (e.g. Safari 9, Chrome 49, etc). At the same time, we have had discussions with various Scratchers that are frustrated by us being fairly conservative with what platforms with support (e.g. Opera, Vivaldi). 

## Proposed Change
We should remove the current "Browser Unsupported" modal which blocks specific browsers and browser versions that are below our "supported" version threshold. Instead, we should only display this error state in the event of a fatal (e.g. BSOD) exception.

### Current State
- User loads a project running Safari 9
- User is immediately presented with a "Browser Unsupported" modal

### Future State
- User loads a project running Safari 9
- The application throw a fatal exception
- User is presented with a "Browser Unsupported" message

### Current State
- User loads a project running Opera 57
- User is immediately presented with a "Browser Unsupported" modal

### Future State
- User loads a project running Opera 57
- User can use Scratch

### Current State
- User loads a project running Chrome 61
- User is immediately presented with a "Browser Unsupported" modal

### Future State
- User loads a project running Edge on XBox
- User can use Scratch until they potentially encounter a feature / action which results in a fatal exception
- User is presented with a "Browser Unsupported" message

### Headline
```
An Error Occurred
```

### Body
```
We are very sorry, but it looks like you are using a browser that Scratch does not support. We recommend updating to the latest version of a supported browser such as Google Chrome, Mozilla Firefox, Apple Safari, or Microsoft Edge. 
```

**Comment by chrisgarrity** [comment]
This can work for everything other than IE. IE fails on importing the gui, so it doesn't even get to the BSOD. So I think we should keep the current browser modal just for IE (or any other browser that cannot even get to the error boundary)

**Comment by thisandagain** [comment]
@chrisgarrity Sounds good to me!
