### ISSUE TITLE
Global Variable becomes Local

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-gui#4302]
A variable marked as global switches to being local for one sprite, but stays global on the others...

In my Slither.io game https://scratch.mit.edu/projects/108566337
I have noted that sometimes the main player becomes invulnerable now and then. What I discovered just now is that the variable that holds whether you have been killed (KilledBy) had become 'local', but only for the first sprite in my game... in all other sprites it still had a global value. This breaks the game greatly, but sadly I clicked save on my project while in this state. Trying to resolve this is NOT easy as all references got messed up when I tried to delete the local variable.

I have seen this happening quite a bit, but without knowing what was the reason. I think this is it. Perhaps the slowness of loading a given sprites scripts? Running a project quickly while loading? or something like this might cause the issue... but it's devastating to a project when it happens and really hard to recover your game from. (deleting the local variable, even when the global exists) removes all references to that variable from that sprite... Deadly :(

### Operating System and Browser

Chrome Windows 10

**Comment by BonfireScratch** [comment]
This is a really serious bug. I have also experienced it before, but it actually caused no problem in my scripts, perhaps it was unused.
@griffpatch when did you realise the bug? Had it messed up before the project had or did this occur while viewing/running the project?

**Comment by griffpatch** [comment]
I believe it can occur even when people are playing the game (not the
owners of the project). But on this occasion it happened to me and knowing
the issue had occurred I looked inside.... And it saved :(

**Comment by thisandagain** [comment]
@griffpatch Oh no! Thanks for reporting this. This is pretty serious and we'll look into it.

**Comment by BonfireScratch** [comment]
@griffpatch indeed, I saw it change while playing the game. Also, players could pass through my snake and I could kill nobody!

**Comment by BonfireScratch** [comment]
@kchadha I will try to recreate the issue

**Comment by griffpatch** [comment]
I'm sorry, but I don't know how to replicate it... All I know is that I've
seen the symptom in game multiple times since scratch 3 came out as my game
was played, but only this one time for I click to look inside rather than
just reloading the project. I am just speculating at the reason. It's
remotely possible that this was not the reason for the issue, and that on
instigating by looking inside that the local variable was created...
Leading to exactly the same issue that was playing out in game already, but
that is unlikely.

I will try to investigate more

Griffpatch

**Comment by picklesrus** [comment]
I found a repro, but it involves setting variables in a when timer > 0 hat block stack.
  @griffpatch's slither project doesn't seem to use the when timer > 0 event block though, so there might be other ways to trigger this too :-/

**Comment by picklesrus** [comment]
For reference, here's my repro case. Notice that the "var" variable was created on the stage, but by setting the value in the soccer ball sprite with a when timer > 0 (which is happening before the stage has a chance to instantiate itself) it is creating both a local and global version.  The values in the monitor for var in the stage vs the soccer sprite and they should be the same.
<img width="1413" alt="screen shot 2019-01-10 at 1 49 06 pm" src="https://user-images.githubusercontent.com/15675877/50989877-8baa4d80-14de-11e9-817b-73f2ea5c5aae.png">
<img width="1413" alt="screen shot 2019-01-10 at 1 48 54 pm" src="https://user-images.githubusercontent.com/15675877/50989882-8e0ca780-14de-11e9-965a-174acb20e734.png">

**Comment by griffpatch** [comment]
What about if you play it embedded and then click look inside and save?

**Comment by griffpatch** [comment]
One thing I have noticed is that sometimes embedded projects can go to the click play round button state 'before' the assets behind have fully loaded. This is not occuring for me right now, perhaps they are al cached, or scratch's servers are running better, but when that occurs I have seen the project just come up white in the past with no game when you click the large green flag. I would say that clicking the play button before the project has loaded is almost certainly the issue here. On network games people are often impation with the load time so they can get playing and join the fun before the game slots become full.

**Comment by fsih** [comment]
@colbygk is it possible to get older versions of the project 108566337, like the sb2 file? It might be helpful to compare that and the current file, but at least griffpatch could restore his game

**Comment by kchadha** [comment]
@griffpatch, that last thing you mentioned is being tracked in #4293, and it is indeed a cause for concern when combined with https://github.com/LLK/scratch-gui/issues/4257#issuecomment-452433108

We are currently working on a fix for the latter, so it should hopefully help to prevent this issue from occurring again.

**Comment by kchadha** [comment]
@griffpatch, the fix for both issues mentioned in my last comment should be in production now. I believe at least one of these was the root cause for this issue, though I was not able to reproduce this bug specific to your project/scenario. I'm closing this issue, but please feel free to re-open it if you see the issue again.

You can fix the broken project by manually editing the project json to remove the variable in question from the sprite's variables section. A fortunate side-effect of this bug is that the variable keeps the same ID in the smaller scope, so after deleting it from the sprite's `variables`, all the blocks referencing the variable in that sprite should now be able to find the reference in the global scope.

I hope this helps! Please let me know if you have any questions.

**Comment by blazepandayt18** [comment]
@griffpatch hello griffpatch i was wondering if you could tell me how to use global var in scratch to make a mmo btw im a huge fan i look forward to seeing if we can callab in the future maybe
