### ISSUE TITLE
Pen is not a perfect circle

### ISSUE THREAD

**Issue by seotts** [LLK/scratch-gui#4313]
### Expected Behavior

Using the pen extension, if you use "pen down" and then immediately "pen up," the resulting dot should be a perfect circle. 
 
### Actual Behavior

The dot is a pixel or two taller than it is wide, which is especially noticeable for small pen sizes. (See [this project](https://scratch.mit.edu/projects/220220160/); in 2.0, the stars were circular. 

![image](https://user-images.githubusercontent.com/4612592/50982192-9529ba80-14ca-11e9-8124-7a642418f00f.png)

### Steps to Reproduce

I made [this project](https://scratch.mit.edu/projects/278583891/) to demonstrate the problem. At small pen sizes, the oval shape is fairly easy to see; at larger pen sizes, there is still a 1-2 pixel difference, as detected by a scanner sprite. 

### Operating System and Browser

MacOS 10.14.2; Chrome 71.0.3578.98

**Comment by Mr-Dave2** [comment]
Several people mentioned, in the now-gone 3.0 beta forum, that pen drawn small dots, that used to look like small dots, now look like small rectangles.

Comparing 2.0 to 3.0 (2.0  image is on top)
![d393ee7a-3fc2-46f6-9d51-02477215e247](https://user-images.githubusercontent.com/35544966/52433826-96eb9b80-2ad3-11e9-864a-bff11e7f7af1.png)


My project (with some out of date instructions) is [here](
https://scratch.mit.edu/projects/245159517/)
