### ISSUE TITLE
Comment has focus and insertion cursor on project load

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#4324]
### Expected Behavior

1. make a project with a block comment on the first sprite. (don't make a comment on the workspace). Add text to the comment and click away.
2. save
3. reload in editor
4a. the comment should not have an insertion cursor blinking
5a. the menu bar should not say "Save now"

### Actual Behavior

4b. the comment DOES have an insertion cursor blinking :(
5b. the menu bar DOES say "Save now" :( (presumably because the comment got focus)

Observed on Mac Chrome and Mac Safari. (Safari has the insertion point at the beginning of the existing comment text; Chrome has it at the end.)

**Comment by paulkaplan** [comment]
Fixed with recent comment update
