### ISSUE TITLE
buggy sounds (with zero length in 2.0) cause crash/BSOD on 3.0

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#4325]
https://scratch.mit.edu/projects/241130603/ is a publicly shared project (source sb2: 
[MII MAKER 2 - Edit And Share Your Avatar.sb2.zip](https://github.com/LLK/scratch-gui/files/2750786/MII.MAKER.2.-.Edit.And.Share.Your.Avatar.sb2.zip) ) which loads with a BSOD crash in 3.0 .

The crash is 
`undefined is not iterable (cannot read property Symbol(Symbol.iterator))`, in one of the packaged libraries.

When I download this sb2 and try uploading it to my account in 3.0, it won't load. But when I edit the sb2 first, I notice that there are many sound assets that have a length of zero seconds. Weird! (But apparently this is a known bug from the past of 2.0.)

When I remove all of these, the project uploads fine and everything works!

Is there a way we can detect these invalid assets, and avoid trying to load them?

**Comment by ericrosenbaum** [comment]
fixed by https://github.com/LLK/scratch-audio/pull/115
