### ISSUE TITLE
Import .txt file to list doesn't work well

### ISSUE THREAD

**Issue by sqrt-panda** [LLK/scratch-gui#4329]
### Expected Behavior

new line is preserved

### Actual Behavior

When first letter of text file is double quotation, new line is not loaded
This problem occurs in CR, LF and CRLF.

test text file
![image](https://user-images.githubusercontent.com/39018125/51069404-df00d500-1671-11e9-9905-9ecec282881b.png)

Scratch 2.0
![image](https://user-images.githubusercontent.com/39018125/51069384-83364c00-1671-11e9-83ef-3249c7f45f2f.png)

Scratch 3.0
![image](https://user-images.githubusercontent.com/39018125/51069401-c0024300-1671-11e9-9ed6-5a8ea21927d7.png)

### Steps to Reproduce

1. Prepare a double quotation text file for the first letter
2. On Scratch 3.0, import this file to list

### Operating System and Browser

Windows10 Chrome71 and Firefox64

**Comment by apple502j** [comment]
This happens because CSV uses quotes when one contains line break or separator.
Maybe we need to use other parsing.

**Comment by sqrt-panda** [comment]
I found a similar bug.
![image](https://user-images.githubusercontent.com/39018125/51252290-c9c3d780-19de-11e9-8097-284059ba22b3.png)
After comma character is not loaded.
![image](https://user-images.githubusercontent.com/39018125/51252348-e9f39680-19de-11e9-8552-511fffafe112.png) ![image](https://user-images.githubusercontent.com/39018125/51252370-fed02a00-19de-11e9-8a11-7c776b8ca9bf.png)
I agree with @apple502j 's opinion.

**Comment by picklesrus** [comment]
We discussed this and the problem we want to solve is that Scratch 3 is not consistent with itself in importing and exporting of lists. Closing this in favor of solving that issue: https://github.com/LLK/scratch-gui/issues/6565
