### ISSUE TITLE
Variables in the player cover the 'my stuff' menu

### ISSUE THREAD

**Issue by jfo8000** [LLK/scratch-gui#4331]
### Expected Behavior

Open the 'my stuff' menu without overlapping variables.

### Actual Behavior
![image](https://user-images.githubusercontent.com/16273166/51080386-023d8a00-172f-11e9-846e-05c36c8f9914.png)

### Steps to Reproduce

Create a new scratch project
Open the data section
Check 'my variable'
Drag it to the right hand side.
Open the 'my stuff' menu

Variable overlaps the menu

Note: this looks to be a simple matter of bumping up the z-index of the menu bar?  In the inspector I changed it from 41 to 999 and the bug went away.

Here is the relevant style 
```
.menu-bar_menu-bar-menu_239MD {
    margin-top: 3rem;
    z-index: 999; /* <---- used to say 41 */
}
```

### Operating System and Browser

Mac / Chrome

**Comment by joker314** [comment]
Hi! This is being tracked in LLK/scratch-www#2587

**Comment by BonfireScratch** [comment]
Somebody close this issue
