### ISSUE TITLE
Tutorial window needs to be able to be minimized without losing one's place

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-gui#4340]
The resources team is hearing from a variety of educators that students are losing their place in tutorials when they close the tutorial window temporarily to move it out of the way to follow a step. 

Suggestion is to be able to close or collapse the window without losing their place. 

/cc @zoebentley @kosiecki17 @SpeakkVisually

**Comment by thisandagain** [comment]
@carljbowman I'm adding this to the schedule for implementation in March. Does that work for you?

**Comment by ericrosenbaum** [comment]
We did this!
