### ISSUE TITLE
Speech bubble incorrectly positioned 

### ISSUE THREAD

**Issue by SpeakkVisually** [LLK/scratch-gui#4344]
Speech bubbles should appear to the top left or right of a sprite. However, speech bubbles currently display in what appears to be costume's center?

<img width="235" alt="screen shot 2019-01-14 at 4 04 19 pm" src="https://user-images.githubusercontent.com/5166432/51141038-1c05cc80-1816-11e9-9295-ffc141fdf1b1.png">

**Steps to Reproduce**

Use a say or think block. 

 **Operating System and Browser**
Mac High Sierra 10.13, Chrome 71.0.3578.98

**Comment by paulkaplan** [comment]
Thanks! resolved by https://github.com/LLK/scratch-render/pull/398
