### ISSUE TITLE
UX: Duplicate and Delete are right next to each other, causing deleted sprites.

### ISSUE THREAD

**Issue by jfo8000** [LLK/scratch-gui#4345]
### Expected Behavior

I recently ran a scratch camp with a bunch of kids using 3.0.  A lot of my old tutorials included 'stamping' sprites to duplicate them.  E.g. we would code one ghost sprite, then duplicate it to have multiple bad guys running along the screen.  

In 3.0 it is very easy to accidentally delete the ghost you just coded. 
![image](https://user-images.githubusercontent.com/16273166/51141303-ebb54100-189c-11e9-92ce-b6a01d820212.png)

Suggest that in the ContextMenu for the sprite selector item, a horizontal rule be added between actions that create/duplicate and actions that destroy.
    
https://github.com/LLK/scratch-gui/blob/57aed74998a4bd41df3caa13a0f9cab5fbe703bc/src/components/sprite-selector-item/sprite-selector-item.jsx

### Actual Behavior

Several kids accidentally deleted their sprites during camp because the stamp tool is no longer in 3.0.  

### Steps to Reproduce

Drink 4 cups of coffee
New scratch project
Right click on cat
Try to select duplicate, but accidentally choose delete

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by benjiwheeler** [comment]
Reopening this because we are reverting https://github.com/LLK/scratch-gui/pull/4359
