### ISSUE TITLE
Save related messages are not translated

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#4367]
### Expected Behavior

Save now, project saved, etc. are translated

### Actual Behavior

They aren't

### Steps to Reproduce

Save a project in another language

### Operating System and Browser

All

**Comment by apple502j** [comment]
This is not a bug - these texts were added to Transifex late so that the translators couldn't translate and review by the end of last December. Actually, in Japanese, these show up correctly, in Japanese. [wontfix].
