### ISSUE TITLE
What should the behaviour of the block input field be when it extends behind the stage?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#437]
### Expected Behavior

I'm not sure.

### Actual Behavior

- To see the value of the block/ the whole block, you need to scroll in the scripting area; clicking the stack doesn't cause it to appear in front of the stage. 
- To edit the value of the input field in the block, you need to click in it, but then it will appear over the stage so you can see the whole value.
  - This behaviour is convenient, because it allows you to see the entire value you're editing without moving the scripting area position, then clicking in the input field again to edit it, but it does look a bit weird.
  - Should there be a max length to the input?
- If your value is SUPER large, it extends out of the gui altogether

I'm wondering if there is some equally convenient behaviour that won't look weird? Or perhaps it should stay the way it currently is?

<img width="865" alt="screen shot 2017-06-12 at 1 35 29 pm" src="https://user-images.githubusercontent.com/1320456/27046868-08195b36-4f74-11e7-8582-23f4854b0a01.png">
<img width="783" alt="screen shot 2017-06-12 at 1 35 22 pm" src="https://user-images.githubusercontent.com/1320456/27046867-08181320-4f74-11e7-8de0-6426642cbbfc.png">

Out of the gui:
<img width="1279" alt="screen shot 2017-06-12 at 2 23 24 pm" src="https://user-images.githubusercontent.com/1320456/27048718-df2320d4-4f7a-11e7-9edf-d03612c29fe8.png">

### Steps to Reproduce

- Drag out a block and enter a long input into one of its fields so it extends behind the stage.
- Click the block.
- Click the input field to edit it.
- Click the scripting area to lose focus.
- Note behaviour of the block & input field.

### Operating System and Browser

_Mac OS El Capitan, Chrome 59_

**Comment by jwzimmer** [comment]
The "beyond" part is actually https://github.com/LLK/scratch-blocks/issues/430, so removing that from this issue. This issue is just about whether it should go in front of the stage like it currently does.

**Comment by thisandagain** [comment]
Tracking in llk/scratch-blocks#430
