### ISSUE TITLE
Renaming a variable doesn't update existing "(var) of (sprite)" sensing blocks

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#4392]
### Expected Behavior

When you rename a variable, all the "(attribute) of (sprite)" menus that have that variable and sprite selected, in every sprite, should be changed to reference the variable's new name.

### Actual Behavior

They don't get updated; they still reference the old name, which is of a variable that doesn't exist, so the block always returns 0.

### Steps to Reproduce

1. Create a "for this sprite only" variable in a sprite.
2. Drag out an "(attribute) of (that sprite's name)" block, and set the attribute menu to the variable.
3. Rename the variable.
4. Note that the menu hasn't been changed. The block will always return 0, not the value of the variable that was originally picked from the menu.

Mind that the menu itself does always contain the right variable names; it's just that existing uses of the of block are not updated (which breaks projects that referenced the variable, requiring that the user go and find every use of the "of" block and update its selected option to the new name).

**Comment by adroitwhiz** [comment]
Reopening because these blocks still report old values until the sprites they belong to are clicked on.

**Comment by fsih** [comment]
Repro:
![rename repro](https://user-images.githubusercontent.com/2855464/83209767-136e1780-a127-11ea-8e05-c18e2dbb8f67.gif)

**Comment by fsih** [comment]
Lowering severity now that the variable gets renamed if you click on the sprite
