### ISSUE TITLE
Original project's cloud vars can be updated by other users via editing (without remixing)

### ISSUE THREAD

**Issue by ArnoHue** [LLK/scratch-gui#4401]
### Expected Behavior

Only the original project code should be able to update cloud variables.

### Actual Behavior

I was working with some Scratchers, who looked into one of my cloud projects (without remixing it). They changed code to make the player invincible (in what is usually a pre-remix copy of the project). However this resulted in cloud variables of the original project to be updated (highscore in this case, where they immediately managed to achieve the #1 score)

### Steps to Reproduce

Being logged in as Scratcher, click "Look into" on another user's cloud project (but do not remix), edit code and (re)run it - this changed code can still update the original project's cloud variables.

### Operating System and Browser

Windows 10, Chrome 71.0.3578.98

**Comment by BryceLTaylor** [comment]
@ArnoHue What account were they signed in with?

**Comment by ArnoHue** [comment]
> @ArnoHue What account were they signed in with?

Account was TommyHu. You can still see it on the cloudmonitor: https://scratch.mit.edu/cloudmonitor/97137611/ Running the project https://scratch.mit.edu/projects/97137611 one can notice that TommyHu got to the top of the highscores, as he simply added a lot of ghosts and magic pills just for fun. We were pretty surprised to see the new highscore not only appear in his session, but also for everyone else opening the project.

**Comment by BryceLTaylor** [comment]
I can not reproduce this issue.  I need more information about the conditions under which the this was seen. What operating system and browser were they using?  How did they access the project?  

I'm going to close this issue.
