### ISSUE TITLE
When an item in a list is used in a script and the script is running, the list should jump to the item that the script is using

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#4403]
### Expected Behavior

In Scratch 2.0, lists jump to the item that the script is using
### Actual Behavior
In Scratch 3.0, no.
### Steps to Reproduce
Make a project with list, drag out a "item #() of (list v),click to run it, the list doesn't jump to the used item.
### Operating System and Browser
I guess all.

**Comment by cyx2015s** [comment]
Sorry,

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/1385
