### ISSUE TITLE
Should be able to re-order sprites in sprite pane

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#442]
### Expected Behavior

We should be able to re-order sprites in the sprite pane, as in 2.0.

### Actual Behavior

Reported by @ntlrsk during Catch Game Internal Playtest II (6/12/17):
> There doesnt seem to be a way to change the order sprites appear in the list 

### Steps to Reproduce

Click on sprite pane in gui prototype and try to rearrange the sprites.

### Operating System and Browser

_Mac, Chrome_

**Comment by rschamp** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/225
