### ISSUE TITLE
Alert message div blocked some menu bar dropdown buttons

### ISSUE THREAD

**Issue by JinXJinX** [LLK/scratch-gui#4428]
### Expected Behavior

Alert message should not block partial menu bar dropdown buttons.

### Actual Behavior

menu bar dropdown buttons are blocked by alert message div
![scratch 3 0 gui](https://user-images.githubusercontent.com/12160296/51706671-3184ae80-1fed-11e9-9937-d79540080436.gif)

### Steps to Reproduce

1. trigger a alert message
2. click 'file' button in menu bar
3. you can see 'new' button and 'load from computer' button is covered by alert's div

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

Mac OS 10.14.2 Safari 12.0.2/ Chrome 71.0.3578/ FireFox 64.0.2

**Comment by thisandagain** [comment]
@carljbowman Any thoughts on the desired z-index here? I can see arguments both ways.

**Comment by thisandagain** [comment]
Thanks @carljbowman. Sounds good.

**Comment by benjiwheeler** [comment]
Related to https://github.com/LLK/scratch-gui/issues/4226

**Comment by benjiwheeler** [comment]
From my checking, it appears this issue was already fixed before #4916 went in. Possibly it was fixed by #4452.

**Comment by apple502j** [comment]
@benjiwheeler Not for me on Firefox 76:
1) On sound tab, upload non-sounds (this creates an alert that cannot disappear)
2) You cannot click Code/Costume tab
3) On develop you can

**Comment by benjiwheeler** [comment]
@apple502j I totally agree about the Code/Costume tabs. But this issue is about menu bar dropdown menus.
