### ISSUE TITLE
"Play sound" blocks when a sprite has no sounds have empty dropdown

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#443]
### Actual Behavior

Reported by @fsih during Catch Game Internal Playtest II (6/12/17):
> Play sound on the banana has a dropdown with an empty space with a checkmark next to it. Not sure what it should look like, but having an empty say bubble with a checkbox looks weird

**In 3.0:**
<img width="217" alt="screen shot 2017-06-13 at 9 53 00 am" src="https://user-images.githubusercontent.com/1320456/27085731-236338da-501e-11e7-9ffc-89f3e09a0e95.png">
<img width="713" alt="screen shot 2017-06-12 at 4 43 08 pm" src="https://user-images.githubusercontent.com/1320456/27054224-3fcf6dda-4f8e-11e7-8314-92a9992e27e4.png">

**In 2.0:**
<img width="190" alt="screen shot 2017-06-13 at 9 54 40 am" src="https://user-images.githubusercontent.com/1320456/27085821-630e7bfc-501e-11e7-8cd8-42cc14d9a5b1.png">

### Steps to Reproduce

Note the banana does not come with any sounds.

- Add banana from sprite library
- Go to sounds category
- Look at "play sound" and "play sound until" blocks
- Click dropdown

### Operating System and Browser

_Mac, Chrome_

**Comment by ericrosenbaum** [comment]
This is similar to the behavior in Scratch 2.0, for what that's worth:

<img width="98" alt="screen shot 2017-06-12 at 4 48 44 pm" src="https://user-images.githubusercontent.com/567844/27054491-175682ca-4f8f-11e7-9854-b8fab3cd3eaf.png">

**Comment by fsih** [comment]
The dropdown in scratch 3 opens a say bubble that's empty except for a checkmark. The dropdown in scratch 2 doesn't show an empty line, it shows "record...", which brings you to the sound tab. I think it would be nice if scratch 3 added "Add sound from library..." as well as eventually adding "record..." as options in the dropdown.

**Comment by heyitsmeuralex** [comment]
Also would be nice for text to appear, perhaps giving a link/shortcut to the Add Sound pane?

```
There are no sounds on this sprite! Add some!
```

**Comment by paulkaplan** [comment]
Now there is the `record` option!
