### ISSUE TITLE
Export assets

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#4437]
_Thanks to all Scratchers who found this problem, and thanks to kenny2github for finding out that this issue is not created on GitHub yet!_

### Expected Behavior
All assets should be exportable.

### Actual Behavior
There is no way to do so.

### Steps to Reproduce
1. Right-click costumes, sounds or backdrops. No way to export it.

### Operating System and Browser
any

### See also
ceebee: ["You can’t export sounds or costumes: This is another feature we do plan to implement in the future."](https://scratch.mit.edu/discuss/post/3388941/)

NOTE: I'll submit a pr for this soon.

**Comment by aoloe** [comment]
probably a nice idea.

but, if you really want, you can already export costumes and sounds by downloading the project to your computer and unzipping it.

not easy to find out about it, but does the job.

**Comment by hedgehog125** [comment]
It would also be nice if you could group the assets and download them all as a zip as well

**Comment by aoloe** [comment]
just download the project as a .sb3 file and unzip it...
.sb3 is just that, a .zip file (+ a `project.json` file that describes the project and contains your code).
you have all your assets in there.
