### ISSUE TITLE
Reporter with menu in palette highlights when monitor is enabled

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#445]
### Expected Behavior

When you click the checkbox next to a reporter in the palette, to enable its monitor, it should not highlight the block in a super weird flickery manner.

### Actual Behavior

This flickering highlight occurs for reporters which have menus.

![highlighting-reporter](https://user-images.githubusercontent.com/567844/27101129-76376d58-504e-11e7-9bff-43d6e5d47a38.gif)

(in reality the flickering is faster than it appears in the gif). 

### Steps to Reproduce

Click the monitor checkbox next to a reporter with a menu, such as "current year".

### Operating System and Browser

Mac OS 10.11.6 Chrome 59.0

**Comment by paulkaplan** [comment]
No longer occurs
