### ISSUE TITLE
How to compile scratch-desktop

### ISSUE THREAD

**Issue by crouse12** [LLK/scratch-gui#4453]
I find that there is a branch "scratch-desktop" in scratch-gui.
Can this branch be compiled to .exe worked on Windows like Scratch Desktop? 
If it can, please tell me how to do it. Thanks.

**Comment by thisandagain** [comment]
We have not yet released the "Scratch Desktop" repo that includes the Electron wrapper and related components for building executables for Windows and MacOS. This is something that we hope to do in the near future.
