### ISSUE TITLE
Order of items in dynamic menus

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#446]
- We would like to know how well/ often users discover items beyond the default item in the block dropdown menus
  - Maybe these items are not discoverable enough?
- We would also like to consider re-arranging items if they don't match expectations or do obscure functionality

**Moved from https://github.com/LLK/scratch-gui/issues/409:**

Reported by @ntlrsk:
> I had expected "touching <mouse pointer> to show the latest (other) sprite name, but realize now that's not how it works in Scratch 2.0. But something to consider. mouse pointer is more consistent, but much rarer than wanting to sense another sprite 

Group question:
> When should things be in the dropdown menus vs. separate blocks?

Relatedly, we were noticing that options from the dropdown menu may get used very rarely; for example, a lot of people were surprised to learn about go to [random position] but were familiar with go to [mouse pointer].

Reported by @mewtaylor:
> Should the default "switch costume" selection be the next costume in the series, rather than the already present, default costume?

**Comment by thisandagain** [comment]
We should talk about this post-alpha.

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#32
