### ISSUE TITLE
Can Scratch 3.0 Be Configured to Run Without WebGL?

### ISSUE THREAD

**Issue by CreativeComputerLab** [LLK/scratch-gui#4461]
I would like to run Scratch 3.0 on the Raspberry Pi 3B+. 

I have done the necessary configurations to enable the OpenGL and WebGL drivers to get Scratch 3.0 to run, however, it runs very slowly and consumes lots of CPU.

Is it possible to configure Scratch 3.0 to run in an optimized mode on embedded (or low spec) platforms by sacrificing some of the sophisticated graphic features by disabling WebGL?

I just want to drag blocks around and do basic coding lessons with kids in a low cost environment.

**Comment by towerofnix** [comment]
Unfortunately there isn't any code written as an alternative rendering system. While you could hypothetically remove the WebGL scratch-render backend (and break sensing blocks such as "touching color"), there wouldn't be (for example) a `<canvas>`-based backend to replace it with. So you'd just have a blank stage screen - definitely not fit for teaching with!

**Comment by CreativeComputerLab** [comment]
OK, just thought I'd ask. Thanks
