### ISSUE TITLE
Blocktionary (Block Lexicon) - do we want to change the set of blocks in the editor?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#447]
In the Editor Weekly (6/13/17) we were discussing issues including the following, and decided this warranted further discussion, probably going over all the blocks that are available currently in 2.0 and seeing if there any changes we want to make in 3.0:
- Are there blocks we should combine/ split, such as should "set" have a dropdown with x, y, etc.
- Which blocks should accept which kinds of arguments
  - (Note: not saying we should necessarily be particularly restrictive about this)
- Control vs. event blocks
  - Is that distinction clear enough?
  - Multiple ST members go to the "wrong" category - is that common?
- Play sound vs. play sound until done
  - This block (/these blocks) always causes confusion; should we rename it (/them)
  - Would reordering them in block palette help?
- Exposing ranges of values, such as "pitch" and x, y
  - How should we do that? 
  - Could the pick random block update?
  - Could there be more widgets?
- Layer blocks (go to front, etc)

**Split off from https://github.com/LLK/scratch-gui/issues/409:**

@jwzimmer reported: "Go to x vs. set x to _ ?"
I was just wondering about what the difference in "go to" and "set" in the blocks meant - it looks like maybe "go to" involves a pair of coordinates (x,y) whereas "set" refers to a single value? I was wondering if the distinction is important or if we need both "go to" and "set" since if you "set" x the sprite also "goes to" that x value (and vice versa)?

@jwzimmer reported: "Should "go to _" block accept "pick random"?"
Another question about whether it's fine for things to fit into blocks they don't make a lot of sense with (I think it probably is?).

@lifeinchords reported confusion around Play sound vs. play sound until done.

Jie reported:
> It's possible to put boolean inside number of repeats, but not sure what that's supposed to do?  Currently the block clicks in but nothing happens
<img width="590" alt="screen shot 2017-06-05 at 10 51 22 am" src="https://cloud.githubusercontent.com/assets/1320456/26789006/f2db60d0-49dc-11e7-9b54-651bd60009e6.png">

Group question:
> What are the ranges for the various things e.g. Pitch? It's hard to know what values to put into e.g. pick random when you don't know the range.

**Comment by mrjacobbloom** [comment]
> Control vs. event blocks ... Multiple ST members go to the "wrong" category - is that common?

YES I've been scratching for years and I honestly still couldn't tell you which contains what blocks

**Comment by liam4** [comment]
@mrjacobbloom It also doesn't help that the colour scheme has changed..!

Originally, in 1.4, there was just one category called Control. This contained all the Control and Events blocks we know today. But that category was getting awfully large, so it was split into two categories, Control and Events, in 2.0. They were separately coloured. Fast-forward to 3.0, and now the colours have been pretty much *swapped* – so it's not surprising that many people used to programming with Scratch 2.0 would get mixed up!

**Comment by TheInitializer** [comment]
>Are there blocks we should combine/ split, such as should "set" have a dropdown with x, y, etc.

I don't think dropdowns should be added if they only have 2 options, especially if the options are `x` and `y`.

**Comment by liam4** [comment]
Agreed with @TheInitializer. It's a bit comparable to the difference between `sprite.setX(123)` and `sprite.set("x", 123)`.

In my opinion, dropdowns should only be used for:

* All "dynamic" choices. Why have this..

  ![item-(1)-of-list, item-(1)-of-other-list, item-(1)-of-another-list](https://user-images.githubusercontent.com/9948030/27146063-672d98bc-510e-11e7-8fde-4bba6b5d2eb0.png)

  ..when you could just have this?..

  ![item-(1)-of-(some list name)](https://user-images.githubusercontent.com/9948030/27146115-8e579424-510e-11e7-816f-1f2e400aceb7.png)

* All "static" choices where there are many options that all have similar results.

  * The `set`/`change effect` menus are a good time to use dropdowns, since there are many options that all simply change the appearance of the sprite.

  * The `set`/`change x`/`y` blocks should *not* have dropdowns, since there are only two options – X and Y.

    * And - maybe this is opinion based - but it seems like X and Y need to be distinguished more than graphic effects; "swirl" is different from "mosaic", but maybe less so than the difference between "X" and "Y".

    * Additionally, keeping the "set [x/y] to .." block as two blocks is less expensive than having the "set [color/fisheye/whirl/pixelate/brightness/ghost/mosaic] effect" block being split into *eight* blocks! (Plus it would actually be *sixteen* blocks, since there's also the "change effect" blocks.)

---

> a dropdown with x, y, etc.

"etc" — Ah, are you finally implementing 3D scratch? ;)

**Comment by thisandagain** [comment]
We should discuss this post-alpha.

**Comment by jwzimmer** [comment]
Just a note on current 3.0 behaviour when combining unexpected inputs/ blocks, @ericrosenbaum & I were trying out the speech & wedo extensions and noticed that currently we can drop the reporter "speech" (this yielded "0") into the dropdown menu of "set voice to" and that we could drop "tilt angle [up]" into the "tilt angle [up]" block (this yielded "undefined").

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#31
