### ISSUE TITLE
Broken project editor on 63964192: no blocks, no sprites and no background

### ISSUE THREAD

**Issue by JuegOStrower** [LLK/scratch-gui#4472]
### Expected Behavior
The blocks, the sprites and the background should be shown in the editor.

### Actual Behavior
In [this proyect](https://scratch.mit.edu/projects/63964192/), the blocks, the sprites and the background are not shown in editor. As it's tracked on [this link](https://scratch.mit.edu/discuss/topic/331439/), this is one of the "Projects are working, but the code is gone". The project runs, but by many reasons, it's broken. I think this is one of the heaviest projects of all Scratch (13mb). It has more than 200 sprites and 1000+ scripts. The project is a Windows 10 Simulator, it has a lock screen. The "Slide up to unlock" is broken. It is imposible to "Slide up", and i can't find a Scratch 3.0 fix if the blocks are not shown.

### Steps to Reproduce
Go  [this proyect](https://scratch.mit.edu/projects/63964192/).
See Inside.

### Operating System and Browser
Windows 10 and Google Chrome

**Comment by thisandagain** [comment]
@BryceLTaylor Can you investigate?

**Comment by BryceLTaylor** [comment]
@JuegOStrower  this project seems to be working just fine.  This issue got fixed relatively early after release.
