### ISSUE TITLE
The lists and the variables are shown over the ask dialog

### ISSUE THREAD

**Issue by JuegOStrower** [LLK/scratch-gui#4473]
### Expected Behavior
If an Scratcher puts a list that on all the player (that fits the 480x360). And then, the ask block is run. The ask dialog should be over any list.

### Actual Behavior
The ask dialog, won't show, because the list is in front of it.

### Steps to Reproduce
Create a new project.
Make a new list.
Make it fit all the player size.
Make a script with the Green Flag and Ask block
Click Green Flag

### Operating System and Browser
Windows 10 and Google Chrome

**Comment by towerofnix** [comment]
Duplicate of #4269.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/4269
