### ISSUE TITLE
Making a new list on the background say "This variable"

### ISSUE THREAD

**Issue by maxiostro** [LLK/scratch-gui#4474]
### Expected Behavior
Make a new list. In the dialog, it should say "This list will be available to all sprites."

### Actual Behavior
In the new list dialog, it says "This variable will be available to all sprites.". Of course, it shouldn't say "Variables", that could confuse new scratchers. However, it's a minor bug.

### Steps to Reproduce
Go to any project. 
Go to the background.
Make a new list.
Read.

### Operating System and Browser
Windows 10 and Google Chrome

**Comment by paulkaplan** [comment]
This is what it looks like now 
![image](https://user-images.githubusercontent.com/654102/62378985-f9b67080-b513-11e9-9f05-95cea5587e8c.png)

**Comment by apple502j** [comment]
@thisandagain This needs to be reopend. It was actually never fixed - @paulkaplan saw that modal on a sprite. Of course you can make sprite-wide lists on a sprite. This issue is for stages, mind you

**Comment by paulkaplan** [comment]
Ah I see, thanks @apple502j

**Comment by heironimus** [comment]
I think the correct solution would be to change [this line](https://github.com/LLK/scratch-l10n/blob/800bc2645192e3e8dbc53e18486e702da446fe74/editor/interface/en.json#L146) on the `scratch-l10n`project to "This will be available to all sprites", removing the word "variable".

Is make a PR there the right solution or is there a better way to do this?

**Comment by apple502j** [comment]
@heironimus I think #5208 is better
