### ISSUE TITLE
Circumvent searching for an input block when you are using a block with an input?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#448]
We know what blocks are available for a certain input (e.g. operators for "if" blocks), so could we make it easy to choose the block you want once you have clicked in the input of another block (e.g. an "if" block) without you having to go to the category and search?

Split off from https://github.com/LLK/scratch-gui/issues/409:

@fsih reported:
> Random idea: what if you could click on a shadow block and get a dropdown of suggestions for what you could put in there? In particular it takes a really long time to search around the block categories and assemble enough blocks to write "if x > 10 and x < threshold" but what if you could click on the diamond in the 'if' block and it suggested all those operators to you in a dropdown

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#30
