### ISSUE TITLE
Scrolling acts as arrow keys input.

### ISSUE THREAD

**Issue by jakel181** [LLK/scratch-gui#4492]
### Scrolling up and down acts like an up down arrow key input.

_Scrolling up and down acts like an up down arrow key input, left right scrolling does not act as a left/right arrow key input._

### Steps to Reproduce

_Effects projects in all modes, editor, full-screen, project page, full-screen editor, that have a when up/down arrow key block in it_

### Example Project

_https://scratch.mit.edu/projects/284680865/_

### Scratch Topic

_https://scratch.mit.edu/discuss/topic/339260/_

### Browser and Operating System

_ChromeOS 11151.113.0, Chrome 71.0.3578.127, Flash 32.0 (release 0)_

**Comment by towerofnix** [comment]
@thisandagain wrote that this is a bug on his profile:

!["...That is not intended so I would say a bug."](https://user-images.githubusercontent.com/9948030/52343102-924cb780-29ed-11e9-846f-e6da9ccf27c0.png)

But it *is* an intended feature. See LLK/scratch-vm#290, LLK/scratch-vm#865; in fact, it's the sole purpose of this [`MouseWheel`](https://github.com/LLK/scratch-vm/blob/develop/src/io/mouseWheel.js) IO device.

**Comment by jakel181** [comment]
> @thisandagain wrote that this is a bug on his profile:
> 
> !["...That is not intended so I would say a bug."](https://user-images.githubusercontent.com/9948030/52343102-924cb780-29ed-11e9-846f-e6da9ccf27c0.png)
> 
> But it _is_ an intended feature. See [LLK/scratch-vm#290](https://github.com/LLK/scratch-vm/pull/290), [LLK/scratch-vm#865](https://github.com/LLK/scratch-vm/issues/865); in fact, it's the sole purpose of the [`MouseWheel`](https://github.com/LLK/scratch-vm/blob/develop/src/io/mouseWheel.js) IO device.

GAhhh! Sorry I'm still getting used to the scratch GitHub! Sorry about the duplicate!

**Comment by thisandagain** [comment]
Yeah. Sorry ... I was mistaken. This is an intended feature that actually worked in 2.0 as well.

**Comment by towerofnix** [comment]
No worries! You definitely had reason to believe it was a bug so it was right to make an issue for it. Mistakes like this happen all the time, so don't worry about it. :)

**Comment by jakel181** [comment]
^ Thisandagain It's fine :)
