### ISSUE TITLE
Import / Export to SB3

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-gui#45]
### Expected Behavior

A drop down on the top of the screen should exist called file, that should have in it (among other things) Upload from your computer, Download to your computer. Upload from your computer should create a file picker that picks and then loads an xml file, while download should generate and download an xml file.

### Actual Behavior

Feature not yet implemented.

I will need this as well for the demos & play tests over here. Should I make a pull request for this? Or is said feature on the way?

**Comment by thisandagain** [comment]
This is blocked by https://github.com/LLK/scratch-vm/issues/194

You can see the beginnings of an implementation here, but we have a lot of design work to do before we would consider a PR for this:
https://github.com/thisandagain/scratch-vm/tree/feature/194

**Comment by SillyInventor** [comment]
Ok. I will keep this on a separate branch then. Since, I intend to just make the calls to workspaceToDom and domToWorkspace, it should still be compatible if you decide you want this when LLK/scratch-vm#194 is resolved.

**Comment by thisandagain** [comment]
Great! Thanks.

**Comment by paulkaplan** [comment]
File save and load have been implemented. Closing.

**Comment by paulkaplan** [comment]
File save and load have been implemented. Closing.
