### ISSUE TITLE
Numbers under backdrop - are they clear enough?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#450]
Spun-off from https://github.com/LLK/scratch-gui/issues/409.

### Actual Behavior

@fsih reported:
> UI thing, I don't understand why it says "2" under my backdrop, I don't see 2 and clicking it doesn't show 2 things

**Comment by fsih** [comment]
Repro:
1. Click + to open backdrop library
2. Choose a backdrop

<img width="123" alt="screen shot 2017-06-13 at 17 10 43" src="https://user-images.githubusercontent.com/2855464/27104938-b48cfc14-505b-11e7-8d9f-6356a234c4b6.png">

Maybe clicking on the backdrop or number could bring you to the costumes tab

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#28
