### ISSUE TITLE
What happens at initialization? Resetting, state on green flag/ red sign, clearing of pen layer, etc.

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#451]
## At the Editor Weekly (6/13/17) meeting, we were discussing resetting, stamps, pen, what clears when you hit red stop sign and when you delete sprites/ backdrops, initialization, etc.

Spun-off from https://github.com/LLK/scratch-gui/issues/409:
Shruti reported confusion around when something was a previous stamp vs. the sprite itself when visible on stage:
> I deleted all the sprites, but still showing on the stage (it happens when I use stamp).

### Confusing project & thumbnail states

**Example projects**
* [Stamp cats - for testing](https://scratch.mit.edu/projects/147710357/)
* [Mosaic cats - for testing](https://scratch.mit.edu/projects/148052106/)
* [Foo Bar remix - cat swarm copy - for testing](https://scratch.mit.edu/projects/147720146/)

**Description**
<img width="632" alt="screen shot 2017-03-10 at 10 51 51 am" src="https://cloud.githubusercontent.com/assets/1320456/23801866/9997703c-057f-11e7-8541-d2911147745e.png">
When I stopped the project, Stamp cats - for testing, in the screenshot above, the cat must have been located somewhere off the edge of the project, since it is not visible in the screenshot.

In My Stuff, the project thumbnail displays the cat at some location, presumably where it stopped moving in one of the previous times the project was played, with no graphic effects. The stamped cats are not included in the thumbnail.
<img width="351" alt="screen shot 2017-03-10 at 10 54 34 am" src="https://cloud.githubusercontent.com/assets/1320456/23802013/f8991fd6-057f-11e7-92ce-cb835c291351.png">

When I return to this project via See Inside, the cat starts from the location shown in the thumbnail, even though I am not setting this value in the script, and it is not the location where the cat left off the last time I played and stopped the project (even if I “save now” the project).
<img width="609" alt="screen shot 2017-03-10 at 10 55 04 am" src="https://cloud.githubusercontent.com/assets/1320456/23802039/0beb1ec2-0580-11e7-8aae-fc80d09ea3b6.png">

When I view inside this project, Mosaic cats - for testing, Sprite 1 starts off screen, and the backdrop is blank. When I press the green flag, the sprite starts being stamped (on screen, near the green flag, since that’s where my mouse pointer is). When I press the stop sign, the regular sprite appears and the stamps stay visible on screen.
<img width="482" alt="screen shot 2017-03-10 at 10 55 34 am" src="https://cloud.githubusercontent.com/assets/1320456/23802051/1d6280be-0580-11e7-8a42-54afe243671e.png">

However, when I view the project in My Stuff, the thumbnail shows many of the stamps, again presumably from some previous run of the project.
<img width="448" alt="screen shot 2017-03-10 at 10 56 02 am" src="https://cloud.githubusercontent.com/assets/1320456/23802067/2e73d5c4-0580-11e7-8ea0-47291ec84344.png">

The Foo Bar remix - cat swarm copy - for testing project has the same confusing (to me) behaviour. In My Stuff, it shows a thumbnail where the cat sprite is located above and to the right of the center of the project pane, and the background is covered with stamps & clones. When I start the project, the stamps & clones are not visible, but the sprite does start off at that location (above and to right of center). I did not set this location or rotation angle of the sprite in the script itself. The state I last stop the project does not necessarily change the thumbnail in My Stuff or initial location of the sprite in the project when I next start it (after a refresh or leaving the page). (As long as I start/ stop the project without refreshing the editor or leaving the page, the state is preserved: the sprite starts/ stop at the same location and the stamps & clones are not cleared.)
<img width="356" alt="screen shot 2017-03-10 at 10 56 31 am" src="https://cloud.githubusercontent.com/assets/1320456/23802094/3f506d94-0580-11e7-9ff0-cc9e9adc2181.png">

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#27
