### ISSUE TITLE
[FEATURE REQUEST] Allow changing block padding

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-gui#453]
### What

_In the editor settings menu allow blocks padding (```Blockly.BlockSvg.MIN_BLOCK_Y```) to be changed
Specifically from 48 (Current/Default):_
![capture png48](https://user-images.githubusercontent.com/17478432/27154014-8b66be08-5121-11e7-979f-2deb7e7e102a.PNG)
_To 40:_
![40](https://user-images.githubusercontent.com/17478432/27154047-a5b53c62-5121-11e7-98d6-7298dccebb8e.PNG)

### Why

- _The community wants it (see https://scratch.mit.edu/discuss/topic/199574/ (You might have to do some searching))_
- _Easier to navigate through big projects on PC_

### Tablets

_The default should remain 48 so tablet users are not deterred_

**Comment by heyitsmeuralex** [comment]
A general ui scale option would be nice!
