### ISSUE TITLE
Unable to open scratch-gui in WkWebView

### ISSUE THREAD

**Issue by abhi3675** [LLK/scratch-gui#4543]
I am trying to open scratch in webview but unable to do so, I suppose there is some library or some animation which is thwarting it to open in the webview. There are even no logs printed to know the actual errors.
If anyone is successful in doing this, please reply.
Any leads will be appreciated

**Comment by thisandagain** [comment]
We would need more information to be able to support you with this. Please provide a stack trace or other errors that you are seeing.

**Comment by abhi3675** [comment]
So, the thing is:
When I open the scratch-gui create url in WkWebView, it gets open up in webview. But when I run the scratch-gui server locally on my PC and try to run webview with this locally hosted url, it doesn't display the scratch-gui, just the blank white page.
The funny part is I am not getting any console logs or error logs for this. This makes me a little dubious.

**Comment by BonfireScratch** [comment]
@thisandagain

**Comment by joker314** [comment]
@abhi3675 Do you run WkWebView on a separate computer/phone to where you're locally hosting scratch-gui? The URL that's generated for your local copy will only work on the computer that's hosting it.
