### ISSUE TITLE
Device Connection Flow uses the wrong app icon when referencing Scratch Link

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#4556]
Looks like we are using the Scratch Device Manager icon when referencing Scratch Link. We should use the Scratch Link app icon instead  

<img width="559" alt="screen shot 2019-02-14 at 1 30 45 pm" src="https://user-images.githubusercontent.com/3409578/52809209-b8153480-305d-11e9-8830-3505ee47a2ab.png">

@kathymakes - Do you mind exporting a replacement icon?

**Comment by kathymakes** [comment]
Added the files here! Looks like we are currently using an svg in the modal.
You can technically use the 1024px svg which is the "master" image but in case there's any need to use a smaller svg, I also added one that's the same size as the current.

[Scratch Link Icon Update.zip](https://github.com/LLK/scratch-gui/files/2866423/Scratch.Link.Icon.Update.zip)

**Comment by ericrosenbaum** [comment]
closed by https://github.com/LLK/scratch-gui/pull/4618
