### ISSUE TITLE
Duplicate a sprite , the blocks in new sprite remain the same id to previous

### ISSUE THREAD

**Issue by TheWindX** [LLK/scratch-gui#4573]
### Expected Behavior

a block should have its own unique ID

### Actual Behavior

when duplicate a sprite , the blocks in new sprite remain the same ID to previous

### Steps to Reproduce
0. create a block in current workspace
1. get its ID
```ID_1 = Blockly.getMainWorkspace().getTopBlocks()[0].id```
2. right click sprite then duplicate
3. in new sprite, get new block's ID depulicated
```ID_2 = Blockly.getMainWorkspace().getTopBlocks()[0].id```
4. test, you see
```ID_2 == ID_1```

### Operating System and Browser

window 10

**Comment by kchadha** [comment]
@picklesrus, I can take this one since it's actually a VM issue and it's also a bug that causes more project changed state issues. Let me know if you want to keep it or pair on it though.
