### ISSUE TITLE
Is it possible to make scratch-gui to look like scratch 2.0

### ISSUE THREAD

**Issue by crouse12** [LLK/scratch-gui#4581]
I find a software called stylish.
This software can make scratch 3 (https://scratch.mit.edu/) to look like scratch 2.0.
![image](https://user-images.githubusercontent.com/25700616/53224944-5f731680-36b1-11e9-97b6-e299cda37af1.png)
Can I know how to make scratch-gui to look like scratch 2.0?

**Comment by NilsTheBest** [comment]
You can, by [downloading the 2.0 offline editor](https://scratch.mit.edu/download/scratch2).

**Comment by Supermariofan432** [comment]
he means Scratch 2.0 on the gui website

**Comment by quickcashsolutionsatm-afk** [comment]
bro how you get this game
