### ISSUE TITLE
Automatically add When Green Flag Clicked block when starting a new project

### ISSUE THREAD

**Issue by Wasserboy08** [LLK/scratch-gui#4583]
### Expected Behavior

When a new project is started, the When Green Flag Clicked block should have been added. Some people decide to not watch the tutorial, and I remember not knowing that it is the intended way to do projects a few years ago.

### Actual Behavior

Project is empty, no Green Flag block

### Steps to Reproduce

Start a new fresh project in the editor

### Operating System and Browser

Firefox on Windows 8.1 32bit

**Comment by benjiwheeler** [comment]
Closing in favor of existing issue: https://github.com/LLK/scratch-gui/issues/2737
