### ISSUE TITLE
Cursor could turn into a hand when hovering account dropdown

### ISSUE THREAD

**Issue by JinXJinX** [LLK/scratch-gui#4584]
### Expected Behavior

I think cursor should keeps same format when hovering any nav dropdown
like this:
![img_0446](https://user-images.githubusercontent.com/12160296/53316784-209eb580-3897-11e9-86f4-a50a4b56107b.jpeg)

### Actual Behavior

But when you hovering account dropdown, cursor is this:
![img_0457](https://user-images.githubusercontent.com/12160296/53316917-a6226580-3897-11e9-9a6e-869cec2af48a.jpeg)

and this:
![img_0447](https://user-images.githubusercontent.com/12160296/53316920-aae71980-3897-11e9-8369-fdf8e2b6bd40.jpeg)

### Steps to Reproduce

1. Login
2. open account dropdown
3. hovering over menu item

### Operating System and Browser

MacOS Chrome

**Comment by thisandagain** [comment]
Agreed! Thanks for filing this.
