### ISSUE TITLE
Making the stage smaller in the editor makes it blurry from the player's point of view

### ISSUE THREAD

**Issue by NilsTheBest** [LLK/scratch-gui#4593]
### Expected Behavior

The stage shouldn't be blurry in player mode, whether the stage is small or normal in the editor.

### Actual Behavior

Making the stage smaller in the editor makes it blurry from the player's point of view.

### Steps to Reproduce

![blurrycat](https://user-images.githubusercontent.com/41824646/53486053-feb85500-3a87-11e9-8397-c61f3f186dc3.gif)

### Operating System and Browser

Ubuntu Linux, Firefox 65.0

**Comment by tomrow** [comment]
Duplicate of #4080

**Comment by NilsTheBest** [comment]
Alright thanks
