### ISSUE TITLE
scratch-desktop branch needs to be merged in to develop

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#4598]
We are building scratch-desktop using a non-develop branch (gui/scratch-desktop). @cwillisf mentioned needing to follow up on getting the changes there merged in. I think this should be a priority, as there are some important features there, like showing the library using local assets.

Here is [the comparison](https://github.com/LLK/scratch-gui/compare/scratch-desktop). A few highlights
- Reconciling the changes to the way Library items are shown, both in terms of resource location (storage vs. direct url) and structure (container/component for library items)
- Allowing GUI consumer to listen for project telemetry events [(related issue)](https://github.com/LLK/scratch-vm/issues/2036)
- Reconciling the asset paths in the webpack config for static assets [(related issue)](https://github.com/LLK/scratch-gui/issues/4606)

Related issues:

/cc @chrisgarrity

**Comment by chrisgarrity** [comment]
There are a lot of support tickets coming in about languages missing from the Desktop editor that have been added to the online version.

**Comment by paulkaplan** [comment]
I'm going to close this since the issues listed here have been broken up into separate issues and 2/3 have been fixed
