### ISSUE TITLE
Switching languages in the editor triggers a save now

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#4605]
### Expected Behavior

_Please describe what should happen_
Switching language in the editor should not trigger an unnecessary save

### Actual Behavior

_Describe what actually happens_
Switching language triggers a save now on some devices (perhaps iPad?)

**Comment by kchadha** [comment]
If I recall correctly, this issue was related to whether we had blocks on the workspace or not...

**Comment by amazinigmech2418** [comment]
I think this issue applies to more than just the language changes. If I try to enter a project's editor and then go to the project page without changing any code, it prompts a save now.

**Comment by chrisgarrity** [comment]
@amazinigmech2418 there are several places that trigger a save now when they shouldn't and we're tracking them separately. You can see all the project saving issues with the [project saving](https://github.com/LLK/scratch-gui/issues?q=is%3Aissue+is%3Aopen+label%3A%22project+saving%22) tag

**Comment by BryceLTaylor** [comment]
I was unable to trigger a save by switching languages on an ipad using safari or chrome, nor on my mac using chrome.  I looked at the project in aws and saw no new saves when switching languages.  It also didn't cause the "save now" text to appear in the header.
