### ISSUE TITLE
Editing custom blocks cause its "inputs" (?) to be bigger when reloading page

### ISSUE THREAD

**Issue by NilsTheBest** [LLK/scratch-gui#4610]
### Expected Behavior

This shouldn't happen.

### Actual Behavior

![customblock](https://user-images.githubusercontent.com/41824646/53666166-a773d980-3c6d-11e9-9a88-cd0255432ad2.png)

### Steps to Reproduce

1. Make a custom block
2. Edit it by adding a new input
3. Reload the page

### Operating System and Browser

Ubuntu Linux, Firefox 65.0

**Comment by thisandagain** [comment]
@BryceLTaylor Can you please repro?

**Comment by ericrosenbaum** [comment]
@thisandagain @BryceLTaylor we've seen this before- there's an issue from sometime last year, but I can't find it now. I was able to repro it, and put the steps in a comment (IIRC). I remember discussing with @kchadha.

**Comment by thisandagain** [comment]
Thanks @ericrosenbaum !

**Comment by kchadha** [comment]
The issues @ericrosenbaum mentioned are:

LLK/scratch-blocks#1691
LLK/scratch-gui#4522

I am not sure if these are exactly the same issue as this one, but they certainly seem related.
