### ISSUE TITLE
Saving while logged out fails silently and loses changes

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-gui#4614]
### Expected Behavior

If you have an active scratch project editing tab open in your browser, but become logged out by another means, making a change to the project and pressing save (while logged out) should bring up a login to save dialog, or an error message.

### Actual Behavior

Saving project message appears, and then disappears (just as it does when save is usually successful).
I have lost a couple of days work due to this bug! How frustrating!

This is what appears in the web browsers console:

PUT https://projects.scratch.mit.edu/288695792 403 (Forbidden)
projects.bundle.js:31 POST https://scratch.mit.edu/internalapi/project/thumbnail/288695792/set/ 403 (Forbidden)

But the scratch gui still appears logged in and no warning of failure is given.

### Steps to Reproduce

1) Log in to Scratch.
2) Open a project for editing (Keep this tab open)
3) Log in on another device (i.e a mobile), or open another browser tab and log out of scratch in that.
4) Return to the open tab from step 2
5) Make a change to the project and then click SAVE
6) It will appear changes have been saved, but they haven't - check the browser console

### Operating System and Browser

Chrome on windows 10 PC

**Comment by rschamp** [comment]
Related to #4346.

I think #3723 and #3764 may have been closed prematurely since we did intend to catch this situation — it's outlined in #3723 — but apparently we never did :(

**Comment by thisandagain** [comment]
I've reopened these issues and assigned to @kchadha as part of a larger "project saving" scope of work.
