### ISSUE TITLE
Shouldn't "letter () of ()" be "character () of ()"?

### ISSUE THREAD

**Issue by NilsTheBest** [LLK/scratch-gui#4619]
Wouldn't "character () of ()" be a more accurate name for that block?
Letter 3 of "567 test" is "s", whereas character 3 of "567 test" would be "7".

**Comment by towerofnix** [comment]
To people who don't have any experience with programming, "character" means, well, a character in a story. "Letter" makes the block much more accessible to new users. Through use and discussion of the block, they'll probably learn that "character" is a more accurate word to refer to an individual glyph in a string; we don't need to make that block require that knowledge to make sense.
