### ISSUE TITLE
Monitor list extends outside of stage

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#463]
### Expected Behavior

The monitors get automatically placed under each other on the left side of the stage. When they run out of space on the left side of the stage, they should start a new column, still within the stage area.

### Actual Behavior

They can extend off the bottom of the stage into the sprite pane area.

<img width="1094" alt="screen shot 2017-06-19 at 11 03 09 am" src="https://user-images.githubusercontent.com/1320456/27291879-8d818648-54df-11e7-945c-218db7c1d9ac.png">

### Steps to Reproduce

This was on https://ericrosenbaum.github.io/scratch-gui/. I added the speech & wedo 2.0 extensions, then went back and forth between them checking the reporters. This added the same monitor to the stage multiple times (e.g. speech) which is in itself a bug (the checked/ un-checked state of a reporter that appears in the block pane for multiple extensions doesn't carry over across extensions, so you can add the variable multiple times), but @fsih mentioned that the monitors are placed without any reference to whether they are in the stage or not, so this sounds like it's a problem in the main gui prototype as well.

### Operating System and Browser

_Mac OS El Capitan, Chrome 59_

**Comment by paulkaplan** [comment]
So the good news is that they no longer overflow the stage, because they now get hidden under the stage. However, the other bug with creating many repeats of of the same monitor is gone, so it is much harder to get this problem :)

**Comment by fsih** [comment]
The Scratch 2.0 behavior seems to be to line them up nicely against the left edge at first, and after that fills up follow some seemingly non-random but indiscernible pattern
![image](https://user-images.githubusercontent.com/2855464/32577863-44070c24-c4a9-11e7-9148-7f4fea847c9e.png)

**Comment by fsih** [comment]
(Current monitor positioning code is in scratch-gui/src/lib/monitor-adapter.js and simply uses the index)
