### ISSUE TITLE
Persian (arabic text) is unreadable in the current font

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#4632]
From Freshdesk:
> Thanks for your great job.
> The Scratch font in offline editor and also in online editor is unreadable,Unpleasant and unfamiliar for > Persian(Farsi) users and maybe Arabic users.
> 
> I suggest to change it with these fonts:
> Calibri , Segoe UI or tahoma

I've asked for more details, but from the suggestions I would assume they're on Windows. It's possible to add an override for the font-family based on the `lang` property, but maybe there is another Windows font that should be ahead of Arial for everyone.

We should probably look at all of the non-latin languages on Windows to check readability.

**Comment by apple502j** [comment]
Windows 7, Japanese "move 10 steps" block

![image](https://user-images.githubusercontent.com/33279053/54025005-97637900-41dc-11e9-917c-5e314e97b07c.png)

**Comment by benjiwheeler** [comment]
Is there a way we could allow the font face to be different, and maybe also differently-sized, based on language? maybe we can also decrease the padding as fonts grow, to keep the blocks from getting taller.

**Comment by chrisgarrity** [comment]
Additional feedback from the original person. I sent them a screenshot of the editor in Persian on MacOS. Their response was that it was better than what they see on Windows: "Yes,This font is better & readable."

We could set different fonts based on the `lang` attribute:
```
:lang(fa) {
  font-family: "Helvetica Neue", Helvetica, Callibri, Tahoma, Arial, sans-serif;
}
```
But we'd also have to maintain them. It would be easier if we could just have a better default for everyone. For example, a font like 'roboto' may be better than others on android, and perhaps we should consider adding it to the default list.

**Comment by benjiwheeler** [comment]
> We could set different fonts based on the lang attribute

Or, set a larger font size, maybe?

**Comment by Goudarz** [comment]
I suggest the [Vazir font](https://github.com/rastikerdar/vazir-font) for the Persian language.

**Comment by chrisgarrity** [comment]
Closing in favor of https://github.com/LLK/scratch-gui/issues/4933
