### ISSUE TITLE
Importing unsupported files result in forever "Importing..."

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#4639]
### Expected Behavior
It should reject unsupported files.

### Actual Behavior
On Edge, the file chooser ignores ".mp3, .wav" rule so anything can be chosen.

Note from @ericrosenbaum : we have also found that you can get the bug on windows chrome by changing the file type in the file type selector to "all files" and then selecting a file that is not a sound. update! there's also a way to get it to happen on mac chrome.

### Steps to Reproduce
Scratcher mii-10 reported that importing flac on Edge showed Importing... popup.
https://youtu.be/vBbvmG_ylMw

### Operating System and Browser
Edge/Windows 10

**Comment by adroitwhiz** [comment]
Reopening because this still happens with sound files
