### ISSUE TITLE
Confirmation dialog for deleting blocks is inconsistent with right-click menu.

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-gui#464]
### Expected Behavior

When you right click and choose "Delete X blocks", the confirmation dialog should say "Delete all X blocks?"

### Actual Behavior

_Well_, it instead adds one to the number, it seems:
![scratch-gui bug](https://user-images.githubusercontent.com/28599280/27383110-174c8458-56bc-11e7-97d9-574a810213cc.PNG)

### Steps to Reproduce

Have 3 or more blocks in the editor, right click, choose "Delete X blocks". This will give you "Delete all X+1 blocks?"

### Operating System and Browser

Windows 10 Chrome 58

**Comment by TheBrokenRail** [comment]
It says that because it is actually deleting that many blocks, all the text and menu inputs you can put a reporter into are separate blocks called shadow blocks and they count torwards the delete blocks number.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Kenny2github** [comment]
Oh really?
![o rly](https://user-images.githubusercontent.com/28599280/27424077-69c5f7b4-5766-11e7-9276-1a357f43ed4a.PNG)
It does seem that way, I count three stack blocks, one reporter block, then two so-called "shadow" blocks. Thing is, the number should be consistent. It should either count the shadow blocks for both dialogs (not recommended, will confuse people), or not count them.

**Comment by rschamp** [comment]
Moved to LLK/scratch-blocks#978
