### ISSUE TITLE
Some projects only load in editor mode but give Asset ID of Null error in player mode

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#4649]
### Expected Behavior

All projects should load on the project page and in the editor.

### Actual Behavior

Some projects don't load, showing the blue "Oops something went wrong" message.  If you check the console, they have an error that says "TypeError: Cannot read property 'assetId' of null"

![Screen Shot 2019-03-13 at 4 40 48 PM](https://user-images.githubusercontent.com/1088291/54313252-4920f200-45af-11e9-9573-9c79152e938c.png)

Here are some example:
https://scratch.mit.edu/projects/245878906/
https://scratch.mit.edu/projects/292083579/
https://scratch.mit.edu/projects/281999647
https://scratch.mit.edu/projects/291931151/

For 245878906 I downloaded the json from s3 and tried uploading it, but it wouldn't load saying "The project file that was selected failed to load"

![Screen Shot 2019-03-13 at 4 49 57 PM](https://user-images.githubusercontent.com/1088291/54313617-1aefe200-45b0-11e9-9b6e-7359f5458e27.png)

The json named as an .sb3 and then zipped:
[245878906.sb3.zip](https://github.com/LLK/scratch-gui/files/2963622/245878906.sb3.zip)

### Steps to Reproduce

Open one of the projects above
Note: The project doesn't load

### Operating System and Browser

Mac Chrome

**Comment by BryceLTaylor** [comment]
More projects:
https://scratch.mit.edu/projects/292874938/

**Comment by BryceLTaylor** [comment]
It seams that for at least https://scratch.mit.edu/projects/292874938/editor/ if you go straight to the editor (not to the project page and then see inside) you can see the project.  When you open the javascript console you see two errors:

`Failed to load the resource: the server responded with a status of 404 ()`
![Screen Shot 2019-03-26 at 11 51 26 AM](https://user-images.githubusercontent.com/1088291/55012250-8167fd80-4fbd-11e9-9ff3-dd2663342fce.png)

They both have to do with the sound file e4d85d5100e1eff4dcd1d152d217f0d2.wav which in the project is called "Song 1 20130127" on the stage.  I downloaded the project, unzipped it, and found that the file had downloaded.  

The file is 5.6MB and 2:06 long

**Comment by BryceLTaylor** [comment]
There is an interesting report from the community that the projects can be loaded from "my stuff": https://scratch.mit.edu/discuss/topic/345883/

**Comment by BryceLTaylor** [comment]
I just did some research and found that in the first project, the sound "Fortnite OST - Season 6 (Squeaky Clean).mp3" and "Floss Music" which are the same sound with the same md5 hash, is not in the asset server.  It is only in the backpack server.  When you load it in the editor, it loads the backpack and the project loads.

If you load it from develop or from the project page, it doesn't load the backpack and it doesn't load.

**Comment by BryceLTaylor** [comment]
I could reproduce the issue:

create a new project 
Open the costume Editor
upload a new costume (I used a screenshot I had just taken)
Immediately add the costume to the backpack
then immediately closed the tab without saving.  
Note:The without saving part is important.
Create a new project
Open the costumes tab
Open the backpack
Drag the image to the costumes area
Save the project
Click "See Project Page"
reload the page
Note: you get a blue screen

**Comment by thisandagain** [comment]
@paulkaplan Let's jump on this now that we have tracked this down and have a clear repro. I think I'd be happy to consider this as a hotfix depending on how invasive the fix is. Please let me know if you'd like to discuss.

**Comment by BryceLTaylor** [comment]
The first half of the fix for this issue has gone in with https://github.com/LLK/scratch-gui/pull/4733.  That should prevent further assets appearing in the backpack server without being in the asset server.  There is still work to do to make sure that all of the assets that are in the backpack server are on the assets server.

**Comment by BryceLTaylor** [comment]
This issue has been resolved by moving the assets from the backpack server to the assets server.
