### ISSUE TITLE
GUI tries to save project to server when outside the context of www

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#4656]
### Expected Behavior

GUI should not attempt to save a project with an ID to the project server unless it is embedded in WWW.

### Actual Behavior

Standalone GUI running locally (or on llk.github.io/scratch-gui/develop) attempts to save a project loaded by ID to the project server when attempting to load another project from local disk.

### Steps to Reproduce

1. Open gui
2. Load a project by ID using `#projectId1` in the URL
3. With the project loaded by ID, attempt to load another project from your computer (File -> Load from your computer)
4. If you are doing this locally, observe the project saving alert that comes up (see screenshot below). If you are doing this on llk.github.io/scratch-gui/develop, open up your console and observe the failed PUT request.

![image](https://user-images.githubusercontent.com/1786240/54441429-227bcc00-4713-11e9-8d3d-e0a7c9127d14.png)

**Comment by benjiwheeler** [comment]
I tried to repro this several ways, and could not. I think it's fixed!

@kchadha or @BryceLTaylor, could you please confirm this?

**Comment by kchadha** [comment]
@benjiwheeler, yep, it seems to be resolved!
