### ISSUE TITLE
Update Tutorial Window Fencing

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#4667]
## Current
The tutorial window is "fenced" in such a way that no part of the tutorial window can be outside the browser. 

![current fencing](https://user-images.githubusercontent.com/3409578/54633374-6f82d980-4a56-11e9-912d-83e7dfb9025a.gif)

## Update
We'd like to allow the tutorial window to be able to go beyond the edge of the browser. We want to make it so it's easier to move the window out of the way and make space for interacting with other parts of the editor. 

- The tutorial window should be able to extend beyond the browser's left/right edge by 80% the windows width. 
- The tutorial window should be able to extend beyond the browser's bottom(/top) edge by 80% the windows height. My instinct tells me allowing the window to exit the top of the browser might feel weird — more in the questions below.  

We can revalue how that feels once prototyped.

### Fencing Left Example
![V2 - Getting Started - Fencing Left](https://user-images.githubusercontent.com/3409578/54633552-c5578180-4a56-11e9-8934-01eee52fd13a.png)

### Fencing Bottom Example
![V2 - Getting Started - Fencing Bottom](https://user-images.githubusercontent.com/3409578/54633568-ce485300-4a56-11e9-9f34-76c663661b95.png)

### Questions
- Do we need a way to reset the window to the default position?
- Should the window stay the last place it was put when opening a new tutorial?
- Should we allow the window to exit the top of the browser? This would break conventions with similar drag-and-drop window UI. Might be worth prototyping with and without.

**Comment by evhan55** [comment]
@carljbowman @ericrosenbaum 

Here is an update on the fencing behavior.  I think it's almost ready for you both to test and verify and help tweak some values:

![drag cards 2](https://user-images.githubusercontent.com/699840/57198404-48b62f00-6f40-11e9-88e6-339e2dd972fe.gif)
