### ISSUE TITLE
Update Video Size in Tutorial Window

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#4668]
## Current
Currently any step that contains a video is much larger than all other tutorial steps. Most tutorials start with a video so the tutorials start by taking up a lot of editor room.

**Tutorial Video** 
<img width="1280" alt="current tutorial video step" src="https://user-images.githubusercontent.com/3409578/54634035-ba512100-4a57-11e9-8d4b-474f6d578ad0.png">

**Tutorial Step** 
<img width="1280" alt="current tutorial step" src="https://user-images.githubusercontent.com/3409578/54634041-bde4a800-4a57-11e9-9a3e-8eaa2de9503b.png">

## Update
In efforts to reduce the frequency of people closing the tutorial window immediately or during the video, we'd like to reduce the dimensions of all video steps to be the same size all other steps. This will also help with the jarring transition between a video step and all other steps.

**Maintain the current tutorial step width** 
The height of tutorial steps vary based on the content. To maintain the video aspect ratio, we should not force a height, but we should force the width to be the same size as all other tutorial steps.

**Comment by DeleteThisAcount** [comment]
How about a minimize button?
