### ISSUE TITLE
Sounds are called sprites in deletion confirmation

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-gui#467]
### Expected Behavior

When you click the X to delete a sound, it should say "Are you sure you want to delete this sound?"

### Actual Behavior

Instead, it says "Are you sure you want to delete this _sprite_?":
![sound vs sprite](https://user-images.githubusercontent.com/28599280/27425035-aa968df0-5769-11e7-9103-5a1755a132ce.PNG)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by liam4** [comment]
I believe this is a duplicate of #385.

**Comment by rschamp** [comment]
Yes it is, thanks @liam4
