### ISSUE TITLE
Sprites aren't visible on the stage on android tablet

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#4672]
### Expected Behavior

_Please describe what should happen_
Sprites and backdrops should be visible on the stage.
### Actual Behavior

_Describe what actually happens_
Some sprites with saturated colors are barely visible:
![Screenshot_2019-03-20-08-22-48](https://user-images.githubusercontent.com/399209/54684311-4032a200-4b14-11e9-8be0-fbef79d98b58.png)

There are three sprites, but you can't see the cat at all, and the others are just faint outlines. Also note that the boardwalk backdrop is not visible.

The sprite becomes visible when dragged:
![invisible](https://user-images.githubusercontent.com/399209/54684485-c0590780-4b14-11e9-96fa-a83a6bdfcf69.gif)

### Steps to Reproduce

It may be something missing from WebGL, so I'm including the device details below.

### Operating System and Browser
Samsung Galaxy Tab A (2016)
Model: SM-T280
Android: 5.1.1
Kernel version: 3.10.65-12484970
  dpi@21HHAD05 '#2
  Wed Nov 21 19:13:56 2018

**Comment by BonfireScratch** [comment]
@chrisgarrity I've run some tests on a G-Pad and they've been pretty worrying...

**Comment by chrisgarrity** [comment]
I've only seen this on my old samsung tablet, so I'm closing it. We can re-open if we hear more reports after release. /cc @BryceLTaylor so you're aware of the issue if we start getting reports of it later.
