### ISSUE TITLE
You can't reply to a comment in the "single comment view"

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#4679]
### Expected Behavior
After you click the send button, the comment will be sent properly
### Actual Behavior
After you click the send button, the single comment view disappears and the comment didn't send
### Steps to Reproduce
Open message and click a comment replied to you, reply to the comment in the single comment view
### Operating System and Browser
Win 8, Chrome 71

**Comment by amazinigmech2418** [comment]
I think this should be moved to scratch-www. This isn't an issue with the editor, but is an issue with the website.

**Comment by cyx2015s** [comment]
oh.
