### ISSUE TITLE
English language error on new list menu

### ISSUE THREAD

**Issue by JuegOStrower** [LLK/scratch-gui#4683]
### Expected Behavior

In the new list menu, it should say "The list will be on all the sprites".

### Actual Behavior

When I make a new list from the stage it says "the variable will be on all the sprites" instead of "this list". This is a translation error, I think. This can confuse New Scratchers.

### Steps to Reproduce

Go to the editor
Go to the stage
Go to the "Variables" blocks (in left)
Click New List

### Operating System and Browser

Windows 10, Google Chrome 72

**Comment by apple502j** [comment]
Duplicate of #4474
