### ISSUE TITLE
Add messages indicator to the nav bar

### ISSUE THREAD

**Issue by maxiostro** [LLK/scratch-gui#4684]
### Expected Behavior

Messages number should be on the editor nav bar, as it is on the rest of the pages. This feature was not included on Scratch 2.0, but a lot of people has always been looking for alternatives to this (like the @GrannyCookies messages number extension, https://chrome.google.com/webstore/detail/scratch-editor-messages/keimlfjkekbehbegbnojedobedfenbbf,  and many other userscripts).
However, adding the button may have downsides: like distracting the scratchers when they are doing its projects. That's why I think that the button could be optional. I think that it has to be there so the right part of the nav bar is the same on all the pages.

### Actual Behavior

The message number is not in the editor.

### Steps to Reproduce

Go to the editor and see the nav bar.

### Operating System and Browser

Windows 10, Google Chrome 73

**Comment by towerofnix** [comment]
This is already filed in #3758 - you should copy your discussion points there!

**Comment by BonfireScratch** [comment]
@JuegOStrower just close this...
