### ISSUE TITLE
Some bugs and things about the sprites area

### ISSUE THREAD

**Issue by maxiostro** [LLK/scratch-gui#4691]
### Expected Behavior
The script area should be bigger. This should be like it was on Scratch 2.0. There, without the editing options inside the sprite area, there was space for more sprites. It could be a good solution just hide the sprite options.
- With the small player, there were space for 8 sprites (4 rows, 2 columns) on Scratch 2.0.
- With the big player, there were space for 10 sprites (2 rows, 5 columns) on Scratch 2.0.

### Actual Behavior

The sprite area is very little compared to Scratch 2.0, and it fits less sprites. Also, it has some bugs with the scrolling bar.
- With the big player, there is space for 5 sprites (1 row, 5 columns).
- With the small player, there is space for 3 sprites (3 rows, 1 column), although there is space for a second one, but it's empty. I noticed that there are only 2 columns when there are 6 or more sprites. That's because of the scrolling bar, that moves the sprites down.

I think all this is related to the sprite editing options, which are inside area (different that Scratch 2.0, and it uses a lot of space). Also, this is related to my screen resolution and ratio (1366x768 and 16:9), but that is one of the most common screen specifications. So I think the editor should be adapted to that resolution.

Also, the New Sprite button is over the 5th sprite. That means that that sprite preview is not completed showed, and it makes the sprite area look ugly in my opinion.

#### Images
Some images that display all this. Sorry for the Spanish on the screenshots. The haven't been cropped a lot. I just removed the rest of the editor and and the Windows bar. I think that the images helps a lot to understand this.
![Big editor on Scratch 3.0](https://user-images.githubusercontent.com/12816832/55041386-8eabd900-500b-11e9-8d84-3ecac75e63ae.png)
Big editor on Scratch 3.0

![Small editor on Scratch 3.0 - more than 6 sprites (10 exactly)](https://user-images.githubusercontent.com/12816832/55041389-91a6c980-500b-11e9-8c23-644862c76fc7.png)
Small editor on Scratch 3.0 - more than 6 sprites (10 exactly)

![Big editor on Scratch 2.0](https://user-images.githubusercontent.com/12816832/55041393-94092380-500b-11e9-8101-3887a4f28632.png)
Big editor on Scratch 2.0

![Small editor on Scratch 2.0](https://user-images.githubusercontent.com/12816832/55041398-98354100-500b-11e9-93b6-6015eddd1657.png)
Small editor on Scratch 2.0

![Small editor on Scratch 3.0 - just 6 sprites](https://user-images.githubusercontent.com/12816832/55041401-99ff0480-500b-11e9-8a65-a0dd5099bd07.png)
Small editor on Scratch 2.0

### Steps to Reproduce

Go to the editor.
Look at the sprite area.
Make new sprites.
Change the player size.
Delete sprites.
Try what I say before.

### Operating System and Browser

Windows 10, Google Chrome 73

**Comment by benjiwheeler** [comment]
Thanks for this feedback, sorry it took so long to respond! We will take your ideas into consideration. It's helpful to hear about the frustrations you've been having with the design.
