### ISSUE TITLE
Some chromebooks flip the backdrops and text upside down on the stage

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#4696]
### Expected Behavior

Backdrops and text should appear in the same orientation in the paint editor as they do on the stage.

### Actual Behavior

On some chromebooks, the text and the backdrop will be upside down on the stage.  

![image (1)](https://user-images.githubusercontent.com/1088291/55252490-75807380-5229-11e9-8bf8-61de6d70495b.png)

### Steps to Reproduce

I've been unable to reproduce this myself, but I'd like to start documenting my investigations here.  This issue came in from help desk tickets from two different people.   I'm still in the process of collecting more information from them.

First Report:

I use Scratch a lot for coding with my class. We use a range of different Chromebooks as their device. For some of them, the sprites, backgrounds and text appears upside down since the new update, making it really hard for them to code properly. It's happening on different models of Chromebooks randomly (working on some of the same type but not all). Is there anything we can do to the ones that aren't working properly? 

Second report:

"When I open my Scratch project, as well as any project in Scratch, the stage and text are inverted. When I design my stage or a background, the image and any words are turned upside down and backwards. Also, if the sprite is enlarged, it inverts as well. "

"I have opened my and other projects in Scratch on other computers and this does not happen on those tools. I'm assuming the issue might be with my computer but was wondering if you have encountered this issue before and have a solution I could try."

### Operating System and Browser

Chrome on Chromebook

**Comment by BryceLTaylor** [comment]
Another user on the forums has seen this issue as well and sent in a screen shot:
![Screenshot 2019-03-29 at 11 17 43 AM](https://user-images.githubusercontent.com/1088291/55331919-4dc82000-5462-11e9-943e-cbdc55dc8042.png)

**Comment by BryceLTaylor** [comment]
I received more information from the first report about their hardware and extensions:

Acer C731 (only one doesn't work, the rest are working)
Lenovo N23 (all 3 aren't working in the classroom)

Extensions: Google calendar, Google dictionary, Google translate, Hapara highlights, Read&write, securly, and video recorder for wevideo. All the students have the same extensions and most of them work but some of them don't. They are controlled by our ICT admin

**Comment by BryceLTaylor** [comment]
Another update from that user is that they are seeing the same issue in another application:  

"I've just learned that another website background/numbers that we use is also upside down for those Chromebooks (https://www.sumdog.com/)... "

**Comment by jodystange** [comment]
I have the same issue, just noticed today (Apr 2, 2019). Text is flipped upside down and backwards on applications within BOTH Chrome Tabs (like BeFunky, Fotor, etc) as well as standalone Chrome Apps (Polarr, etc.). Tried the following fixes: restore setting to original defaults, clearing all cache, cookies and site settings, close-re-open browser, and rebooting. Issue persists.
![Screenshot 2019-04-02 at 11 50 40 AM](https://user-images.githubusercontent.com/49208908/55428317-b33d0f00-553d-11e9-870c-1aec1149b46a.png)

**Comment by wadefelix** [comment]
![scratch-upsidedown](https://user-images.githubusercontent.com/1306724/78244893-0e229100-7519-11ea-92bc-71905218864f.png)
版本 78.0.3904.108（正式版本）Built on Raspbian , running on Raspbian 10 （32 位）

**Comment by apple502j** [comment]
@BryceLTaylor The issue happens on Raspbian:
My browser / operating system: raspbian buster, Chromium 78.0.3904.108, No Flash version detected
https://scratch.mit.edu/discuss/post/3980935/

**Comment by Taitaitatata** [comment]
Scratch 3.0 backgrounds now draw correctly on Chromiuim running on Raspberry Pi OS
![2020-11-07-103426_1364x725_scrot](https://user-images.githubusercontent.com/70869837/98428560-6d670600-20e5-11eb-980a-805f2f632bfe.png)
