### ISSUE TITLE
If on edge bounce broken

### ISSUE THREAD

**Issue by chicken3600** [LLK/scratch-gui#47]
This block is intended to make the sprite turn in the opposite direction when it hits an edge.

What actually happens is that the sprite just keeps moving into the edge of the screen.

To view the error, just make a script saying: 'When green flag clicked, forever, move 10 steps. If on edge bounce.'

This error was viewed in Firefox on Mac OS X 10.6

**Comment by CosmicWebServices** [comment]
This should go in scratch-vm.

**Comment by chicken3600** [comment]
I'm not really sure what the difference between this and scratch-vm is

**Comment by CosmicWebServices** [comment]
This is the GUI of the editor.
Scratch- Render is the rendering of the scratch viewer
Scratch-vm puts the rendering and the scratch-blocks together

Now that I think of it this should go in Scratch-Render

**Comment by thisandagain** [comment]
Moved to LLK/scratch-vm#399
