### ISSUE TITLE
Variable Monitor Cannot Be Moved

### ISSUE THREAD

**Issue by BGMead** [LLK/scratch-gui#472]
### Expected Behavior

_When you move a variable around, then hide it, then show it again, it should stay in the same place._

### Actual Behavior

_Instead, it goes somewhere completely random._

### Steps to Reproduce

_??? Not an advanced web developer, sorry._

### Operating System and Browser

_My browser / operating system: Windows 8, Chrome 58.0.3029.110, Flash 26.0 (release 0)_

**Comment by paulkaplan** [comment]
Hi there! Thanks for the bug report. For the "Steps to Reproduce" could you just go through, step-by-step, the actions you took. For example you might say

1. Create a new variable
2. <what do you mean by "hide it"? There is no block for hiding variables yet>
3. ...

**Comment by BGMead** [comment]
1. Create a new variable
2. Move it around
3. Hide the variable by toggling the checkmark box next to the variable name
4. Show it by clicking the checkmark box again
5. Boom. It moved.

**Comment by paulkaplan** [comment]
Aha! Thanks for explaining.
