### ISSUE TITLE
In some browsers fullscreen mode is significantly slower then non-fullscreen mode

### ISSUE THREAD

**Issue by wmacfarl** [LLK/scratch-gui#4739]
### Expected Behavior

Fullscreen mode should be just as performant as non-fullscreen mode.

### Actual Behavior

Fullscreen mode is significantly slower and has a significantly reduced framerate for even very simple projects involving motion.

### Steps to Reproduce

The following project shows the behavior.
https://scratch.mit.edu/projects/302780201/

Open the project.  Run it in editor or from the project page and it runs smoothly.  

Switch to fullscreen/presentation mode from either one and it begins to drop most of its frames.

### Operating System and Browser

The slowdown occurs when using:
Google Chrome 73.0.3683.103 (Official Build, 64bit) on Mac OSX El Capitan 10.11.6 and OSX High Sierra 10.13.6

It does not occur when using Chrome 68.0.3440.84 in the same operating systems (Mac OSX El Capitan 10.11.6 and OSX High Sierra 10.13.6)

It also does not seem to occur in Firefox or on Chrome in Windows

**Comment by paulkaplan** [comment]
@BryceLTaylor Can't repro on Mac/Chrome 79

**Comment by rschamp** [comment]
For August — try to repro

**Comment by BryceLTaylor** [comment]
I can not reproduce this on macOS10.13.6 using Chrome version 76.0.3809.100 or on Chrome version 85.  It's possible it's related to the specific hardware of those devices.  Alternatively it could have been a few versions of Chrome.  

I'm going to close and if it shows up again we can reopen.
