### ISSUE TITLE
Selecting in the costume tab should set sprite's costume

### ISSUE THREAD

**Issue by liam4** [LLK/scratch-gui#474]
### Expected Behavior

Selecting a costume in the costume tab should set the active sprite's costume to be the one selected (e.g. clicking on `costume1` should set the sprite's costume to `costume1`).

### Actual Behavior

Clicking on a costume in the costume tab does not do anything (besides mark it as the selected costume in the tab state).

### Steps to Reproduce

1. Make sure the active sprite has at least two costumes; the default scratch cat sprite does.
2. Click on the "Costumes" tab (between "Scripts" and "Sounds").
3. Select the costume that isn't currently active.

### Operating System and Browser

macOS 10.12.4, Chrome 59.0.3071.115

---

[(I've written the one-line code fixing this.)](https://github.com/liam4/scratch-gui/commit/cf34ff15af77b8fb3be2c2b586e68c8f1bed4446)

**Comment by rschamp** [comment]
Thanks @liam4! Please feel free to submit that fix as a PR.
