### ISSUE TITLE
Set language block ignores things dropped into it

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#4758]
### Expected Behavior

The droppable field in the Set Language block in the Text to Speech extension should use inputs from blocks dropped into the field.

### Actual Behavior

If you "drop" a block that reports a language into the Set Language block it ignores it and uses whatever you set the dropdown to before the reporter was put in.

Examples of reporter blocks are the "Language" block from the translate extension or a variable.  If you set the variable to French and put

### Steps to Reproduce

Create a project
Add the text to speech extension
Add the translate extension
Drag out the "Set Language" block
Attach the "Say ___ " block
Drop the "translate ___ to [language]" block in the Say block
Set the "Set Language" block (text to speech) to english
Type a phrase in a language that you know into the "say" block
Set the language in the "translate" block to the language you know
![Screen Shot 2019-04-19 at 9 57 38 AM](https://user-images.githubusercontent.com/1088291/56427380-9ddc1a80-6289-11e9-9cf8-0209efceaea1.png)
Click the stack
Note: The voice says the phrase in an outrageous American accent

Set the language in the say block to English
Create a variable called "lang"
To the top of the stack add the block "set lang to [that language you know]"
Drop the reporter for the variable "lang" into the "say" block
![Screen Shot 2019-04-19 at 9 58 49 AM](https://user-images.githubusercontent.com/1088291/56427436-dc71d500-6289-11e9-8c5d-5159646438ce.png)
Click the stack
Note: It says the same phrase in the language you put with the same outrageous accent

Drag out another reporter for "lang" and put it in the "set language" block
![Screen Shot 2019-04-19 at 10 01 02 AM](https://user-images.githubusercontent.com/1088291/56427494-14791800-628a-11e9-8491-776bc01368da.png)
Click the stack
Note: it still has the outrageous American accent

Remove the reporter from the "set language" block
Change the dropdown to the language that you have been using
![Screen Shot 2019-04-19 at 10 02 21 AM](https://user-images.githubusercontent.com/1088291/56427534-3ecad580-628a-11e9-9d6d-dd2c34c2e551.png)

Click the stack
Note: it says it in a correct accent

You can also use the translate "language" block and change the language for your editor to see this.

### Operating System and Browser

Mac Chrome

**Comment by ericrosenbaum** [comment]
(to be spoken in outrageous accent): thank you we are aware of the issue!

tracking in https://github.com/LLK/scratch-vm/issues/1673
