### ISSUE TITLE
Clicking "shrink" on tutorial window should pause the video

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#4766]
If you play a video in a tutorial window, then click the "shrink" button, it should pause the video.

**Comment by evhan55** [comment]
I looked into this a bit, and I am not sure if we can access the Wistia API via an iframe.

The Wistia API says you can access the video to interact with it dynamically:
https://wistia.com/support/developers/player-api

The way to do it would be via the `window._wq` object.  I tried to access that object on the Scratch GUI `window` and it does not exist.  Then I tried to access it via the `iframe`'s own `contentWindow`, and I get the follow error:

```
Uncaught DOMException: Blocked a frame with origin "http://localhost:8601" from accessing a cross-origin frame.
```

**Comment by evhan55** [comment]
I will look into whether using `window.postMessage` on the iframe could work, but it seems risky to me, although I don't have a solid understanding of the risks involved.

**Comment by evhan55** [comment]
@paulkaplan @cwillisf 

I am trying to use a JS API from wistia in a `iframe` loaded by scratch-gui.  It seems like using `window.postMessage` is one of the only ways to make calls to that API because otherwise the calls are blocked for security reasons.

Do we do anything like this elsewhere in scratch-gui or is it too unsafe?

**Comment by paulkaplan** [comment]
@evhan55 I think doing a postMessage into an iframe that we are creating is fine. As long as we aren't letting other people `postMessage` into _our_ application, it seems ok.

**Comment by evhan55** [comment]
@paulkaplan Ok thanks! I will give it a try.
