### ISSUE TITLE
Sound editor redesign proposal/mockup

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-gui#4768]
I'm not sure whether a relatively major redesign like this is acceptable after 3.0's release, but many Scratchers have been complaining about the lack of major sound editing features present in 2.0. As such, I've created a mockup of a potential redesigned sound editor:

![scratch sound editor mockup](https://user-images.githubusercontent.com/25993062/56536542-4f9a7600-652c-11e9-808e-7574c53eb792.png)

I've laid the buttons out in an arrangement somewhat similar to the costume editor: the first row is actions which come in pairs, and the second row holds copy/paste/delete ("trim" here) and more action buttons (though here, they aren't contextual, because there's no tool state/context).

Zooming is done via zoom buttons, the same way as in the costume editor. You can now easily scroll through the audio as well. As with 2.0, selection is accomplished simply by clicking and dragging.

In addition to the standard waveform, there's now an RMS waveform (which, I admit, may not be strictly necessary) and time marks.

Useful effects from 2.0 (silence, fade in, fade out) have been re-added.

There are some things I'm not quite sure about:
* Should stereo audio be supported? If so, should it be handled invisibly or show as two stacked waveforms, the way other audio software does it?
* How do the controls work on a touchscreen if selection is done via swiping? Perhaps there, the scrollbar could be made larger, and it could have two handles on its left and right sides which allow you to drag the two "ends" of the scrollbar separately to zoom in and out.
* Should the action to delete selected audio be called "trim" or "delete"? I think "trim" is more clear, but it may be confusing to those used to the current Trim dialog.
* Should there be a volume or gain slider instead of louder/softer buttons that allows you to smoothly adjust the gain of the selected audio (with visual feedback in the waveform)?
* Grouping all the buttons at the top is good for mouse users (less moving your mouse!) but potentially bad for touchscreen users (you've gotta be precise!) Is the padding between controls sufficient, or should certain buttons (play/stop and zoom in particular) be moved below the waveform?

I'd love to hear some thoughts on this design.

**Comment by DeleteThisAcount** [comment]
very epic and will basically fix everything wrong currently.

will you be able to delete sections from the audio editor (is that through trim?)

and would there be still the old trim button?

**Comment by adroitwhiz** [comment]
> will you be able to delete sections from the audio editor (is that through trim?)
> 
> and would there be still the old trim button?

Perhaps there could be two buttons: "delete" would delete the selected audio, and "trim" would delete everything *but* the selected audio. I can see how that could get confusing, though, so it might be best to pick one.
Given a choice between the two, I'd prefer "delete", since "delete" can do everything "trim" can, but "trim" can't do everything "delete" can.

**Comment by paulkaplan** [comment]
A lot of these suggestions were integrated into the most recent sound editor update, check it out!
