### ISSUE TITLE
Implement translation for Scratch-gui

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#477]
- [x] Include react-intl in scratch-gui and provide example of translating strings
- [ ] implement locale switching based on browser locale
- [x] implement locale switching in the ui
- [x] auto generate l10n source data from jsx source with babel plugin
- [x] process to update transifex from source l10n
- [x] process to pull translations from transifex - could be npm translations module?
- [x] build process including tx translations

**Comment by paulkaplan** [comment]
@chrisgarrity is this issue referring to the strings in the GUI like "Record a sound", "Add costume", etc?

**Comment by chrisgarrity** [comment]
@paulkaplan Yes, all the things that aren't the blocks.

**Comment by paulkaplan** [comment]
@chrisgarrity can we split this issue into the units of work so that they can be prioritized and closed by individual PRs.

**Comment by zyctinker** [comment]
hi I'm interested in this plan. I want to know when will you implement locale switching in the ui so that my students can use scratch 3.0 .   If you provided the API, I can take the task of Chinese translation. Thank you.

**Comment by chrisgarrity** [comment]
@zyctinker this is just the start of the process of localizing 3.0 and doesn't include translation of the blocks themselves yet. When we're ready to have Scratch 3.0 translated, there will be a new project on our translation platform: https://www.transifex.com/llk/public/

**Comment by chrisgarrity** [comment]
Tracking in 
- #507
- #509 
- #510 
- #511 
- #517 
- #518 
- #524
