### ISSUE TITLE
Prevent CJK character in number input

### ISSUE THREAD

**Issue by ajaxsys** [LLK/scratch-gui#4779]
![image](https://user-images.githubusercontent.com/627262/56844761-90113f80-68f0-11e9-9d75-2cb5a66012db.png)

Should prevent inputting some CJK character,
as some children may input １２３(fullwidth number, which not work) instead of 123(halfwidth number).

Maybe it's better to transeform １２３(fullwidth number, which not work) to 123(halfwidth number) automatically.

**Comment by Kenny2github** [comment]
Well spotted! Yes, I agree that arbitrary CJK characters should not be allowed but fullwidth numbers should be converted to normal numbers.

**Comment by apple502j** [comment]
Sorry, we call it Duplicate of LLK/scratch-blocks#1857 .

**Comment by Kenny2github** [comment]
Oops, you're right.
Duplicate of LLK/scratch-blocks#1857

**Comment by ajaxsys** [comment]
thanks, close it!
