### ISSUE TITLE
"Add a backdrop" button should not select Stage

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-gui#4797]
Clicking Add a backdrop button from a sprite switches to select Stage which confuses beginners. 

Add a backdrop should not switch. 

Open Scratch. Click "Add a backdrop" button. Choose a backdrop. the Stage will become selected (and thus move blocks will disappear).

I thought this had been changed before launch - I wonder if it changed back or if there was a misunderstanding about what this issue meant:
 https://github.com/LLK/scratch-gui/issues/3500

**Comment by ntlrsk** [comment]
This breaks the first Scratch card in the Scratch Cards set - and several others.

**Comment by paulkaplan** [comment]
@ntlrsk Oh no! It looks like there was a miscommunication, the linked issue only changed the behavior to not change from the code tab to the costume editor after adding a backdrop, but did not change the behavior of selecting the stage after adding a backdrop. 
> Thus, as we discussed, the recommendation is to have clicking the Add a backdrop button stay on the current tab and not switch

It should be a minor change to make adding a backdrop not select the Stage.

/cc @carljbowman, and we can chat about this offline, but one question: there are 3 other buttons in that menu (surprise, file upload and blank) that all select the stage and open the backdrops tab. Should those stay that way?

**Comment by carljbowman** [comment]
**Design Meeting Recap** 
Following up with some notes from the design meeting with the resources team.

Many of us have seen confusion when someone adds a Backdrop and then the Stage becomes selected. Sometimes we hear this vocalized as "Where did my scripts go?" We also recognize that the Stage is rather different than Sprites which can add to the confusion, especially for new Scratchers. One major difference is being able to add "Backdrops" (more similar to Costumes) at the "surface" of the editor, where as with Sprites you can only add Costumes in the Paint Editor.

There is also some hierarchical UI questions regarding the selected state of the Stage being clear. We would like to explore the selected state further, but for the near term we'd like to focus on the behavior.

**Desired Behavior** 
We'd like to update the selecting behavior when adding a Backdrop the Stage selector (not in the Paint Editor). As @paulkaplan mentioned there may be different behaviors based on how a backdrop is added: surprise, via file, etc. 

- Add Backdrop via Library: Stage should not become selected and the workspace tab (Code, Costume/Backdrop, Sound) should not change
- Add Backdrop via Surprise: Stage should not become selected and the workspace tab (Code, Costume/Backdrop, Sound) should not change
- Add Backdrop via Paint: Stage should become selected and the workspace should be switched to the "Backdrops" tab with the newly added Backdrop in the Paint Editor
- Add Backdrop via File: Stage should become selected and the workspace should be switched to the "Backdrops" tab with the newly added Backdrop in the Paint Editor

/cc @ntlrsk @paulkaplan @kosiecki @SpeakkVisually
