### ISSUE TITLE
Scract GUI page is not displaying

### ISSUE THREAD

**Issue by vinayakumarr** [LLK/scratch-gui#4807]
When the following command is installed after installing the scratch-gui

npm start

It shows in the command, compiled successfully.

｢wds｣: Project is running at http://0.0.0.0:8601/

When I try to access it in browser using http://0.0.0.0:8601/, it is not showing the GUI.

**Comment by apple502j** [comment]
Any error on browser console?

**Comment by cryanis** [comment]
try http://localhost:8601

**Comment by benjiwheeler** [comment]
@vinayakumarr, can you post the full commandline log you see?

**Comment by vinayakumarr** [comment]
It worked, there were some errors due to mismatch in packages.
