### ISSUE TITLE
There is music that can not be played in Safari

### ISSUE THREAD

**Issue by QylinFly** [LLK/scratch-gui#481]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by rschamp** [comment]
@QylinFly, would you mind providing Expected Behavior, Actual Behavior, and Steps to Reproduce?

**Comment by thisandagain** [comment]
Tracking in #388
