### ISSUE TITLE
Is there a way to preload a Scratch project when hosting your own Scratch server?

### ISSUE THREAD

**Issue by naddison36** [LLK/scratch-gui#4813]
I've been working on a Scratch extension for integration to the Ethereum blockchain
https://github.com/naddison36/eth-scratch3

I've got a Docker file that bundles up the scratch-gui, scratch-vm and my customs extensions. I can then deploy the image to a cloud provider.

What would be nice if I could also bundle in a project file that is preloaded rather than having the user manually load the Scratch project.

**Comment by towerofnix** [comment]
You'll want to look into modifying the [src/lib/default-project](https://github.com/LLK/scratch-gui/tree/develop/src/lib/default-project) directory. The project.json code belongs in `project-data.js`; you'll have to define assets (costumes and sounds) in `index.js`.

There's no builtin way to automatically load a project from an externally hosted file - that'd take a considerably greater amount of effort to implement.

**Comment by naddison36** [comment]
thanks
