### ISSUE TITLE
Negative numbers are challenging

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#483]
We sometimes notice (like in our recent Catch Game external play test) that kids have difficulty understanding and using negative numbers in Scratch, especially younger kids. Here are some things we've seen:

- Not knowing they can type the "minus sign" using the - key
- Not making the mental leap from moving a sprite forward using positive numbers to moving it backward with negative numbers (or other examples like making a sprite smaller by changing by a negative number)
- Not correctly reading negative numbers in blocks shown on cards and in the tips window, and copying them over into blocks as positive numbers
  
**Ideas**

Let's consider adding custom input widgets specialized for each field wherever possible. For numeric inputs that allow negative values, you could just drag the slider to the left to go below zero.

**Comment by chrisgarrity** [comment]
Also see #508. Putting space between the `-` and `170` turns the value into a string instead of a number.

**Comment by jwzimmer** [comment]
I also noticed the following trouble during the Catch Game External Playtest (June 2017):
- (At least) one of the users reversed the negative numbers from the cards. They put a negative number where they wanted a positive and vice versa, and had difficulty understanding the behaviour and how to fix it.
- (At least) one of the users asked what the negative numbers were.

**Comment by fsih** [comment]
According to the common core standards, negative numbers aren't introduced in school until 6th grade
http://www.helpingwithmath.com/by_grade/gr6_cc_skills.htm

**Comment by heyitsmeuralex** [comment]
^ is US-only, for example here in the UK negative numbers are learnt very early on

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#26
