### ISSUE TITLE
add icon to indicate that hardware extensions require Internet access

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-gui#4839]
Migrated from LLK/scratch-desktop#52

Due to technical reasons around the security models in most browsers, using Scratch Link requires Internet access. Until/unless we find a way around that it might make sense to add an "Internet access required" icon to all extensions which use Scratch Link. This is perhaps more important for Scratch Desktop but would still be helpful for the online version of Scratch.

From @ntlrsk in https://github.com/LLK/scratch-desktop/issues/52#issue-443677386:
> Currently Scratch Desktop does not indicate that the Bluetooth extensions (e.g., micro:bit, LEGO Mindstorms) also require wireless to work.
>
> Adding the wireless extension next to the Bluetooth icon would make this clear. 
>
> ![image](https://user-images.githubusercontent.com/4721032/57665950-16ee3980-75cc-11e9-8259-bb677b2727ce.png)

From @ntlrsk in https://github.com/LLK/scratch-desktop/issues/52#issuecomment-494559992:
> It would be very helpful to have a warning on the online version too. In South Africa, the microbit and separately the LEGO Mindstorms connections to the hardware kept dropping, and we couldn't figure out why since Bluetooth was working. This happened on a wireless hotspot as well as the wireless network in the Clubhouse space.

**Comment by cwillisf** [comment]
From @ntlrsk in https://github.com/LLK/scratch-desktop/issues/52#issuecomment-492052449:
> Ideally this would happen before Scratch Desktop is disseminated more broadly to 35 countries for Africa Code Week. Broad dissemination of Scratch Desktop on USB drives starts in July 2019.

**Comment by ericrosenbaum** [comment]
We did this! https://github.com/LLK/scratch-gui/pull/4641

**Comment by cwillisf** [comment]
Moved back to LLK/scratch-desktop#52... sorry for the confusion!
