### ISSUE TITLE
Supporting a variety of reading skill levels

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#484]
We often see kids having trouble related to reading in our play tests (like our recent Catch Game external play test). Here are some ways this shows up:

- Following the images or gifs in the tips window or on cards, but not read some or all of the accompanying text
- Mixing up similar-looking blocks when copying them from a card or tip, such as accidentally using "show" instead of "hide" or vice versa
- General discomfort or slowness reading
- Vision and/or reading problems cause some kids to holding their face very close to the screen to read small text
- Difficulty finding a block that they want in the blocks palette

**Comment by mrjacobbloom** [comment]
reminds me of this spiel: https://developers.google.com/blockly/guides/app-integration/best-practices#6_instructions

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#25
