### ISSUE TITLE
Sensing dropdown selection causes toolbox overlap

### ISSUE THREAD

**Issue by LukeSchlangen** [LLK/scratch-gui#4857]
### Expected Behavior

The dropdown selection should occur, but the procedures in the toolbox should not all change their x and y position to be on top of one another.

### Actual Behavior

After a second dropdown selection, all of the blocks end up stacked on top of one another, meaning that in order to edit, a user must move all of the procedures to uncover their code.

Youtube video here: https://youtu.be/uuh9lZ7vfU8

### Steps to Reproduce

- Select a sprite from the dropdown in `Sensing`. -> First one seems to work fine.
- Select a different sprite from the dropdown in `Sensing` -> All blocks end up stacked on one another

### Operating System and Browser

Mac OS 10.14.5
Chrome Version 74.0.3729.169

**Comment by towerofnix** [comment]
Duplicate of https://github.com/LLK/scratch-gui/issues/4400! :P

**Comment by LukeSchlangen** [comment]
Thank you @towerofnix! I'll close this one!
