### ISSUE TITLE
Stage blank on Safari (OSX, IPhone)

### ISSUE THREAD

**Issue by gengshenghong** [LLK/scratch-gui#486]
See https://github.com/LLK/scratch-render/issues/148 for details, it confirmed to be an issue of scratch gui instead of scratch render.

**Comment by gengshenghong** [comment]
FYI, I've tested scratch-vm playground on iOS, and got some ideas, I've removed below lines:
//const audioEngine = new window.AudioEngine();
//vm.attachAudioEngine(audioEngine);

and it worked well (means I see the cat in scratch vm stage). I think it is same for scratch GUI, the root cause is the audio engine not supported on Safari. As @liam4 mentioned you are working on Audio support on Safari recently (not done right?) I assume this should be resolved when audio feature worked on Safari.

Thanks very much,
Shenghong

**Comment by rschamp** [comment]
Fixed in #543

**Comment by thisandagain** [comment]
#543 was closed but not merged as it broke Chrome.

**Comment by rschamp** [comment]
Sorry about that.

**Comment by thisandagain** [comment]
Tracking in #388
