### ISSUE TITLE
how to save ?

### ISSUE THREAD

**Issue by wenxy** [LLK/scratch-gui#4861]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
WHAT DO YOU MEAN?

**Comment by benjiwheeler** [comment]
@wenxy, when you open an issue, please describe the problem you're experiencing. Otherwise, we don't know how to help!

Closing because this came with no description. @wenxy, open a new issue and tell us what you're experiencing.

Thank you!
