### ISSUE TITLE
How to stop?

### ISSUE THREAD

**Issue by hayanggames** [LLK/scratch-gui#4885]
### Expected Behavior

The project stops when I press the red stop button.

### Actual Behavior

It can't stop. Can only start.

### Steps to Reproduce

Need to make the stop button work.

### Operating System and Browser

Ubuntu 19.04 & Chrome 74.0.3729.169(64 bit)
Node.JS 10.16.0

**Comment by apple502j** [comment]
What Scratch code? There are a few ways to make blocks trigger when stopped.
