### ISSUE TITLE
Video transparency in video sensing doesn't go all the way invisible

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#4888]
### Expected Behavior

Setting the video transparency to 100 using the video sensing block `set video transparency to 100` block should cause the video to be totally transparent, and not visible.

### Actual Behavior

`set video transparency block to 100` seems to make the parts of the video that are white be white and the things that are dark to be clear.  It seems to be using the brigthness channel to affect the transparency in some way.  

![Transparency100videoSensingPurple](https://user-images.githubusercontent.com/1088291/58892997-4240e180-86bd-11e9-8d0c-ca930ce1f737.png)

The color that you set the background to seems to matter.  This issue is not observable if you set the backdrop to white, but the contrast changes depending on what color the backdrop is.

White/Clear backdrop at 100% transparency:
![transparency100videoSensingWhite](https://user-images.githubusercontent.com/1088291/58893062-613f7380-86bd-11e9-998c-b341084cb40d.png)

Purple backdrop at 100% transparency:
![Transparency100videoSensingPurple](https://user-images.githubusercontent.com/1088291/58893156-8df38b00-86bd-11e9-80c6-f9ec2353b877.png)

Here is an example project made by @ericrosenbaum to illustrate that. scratch.mit.edu/projects/314377995

It is also worth noting that less transparent video sensing makes the colors look strange.

50% transparent on white backdrop:
![Screen Shot 2019-06-04 at 11 35 38 AM](https://user-images.githubusercontent.com/1088291/58893199-a499e200-86bd-11e9-801f-0f0a921e6dae.png)

50% transparent on purple backdrop:
![Transparency50videoSensingPurple](https://user-images.githubusercontent.com/1088291/58893257-c8f5be80-86bd-11e9-96c9-305b7d6b4cdd.png)

### Steps to Reproduce

Create a new project
Add the video sensing extension
Turn video on
Note: the colors in the video look a little desaturated
Drag out a `Set video transparency block to ` block out
Set the value to 100 and run the block
Note: the video appears to disappear
Add a backdrop, it's easy to see if it is a solid color
Note: the video on the stage is still visible.

### Operating System and Browser

Mac Chrome, Mac Safari

**Comment by fsih** [comment]
Eric's project looks so cool though

**Comment by cwillisf** [comment]
This looks like a blending mode / premultiplied alpha problem, and if that's true at least some of the fix will probably be in scratch-render. I also agree with [@fsih's comment](https://github.com/LLK/scratch-gui/issues/4888#issuecomment-537249111) though ;)

**Comment by paulkaplan** [comment]
Adding to what @cwillisf said: it looks like the video is represented by a PenSkin ([src](https://github.com/LLK/scratch-vm/blob/develop/src/io/video.js#L156)) and PenSkin was changed in May ([PR](https://github.com/LLK/scratch-render/pull/418)) to treat pixel data in pen skins as premultiplied alpha colors. But the video transparency uses the "ghost" effect, which does not work with premultiplied blending (it [adjusts the alpha channel only](https://github.com/LLK/scratch-render/blob/fe01fea9d06576bee2267a58aeac30c17f204e30/src/shaders/sprite.frag#L159), where for premultiplied you'd have to adjust rgb and alpha to do the same thing).
