### ISSUE TITLE
Difficult to delete a sprite, costume, or sound on touch devices

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#4911]
### Expected Behavior

It should not take multiple tries to delete a sprite on a touch device.

### Actual Behavior

The 'delete' icon is so small that it is difficult to tap it with a finger on a touch device.

**Comment by apple502j** [comment]
Huh!? Then the delete button has no use (except for making users who got sprites deleted accidentally angry)

**Comment by chrisgarrity** [comment]
@apple502j actually one of the first things we see scratchers do when they start a project is delete the cat sprite, so it's pretty common. Right now that's pretty hard on any kind of touch device.
