### ISSUE TITLE
Cannot use blocks color eyedropper more than once, it freezes on iOS

### ISSUE THREAD

**Issue by endure90** [LLK/scratch-gui#4920]
--- Edited to add details by @paulkaplan 
Trying to use the blocks eye dropper more than once causes the UI to freeze when using iOS.
Also dragging the eyedropper around causes the whole page to move around.

**Comment by apple502j** [comment]
Can you describe more?

**Comment by towerofnix** [comment]
I think they mean that when the scratch-paint color picker of a shape filled with a gradient is open, the eyedropper tool will always change the first color, even if the user has the second color selected.

**Comment by endure90** [comment]
![image](https://user-images.githubusercontent.com/22869823/59609695-718a3080-914a-11e9-9f83-9ba55a525cf5.png)
When I click on the location of the arrow in the first picture, a mask will open and I will take the color in the stage area. Click the arrow again in the first picture and nothing happens, and the entire work area cannot be dragged

**Comment by AntoniaHE** [comment]
I have the same problem

**Comment by paulkaplan** [comment]
@towerofnix no this is a separate issue specifically with the blocks color picker, I was able to reproduce it on iOS. I updated the description with more repro steps.

**Comment by paulkaplan** [comment]
But @towerofnix if there isn't already an issue filed for that problem it would be good to file that one separately! I've noticed that recently.

**Comment by towerofnix** [comment]
@paulkaplan looks like you already made one not long after I commented :) https://github.com/LLK/scratch-paint/issues/861
