### ISSUE TITLE
how to enable login and register feature in scratch-gui?

### ISSUE THREAD

**Issue by antcto** [LLK/scratch-gui#4945]
The login and registration of scratch-gui are disabled by default. How to enable them?

I checked the menu-bar.jsx:

> no login session is available, so don't show login stuff

how to set the seesion? The scratch-www can request session from server but I didn't find where the scratch-gui request the server..

**Comment by apple502j** [comment]
scratch-www handles sessions.
https://github.com/LLK/scratch-www/blob/develop/src/views/preview/presentation.jsx#L329

Note: to enable that I think you need developer access (Scratch Team).

**Comment by antcto** [comment]
your meaning i need to install scratch-www and link to scrath-gui, and then i can use the login and registration feature?

**Comment by apple502j** [comment]
Nope, there are some closed-source applications that are required.
