### ISSUE TITLE
How to play the project on website without scratch-www?

### ISSUE THREAD

**Issue by antcto** [LLK/scratch-gui#4946]
I just only plan to play the scratch project on my website without scratch-www. how to do it?
which javascript files need to import into web page?

**Comment by apple502j** [comment]
https://llk.github.io/scratch-gui/develop/player.html
https://github.com/LLK/scratch-gui/blob/develop/src/playground/player.jsx

**Comment by antcto** [comment]
thanks for your reply and help.

**Comment by antcto** [comment]
@apple502j did you know where has the original of https://llk.github.io/scratch-gui/develop/lib.min.js?

i need to change the project_server url to myself in my web project.
