### ISSUE TITLE
Block input field visible over sprite when sprite library is open

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#495]
### Expected Behavior

The input field from the block in the scripting area should not be visible when the sprite library is open.

### Actual Behavior

During the Catch Game External Playtest (6/21/17), one of the users had completed the "falling" stack from the cards (making the apple fall), then opened the sprite library, and the input field of one of the blocks in the scripting area was visible in the library, over the sprites.

<img width="744" alt="screen shot 2017-07-05 at 4 23 58 pm" src="https://user-images.githubusercontent.com/1320456/27883647-4c956830-619f-11e7-96c3-36c827f4d78b.png">

### Steps to Reproduce

Have not yet attempted to repro.

### Operating System and Browser

_Mac, Chrome_

**Comment by amazinigmech2418** [comment]
Unfortunately, this is due to canvas layering errors. Maybe not rendering the blocks when in the menu could help.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/1129
