### ISSUE TITLE
Missing image thumbnails in the backdrop library - on one computer

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#496]
### Expected Behavior

All of the thumbnails for the backdrops should show up in the backdrop library.

### Actual Behavior

During the Catch Game External Playtest (6/21/17), one of the users had a lot of broken thumbnails in their backdrop library. The computer was "United States". I don't recall seeing this on other computers.

<img width="1132" alt="screen shot 2017-07-05 at 4 44 31 pm" src="https://user-images.githubusercontent.com/1320456/27884255-a7ac3c4c-61a1-11e7-91d9-12eaeb4feda9.png">

### Steps to Reproduce

Have not yet attempted to repro.

### Operating System and Browser

_Mac, Chrome_

**Comment by chrisgarrity** [comment]
Discovered that emptying the cache and reloading corrects the missing thumbnails in the  smoke test today (12/15)
