### ISSUE TITLE
[Questions] Which directory contains the logic of state management?

### ISSUE THREAD

**Issue by syang** [LLK/scratch-gui#4963]
(not sure if this is the right place to ask, but bear with me to start here)

Hi Scratch Dev team,

I wanted to understand where the state management logic is located in the repo. 

- Is state mgmt located in src/playground? 

- the doc says https://github.com/LLK/scratch-vm is the logic to maintain states, and I see src/containers heavily use that library, is the state mgmt located in src/containers?

One more related question, if a Scratch program is about two players' online game, which there will be some state exchange between the two clients, how will such functionality get accomplished?

Thanks,

**Comment by benjiwheeler** [comment]
@syang, can you say more about what you mean by "state management"? Do you mean, the current state of all the sprites, where in their code execution currently is, and what variable/list values are?

For a two player game where each player is using a separate computer, you would have to use cloud variables, and have the Scratch program use changes in those variable values to communicate between the two instances of the game.

**Comment by syang** [comment]
Hi @benjiwheeler, 

> @syang, can you say more about what you mean by "state management"? Do you mean, the current state of all the sprites, where in their code execution currently is, and what variable/list values are?

Yes, by 'state' I mean the variables tracking a program states.
So yes, I meant this kind of things. e.g., if I am building a Mario Jump, what is the velocity of Mario currently is; what you listed above is also 'state' I meant here.

> 
> For a two player game where each player is using a separate computer, you would have to use cloud variables, and have the Scratch program use changes in those variable values to communicate between the two instances of the game.

"you would have to use cloud variables..." Yes, exactly I wanted to know which project / repo under LLK is meant to be the cloud backend, so that it can track these cloud variables.

**Comment by benjiwheeler** [comment]
Thanks for clarifying. My best answer is "it's somewhere in the vm" but I know that's not a very helpful answer! I'd like to know more about that area of the code as well.

**Comment by kchadha** [comment]
Hi @syang, all scratch-project related state is located in the scratch-vm runtime object (located here: https://github.com/LLK/scratch-vm/blob/develop/src/engine/runtime.js). In the scratch-vm (virtual machine), the objects that represent sprites are called targets, and variable information is part of a target.

If you have a local copy of scratch-gui running, you can pause the debugger somewhere that has access to the vm and access the list of targets through `vm.runtime.targets`. Each target has a `variables` property which is a map of variable IDs to variable objects (containing information about the variable).

Regarding cloud variables, both the VM and GUI have logic for interacting with the cloud server. The scratch cloud server is private, so if you are creating your own application, you would need to implement your own server.

The logic in the gui/vm for interacting with the cloud server lives in the following places:
- https://github.com/LLK/scratch-gui/blob/develop/src/lib/cloud-provider.js
- https://github.com/LLK/scratch-gui/blob/develop/src/lib/cloud-manager-hoc.jsx
- https://github.com/LLK/scratch-vm/blob/develop/src/io/cloud.js

**Comment by benjiwheeler** [comment]
Closing per @kchadha's very thorough answer! Thanks!

**Comment by syang** [comment]
> Hi @syang, all scratch-project related state is located in the scratch-vm runtime object (located here: https://github.com/LLK/scratch-vm/blob/develop/src/engine/runtime.js). In the scratch-vm (virtual machine), the objects that represent sprites are called targets, and variable information is part 
of a target.

@kchadha, is the virtual machine (scratch-vm) running with scratch-gui? i.e., scratch-vm is purely a browser side logic (more specifically, it holds states inside the React app)?
> 
> If you have a local copy of scratch-gui running, you can pause the debugger somewhere that has access to the vm and access the list of targets through `vm.runtime.targets`. Each target has a `variables` property which is a map of variable IDs to variable objects (containing information about the variable).
> 
"If you have a local copy of scratch-gui running..." does it matter whether I run a local copy or I access the scratch-gui logic from the public site, such as https://scratch.mit.edu/projects/320393765/editor?  I feel I should be able to open a debugger either way, right (assuming the scratch-vm is an in-browser component)?


> Regarding cloud variables, both the VM and GUI have logic for interacting with the cloud server. The scratch cloud server is private, so if you are creating your own application, you would need to implement your own server.

Two questions here:

- Do you know why the cloud server is not open sourced? 
- Do you know what API the cloud server should be implementing (if I wanted to implement a cloud server)?

> 
> The logic in the gui/vm for interacting with the cloud server lives in the following places:
> 
> * https://github.com/LLK/scratch-gui/blob/develop/src/lib/cloud-provider.js
> * https://github.com/LLK/scratch-gui/blob/develop/src/lib/cloud-manager-hoc.jsx
> * https://github.com/LLK/scratch-vm/blob/develop/src/io/cloud.js
