### ISSUE TITLE
Change the word "scripts" to "blocks"

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#497]
We currently use the word "scripts" on the tab that shows you the blocks palette and blocks workspace. Let's consider changing this to the word "blocks."

**Comment by carljbowman** [comment]
YAAAAAS!

**Comment by CosmicWebServices** [comment]
Is there confusion related to this wording?

**Comment by angryboy2016** [comment]
here i rename scripts to blocks on first tab

![scratch 3 0](https://user-images.githubusercontent.com/24998969/27932518-dff881c6-6252-11e7-90d3-ad24ab2e9013.PNG)

**Comment by thisandagain** [comment]
@CosmicWebServices Yes. We use the word "blocks" throughout our help materials, but very rarely use the word "script" or "scripts". While testing with people who have never used Scratch before we have found that the use of the word "Scripts" can be confusing.
