### ISSUE TITLE
Understanding the coordinate system

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#498]
There are several issue we see in play tests related to the coordinate system:

- Lack of familiarity with the terms "x" and "y" to refer to the horizontal and vertical axes
- Not knowing that the center of the stage is at 0,0

**Comment by liam4** [comment]
The old xy-grid.gif background comes to the rescue!

> ![xy-grid](https://user-images.githubusercontent.com/9948030/27932007-7593b86c-6272-11e7-9ded-9a4673200ac3.gif)

(Well, maybe it's not quite a direct solution, but it could be useful to look at when thinking about this issue.)

**Comment by jwzimmer** [comment]
I also saw users not understanding that x, y positions referred to a sprite's coordinates on the stage, and not knowing what values to expect to be in that range.

**Comment by chooper100** [comment]
In Scratch 1.x and 2.0, the Scratch coordinates of the mouse are displayed beneath the stage:

![image](https://user-images.githubusercontent.com/14095134/28093857-40cd1dbc-6691-11e7-9d8b-ecab626d23ca.png)

I think adding this into 3.0 (any insight why it was not added originally?) along with an updated xy-grid.gif would go a long way to solve this issue

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#23
