### ISSUE TITLE
Invalid padding of "My Blocks" boolean type block

### ISSUE THREAD

**Issue by BrightLin** [LLK/scratch-gui#4984]
### Expected Behavior

Expect the field text horizontal align to block.
![image](https://user-images.githubusercontent.com/15828392/61122353-30303b00-a4d4-11e9-9489-df2cc372a148.png)

### Actual Behavior

Right align to the block when the field text is single letter. This issue occurs on the boolean type field.
![image](https://user-images.githubusercontent.com/15828392/61122463-6c639b80-a4d4-11e9-9b56-8e12e932fab0.png)
It is OK on the "Make a block" modal
![image](https://user-images.githubusercontent.com/15828392/61122564-b51b5480-a4d4-11e9-8503-b564f8b273e0.png)

### Steps to Reproduce

1. Change to "My Blocks" category
2. Click "Make a block" button
3. Add an input- boolean and modify the text to 'a' and click "OK"
![image](https://user-images.githubusercontent.com/15828392/61122564-b51b5480-a4d4-11e9-8503-b564f8b273e0.png)
4.See the workspace
![image](https://user-images.githubusercontent.com/15828392/61122582-c5333400-a4d4-11e9-8e69-a3272ae2b624.png)
![fieldtext](https://user-images.githubusercontent.com/15828392/61122918-9ec1c880-a4d5-11e9-9589-29a6bdd1aa01.gif)

### Operating System and Browser
Windows 10, Google Chrome 75.0.3770.100

**Comment by towerofnix** [comment]
This is already reported in LLK/scratch-blocks#1863.

**Comment by BrightLin** [comment]
> This is already reported in [LLK/scratch-blocks#1863](https://github.com/LLK/scratch-blocks/issues/1863).


OK, thank you towerofnix

**Comment by BrightLin** [comment]
@towerofnix Got it. Thank you towerofnix!

**Comment by towerofnix** [comment]
@ericrosenbaum @BrightLin since this is a duplicate issue already being tracked elsewhere, it should be closed.

**Comment by ericrosenbaum** [comment]
thanks @towerofnix and @BrightLin! closing as duplicate
