### ISSUE TITLE
Typing/ changing block input values via typing can be slow and error-prone

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#499]
In play tests we see that kids often have difficulty typing in numbers and words, that it is slow compared to other things they do in the UI, and they sometimes make errors that result in confusion.

**Comment by jwzimmer** [comment]
I also noticed that several users during the Catch Game External Playtest (June 2017) had trouble when typing values into the block inputs. They had trouble selecting the input and getting the cursor to appear in it - clicking in the block input was difficult and caused at least one user to drag blocks unintentionally.

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#22
