### ISSUE TITLE
how to load local static assets or sprite?

### ISSUE THREAD

**Issue by acegank** [LLK/scratch-gui#4998]
in the 'src/components/library-item/library-item.jsx' 

> const iconURL = iconMd5 ?
            `https://cdn.assets.scratch.mit.edu/internalapi/asset/${iconMd5}/get/` :
            this.props.iconRawURL;

but i want to load my local assets, so i modify ，

> const iconURL = iconMd5 ? `./static/assets/${iconMd5}` : this.props.iconRawURL;

but now， i don't konw how to download the assest to my project？

**Comment by apple502j** [comment]
You can check LLK/scratch-desktop .
https://github.com/LLK/scratch-desktop

**Comment by acegank** [comment]
@apple502j  thank you！

**Comment by aquino-luane** [comment]
@acegank did you find how to do it? if so I appreciate if you can share how you did 🙇‍♀️
I checked the scratch-desktop shared link by @apple502j  but was not able to figure it out

**Comment by mxmou** [comment]
The relevant code in scratch-desktop is:
https://github.com/scratchfoundation/scratch-desktop/blob/f7ed5a2/src/common/ElectronStorageHelper.js
https://github.com/scratchfoundation/scratch-desktop/blob/f7ed5a2/src/renderer/ScratchDesktopGUIHOC.jsx#L92
https://github.com/scratchfoundation/scratch-desktop/blob/f7ed5a2/src/renderer/ScratchDesktopGUIHOC.jsx#L121

**Comment by aquino-luane** [comment]
> The relevant code in scratch-desktop is: https://github.com/scratchfoundation/scratch-desktop/blob/f7ed5a2/src/common/ElectronStorageHelper.js https://github.com/scratchfoundation/scratch-desktop/blob/f7ed5a2/src/renderer/ScratchDesktopGUIHOC.jsx#L92 https://github.com/scratchfoundation/scratch-desktop/blob/f7ed5a2/src/renderer/ScratchDesktopGUIHOC.jsx#L121

I will check, thank you 🙇‍♀️
