### ISSUE TITLE
Trouble with scrolling 

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#500]
In play tests we see several issues related to scrolling the vertical panes in the UI, including the blocks palette, blocks workspace, and libraries:

- They don't know that they can scroll at all (or maybe find it too difficult), so they often choose only from the items visible at the top of the pane, and can't find blocks or library items that are at the bottom.
- Kids often drag using the tiny scroll bar handle at the edge of the pane, perhaps because they are unaware of other scrolling gestures (dragging on the background, two finger scrolling, using the mouse scroll-wheel)

**Comment by jwzimmer** [comment]
I saw this as well with at least 2 users in the Catch Game external playtest (June 2017). The users used the tiny scrollbar at the edge of the screen, which made it harder for them to easily scroll.

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#21
