### ISSUE TITLE
why use redux ?

### ISSUE THREAD

**Issue by linushp** [LLK/scratch-gui#5006]
many state no need multi component to share .
just one component inner state ,
why use redux ?  I cannot read the code , too diffcult.

**Comment by apple502j** [comment]
Then learn Redux :stuck_out_tongue:

**Comment by paulkaplan** [comment]
@linushp I generally agree that components that are truly isolated may not need to use redux at all, and that is actually our general pattern (see e.g. the sound editor, many inputs, etc.) One thing to keep in mind is even if something looks like local state, it needs to persist when the editor is "flipped" from project page view to editor view on the website. 

Are there specific components that use local state that should not be in redux?

**Comment by linushp** [comment]
@paulkaplan  

I see .  but why actions and reducer in one js file ? 

I like the  redux style of https://www.npmjs.com/package/redux-dispatch-action
