### ISSUE TITLE
Stack highlighting could be more obvious

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#501]
We sometimes see in play tests that kids do not notice the stack highlighting, leading to confusion about which parts of their code are running.

**Comment by liam4** [comment]
Yeah, I [posted about this](https://scratch.mit.edu/discuss/post/2702795/) in the Scratch discussion topic.

> ![demo gif](https://i.cubeupload.com/SSTAhi.gif)
>
> I don't find that the “running” highlight contrasts very well with the background color of the scripting area..
