### ISSUE TITLE
Custom procedure parameter being set to 0 after being read

### ISSUE THREAD

**Issue by tarmelop** [LLK/scratch-gui#5011]
### Expected Behavior

This code should "say" the same value of the parameter twice.
<img width="385" alt="Screen Shot 2019-07-22 at 12 29 16 PM" src="https://user-images.githubusercontent.com/2232828/61648160-e6d2af00-ac7c-11e9-9fae-1b0d6868746c.png">

### Actual Behavior

The second time the parameter is = 0

### Steps to Reproduce

Just reproduce the code in the screenshot.

### Operating System and Browser

Mac OS 10.14.5 Chrome 75.0

**Comment by kchadha** [comment]
It looks like this was caused by a recent set of performance changes that went into the vm (LLK/scratch-vm#2145).
