### ISSUE TITLE
When right-clicking sprite, duplicate menu does not show.

### ISSUE THREAD

**Issue by mjk0513** [LLK/scratch-gui#5031]
### Expected Behavior
At first time, right-clicking sprite, duplicate menu appears.
<img width="217" alt="スクリーンショット 2019-07-26 23 10 09" src="https://user-images.githubusercontent.com/8245567/61958640-a8cae780-affc-11e9-94a6-e8d27b717053.png">

### Actual Behavior
When dragging sprite to another space, copy menu does not show.
And OS's context-menu appears.

![8tw8n-n69at](https://user-images.githubusercontent.com/8245567/61958597-95b81780-affc-11e9-9ac5-1f8a4f4d465b.gif)

### Steps to Reproduce
Look at this gif file.

### Operating System and Browser
* macOS 10.14.5
* Chrome 75.0.3770.142
*  Safari 12.1.1
* FireFox 68.0.1

**Comment by paulkaplan** [comment]
Thanks! Submitted a PR for this.
