### ISSUE TITLE
How to store project data in my database?

### ISSUE THREAD

**Issue by Tsepu** [LLK/scratch-gui#5040]
### Expected Behavior

I am working on a project using Scratch-GUI. I included it in my local project. I want to store data of project in my database when someone create project on the system, but i can't. Do you have any idea?

**Comment by apple502j** [comment]
Modify https://github.com/LLK/scratch-gui/blob/develop/src/lib/save-project-to-server.js

**Comment by Tsepu** [comment]
I see https://github.com/LLK/scratch-gui/blob/develop/src/lib/save-project-to-server.js. But honestly i don't know what to do. Can you give me more detail information, please?

**Comment by apple502j** [comment]
I can't answer because I don't know how your project is working, but basically you send API request to your server, and your server handles database part.

**Comment by Tsepu** [comment]
???
