### ISSUE TITLE
How to change options?

### ISSUE THREAD

**Issue by Tsepu** [LLK/scratch-gui#5041]
### Expected Behavior

I included scratch-gui in my local project. Now i want to change options as follows:

1. Language: [English, Korea]
2. Hide Coming soon buttons.
3. Enable sound
4. Show Recycle Bin

### Actual Behavior

1. So many Languages
2. many Coming soon button
3. Sound is disabled
4. There is no Recycle Bin

**Comment by apple502j** [comment]
For languages, you may want to edit scratch-l10n. Coming Soon is actually for buttons that only work with Scratch - it's up to you whether you remove it.

What sound is disabled?

**Comment by Tsepu** [comment]
I just want to control options fully. Above things are  examples.

**Comment by apple502j** [comment]
Well,
1) Edit scratch-l10n
2) Remove coming soon thing
3) What do you mean
4) Edit scratch-blocks

**Comment by apple502j** [comment]
If you want to control fully, make from scratch, not from Scratch.

**Comment by Tsepu** [comment]
What do you mean from scratch not from Scratch. Is it different things? Can you send me links?
