### ISSUE TITLE
Cannot download file if I pack scratch into an apk file 

### ISSUE THREAD

**Issue by crouse12** [LLK/scratch-gui#5065]
I use Cordova to pack scratch 3.0 into an apk file.
It works, but it cannot download sb3  file.
May I know how to fix it?

**Comment by apple502j** [comment]
Fix: Don't make it into APK

You should wait for Scratch Android (coming this year?)

**Comment by crouse12** [comment]
Are you sure that the scratch android will appear this year?

**Comment by apple502j** [comment]
Generally speaking: developing an app is a hard work. I got this email from the team:

> There will be updates over the next month or so as we get ready to launch the new Android app later in the fall.

However, this is not very promised, because if there is a blocking issue, that will be postponed. (It just happened for Scratch 3.0 - from August 2018 to January 2019)

**Comment by crouse12** [comment]
OK! I am waiting for official scratch-android.
The following video is my apk test.

https://www.youtube.com/watch?v=tP_N9689Kug
