### ISSUE TITLE
No visual clues in operators for strings vs numbers vs...

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#508]
Observed in the catch game playtest video:

Trying to check for the y position of the apple being below -170.

First they typed the text 'y position' into the first operand instead of finding the y-position reporter. They did eventually realize it didn't match the card and found the reporter.

They typed "- 170" with a space between the `-` and the `170`. This turned the value into a string, and the operator was never true.  They never figured this one out.

**Comment by chrisgarrity** [comment]
![screen shot 2017-07-06 at 3 57 37 pm](https://user-images.githubusercontent.com/399209/27930244-e1734e9e-6263-11e7-9d8b-259db4180a25.png)

**Comment by heyitsmeuralex** [comment]
Perhaps give the input a red border when an invalid value is given, similar to 1.4's divide-by-zero behaviour..?

Adding a tooltip to it too (e.g. "This should be a number!") would be a good idea, no?

**Comment by CosmicWebServices** [comment]
@heyitsmeuralex I mean that is good if they manually inputed it and not put it in like a variable...

**Comment by chrisgarrity** [comment]
@heyitsmeuralex sometimes you want to be able to use strings - for example, when sorting alphabetically. So it's not an invalid input, it's just a challenging concept for beginners - that inputs can be considered text or numbers, and Scratch attempts to guess which you mean.

**Comment by heyitsmeuralex** [comment]
> when sorting alphabetically

```
"aanner" > "bad"
```
I'd say that's - although common in many languages - _more_ confusing than Scratch technically having a single datatype. Why is `"hello" - 2` what it is, for example? Scratch3 should _at least_ provide some kind of error or warning...

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#17

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#18
