### ISSUE TITLE
Dragging the mouse outside a modal closes it; user can lose their work

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#5080]
### Expected Behavior

1) in sound recording modal, mousedown on sound selection handles
2) drag them to right-hand end of sound
3) mouse goes a bit farther
4) everything is ok

### Actual Behavior

4) sound recording modal closes, losing my work! :(

![lostrec](https://user-images.githubusercontent.com/3431616/62747201-66a09d80-ba21-11e9-9112-da7e580554f1.gif)

### Ideas

Seems like this is likely to be solved by updating react-modal; see similar fix in www: https://github.com/LLK/scratch-www/pull/2987

**Comment by apple502j** [comment]
Dependency bump won't solve this, as that PR only fixed dragging on text input. (also, react-modal is 3.9 so it should have been fixed if that's the case!)
