### ISSUE TITLE
Library should expect 3.0 sprite format

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#5084]
Currently, the library json files contain sprite and asset info generated from 2.0 projects. Once we've updated the library generator to use 3.0 projects, the GUI will need to handle the changes to a few properties. Here are the changes I've found so far:

- The library item container should use the `md5ext` instead of `baseLayerMD5` to animate the sprite's costumes on hover
- The randomize sprite position util should set the `x` and `y` properties instead of `scratchX` and `scratchY`  (Paul: this one is already handled)
- lib/empty-assets.js may need to be changed to use the 3.0 format as well, depending on how it is used.

Another note: to eliminate dependency on library generation using 3.0 syntax, it would be best to implement this in a way that supports both formats, that way we can release without waiting for the actual library to change, which may be blocked by other issues.

**Comment by paulkaplan** [comment]
@ericrosenbaum looked into this, I think the second one you mention is not needed because the code already handles 3.0 sprite objects
