### ISSUE TITLE
New Block: ( ( t ) if < condition > else ( f ) )

### ISSUE THREAD

**Issue by averagewolfie** [LLK/scratch-gui#5099]
### Expected Behavior

This is a shorthand if-else reporter block which returns first input `( t )` if `< condition >` is true, or third input `( f )` if `< condition >` is false. This would be especially useful with `( join ( txt ) ( txt ) )` block, or when setting variables, because it can eliminate potential duplicate uses of specific blocks or strings in a function. Suppose, for example, you want Scratch cat to say your username "is the current user," but also just say something slightly different if no one is logged on. The example would be to use this...

![block](https://user-images.githubusercontent.com/42146549/62995616-f03bdb00-be26-11e9-8e8c-c4d870c81802.png)

### Actual Behavior

... as opposed to this...

![block2](https://user-images.githubusercontent.com/42146549/62995627-fcc03380-be26-11e9-9130-70e711e32d5e.png)

Just by doing this, two things are easily eliminated: one say block, and a recycled string value. The visual length of the code blocks is also nicely compacted. Now, sure, a repeated string could also be put into a variable, but with this block, you wouldn't have to do that either.

**Comment by Kenny2github** [comment]
Duplicate of #778

**Comment by averagewolfie** [comment]
Ah. For some reason, I must have missed that.
