### ISSUE TITLE
On Edge, some vector images turn into grey rect & ?

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#5105]
### Expected Behavior
Image should be kept as-is!

### Actual Behavior
![ball-e](https://user-images.githubusercontent.com/33279053/63168003-e2c46200-c06d-11e9-89a6-1c5176181f96.png)
Some of the **vector** images (which are usually in the library) turn into grey rect & ? image on Edge. (PNG version above. For SVGs see the projects, MD5 checksum of SVG `8E768A5A5A01891B05C01C9CA15EB6AA`)

### Bug Reports
- https://scratch.mit.edu/projects/190478909/ `Cat1`, `Cat2` and `Cat6` (all Scratch Cat)
- https://scratch.mit.edu/projects/241515902/ `Sprite1` (Scratch Cat)
- https://scratch.mit.edu/projects/323776983/ `Ball1` (sprite library name Ball) - `Ball10`

### Steps to Reproduce
On Edge, I tried adding some sprites using the Surprise and found "that":
- Starfish
- Winter Hat
- Cat
- Ball
- Story letters
and more.

The console showed me something "interesting": `XML5662 "The "xml" prefix is reserved and must have the URI "http://www.w3.org/XML/1998/namespace/"."` This can be read as "asset problems" but I thought it will be nice to post here.

See also https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/console/error-and-status-codes#xml-codes

### Operating System and Browser
Edge on Windows 10

*Note: This **is** data loss. Make sure to put **critical**!*

**Comment by lktornado360** [comment]
also https://scratch.mit.edu/projects/323718694/ and https://scratch.mit.edu/projects/10016238/
