### ISSUE TITLE
Unable to load "embed" project player

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#5107]
### Expected Behavior
Able to load the "embed" project player via an iframe

### Actual Behavior
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.<anonymous> (https://scratch.mit.edu/js/projects.bundle.js:161:3254301)
    at t (https://scratch.mit.edu/js/common.bundle.js:1:101)
    at Object.<anonymous> (https://scratch.mit.edu/js/projects.bundle.js:161:3351957)
    at t (https://scratch.mit.edu/js/common.bundle.js:1:101)
    at window.webpackJsonp (https://scratch.mit.edu/js/common.bundle.js:1:418)
    at https://scratch.mit.edu/js/projects.bundle.js:1:1
```

### Examples
- https://geometrydash.io/
- https://www.crazygames.com/game/paper-minecraft

### Operating System and Browser
Mac OS 10.14.5 | Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by thisandagain** [comment]
@BryceLTaylor Can you try to reproduce this (perhaps in something like Glitch or Wikia)?

**Comment by benjiwheeler** [comment]
FWIW, I was able to embed using jsbin:

![image](https://user-images.githubusercontent.com/3431616/63259309-56d55480-c27e-11e9-8eb1-e77028ef66fb.png)

It seems to work fine, though there were a bunch of console errors:

![image](https://user-images.githubusercontent.com/3431616/63259414-97cd6900-c27e-11e9-959f-add2e059bc96.png)

Note no localstorage errors, though.

**Comment by paulkaplan** [comment]
I'm not able to repro this either. We don't rely on localStorage for anything, but do use it for a few extras. I tried disabling localStorage on Firefox (about:config => dom.storage.enabled) and it still loaded fine.

**Comment by BryceLTaylor** [comment]
I couldn't either.  Closing since no one can reproduce.
