### ISSUE TITLE
Add locale switching to the UI

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#511]
Will need a way for the user to switch to the language of their preference regardless of browser setting. Should be a saved preference for signed in users.

Part of #477

**Comment by CosmicWebServices** [comment]
I am assuming that this could use the local storage api (or a cookie) unless you want this stored on server?

**Comment by chrisgarrity** [comment]
@CosmicWebServices this is a place holder issue for designing the widget for switching languages (where should it be, icon? dropdown?, etc). Most of the other parts of #477 can get done without this, so splitting it out.

**Comment by paulkaplan** [comment]
Implemented!
