### ISSUE TITLE
Sprite Info / Stage Info Area Updates

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#514]
![desktop - 1280x720](https://user-images.githubusercontent.com/3409578/27959368-246e181e-62f5-11e7-9cca-6ff1a9391b2c.png)

### New Icons
[new icons.zip](https://github.com/LLK/scratch-gui/files/1131048/new.icons.zip)

### Loose Sizing Reference
Each grid unit is 4px (.25rem). Margins, padding, fixed sized objects (e.g. sprite tile, text field heights) should match the sizing. Other things like positioning should be left up to flex-box. 

<img width="1068" alt="screen shot 2017-07-07 at 9 13 45 am" src="https://user-images.githubusercontent.com/3409578/27959231-9fd6832a-62f4-11e7-8f2c-80c0aee9ab69.png">

**Comment by paulkaplan** [comment]
@carljbowman I need a few more details to implement this:

1. What is the active state of the stage? Does it outline the thumbnail the way it does now (that might be strange now that is edge-to-edge?)
2. What is the clickable area to select the stage. Right now it is the stage thumbnail. Is it still that?
3. Does clicking the little purple arrows change the backdrop thumbnail and the stage itself?

**Comment by carljbowman** [comment]
@paulkaplan - Thanks for calling these out!

### 1. Stage Select State. Here is a radical idea...
![selected-stage](https://user-images.githubusercontent.com/3409578/28826864-959837c4-7699-11e7-85b5-9d59e95611f9.png)

Selection state (sprite or stage) has consistently been a confusing part of the interface. This is a place I would like to continue to explore, but for now it'd be great to have more emphasis on the selected element.

2.0 had a strategy of incorporating a sprite/bg "watermark" in the top left part of the workspace to try to reenforce their association. I am not convinced this is the right strategy. More to be discussed and explored. Animation maybe something we play with here.

### 2. Clickable Stage Area 
Based on the response to question  1, we should make the entire container element clickable. 'Add Sprite' and 'BG Navigation' (question 3) should remain independently clickable. 

### 3. Purple Arrows
Ideally these would change the Backdrop Thumbnail and the Backdrop on the Stage. Playtesting has highlighted that the relationship of Backdrops to Stage is rather confusing. This relationship also different from how Sprite to Costumes are representing in the UI.

I'd like to explore a way of setting the Backdrops in this area without having to go to the Backdrop (Paint Editor tab) or by using the 'switch backdrop to' block.

Small detail. The arrows should only become clickable when appropriate. The sketch above is a bit misleading as the right arrow looks clickable, but there is only 1 backdrop.  

### 4. Global Colors
Maybe it makes sense to break this out into a separate issue of global UI colors. I'd like to update the colors globally to increase contrast, but also clean up our color variables with the intention to support even higher contrast settings for accessibility.  

Tracking here: https://github.com/LLK/scratch-gui/issues/576

**Comment by mrjacobbloom** [comment]
Regarding your 4th point, I really like how the backdrop arrows are "looks colored" -- I don't know if it'd actually make anything clearer, but I think it's a cool idea to have ui elements be the same color as the blocks that relate to them

**Comment by paulkaplan** [comment]
@carljbowman so just to be totally clear about the different parts of this, here is the checklist as I understand it:

- [x] Change icons for new sprite / new backdrop
- [ ] Change stage selected state
- [ ] Make clicking on entire stage area select the stage
- [ ] Add purple arrows that change the current backdrop
- [ ] Update icons in the sprite info area (x, y, show/hide)
- [ ] Change border visuals for selected sprite cards
- [ ] Updating background colors (tracked separately)

Anything missing from here? Sorry, I just need an itemized list or else i'll forget something.

**Comment by carljbowman** [comment]
@paulkaplan - Thanks for clarifying. This list looks great. I'd only add that we should also do a quick pass on spacing and sizing of the elements in the Sprite Info Area. I'd be happy to pair on this. Shouldn't take more than 30min to tweak.

**Comment by CosmicWebServices** [comment]
Just from a UX perspective I actually just from looking at the picture I could not find where the motion, events data, etc was at first... and when i did find it it was kind of hard to tell the diferences without reading it maybe instead of just colors there can be icons also?

**Comment by carljbowman** [comment]
@CosmicWebServices - Thanks for the feedback. We have talked about exploring icons for the Blocks Categories in addition to the colors. Here are some related issues:

https://github.com/LLK/scratch-blocks/issues/995
https://github.com/LLK/scratch-blocks/issues/262
