### ISSUE TITLE
About language settings

### ISSUE THREAD

**Issue by hyansuper** [LLK/scratch-gui#5141]
1. How to set a non-English lang as default?
2. How to make my customed extensions support multi languages?
Thank you!

**Comment by apple502j** [comment]
1) The default is not English, but your language. Making non-English a real default would need tons of fix against `FormattedMessage`'s defaultMessage, but for one-time use you can use like `?locale=zh-tw`.
2) Not yet supported. seealso: https://github.com/LLK/scratch-vm/blob/develop/docs/extensions.md
