### ISSUE TITLE
pull-down language of [backdrop# of Stage] block

### ISSUE THREAD

**Issue by manabu-s** [LLK/scratch-gui#5144]
### Actual Behavior

When [backdrop# of Stage] block is dragged to the code area, the pull-down language is set to English.
I guess it is caused by a mistake in the translation file.

### Steps to Reproduce
1. Set language to Japanese
2. Drag  [backdrop# of Stage] block to the code area
3. The backdrop # part is changed to English
![bug](https://user-images.githubusercontent.com/1431162/64149826-f8a19780-ce61-11e9-9268-7f97f0fdf115.png)

### Operating System and Browser
Windows10 Chrome76

**Comment by apple502j** [comment]
Duplicate of #4209 / #4209 との重複Issue

**Comment by manabu-s** [comment]
@apple502j ありがとうございます。取り下げます。
