### ISSUE TITLE
Make greenkeeper PRs show the commits it includes

### ISSUE THREAD

**Issue by picklesrus** [LLK/scratch-gui#5147]
Other greenkeeper PRs we get from other repos have a release notes and commits section.  e.g. https://github.com/LLK/scratch-www/pull/2985

It would be nice if the greenkeeper PRs from to update gui on www had a list of commits too so we can tell what we're merging.

**Comment by apple502j** [comment]
@BryceLTaylor This can be closed since we no longer use greenkeeper
