### ISSUE TITLE
How to save project?

### ISSUE THREAD

**Issue by Tsepu** [LLK/scratch-gui#5158]
### Expected Behavior

Send request when click the "Save now"

### Actual Behavior

It doesn't show any reaction. But when i import project it gives response.

### Steps to Reproduce

- I just downloaded scratch-gui.
- I changed urls in project-fetcher-hoc.jsx
- ? I want save project json response in my database.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
We can't answer without the code and error - what's up?

**Comment by Tsepu** [comment]
[https://drive.google.com/file/d/1JO9Yi35GqsabVydYdvpFnJ8YhX6D8cGz/view?usp=sharing](url)

If you this, you know what happened. what i just want to know is why don't work "Save now" button.

**Comment by towerofnix** [comment]
@Tsepu it looks like your localhost server does not support the API scratch uses for uploading (saving) project files. I don't know exactly what your setup is but you need to implement a mockup API that works the way [this documentation](https://gist.github.com/towerofnix/5c75560dfea08f8cda54d0a459c2085f) describes.

(Actually, according to those errors (ERR_CONNECTION_REFUSED), you don't have a server there running at all - like I said above, you'll need to make a server according to the documentation I linked. AFAIK there is no open source tool or reference for doing that yet though.)

**Comment by essedev** [comment]
So to have a working copy of Scratch, with auto save functionality, the possibility to enbed in an iframe ecc.., I have to recreate the whole API system? I just installed scratch-gui but I'm not really understanding what else I need. Thanks, any help will be really appreciated!

**Comment by hyperobject** [comment]
Similar to #8591, we're not going to be able to fully address this question, but feel free to continue the conversation!
