### ISSUE TITLE
Support for Edible Scratch and Meow

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#518]
Do we want to support Edible Scratch (yum) and Meow (cat) in Scratch 3.0

**Comment by liam4** [comment]
Yes! 🐱 

<img width="187" alt="screen shot 2017-07-10 at 7 06 58 am" src="https://user-images.githubusercontent.com/9948030/28015556-79eae894-653e-11e7-9a4a-250148c9c28b.png">
