### ISSUE TITLE
Modal for list creation on stage says VARIABLE will be available to all sprites

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-gui#5184]
### Expected Behavior

When creating a list on the stage, where there would normally be a "for all/this sprite(s)" selector it should say "This list will be available to all sprites."

### Actual Behavior

It says "This *variable* will be available to all sprites":
![image](https://user-images.githubusercontent.com/28599280/65145602-85e11080-da4c-11e9-9659-53c2fb198485.png)

### Steps to Reproduce

1. Go to the Stage
2. Click "Make a list"
3. <br/>![image](https://user-images.githubusercontent.com/28599280/65145647-a0b38500-da4c-11e9-9247-16b7202fe7e0.png)

### Operating System and Browser

Windows 10 OS Version 1809 (Build 17763.737) Chrome 76.0.3809.132 (Official Build) (64-bit)

**Comment by apple502j** [comment]
Duplicate of #4474 (which ST closed by misunderstanding - hey, it says "Go to background")

**Comment by Kenny2github** [comment]
@apple502j I think the misunderstanding was because they didn't realize "background" meant "stage"

**Comment by Kenny2github** [comment]
#4474 was reopened
