### ISSUE TITLE
Feature Request: Can an Existing Project be Loaded by Specifying a URL Parameter?

### ISSUE THREAD

**Issue by CreativeComputerLab** [LLK/scratch-gui#5192]
As a user I would like to be able to open up a scratch project directly by specifying a URL to it.
For example, the current dev environment the URL http://localhost:8601/ opens up a fresh Scratch project. I would like to be able to use the following URL to open up my project:
http://localhost:8601?url=http://localhost:8601/projects/myProject.sb3

The 'myProject.sb3' project file is accessible and served by the web server as given in 'url' parameter in the above URL.
I would like the Scratch 3 IDE to come up with that project loaded.

The url parameter can point to any server from which to load the project, for example:
http://localhost:8601?url=http://someotherserver.org/myProject.sb3

This will enable users to pass URLs to projects which will be quite useful in a collaborative classroom/club setting.

This feature exists in ScratchX 2

I raised this question in the scratch-vm repo but now that I'm more familiar with the code I realize it belongs in this repo.   Link to original question: https://github.com/LLK/scratch-vm/issues/2166

**Comment by apple502j** [comment]
There are two problems:
1) CORS matters in some cases. (Search for CORS)
2) What if the file was invalid or even malicious?

**Comment by CreativeComputerLab** [comment]
Right, then whitelisted URLs can be set to localhost and specified repositories.  I think that's how ScratchX 2 handles this.

**Comment by CreativeComputerLab** [comment]
BTW, I would like to contribute this feature via pull request, however, I need some guidance on the best place in the code to:
	a) Parse the url parameter out of the URL
	b) Pass the url parameter to the requestProjectUpload method in the SBFileUploader component defined in src/containers/sb-file-uploader.jsx

Also, any advice on whether this is the best approach i.e will this solution approved for deployment in the app?

**Comment by apple502j** [comment]
You shouldn't submit PRs without `[help wanted]`tag.

**Comment by AlisaYang** [comment]
> ?sb3url=https://adapter.codelab.club/sb3/Pong_Starter.sb3

@wwj718  Hey. This link doesn't work on the local server. I try to use `http://localhost:8601/?sb3url=https://adapter.codelab.club/sb3/Pong_Starter.sb3` or `http://192.168.xxx:8601/?sb3url=https://adapter.codelab.club/sb3/Pong_Starter.sb3`.  Please give me some help. Thanks.

**Comment by apple502j** [comment]
@AlisaYang The real scratch-gui does not have that.

**Comment by AlisaYang** [comment]
> @AlisaYang The real scratch-gui does not have that.

okay, thanks for your reply.
