### ISSUE TITLE
How to make an extension auto connect ?

### ISSUE THREAD

**Issue by hyansuper** [LLK/scratch-gui#5193]
![Screenshot from 2019-09-20 20-35-09](https://user-images.githubusercontent.com/44317361/65327476-a04ef180-dbe6-11e9-9958-6d73bcbbd594.png)

When I choose an extension, I **don't** want the scan/connect popup to show, is there a way to auto scan and connect ?

In the `src/lib/libraries/extensions/index.js` file, I played with `useAutoScan` and `launchPeripheralConnectionFlow` attributes, setting them `true` or `false`, unable to get what I want.
Is there an `useAutoConnect` attribute or something?

**Comment by apple502j** [comment]
Nope. Currently there is no way to auto-connect.
Not impossible to implement, but consider the case where you have 2 or more connectables.

**Comment by hyansuper** [comment]
In scratch-vm，I put scan() and connect() in constructor. That works
