### ISSUE TITLE
Costume Editing -- Feature Request

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-gui#52]
### Expected Behavior

Should be able to edit costumes.

### Actual Behavior

Functionality not added.

### Operating System and Browser

Ubuntu 16.04, chrome 56.0.2924.76 

I am sure you're already working on this, just adding an issue so I can share our first play test findings / complaints.

**Comment by thisandagain** [comment]
Implementing the paint editor is a huge group of work that we will track in a new repo once we start work.
