### ISSUE TITLE
Creating a variable with the same name as an old one makes a variable that can't be changed

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#520]
### Expected Behavior

Variable setting and incrementing blocks should work

### Actual Behavior

Nothing happens; value stays at 0

### Steps to Reproduce

Create a variable x
Delete the variable x
Create a new variable also named x
Click on the change x by 1 block. Nothing happens.
Set x to block also does nothing

**Comment by thisandagain** [comment]
Needs repro / confirmation.

**Comment by paulkaplan** [comment]
Can no longer repro, was fixed. Closing.
