### ISSUE TITLE
Touchpad taps don't count as clicks on Scratch stage

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#5213]
### Expected Behavior

1. Open a project; e.g., Bouncy Heroes https://scratch.mit.edu/projects/173918262/
1. Set your computer to register touchpad taps as clicks
1. Use touchpad to tap on start button
1. I expect the tap to register as a click

### Actual Behavior

The tap does not register as a click

### Operating System and Browser

Mac: 10.14.5 Chrome Version 76.0.3809.132 (Official Build) (64-bit)
Chromebook: Samsung Chromebook Pro, running ChromeOS 76.0.3809.136 (Official Build) (64-bit)

**Comment by BryceLTaylor** [comment]
Couldn't repro
