### ISSUE TITLE
How to save project code?

### ISSUE THREAD

**Issue by Tsepu** [LLK/scratch-gui#5219]
### Expected Behavior

I am asking this question four times. I implemented scratch-gui in my local. I want to save block programming source code at my database.

### Actual Behavior

https://drive.google.com/file/d/1JO9Yi35GqsabVydYdvpFnJ8YhX6D8cGz/view

If you see above link (this is a video), you will understand the problem. please, do not focus on errors. I just want to know why save button does not work before "load from your computer". 

### Steps to Reproduce

1. Download scratch-gui
2. implement it to Django project

### Operating System and Browser

_Windows 10, 64Bit...., Chrome

**Comment by liyaopinner** [comment]
i am to know that too
