### ISSUE TITLE
Can not edit .mp3 files

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#5221]
### Expected Behavior

You should be able to edit any sound file that you can load into a project.

### Actual Behavior

If you upload an .mp3 file and open it in the sound editor you can select portions of the sound but none of the buttons alter the sound.  You can't alter the whole sound either.  None of these functions do anything:
Faster
Slower
Louder
Softer
Mute
Fade in
Fade out
Reverse
Robot
pressing delete on the keyboard
pressing shift-delete on the keyboard

### Steps to Reproduce

Create a Scratch Project
Click the sounds tab
Choose Upload Sound from the thermometer menu
Upload an mp3 fiile
Note: the sound appears in the editor
Select a portion of the sound
Note: the selection tool selects a region of the sound
Press Delete
Note: nothing is removed from the sound
Click any of the effects buttons
Note: no effects are applied

If you deselect the region and try to apply effects to the whole sound they are not applied.

### Operating System and Browser

Mac Chrome

**Comment by BryceLTaylor** [comment]
It's worth noting that you CAN edit the sounds in the library

**Comment by ericrosenbaum** [comment]
@BryceLTaylor Is this the same as the existing issue with editing long sounds (https://github.com/LLK/scratch-gui/issues/4897)? the sound editor does not let you edit sounds longer than 2min or so. Uploading and editing short mp3s works fine.

**Comment by paulkaplan** [comment]
@BryceLTaylor can you close if @ericrosenbaum's comment is right?
