### ISSUE TITLE
Not able to load file (Creating two entries of stage in project.json)

### ISSUE THREAD

**Issue by iamsush** [LLK/scratch-gui#5225]
### Expected Behavior

I created a file and saved it, it should open when I import it.

### Actual Behavior

While importing the same saved file, it fails with the below error message:
`{
    "validationError": "Could not parse as a valid SB2 or SB3 project.",
    "sb2Errors": [{
        "keyword": "required",
        "dataPath": "",
        "schemaPath": "#/required",
        "params": {
            "missingProperty": "objName"
        },
        "message": "should have required property 'objName'"
    }],
    "sb3Errors": [{
        "keyword": "enum",
        "dataPath": ".targets[2].isStage",
        "schemaPath": "sb3_definitions.json#/definitions/sprite/properties/isStage/enum",
        "params": {
            "allowedValues": [false]
        },
        "message": "should be equal to one of the allowed values"
    }]
}`

Information might help : While trying to resolve the issue, I looked into the project.json file inside sb3 package and it had two entries of stage at target[0] and target[2] with the same name and isStage(true) value. 

### Steps to Reproduce

I am not sure how to reproduce the error, there's some ambiguity in the behaviour as far as I have seen.

### Operating System and Browser

Windows 10, Chrome

**Comment by qomosoloto** [comment]
So, how to solve this problem?I have met this issue too....

**Comment by luke-f-miller** [comment]
@BryceLTaylor this issue was marked as closed last year. Is it resolved? Our instance of scratch-gui is currently experiencing the same issue. Any guidance on a resolution?

**Comment by damianxd** [comment]
I solved this problem by editing the sb3_definitions.json in the following path:
./node_modules/scratch-parser/lib/sb3_definitions.json

Find the isStage lines and change the enum variables to "true,false", like this:
                "isStage": {
                    "type": "boolean",
                    "enum": [true,false]
                },

Here is my file as reference.

[sb3_definitions.json](https://github.com/user-attachments/files/20213011/sb3_definitions.json)

Just remember that this is just a quick patch, shouldn't be used in production and it can surely break something else. But at least you will be able to open your files
