### ISSUE TITLE
loading sb3 file from scratch page itself instead of uploading manually

### ISSUE THREAD

**Issue by PradeepHGK** [LLK/scratch-gui#5247]
### Expected Behavior
loading .sb3 file from scratch page itself instead of uploading manually
_Please describe what should happen_
Need to load predefined sb3 files from scratch page itself without uploading manually 
### Actual Behavior
We need to upload manually
_Describe what actually happens_

**Comment by towerofnix** [comment]
See discussion in https://github.com/LLK/scratch-gui/issues/5192.

**Comment by PradeepHGK** [comment]
> See discussion in #5192.

Thanks for the reply.
i want it in the way, of selecting tutorials in scratch page, in the same way i have to select my mutiple project templates similar to this https://machinelearningforkids.co.uk

is there any existing way in scratch project?
