### ISSUE TITLE
Change List Variable name not updated on stage.

### ISSUE THREAD

**Issue by alexwenbj** [LLK/scratch-gui#5256]
### Expected Behavior

I defined a list called "MyLst",it showed in stage,then I changed this list to "MyList",but the name in variable monitor for this list didn't change, even if I refresh the page.

### Actual Behavior

The variable name in variable monitor should change to the new one.

### Steps to Reproduce
1. Define a list variable, name it "MyLst"
2. Change this variable name to "MyList"
3. Look at the variable name in list monitor on stage.

### Operating System and Browser
 Mac OS 10.15 Chrome 77.0.3865.90

**Comment by towerofnix** [comment]
Duplicate of #4098.
