### ISSUE TITLE
Understanding behavior of blocks in blocks menu vs. workspace

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#528]
During the Catch Game External Playtest, June 2017, we witnessed confusion around the role of blocks in the blocks menu versus blocks in the workspace.

Confusions we saw:
- Do the dropdown menu selections on blocks need to be made when the block is in the blocks menu, or can they be made after it's in the workspace?
- If the dropdown menu on a block is updated in the blocks menu, does that propagate to all instances of the block that are already in the workspace?
- Do the blocks need to be pulled out of the blocks menu "in order", in the order they appear in the stack shown in the cards?
- User expected editing blocks in blocks menu to work with the sprite
- Didn’t understand that the blocks need to be in the workspace, ordered, and connected

For example, a user changed the block menu selection in the block pane, not in the block they had already dragged to the scripting area, then they clicked the block in the scripting area expecting it to use the updated block menu selection.

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#16
