### ISSUE TITLE
Understanding how to start & stop projects, blocks, and stacks

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#529]
Related to several other issues, including https://github.com/LLK/scratch-gui/issues/451.

Observations from Catch Game External Playtest (June 2017):
- User expressed frustration, said “it’s not working”, when clicking the green flag button would not start a stack/ project with no hat block
  - A second user didn't understand that you can click on a block to run it, they went to the green flag button even though there was no green flag block to trigger that stack
- User was reading “when green flag clicked” hat block as “when clicked”
- At least two users asked how to stop their projects
- Users did not initially understand they could click a block in the block menu/ pane or workspace area to run it
  - It seemed to be a bit easier for them to understand clicking it in the block menu/ pane than in the workspace when it wasn't part of a stack
  - Whether a block in the workspace needed to be connected as part of a stack or not seemed to confuse several users

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#15
