### ISSUE TITLE
how to get project from server

### ISSUE THREAD

**Issue by tianxiaobao** [LLK/scratch-gui#5290]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by tianxiaobao** [comment]
now url is : http:kdy.com/?sb3Url=http:xxx.com/123.sb3
i can get project data by
**axios.get('http:xxx.com/123.sb3',{responseType: 'arraybuffer'}).then((data)=>{this.props.loadProject(data)
})**
but the page has default cat

if i write
**axios.get('http:xxx.com/123.sb3',{responseType: 'arraybuffer'}).then((data)=>{
    setTimeout(() =>{
        _this.props.loadProject(data)
    },500)
})**
it is normal

**Comment by BryceLTaylor** [comment]
Please fill out the issue template so we can understand the issue you're seeing.

**Comment by benjiwheeler** [comment]
I'm interested in what this problem was, and if there was any solution. I'm surprised that the setTimeout was necessary, and I wonder if it points to anything broken.
