### ISSUE TITLE
How can I embedded Source Code Scratch UI to my react app?

### ISSUE THREAD

**Issue by HoangHuyLe** [LLK/scratch-gui#5293]
### Expected Behavior

I start learn Reactjs. I create a new app name My-app with Create-react-app and I want to Embed Scratch UI to My-app. Detail, when I put a button on My-app, it route to UI Scratch with Sigle Page App.
### Actual Behavior
It is error when compile JSX in Scratch UI code with JS code in My-app.

### Operating System and Browser
_Win 10

How can I do that

**Comment by apple502j** [comment]
What's your error?

**Comment by HoangHuyLe** [comment]
ok thank for your reply but I have a new Idea.
Now, I want run a Scratch project on my website, like this https://scratch.mit.edu/projects/335217396/
Can you tell me how can I do that.
Please tell me with step by step because I don't know more about JS.

**Comment by apple502j** [comment]
You should learn JavaScript 😛

**Comment by cuixiping** [comment]
1. Open a project page, like https://scratch.mit.edu/projects/350898298/

2. Click the `Copy Link` button

![image](https://user-images.githubusercontent.com/1104492/70957168-35f80100-20b0-11ea-8b75-d72fcb1d1166.png)

3. Copy the embed code and paste into your html code.
![image](https://user-images.githubusercontent.com/1104492/70957255-7e172380-20b0-11ea-9180-f281146b6692.png)

4. That's all.
