### ISSUE TITLE
What does the frog say

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#5294]
Fly goes, "Hello!"
But there's one sound
That no one knows
What does the frog say?

<img width="451" alt="Screen Shot 2019-11-14 at 10 44 53" src="https://user-images.githubusercontent.com/2855464/68872383-f2366400-06cb-11ea-945a-e607501f2872.png">

**Comment by apple502j** [comment]
LOL. Maybe make fly a separate sprite.

**Comment by BryceLTaylor** [comment]
The speech bubble is behaving as expected.  @kosiecki17 @zoebentley We're closing this issue but we should consider this when designing future sprites.
