### ISSUE TITLE
Understanding what to do with a block that is input to another block (e.g. sensing)

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#530]
During the Catch Game External Playtest (June 2017), at least one user had difficulty figuring out what to do with sensing / input blocks. 

They weren't sure how to use them in conjunction with the other blocks. They found the "touching sprite" block and seemed to understand that they wanted something to happen when the two sprites touched, but wasn't sure how to incorporate that input sensing block with their existing stacks.

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#14
