### ISSUE TITLE
Incorrect backdrop index number

### ISSUE THREAD

**Issue by BrightLin** [LLK/scratch-gui#5307]
### Expected Behavior

1 Choose some backdrop images
2 Click the "Backdrops" tab
3 Change current backdrop
4 The stage backdrop index will change.

### Actual Behavior

**Actual the backdrop index is not change.**

See the gif below, the "Stage" is always "Backdrops 5":
![stage image index](https://user-images.githubusercontent.com/15828392/69114117-a7e42700-0abf-11ea-94f0-bf50460caadb.gif)

### Steps to Reproduce

1 Choose some backdrop images
2 Click the "Backdrops" tab
3 Change current backdrop

### Operating System and Browser

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) **Chrome/78.0.3904.70** Safari/537.36

**Comment by apple502j** [comment]
That's not the backdrop id, but the numbers of backdrops available.

**Comment by BrightLin** [comment]
@apple502j  OK. Got it. Thank you

**Comment by paulkaplan** [comment]
Paging @carljbowman just so that he sees this, but thanks for the feedback. Going to close this as `#notabug`
