### ISSUE TITLE
How to find the right block?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#531]
During the Catch Game External Playtest (June 2017), we saw users experience confusion with finding relevant blocks:
- Where to find the "when green flag clicked" hat block
- They had trouble finding the relevant blocks, both when trying to choose the right category and when searching within a category
  - What the names of the categories mean in relation to their blocks' functionality
- Distinguishing blocks which look similar but have different text
  - Difficulty distinguishing the blocks within the block menu/ pane (e.g. "if" vs. "forever") as well as when comparing the blocks in the menu vs. in the cards (trying to recreate a stack)
  - Possibly relating to https://github.com/LLK/scratch-gui/issues/484
- Color/ category confusion when looking at the stacks in the cards vs. trying to find the block on screen, e.g. data vs. control
  - Related to https://github.com/LLK/scratch-blocks/issues/995

**Comment by chooper100** [comment]
A previous suggestion was made to add a search field to the block toolbox, which would help people who struggle finding blocks (the search should work across all block categories)

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#13
