### ISSUE TITLE
Update GUI in Scratch forums

### ISSUE THREAD

**Issue by Nambaseking01** [LLK/scratch-gui#5322]
I was searching for other issues about this, but there aren't. I'm not particularly impatient about this feature, but since this is the GUI repo I thought I'll suggest it to calm some people down. The GUI in the Scratch forums is still in the 2.0 version, so maybe you could do more work on making it 3.0? It would really be nicer for a lot of Scratchers.

**Comment by apple502j** [comment]
Should be moved to LLK/scratch-www

**Comment by Nambaseking01** [comment]
Okay, will move it there. Thanks for the notification.
