### ISSUE TITLE
Color number is hard to understand and does not match the wiki article

### ISSUE THREAD

**Issue by cuixiping** [LLK/scratch-gui#5324]
### Expected Behavior

Color number matches the wiki article "[Computer Colors][1]"

### Actual Behavior

Color number is hard to understand and does not match the wiki article "[Computer Colors][1]"

### Operating System and Browser

It has nothing to do with the operating system and browser version.

### Steps to Reproduce

Set pen color to different number and draw.

![Color values](https://user-images.githubusercontent.com/1104492/70018466-2ad9a700-15c1-11ea-8103-32ce8414ec89.png)

Obviously it does not meet the calculation rules described in the wiki article "[Computer Colors][1]":

![image](https://user-images.githubusercontent.com/1104492/70018660-cf5be900-15c1-11ea-9e72-a5f83dc5e1d3.png)

So I don't know what's the formula from RGB color to Scratch color number.

[1]: https://en.scratch-wiki.info/wiki/Computer_Colors

**Comment by apple502j** [comment]
@cuixiping Try the color picker one - it accepts hex

**Comment by Kenny2github** [comment]
![image](https://user-images.githubusercontent.com/28599280/70106875-c92c4200-167f-11ea-9492-5e39a63e8221.png)

**Comment by cuixiping** [comment]
@Kenny2github That screenshoot may come from old version.
For example, if I want to draw a red line (R=255, G=0, B=0), actually a yellow line is drawn.
The whole code:

![image](https://user-images.githubusercontent.com/1104492/70110518-30e78a80-168a-11ea-8417-4f88cdda7d3f.png)

A red line is expected, but a yellow line is drawn.

**Comment by apple502j** [comment]
![image](https://user-images.githubusercontent.com/33279053/70111703-68f4ca80-1696-11ea-9bf8-0b00ce0a2638.png)
Use this.

**Comment by cuixiping** [comment]
@apple502j  Thank you. I know the color picker feature, but that's a different user case.

**Comment by Kenny2github** [comment]
@cuixiping Actually, my screenshot was taken on the latest development version https://llk.github.io/scratch-gui/develop

What you don't seem to understand is that you can just drag blocks into the COLOR input of the "set pen color" block:
![gif](https://i.gyazo.com/f46f45a8063e80dd15889f7936aef0b1.gif)

**Comment by cuixiping** [comment]
> @cuixiping Actually, my screenshot was taken on the latest development version https://llk.github.io/scratch-gui/develop
> 
> What you don't seem to understand is that you can just drag blocks into the COLOR input of the "set pen color" block:
> ![gif](https://camo.githubusercontent.com/3582feae3b0430142cb4bfdafbd69e1f047e974a/68747470733a2f2f692e6779617a6f2e636f6d2f66343666343561383036336538306464313538383966373933366165663062312e676966)

Thank you very much. I really didn't know this skill before you point out.

**Comment by Kenny2github** [comment]
You can close it yourself - there's a "close issue" button next to "comment"
