### ISSUE TITLE
What should happen when sprite size is set to 0%?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#533]
A user asked this during the Catch Game External Playtest (June 2017). When they tried it, it didn't seem to be different from setting the sprite size to 1% - it made the sprite super tiny, but not invisible.

Setting to size 0% should maybe make the sprite vanish? I'm not sure! But I thought it was a good question. : )

**Comment by liam4** [comment]
Setting the size to 0% *would* make the sprite vanish, but [the size of a sprite is limited in a range](https://github.com/LLK/scratch-vm/issues/255). So, using the "set size to 0%" block doesn't *actually* set the sprite's scale property to 0; instead it sets it to some small number, for example, with the scratch cat costume, 5%:

<img width="391" alt="Set size to 0%; size becomes 5%" src="https://user-images.githubusercontent.com/9948030/28080440-01aac8ac-663a-11e7-9564-6233c2a81551.png">

**Comment by chooper100** [comment]
Allowing the size to be set to 0% could also lead to users losing their sprites (in the same way that sprites aren't allowed to move off stage)

(I say this as I presume remembering to change the size back to 100 is less intuitive then just clicking the show block)

**Comment by chooper100** [comment]
It would be nice to have minimum size at 1% rather than 5% - this allows for smoother animations when hiding sprites by decreasing their size

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#12
