### ISSUE TITLE
Clarify "language" block in Translate extension?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#5340]
Using the translate extension, I found it hard to understand what the "language" reporter did. It might be clearer if its text was "my language" or "user's language".

**Comment by apple502j** [comment]
It was `viewer language` before: LLK/scratch-vm#1190
@ericrosenbaum you created that issue :D

**Comment by GrahamSH-LLK** [comment]
I think "user's language" works well
