### ISSUE TITLE
In Translate extension, add reporter or menu item for choosing a random language

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#5341]
It's fun to be able to pick a random language sometimes! But this is hard for users to do.

Maybe we could add a "random language" reporter, or a "random language" menu item in the languages dropdown menu?

Somewhat related: https://github.com/LLK/scratch-gui/issues/2249

**Comment by apple502j** [comment]
Duplicate of LLK/scratch-vm#1189

**Comment by benjiwheeler** [comment]
Thanks, @apple502j
