### ISSUE TITLE
Difficulty with re-ordering blocks

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#535]
Encountered during the Catch Game External Playtest (June 2017).

Users had difficulty combining stacks & reordering blocks in stacks. Sometimes the blocks connect & disconnect in what seems to be an unexpected way.

For example, one user ended up saying “I need to start all over” because their blocks got out of order as they tried to combine two stacks. This caused behaviour they didn't understand, and so they deleted the sprite (and thus all their scripts).

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#11
