### ISSUE TITLE
On Safari, sound editor can start sound with no way to stop it

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#5350]
### Expected Behavior

It should never be the case that Scratch is playing a sound with no way at all to stop the sound, except for e.g. refreshing the page or quitting the browser.

### Actual Behavior

It is possible to get into a state where a minute-plus long sound file is playing, and there is no way to stop it. 

### Steps to Reproduce

- Use Mac Safari
- Load a project with a long but still editable sound (say, over 60 seconds, but under 113 seconds, so it's under the edit limit)
- Open the sound editor
- Click the robot effect button, then immediately switch away from the sound editor to the "costumes" or "code" tab
- The sound will then start, and there's no way to stop it, aside from refreshing the page or quitting the browser.

### Operating System and Browser

Mac OS 10.13.6 Safari 13.0.4

**Comment by rschamp** [comment]
(This seems to have been fixed!)
