### ISSUE TITLE
how to load sb3 files from web URL?

### ISSUE THREAD

**Issue by nonicknamelala** [LLK/scratch-gui#5351]
I want to build a site to share the scratch project on web, but I do not know how to load the sb3 files from the web URL location.  if that could be loaded on web , how to automatically maximize the play window ? thank you!

**Comment by benjiwheeler** [comment]
You'll need to find a place online to host your sb3 files, then find the places in this project's project-fetcher-hoc and project-saver-hoc files that find and create/update the sb3 files; note that the project assets will also need to be stored somewhere. Also look at sb-file-uploader and sb3-downloader.

As for maximizing the play window, you can pass the `isFullScreen` prop to the <GUI> component.
