### ISSUE TITLE
Using the mouse to drag sprites on the stage as a thought process

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#536]
During the Catch Game External playtest (June 2017), we saw (at least) a couple of users trying to drag the "catcher" or "catchee" sprite (apple or whatever sprite they had chosen) to simulate the action the user wanted to happen. I saw the user doing this while/ before constructing the relevant stack of blocks.

The users also returned to dragging the catcher sprite around to catch the catchee even after they had added the stacks that control the catcher via left/ right arrows. There seemed to be something easier to understand/ remember/ relate to with using the mouse rather than using the arrow keys (they sometimes forgot how that part of the program worked).

Since one of the reasons we have sprites is to capitalize on body-syntonicity to make it easier for users to understand how their program works, I wonder if there is some way we can use or support this impulse (to physically work out the algorithm while/ before coding it using the mouse & sprites on the project stage) in order to yield insights about the blocks.

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#10
