### ISSUE TITLE
Menus should not close themselves on mouseup, if mouse is in a modal

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#5363]
In the course of addressing https://github.com/LLK/scratch-gui/issues/4762 and creating the PR https://github.com/LLK/scratch-gui/pull/4809 , it became clear that our menu bar menus were closing themselves too aggressively.

They currently close if there is any mouseup which occurs outside the menu. But if there is a modal open, that modal (and the entire ReactModalPortal) is in the foreground, and the menu is in the background -- the menu should ignore clicks until it is in the foreground again.

**Comment by apple502j** [comment]
Not modal, but #3365 is a similar case. See also #5318

**Comment by benjiwheeler** [comment]
Closing in favor of https://github.com/LLK/scratch-gui/issues/4907
