### ISSUE TITLE
Going to Sound & Costumes tabs to change the sounds & costumes

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#537]
During the Catch Game External playtest (June 2017) we saw (at least) a couple of users going to the Sounds tab or Costumes tab when they wanted to change the sounds or costumes in the project (respectively).
- When one of the users wanted to change what sound was playing in the project, they went to the Sounds tab to look for the relevant blocks.
  - They looked in Sounds tab for “Play sounds” block.
- When one of the users wanted to change the costume that the sprite was displaying as, they went to the Costumes tab.
  - They clicked the other costumes in the tab expecting to see that reflected in the sprite on the stage.
  - When that didn't work, they were confused.
  - They did not realize they could look in "Looks" to change the costume.

**Comment by chooper100** [comment]
In Scratch 2.0 (and I'm pretty sure in 1.x) it is possible to change the sprite costume by clicking on the costumes in the costume tab.

I think it would be good to carry this feature forwards to 3.0

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#9
