### ISSUE TITLE
Using video sensing doesn't work while on a video call on Windows 10 

### ISSUE THREAD

**Issue by Yezzle** [LLK/scratch-gui#5378]
### Expected Behavior

Showing the video at the stage area when adding the video sensing module
### Actual Behavior
there is nothing heppened on stage area(means you can see backgrounds and sprites but no video) and the console show an error:
![image](https://user-images.githubusercontent.com/29877797/72132686-849c7080-33ba-11ea-9ece-62b8119f8046.png)

_Describe what actually happens_
This seems to happen when there is another page using the code like `navigator.mediaDevices.getUserMedia`, In my website, I used a live room to myself to others and share with my desktop.  This gose well on notebooks but not good on a desktop computer
### Steps to Reproduce
this is easy to reproduce , you need to find a live room page and open the scratch ide page on a desktop computer
_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser
Win10 and the browser is google 79.0.3945.117(latest version)
_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by BryceLTaylor** [comment]
I was not able to reproduce this issue on Chrome 97 using Windows 10 while on a google meet video call.
