### ISSUE TITLE
Can you cut a script and paste it to another program, like Word?

### ISSUE THREAD

**Issue by dging10** [LLK/scratch-gui#5380]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by dging10** [comment]
I want to copy a script so that I can paste it in Word. Is there a way to do this? I know I can duplicate and move it to other sprites. But can a paste to other programs? Thanks.

**Comment by apple502j** [comment]
You can take a screenshot: On Windows, use SnippingTool. If you use Firefox, it has built-in screenshot feature too, so you can also use that.
