### ISSUE TITLE
Do users understand the significance of the block order, sequential execution, & connection?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#539]
We've seen confusion like:
- Users aren't sure when to start a new stack vs. when to add to an existing stack
- Users don't realize they can drop a single block into the workspace and click it to execute it
  - Either executing it by clicking it in the block menu/ pane, or adding it to a stack and executing the whole thing even if they're only interested in the effect of that single block
- Users ask questions indicating confusion about block order when block order isn't important
- Users sometimes don't seem to understand that blocks execute sequentially

For example, one user during the Catch Game External Playtest (June 2017):
- User was not sure how to add a block to the program
  - They wanted to change the sprite size
  - Once they found the block, they were not sure what to do with it
  - They asked whether it should go “in the forever?”
  - They asked “before or after” the change y position block (although order doesn’t really matter)

Another example: one user always added new blocks to an existing stack with a hat block at the top (based on the examples in the cards), no matter what they were trying to do (even if they just wanted to execute that one block). They didn't seem to understand that the blocks didn't need to be connected to a stack.

These confusions make me wonder if users - especially New Scratchers, without previous programming exposure - get any information out of the "stack" and "connection" aspects of how Scratch is displayed. Does it convey that blocks are executing sequentially? Is the role of hat blocks as a "trigger" for the stack to execute conveyed? Do the roles of stacks vs. individual blocks seem to have any significance?

Related: https://github.com/LLK/scratch-gui/issues/535, https://github.com/LLK/scratch-gui/issues/529, https://github.com/LLK/scratch-gui/issues/528.

**Comment by jwzimmer** [comment]
During the Extension Categories External Playtest (8/3/17), we saw confusion around:
Sequential execution, how to run a block, what is the relationship between sprites & blocks
  - Hat blocks: you need a block to start these other blocks
  - Users using the Speech extension > speak block, then setting the voice block, indicating they weren't clear on the sequential execution of the stack
    - This is also the order of those blocks in the block menu for the Speech extension
  - That they could have multiple stacks of blocks was not clear. Had to be ‘okayed’ by facilitator
    - Could this be solved by resources/onboarding? Maybe some examples that show the multiple stacks? (Although our demo projects did have multiple stacks, if I recall correctly.)
  - More visible stack highlighting seems like it might help clarify the when execution happens

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#7
