### ISSUE TITLE
Iterating through every block in one frame

### ISSUE THREAD

**Issue by caxapexac** [LLK/scratch-gui#5390]
How to iterate through every block? I have already added my custom extension block but I want to do custom logic on pressing "generate c code for arduino" button.

**Comment by apple502j** [comment]
Scratch and Arduino will not do well without some modifications; Broadcasts and clones will be hard to implement in C. Also, the "Block to Code" feature from Blockly is removed in scratch-blocks. If you can access Blocks object in VM(Sprite has blocks attr), and can parse the weird AST of Scratch yourself, then possibly!

You can use getScripts, and then add getNextBlock to the stack. Maybe something like:
```js
const blocks = sprite.blocks;
const scriptStacks = blocks.getScripts().map(blockId => [blockId]);
scriptStacks.forEach(stack => {
  let next;
  while (next = blocks.getNextBlock(stack.slice(-1)[0])) { // last item of array
    stack.push(next);
  }
});

**Comment by caxapexac** [comment]
@apple502j thanks you, there is no problem broadcasting data to arduino, I just need to convert blocks to text source code.

Where is `sprite` property located?

**Comment by apple502j** [comment]
Depends on what sprite you're looking for - list of sprites? (`vm.runtime.targets`) the sprite the user is editing? (`vm.editingTarget)

**Comment by caxapexac** [comment]
@apple502j thank you very much, it almost works)
