### ISSUE TITLE
Color picker result inaccurate

### ISSUE THREAD

**Issue by JinXJinX** [LLK/scratch-gui#5394]
### Expected Behavior

when the color is 0, 0, 88 (Color, Saturation, Brightness)

the color picker should return 0, 0, 88

### Actual Behavior

the color picker return 0, 0, 89

### Steps to Reproduce

1. draw a rectange on backdrop, fill in this color:

Color: 0 
Saturation: 0 
Brightness:89
![image](https://user-images.githubusercontent.com/12160296/72910796-0bc8dd00-3d07-11ea-9bf6-8de340cf9c8f.png)

2. click sprite, and add a "touching color ... ?" block
![image](https://user-images.githubusercontent.com/12160296/72911553-441ceb00-3d08-11ea-91c4-135cfa1c01da.png)

3. use the block's color picker at the bottom
![image](https://user-images.githubusercontent.com/12160296/72911634-657dd700-3d08-11ea-9ae6-f5b121d001ae.png)

4. select the gray backdrop
![image](https://user-images.githubusercontent.com/12160296/72911661-6dd61200-3d08-11ea-8627-feb2c661c3c7.png)

5. the result you will get is:

Color: 0 
Saturation: 0 
Brightness:88
![image](https://user-images.githubusercontent.com/12160296/72911762-93fbb200-3d08-11ea-9904-ca72161f983e.png)

example project: https://scratch.mit.edu/projects/361565131/
and a gif
![Untitled-74 on Scratch](https://user-images.githubusercontent.com/12160296/72912274-67946580-3d09-11ea-98d4-716dfdab82c2.gif)

### Operating System and Browser

Mac OS 10.15.2
Chrome 79

### More Info

I had tried other brightness numbers, like 0, 0, 87 and lower, or 0, 0, 90 and higher.

this bug only happens with the color 0, 0, 88, and 0, 0, 89

and it doesn't happen every time...

**Comment by BryceLTaylor** [comment]
Thanks for the report.  You're right that it doesn't get the same number, but since we don't use that much precision in the touching color block, it should not affect the behavior of the block.  It should still find that color.
