### ISSUE TITLE
New Sprite Not Always Visible

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-gui#54]
### Expected Behavior

After selecting new sprite, said sprite should appear.

### Actual Behavior

Works sometimes, but not always. Eg. apple doesn't load.

### Steps to Reproduce

Start blank project, click new sprite, click apple.

### Operating System and Browser

Ubuntu 16.04, chrome 56.0.2924.76

**Comment by tmickel** [comment]
(as a hint, looks like in at least the apple case, you can get it to show by running "next costume")

**Comment by SillyInventor** [comment]
So this occurs when the costume in the sprite doesn't have a resolution. Not having a resolution causes it to fail in getting x & y location in RenderedTarget.prototype.updateAllDrawableProperties. This doesn't fail in set costume, because there is already a check. Easiest fix is to put a check in updateAllDrawableProperties.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-vm#484
