### ISSUE TITLE
"If" vs. "Forever > If" - can we make it clearer that "if" needs to be wrapped in "forever" if you want the stack to trigger every time the statement is true?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#540]
During the Catch Game External Playtest (June 2017), at least one user didn’t realize they needed to wrap their if statement in a forever statement to get the stack inside the if statement to trigger every time the if statement was true.

I have seen other users run into this same issue, so I was wondering if we could make this paradigm clearer or easier to discover?

**Comment by mrjacobbloom** [comment]
In 1.4 there was a "Forever If <>" block, although personally it caused more confusion for me than it solved

https://wiki.scratch.mit.edu/wiki/Forever_If_()_(block)

**Comment by jwzimmer** [comment]
thanks @mrjacobbloom 👍

**Comment by Kenny2github** [comment]
@jwzimmer so should this be closed?

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#5

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#6
