### ISSUE TITLE
Problems with floating point errors

### ISSUE THREAD

**Issue by YuzhenQin** [LLK/scratch-gui#5404]
### Expected Behavior

The long floating point numbers set in variables have errors after restart

### Actual Behavior

The long floating point numbers set in variables have errors after restart

### Steps to Reproduce

1.start scratch  
2.**create a variable**  
3.**set it to a long float number**  
4.restart scratch
5.**check the float number in the variable**

### Operating System and Browser

Scratch-gui on Scratch-www,Windows 10,Chrome

**Comment by YuzhenQin** [comment]
It needs to use high precision

**Comment by adroitwhiz** [comment]
All JavaScript numbers are double-precision floats. There's no way to add more precision.
