### ISSUE TITLE
when exporting a character from the website's Scratch editor, and then back to the work page, the browser will malfunction as above 

### ISSUE THREAD

**Issue by YuzhenQin** [LLK/scratch-gui#5413]
### Expected Behavior

I found that when exporting a character from the website's Scratch editor, and then back to the work page, the browser will malfunction as above (not only Google Chrome), refreshing, restarting the browser or computer is also useless, and swallowed more than once . Please be able to fix this small bug. Thank you.

### Actual Behavior

I found that when exporting a character from the website's Scratch editor, and then back to the work page, the browser will malfunction as above (not only Google Chrome), refreshing, restarting the browser or computer is also useless, and swallowed more than once . Please be able to fix this small bug. Thank you.

### Steps to Reproduce

I found that when exporting a character from the website's Scratch editor, and then back to the work page, the browser will malfunction as above (not only Google Chrome), refreshing, restarting the browser or computer is also useless, and swallowed more than once . Please be able to fix this small bug. Thank you.

### Operating System and Browser

Google chrome 79/80,Edge,Edge Dev 81,Chromium,Firefox

**Comment by BryceLTaylor** [comment]
Can you elaborate on the steps you followed to see this issue and include screenshots or a gif?
