### ISSUE TITLE
When I draw a sprite, hold shift to draw a straight line but the stage does not have this straight line.

### ISSUE THREAD

**Issue by qm88888888** [LLK/scratch-gui#5414]
### Expected Behavior

stage  have a  straight line. 

### Actual Behavior

stage don't  have a  straight line.

### Steps to Reproduce

hold shift and draw a straighe line.
![image](https://user-images.githubusercontent.com/18499175/73716264-78a19580-4751-11ea-88e5-94a618018941.png)

### Operating System and Browser

Win10 64 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

**Comment by towerofnix** [comment]
Can repro - it doesn't matter whether the line is drawn horizontally or vertically, nor the weight/diameter of the line. Drawing other shapes anywhere else in the shape makes the line appear.

I tried copying the line and pasting it, which placed it diagonally offset a few pixels (per normal copy behavior). This made the full costume appear on-stage. Then, I shifted it to be in the same cross-axis position (i.e. immediately behind the original line), and the costume promptly disappeared on-stage.

My guess is that it's looking for the bounding area of the costume to be non-zero before rendering it, and it fails to consider the diameter of a line's stroke, treating it as a single 0-by-length shape.

**Comment by adroitwhiz** [comment]
This is another instance of the bug fixed by https://github.com/LLK/scratch-svg-renderer/pull/85.

I've also noticed a lot of Bugs and Glitches posts related to said bug, but haven't taken the time to compile them all yet.

**Comment by qm88888888** [comment]
> Can repro - it doesn't matter whether the line is drawn horizontally or vertically, nor the weight/diameter of the line. Drawing other shapes anywhere else in the shape makes the line appear.
> 
> I tried copying the line and pasting it, which placed it diagonally offset a few pixels (per normal copy behavior). This made the full costume appear on-stage. Then, I shifted it to be in the same cross-axis position (i.e. immediately behind the original line), and the costume promptly disappeared on-stage.
> 
> My guess is that some code is looking for the bounding area of the costume to be non-zero before rendering it, and it fails to consider the diameter of a line's stroke, treating it as a single 0-by-length shape.

thanks.

**Comment by qm88888888** [comment]
> This is another instance of the bug fixed by [LLK/scratch-svg-renderer#85](https://github.com/LLK/scratch-svg-renderer/pull/85).
> 
> I've also noticed a lot of Bugs and Glitches posts related to said bug, but haven't taken the time to compile them all yet.

thanks.
