### ISSUE TITLE
Scratch GUI is broken in High Sierra BETA Safari

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-gui#542]
### Actual Behavior

I have the new High Sierra because I am a developer and I noticed that the new PR that was just merged broke Scratch GUI for me (and other things).

Stage is completely black.
![screen shot 2017-07-13 at 11 42 00 am](https://user-images.githubusercontent.com/10731781/28175051-2790bb2a-67c1-11e7-9fb2-7d27159cc37e.png)

"+" buttons are unresponsive.
Page is slow to load (3-5 seconds each time)
Blocks, Costumes, and Sound tabs are unresponsive 
Flag and stop are unresponsive 

### Expected Behavior

This stuff should work...

### Steps to Reproduce

Load Scratch GUI in High Sierra in Safari.

### Operating System and Browser

Mac OS 10.13 Beta
Safari

**Comment by CosmicWebServices** [comment]
Just noticed I forgot console errors

```
TypeError: this.audioContext.createStereoPanner is not a function. (In 'this.audioContext.createStereoPanner()', 'this.audioContext.createStereoPanner' is undefined)

Unhandled Promise Rejection: NotAllowedError (DOM Exception 35): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

and image:

![screen shot 2017-07-13 at 4 22 53 pm](https://user-images.githubusercontent.com/10731781/28186005-928ff53c-67e7-11e7-9519-7721d974e6ac.png)

**Comment by liam4** [comment]
I believe that the same error happens in regular (Sierra) Safari as well, as noted in LLK/scratch-audio#52.

**Comment by CosmicWebServices** [comment]
@liam4 I have not tested it

**Comment by Kenny2github** [comment]
@CosmicWebServices you seem to have switched around "Actual Behavior" and "Expected Behavior" in the OP.

**Comment by CosmicWebServices** [comment]
@Kenny2github 🤦‍♂️
