### ISSUE TITLE
Project state not correctly re-initialized when loading from ID

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#544]
### Expected Behavior

If a variable is deleted from a project, its monitor should also disappear.

### Actual Behavior

Well, I accidentally activated the "back" Chrome browser function on my 3.0 project via my trackpad, so the page refreshed to an apparently older state of the project (the starting state I think, since I loaded it from 2.0 project 166705236). I added a new variable to replace the one that had gotten deleted on "back", and noticed that now 2 monitors were on the stage, for the old & new variable, although I could not find the old variable in the dropdown menus or in the Data section for any sprite or the backdrop.

<img width="317" alt="screen shot 2017-07-13 at 4 54 46 pm" src="https://user-images.githubusercontent.com/1320456/28187363-7c8a3e64-67ec-11e7-9bb7-89b544e9e6e4.png">
<img width="1280" alt="screen shot 2017-07-13 at 4 51 46 pm" src="https://user-images.githubusercontent.com/1320456/28187364-7c8d7d68-67ec-11e7-996d-fc0e4a9e319a.png">

### Operating System and Browser

_Mac OS El Capitan, Chrome 59_

**Comment by jwzimmer** [comment]
When I refreshed my project (by refreshing the tab I had opened Scratch 3.0 in) today, the sprites, backdrops, and script all disappeared, as if it were a new project, but the two variable monitors remained on the stage.

There were errors in the console, most notably:

```
Uncaught TypeError: Cannot read property 'postSpriteInfo' of null
    at VirtualMachine.postSpriteInfo (gui.js:22789)
    at Stage.onMouseMove (gui.js:74224)
    at HTMLDocument.wrapper (gui.js:2861)
```

```
Uncaught (in promise) Error: Variable "undefined" is already in use and its id is "-[v1BPTf`,bA:O5jYNU$" which conflicts with the passed in id, "isw8W?:7WjC)([st`g:O".
    at Blockly.VariableMap.createVariable (gui.js:105177)
    at Blockly.WorkspaceSvg.Blockly.Workspace.createVariable (gui.js:105188)
    at Blockly.WorkspaceSvg.createVariable (gui.js:105496)
    at Object.Blockly.Xml.domToVariables (gui.js:105447)
    at Object.Blockly.Xml.domToWorkspace (gui.js:105442)
    at Blocks.onWorkspaceUpdate (gui.js:71984)
    at VirtualMachine.wrapper (gui.js:2861)
    at VirtualMachine.EventEmitter.emit (gui.js:44496)
    at VirtualMachine.emitWorkspaceUpdate (gui.js:22734)
    at gui.js:22408
```

```
Uncaught Error: Variable "undefined" is already in use and its id is "-[v1BPTf`,bA:O5jYNU$" which conflicts with the passed in id, "isw8W?:7WjC)([st`g:O".
    at Blockly.VariableMap.createVariable (gui.js:105177)
    at Blockly.WorkspaceSvg.Blockly.Workspace.createVariable (gui.js:105188)
    at Blockly.WorkspaceSvg.createVariable (gui.js:105496)
    at Object.Blockly.Xml.domToVariables (gui.js:105447)
    at Object.Blockly.Xml.domToWorkspace (gui.js:105442)
    at Blocks.onWorkspaceUpdate (gui.js:71984)
    at VirtualMachine.wrapper (gui.js:2861)
    at VirtualMachine.EventEmitter.emit (gui.js:44496)
    at VirtualMachine.emitWorkspaceUpdate (gui.js:22734)
    at VirtualMachine.setEditingTarget (gui.js:22674)
```

<img width="1280" alt="screen shot 2017-07-14 at 11 28 32 am" src="https://user-images.githubusercontent.com/1320456/28218907-0d1aaacc-6888-11e7-9e76-de3f446ba74f.png">
<img width="1280" alt="screen shot 2017-07-14 at 11 28 25 am" src="https://user-images.githubusercontent.com/1320456/28218906-0d171ac4-6888-11e7-89d0-f3c3ca36b51d.png">
<img width="1275" alt="screen shot 2017-07-14 at 11 27 18 am" src="https://user-images.githubusercontent.com/1320456/28218908-0d1b6174-6888-11e7-819d-4e8537c3fd6f.png">

**Comment by jwzimmer** [comment]
I can repro the deleted variable's monitor remaining on stage, but I'm not able to repro the errors in the console.

To repro:
- Load project 147710357 in the GUI
- Go to Data and check off the variable monitors so they appear on stage
- Use the mac keyboard to swipe back a page or use the Chrome browser back button
- Note that project data clears except the monitors on the stage

<img width="1280" alt="screen shot 2017-08-23 at 10 38 07 am" src="https://user-images.githubusercontent.com/1320456/29621993-3ac2912e-87f0-11e7-96e9-f4f9516605f8.png">

I can also add new variables with the same names as the variable monitors already visible on stage.

<img width="1280" alt="screen shot 2017-08-23 at 10 39 38 am" src="https://user-images.githubusercontent.com/1320456/29621994-3ac4e9ec-87f0-11e7-92a9-4af70370927d.png">

Repro'd on https://llk.github.io/scratch-gui/, Chrome Version 60.0.3112.78 (Official Build) (64-bit), Mac OS El Capitan

**Comment by paulkaplan** [comment]
So this is a problem with the project ID loading from a hash, not really with variables or monitors. I think we might want to backlog this because of that.

**Comment by paulkaplan** [comment]
I'm going to backlog this and update the title to reflect the way it is related to correctly re-initializing project state when loading from an ID.
