### ISSUE TITLE
Default text in sensing and operator blocks always loads in English

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#5445]
### Expected Behavior

When the editor loads in a different language (e.g. due to browser language setting), the default text on the `ask` and text operator blocks should be translated.

### Actual Behavior

The default text is in English. Here's an example with the editor loading in Spanish:
![screen shot 2018-12-17 at 9 33 31 am](https://user-images.githubusercontent.com/399209/50093625-39c41f80-01df-11e9-81e3-254aa8ead678.png)
![screen shot 2018-12-17 at 9 33 53 am](https://user-images.githubusercontent.com/399209/50093631-3d57a680-01df-11e9-8bc9-2a7bc58494df.png)

If you switch to another language, they are translated when the new language loads. Here's the same blocks after switching to Italian:
![screen shot 2018-12-17 at 9 37 52 am](https://user-images.githubusercontent.com/399209/50093764-8f003100-01df-11e9-9fc4-bfe29a9ae692.png)
![screen shot 2018-12-17 at 9 38 15 am](https://user-images.githubusercontent.com/399209/50093773-932c4e80-01df-11e9-848a-2daaceef5f55.png)

And if you go back to Spanish afterwards, the default text **is** translated.

### Steps to Reproduce
Load the editor in a language other than English, either by setting the language in the browser, or by adding `?locale=es` to the URL to set the language (replace `es` by any language code).

**Comment by benjiwheeler** [comment]
@smrman Thanks for the suggestion!

**Comment by chrisgarrity** [comment]
@benjiwheeler @Smrman the blocks are fine - as demonstrated by the fact that you can switch languages and switch back. The issue is in the gui initialization of the blocks, that's why the issue is filed here.
