### ISSUE TITLE
Assets not saved/found in server unless used first in scratch.mit.edu

### ISSUE THREAD

**Issue by raquelhortab** [LLK/scratch-gui#5466]
I'm quite new to this so pardon me if my questios are obvious or if I didn't fully undestand how this project works.

### Expected Behavior

Assets should be uploaded to the assets server and be available when opening a serialized project afterwards

### Actual Behavior

When importing assets (eg. images as costumes) in a locally run scratch app, they are not found when the project is opened again. (using serialized object: `state.scratchGui.vm.loadProject(JSON.parse(e.data.serialized))`)

### Steps to Reproduce

We are using our own scratch server in our website, we access it through an iframe. I modified gui.jsx to be able to send the serialized project to our rails server (and receive from) using javascript's postMessage (see [this](https://github.com/LLK/scratch-gui/commit/8b98957b5fa3a703c46972757eba8c31663b6dd4) commit). 

If I don't use any custom images, the project is imported as expected. However, if I upload images as costumes those are not found when I open the project again and scratch is not loaded correctly, the stage is blank and the costumes folder too:

![image](https://user-images.githubusercontent.com/19463905/74811824-95fa6600-52f2-11ea-88fd-8f4a058931e4.png)

The errors shown in the javascript console are the following:
![image](https://user-images.githubusercontent.com/19463905/74812466-dd352680-52f3-11ea-8a4a-8b35e993d84f.png)

The thing is, they are found and everything is loaded correctly if I have already used those images in some project in the editor in scratch.mit.edu.

My guess was that maybe we need to have our own assets server although this is not documented and the assetsHost in storage.js defaults to https://assets.scratch.mit.edu. I know that if export/import it as an sb3 it would have all the assets, but a serialized version of the project is much easier to send and store to our rails app. Also I guessed that if there's (or there can be) an assets server we shouldn't need to import the image file everytime. 

I'd really appreciate if someone could point me to the right direction on what to do here. Thanks.

### Operating System and Browser

Ubuntu 18.04.3 LTS, Google chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by apple502j** [comment]
First of all, you have wrong code. You don't import modules like that (and it may fail).
Second, yes, you need to have the asset server.

**Comment by raquelhortab** [comment]
> First of all, you have wrong code. You don't import modules like that (and it may fail).
> Second, yes, you need to have the asset server.

I am well aware of the imports, this have already been fix in another brach I am currently working on.

Is there any documentation on how such server should be or how the assets are sent? It feels like it is so easy to host your own scratch app server but there's no info on how to set up an assets server.

**Comment by apple502j** [comment]
It should accept 2 requests: POST `/<asset-name-with-extension`>, GET `/internalapi/asset/<asset-name-with-extension>/get/`

**Comment by raquelhortab** [comment]
Thanks!
