### ISSUE TITLE
NPM Encountered error while compiling (translated)

### ISSUE THREAD

**Issue by 368573607** [LLK/scratch-gui#5473]
# npm编译的时候遇到错误
在运行的时候，没有问题，可以正常运行，可是一执行”npm run buiud“就报错，报错信息如下：
```node.js
npm ERR! missing script: dev

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2020-02-25T08_44_29_079Z-debug.log
```
希望各位大佬解答，我本人只是一个Node.js的小白`

**Comment by BryceLTaylor** [comment]
Translated using Google Translate:
Title: NPM Encountered error while compiling
When running, there is no problem and it can run normally, but as soon as "npm run buiud" is executed, an error is reported. The error message is as follows:
