### ISSUE TITLE
Miscounting delete blocks

### ISSUE THREAD

**Issue by mdave16** [LLK/scratch-gui#550]
Imagine having a few blocks out and wanting to delete all. You right click and the option says "delete x blocks", but you click it and a popup says "delete y blocks?" 
### Expected Behavior

x == y

_Please describe what should happen_

the number should stay the same

### Actual Behavior

_Describe what actually happens_

the counter counts blocks without input like "forever" as 1 and each input as an extra 1, e.g. 2 mod blocks will give the message "delete 6 blocks?" 

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

take out multiple blocks on any sprite and then right click and select the delete option

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

Ubuntu 16.04 LTS
mem 3.7 GiB
Proc: Intel Core i3-4010U CPU @ 1.70GHz x 4
Graphics Intel Haswell Mobile
OS type:: 64-bit
Disk 365.0 GB
Browser Mozilla Firefox 54.0 (64 bit) 
Mozilla Firefox for Ubuntu canonical - 1.0

**Comment by mdave16** [comment]
not entirely sure this is the right repo for this error, but i can move it later.

**Comment by rschamp** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/978
