### ISSUE TITLE
Dragging a sprite briefly causes a duplicate sprite to be visible

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-gui#5509]
### Expected Behavior

When you drag a a sprite in the editor, it should appear as though the sprite has moved immediately to your mouse cursor.

### Actual Behavior

When you start and stop dragging a sprite in the editor, a duplicate of it is briefly visible:
![Peek 2020-03-12 11-48](https://user-images.githubusercontent.com/25993062/76539746-897fae00-6457-11ea-9f9e-bbe27a73c054.gif)

### Steps to Reproduce

1. Enter the editor
2. Drag a sprite around

### Operating System and Browser

Fedora Linux, Firefox 73

**Comment by GrahamSH-LLK** [comment]
It's not as dramatic for me, but it still happens on Chrome OS Chrome 81.
