### ISSUE TITLE
Say block rounding is inconsistent with Scratch 2

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#5512]
### Expected Behavior
Say (.009/1) says .009 in scratch 2

### Actual Behavior
Say (.009/1) says .01 in scratch 3

### Steps to Reproduce
Use say and divide operator blocks

### Operating System and Browser
All

/cc @kchadha @BryceLTaylor

**Comment by adroitwhiz** [comment]
I don't think my PR introduced this; [2.0 just does some weird things](https://github.com/LLK/scratch-flash/blob/develop/src/scratch/ScratchSprite.as#L579).

**Comment by fsih** [comment]
Yeah, this is for the bug with the say block that already exists prior to your PR. We noticed it while testing your PR.

**Comment by fsih** [comment]
The proposed fix is to fix forward by copying Scratch 2's behavior, which is to not round say/think bubbles to 2 decimal points when the number is < .01

**Comment by adroitwhiz** [comment]
Are there any projects that will break if the behavior is different? The 2.0 behavior seems somewhat confusing in my opinion. Displaying extra precision for small numbers makes sense, but always rounding to 2 decimal points when 1 would suffice seems a bit weird.

**Comment by fsih** [comment]
Sorry, to clarify, we're planning to not round to 2 decimal points when the number is < .01, and not copy any of the other 2.0 behavior for now.
