### ISSUE TITLE
'touch' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by BoomerScratch** [LLK/scratch-gui#5530]
### Expected Behavior

I was reading the guide on how to publish to github pages, and it said you need to run `npm run deploy`

### Actual Behavior

When i did that, it said: `'touch' is not recognized as an internal or external command, operable program or batch file.`, with some other errors. I did run `npm run build`.

### Steps to Reproduce

I don't think you can reproduce this; it happens on my computer. I don't know if this happens on other computers.

### Operating System and Browser

OS: Windows 10, browser not needed.

**Comment by apple502j** [comment]
Maybe you can run `npm install touch-cli -g`.

**Comment by BoomerScratch** [comment]
> Maybe you can run `npm install touch-cli -g`.

It worked! Thank you! My problem is solved so i'm closing this issue.
