### ISSUE TITLE
Sensing of block should not reset to English in the workspace

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#5536]
### Expected Behavior

When using the editor in another language if you drag the `costume # of Sprite` block into the workspace, the value selected should stay in the current language. E.g. If I am using Scratch in French, after dragging the block to the workspace it should look the same as the block in the toolbar:
<img width="246" alt="Screen Shot 2020-03-24 at 11 18 31 AM" src="https://user-images.githubusercontent.com/399209/77443380-680cb380-6dc1-11ea-8abf-95989bec72d8.png">

Possibly related to #5445 

### Actual Behavior
The currently selected value reverts to English in the workspace. The choices in the menu are still translated, and if you select one of the other choices it will be translated.
![sensing-lang](https://user-images.githubusercontent.com/399209/77443725-a5714100-6dc1-11ea-8501-ae6c82459f18.gif)

### Steps to Reproduce

1. Switch to another language
2. drag the sensing of block out of the blocks palette.

**Comment by apple502j** [comment]
Duplicate of #4209

**Comment by chrisgarrity** [comment]
Yup, I somehow missed that one when I looked.
