### ISSUE TITLE
Slider monitors should not be mirrored in RTL languages

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#5545]
### Expected Behavior
Cultures that use RTL languages still use the same coordinate system and numbers as other languages. In a number line the numeric values should increase to the right. e.g.
```
0....5....10....15 etc
```

In other words numeric sliders should look identical in LTR and RTL languages.
### Actual Behavior

Slider values have the larger value on the left and smaller value to the right in RTL languages.
![slider](https://user-images.githubusercontent.com/399209/77765554-c8476380-7014-11ea-91ac-e6241500bdc6.png)

### Steps to Reproduce

Create a slider, then switch between LTR and RTL languages.

**Comment by BoomerScratch** [comment]
I'll start working on a fix!

**Comment by chrisgarrity** [comment]
It turns out this is more ambiguous that we thought. In UI conventions, sliders should be mirrored in RTL languages (e.g. https://material.io/design/usability/bidirectionality.html#mirroring-elements). We are following current UI conventions for sliders, so we may not want any change. It will take more feedback from the educators in communities with RTL languages.

**Comment by chrisgarrity** [comment]
After additional feedback from people who use RTL languages, we've decided to keep the sliders as they are (increasing values towards the left).
