### ISSUE TITLE
Changing languages a few times breaks because of too many AudioContexts

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#556]
Changing languages several times causes this error, which totally stops your project from being used.

![image](https://user-images.githubusercontent.com/654102/28466873-d365e188-6dfb-11e7-8d19-fab26be4fce7.png)

> Uncaught DOMException: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).

This is actually being caused by the `AudioEngine` from scratch-audio, because the audio stuff in the gui has a `SharedAudioContext` utility to only ever create one audio context. A similar strategy could be used on the audio engine.

**Comment by Kenny2github** [comment]
It seems to create two new AudioContexts every time you change languages - I changed twice and it had 6.

**Comment by paulkaplan** [comment]
Closing because it will be fixed by https://github.com/LLK/scratch-audio/pull/54 which has been merged.
