### ISSUE TITLE
Normal Stage Size/Small Stage Size Toggle

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-gui#56]
![image](https://user-images.githubusercontent.com/1512021/40077105-a01a1fa4-584e-11e8-9aca-104e8f88753d.png)

**Comment by thisandagain** [comment]
Design for this is available in #1

**Comment by josiahneuberger** [comment]
I implemented a zoomed stage feature into Scratch GUI 3.0.  

Are you guys still interested in a feature like this?

![demo2-stage-zoomed](https://user-images.githubusercontent.com/2754030/29492279-c23985a8-8544-11e7-97f5-3a7dbfa8bb7f.gif)

Code diff:

https://github.com/LLK/scratch-gui/compare/develop...josiahneuberger:add-full-screen-render-view?expand=1

**Comment by thisandagain** [comment]
Thanks @josiahneuberger. We are very interested in this.

/cc @rschamp @paulkaplan @cwillisf

**Comment by josiahneuberger** [comment]
@thisandagain cool! I'm glad it may be of help. I re-factored this a bit to move the zoom control to a separate component. Now the stage menu is separate and is zoomed along with the stage. Also, moved the zoom icon to the correct position using a re-created Scratch 2.0 icon set.

I fixed the two outstanding bugs that I was aware of with zooming. First, I now resize the renderer so the mouse positions are not off any more. Second, the sprites are now drag-able in zoom mode as you would expect:

![demo3-stage-zoomed](https://user-images.githubusercontent.com/2754030/29748236-1834e0c4-8ae0-11e7-9d38-1f4dd9c145d3.gif)

What are you guys looking for with testing before I submit a pull request? I already ran the test suite and fixed the errors.

**Comment by thisandagain** [comment]
Thanks! @rschamp, @paulkaplan, and @cwillisf could one of you follow-up with @josiahneuberger on this?

**Comment by thisandagain** [comment]
Note to self: needed for workshops / testing (CSF)

**Comment by carljbowman** [comment]
Here are some sketches

Large Stage
![lg stage toggle](https://user-images.githubusercontent.com/3409578/40125912-0af2631c-58fa-11e8-8bf3-8d94818188e2.png)

Small Stage
The only major UI consideration here is the Sprite Info area. We already have some responsive behavior for this section, so I imagine extend those to hide a majority of the information.

![sm stage toggle](https://user-images.githubusercontent.com/3409578/40125921-0e441fe2-58fa-11e8-8e87-8a26b2201938.png)
