### ISSUE TITLE
Clicking a color menu causes the default scrollbar to appear too

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-gui#560]
### Expected Behavior

Clicking the color menu should work normally

### Actual Behavior

When clicking a color menu (like the one in `set pen color to []`) the default scrollbar appears (like in #548)

### Steps to Reproduce

![scrolling problem w color picker](https://user-images.githubusercontent.com/28599280/28499658-7031cfe8-6fed-11e7-8f36-e5dd1b2fa765.gif)

1. Navigate to the pen blocks menu
2. Click on the color menu in `set pen color to []`
3. Move the mouse to the Stage and scroll down
4. White space below editor shows (why is there that space?)

### Operating System and Browser

Windows 10 Chrome 58

**Comment by paulkaplan** [comment]
Woah interesting bug! I'm going to file this on scratch-blocks, since it actually originates and will be fixed there, but I'll leave this open as a reference until that one is closed. Thanks!

**Comment by chrisgarrity** [comment]
tracking in https://github.com/LLK/scratch-blocks/issues/1023

**Comment by Kenny2github** [comment]
@chrisgarrity @paulkaplan deliberately left this open...
