### ISSUE TITLE
please add a chinese language seletor in languages.json. you know much chinese people like this scratch project.

### ISSUE THREAD

**Issue by youngonlyforyou** [LLK/scratch-gui#562]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by Kenny2github** [comment]
你可不可以用中文再重複一次？我可以幫你翻譯。

**Comment by youngonlyforyou** [comment]
现在scratch - gui 界面上所有的文字都是英语，比如block上的文字 event、control、sound等等。我的目的是：点击下拉选择框，选择中文，实现界面所有文字显示为中文。event  -> 事件、 control  -> 控制、sound  ->声音等。
或者作者应该把工程里面的所有文字写到一个文件中 en.json ,然后我可以手动改成 zh.json.

**Comment by Kenny2github** [comment]
不同語言的功能尚未開始發展—但請放心，遲早一定會實行的。然而，實行後，你仍然會需要等待scratch-gui的內容翻譯了才能有這個功能。

**Comment by paulkaplan** [comment]
Hi thanks for the submission. We are still very early in our translation work, and we will definitely have a chinese option when we start getting translations done. I'm going to close this issue.
