### ISSUE TITLE
Sharing a costume from a sprite to the stage should create a new backdrop

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#5642]
### Expected Behavior

If you drag a costume tile from a sprite onto the stage in the sprite info area (share the love) it should make a new backdrop on the stage that matches the costume.

### Actual Behavior

No backdrop is made.

### Steps to Reproduce

Create a new project
Open the costume editor
Drag the costume tile from one of the default cat's costumes from the costume list to the stage in the sprite info area
Let go of the mouse
Note: the tile disappears and no backdrop appears in the backdrop list

### Operating System and Browser

Mac Chrome

**Comment by BryceLTaylor** [comment]
It would also be nice if it worked the other way, too.

**Comment by adroitwhiz** [comment]
It looks like it already works the other way (dragging a backdrop onto a sprite tile).

**Comment by apple502j** [comment]
This also affects backpack to stage: https://scratch.mit.edu/discuss/topic/397309/
