### ISSUE TITLE
Compatibility - Android 5.1

### ISSUE THREAD

**Issue by jiangbo2015** [LLK/scratch-gui#565]
### Expected Behavior

work normal on mobile

### Actual Behavior
crash application after open this website

### Steps to Reproduce

open this website on mobile

### Operating System and Browser
android 5.1  chrome

**Comment by Kenny2github** [comment]
Could you provide a little more info please?

**Comment by jiangbo2015** [comment]
**I use it with reactnative's weview, but here some problem**
**here is crosswalk's link bridge**
```
public void linkBridge() {
        if (messagingEnabled) {
            this.evaluateJavascript(
                "window.originalPostMessage = window.postMessage," +
                "window.postMessage = function(data) {" +
                BRIDGE_NAME + ".postMessage(String(data));" +
            "}", null);
        }
    }
```
th

> then i find scratch-gui use window.postMessage/ global.postMessage too, reactnative's code will override scratch's code

**Comment by rschamp** [comment]
@jiangbo2015 What specific issue is there with scratch-gui that is causing the crash? It currently doesn't use `postMessage`.

**Comment by jiangbo2015** [comment]
in fact, I solved this problem ,  in react-native for android, I must use croasswalk to run scratch-gui,
now it is not a problem, thanks
