### ISSUE TITLE
"load from your computer" does not working in Mac

### ISSUE THREAD

**Issue by Ceeson** [LLK/scratch-gui#5651]
save the project to disk, then open this project with"load from your computer" is not working.
also no error happen.
chrome version: 80.0.3987.163 (64bits)
system of computer: Mac

**Comment by apple502j** [comment]
Did you double-click the file? Does open window open?

**Comment by Ceeson** [comment]
> Did you double-click the file? Does open window open?

both.

**Comment by apple502j** [comment]
Ah - that makes sense, double-clicking won't open the file. 
Duplicate of #3365

**Comment by benjiwheeler** [comment]
@ceeson Can you try clicking the file dialog window's "Open" button, and making sure not to double-click anything? My guess is @apple502j is right.

We have a fix in the works, BTW!

**Comment by Ceeson** [comment]
It's fixed.
because have a "setTimeout" in "onload" this function,and "componentWillUnmount" has reset the fileInput.
thanks.
