### ISSUE TITLE
You can't name a sprite _random_, _myself_, _stage_ or _mouse_

### ISSUE THREAD

**Issue by qucchia** [LLK/scratch-gui#5658]
### Expected Behavior

You should be able to name your sprites to whatever you want.

### Actual Behavior

When trying to name a sprite \_random_, \_myself_, \_stage_ or \_mouse_ the change will be reverted.

### Steps to Reproduce

Try to rename a sprite to one of the names above.

### Operating System and Browser

Chrome OS 81

**Comment by Explosion-Scratch** [comment]
Whoa, why? Are those names used for other purposes in the code?

**Comment by apple502j** [comment]
if `_mouse_` or `_random_` is passed to "go to " block, it acts like "go to mouse pointer", so it can't be used to go to the sprite called `_mouse_`. Same thing for `create clone` block which takes `_myself_` and `() of ()` which takes `_stage_`.

You can't name it `_edge_` either - for touching block. see also: https://github.com/LLK/scratch-vm/blob/develop/src/virtual-machine.js#L28

**Comment by Explosion-Scratch** [comment]
Oh, okay, thanks! That makes sense!

On Sunday, April 19, 2020, apple502j <notifications@github.com> wrote:
> if _mouse_ or _random_ is passed to "go to " block, it acts like "go to
mouse pointer", so it can't be used to go to the sprite called _mouse_.
Same thing for create clone block which takes _myself_ and () of () which
takes _stage_.
>
> You can't name it _edge_ either - for touching block. see also:
https://github.com/LLK/scratch-vm/blob/develop/src/virtual-machine.js#L28
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/NCrmgF1WA9OJF7TuiUhYUsX4Jsp7v5NV8j19BB-bpf9Zt7GGZrB8a2SKtGmJ4NE-2Ly88uT2nnZ0WsLPtgLOYBQktc8LsvKPSzYivjGSKLfVwLHP6hh7PBMT8-CLZmoBV463zOoT4NgzxWMlKIIg9x3_kqrkDVbEJFW4qlaaPCdj38JxcKygHf_lw94xT4pSr_VRJ3sYGWDW9pRpPoFN5KOJbLqO-OSNaXmpQ9moQw=s0-d-e1-ft#https://github.com/notifications/beacon/AOT2P3SSRXV2CXNVF42N5TLRNL6TBA5CNFSM4MLJ23QKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOES4YVSY.gif>
