### ISSUE TITLE
Color picker causes high-frequency stage flickering in Firefox 75

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-gui#5678]
### Expected Behavior

The stage should not flicker, especially 60 times a second

### Actual Behavior

On Firefox (versions 75 and up), using the color picker on blocks' color inputs causes the stage to flicker rapidly:

<details>
<summary>
Seizure Warning
</summary>

![Peek 2020-04-24 16-22](https://user-images.githubusercontent.com/25993062/80253740-cf7b8480-8647-11ea-959d-157e603fa10e.gif)

(Due to the limitations of the .gif format, the flickering is slowed down. It's much faster in reality.)

</details>

***This could potentially cause epileptic seizures.***

### Steps to Reproduce

1. Open a block's color input
2. Click the eyedropper icon to open the color picker:
![image](https://user-images.githubusercontent.com/25993062/80253888-21240f00-8648-11ea-8b68-faa104b74818.png)
3. Observe the stage flickering. Don't observe it too closely or you might get a nasty headache or worse.

### Operating System and Browser

Firefox 75 and up, confirmed on Windows and Linux

Also confirmed this does not occur on Firefox 74

**Comment by fsih** [comment]
Yikes!

**Comment by cwillisf** [comment]
Wow, thanks for bringing this to our attention, @adroitwhiz!

**Comment by cwillisf** [comment]
Guidance from W3C regarding flashing web content:
https://www.w3.org/TR/2008/REC-WCAG20-20081211/#general-thresholddef
