### ISSUE TITLE
Invalid Host header

### ISSUE THREAD

**Issue by ThomasLETELLIER** [LLK/scratch-gui#5682]
### Expected Behavior

I tryied to get on my own Ubuntu 18.04 server my own Scratch to work in.

### Actual Behavior

When I use the npm start, on localhost:8601, I just got this message:

> Invalid Host header

**Comment by cdn0x12** [comment]
add `allowedHosts` in `webpack.config.js > const base > devServer` :

```javascript
const base = {
    mode: process.env.NODE_ENV === 'production' ? 'production' : 'development',
    devtool: 'cheap-module-source-map',
    devServer: {
        contentBase: path.resolve(__dirname, 'build'),
        host: '0.0.0.0',
        allowedHosts: ['.your.domain',], // Add Your domain
        port: process.env.PORT || 8601
    },
```

or you can disable host verification by adding `disableHostCheck: true,` to `devServer` (It may make your scratch insecure)
