### ISSUE TITLE
List Does Not Update

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-gui#5729]
I am creating a cloud chatroom with certain phrases that should get added and stay on the list with cloud variables. But it does not work as intended. The phrases only get added to one tab where you are playing it instead of getting added to both tabs. The project only adds phrases for a temporary time, too causing the phrases in the list which are added to disappear
### Expected Behavior

Scratch should keep updating the list and make the project permanent.
### Actual Behavior

Described above.
### Steps to Reproduce

1. Add the code which can be found [in this project](https://scratch.mit.edu/projects/390491930/editor/) to a new one.
2. Run the project.

### Operating System and Browser

Chrome, Windows 10 Pro

**Comment by apple502j** [comment]
what do you mean?

**Comment by R4356th** [comment]
> what do you mean?

Fixed it, I accidentally posted that before.

**Comment by apple502j** [comment]
Not a bug, @R4356th it's your code's problem. you are not updating the list when the cloud variable updates.

**Comment by R4356th** [comment]
@apple502j, I am not quite sure what you mean.

**Comment by R4356th** [comment]
I tried adding a wait () seconds block but it did not work.

**Comment by apple502j** [comment]
This is not a bug so please do not report it here, anyway

The problem with your code is that you only add when you send message. Instead, you need to add when the cloud variable changed.

**Comment by R4356th** [comment]
@apple502j, I still do not get it. Please look at the current version of the project.

**Comment by apple502j** [comment]
@R4356th Cloud variables can update itself when other people update it, so you have to constantly check if the value has changed. 
Here's my remix: https://scratch.mit.edu/projects/393237949/

**Comment by R4356th** [comment]
@apple502j , thank you very much! Sorry @LLK for reporting it as a bug.
