### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by Spaceflyer234** [LLK/scratch-gui#5736]
I run the npm run deploy command, but got this error:

remote: Permission to LLK/scratch-gui.git denied to Spaceflyer234.
fatal: unable to access 'https://github.com/LLK/scratch-gui/': The requested URL returned error: 403

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scratch-gui@0.1.0 deploy: `touch build/.nojekyll && gh-pages -t -d build -m "Build for $(git log --pretty=format:%H -n1) [skip ci]"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scratch-gui@0.1.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/spaceflyer234/.npm/_logs/2020-05-11T14_56_00_632Z-debug.log

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
That command can only be used by the Scratch Team.

**Comment by BoomerScratch** [comment]
> That command can only be used by the Scratch Team.

What do you mean? That command just works fine for me, and I am not an ST member. Also, how about [the wiki article](https://github.com/LLK/scratch-gui/wiki/Publishing-to-GitHub-Pages)? It tells you to run that command.
