### ISSUE TITLE
when i run gui , allways error at gui/container/dound-editor.jsx/line89  :audioBuffer allways undefine.

### ISSUE THREAD

**Issue by youngonlyforyou** [LLK/scratch-gui#574]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by Kenny2github** [comment]
Please provide Expected Behavior, Actual Behavior, and Steps to Reproduce.

**Comment by thisandagain** [comment]
Tracking in #388
