### ISSUE TITLE
Add Extension Flow

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#577]
Tracking issue
- [x] Button for Adding Extension as Category
- [x] Library of Extensions
  - [x] Need to have variation in visual hierarchy
  - [x] Explore metadata associated with Extensions

**Comment by felix2ch** [comment]
One extension maybe own few categories.Blocks too much to fit in one category for some extensions.

**Comment by carljbowman** [comment]
Designs: https://invis.io/RZDRUE8UN
