### ISSUE TITLE
onStartDrag should not call Renderer.pick() on a non-draggable target

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#5776]
See https://github.com/LLK/scratch-gui/pull/4982

**Comment by BryceLTaylor** [comment]
@adroitwhiz can you please add information to this issue from the users perspective.

**Comment by adroitwhiz** [comment]
You can probably close this in favor of https://github.com/LLK/scratch-gui/issues/5781

**Comment by benjiwheeler** [comment]
Reopening per problems encountered with #4982
