### ISSUE TITLE
Should long text in monitors wrap?

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-gui#5796]
### Expected Behavior

I don't know!

### Actual Behavior

Currently, if you put a long string of text in a variable, that variable monitor's text will wrap:
![image](https://user-images.githubusercontent.com/25993062/82499183-3eb98c80-9abf-11ea-9b42-7b7823e639ff.png)

According to [this PR comment](https://github.com/LLK/scratch-gui/pull/4854#issuecomment-544757390) from @towerofnix, they explicitly kept this behavior when changing the way whitespace was handled on monitors, which indicates that this wrapping behavior *may* be intentional?

Of note is that 2.0 doesn't wrap monitor text:
![image](https://user-images.githubusercontent.com/25993062/82499345-86d8af00-9abf-11ea-869c-3912c26cf3d8.png)

**Comment by BryceLTaylor** [comment]
Monitors wrap by design.
