### ISSUE TITLE
Automatically select a costume/sound when it is added

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#580]
### Expected Behavior

_Please describe what should happen_

When adding a new sound or costume, it should be selected in the list (the editor should update with the contents). 

### Actual Behavior

_Describe what actually happens_

The selected costume/sound remains selected after the new costume/sound has been added.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Go to sounds tab
2. Add a new sound
3. See that the new sound has not been selected.

**Comment by jwzimmer** [comment]
Noticed during Paint Editor internal smoketest 11/3/17: when I add a new costume, that new costume is shown on the project stage and in the sprite thumbnail, but it's not selected in the costume tab or paint editor.

<img width="1280" alt="screen shot 2017-11-03 at 1 46 17 pm" src="https://user-images.githubusercontent.com/1320456/32448151-241a6218-c2dc-11e7-93b1-694a555f577b.png">
