### ISSUE TITLE
Changing extension blocks colors

### ISSUE THREAD

**Issue by happy228** [LLK/scratch-gui#5801]
I want to change colors of some blocks, but dont know how to change it in my extension.
![й](https://user-images.githubusercontent.com/42119492/82668658-2e8ee200-9c64-11ea-953f-2af4ba0174fb.PNG)
Have thoughts about this, but nothing changed (also tried hex code)
![Снимок](https://user-images.githubusercontent.com/42119492/82668659-2fc00f00-9c64-11ea-898c-564e121590eb.PNG)
Does anyone know?

**Comment by apple502j** [comment]
Currently, you can only change the whole extension block color. To do so specify `color1`, `color2` and `color3` in the `getInfo`. (format is, iirc, `#xxxxxx`)

**Comment by happy228** [comment]
> Currently, you can only change the whole extension block color. To do so specify `color1`, `color2` and `color3` in the `getInfo`. (format is, iirc, `#xxxxxx`)

I know about changing whole extension color, just wanted to vary my blocks, but thanks anyway
