### ISSUE TITLE
Dragging scripts from the backpack onto the active sprite's selector tile doesn't update the workspace

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-gui#5802]
### Expected Behavior

When you drag a script from the backpack onto the sprite tile of the currently-selected sprite, the workspace should update to show that script.

### Actual Behavior

The script doesn't appear until you switch to another target and come back:
![Peek 2020-05-22 11-12](https://user-images.githubusercontent.com/25993062/82682425-3bd4ae00-9c1d-11ea-9b8d-a32f540db434.gif)

### Steps to Reproduce

1. Drag a block from the Blocks Palette into your backpack
2. Drag that block from your backpack onto the currently-selected sprite tile
3. Notice that the block does not appear in the workspace
4. Select another sprite and then select the original one again
5. Notice that the block now appears in the workspace

### Operating System and Browser

All

**Comment by Explosion-Scratch** [comment]
Intresting, this should be fixed.
