### ISSUE TITLE
Sound Editor - cancel trim operation

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-gui#582]
When I was trying out the trim editor I made a problem and the only way I could figure out to undo it was to re upload the sound. Maybe I just did not see it but I would like to be able to undo and redo trims or effects I make.

Also canceling trim would be nice

**Comment by paulkaplan** [comment]
Undo/redo is on the way. Cancelling the trim definitely came up, @carljbowman could you throw together a design for how to do this?

**Comment by CosmicWebServices** [comment]
Cool thanks!

**Comment by paulkaplan** [comment]
No longer relevant, changed the way trimming works in the sound editor, now it just deletes by selection
