### ISSUE TITLE
All integration tests fail on CircleCI

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#5828]
### Expected Behavior

_Please describe what should happen_
All the tests should pass when running in CircleCI

### Actual Behavior

_Describe what actually happens_
None of the integration tests ever pass. E.g. https://circleci.com/gh/LLK/scratch-gui/6457

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Push a commit to develop and see how it runs in CircleCI

**Comment by apple502j** [comment]
This may be fixed by bumping both node (to 10) and chromedriver (to latest) - it seems like `circleci/node:8.16-browsers` is not updated?

**Comment by rschamp** [comment]
@apple502j That would explain this! Thanks for taking a look. @picklesrus This might be a good first lead. If we do update the CircleCI config it might be a good idea to see if we can lock down the versions better so we can update on our own schedule.
