### ISSUE TITLE
Call window from scratch-gui in scratch-desktop

### ISSUE THREAD

**Issue by happy228** [LLK/scratch-gui#5831]
I want to call this window in scratch-desktop for my extension:

![2](https://user-images.githubusercontent.com/42119492/83267808-f43abd00-a1ee-11ea-8575-1231ea2a85b6.PNG)

I found it's jsx file, but don't know how to call it in scratch-desktop
![1](https://user-images.githubusercontent.com/42119492/83267927-17656c80-a1ef-11ea-9c9e-40d5bb22e063.PNG)
I want to paste it here
![3](https://user-images.githubusercontent.com/42119492/83268304-a1153a00-a1ef-11ea-8b64-99f043373a9c.PNG)

P.S. I am not a pro React developer, need some example code. I am just making extension for my arduino board.

**Comment by ericrosenbaum** [comment]
Hi @happy228 - if you are making an extension, depending on what you are doing, you may be able to use this modal (we call it the "connection modal") the same way our official extensions use it, without writing any react code. All you have to do is set a property in the extension library- you can follow the examples of our other hardware extensions, like [this](https://github.com/LLK/scratch-gui/blob/568d642e482ebafec048ad31003c12e2eb293e72/src/lib/libraries/extensions/index.jsx#L186).

**Comment by ericrosenbaum** [comment]
@happy228 please re-open or open a new issue if you have more questions

**Comment by happy228** [comment]
thanks! It helped me
