### ISSUE TITLE
You can add sprites outside stage, and mess with buttons

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-gui#5834]
### Expected Behavior

You shouldn't be able to disable the love and favorite buttons.  
### Actual Behavior

You can, by adding a sprite outside of the stage that intercepts them. You also can detect if someone is hovering over buttons.
### Steps to Reproduce

You can. I can't find one that disables them, but [this](https://scratch.mit.edu/projects/375350431/) project detects them. I have seen one that actually works at disabling the buttons.
### Operating System and Browser
Chrome 81 Chrome OS

**Comment by apple502j** [comment]
NOTE: Detector part is another bug - #5243 - and LLK/scratch-vm#2309 will patch those.

**Comment by BryceLTaylor** [comment]
Closing as duplicate of #5243. If the click interception can be reproduced, please open it in a separate issue including reproduction steps.

**Comment by GrahamSH-LLK** [comment]
See #5840
