### ISSUE TITLE
Projects with many assets don't load in Chrome some of the time

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#5844]
### Expected Behavior

All projects load normally.

### Actual Behavior

A few projects have come to our attention that don't load in chrome, instead giving a blue error screen (BSOD).  These projects have tons of assets (hundreds).

https://scratch.mit.edu/projects/371197630/
https://scratch.mit.edu/projects/399970272/

If you look in the network tab as the project loads you will see that many assets load.  After loading a number of them, they start coming back as failed requests.  This seems to only happen when using Chrome.

The assets that fail to load can be loaded directly from the api.  

Reloading the page seems to work. The project is viewable.

The current theory is that this is a chrome bug which can only load a certain number of assets per page.  It seems that the first time you load it, the browser caches the responses for the images it finds, then only has to load the images it failed to load the first time, so it works the second time.

### Steps to Reproduce

Load one of the two projects listed above in chrome.
Note: you get a BSOD
reload the page
Note: the project loads this time.  It may take multiple reloads.

Load the project in another browser
Note: the project loads.

### Operating System and Browser

Mac Chrome

**Comment by Explosion-Scratch** [comment]
Does this happen with windows too? (I noticed you put "_mac_ chrome" also, I'm using Mac so I can't check.)

**Comment by apple502j** [comment]
https://scratch.mit.edu/projects/399970272/ loaded for me on Chrome Win10

**Comment by Explosion-Scratch** [comment]
It crashes for me too. This should be fixed.

>

**Comment by mxmou** [comment]
> Does this happen with windows too? (I noticed you put "_mac_ chrome" also, I'm using Mac so I can't check.)

For me it does happen on Windows.

@BryceLTaylor Can you change the title to something that actually makes sense?

**Comment by BryceLTaylor** [comment]
I've had a report that this is also happening using these other browser/os combinations
- Android smartphone using Firefox, Chrome or Opera.
- iPhone using Safari or Chrome
- Linux Chrome

**Comment by RokCoder** [comment]
This is not specific to Chrome so the issue title needs updating.

Using https://scratch.mit.edu/projects/339207237/ loads intermittently with -

Microsoft Edge (Win10)
Chrome (Win10)
Chrome (MBP)

Haven't seen the issue with -

Safari (MBP)
Chrome (Android) - though I'm sure I've seen it happen on my phone before. Worked first time this time though!

**Comment by mxmou** [comment]
> This is not specific to Chrome so the issue title needs updating.
> 
> Using https://scratch.mit.edu/projects/339207237/ loads intermittently with -
> 
> Microsoft Edge (Win10)
> Chrome (Win10)
> Chrome (MBP)

I think "Chrome" refers to all browsers based on Chromium in this repo.

**Comment by benjiwheeler** [comment]
Closing per https://github.com/LLK/scratch-gui/issues/7111

**Comment by Explosion-Scratch** [comment]
lol
