### ISSUE TITLE
Cloud vs Clouds

### ISSUE THREAD

**Issue by 2br-2b** [LLK/scratch-gui#5848]
### Expected Behavior

It should be easy to distinguish the different default sprites. 

### Actual Behavior

It is hard to distinguish between ‘Cloud’ and ‘Clouds’. They should be changed to ’Cloud 1’ and ‘Cloud 2’ or something similar.

### Steps to Reproduce

Open the default sprites menu.

### Operating System and Browser

Any

See #5843

**Comment by Explosion-Scratch** [comment]
Yes, I don't really know how they name the sprites, but this should be fixed.

**Comment by BryceLTaylor** [comment]
I'm closing as a duplicate of #4218
