### ISSUE TITLE
Inputs/ Fields retain focus after typing

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#587]
### Expected Behavior

@carljbowman to explain

### Actual Behavior

Inputs/Fields retaining focus after typing, causing confusion during the Extension Categories External Playtest (8/3/17). Users asked "why is this block not working?" This was specifically frustrating with Speech “when I hear” blocks (this happened a couple times).

(Possibly related to https://github.com/LLK/scratch-gui/issues/182?)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by jwzimmer** [comment]
@carljbowman can you clarify what you were seeing here? I thought I understood what you meant, but when I try to repro it, I am seeing the "when I hear" block triggering even when I have been typing in its field and have not moved my cursor elsewhere. So I think I may have misunderstood what issue you were describing.

<img width="636" alt="screen shot 2017-08-04 at 1 17 58 pm" src="https://user-images.githubusercontent.com/1320456/28979354-985f18da-7917-11e7-8c8e-547d8cb0c6a6.png">

**Comment by carljbowman** [comment]
Hmm. That is interesting. There were several times during the playtest when the input/field retained focus the 'when I hear' block did not execute. 

Just tired it on my machine and I could not repro. Maybe we should try it one of the laptops we used in the playtest, if you haven't already.

**Comment by jwzimmer** [comment]
I can't repro on Philippines laptop (one of the ones we used during the playtest). If we see this again, we can re-open this issue. /cc @carljbowman
