### ISSUE TITLE
modify cloud data of someone ele's project

### ISSUE THREAD

**Issue by jeffalo** [LLK/scratch-gui#5878]
### Expected Behavior

nothing happens

### Actual Behavior

when downloading as an sb3 and loading into a new project the cloud variables are still linked to the original and you can edit them on the original project

### Steps to Reproduce

1. make project with cloud variable
2. other account download as sb3
3. upload to new project
4. edit variable values
5. check cloud logs on original project

![image](https://user-images.githubusercontent.com/40470736/84310393-d90e6c80-ab61-11ea-87c4-bcb8eb34d035.png)

### Operating System and Browser

Chrome, MacOS

**Comment by BoomerScratch** [comment]
@JeffaloBob Nope, can't reproduce.

**Comment by apple502j** [comment]
Clouds should be disabled if you see inside.
