### ISSUE TITLE
Where is the terminal?

### ISSUE THREAD

**Issue by Mar10Josh** [LLK/scratch-gui#5880]
Hey! you say you need to open the **Terminal** in your **Repository**, but i cannot find it!
help wanted

**Comment by apple502j** [comment]
What OS are you on?

**Comment by BoomerScratch** [comment]
I think what they mean is to cd it:
```bash
cd PathToFolder
```
PathToFolder needs to be the path of the cloned repo folder, like `C:\Users\You\scratch-gui`

**Comment by Mar10Josh** [comment]
> What OS are you on?

Macbook

**Comment by Mar10Josh** [comment]
> I think what they mean is to cd it:
> 
> ```shell
> cd PathToFolder
> ```
> 
> PathToFolder needs to be the path of the cloned repo folder, like `C:\Users\You\scratch-gui`. Then you have the terminal opened in your repository. If you are trying to find the terminal itself, I recommend on Windows `cmd.exe` or `powershell.exe`.

i"m on macbook

**Comment by BoomerScratch** [comment]
@Mar10Josh https://support.apple.com/guide/terminal/open-or-quit-terminal-apd5265185d-f365-44cb-8b09-71a064a42125/mac
You need to have [Git](https://git-scm.com) and [NodeJS](https://nodejs.org) installed.

**Comment by chrisgarrity** [comment]
@Mar10Josh you need to be running an application that shows you a command line window. iTerm is the default terminal application on macbooks, iTerm2 is another common alternative. When you open the terminal window you are usually in the "home" directory for your account, not the directory corresponding to the scratch-gui repository. You need to `cd <path to the repository>`. All the commands in the README assume that the command line context is the repository directory.
