### ISSUE TITLE
Page-length Overflow in Editor

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-gui#5887]
### Expected Behavior

There should not be any kind of overflow.

### Actual Behavior

There is overflow inside the editor. Here are some screenshots-

Chrome:
![Screenshot (9)](https://user-images.githubusercontent.com/61620631/84595495-07e65480-ae7a-11ea-86b3-dd7a34132e08.png)

Firefox:
![Screenshot (10)](https://user-images.githubusercontent.com/61620631/84595539-3bc17a00-ae7a-11ea-90ee-6953e6b7352f.png)

### Steps to Reproduce

Create or open a project inside the editor.

### Operating System and Browser

Windows 10, Chrome Version 83.0.4103.97 (Official Build) (64-bit), Firefox Version 77.0.1 (64-bit)

### Extra Note

I apologize if this is intended.

**Comment by SheepTester** [comment]
I think it's intended so that there's always ample space for the sprite list etc

https://github.com/LLK/scratch-gui/blob/202238a3d139f5c8db211f57ea380fb6a0a8dbfb/src/playground/index.css#L9-L11

**Comment by R4356th** [comment]
@SheepTester, but it was not present even a few days ago. And there is always space for the sprite list.

**Comment by BoomerScratch** [comment]
You can try pressing the F11 key (FN+F11 if it doesn't work).

**Comment by R4356th** [comment]
@BoomerScratch, that did not work.

**Comment by GrahamSH-LLK** [comment]
Can't repro on ChromeOS

**Comment by GrahamSH-LLK** [comment]
Do you have a weird sized screen?

**Comment by R4356th** [comment]
It depends on what you call a "weird sized screen". I am pretty sure I am not on one. However, even if I were on one, it would still be some sort of bug which would have to be fixed.

**Comment by BoomerScratch** [comment]
@R4356th I think it's your screen resolution.

**Comment by R4356th** [comment]
@BoomerScratch, I do not think so. My display resolution is set to 1920*1080.

**Comment by BoomerScratch** [comment]
@R4356th Mine is 1440×900, and it doesn't happen.

**Comment by R4356th** [comment]
@BoomerScratch and @apple502j, hmm, weird. 🤔

**Comment by BryceLTaylor** [comment]
This is as designed.  We have included a minimum height.
