### ISSUE TITLE
Sound editor - trim error when left trimmer and right trimmer overlapped

### ISSUE THREAD

**Issue by gengshenghong** [LLK/scratch-gui#590]
### Expected Behavior
should just avoid overlap or delete the sound (warm?)...or...whatever, user should be aware of the error?

### Actual Behavior

_Describe what actually happens_
![image](https://user-images.githubusercontent.com/1018468/29011456-ca3adf88-7b65-11e7-9489-0de0494bc028.png)

### Steps to Reproduce

Trim the sound, drag left trimmer and right trimmer to the same place, click "save".

### Operating System and Browser
Version 50.0.2661.94 (64-bit), Ubuntu 14.04

**Comment by towerofnix** [comment]
Maybe the "Save" button should be disabled, and have a user-visible error message explaining why?

Tiny mockup (though the text could certainly use improvement):

![Desaturated "Save" button next to grey error message](https://user-images.githubusercontent.com/9948030/29027235-2c975bc6-7b56-11e7-842e-285d70ca27b9.png)

**Comment by gengshenghong** [comment]
i think it is a good idea to disable button and prompt user…

**Comment by paulkaplan** [comment]
@carljbowman thoughts on what we should do if you pull the trimmers all together?

**Comment by carljbowman** [comment]
@paulkaplan - Generally I think we should keep the trimmers. I am not convinced by the workshop (playtest) that we should remove them. We saw a lot of tinkering and experimentation, but not a lot of longer form project making. I imagine trimming and undo/redo are features will become more relevant as the creator transitions from tinkering to longer form creation.

We should explore the two things:
1. Resolving this issue of overlapping crop marks
2. Having a cancel state for the trim feature. Which I believe we are tracking in a separate issue.
