### ISSUE TITLE
iPad touchscreen tap doesn’t count as “mouse down”

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-gui#591]
### Expected Behavior

When you tap on the stage with a touchscreen the “mouse down?” block should report true.

### Actual Behavior

Nothing when stage is tapped with touchscreen

### Steps to Reproduce

1. Drag into scripts area and run:
```scratchblocks
forever {
    point in direction (<mouse down?> * (90))
}
```
2. Tap on stage with iPad touchscreen
3. No direction change

### Operating System and Browser

iOS 11 Developer Beta, Chrome 60

**Comment by rschamp** [comment]
Thanks @Kenny2github. Curious about the steps to reproduce — the `say` block is not currently implemented. Which build are these steps for?

**Comment by Kenny2github** [comment]
I was using `say` as a random example - didn’t know it wasn’t implemented yet 😅 
The actual example was
```scratchblocks
forever {
    point in direction (<mouse down?> * (90))
}
```
And there was no direction change on tap.

**Comment by rschamp** [comment]
Ok, no problem! Thanks for your report.

**Comment by gengshenghong** [comment]
This seems like not a "mouse down" issue only, many mouse events does not work as well? Example: the "long press" and then "mouse move" does not work for stage and trimmer in sound editor on iPad. The Blocks part worked well (you can "long press" on a block and drag it to workspace). It seems like events on touch screens are not handled correctly by Scratch-GUI and Scratch-Blocks handled it quite well.

Thanks,
Shenghong

**Comment by thisandagain** [comment]
We have not yet addressed issues with touch in the GUI. We will resolve this later in the year.
