### ISSUE TITLE
the websocket of speech reconization was broken wss://speech.scratch.mit.edu/

### ISSUE THREAD

**Issue by ATKovz** [LLK/scratch-gui#5933]
### Expected Behavior

wss://speech.scratch.mit.edu/ should be connected

### Actual Behavior

the websocket connection was break

```
Error in connection establishment: net::ERR_CONNECTION_CLOSED
```

### Steps to Reproduce

just create a new Websocket connection and connect it

### Operating System and Browser

Mac OS 10.15.3

**Comment by ericrosenbaum** [comment]
That server was an experimental prototype used internally by the Scratch team. We have turned it off.
