### ISSUE TITLE
resort to using the ^0.1.0-prerelease.0 reference instead of latest

### ISSUE THREAD

**Issue by vincentbriglia** [LLK/scratch-gui#594]
### Expected Behavior

When using auto-linking tools such as lerna, the "latest" tag in package.json doesn't work. Rather than using "latest", resort to using "^0.1.0-prerelease.0" in the package.json

### Actual Behavior

packages don't get auto-linked

### Steps to Reproduce

This is not a problem with scratch-gui per-se, this helps with being conform so that local development is easier

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by rschamp** [comment]
Unfortunately, this causes other issues with local development, since a simple `npm install` will not install the latest version of these modules. This will be resolved when all components use semver.

**Comment by rschamp** [comment]
We are no longer using latest
