### ISSUE TITLE
Auto load extension

### ISSUE THREAD

**Issue by happy228** [LLK/scratch-gui#5940]
I need to set extensions on start screen automatically. In other words, when i start scratch i don't have to click on extension button, extension is already on the screen.

**Comment by BoomerScratch** [comment]
How about using a query string?
For example:
https://scratch.mit.edu/projects/editor/?extensions=pen
Also, I think this should be moved to LLK/scratch-vm.

**Comment by ericrosenbaum** [comment]
I think the most straightforward way is to call the VM function `vm.extensionManager.loadExtensionURL(extensionID)` from here in the GUI. When I've done that, I put it in the blocks container's `componentDidMount` function ([here](https://github.com/LLK/scratch-gui/blob/3f0389179ce7de87893b8c6c4882ba1256c8fc85/src/containers/blocks.jsx#L88)). That should load the extension when the GUI loads.
