### ISSUE TITLE
Scrollbar always appears in sounds tab and costumes tab

### ISSUE THREAD

**Issue by BoomerScratch** [LLK/scratch-gui#5946]
Related to #2295

### Expected Behavior

Scrollbars do not appear in the sounds and costumes/backdrops tabs. (If there are not many costumes/sounds)
![image](https://user-images.githubusercontent.com/60622217/85942403-59d2b400-b929-11ea-8524-ad75af7ee9c9.png)![image](https://user-images.githubusercontent.com/60622217/85942416-6fe07480-b929-11ea-87f3-177ed9d6dbd7.png)

### Actual Behavior

They do.
![image](https://user-images.githubusercontent.com/60622217/85942455-ba61f100-b929-11ea-982d-dda630b4c15b.png)![image](https://user-images.githubusercontent.com/60622217/85942470-c352c280-b929-11ea-80e8-5113db46e8a9.png)

### Steps to Reproduce

Open a project and switch to the sounds/costumes/backdrops tab.

### Operating System and Browser

Chrome 83.0.4103.116, Windows NT 10.0.

**Comment by BryceLTaylor** [comment]
This is a browser level setting that we don't control but account for in our design.

**Comment by fsih** [comment]
@BryceLTaylor I think we could remove those scrollbars if we wanted to. They don't appear by default on Macs, but they aren't forced to appear on Windows

**Comment by BryceLTaylor** [comment]
@fsih They appear to me on mac.  It's a browser setting. (possibly an OS level setting).  Discussing with @carljbowman, we decided that this behavior is acceptable.

**Comment by BoomerScratch** [comment]
@BryceLTaylor @fsih This is easily fixable: the problem is `overflow-y: scroll`, which should be `overflow-y: auto`.
https://github.com/LLK/scratch-gui/blob/81664880021571a9144691379b584305f3b5e703/src/components/asset-panel/selector.css#L50
