### ISSUE TITLE
Can drag lots of elements

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-gui#5950]
### Expected Behavior

When you are dragging a variable, you shouldn't be able to drag lots of the page.

### Actual Behavior
You can drag the whole page
![Screenshot 2020-06-29 at 8 37 49 PM](https://user-images.githubusercontent.com/64214252/86069796-ee800380-ba48-11ea-9df8-b2a5c0bf3f9f.png)

### Steps to Reproduce
It's never happened before, but I was dragging a variable and it happened

### Operating System and Browser
ChromeOS

**Comment by BoomerScratch** [comment]
It's your browser. It's not a problem with Scratch.

**Comment by GrahamSH-LLK** [comment]
Ok. Closing
