### ISSUE TITLE
Question: why does Travis commonly fail on greenkeeper prs?

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-gui#596]
^^

**Comment by rschamp** [comment]
It depends on the PR. This is the job of Travis — some dependency upgrades require changes to the codebase to function.  For instance if `eslint` introduces a more strict linting rule, we must update our config or re-lint our code to accommodate.

For build-time dependencies (`webpack`, `eslint`, etc. - code not touched while running the app), we pin to major (`^`) versions, so it's actually expected that these upgrades will fail without changes. The defining feature of major version bumps is that they include breaking changes.

**Comment by Kenny2github** [comment]
Ah, I see. Thanks!
