### ISSUE TITLE
[Scratch Desktop] After trying to create variable with existing name, can't create anymore variables

### ISSUE THREAD

**Issue by Smrman** [LLK/scratch-gui#5970]
### Expected Behavior

You should be able to create more variables after trying to create a variable with an already-existing name.

### Actual Behavior

Modal doesn't let input the name of the new variable to create.

### Steps to Reproduce

1. Open Scratch Desktop.
    1.1 Notice there is a default variable named "my variable".
![image](https://user-images.githubusercontent.com/17651422/86803884-b3985400-c076-11ea-80c6-d582e850edfe.png)
In my case, the editor create that default variable named "ma variable" since my computer language is set to French, but this is the case for any language.
2. Try to create a new variable with the name of an already-existing variable.
    2.1 Click the "Create variable" button.
    2.2 Enter the name of an existing varibale (e.g. "my variable")
    2.3 Local or Global variable doesn't matter.
![image](https://user-images.githubusercontent.com/17651422/86804164-fe19d080-c076-11ea-96f1-6c582aaa4210.png)
    2.4 Click Ok.
    2.5 Alert box says a variable with such name already exists.
![image](https://user-images.githubusercontent.com/17651422/86803792-99f70c80-c076-11ea-99f7-f7a855964ace.png)
    2.6 When clicking Ok on the alert box, the modal immediately closes.
3. Try to create another variable
    3.1 Click the "Create variable" button once again.
    3.2 Try to enter a name for that variable. **You can't. The input field is disabled**.
![image](https://user-images.githubusercontent.com/17651422/86804430-34efe680-c077-11ea-9093-85ef673c17cc.png)
Not that obvious on the picture, but the input is disabled, can't select the text box, put my cursor in it and enter text.

### Note

This bug doesn't appear on the online version of Scratch.
This is a Scratch Desktop only bug.
Is this a regression of some sort? Don't remember seeing this bug before.

Also, I noticed I didn't have the latest version of Scratch Desktop (had v. 3.9 while v. 3.12 was out at the time of writing).
I proceeded to install Scratch Desktop from the Microsoft Store, but the store didn't provide the latest version (v. 3.6).
The 3.6 version didn't have the bug.
Uninstalled the version from the MS Store and installed from the executable provided by the Scratch website (v. 3.12).
The bug is present in the 1.12 version.

### Operating System and Browser

![image](https://user-images.githubusercontent.com/17651422/86803337-2d7c0d80-c076-11ea-8dfd-706dc488e5b2.png)
![image](https://user-images.githubusercontent.com/17651422/86806728-6f5a8300-c079-11ea-8a61-d03d1af6aeeb.png)
Microsoft Windows, Version 20H2 (build 19042.330)

**Comment by Smrman** [comment]
Nvm, found the exact same issue on https://github.com/LLK/scratch-desktop/issues/112

**Comment by BryceLTaylor** [comment]
Closing as duplicate.

**Comment by ChomyT** [comment]
So what is the solution to this problem?
