### ISSUE TITLE
Reload does not ask for confirmation to navigate away on changed project on iPad

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#5990]
### Expected Behavior

When there are unsaved changes and you click reload, there should be an alert that the user needs to confirm before navigating away.

### Actual Behavior

The project just reloads with the last state of the project

### Steps to Reproduce

As a logged in user:
* create a new project
* add a backdrop or new sprite
* click reload
The project reloads with the default project

### Operating System and Browser

iPad mini 4, iOS 13.5.1, Safari

**Comment by benjiwheeler** [comment]
It seems that there is no simple answer for this problem. See:
* https://www.igvita.com/2015/11/20/dont-lose-user-and-app-state-use-page-visibility/
* https://stackoverflow.com/questions/3239834/window-onbeforeunload-not-working-on-the-ipad
* https://stackoverflow.com/questions/6205989/is-there-an-alternative-method-to-use-onbeforeunload-in-mobile-safari

**Comment by benjiwheeler** [comment]
Removed the bug label, as this appears to be 100% intentional behavior by Apple

**Comment by cwillisf** [comment]
Unfortunately, it looks like mobile Safari doesn't offer any way to fix this. If we find out there's a way we should reopen this, but I'll close it for now since there's nothing we can do.
