### ISSUE TITLE
Workspace scrolling is shared between sprites

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#6]
Scroll/pan position should probably be stored with a value for each target, so that switching between sprites won't make you need to go back to where your far-way scripts are. (That's a huge problem I have with multiple sprites having [tons](http://i.imgur.com/1FZQJ82.png) [of](http://i.imgur.com/U6iYBZJ.png) [scripts](http://i.imgur.com/WvNtVkY.png) in Scratch 2!)

(Probably has a bit to do with scratch-vm..)

Kind of similar to LLK/scratch-blocks#690.

---

Moved from LLK/scratch-blocks#693
/cc @liam4

**Comment by rachel-fenichel** [comment]
Tracking bug in blockly: https://github.com/google/blockly/issues/1052

**Comment by paulkaplan** [comment]
Per-sprite workspace positioning has been implemented.
