### ISSUE TITLE
Blocks - implement "item # of [string] in [drop down]" reporter

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#600]
Implement new reporter as per discussions with the resources team. Essentially this reporter simplifies finding the index of an item in a list by it's value. In the event that multiple items in the list exactly match the supplied string the reporter will return the first index. In the event that no item exists that exactly matches the supplied string the reporter will return `0`.

### Block Spec
`item # of [string] in [drop down]`

### Defaults
`item # of [thing] in [list]`

### Drop-down
- `[dynamic list of lists]`

### Position
The new reporter should be added to the data category below the `item (drop down) of [drop down]` reporter.

### Reference
- [Javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf)
- [Python](https://docs.python.org/2/library/array.html#array.array.index)

/cc @ntlrsk @carljbowman

**Comment by thisandagain** [comment]
Pushing to November milestone to match implementation timeline for lists. 

/cc @rschamp @paulkaplan

**Comment by towerofnix** [comment]
This is actually really, *really* helpful, even for relatively more complicated projects :heart:

E.g. I could have three lists: "names", "x positions", and "y positions". Then I could get the x position and y position by doing something like this:

![set index to (index of name in names)...](https://user-images.githubusercontent.com/9948030/29182576-d4079930-7dd5-11e7-8068-45dc9dd9c1ac.png)

I can already *do* this by using a custom block (or some alternative method, like maintaining a list of references to the indexes of data), but this just makes everything a bit simpler.

**Comment by CosmicWebServices** [comment]
This is sweet

**Comment by mrjacobbloom** [comment]
Dictionaries here we come

**Comment by griffpatch** [comment]
I just wondered, what about the case where you have a list containing a
mixture of upper and lowercase versions of the same string.
If you ask for the index of one particular string and it matches exactly to
one, but only case insensitively to another, should it return the index of
the exact match? or always the first matching one?

**Comment by thisandagain** [comment]
@griffpatch Good question. If we wanted to resolve that I suppose we would simply need to fully traverse the contents of the list looking for both exact and case insensitive matches before returning. The inconsistency here feels like it could be potentially confusing in either direction though so I'm not quite sure if I've formulated an option yet.

**Comment by mrjacobbloom** [comment]
Since scratch generally ignores case, I'd expect this block to be completely case-insensitive. That said, it'd be really handy to have another set of blocks that can be used to test case so we could do this manually if needed
