### ISSUE TITLE
Blocks - implement "[string] contains [string]" reporter

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#601]
Implement new reporter as per discussions with the resources team. Essentially this reporter simplifies a whole range of string applications by allowing for simple "contains" matching. For an example of how Scratchers get around the current limitation see the following:
https://scratch.mit.edu/projects/10448268

### Block Spec
`[string] contains [string]`

### Defaults
`[hello world] contains [hello]`

### Position
The new reporter should be added to the operators category below the `length of [string]` reporter.

### Reference
- [Javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes)
- [Python](https://docs.python.org/3/reference/expressions.html#membership-test-details)

/cc @ntlrsk @carljbowman

**Comment by Kenny2github** [comment]
I’m trying to Implement this - but I’m not really sure how 😕. I’ve added the block in `scratch-blocks/core/blocks-vertical.js`, under the “length of” block, but I don’t know where to add the script for it. Any help?

**Comment by thisandagain** [comment]
@Kenny2github Thanks! Take a look in the "blocks" directory of `scratch-vm`. 😄

**Comment by ateesdalejr** [comment]
Will there be a possibility of this being a reporter block that returns the index of where the string was first found?

**Comment by Kenny2github** [comment]
@ateesdalejr it seems not - this is just a boolean block.

@thisandagain shouldn't this be closed now?
