### ISSUE TITLE
Remove checkbox before the block

### ISSUE THREAD

**Issue by mkovalevski** [LLK/scratch-gui#6012]
This checkbox is confusing me, I don't know how it appeared. I want to remove it but didn't find anything close to my problem. I created this block in extension
![checkbox](https://user-images.githubusercontent.com/42119492/87943915-e572d700-cac8-11ea-86c9-d0de89521c4f.PNG)

**Comment by apple502j** [comment]
This is a monitor checkbox. You can remove by adding `disableMonitor: true` on the block definition at getInfo.
```js
                {
                    opcode: 'myReporter',
                    blockType: BlockType.REPORTER,
                    text: 'foo',
                    arguments: {},
                    disableMonitor: true
                }
```

**Comment by mkovalevski** [comment]
Thank u very much!
