### ISSUE TITLE
In RTL languages, reordering sprites is very strange.

### ISSUE THREAD

**Issue by noamraph** [LLK/scratch-gui#6020]
### Expected Behavior

In order to reorder sprites, you drag a sprite onto another sprite. The position under the mouse cursor becomes gray, to show that the sprite will be moved to this position.

### Actual Behavior

The position which becomes gray is not the position under the mouse cursor, but rather the opposite - if the mouse is over the rightmost position, the leftmost position will be the target.

### Steps to Reproduce

Change the language to Hebrew.
Add two sprites so you'll have three.
Drag one of the sprites over the others, see that when the mouse is over the leftmost position, the rightmost position is marked.

### Operating System and Browser

Ubuntu 16.04, Chrome Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by noamraph** [comment]
I was able to identify the cause in code. Making this change fixed the issue in RTL mode:

```
diff --git a/src/lib/sortable-hoc.jsx b/src/lib/sortable-hoc.jsx
index eb971d0..4197c3c 100644
--- a/src/lib/sortable-hoc.jsx
+++ b/src/lib/sortable-hoc.jsx
@@ -25,7 +25,7 @@ const SortableHOC = function (WrappedComponent) {
                 // Drag just started, snapshot the sorted bounding boxes for sortables.
                 this.boxes = this.sortableRefs.map(el => el && el.getBoundingClientRect());
                 this.boxes.sort((a, b) => { // Sort top-to-bottom, left-to-right.
-                    if (a.top === b.top) return a.left - b.left;
+                    if (a.top === b.top) return -(a.left - b.left);
                     return a.top - b.top;
                 });
                 if (!this.ref) {
diff --git a/src/lib/drag-utils.js b/src/lib/drag-utils.js
index e3f5c1b..2d25d0b 100644
--- a/src/lib/drag-utils.js
+++ b/src/lib/drag-utils.js
@@ -30,8 +30,11 @@ const indexForPositionOnList = ({x, y}, boxes) => {
         const maxY = box.bottom === bottomEdge ? Infinity : box.bottom;
         // The last item in the wrapped list gets a right edge at infinity, even
         // if it isn't the farthest right. Add this as an "or" condition for extension.
+        /*
         const maxX = (n === boxes.length - 1 || box.right === rightEdge) ?
             Infinity : box.right;
+        */
+       const maxX = box.right === rightEdge ? Infinity : box.right;
 
         // Check if the point is in the bounds.
         if (x > minX && x <= maxX && y > minY && y <= maxY) {
```

The change in `sortable-hoc.jsx` is the most important. It reverses the assumption that items are ordered from left to right. Obviously this needs to depend on whether the component is RTL, but I don't know how to query that.

In `drag-utils.js` I disabled the special case that makes the last box extend infinitely to the right. This should be fixed so that in RTL mode, the last box will extend infinitely to the left.

I will be happy to write a proper pull request, but I'll need some hints on how to check if the component is in RTL mode.

**Comment by apple502j** [comment]
You need to get isRtl from somewhere. For sortable-hoc you can add `isRtl: PropTypes.bool` to `SortableWrapper.propTypes =`, `isRtl: state.locales.isRtl` and use `this.props.isRtl`

For drag-utils you probably need to add an argument to the function and pass isRtl as argument.

**Comment by noamraph** [comment]
@apple502j Thanks! Thanks to your help I wrote a pull request.
