### ISSUE TITLE
How can I add some  video tutorials in scratch 3.0

### ISSUE THREAD

**Issue by crouse12** [LLK/scratch-gui#6022]
I  want to know how to add a video to tutorials in scratch 3.0. May I know how to  do it?

**Comment by apple502j** [comment]
You need Wistia account.

**Comment by crouse12** [comment]
Can you show me how to do it?
I can create a Wistia account.

**Comment by crouse12** [comment]
Can it uses youtube?

**Comment by apple502j** [comment]
The current code uses Wistia. You can code it though!

**Comment by crouse12** [comment]
Can you teach me how to use Wistia?

**Comment by apple502j** [comment]
I don't know, sorry.

**Comment by crouse12** [comment]
In scratch-gui\src\lib\libraries\decks\steps, there are many gif files for tutorials.
In scratch-gui\src\lib\libraries\decks, there is a index.jsx file which can modify the tutorials.
However, I cannot find how to put videos.
Is it in en-steps.js?

**Comment by apple502j** [comment]
translate-video.js has Wistia video IDs.

**Comment by crouse12** [comment]
I try to increase a new menu bar for youtube.
I think it is also a good solution.

![image](https://user-images.githubusercontent.com/25700616/88279642-ffa1f480-cd16-11ea-9c31-da8cc9045b1e.png)

**Comment by PhidgetsInc** [comment]
I added YouTube capability in a forked repo. You can take a look at how I did it and adapt it to your requirements.

[https://github.com/PhidgetsInc/scratch-gui/commit/0c6e190e86d1bbbea82d5239230a7b9c5c0ab243](https://github.com/PhidgetsInc/scratch-gui/commit/0c6e190e86d1bbbea82d5239230a7b9c5c0ab243)

Files of note are:
`src/components/cards/cards.jsx` 
`src/lib/libraries/decks/translate-video.js`
`src/lib/libraries/decks/index.jsx`

**Comment by crouse12** [comment]
Thanks

**Comment by crouse12** [comment]
You are too strong.  I still have a question.
May I know how to modify the tutorial menu?

![image](https://user-images.githubusercontent.com/25700616/88349943-17fc2880-cd84-11ea-822e-a4d1b5073530.png)

**Comment by apple502j** [comment]
You can modify lib/libraries/tutorial-tags.js and lib/libraries/tag-messages.js

**Comment by crouse12** [comment]
I did. However, the scratch broken.

**Comment by crouse12** [comment]
Thanks. I try it successfully. 'All' cannot be modified. However, Others can be modified.
