### ISSUE TITLE
npm install,chromedriver install failed!

### ISSUE THREAD

**Issue by yuanhaisu** [LLK/scratch-gui#6034]
### Actual Behavior

_Describe what actually happens_
![image](https://user-images.githubusercontent.com/11955508/88497195-349d9800-cff2-11ea-9939-e2c73f6d8534.png)

### Steps to Reproduce
cd /opt/scratch-gui
npm install

### Operating System and Browser

centos 7 
![image](https://user-images.githubusercontent.com/11955508/88497408-dcb36100-cff2-11ea-9f54-7822d3c263af.png)

**Comment by yuanhaisu** [comment]
after npm install --ignore-scripts   & npm install  
then npm start 

get errors:
![image](https://user-images.githubusercontent.com/11955508/88500623-c6f66980-cffb-11ea-9bc7-a60d618a6df7.png)

**Comment by apple502j** [comment]
Are you using proxies?

**Comment by yuanhaisu** [comment]
> Are you using proxies?

when i update node and npm to latest version,it's ok!
