### ISSUE TITLE
Help: how to add a layer over video on Stage?

### ISSUE THREAD

**Issue by hyansuper** [LLK/scratch-gui#6061]
I am trying to make an face recognition extension, and I want to draw an rectangle over detected face. 

I made a similar function to [_setupPreview](https://github.com/LLK/scratch-vm/blob/develop/src/io/video.js#L145), by creating a [VIDEO_LAYER drawable](https://github.com/LLK/scratch-vm/blob/develop/src/io/video.js#L151) and periodically [update and redraw](https://github.com/LLK/scratch-vm/blob/develop/src/io/video.js#L182), I can display a rectangle on Stage, but when the camera is playing(by activating the video-sensing extension), my rectangle disappears, Is it because the two layers are both VIDEO_LAYER and they conflict? So is it possible to add a layer over the video on Stage? or I should I make an custom layer beside the [built in layers](https://github.com/LLK/scratch-vm/blob/develop/src/engine/stage-layering.js)?

**Comment by ericrosenbaum** [comment]
Hi @hyansuper - sorry about the delay- hopefully by now you have figured out a solution. Your idea to add a custom layer makes sense to me. Let us know if you have more questions!

**Comment by hyansuper** [comment]
Hi, @ericrosenbaum , I haven't been able to find a solution. If you know, please briefly show me
