### ISSUE TITLE
Blocks - add "When this sprite touches [sprite]" hat

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#607]
This block would be a hat that uses the same logic as the existing boolean reporter, "touching [mouse-pointer]?", which has a menu to choose the mouse pointer, the edge, or a sprite. 

One reason to add this block is that it would greatly simplify a common case for beginners, where they want to detect that one sprite is touching another, often in a game. One example is in the "Catch Game" Scratch cards:

<img width="343" alt="screen shot 2017-08-10 at 4 26 05 pm" src="https://user-images.githubusercontent.com/567844/29192922-49b49b5e-7df1-11e7-853b-14676b268433.png">

This stack could be reduced to a much simpler one- the new hat would replace the forever block, the if block, and the boolean reporter:

When this sprite touches bowl
Play sound pop
Go to random position
Set y to 180

**Comment by thisandagain** [comment]
I really like this idea.

I'm curious about what should be included in the drop-down here and what the default should be. In 36% of shared projects there is only one sprite. Should we think about matching what is in the `touching [drop down] ?` reporter (see: https://github.com/LLK/scratch-gui/issues/599)?

I'm also curious about the language on the block. A slight variation could be `when touching [drop down]` as to match the `touching [drop down] ?` and be a bit more terse. Thoughts?

/cc @ntlrsk @carljbowman

**Comment by towerofnix** [comment]
>I'm also curious about the language on the block.

[So,](url) `

**Comment by towerofnix** [comment]
>I'm also curious about the language on the block. A slight variation could be when touching [drop down] as to match the touching [drop down] ? reporter and be a bit more terse. Thoughts?

"When touching" might imply that the following blocks will be run *constantly while* touching [argument]. For example, a user might try to do this:

!["when touching mouse"; "turn 15 degrees"](https://user-images.githubusercontent.com/9948030/29199428-581c81e8-7e23-11e7-8630-46a02dc7baed.png)

..and then be surprised to find that the sprite only turns *once*, as soon as the mouse is touching it!

Whereas "when this sprite touches" makes more sense in that case, I think:

!["when this sprite touches mouse"; "turn 15 degrees"](https://user-images.githubusercontent.com/9948030/29199420-47cf98a2-7e23-11e7-81f2-d4c2fc2aa0c4.png)

Plus, I think the actual solution would jump out more clearly with "when this sprite touches"; compare:

![The respective hat blocks, attached to "repeat until (not touching mouse): turn 15 degrees"](https://user-images.githubusercontent.com/9948030/29199475-a0c1bed6-7e23-11e7-90d5-259b2913739d.png)

**Comment by mrjacobbloom** [comment]
Plus it's closer to the "when this sprite clicked" block so I think it's more important to match that

**Comment by thisandagain** [comment]
Agreed @towerofnix ! Thanks for the adding some visuals to this! 😄

**Comment by Kenny2github** [comment]
Any updates to this?

**Comment by thisandagain** [comment]
Hi @Kenny2github please refrain from bump comments like this. On each issue you can see where it is in the schedule by looking at the Milestone. For items that are listed in the "Backlog" that means that they likely will not be addressed until after the alpha release.

**Comment by Kenny2github** [comment]
Hi @thisandagain you made your point in one pr - there's no need to reiterate it in every case I made my mistake. Thanks.

**Comment by kyleplo** [comment]
I like this idea - ScratchJr has the ![image](https://user-images.githubusercontent.com/31634240/36606380-86f4187e-1891-11e8-975b-11b857b8fc98.png) block, and this would just be a more complex version.

**Comment by kyleplo** [comment]
Could there also be this option?
![image](https://user-images.githubusercontent.com/31634240/36606528-f546f526-1891-11e8-90cd-9e5dffa4b99c.png)
