### ISSUE TITLE
Update nav to reflect save failure

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#6077]
**Back to [Save Alerts Phase I Redesign – Overview](https://github.com/LLK/scratch-gui/issues/6069)**

## Nav change
When a project fails to save, the "save now" area of the nav should update to indicate that the project could not save.  

![4 1 1 Fallback](https://user-images.githubusercontent.com/8203939/89658106-1ceccc00-d89c-11ea-96ff-3207d148789d.png)

## Successful Save
After a successful save, the indicator should return to its blank state.

### Other considerations
If the save failure is due to connectivity it should get the connectivity indicator instead of the default one.  This will eventually get filed separately.

**Comment by paulkaplan** [comment]
I'm going to close this to condense it with https://github.com/LLK/scratch-gui/issues/6076, since we don't want to merge the nav without the button update.
