### ISSUE TITLE
Save failure indicator in nav should reopen save alerts

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#6078]
After failing to save, the "failed to save" indicator in the nav bar should reopen any closed save alerts.

![4 1 1 Fallback](https://user-images.githubusercontent.com/8203939/89658106-1ceccc00-d89c-11ea-96ff-3207d148789d.png)

This relies on the implementation of https://github.com/LLK/scratch-gui/issues/6077

**Back to [Save Alerts Phase I Redesign – Overview](https://github.com/LLK/scratch-gui/issues/6069)**

**Comment by paulkaplan** [comment]
I'm going to close this to condense it with https://github.com/LLK/scratch-gui/issues/6076, since we don't want to merge the nav without the button update.
