### ISSUE TITLE
Integration test for adding a new sprite, and some stylistic questions

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#609]
Continue work started in https://github.com/LLK/scratch-gui/pull/584#issuecomment-321800429 by:
- [ ] reorganizing tests (maybe as in https://github.com/jwzimmer/scratch-gui/commit/0363e358bb387e4d0dbbe9b4fd7931ff6c3717a1)
- [ ] adding an additional test to add a new sprite and check costume lists before/ after
- [ ] figure out if we want to add more asserts per test or not

**Comment by paulkaplan** [comment]
Tests have been added and the system is evolving!
