### ISSUE TITLE
What if Scratch could run the bigger scratch projects

### ISSUE THREAD

**Issue by junaayd123** [LLK/scratch-gui#6092]
Hello, I think it would be great if Scratch could run the biggest scratch projects, like GriffPatch's raytracer, my computer could not run it all. I am using Chrome on a Windows 10 HP Pavilon computer, can you fix this? Thanks!

**Comment by BryceLTaylor** [comment]
This suggestion is too broad.  If you have a specific error or performance improvement in mind you could file that.

**Comment by junaayd123** [comment]
> This suggestion is too broad. If you have a specific error or performance improvement in mind you could file that.

Oh, ok. Thanks
