### ISSUE TITLE
Signing in issues

### ISSUE THREAD

**Issue by junaayd123** [LLK/scratch-gui#6098]
Hello. I have an issue with Scratch. When I log into my Scratch account and shut down my PC, then I start it up, and then I find out that I have been signed out. I am using an HP Pavilon All-in-One PC, although this issue happenes not that often. I used Google Chrome.

**Comment by BryceLTaylor** [comment]
We use cookies to track your session.  I would check your browser settings to make sure you're not clearing cookies when you close the browser.

**Comment by junaayd123** [comment]
Oh, ok! Well I don't have that problem anymore.
