### ISSUE TITLE
Items in the backpack are not localized

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#6115]
### Expected Behavior
The labels in the backpack: script, sprite, costume etc. should be localized into other languages.

### Actual Behavior
Spanish and Arabic below. Note I don't expect the actual names of the sprites, sounds etc to be localized, they should match whatever the name was when it was added, with the exception of "script" "code" both should be localized.
<img width="526" alt="Screen Shot 2020-08-21 at 10 02 36 AM" src="https://user-images.githubusercontent.com/399209/90899272-ab317980-e395-11ea-9f45-4e831164f3d3.png">
<img width="591" alt="Screen Shot 2020-08-21 at 10 02 05 AM" src="https://user-images.githubusercontent.com/399209/90899280-ae2c6a00-e395-11ea-941e-ab1341000827.png">

### Steps to Reproduce

Switch to any language other than English

### Operating System and Browser

Mac OS 10.14.6 Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by apple502j** [comment]
This is provided from API - but easy to handle it ourselves.

**Comment by apple502j** [comment]
Fix available at https://github.com/apple502j/scratch-gui/tree/localize-backpack-assets
