### ISSUE TITLE
Sound cannot be uploaded

### ISSUE THREAD

**Issue by W1THRD** [LLK/scratch-gui#6118]
### Expected Behavior

Sounds  should upload to the scratch project as normal, and be saved.

### Actual Behavior

1. The sound uploads
2. The save/share button is pressed, and this is where the trouble starts.
3. The project tries to save for 1 - 12 minutes 
4. A message box appears that says that the project could not be saved

### Steps to Reproduce

1. Open the online scratch.mit.edu Editor while signed in to scratch
2. In the sounds tab, upload a sound
3. Press the save button- you will see the saving error

### Operating System and Browser

OSes I have tried:
- Windows 10 latest version
- Samsung Galaxy Tab S6 Lite
- Chromebook
- iPad
- Kindle fire

Browsers I have tried:
- Old MS edge
- Google Chrome
- Apple Safari
- Amazon Silk
- Scratch app for android

**Comment by TheSeagullDev** [comment]
Can't repro on MacOS 10.15.6 using Chrome

**Comment by BryceLTaylor** [comment]
It sounds like you're saving a file that is larger than our maximum file size (10MB) for assets.  We have an issue filed for addressing communications around that: https://github.com/LLK/scratch-gui/issues/6073.

It is not our intention to change or remove the file limit, though.
