### ISSUE TITLE
For some users projects don't run when clicking the green flag

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#6139]
### Expected Behavior

Clicking the green flag from the project player should cause the project to start running.

### Actual Behavior

We've been getting reports from some users on Windows saying that when they click the green flag on the project page the project doesn't start.

>  I noticed that when I click the green flag next to the scratch project, it freezes and doesn't start. It works if I go inside the project scripts and do it manually...

When asked for an example project that shows this behavior I was given https://scratch.mit.edu/projects/390577962/, but I was not able to reproduce the issue on any browser.  scratch.mit.edu/projects/413349212 is another example.

I asked the user to send me a screenshot oft heir console, which showed this warning:
![Screen Shot 2020-08-31 at 11 33 17 AM](https://user-images.githubusercontent.com/1088291/91737992-daa66a00-eb7d-11ea-8fc1-69b36efe88ea.png)

### Steps to Reproduce

Load a project page
Click the green flag

The Help Wanted label here refers needing more information about the circumstances that cause this issue.  

### Operating System and Browser

Chrome 84 on Windows 10 (from the reporting user) Also Edge.

**Comment by apple502j** [comment]
The console warning is not related to the issue. I think it's a Kaspersky Safe Kids bug which causes project view counter to crash, as you triaged in LLK/scratch-www#4326

**Comment by BryceLTaylor** [comment]
I'm going to close this as a duplicate of LLK/scratch-www#4326
