### ISSUE TITLE
Flaky integration test: sign in/sign out

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#6148]
It succeeded once I ran it again
Unfortunately I accidentally overwrote my copy buffer

**Comment by BryceLTaylor** [comment]
@fsih  Which tests?

**Comment by fsih** [comment]
Sign in/sign out

**Comment by fsih** [comment]
wait a second maybe this was on www

**Comment by BryceLTaylor** [comment]
I'm going to close this.  If it happens again, please reopen with the failure messages.
