### ISSUE TITLE
The packed file is too large

### ISSUE THREAD

**Issue by LookForwordTomorrow** [LLK/scratch-gui#6184]
The packed scratch GUI file is too large (22m +). If NPM link is used, it will lead to the main.js It's very big. Do you have any solutions

**Comment by BoomerScratch** [comment]
I'm not sure what you mean. Are you running out of RAM? Then enable virtual RAM or swapfile.
If you mean that the GUI folder is really large, you can try `git clone https://github.com/LLK/scratch-gui --depth=1` and `npm install`. (then `npm link` it if you want)

**Comment by rschamp** [comment]
Hi @LookForwordTomorrow, the uncompressed file is large, but if you run the build with the environment variable `NODE_ENV` set to `production`, it will minify the bundle. This is harder to develop with, but will give a smaller bundle size.

Please reopen if you have any more specifics of the trouble you're running into.
