### ISSUE TITLE
Ask bubble should not autofocus

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#6194]
### Expected Behavior
Ask bubble should not autofocus.

### Actual Behavior
Ask bubble auto-focuses. By making and closing ask bubble repeatedly, this can be used to take over the focus from inputs, including report options.

### Steps to Reproduce
Repro project: https://scratch.mit.edu/projects/426898825/

### Operating System and Browser
Windows 10, Firefox 80, also works on Chrome

**Comment by BryceLTaylor** [comment]
@apple502j It seems like you had to put quite a lot of effort into making a project that does this.  Do you think it's likely that someone could accidentally get into this state?  Or possibly use this maliciously somehow?

**Comment by GrahamSH-LLK** [comment]
I can't see any malicious use, except making it impossible to sign in/report. I guess if it was paired with something that detected when your mouse was near the report button, it could prevent you from reporting anything there. This project also does that, but without the detection.

**Comment by Explosion-Scratch** [comment]
I honestly can't see anyone doing this (maybe qucchia, but not maliciously)  It sure is nice to be able to type your answer without clicking on the ask bubble though.

**Comment by jeffalo** [comment]
here are the blocks that make it work
![image](https://user-images.githubusercontent.com/40470736/93895095-bdce0400-fcef-11ea-855c-a1b74806d3d8.png)
i don't know how scratch's callstack works so it could probably be made with less blocks
