### ISSUE TITLE
Extensions Stick Around

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-gui#6196]
### Expected Behavior

If you click File > New on a project with extensions, the extensions should be cleared (before reload) on the new project.
### Actual Behavior

They stick around until reload
### Steps to Reproduce

Create a new project
Add an extension (Or extensions)
Click File > New
See Extensions
### Operating System and Browser

ChromeOS

**Comment by apple502j** [comment]
Duplicate of LLK/scratch-vm#1731

**Comment by BryceLTaylor** [comment]
Closing as duplicate
