### ISSUE TITLE
GET http://localhost:9080/static/extension-worker.js 404 (Not Found)

### ISSUE THREAD

**Issue by chrisruk** [LLK/scratch-gui#6200]
### Expected Behaviour

When I added one of our extension's via the scratch GUI, using 3.12 branches of both scratch-gui and 
scratch-desktop, the extension was added fine.

### Actual Behaviour

I just switched to using branches 3.13 of both scratch-gui and 
scratch-desktop.

When I add one of our extensions via scratch, the following message now appears in 
the devtools window:

```
extension-worker.js?52ab:2 GET http://localhost:9080/static/extension-worker.js 404 (Not Found)
./node_modules/scratch-vm/node_modules/worker-loader/dist/cjs.js?name=extension-worker.js!./node_modules/scratch-vm/src/extension-support/extension-worker.js.module.exports	@	extension-worker.js?52ab:2
eval	@	extension-manager.js?60db:163
loadExtensionURL	@	extension-manager.js?60db:158
handleItemSelect	@	extension-library.jsx?8a46:43
wrapper	@	index.js?9548:550
handleSelect	@	library.jsx?2257:124
wrapper	@	index.js?9548:550
handleClick	@	library-item.jsx?5ab8:38
```

And the extension doesn't appear

### Operating System and Browser

Linux

Any pointers would be most appreciated!

**Comment by apple502j** [comment]
I'm sure current version is 3.15 - try with that?

**Comment by chrisruk** [comment]
Thanks for the comment, 3.15 did work for me better :)

One of my extensions seems to work fine now, I'm just trying to diagnose an issue with the other, which I will file a separate issue for, as it involves mainly scratch-desktop.
