### ISSUE TITLE
I18N for blocks

### ISSUE THREAD

**Issue by felix2ch** [LLK/scratch-gui#621]
We know the i18n solution for gui is react intl.
What about blocks?
React intl seem not working for blocks.

**Comment by chrisgarrity** [comment]
@felix2ch react-intl won't work for the blocks, but we are working on a solution based on intl and format.js. It will use ICU format strings. In addition to being consistent with scratch-gui and scratch-www, ICU allows translators to reorder placeholder arguments as necessary. That is something that isn't possible with the Scratch 2.0 blocks translation.
