### ISSUE TITLE
There was more options option in Make list and variable.

### ISSUE THREAD

**Issue by sairam4123** [LLK/scratch-gui#6222]
There was more options option in Make list and variable. Where did it go?
I remember there was a more or advanced options in Make List and Variable.
Thank you.

**Comment by sairam4123** [comment]
If I'm in a Wrong place, please redirect me to the right place to ask this question. Thank you.

**Comment by apple502j** [comment]
I think you can only see them if you can create cloud variables.

**Comment by sairam4123** [comment]
Oh, what were the audio effects in Scratch 3 when it was being built?

**Comment by sairam4123** [comment]
And where can I find the audio library I find in Scratch 3?, Is it Open Source?

**Comment by apple502j** [comment]
All Scratch 3 source code is available at https://github.com/LLK - I'm not sure what you mean by "audio effects" though.

**Comment by sairam4123** [comment]
effects like Echo, Pan, and more.
`change echo effect by 12`

**Comment by apple502j** [comment]
scratch-audio.
