### ISSUE TITLE
Something I'll add to variables

### ISSUE THREAD

**Issue by willycoffee** [LLK/scratch-gui#6224]
If you use the show or hide variable blocks, the checkbox next to the variable doesn't tick.

Maybe make it automatically tick so people don't get confused.

**Comment by towerofnix** [comment]
This is already being tracked in #2032, and there's a PR I made a while ago which fixes it #4147, though still semi-blocked on a couple other PRs.

**Comment by willycoffee** [comment]
Oh ok.
