### ISSUE TITLE
Change Add Sprite, BG, Sound icons to have square proportions/optical alignment

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#623]
Currently we have natively sized icons, but we would like to move towards a standardized square viewbox on icons. This is similar to how the icons on blocks are created and exported.

- [x] Add Sprite
- [x] Add Backdrop
- [x] Record Sound
- [x] Add Sound
- [x] Add Extension

**Comment by carljbowman** [comment]
[add-icons.zip](https://github.com/LLK/scratch-gui/files/1333781/add-icons.zip)

**Comment by paulkaplan** [comment]
@carljbowman can this be closed? Those icons have all changed.
