### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by mkovalevski** [LLK/scratch-gui#6236]
I develop an extension for arduino and when I call a window, which is created by myself, with .html file I get such error in production mode (desktop version): `Not allowed to load local resource: file:///C:/Users/User/AppData/Local/Programs/Scratch Desktop/resources/app.asar/port-window.html`

I call this window in renderer.jsx file and my port-window.html located in the same directory with renderer.jsx
```
                let portWindow = new BrowserWindow({
                    width: 400,
                    height: 250,
                    frame: true,
                });`

                portWindow.loadURL(url.format({
                    slashes: true,
                    protocol: 'file:',
                    pathname: path.join(__dirname, 'port-window.html'),
                }));
```
Does somebody know how to fix it?

**Comment by cwillisf** [comment]
Since this is Electron-specific I think LLK/scratch-desktop#156 is a better place for this discussion
