### ISSUE TITLE
Same custom blocks,but different behaviors

### ISSUE THREAD

**Issue by alexwenbj** [LLK/scratch-gui#6245]
https://scratch.mit.edu/projects/433655392/
### Expected Behavior
The same custom blocks should have the same behaviors.
I defined two custom blocks named "mmm"  and "nnn",they have the same blocks.But when I invoked them individually, they act differently.

### Actual Behavior
Their behaviors are different.
![image](https://user-images.githubusercontent.com/12047524/95348210-63889200-08f0-11eb-9b17-9725bf60a78b.png)

Please see the screen shot,and switch the `mmm` and `nnn` invocation and observe the stage.
The mmm/nnn definitions as below, I just duplicated from one to another.
![image](https://user-images.githubusercontent.com/12047524/95348817-fd503f00-08f0-11eb-84dd-6af45ab76e13.png)

### Operating System and Browser
Mac OS 10.15.5, Chrome 85.0.4183.121,64 bits.

**Comment by apple502j** [comment]
"nnn" has "run without screen refresh" turned on, while "mmm" doesn't. Works as intended?

**Comment by alexwenbj** [comment]
Oh,gosh!My wrong,thank you. @apple502j
