### ISSUE TITLE
Send Feedback Button Leads To Inaccessible Topic

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-gui#6272]
### Expected Behavior

The send feedback button on scratch-gui should actually work, or not be there. 
### Actual Behavior

It's there and leads to an inaccessible topic. 

### Steps to Reproduce

Open scratch-gui on github pages
Click Button
See 403 Error
### Operating System and Browser

ChromeOS

**Comment by BryceLTaylor** [comment]
This is only on the master branch which is no longer part of development.
