### ISSUE TITLE
Saving issues with uploading projects

### ISSUE THREAD

**Issue by Chikorita-Lover** [LLK/scratch-gui#6287]
### Expected Behavior

My uploaded project from an `.sb3` file was expected to save on my Scratch account.

### Actual Behavior

My uploaded project kept saying "Saving project..." and never finished saving.

### Steps to Reproduce

1. Create a project and download it as an `.sb3` file
2. Upload the file to a new project/already-existing project
3. Wait for it to upload, then watch it save indefinitely

### Operating System and Browser

**Operating System**: Samsung Chromebook 3 and Windows 10 (doesn't seem to be a device issue)
**Browser**: Chrome (could be a browser issue)

### Notes
- A lot of other users seem to have this same issue, looking through the Scratch forums

**Comment by BryceLTaylor** [comment]
@Chikorita-Lover does this happen if you try to upload the default project?  As in, just the cat on a white background?

**Comment by Chikorita-Lover** [comment]
Actually this was patched recently and I was able to upload it yesterday, thanks for replying though!

**Comment by Explosion-Scratch** [comment]
Glad this was patched!
