### ISSUE TITLE
how i can change all the block 's language to other language ? Team should give many  plan

### ISSUE THREAD

**Issue by youngonlyforyou** [LLK/scratch-gui#629]
how i can change the all the block 's language to other language ? Team should give many  plan.
i want change the UI to other language ,include all block .

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-www/issues/1467

**Comment by zhlella** [comment]
This is Scratch3.0 by Javascript .That is Scratch2.0 by Flash. I don't know.
