### ISSUE TITLE
Download link does not get removed on legacy Edge

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#6293]
https://github.com/LLK/scratch-gui/blob/develop/src/lib/download-blob.js

Element `downloadLink` won't be removed if `navigator.msSaveOrOpenBlob` is called.

**Comment by BryceLTaylor** [comment]
@apple502j Can you describe the behavior that users should be seeing and what they are seeing?

**Comment by apple502j** [comment]
@BryceLTaylor This may not be visible - but at least a tech debt issue. May have slight memory leak.

**Comment by BryceLTaylor** [comment]
Closing because it does not seem to affect users and therefore we are unlikely to address it.
