### ISSUE TITLE
Some UI looks like 2.0 still. Ugh.

### ISSUE THREAD

**Issue by aetinx** [LLK/scratch-gui#6299]
### Expected Behavior

_Look like home screen UI_

### Actual Behavior

_Looks like 2.0_

### Steps to Reproduce

_Go to any profile_

### Operating System and Browser

_Any_

**Comment by Explosion-Scratch** [comment]
Yup! Longtime issue, Maximouse made a nice fix though. It's a userstyle
that just makes it look instantly better.

**Comment by ghost** [comment]
Firstly, browser extensions including userstyles are not allowed to be advertised on Scratch, and I think it extends here. Secondly, this repository is for the Scratch Editor only, not for the rest of the Website. Thirdly, profile page are stored in a private repository, and are only meant to be discussed in the Scratch Forums.

**Comment by Explosion-Scratch** [comment]
@SausageMcSauce sorry! I'll keep that in mind, (I also might note that
sharing any functional code snippets is not allowed and this definitely
dosen't obey that! The whole repo is functional (hopefully) code!)

**Comment by jeffalo** [comment]
also keep in mind, this repo, scratch-gui is for the editor. what you're talking about is the migration from scratchr2 pages to scratch-www which has been going on for a few years. I'm pretty sure they know that they need to migrate their pages so making a github issue like this one is probably not too necessary :)

**Comment by BryceLTaylor** [comment]
Transferring pages from the old style to the new style is still in progress.  We do not consider it to be a bug.  If you find issues with functionality scratchr2 pages (such as profile pages) you can file issues on the scratch-www repository, but be aware that we may move them to a closed source repository.

**Comment by GrahamSH-LLK** [comment]
> Firstly, browser extensions including userstyles are not allowed to be advertised on Scratch, and I think it extends here. Secondly, this repository is for the Scratch Editor only, not for the rest of the Website. Thirdly, profile page are stored in a private repository, and are only meant to be discussed in the Scratch Forums.

As far as I know, it doesn't extend here.
