### ISSUE TITLE
npm package.json script i18n:msgs

### ISSUE THREAD

**Issue by demongodYY** [LLK/scratch-gui#630]
### Expected Behavior

fix npm run i18n:msgs error in windows

### _Describe what actually happens_

fix code scripts : {      .....
                             "i18n:msgs": "node ./scripts/generate-locale-messages.js", 
                             .....
                       }
in package.json with develop branch.

### Operating System and Browser

windows10 1703

**Comment by thisandagain** [comment]
@demongodYY Could you share what the error is that you are seeing? What type of shell are you using (e.g. PowerShell, Cygwin, etc.)?

**Comment by demongodYY** [comment]
when I type "npm run i18n:msgs" or "npm start" on shell ,  it will run  ./scripts/generate-locale-messages.js ,and show( '.' Is not an internal or external command, nor is it a program or batch file that can be run).
     I use both CMD and PowerShell will occur this error

**Comment by thisandagain** [comment]
@demongodYY Thanks. I figured the `./` was the issue but it's nice to know for sure.
