### ISSUE TITLE
npm start ERR

### ISSUE THREAD

**Issue by xmagicbox** [LLK/scratch-gui#632]
"npm install"  is OK,but"npm start" get the belows:

Google Cloud Ubuntu 16.04 LTS

root@instance-3:~/scratch/scratch-gui# sudo npm start

> scratch-gui@0.1.0 start /root/scratch/scratch-gui
> npm run i18n:msgs && webpack-dev-server

> scratch-gui@0.1.0 i18n:msgs /root/scratch/scratch-gui
> ./scripts/generate-locale-messages.js

/root/scratch/scratch-gui/scripts/generate-locale-messages.js:50
let messages = locales.reduce((collection, lang) => {
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
npm ERR! Linux 4.10.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "i18n:msgs"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! scratch-gui@0.1.0 i18n:msgs: `./scripts/generate-locale-messages.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scratch-gui@0.1.0 i18n:msgs script './scripts/generate-locale-messages.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scratch-gui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/generate-locale-messages.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scratch-gui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scratch-gui
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /root/scratch/scratch-gui/npm-debug.log
npm ERR! Linux 4.10.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! scratch-gui@0.1.0 start: `npm run i18n:msgs && webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scratch-gui@0.1.0 start script 'npm run i18n:msgs && webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scratch-gui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run i18n:msgs && webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scratch-gui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scratch-gui
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /root/scratch/scratch-gui/npm-debug.log

**Comment by paulkaplan** [comment]
Hi, looks like you are on node 4.2.6 from the trace. `scratch-gui` is only tested with node 6+. That doesn't seem to be documented anywhere, our bad.

**Comment by xmagicbox** [comment]
ths，i update to node 8.x, it works!
