### ISSUE TITLE
Does not compile.

### ISSUE THREAD

**Issue by josiauh** [LLK/scratch-gui#6338]
### Expected Behavior

It should compile and make the GUI (or Graphical User Interface) Appear 

### Actual Behavior

It fails to compile and destroys the GUI completely.

### Operating System and Browser

Mac OS Catalina Chrome

**Comment by BryceLTaylor** [comment]
@Mar10Josh can you provide more information on what you did to cause the failure? We need a list of reproduction steps.

**Comment by josiauh** [comment]
I dunno

**Comment by josiauh** [comment]
Solution found: use the depth on git clone.
