### ISSUE TITLE
Block with multi-line input field

### ISSUE THREAD

**Issue by felix2ch** [LLK/scratch-gui#635]
We can create a multi-line block in google blockly for many input field, It looks great.
In scratch , It will be a incredible long block.
Is there a solution for this situation?

Thanks.

**Comment by thisandagain** [comment]
Scratch does not have plans to support multi-line text input fields. What are you trying to accomplish?

**Comment by felix2ch** [comment]
It doesn't mean multi-line text input in single input field, It have multi-input fields.
Like a block below.
<img width="231" alt="screen shot 2017-08-22 at 10 13 58 am" src="https://user-images.githubusercontent.com/6711220/29545761-b44698b6-8722-11e7-8c63-9a902f026b8e.png">

**Comment by thisandagain** [comment]
Ah. I see. No, we will not be supporting blocks in this format.
