### ISSUE TITLE
 How to monitor the blocks on screen?

### ISSUE THREAD

**Issue by FelipeBit** [LLK/scratch-gui#6351]
Hi guys, I'm doing an academic work and I would like to know if there is any way to monitor the blocks on screen, insertions, deletions, know which ones are connected, etc ...

**Comment by apple502j** [comment]
Maybe https://github.com/LLK/scratch-vm/blob/develop/src/engine/blocks.js#L301 ?

**Comment by FelipeBit** [comment]
Thank you very much, this is what I was looking for
