### ISSUE TITLE
my project can not load preview cat in android webview

### ISSUE THREAD

**Issue by jimmyspace** [LLK/scratch-gui#6427]
my project can not load preview cat in android webview, but it can load in mobile browser

waring in sandroid studio

 E/chromium: [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
 E/chromium: [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
 E/chromium: [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
 E/chromium: [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
 E/chromium: [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw

**Comment by rschamp** [comment]
It sounds like you're trying to build a custom app using the GUI. Unfortunately we can't provide support for this. Please reopen with more specific information if not.
