### ISSUE TITLE
Fullscreen mode on mobile chops off rightmost third of stage

### ISSUE THREAD

**Issue by tomrow** [LLK/scratch-gui#6453]
In fullscreen mode on Android, the aspect ratio is warped and the stage edge cuts off part of the image.
Phone model used to take this screenshot is Samsung Galaxy S10+.

![Screenshot_20201205-205556_Scratch](https://user-images.githubusercontent.com/10169982/101265277-0fa5f800-373d-11eb-8433-185ca0fc4b53.jpg)
Phone
![scratch_correct](https://user-images.githubusercontent.com/10169982/101265280-159bd900-373d-11eb-9745-d1d499f38149.png)
Correct aspect ratio scaling as taken from a Windows PC

**Comment by tomrow** [comment]
To clarify; this is the offline app, and not the website

**Comment by BryceLTaylor** [comment]
We do not support phones for the android mobile app.  It is intended only for tablets.

**Comment by tomrow** [comment]
IMO this should probably still be considered since it could probably be triggered on tablets too as long as they have an unusual aspect ratio.
