### ISSUE TITLE
The 2nd loaded project (pen related projects?) does not work when greenflag clicked

### ISSUE THREAD

**Issue by gengshenghong** [LLK/scratch-gui#647]
### Expected Behavior

Everything should just work.

### Actual Behavior

Nothing happened.

### Steps to Reproduce
1. open https://llk.github.io/scratch-gui/develop/
2. load project draw_circle.json
3. click green flag to run it (do make sure this is done)
4. load project draw_square.json
5. click green flag to run it, now, nothing happened on the stage. There is no issue on the project, if you load this one first, it will work. Whatever, the 2nd loaded project does not work.

Note: At the beginning, I thought the 2nd loaded project will always fail (I mean, it is an issue of "loadproject" function), but when I write another 2 project (one is move 10 steps when green flag clicked, one is to turn right when green flag clicked), and no issue for them. So, I think the issue is something related to pen stuff. If I do not click green flag after 1st project loaded and load 2nd project directly, it works....

### Operating System and Browser
Ubuntu 14.04, Chrome Version 50.0.2661.94 (64-bit), I guess this is not related to the issue, all OSes should reproduce it.

The project code:
![image](https://user-images.githubusercontent.com/1018468/29758762-af0433fc-8be8-11e7-929e-e8b82bde9b8e.png)

![image](https://user-images.githubusercontent.com/1018468/29758775-bd4854ca-8be8-11e7-888b-bc71c152bf6a.png)

**Comment by thisandagain** [comment]
Thanks @gengshenghong. Could you link us to the two project JSON files?

**Comment by gengshenghong** [comment]
Uploaded the two projects json (changed a little...) using gist (as github does not support .json file here).

https://gist.github.com/gengshenghong/2830470b7719be1cbd26ee4a6b0a6d8d

**Comment by paulkaplan** [comment]
Looks like these are now fixed
