### ISSUE TITLE
It corrupts custom-made SVGs from Scratch 2

### ISSUE THREAD

**Issue by Kouzeru** [LLK/scratch-gui#6484]
### Expected Behavior

![chrome_hgdYo5fXHp](https://user-images.githubusercontent.com/46141631/102112686-03274b00-3e73-11eb-9e6f-cda1e6f8d899.png)

### Actual Behavior

The same project loaded into latest version of Scratch 3
![fAR80AAAAASUVORK5CYII](https://user-images.githubusercontent.com/46141631/102112673-fefb2d80-3e72-11eb-863f-a5aba6e5a828.png)

### Steps to Reproduce

Download the sb2 project https://kouzeru.github.io/phsphr60/sb2/gd.sb2
And load the project on https://scratch.mit.edu/projects/editor/ they'll broken
There is no issue when loaded on https://llk.github.io/scratch-gui/master/

### Operating System and Browser

Windows 10, latest Chrome

**Comment by apple502j** [comment]
Duplicate of LLK/scratch-paint#1320

**Comment by kchadha** [comment]
Closing as duplicate of LLK/scratch-paint#1320 which has been fixed.
