### ISSUE TITLE
Stage/Backdrop Area

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#65]
We need to refine the design of this pane

**Comment by carljbowman** [comment]
# 2.0 - Stage Area
<img width="82" alt="screen shot 2017-02-07 at 4 50 40 pm" src="https://cloud.githubusercontent.com/assets/3409578/22713230/9585442a-ed55-11e6-9433-7ae1c4ae042e.png">

## Add Backdrop
<img width="81" alt="screen shot 2017-02-07 at 4 51 53 pm" src="https://cloud.githubusercontent.com/assets/3409578/22713272/bea3d06a-ed55-11e6-9e3c-96f79f3500c0.png">

- via Backdrop Library
- via Creating in Paint Editor
- via Local File Upload
- via Photo Capture

## Selection
Shifts the Editors focus to the Stage (e.g. workspace relative to Stage)
![stage selection](https://cloud.githubusercontent.com/assets/3409578/22713393/46237a04-ed56-11e6-9348-c2ae709d8bdb.gif)

- The Stage can be selected by clicking on the Stage in the Stage Area

## Stage Info
<img width="81" alt="screen shot 2017-02-07 at 4 58 47 pm" src="https://cloud.githubusercontent.com/assets/3409578/22713505/b8be7b2c-ed56-11e6-8191-e76f77185750.png">

- Displays the amount of Backdrops

**Comment by carljbowman** [comment]
# 3.0 - Animation Playtest Prototype

### Overview
<img width="786" alt="screen shot 2017-02-07 at 5 00 48 pm" src="https://cloud.githubusercontent.com/assets/3409578/22713563/ff11f82e-ed56-11e6-87ca-e416fb86b80c.png">

#### In Scope
- [ ] Add Backdrop
  - [ ] via Library
- [ ] Selection
  - [ ] Direct Selection
- [ ] Stage Info
  - [ ] Backdrop Count

#### Out of Scope
- Add Sprite 
  - via Creating in Paint Editor
  - via Local File Upload
  - via Photo Capture

---

![r1_gui_animate-prototype](https://cloud.githubusercontent.com/assets/3409578/22697557/c8047122-ed1f-11e6-8215-b79034bb80c5.png)

## Add Backdrop
<img width="91" alt="screen shot 2017-02-07 at 5 06 59 pm" src="https://cloud.githubusercontent.com/assets/3409578/22713800/ddf14d06-ed57-11e6-8ef3-2b009232582b.png">

- Single Button that opens the Backdrop Library
- Same styling as 'Add Sprite' button 

## Selecting a Stage
<img width="82" alt="screen shot 2017-02-07 at 5 11 48 pm" src="https://cloud.githubusercontent.com/assets/3409578/22713977/89d4240e-ed58-11e6-98e9-093718db5159.png">

- Selection stoke
- Interaction states (e.g. hover) TBD

## Stage Info
<img width="84" alt="screen shot 2017-02-07 at 5 13 19 pm" src="https://cloud.githubusercontent.com/assets/3409578/22714032/bfd5823c-ed58-11e6-97f2-2f4096cdbe8b.png">

- 'Stage' Label
- Backdrop count (updates based on the amount of backdrops)
- 'Backdrops' Label

**Comment by Airhogs777** [comment]
The text "Selecting a Stage" and the plus button make it seem like in Scratch 3 you'll be able to create multiple stages (as opposed to multiple backgrounds in one stage)

**Comment by CosmicWebServices** [comment]
Not that it is a bad thing...

**Comment by carljbowman** [comment]
@Airhogs777 - That's a great observation. Def something we should think some more about. 

In 2.0 that you can add 'Backdrops' to the Stage from the Stage Area, but you cannot add 'Costumes' to a 'Sprite' from the Sprite Area, one must go the the 'Costumes Tab / Paint Editor'. 

To your point the UI being the same does not help to clarify this distinction. Something to iterate on.

**Comment by carljbowman** [comment]
@lifeinchords - Updated specs based on our conversation about https://github.com/LLK/scratch-gui/pull/134

**Comment by lifeinchords** [comment]
Updated!
![screen shot 2017-02-27 at 7 29 10 pm](https://cloud.githubusercontent.com/assets/716168/23386196/10a0cd96-fd23-11e6-8ecb-9b635983431b.png)

Re: the border issue, chatted with @rschamp, it's `canvas` related, not CSS. Let's make an issue after about this.
