### ISSUE TITLE
Travis CI Badge Has Not Been Removed

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-gui#6503]
### Expected Behavior

This is not an issue with the code but the README. The badge should not even be there since Travis CI has been replaced with Circle CI.

### Actual Behavior

The badge is still there.

### Steps to Reproduce

Just read the README.md.

### Operating System and Browser

N/A

**Comment by ghost** [comment]
The Greenkeeper badge should also be removed as Scratch has switched to Dependabot.
