### ISSUE TITLE
Errors on Loading a Saved Project

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-gui#654]
### Expected Behavior

Loading a project should open the project.

### Actual Behavior

I get the error:
![image](https://user-images.githubusercontent.com/8440451/29823804-b9cb509e-8c9d-11e7-9ee7-e7fa1251b0c3.png)
Creating a new sprite resulted in:
![image](https://user-images.githubusercontent.com/8440451/29824177-c1d4046a-8c9e-11e7-9ca0-95a1b2ff39a6.png)
The new sprite replaces the scratch cat and the backdrop is missing.
The error only occurred in Scratch GUI and not in Scratch VM.

### Steps to Reproduce

1. Download (created by calling save on a new project): [project-8-29-2017-9-40-23 AM.txt](https://github.com/LLK/scratch-gui/files/1260478/project-8-29-2017-9-40-23.AM.txt)
2. Change the extension from .txt to .json (because you can't upload JSON).
3. navigate to https://llk.github.io/scratch-gui/
4. Click load, and navigate to the file

### Operating System and Browser

Ubuntu 17.06, Chrome 60.0.3112.101

**Comment by Kenny2github** [comment]
Repro-ed on Chrome 57 Raspbian Pixel Desktop, with same errors.

**Comment by rschamp** [comment]
Fixed in #611. Please note that the most up to date build is viewable at https://llk.github.io/scratch-gui/develop/
