### ISSUE TITLE
Save Picker

### ISSUE THREAD

**Issue by u254254** [LLK/scratch-gui#6540]
## Feature suggestion (Save File Picker)
<img width="248" alt="스크린샷 2021-01-06 오후 12 44 10" src="https://user-images.githubusercontent.com/72965213/103726858-3d70ac00-501d-11eb-94e7-dc225be05590.png">
@TurboWarp uses draft FileSystem API to save file.
<img width="610" alt="스크린샷 2021-01-06 오후 12 50 03" src="https://user-images.githubusercontent.com/72965213/103727083-b5d76d00-501d-11eb-8ff5-ccfb5e9b851f.png">

**Comment by apple502j** [comment]
No support. FileSystem API is too new to be used in production. Look, my browser doesn't support it yet.
