### ISSUE TITLE
SBFileUploader should specify accept file formats in MIME types, not extensions.

### ISSUE THREAD

**Issue by mumez** [LLK/scratch-gui#6575]
https://github.com/LLK/scratch-gui/blob/develop/src/lib/sb-file-uploader-hoc.jsx#L79

iOS Safari does not support `<input type="file" accept=".sb,.sb2,.sb3">` type notation, which uses file extensions for the accept attribute value. So for the broader compatibility, MIME-type format like "application/x-scratch3" would be preferable when setting the accept attribute.

https://caniuse.com/input-file-accept

**Comment by BryceLTaylor** [comment]
Can you describe the problem that the user sees and the steps they need to take in order to see the problem?

**Comment by mumez** [comment]
Sometimes .sb3 files are grayed out in file upload dialog. It is seen on iPad only. I guess it is related to the accept format.
![ErlQ4WYVQAM53Jr](https://user-images.githubusercontent.com/705350/104672705-a2b25480-5723-11eb-9d58-493725bdcc5d.jpg)

**Comment by mumez** [comment]
I've found that .sprite3 files are always grayed out regardless of platforms. This fact shows that the `accept=".sb,.sb2,.sb3"` notation actually works even on iOS Safari. So my guess was wrong.
I was unable to detect the exact reason why .sb files were grayed on iOS Safari. It is okay to close the issue now. 
![IMG_492A32F0907C-1](https://user-images.githubusercontent.com/705350/104730184-ee451c80-577c-11eb-8f15-c94a1c5fb23f.jpeg)
