### ISSUE TITLE
Duplicate variable monitors are created when switching to/from the Data category

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#658]
![img](https://user-images.githubusercontent.com/13041273/29862962-c48d028a-8da0-11e7-9232-144be9d4c3f2.png)

---
Moved from LLK/scratch-blocks#1066
/cc @Micircle @kenny2github

**Comment by thisandagain** [comment]
Putting in the November milestone to match up with scheduling for the rest of variables / lists. Does that seem reasonable to you @rschamp and @fsih ?

**Comment by paulkaplan** [comment]
Fixed by https://github.com/LLK/scratch-blocks/pull/1182
