### ISSUE TITLE
npm run watch stuck

### ISSUE THREAD

**Issue by MarkKocherovsky** [LLK/scratch-gui#6618]
### Expected Behavior

I am trying to run the npm run watch command as shown here: https://github.com/LLK/scratch-gui/wiki/Getting-Started#example-scratch-gui-vm-and-blocks-linked](https://github.com/LLK/scratch-gui/wiki/Getting-Started#example-scratch-gui-vm-and-blocks-linked). I expect it to run the command and then return to the command line so I can continue.

### Actual Behavior

However, it gets stuck on ``Entrypoint main = 829006d1e432e3295097.worker.js 829006d1e432e3295097.worker.js.map``
![image](https://user-images.githubusercontent.com/67556945/105077602-bda20300-5a5a-11eb-923a-fd8bfbe1fce2.png)

I am not sure whether or not this just takes a very long time to run, or if there is something wrong with my setup.

### Steps to Reproduce

I'm not entirely sure, as I was going through the Getting Started Tutorial above.

### Operating System and Browser

Windows 10, Ubuntu for Windows 20.04.1, NodeJS version 15.6.0, npm version 7.4.0

**Comment by apple502j** [comment]
Nope. You need a new console, it's not stuck, it's just waiting for changes...

Does localhost:8601 show anything?

**Comment by MarkKocherovsky** [comment]
> Nope. You need a new console, it's not stuck, it's just waiting for changes...
> 
> Does localhost:8601 show anything?

Only "This site can't be reached"

Should I just wait for the process to finish?

**Comment by apple502j** [comment]
I don't think `npm run watch` finishes. It builds then waits for changes in the files.

What happens with `npm start`?

**Comment by MarkKocherovsky** [comment]
> I don't think `npm run watch` finishes. It builds then waits for changes in the files.
> 
> What happens with `npm start`?

It runs and returns "Compiled Successfully", and is now waiting.

**Comment by apple502j** [comment]
Then it's working fine. The command never finishes, unless you press Ctrl+C and kill the server.

**Comment by MarkKocherovsky** [comment]
> Then it's working fine. The command never finishes, unless you press Ctrl+C and kill the server.

Alright, thanks
