### ISSUE TITLE
Moving into "Create Variable" button a certain way makes it unclickable

### ISSUE THREAD

**Issue by joker314** [LLK/scratch-gui#662]
### Expected Behavior

When you place your mouse pointer outside the "Create Variable" button, just below the right padding, and quickly move it into the button, into the right padding, then the cursor should become "pointer" and the button should be clickable

### Actual Behavior

The button isn't clickable and the pointer remains on the default. It only switches cursor and becomes clickable when you hover over the actual text, and then you can move the cursor back to where it was (over the right padding) and it'll still be clickable there too

### Steps to Reproduce

1) Visit https://llk.github.io/scratch-gui/develop/
2) Click on the "Data" category
3) Hover your mouse just below the right padding (red dot)
4) Move it sharply up (if you let the pointer sit on the border, it won't work)
5) The cursor should now be on the right padding
6) The button isn't clickable (try clicking)
7) The cursor isn't a pointer (indicating it's not clickable)

It will however work if you

8) Move the cursor left, over the text
9) Move it back

### Operating System and Browser

Windows 10 Chrome 60.0.3112.113

**Comment by thisandagain** [comment]
@rschamp @paulkaplan @fsih Should this be moved to `scratch-blocks`?

**Comment by thisandagain** [comment]
Can repro in both `scratch-gui` and `scratch-blocks`. Moving to `scratch-blocks`.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-blocks#1073
