### ISSUE TITLE
Variables containing XML tags being mistreated

### ISSUE THREAD

**Issue by joker314** [LLK/scratch-gui#665]
### Expected Behavior

Creating a variable with the name `<hi>Some text</hi>` should render as `<hi>Some text</hi>`

### Actual Behavior

Creating a variable with the name `<hi>Some text</hi>` renders as `Some text`

### Steps to Reproduce

Go to the "Data" category, click "Create Variable", then type `<hi>Some text</hi>` and click "OK"

### Operating System and Browser

Windows 10, Chrome 60.0.3112.113

**Comment by Kenny2github** [comment]
This also allows variables with (seemingly) identical names:
![test](https://user-images.githubusercontent.com/28599280/30205587-cedb92f2-94bb-11e7-983c-fdfcd0edef4c.png)
||
V
![test](https://user-images.githubusercontent.com/28599280/30205620-ec1b38f4-94bb-11e7-8425-fad5e2bf74b8.png)

**Comment by Scimonster** [comment]
I'll work on this bug. After a bit of research, the issue seems to actually lie in the [scratch-blocks](/LLK/scratch-blocks) repo.

**Comment by Scimonster** [comment]
So, the part about the block names in the palette was in [scratch-blocks](/LLK/scratch-blocks), and fixing it on stage monitors was in [scratch-vm](/LLK/scratch-vm). Just submitted PR LLK/scratch-vm#701 to fix it there.

I recommend closing this after those two are resolved.

**Comment by towerofnix** [comment]
Apparently [fixed](https://github.com/LLK/scratch-blocks/pull/1114#issuecomment-338213003):

> Upstream merge solved this! Thanks for the patience.

**Comment by Scimonster** [comment]
@towerofnix Well, one of the two parts was fixed.

**Comment by Scimonster** [comment]
Second PR has been merged; this issue can be closed.

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-vm/pull/701
