### ISSUE TITLE
Menu bar

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#67]

**Comment by carljbowman** [comment]
The menu bar has been simplified for the Animate a Name / Word playtest prototype. For this prototype we just need a nav-like band with the logo and prototype name.

![r1_gui_animate-prototype_menu-bar](https://cloud.githubusercontent.com/assets/3409578/22653099/860a0d50-ec56-11e6-8aae-5353bcccb793.png)

Eventually this bar will include menu systems like 'File', 'Edit', Shared Status, and so on...

**Comment by thisandagain** [comment]
@lifeinchords I believe this is done enough to close, correct?

**Comment by lifeinchords** [comment]
Yup!

**Comment by SillyInventor** [comment]
Should there be a separate tracker for the file and edit drop-downs?

**Comment by thisandagain** [comment]
Yes, but we need a design spec for that first which we are still tracking in #1
