### ISSUE TITLE
"Loading Project" screen displays for too long on Safari Mobile 14

### ISSUE THREAD

**Issue by dominic-03** [LLK/scratch-gui#6728]
### Expected Behavior

Empty projects should load in 3 seconds or less, which was the behavior of Safari Mobile 13.

### Actual Behavior

Empty projects can take up to a minute to load, even on fast WiFi connections.

### Steps to Reproduce

Install iPadOS 14-14.4, create a new project

### Operating System and Browser

iPadOS 14.4, Mobile Safari 14.0.3

### Additional notes

~~This happens on multiple WiFi networks.~~ It does not happen on Chrome Mobile or on iPads running iPadOS 13 or earlier. It also does not happen on Chrome Mobile 87. The project clearly isn't actually loading, as even empty projects will display this loading screen for too long.

**Comment by apple502j** [comment]
This may be related to font loading (projects don't load until all fonts are loaded)

Gonna make a mod for testing.

**Comment by BryceLTaylor** [comment]
I could not reproduce this on ipadOS 14.0.1.  Does it only happen on 14.4?

**Comment by dominic-03** [comment]
Actually, I can't seem to reproduce it now. I could do it fine at school, I thought I remembered it happening at home but maybe not?

Either way, it loads fast at school in Chrome or iPadOS 13 and slowly in iPadOS 14, so while the network may be a problem loading must be handled differently between the two.

**Comment by BryceLTaylor** [comment]
I just updated to 14.4 and couldn't reproduce it.

**Comment by dominic-03** [comment]
> I just updated to 14.4 and couldn't reproduce it.

I can't either, unless I'm at school. Which gives a different issue: Why is loading handled differently between browsers? (And what element is being blocked? But that's not as important)

I'm assuming my school blocks a piece of Scratch that tries to load. In iPadOS 13, it apparently ignored the loading error, but iPadOS 14/Safari will continue trying to load it.

I'm confused now. Should I open a new issue? This problem seems to be different from what I originally thought.
