### ISSUE TITLE
In Windows TargetPane does't display well

### ISSUE THREAD

**Issue by pyz1989** [LLK/scratch-gui#673]
### Expected Behavior
TargetPane should display well.
### Actual Behavior
Visit  [scratch-gui home page](https://llk.github.io/scratch-gui/), TargetPane does't display well.
### Steps to Reproduce
Just visit  [scratch-gui home page](https://llk.github.io/scratch-gui/)

![impression drawing](http://i2.bvimg.com/524586/5f687eff12ba57d6.png)
A part of Stage is disappear.
### Operating System and Browser
Windows 10,  Chrome 61

**Comment by Kenny2github** [comment]
There is a "develop" branch of the editor, with the most up-to-date changes, located at https://llk.github.io/scratch-gui/develop. This issue was resolved on that branch in #606.
