### ISSUE TITLE
incorrect color effect for white area on phone/pad

### ISSUE THREAD

**Issue by gengshenghong** [LLK/scratch-gui#674]
### Expected Behavior

It should work like in Desktop browser...

### Actual Behavior

When set color effect to something larger than zero (for example, 1...10...), the sprite's white area (maybe it is transparent area?) becomes black.

### Steps to Reproduce

On iPhone or Android:
1. Open llk.github.io/scratch-gui/develop
2. drag "set color effect to xxx" block in "looks" category to workspace
3. click the block to run it
4. issue as below:
![img_3909](https://user-images.githubusercontent.com/1018468/30210120-c83d419a-94cd-11e7-9c93-d3491a12e9b5.PNG)

### Operating System and Browser
It works on my Mac OS X (MacBook Air) Safari browser, and my Ubuntu Chrome browser. But failed on both my iPhone (which is Safari) and my Android tablet (in Chrome browser). So, it seems not an issue of browser but an issue of "mobile" comparing with PC???

**Comment by rschamp** [comment]
Moved to LLK/scratch-render#168
