### ISSUE TITLE
Publishing to GitHub Pages doesn't work

### ISSUE THREAD

**Issue by jmg460** [LLK/scratch-gui#6783]
### Expected Behavior
I've followed this wiki page: https://github.com/LLK/scratch-gui/wiki/Publishing-to-GitHub-Pages/38da021fa9db0a483599f0ebd9ca5939e5f0b325

It should install a private build using Travis CI

### Actual Behavior
It doesn't work.  I get this message: "Oh no! You tried to trigger a build for [github_username]/scratch-gui but the request was rejected."

### Steps to Reproduce
If you follow the Automatic steps using Travis CI steps here: https://github.com/LLK/scratch-gui/wiki/Publishing-to-GitHub-Pages/38da021fa9db0a483599f0ebd9ca5939e5f0b325 you will get this error

**Comment by apple502j** [comment]
I think since that we started using CircleCI? So old config for Travis is deleted.

**Comment by jmg460** [comment]
I will have to check out CircleCI.  I read that Travis CI needed a travis.yaml (and I noticed the dev REPO didn't have one), but I didn't know for sure because I am new to this stuff.  Thank you!

**Comment by chrisgarrity** [comment]
@jmg460 as mentioned the Scratch Team has started using CircleCI instead of travis. To automatically publish a branch on a fork you would need to set up travis or circleCI for yourself as you will not have the authorization to use the Scratch organization's credentials.
