### ISSUE TITLE
How to load custom sprites/costumes from local server dynamically?

### ISSUE THREAD

**Issue by alexwenbj** [LLK/scratch-gui#6787]
### Expected Behavior
In Scratch 2.0, the sprites/costumes assets are store in JSON files such as sprites.json/costumes.json located in server, when open the Scratch sprite tab to select sprite, it will firstly pull the sprites.json(costumes.json) and parse it, then download the sprites from server and render in Scratch. But in scratch 3, it seems remove this function, and only pack all the sprites/costumes during build. My question is ,how to load the sprites.json from server to use my own sprites/costumes? (The sprites/costumes can be replaced frequently, so I don't want to rebuild the scratch every time)

Thank you.

**Comment by apple502j** [comment]
Current impl expects libraries to be loaded synchronously. You can change that, but that's kinda pain. Building Scratch is faster (takes less than 5 minutes)

**Comment by alexwenbj** [comment]
Got it, thank you.
