### ISSUE TITLE
Don't replace costumes that have failed to load with ? sprites

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#6838]
### Expected Behavior

Costumes that fail to load should not replace the asset in your project.  When it fails to load or display, it should temporarily put a placeholder asset (the ? ) onto the stage, but not actually replace the content of the costume.

When the project saves, since the ? asset is not actually part of the project it would not overwrite the original asset in the project.json or the asset on the server.  Design will be needed to figure out what to do when the project is saved locally.

There should be some indication of the problem in the costumes tab when the costume is selected, including the costume tile and something in the paint editor itself when it is selected.

This should be the case for both vector and bitmap costumes that fail to load/display.  

### Actual Behavior

Currently, when an svg fails to load it is replaced with a question mark (?) placeholder asset.   When we do this it actually replaces the asset in the scratch project and saving the project changes the asset id in the project.json to the ? image.  This is destructive to people's work, especially if the failure to load is temporary or a regression that is fixed after a short time.

Also, when a bitmap fails to load it causes a BSOD (Blue Screen of Death), preventing the whole project from loading.

**Comment by kchadha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prevent Data Loss During Issues of Loading Assets (Grey Question Mark Issue)](https://trello.com/c/nSCfUx0M/40-prevent-data-loss-during-issues-of-loading-assets-grey-question-mark-issue)

**Comment by kchadha** [comment]
The vector costume part of this was resolved in LLK/scratch-vm#3637

**Comment by kchadha** [comment]
Re-reading this, the UX phase of this work should be tracked in a separate feature:

> There should be some indication of the problem in the costumes tab when the costume is selected, including the costume tile and something in the paint editor itself when it is selected.
>
> This should be the case for both vector and bitmap costumes that fail to load/display.
