### ISSUE TITLE
Reporters can overflow stage

### ISSUE THREAD

**Issue by JGames101** [LLK/scratch-gui#684]
If the content of a reporter is longer than what could be contained inside of the stage, instead of being cut off, it continues to grow downwards, above the sprite information and list.
![scratch 3 0 gui - google chrome 2017-09-16 1_31_54 pm](https://user-images.githubusercontent.com/23436667/30515801-8375ef1e-9ae3-11e7-971c-a2aefdfccae4.png)

**Comment by Kenny2github** [comment]
**raises eyebrow** Repro-d on Chrome 60 Windows 10:
![image](https://user-images.githubusercontent.com/28599280/30519208-a326812c-9bc2-11e7-82bc-dd70504915bb.png)

**Comment by LFP6** [comment]
As a thought I'd think an internal scrollbar would be better than cutting it off. Also, I'd usually prefer resizing it to a set size as opposed to just arbitrary resizes.

Haven't looked into what's supposed to happen with this, so I'm just throwing these out there in case it hadn't been brought up.

**Comment by thisandagain** [comment]
Tracking in #463

LOL @ that repro @Kenny2github 😄
