### ISSUE TITLE
What is the sampleCount mean and how to get it from wav file?

### ISSUE THREAD

**Issue by alexwenbj** [LLK/scratch-gui#6849]
I found that in sounds.json file, there is a property "sampleCount" for every wav file,what is it mean and how to get it from wav file?(I can get the sampleRate,etc)
Thank you.

**Comment by apple502j** [comment]
seems like it's length of `AudioBuffer.getChannelData()`

**Comment by alexwenbj** [comment]
@apple502j got it, thank you.
