### ISSUE TITLE
Sounds Editor : Uncaught TypeError

### ISSUE THREAD

**Issue by Zhuhp** [LLK/scratch-gui#690]
Click the 'Sounds' tab, can't load content
![qh1mmqxbpjkjcicz r gxy](https://user-images.githubusercontent.com/7781876/30573478-baf60c9a-9d26-11e7-8109-197405929a06.png)

And get error:
![avz jo ycj 1 q ks46 w](https://user-images.githubusercontent.com/7781876/30573592-5cdb8b70-9d27-11e7-8b3b-4c6305892902.png)

Cloning the lastest project and Compiling, then execute 'npm run start'

The error appears in Window 10  Chrome  61.0.3163.91

In Mac OS 10.12.6  Chrome  61.0.3163.91, the error not appears

**Comment by thisandagain** [comment]
@ericrosenbaum are you able to repro this?

**Comment by ericrosenbaum** [comment]
@fsih or @cwillisf looks like this is appearing on windows 10- could one of you please have a look?

**Comment by fsih** [comment]
I'm not able to repro on Windows 10, Version 60.0.3112.113 (Official Build) (64-bit)

This looks like an error you might get if your version of the VM is out of date. Try pulling an updated scratch-vm or npm unlinking scratch-vm in scratch-gui.

**Comment by thisandagain** [comment]
@Zhuhp Can you please try making sure you have the latest version of the `vm` installed and try again? If you continue to see the error please feel free to reopen this issue.
