### ISSUE TITLE
how to create 8*8 matrix

### ISSUE THREAD

**Issue by crousekimo** [LLK/scratch-gui#6938]
I found microbit has a 5*5 matrix blocktype.
May I know how to create 8*8 matrix blocktype?

![image](https://user-images.githubusercontent.com/43980978/111560944-92bffb00-87ce-11eb-9070-7e8e12045681.png)

**Comment by apple502j** [comment]
Duplicate of LLK/scratch-vm#2226

**Comment by BryceLTaylor** [comment]
Closing as duplicate
