### ISSUE TITLE
sprite is still dragable after execute set drag mode to not draggable 

### ISSUE THREAD

**Issue by moonkop** [LLK/scratch-gui#6944]
### Expected Behavior

after running setDragMode(not draggable) block sprite should not be draggable

### Actual Behavior

still dragable 

### Steps to Reproduce

execute the setDragMode(not draggable) block 

try to drag the sprite 

### Operating System and Browser

 Mac OS 10.15.7 Chrome88

**Comment by apple502j** [comment]
Are you sure you are not in the editor? You can always drag sprites in editor.

**Comment by BryceLTaylor** [comment]
I can not reproduce this issue.  After setting the sprite to non-draggable and switching to the project page or fullscreen mode I am unable to drag the sprite.  I am able to drag the sprite while in the regular screen mode in the editor as expected.
