### ISSUE TITLE
How do I translate the blocks to Chinese in my project?

### ISSUE THREAD

**Issue by challange** [LLK/scratch-gui#696]
I want to translate the blocks to Chinese，but l can't find every blocks name in my project. I felt very strange.
Is there a guide or example for doing this kind of thing?

**Comment by Kenny2github** [comment]
Translations are currently not being worked on - too many interface items' names might change often. You will be able to translate once 3.0 is released.

**Comment by chrisgarrity** [comment]
@challange we're working on the infrastructure for translation right now, and what is in the gui is the current prototype. Things are still changing often, so it's not yet ready to be translated. When it is ready to be translated it will be a public project on our [Transifex translation site](https://www.transifex.com/llk/public).
