### ISSUE TITLE
Procedure definition top block appended with "false"

### ISSUE THREAD

**Issue by AnmAtAnm** [LLK/scratch-gui#699]
### Expected Behavior

Open https://llk.github.io/scratch-gui/develop/#135648692
Find left-most stack (a function definition) labeled "Draw snowflake part"

### Actual Behavior

Found left-most stack labeled "Draw snowflake part   false".

"false" is appended to all function definition top blocks.

### Steps to Reproduce

Open https://llk.github.io/scratch-gui/develop/#135648692

### Operating System and Browser

Mac OS X 10, Chrome 60

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/607
