### ISSUE TITLE
Adds Sounds and Costuumes Tabs

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-gui#70]
### Expected Behavior

_They would be there._

### Actual Behavior

_They are not implemented._

### Steps to Reproduce

_Go to http://llk.github.io/scratch-gui and look above toolbox._

### Operating System and Browser

_Chrome Windows 10_

### Note

_I have a fork that adds BLANK tabs in it is at https://github.com/TheBrokenRail/scratch-gui/tree/master These tabs use colors from the concept image in #1._

**Comment by TheBrokenRail** [comment]
According to #65 the Animation Playtest Prototype there will only be one tab should I make a pull request for that?

**Comment by thisandagain** [comment]
No thanks. I believe @lifeinchords is working on the overall UI for the play test. If he has specific tasks we will file them and add the "help wanted" label.

**Comment by thisandagain** [comment]
Tracking in #78 and #79
