### ISSUE TITLE
Right-clicking on a sprite and clicking on the screen moves the sprite

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-gui#701]
### Expected Behavior

Right-clicking on a sprite opens the right-click menu but doesn't start a drag.

### Actual Behavior

Right-clicking on a sprite opens the right click menu and doesn't move the sprite, but the next click anywhere on the page moves the sprite as far as possible toward the mouse pointer.

### Steps to Reproduce

Open llk.github.io/scratch-gui/develop
Right-click on the scratch cat on the stage
Click anywhere else on the page

### Operating System and Browser

Chrome on ubuntu

**Comment by bartljak** [comment]
I reproduced this bug with Safari 11.0 on macOS 10.12.6

**Comment by SillyInventor** [comment]
Onstartdrag should probbably get the event button in addition to the x,y so you can exclude right click drags.

**Comment by paulkaplan** [comment]
Fixed
