### ISSUE TITLE
crash at adding text in paint editor of local built Scratch

### ISSUE THREAD

**Issue by yokobond** [LLK/scratch-gui#7015]
### Expected Behavior

Type text in paint editor without crash on a Scratch editor which I built locally.

### Actual Behavior

When I build local Scratch editor from source code,   the local Scratch crash at adding any text in paint editor with error screen "Oops! Something went wrong.".

### Steps to Reproduce

Clone latest LLK/scratch-gui  (the tag that I checked this problem).
Then start dev server as followings.

```
git clone --depth 1 --branch 0.1.0-prerelease.20210401231322 https://github.com/LLK/scratch-gui.git
cd ./scratch-gui
npm ci
npm run start
```

Open `http://0.0.0.0:8601/` with browser.
Then open paint editor of sprite costume and type text with text tool.
When the focus was left the text, the Scratch will crash and display error message.

Logs on the browser console is this.

```
gui Unhandled Error: TypeError: getFonts is not a function
    at inlineSvgFonts (http://0.0.0.0:8601/lib.min.js:263738:15)
    at http://0.0.0.0:8601/lib.min.js:366985:98
    at Watermark.getCostumeData (http://0.0.0.0:8601/lib.min.js:362452:82)
    at Watermark.wrapper [as getCostumeData] (http://0.0.0.0:8601/lib.min.js:88610:15)
    at Watermark.render (http://0.0.0.0:8601/lib.min.js:362459:26)
    at finishClassComponent (http://0.0.0.0:8601/lib.min.js:115246:31)
    at updateClassComponent (http://0.0.0.0:8601/lib.min.js:115223:12)
    at beginWork (http://0.0.0.0:8601/lib.min.js:115598:16)
    at performUnitOfWork (http://0.0.0.0:8601/lib.min.js:117597:16)
    at workLoop (http://0.0.0.0:8601/lib.min.js:117661:26)
```

### Operating System and Browser

Mac OS 10.15.7 Chrome 89.0.4389.114

**Comment by apple502j** [comment]
多分scratch-render-fontsのversion mismatchですね。`npm install`ではどうでしょうか。

Probably version mismatch of scratch-render-fonts, perhaps try `npm install`?

**Comment by yokobond** [comment]
`npm install` でも変化はありませんでした。`npm ci` と同じくエラーになります。

There was no change with `npm install`. As with `npm ci`, it will get same error.

**Comment by eqot** [comment]
> 多分scratch-render-fontsのversion mismatchですね。

おっしゃる通りで、[この PR](https://github.com/LLK/scratch-gui/pull/7003) にて解決できました。

This issue can be resolved with [this PR](https://github.com/LLK/scratch-gui/pull/7003).

**Comment by BryceLTaylor** [comment]
It looks like scratch-render-fonts has been updated.  Go ahead and reopen if the problem persists.
