### ISSUE TITLE
Can I create my own?

### ISSUE THREAD

**Issue by minhazsites** [LLK/scratch-gui#7025]
Hello, I am a beginner. I couldn't find any language espicially mine - Bangla in scratch.mit.edu project. Can I can duplicate this project (/scratch-gui/master/) and customize by changing the language to Bangla and host on https://scratchbd.github.io/.

Disclaimer : No commercial purpose intended, Only for non-profit and education goals to help children in my country who don't speak English. All credits are given to  LLK/scratch-gui.

**Comment by apple502j** [comment]
See https://github.com/LLK/scratch-l10n/wiki/Guide-for-Scratch-Translators

**Comment by marhristo** [comment]
Στάλθηκε από το Galaxy μου
-------- Αρχικό μήνυμα --------Από: Minhaz Rahman ***@***.***> Ημερομηνία: 9/4/21  09:20  (GMT+02:00) Προς: LLK/scratch-gui ***@***.***> Κοιν.: Subscribed ***@***.***> Θέμα: [LLK/scratch-gui] Can I create my own? (#7025) 
Hello, I am a beginner. I couldn't find any language espicially mine - Bangla in scratch.mit.edu project. Can I can duplicate this project (/scratch-gui/master/) and customize by changing the language to Bangla and host on https://scratchbd.github.io/.
Disclaimer : No commercial purpose intended, Only for non-profit and education goals to help children in my country who don't speak English. All credits are given to  LLK/scratch-gui.

**Comment by minhazsites** [comment]
> See https://github.com/LLK/scratch-l10n/wiki/Guide-for-Scratch-Translators

Oo thank you, I didn't know there was a way. I would surely help the research grow via contributing.
