### ISSUE TITLE
Tab bar has incorrect width

### ISSUE THREAD

**Issue by mxmou** [LLK/scratch-gui#7036]
### Expected Behavior

The right of tab bar would be aligned with the block palette. This is (or was?) the intended behavior - its width is set to 250px, which used to be the width of the palette.

### Actual Behavior

It is not aligned:
![tabs_align_en](https://user-images.githubusercontent.com/51849865/114575534-8ec2b400-9c7a-11eb-850c-153ab895771b.png)

In some languages it's even smaller:
![tabs_align_sl](https://user-images.githubusercontent.com/51849865/114575574-984c1c00-9c7a-11eb-93bc-9e02d668f167.png)

When the block category menu was made vertical, the total width of the palette became 312px, but the width of the tab bar was not updated. If the width of `.tab-list` is set to 312px, it looks like this:

![image](https://user-images.githubusercontent.com/51849865/114588236-be77b900-9c86-11eb-89c5-4492676a73e4.png)

### Steps to Reproduce

Open the editor.

### Operating System and Browser

Edge 89 on Windows 10 but should behave the same on all browsers.

**Comment by BryceLTaylor** [comment]
The intention of the tabs is to scale relative to their content and be independent of the width of the blocks pallet.
