### ISSUE TITLE
how to connect scratch-www to scratch-gui 

### ISSUE THREAD

**Issue by manitac** [LLK/scratch-gui#7041]
on my local machine I have setup scratch-www and scratch-gui both setup.
Both are working well individually. But I want to implement changes in scratch -gui header but when going from scratch-www, create option it is still not picking up the local scratch-gui.
Please help how to solve this issue.
Wants to do customization in scratch-gui which should be reflected in scratch-www.

Thank you
![issues](https://user-images.githubusercontent.com/39349203/114833323-14ff0780-9ded-11eb-9cbb-44b75d652f2e.JPG)

**Comment by apple502j** [comment]
I'm not sure why you have a "package-lock" file in the directory. Anyway, `npm link` on gui side and `npm link scratch-gui` on www side should be enough.

**Comment by manitac** [comment]
@apple502j 
thank you.
I tried as you told but still when making changes in scratch gui folder files and access that through scratch-www project starting, it is not reflecting change.
What steps I followed are:-
setup scratch-www  and scratch-gui at  same location successfully. both are running well individually.
but when I tried linking like:
npm link on gui side and npm link scratch-gui on www side and then running scratch-www by npm start  command, it is not reflecting changes done in scratch-gui  header css.
Please Help.

**Comment by chrisgarrity** [comment]
@manitac basically echoing what @apple502j  said. 

1. Checkout and set up scratch gui as usual
2. run `npm link` in the scratch-gui directory
3. Check out and set up scratch-www as usual, including `npm install` to make sure everything else has been installed
4. run `npm link scratch-gui` in the scratch-www directory to use your local gui

changes to scratch-gui may not be reflected in www while it's running. You may need to stop and restart www to see local changes in gui.
