### ISSUE TITLE
Customization of UI in scratch-www

### ISSUE THREAD

**Issue by rashid-01** [LLK/scratch-gui#7048]
### Expected Behavior
I have scratch-www source code and want to customize the user-authentication part as per my requirements.
_Please describe what should happen_
Please suggest How can I achieve this? 
I want to log in through my credentials and save the projects on my profile stuffs.
![Screenshot 2021-04-22 163520](https://user-images.githubusercontent.com/54931339/115704340-e0f58a80-a388-11eb-9727-b59d3781c42c.jpg)

**Comment by apple502j** [comment]
Profile pages are not open source.

**Comment by rashid-01** [comment]
Ok, Is there any option to customize the header of Editor?
@apple502j

**Comment by apple502j** [comment]
Yes: `menu-bar.jsx` in the repo.

**Comment by RIT-entertainment** [comment]
Should This Issue Be Closed?

**Comment by chrisgarrity** [comment]
I'm closing this issue since it's not actually a problem, and has been answered. If you want to continue the conversation in this issue feel free to do so.
