### ISSUE TITLE
Backdrop label, icon, "add backdrop" aligned wrong

### ISSUE THREAD

**Issue by GreenBayRules** [LLK/scratch-gui#705]
![image](https://user-images.githubusercontent.com/11379161/30840845-724520f0-a22e-11e7-8155-2e4239140837.png)

### Expected Behavior

The backdrop label, icon, and "add backdrop" shouldn't be on top of each other.
### Actual Behavior

The backdrop label, icon, and "add backdrop" are on top of each other.

### Steps to Reproduce

Go to the website, look in the bottom right corner.

### Operating System and Browser

Windows OS Chrome

**Comment by thisandagain** [comment]
This appears to be an issue with the size of your screen. Our minimum supported resolution is 1024x768. How large is your browser window? Can you share a screenshot of the full screen?
