### ISSUE TITLE
Scratch Gui on Github Pages Problem

### ISSUE THREAD

**Issue by zoraezimran** [LLK/scratch-gui#7058]
What is the branch which will make the scratch-gui work on github pages?

Because I can't do the the way you showed on the wiki

**Comment by apple502j** [comment]
I just run `npm run build` and copy files in build folder. Simple and it works.

**Comment by zoraezimran** [comment]
you mean all the files on this github repository?

where do your run npm run build 

@apple502j

**Comment by FunctionalMetatable** [comment]
You have to clone it locally on your machine and then install/build it. it can also be used as a github workflow.

```bash
git clone https://github.com/LLK/scratch-gui
cd scratch-gui
npm install
npm run build
```

**Comment by zoraezimran** [comment]
ok thanks
