### ISSUE TITLE
blocks edit view Drag and Drop error

### ISSUE THREAD

**Issue by challange** [LLK/scratch-gui#707]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_ Drag and Drop edit view will report error_

### Steps to Reproduce

![qq20170926-153621](https://user-images.githubusercontent.com/10009376/30848136-b7d857de-a2d0-11e7-8ca0-51da7112dd53.png)

### Operating System and Browser

Mac OS 10.11.6 Google Chrome 60.0.3112.113
visit: https://llk.github.io/scratch-gui/

**Comment by thisandagain** [comment]
Can you please provide more information? This is not enough for us to understand the problem you are encountering:

- Are you seeing this while running the project locally or when using the latest `master` or `develop` build?
- What browser version are you using?
- Please describe steps to reproduce the error in detail

**Comment by challange** [comment]
Mac OS 10.11.6 Google Chrome 60.0.3112.113
visit: https://llk.github.io/scratch-gui/

**Comment by linhaiwz** [comment]
i

**Comment by paulkaplan** [comment]
I believe this error is caused by a chrome extension that you have installed (judging from how the error is coming from `VM` instead of from a file.
