### ISSUE TITLE
2.0 project does not translate well in Scratch 3

### ISSUE THREAD

**Issue by yongabyte** [LLK/scratch-gui#711]
### Expected Behavior

Have all of the dialog correctly display and 'S' at the center of sprite's forehead. 

### Actual Behavior

 1. all of the dialog boxes lost.
 2. The 'S' on supercat's forehead is out of place.

### Steps to Reproduce

1. run https://llk.github.io/scratch-gui/develop/#112105490
2. click the green flag

### Operating System and Browser

Ubuntu 16.04 Firefox 55.0.2 & Chromium 60

**Comment by Kenny2github** [comment]
There are a number of features that that project requires that have not been implemented in Scratch 3.0 yet - if you would like to see them as they come out, you can watch the scratch-* repositories.

**Comment by thisandagain** [comment]
Tracking missing functionality in https://github.com/LLK/scratch-vm/issues/307
