### ISSUE TITLE
could i change bubble category to image category?

### ISSUE THREAD

**Issue by rollback228** [LLK/scratch-gui#7113]
![image](https://user-images.githubusercontent.com/7988087/117527550-1dff8500-aff7-11eb-94cb-19f387e9f221.png)

I want to change circle shape to image or another.
Could i change?

**Comment by rollback228** [comment]
Could i change bubble to image ?

**Comment by apple502j** [comment]
Yes; easiest method is to add background-image via CSS

**Comment by chrisgarrity** [comment]
Thanks @apple502j for providing an answer. Closing the issue.
