### ISSUE TITLE
Colors not loading correctly

### ISSUE THREAD

**Issue by zhudanmeng** [LLK/scratch-gui#7131]
![Screenshot 2021-05-13 164410](https://user-images.githubusercontent.com/36681583/118101719-7a551100-b40a-11eb-894f-0e9e20053168.png)

Colors don't seem to be loading correctly. All I did was cloning the repo, running npm install in scratch-gui and then npm start. 

It's giving me errors in the css files whenever a $variable is declared or used, not sure if it's the default behaviour with postcss-simple-vars or if something isn't installed correctly.

**Comment by mxmou** [comment]
Make sure that there is no environment variable named `DEBUG` - I think that's what causes these weird colors.

**Comment by zhudanmeng** [comment]
@mxmou thanks that fixed it!
