### ISSUE TITLE
Can I Edit UI?

### ISSUE THREAD

**Issue by RIT-entertainment** [LLK/scratch-gui#7161]
Hello! Yes, I do know that there is already a question about this, but I have a different question. I have setup GitHub pages for this repo, and I would like to know if it is possible to add a login/signup button, as well as a project page (I have found a html file for project pages, but I don't know how to incorporate it into the main editor!). The link for my fork is: https://reeceypie.github.io/Micro-Code/ . Any help is appreciated!  :D

EDIT: And can I add a backpack?

**Comment by apple502j** [comment]
Do you have a server to store the stuff?

**Comment by RIT-entertainment** [comment]
errr.... How would I make one?

**Comment by RIT-entertainment** [comment]
Should I Use Ubuntu Server Edition?
(By server do you mean database?)

**Comment by apple502j** [comment]
OS usually doesn't matter, you can use Windows, macOS, any distro of Linux, etc. Just a server, a database and a URL you can connect to log in, get and store the data.

**Comment by RIT-entertainment** [comment]
What do you mean by database?

**Comment by apple502j** [comment]
Something to store the user info, project content, costumes, sounds, backpacks, etc. Doesn't need to be SQL-based, just something that can store data. You yourself can be a database if you want to write down on a paper and type yourself as requested, but that's not a good solution, so you should let a computer do its job

**Comment by RIT-entertainment** [comment]
Would a **Microsoft Access** database be good enough?

**Comment by apple502j** [comment]
If you have a way to write to that from a website, yes. Just having Microsoft Access and opening it wouldn't be enough though

**Comment by RIT-entertainment** [comment]
What would you recommend to use for a database?

**Comment by RIT-entertainment** [comment]
But if I had a database and server, then what would I do next?

**Comment by apple502j** [comment]
Assuming you did all backend stuff (like handling login, storing projects, etc), you can just mod this so that it supports your system!

**Comment by RIT-entertainment** [comment]
How would I set that up, As well as moding?

**Comment by apple502j** [comment]
Depends on what you want to use: python, nodejs, or PHP? Windows or Linux? SQL, mongo or JSON?

**Comment by RIT-entertainment** [comment]
I would use python, Linux and SQL.

**Comment by apple502j** [comment]
Great! Look for tutorials on how to make one online, and you should be able to make one.

**Comment by RIT-entertainment** [comment]
How would I mod the GUI to connect to the database?

**Comment by RIT-entertainment** [comment]
> How would I mod the GUI to connect to the database?

**Comment by apple502j** [comment]
storage.js and save-project-to-server.js are the main ones.

**Comment by RIT-entertainment** [comment]
Ok. Thanks!

**Comment by RIT-entertainment** [comment]
Can I Add The Login Feature, So That Users Can Post Their Project's To Scratch?

**Comment by apple502j** [comment]
Well, that'd require collecting others' Scratch usernames and passwords. I'm sure if they found that, they'll ban you for phishing...

**Comment by RIT-entertainment** [comment]
How can I add it so that they can log in themselves? Could I embed the Scratch sign in code?

**Comment by apple502j** [comment]
Nope, you're still someone trying to hack an account to upload projects. Just make your own login system and don't bother reusing Scratch ones.

**Comment by RIT-entertainment** [comment]
Oh, Ok. How would I make my own login system? (If you can't already tell, I am not very good at html/JavaScript)

**Comment by RIT-entertainment** [comment]
How would I make a log in system?

**Comment by RIT-entertainment** [comment]
> How would I make a log in system?

**Comment by chrisgarrity** [comment]
@reeceypie just to clarify - you are welcome to fork this repository and make your own version of the scratch-gui but you will not be able to use the Scratch website's authentication or save projects in your version to the Scratch site. Also, the backpack feature requires its own server and database for saving backpack items per user.

**Comment by RIT-entertainment** [comment]
Ok. Thanks!
