### ISSUE TITLE
Save Option Still On Editor

### ISSUE THREAD

**Issue by RIT-entertainment** [LLK/scratch-gui#7198]
### Expected Behavior

No Save Button

### Actual Behavior

Save Button Included - [Image](https://im3.ezgif.com/tmp/ezgif-3-5ebe47288dc1.gif)
### Steps to Reproduce

Add Code, Then On Top Right, It Says "Save Now"
### Operating System and Browser

Win 10 ????? Chrome 90.0.4430.212 (Official Build) (64-bit)

**Comment by BryceLTaylor** [comment]
Removing the save button is not a feature we plan to support.

**Comment by RIT-entertainment** [comment]
Ok
