### ISSUE TITLE
When I use npm install, document not found appears

### ISSUE THREAD

**Issue by LS-LILEI** [LLK/scratch-gui#7211]
### Expected Behavior

clone project and npm install

### Actual Behavior

When I use npm install, document not found appears

npm ERR! 404 Not Found - GET https://registry.npm.taobao.org/@babel/runtime/-/runtime-7.14.0.tgz - [not_found] document not found
npm ERR! 404 
npm ERR! 404  '@babel/runtime@https://registry.npm.taobao.org/@babel/runtime/-/runtime-7.14.0.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

### Steps to Reproduce

npm install

**Comment by apple502j** [comment]
This is not our bug; taobao's copy of the NPM registry does not have the latest version. You can use VPN or (once the pandemic ends) go to Hong Kong/other countries to install.
