### ISSUE TITLE
Open projects periodically console log "Error: Promised response from onMessage listener went out of scope  common.js:4:491"

### ISSUE THREAD

**Issue by wyattscarpenter** [LLK/scratch-gui#7218]
### Expected Behavior

No errors occur in normal operation.

### Actual Behavior

Open project pages periodically console log "Error: Promised response from onMessage listener went out of scope  common.js:4:491". This happens about once a minute.  The projects still work.

### Steps to Reproduce

Open any scratch project on the website, and wait for a couple of minutes. You can run the project or just keep the page open without running the project, the error will be logged regardless.

I think if you open multiple scratch projects in different tabs, they all log this error at the same time, but it was difficult for me to measure this exactly.

### Operating System and Browser

Current Firefox, current Windows

**Comment by apple502j** [comment]
This is not Scratch's bug; this occurs in Firefox internal code.

**Comment by wyattscarpenter** [comment]
Dang, you're right, it was an extension I had enabled.
