### ISSUE TITLE
BLE device name - need help

### ISSUE THREAD

**Issue by sbb777** [LLK/scratch-gui#7226]
I need some help.
I’m making own extension for our team's BLE device.
It can be connected and communication is OK. It works.

Only thing is, 
during scanning it does not display the name of BLE device on the GUI.
Which parts of codes do I need to check?
It's not a bug, need help.

### Operating System and Browser

Windows 10, Chrome, deployed to github.io page.

**Comment by apple502j** [comment]
Scratch Link sends JSONRPC message `didDiscoverPeripheral` with a `name` attribute. This is `Advertisement.LocalName` or empty string if null.

**Comment by chrisgarrity** [comment]
I'm closing this issue since it's been answered. If you want to continue the conversation in this issue feel free to do so.
