### ISSUE TITLE
Implement Lego WeDo 2.0 extension

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#724]
We'll use the new extension system to add an extension for the Lego WeDo 2.0. This work will be based on prior work in the VM [here](https://github.com/LLK/scratch-vm/pull/556). 

We should bear in mind issues with that code noted [here](https://github.com/LLK/scratch-vm/issues/596). 

We should make sure to cover the steps included in the earlier prototype extension work [here](https://github.com/LLK/scratch-vm/issues/606). 

We should include safeguards against this crash: https://github.com/LLK/scratch-vm/issues/572

And consider these improvements: https://github.com/LLK/scratch-vm/issues/667

**Comment by DenisKaVladimirovich** [comment]
Hello. I need help for create this extension. Help me with it, please
