### ISSUE TITLE
Bug: Neigh Pony is in the sprite library when it should not be

### ISSUE THREAD

**Issue by Time-dragon** [LLK/scratch-gui#7271]
### Expected Behavior

Neigh Pony not being in the library.

### Actual Behavior

It is there.

### Steps to Reproduce

1. Go to Sprite Library
2. Scroll until you see "Neigh Pony" or search for Neigh Pony
3. See it

### Operating System and Browser

ChromeOS and Chrome

**Comment by Time-dragon** [comment]
Changed name

**Comment by ninjamar** [comment]
This happens using webkit and chromeos/debian

**Comment by Time-dragon** [comment]
> This happens using webkit and chromeos/debian but I believe it happens on all os's and browser's

Okay.

**Comment by FunctionalMetatable** [comment]
https://github.com/LLK/scratch-gui/blob/ba76db7350bd43b79119cac2701bc10f6c511f0c/src/lib/libraries/costumes.json#L7479

**Comment by chrisgarrity** [comment]
@Time-dragon Neigh pony is supposed to be in the library.
