### ISSUE TITLE
Repo Error: Issue Templates are old

### ISSUE THREAD

**Issue by Time-dragon** [LLK/scratch-gui#7285]
### Expected Behavior

Choosing the template.

### Actual Behavior

Bug report template.
### Steps to Reproduce

Make an issue.

### Operating System and Browser
ChromeOS and Chrome.

**Comment by chrisgarrity** [comment]
@Time-dragon we're aware of the new ability to have different issue templates. The team is working on a set of templates that will work for all our repos, not just gui. We're not looking for community submissions of new templates at this time.
