### ISSUE TITLE
Custom Block List

### ISSUE THREAD

**Issue by samuelpereira** [LLK/scratch-gui#731]
Hi,

I trying to use a custom block list with scratch-blocks.

**I have done this steps:**

git clone scratch-gui
npm install
npm start

So far so good...

But when i try to edit i go to node_modules/scratch-blocks/blocks_vertical and remove some js files... and edit others..

But when i build with "python build.py" the file **dist/vertical.js** is not updated, and is this file that is used by scratch-gui

Why scratch-gui is using this file only?

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by paulkaplan** [comment]
Hi @samuelpereira. In order to update that dist file you actually need to run both `python build.py` and `webpack` (which creates the dist/vertical file). You can run these both at the same time using the `npm run prepublish` command, which just runs `python build.py && webpack`.
