### ISSUE TITLE
Prevent or move scrollbar in toolbox

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#747]
![Scrollbar covers toolbox](http://i.cubeupload.com/q4yCmz.png)
On a Chromebook, the category scrollbar covers the toolbox. This doesn't prevent functionality, but it is annoying and you might want it to be removed.

I suggest that you either widen the category menu for more room or shrink the scrollbar.

**Comment by Kenny2github** [comment]
Duplicate of LLK/scratch-blocks#1119

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/1119
