### ISSUE TITLE
Why is repeat until block is executing on false condition?

### ISSUE THREAD

**Issue by hacktronics** [LLK/scratch-gui#7484]
### Expected Behavior
The repeat until block should work on true condition only.
_Please describe what should happen_
![image](https://user-images.githubusercontent.com/62869751/128590244-75caf1ee-51e2-475d-a467-813e463af256.png)

### Actual Behavior
This is not working, the sprite in not moving
_Describe what actually happens_
Sprite should move
### Steps to Reproduce
I have the github codebase from 17th July, 2021
_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser
Windows 10 Chrome
_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by hacktronics** [comment]
I think this is confusing, I think the developers had deliberately made it loop till false and stop on true. May be I was expecting something like loop till, like the for loops or do while loops in programming, loop till false is something new for me.

**Comment by apple502j** [comment]
Well, that is why it is called "repeat *until*" and not "repeat *while*". There is a while block, but it is an easter egg.
