### ISSUE TITLE
Monitors are not sprite-specific

### ISSUE THREAD

**Issue by Scimonster** [LLK/scratch-gui#749]
### Expected Behavior

When showing a stage monitor for a sprite-specific block (e.g. `x position`), it should remember which sprite it references.

### Actual Behavior

It shows the value from the most-recently-interacted-with sprite (i think).

### Steps to Reproduce

1. Create 2 sprites
2. (optional) Move them around so that they are clearly in different spots
3. In the first, check the `x position` block
4. In the second, check the `x position` block
5. There will be two identical monitors on the stage

![Example image](https://user-images.githubusercontent.com/2826514/31355001-384ca79c-ad41-11e7-94b2-bdfd5626e62f.png)

In the example, i set variables `x1` and `x2` to the sprite's x position with a script. You can see that both the blue `x position` monitors display the cat's position, not the plane's (since i last touched the cat).

### Operating System and Browser

Ubuntu 17.04, Chrome 61.0.3163.100.

Likely related to #658.

**Comment by VutonDesign** [comment]
Just tested this, Having the same issue on:
- Windows 10 (Chrome)
- Windows 8.1 (Chrome)
- IOS 11 (Safari)

I think it's safe to say this is a widespread problem.
