### ISSUE TITLE
Is there a way to know what version of this package is being used on scratch.mit.edu?

### ISSUE THREAD

**Issue by floehopper** [LLK/scratch-gui#7510]
Is there a way to know what version of the `scratch-gui` package is being used on scratch.mit.edu? e.g. is there a branch or tag pattern which indicates this? Or is there a way to see if from the scratch.mit.edu website somehow? Thanks.

**Comment by apple502j** [comment]
See https://github.com/LLK/scratch-www/blob/master/package.json#L130

**Comment by floehopper** [comment]
@apple502j Thanks. Can you confirm that the latest commit in the `scratch-www` `master` branch is deployed to scratch.mit.edu as per [this comment](https://github.com/LLK/scratch-www/issues/5909#issuecomment-896095674)?

**Comment by apple502j** [comment]
@floehopper In most cases, yes: it'll take around a hour or so before it gets deployed. In rare cases, the files may be modified locally, but that only happened once or twice iirc.

**Comment by floehopper** [comment]
Thanks 👍
