### ISSUE TITLE
Considering how the blocks (and editor) will look at extremely large sizes

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#752]
A user brought up this issue w.r.t. a student they are working with who needs to increase the zoom a lot in order to make out the block text.

Reported via freshdesk no. 92785 (speaking about the 2.0 blocks, not the 3.0 blocks):
> I work with a visually impaired student and we encounter great difficulties in being able to work on scratch because, given the screen enlargement rate that it needs (+ 400%), the blocks pixelize and become illegible. Would you have developed a support for people with visual impairment?

Filing as an issue in case we want to consider this feedback in design of 3.0 or when considering what kind of extensions people might want to create, etc.

**Comment by thisandagain** [comment]
This is already resolved in 3.0 because the blocks are vector. :tada:

**Comment by jwzimmer** [comment]
An update from the reporting user on how they & their student found the 3.0 prototype:
> So, we tried the prototype of Scratch 3.0 and IT IS SOOOO MUCH BETTER !
The middle section is just great : by enlarging it to the max and using the magnifier, she can read the various blocks. The fact that the “screen” is on the right makes it also a lot easier because there is a left to right motion for the eyes, which is much better than having to work the other way.
Now, the only problem lies in the left sections where all the blocks are : we can only use the computer’s magnifier and it’s not legible enough. The colours are not contrasted enough and [the student] cannot see the difference between the blue, green and various shades. So, if there is one extra improvement to make, it would be to have the same zoom on the left section. But as said, it is really so much better ! Congrats’ !

/cc @carljbowman
