### ISSUE TITLE
Translation for in "en" is missing

### ISSUE THREAD

**Issue by appxiang** [LLK/scratch-gui#7524]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by chrisgarrity** [comment]
Please provide the information requested in the issue template. English is the default language, so it's not missing. If there's a problem screen shots are helpful.

**Comment by mxmou** [comment]
This is probably about the warnings in the browser console when adding any extension:
![image](https://user-images.githubusercontent.com/51849865/134781730-03aa820c-c09a-4a0a-bd06-a64a8faca1c7.png)

**Comment by BryceLTaylor** [comment]
Ah, that makes it a duplicate of https://github.com/LLK/scratch-vm/issues/2270.  Thanks @mxmou for the info!
