### ISSUE TITLE
Backdrop area is cut off

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#754]
## Steps to reproduce
Change minimum font size preference in settings (minimum of 12 or 13 will repro) , then view at actual size - backdrop gets cut off. 

Everything looks fine after zooming in.

![Screen Shot 2017-10-11 at 2.17.47 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/134c1e85-6424-4fdd-9c99-07ba30bc9c70/Screen+Shot+2017-10-11+at+2.17.47+PM.png)

OSX Sierra 10.12.6
Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by VutonDesign** [comment]
@chrisgarrity Doesn't seem OS specific, I'm having the same problem on 
> Windows 8.1 - Chrome 61.0.3163.100

**Comment by thisandagain** [comment]
Is this a zoom level issue? @chrisgarrity can you provide repro steps?
