### ISSUE TITLE
How i can write ext for communicate with HID devices

### ISSUE THREAD

**Issue by DenisKaVladimirovich** [LLK/scratch-gui#756]
Hello. I wanna communicate my scratch with some hid devices. What i need to do for start simple tcp or udp client client in Scratch-gui(3.0).

Windows 10. Chrome latest

**Comment by thisandagain** [comment]
Hello! You are a little ahead of us. We'll be publishing our extension specs early next year and would love to see folks getting started to work on extensions then. We hope to support both HID and Serial in the Scratch Device Manager eventually.
