### ISSUE TITLE
Right-clicking brings up Scratch context menu and default browser context menu

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#761]
### Expected Behavior

When right-clicking on a block, you should only get one menu.

### Actual Behavior

@fsih reported on 10/11/17 (using https://ericrosenbaum.github.io/scratch-gui/extensions-oct2017/):
> When I right click I get 2 context menus, the Scratch one and the default browser one.

### Steps to Reproduce

Unknown, I don't actually see this when I right-click on a block, the scripting area, or the block palette. 

### Operating System and Browser

_Chrome, Mac (Sri Lanka machine)_

**Comment by jwzimmer** [comment]
@fsih what were your steps for repro'ing this? : )

**Comment by fsih** [comment]
I don't see it on my own machine. I was using Sri Lanka when it was happening before, so Chrome on Mac. Maybe it's fixed?

**Comment by ericrosenbaum** [comment]
For future reference, it turns out this was caused by a sneaky chrome extension called "enable right click"! @rschamp has now deleted the extension from Sri Lanka.
