### ISSUE TITLE
Are there sources for mobile?

### ISSUE THREAD

**Issue by jysim1** [LLK/scratch-gui#7612]
https://play.google.com/store/apps/details?id=org.scratch
<-Is the source of this app private?

**Comment by cwillisf** [comment]
Thanks for asking! Our Android app has two parts.

The editor is the `native` branch of the `scratch-gui` repository, which is available here: https://github.com/LLK/scratch-gui/tree/native

The part of the app which wraps the editor is not currently public, but that may change in the future.
