### ISSUE TITLE
An error occurred with the message “ 呀，出错了。  很抱歉，Scratch出故障了。这个问题已经自动报告给Scratch开发团队。请刷新页面再试试。” while loading

### ISSUE THREAD

**Issue by cheny0y0** [LLK/scratch-gui#7618]
### Expected Behavior

Open [Scratch 3.0 GUI](https://llk.github.io/scratch-gui/develop/)

### Actual Behavior

An error occurred while loading [Scratch 3.0 GUI](https://llk.github.io/scratch-gui/develop/)

### Steps to Reproduce

Go to one of browsers and type https://llk.github.io/scratch-gui/develop/ and browse

### Operating System and Browser

iPadOS 15.7 with Safari

**Comment by BryceLTaylor** [comment]
I'm unable to reproduce this issue.  Can you say more about what you are doing to get into this situation or what your network situation is?

**Comment by rschamp** [comment]
Happy to reopen if you can give more context.
