### ISSUE TITLE
Pitch block monitor displayed NaN

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#763]
### Expected Behavior

The pitch block (pitch extension, see @ericrosenbaum's fork) should not return NaN/ the monitor should not display NaN.

### Actual Behavior

@fsih reported on 10/11/17:
> I have code that says forever set variable to pitch, and the monitor for that variable showing. I saw it display NaN

### Steps to Reproduce

Unknown

### Operating System and Browser

_Chrome, Mac (Sri Lanka machine), at https://ericrosenbaum.github.io/scratch-gui/extensions-oct2017/_

**Comment by paulkaplan** [comment]
Can't repro, closing.
