### ISSUE TITLE
security issue: string variable can exhaust memory and cause scratch hang there

### ISSUE THREAD

**Issue by houcy** [LLK/scratch-gui#7630]
### Expected Behavior

scratch run normally 

### Actual Behavior

scratch hung there and computer memory exhausted.

### Steps to Reproduce

create variable a
set a to 0
repeate 64 times:
      set a to  a join a

### Operating System and Browser

scratch desktop,  browser all affected

**Comment by apple502j** [comment]
Client-side denial of service don't really count as a security issue. If you do [find](https://github.com/LLK/scratch-vm/pull/2476) [security](https://github.com/LLK/scratch-svg-renderer/pull/179) [issues](https://github.com/LLK/scratch-www/issues/4406), you should contact them privately.

**Comment by houcy** [comment]
Thanks for your reply. If someone downloads a scratch project from website and that project contains denial-of-service code, the client would be affected, that's very easy to operate. I suggest the string variable length be checked and limited to a certain range.

**Comment by apple502j** [comment]
It's likely the program will either crash or hang and Windows will kill the program. Not a big problem.

**Comment by houcy** [comment]
ok, that's fine, thanks.
