### ISSUE TITLE
PLEASE make a clone count sensing

### ISSUE THREAD

**Issue by tnhung2011** [LLK/scratch-gui#7639]
### Expected Behavior

_I wanted you (Scratch Team) to add a sensing named **"clone count"**._

### Why I need that sensing?

_I wanted you to make a sensing named **"clone count"** because I wanted to manage my sprites **easier** (variables are lot more dumb because it doesn't count the clones when I coded/snaped it with the event "when I start as a clone"_

### Steps to Reproduce

_I thought you can copy the code from [Scratch Addons](https://github.com/ScratchAddons/ScratchAddons) because they added a clone counter made by [Jeffalo](https://jeffalo.net/) that only display and didn't have any sensing blocks tho._

### Operating System and Browser

_I'm currently using Windows 8.1, Chrome 93.0.4577.82 with no Flash version detected_

**Comment by GrahamSH-LLK** [comment]
The Scratch Addons code will be of no use in implementing this, you should delete that. (also the ext/userscript policy _kinda_ applies here.)
