### ISSUE TITLE
When replacing number inputs, new blocks should come to front

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#765]
### Expected Behavior

When number (inputs) are replaced by other blocks, the replaced blocks should pop to the front.

### Actual Behavior

@fsih reported on 10/11/17:
> When numbers replaced by other blocks, the replaced blocks should pop to the front. Instead they pop to the back behind the stack of blocks.

### Steps to Reproduce

Unknown

### Operating System and Browser

_Chrome, Mac (Sri Lanka machine), at https://ericrosenbaum.github.io/scratch-gui/extensions-oct2017/_

**Comment by jwzimmer** [comment]
@fsih do you have steps for this one? I'm not sure if I'm seeing the same thing as you're describing... is the behaviour in this gif what you are talking about?

![out](https://user-images.githubusercontent.com/1320456/31518285-c5af6354-af6c-11e7-9f81-c346f9da2b13.gif)

**Comment by fsih** [comment]
Here is the behavior. The size block disappears.
![replacebubble](https://user-images.githubusercontent.com/2855464/31632258-46a71d9c-b28a-11e7-9ce5-ca40b6e96c47.gif)

**Comment by benjiwheeler** [comment]
Is this a scratch-gui issue, or a scratch-blocks (blockly) issue?

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/937
