### ISSUE TITLE
When you click on a slider in the color picker, the handle should jump to the position of the click

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#766]
### Expected Behavior

When you click on a slider in the color picker, the handle should jump to the position of the click. The Saturation value handle doesn't move at all based on clicks, and it should.

### Actual Behavior

@chrisgarrity reported on 10/11/17:
> Color picker sliders - I expected to be able to click in the slider and have the 'handle' jump to that position, instead it just moves a little in the direction of the click

### Steps to Reproduce

- Go to the "color is touching color" sensing block
- Click on one of the color swatch values to open the color picker
- Click on "Saturation"
- Note that handle doesn't move at all 
- Click on the other value scales
- Note that handle moves slightly in direction of click

### Operating System and Browser

_Chrome, Mac, at https://ericrosenbaum.github.io/scratch-gui/extensions-oct2017/_

**Comment by amazinigmech2418** [comment]
Try using clientX to read the mouse x position and move the slider.

**Comment by ivanixgames** [comment]
The code that impacts this issue is in the scratch-blocks repo.
https://github.com/LLK/scratch-blocks/issues/1381

**Comment by paulkaplan** [comment]
It does now!
