### ISSUE TITLE
Uncaught Connection checks failed. Input "OPERAND1" connection on "operator_and" block (id="W*RcL:x9[CVEU25V*XUf") expected Boolean, found String

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-gui#767]
### Expected Behavior

Project should load fully without failing silently with a partially loaded project.

### Actual Behavior

The inverse of the above ;)

### Steps to Reproduce

Load this project: https://llk.github.io/scratch-gui/develop/#126517840

`lib.min.js:formatted:32939 Uncaught Connection checks failed. Input "OPERAND1" connection on "operator_and" block (id="W*RcL:x9[CVEU25V*XUf") expected Boolean, found String`

I suspect this could well be caused by the use of a hacked block somewhere in the project, although I'm not 100% sure? However, the result is that if you click on the 'Game' sprite, the main green flag clicked script is not present in the project. I assume it (and lots of other scripts) failed to parse after the exception above occurred.

### Operating System and Browser

Chrome (latest) on windows 10 PC

**Comment by paulkaplan** [comment]
Yeah looks like a hacked block. It has a variable attached to the input of the `and` block:

![hacked-block](https://user-images.githubusercontent.com/654102/32191298-ed51c6e0-bd86-11e7-8995-3caf821fade1.gif)

Clearly exploding is the wrong behavior, but what is the right behavior. @thisandagain I'm not sure I have the context about hacked blocks to know what this _should_ do, thoughts?

**Comment by towerofnix** [comment]
The two "correct" options:

1. Just don't crash - let the variable reporter stick around inside the boolean slot.

2. Transform the project upon loading - this.. ![a = a and (some variable)](https://user-images.githubusercontent.com/9948030/32201445-e1bf2bf4-bdb5-11e7-89c0-ac2f3bdcfb24.png) ..is equivalent to this: ![a = a and (some variable = not <>)](https://user-images.githubusercontent.com/9948030/32201473-fbb028ba-bdb5-11e7-8608-0009a753f4cc.png)

I'm not actually 100% sure that option 2 is correct (for instance, does sticking a non-boolean reporter inside of a boolean slot make the interpreter "truthy"/"falsey"-ify the reporter's value?), and it's also a pretty complicated solution.

I'd think option 1 is better. Still need to consider how reporters in booleans should be treated, though - definitely don't want to break compatibility with old projects!

**Comment by thisandagain** [comment]
Good question @paulkaplan! Let's chat about it in person this week.

**Comment by apple502j** [comment]
I hope everything hacked(define block, input, etc) is "as is". Nobody likes to break projects.
I also know hacking is not official, but it's very popular, and a lot of projects use it.

**Comment by thisandagain** [comment]
This has been discussed. We currently don't see a way for us to support all types of "hacked blocks" in Scratch 3.0. Some of the ways in which undocumented / unsupported behavior works in Scratch 2.0 *may* continue to work in Scratch 3.0 but we cannot guarantee anything. We will be putting checks in place to try to prevent hacked blocks from simply crashing the Scratch 3.0 editor however.

**Comment by Kenny2github** [comment]
Carrying over information from #1673:

From @thisandagain:
>Project should run normally:
>https://scratch.mit.edu/projects/195483628/
>Project loads, but does not run:
>https://llk.github.io/scratch-gui/develop/#195483628

From @Kenny2github:
>Actually, the project does seem to run, but anything involving pen (in this case, everything :stuck_out_tongue: ) seems to not work. I'd imagine that's due to this error:
>![image](https://user-images.githubusercontent.com/28599280/37969525-891942f6-3203-11e8-8a4d-a727c3a26b52.png)

From @apple502j:
>Oh, It uses JSON hacking!
>maybe it causes the problem
>
>All projects with it will be broken
>unless hacking is also supported in 3.0

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/1030
