### ISSUE TITLE
Monitor visibility gets out of sync on switching sprites

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#768]
### Expected Behavior

Monitor visibility set by the checkbox should stay in sync when switching sprites.

### Actual Behavior

Checkbox state and monitor visibility can get out of sync.

Seems related to https://github.com/LLK/scratch-gui/issues/749

### Steps to Reproduce

- Go to https://llk.github.io/scratch-gui/develop/
- Set the checkbox for the "x position" monitor to show it
- Switch to stage
- Switch back to Sprite1
- Monitor is still showing, but box is unchecked

**Comment by griffpatch** [comment]
(and if you click the monitor again, a duplicate monitor is generated...
nice that they both work though *grin*).

This effect is also true for variables monitors, except that local variable
monitors only show the correct value when you are viewing the sprite the
variable belongs to (if you switch to another sprite while the local
variable is visible, then the monitor changes value to show '0' - see
project: https://llk.github.io/scratch-gui/develop/#26861174 and make 'aaa'
visible, then switch sprites back and forward to see the value change)

**Comment by griffpatch** [comment]
Actually the "x position" is monitor also only shows the active sprite's 'x
position'. Maybe this is a know issue, I remember there being mention of
something similar before - sorry if I'm repeating things.
