### ISSUE TITLE
Which direction is the transparency range?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#772]
### Expected Behavior

Ideally, the implementation of transparency would feel "natural". This would be reflected in whether users could keep track of it once they learned how it worked (and whether learning how it worked was attainable). If users have to keep re-working-out how the block works, that could indicate that the paradigm we've chosen isn't well-aligned with their expectations.

### Actual Behavior

During an internal smoketest on 10/11/17, several people reported being surprised by whether 0 or 100 would be fully transparent/ fully opaque, and having to re-work-out how the block worked multiple times during the smoketest.

### Steps to Reproduce

We should see how users react to this block in future workshops.

### Operating System and Browser

Chrome, Mac, at https://ericrosenbaum.github.io/scratch-gui/extensions-oct2017/

**Comment by mrjacobbloom** [comment]
I've confused myself from time to time with which way the cost effect goes

**Comment by jwzimmer** [comment]
For now we're keeping the range as currently implemented.
