### ISSUE TITLE
Should we use "ghost" instead of "transparency" in the pen extension?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#773]
This question came up during a smoketest on 10/11/17. The word "ghost" would be consistent with the ghost effect in the Looks category ("change [color] effect by (10)", etc.), and might be able to leverage existing Scratcher intuition w.r.t. how ghost works to help solve https://github.com/LLK/scratch-gui/issues/772. We should consider whether or not how ghost currently works is reasonably learnable/ intuitive for new Scratchers (as opposed to how we're currently implementing transparency).

### Steps to Reproduce

You can see "transparent" in the pen extension blocks, and "ghost" in the Looks category blocks:
<img width="238" alt="screen shot 2017-10-13 at 10 36 51 am" src="https://user-images.githubusercontent.com/1320456/31551429-82f06522-b002-11e7-96a9-e0299b9dd228.png">
<img width="220" alt="screen shot 2017-10-13 at 10 36 38 am" src="https://user-images.githubusercontent.com/1320456/31551430-82fe7e78-b002-11e7-8e3a-9246db95fc7c.png">

### Operating System and Browser

Chrome, Mac, at https://ericrosenbaum.github.io/scratch-gui/extensions-oct2017/

**Comment by rschamp** [comment]
And if we do change "transparency" to "ghost", would we also want to change "hue" to "color" to be consistent there as well? Maybe we want to change "hue" to "color" anyway since it's more understandable?

**Comment by Kenny2github** [comment]
@rschamp in 2.0 the "hue" block is already called "color" - I don't really know what the reason for changing it was.
As for "transparency" changing to "ghost", I don't really know.

**Comment by DeleteThisAcount** [comment]
I really feel that we should have english/other language and then advanced (language) because then mabye younger people would understand for example ghost better than transperent. Then in the advanced language have transparent and not ghost. same for hue

**Comment by griffpatch** [comment]
Was hue introduced to distinguish between set colour and set hue where
originally there were two set colour blocks (one that took a number that
could represent any rgba string, and the other that took a number
representing hue (but was also called colour).

**Comment by jwzimmer** [comment]
For now we're going to keep using transparency where we're currently using it (and same with ghost). We're going to use "color" instead of "hue".
