### ISSUE TITLE
Paint Editor

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#78]
- [ ] Design
    - [ ] Benchmarks
    - [ ] Existing use case documentation
    - [ ] Overall UX wires
    - [ ] Vector editor spec
    - [ ] Bitmap editor spec
- [ ] Implementation
    - [ ] Add "costume" tab
    - [ ] Vector editor
    - [ ] Bitmap editor

**Comment by jwzimmer** [comment]
As noted in internal playtest 3/13/17:
> I can't delete a backdrop!
This is not implemented yet, but at some point obviously we will want to, so just noting it.

**Comment by liam4** [comment]
Quick update, the costumes tab was added (and is at least partially implemented) now, so that can be checked off; same deal for the sounds tab (#79).

**Comment by fsih** [comment]
No bitmap editor yet, but closing this since we'll track that separately.
