### ISSUE TITLE
Pitch block returns value -1

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#780]
### Actual Behavior

@SpeakkVisually reported on 10/11/17:
> Pitch block always returns value -1

@ericrosenbaum described the issue as:
> This generally happens when the microphone input is not working. It can be because the system settings are incorrect (i.e. input not set to the default mic). It can also be because the computer went to sleep, and after waking the extension does not reconnect to the mic.

### Operating System and Browser

_Mac, Chrome, https://ericrosenbaum.github.io/scratch-gui/extensions-oct2017/_

**Comment by paulkaplan** [comment]
Closing as no-longer-relevant
