### ISSUE TITLE
Failed save & load of project, even when loading extensions before project file

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#784]
### Expected Behavior

Saving a project & loading the saved file should cause all of the project's information to re-appear in the GUI.

### Actual Behavior

During a workshop on 10/16/17, two users downloaded their project as a .json file using "Save" but were unable to re-load the project. It loaded no blocks other than a red, text-less hat-block. We tried loading the extensions before the project json but it still did not load correctly.

Screenshots from United States (machine) to be added to this issue to clarify. (/cc @chrisgarrity & @ericrosenbaum)

### Steps to Reproduce

Unknown

### Operating System and Browser

_Mac, Chrome, https://ericrosenbaum.github.io/scratch-gui/extensions-oct2017/_

**Comment by thisandagain** [comment]
Tracking in LLK/scratch-vm#194
