### ISSUE TITLE
Changing the Menu Option Doesn't Change the Label of Monitors

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-gui#785]
### Expected Behavior

Checking the checkbox should show the monitor, changing the block should update the label.

### Actual Behavior

It doesn't. Instead the label remains constant. Ex.
Check the checkbox for current year, then change to second results in:
![image](https://user-images.githubusercontent.com/8440451/31632834-5b77f212-b28c-11e7-9e0e-3bbcca65101e.png)

### Steps to Reproduce

Go to https://llk.github.io/scratch-gui/develop/
Go to Sensing
Check the box next to current year
Change the current year to current second

### Operating System and Browser

Chrome 61.0.3163.100, Ubuntu 16.04

**Comment by Kenny2github** [comment]
Actually, the behavior of that checkbox is simply inconsistent with 2.0:
1. Check the box (on "year")
2. Switch the dropdown to "month"
3. The "year" monitor remains, with no "month" monitor.
This is consistent with 2.0
4. Uncheck the box
5. Instead of doing nothing, *like in 2.0*, it hides the "year" monitor. *This is a regression*.
6. Then if you check the box again, it shows the "month" monitor. In 2.0, *the "year" monitor would still be there*.

**Comment by fsih** [comment]
Adding Carl since this might need design

**Comment by thisandagain** [comment]
From design conversation: unlike Scratch 2.0, if the dropdown on a block in the toolbox is modified while a monitor is enabled, the monitor should change to reflect the current drop-down state.

/cc @carljbowman @paulkaplan

**Comment by fsih** [comment]
Say you check the box and change the dropdown from "current year" to "current month." Then you add a new sprite. Now the flyout goes back to saying "current year," and still has the checkmark next to it.
- Should the monitor now switch back to showing current year?
- Should it keep showing month, and only change again when the dropdown gets changed?
- Should the flyout have stayed on 'month' when you switched sprites? (Is it possible that different sprites would have different options in dropdowns?)
/cc @carljbowman @paulkaplan @thisandagain

**Comment by thisandagain** [comment]
@fsih Really good question. In 2.0 the block palette essentially "resets" between editing target changes which had some odd side-effects that aren't really handled. 

For simplicity (to avoid unintended side effects), my instinct is to go with either option 1 or option 2. I lean towards option 2 as that is most similar to the current behavior and my guess is will be seen as less surprising in most instances.

Curious to get input from @carljbowman and @paulkaplan

**Comment by fsih** [comment]
@thisandagain I would probably lean toward 2 then, since if you wanted to have a monitor that shows the current hour, it would be annoying if it kept changing back to year when you switched sprites.
