### ISSUE TITLE
Sound Editor

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#79]
_Updated by Paul, July 6th_

First Iteration will include

- [x] Play / Stop
- [x] Renaming
- [x] Start / End Trimmer 
- [x] Duplicate entire sound
- [x] Applying effects to an entire sound (chipmunk, monster, robot, echo, fuzz)

Not included this iteration
- undo/redo
- positive selection tool
- pause
- timing indications
- zooming

**Comment by paulkaplan** [comment]
This is finished as specified in the first iteration description. We should open a new one for design pass / improvements
