### ISSUE TITLE
Dragging in code from backpack deletes code

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-gui#7903]
Normally the code would be inserted into the coding area but instead it just deletes everything and you cant press undo. The only way to get your code back is to refresh the page before it autosaves. It also deleted the code when I copied it into my backpack and saved the project. Im pretty sure this is because it contains the character U+FFFF.

### Steps to reproduce
This might not work on all projects, but the ones ive tested it on, it does work
Just set a variable to include U+FFFF or a value to include U+FFFF (like u+ffff * 4)

### System Details
Currently using windows 10 with firefox 95.0

**Screenshots**
I get this error from line 511:33:
![image](https://user-images.githubusercontent.com/93948811/145680816-de25a975-bc14-4fb5-ba99-64876afeaba8.png)

**Comment by poglolreeeeeeeeeeeeeee** [comment]
I think this is because it contains the character U+FFFF but I dont know

**Comment by BryceLTaylor** [comment]
Could you provide reproduction steps?  What code do you need to drag into a project?  Do you have a link to a project this happens to?
