### ISSUE TITLE
Items in local lists are not kept with backpacked sprites

### ISSUE THREAD

**Issue by awesome-llama** [LLK/scratch-gui#7919]
### Expected Behavior

Local lists (those set to "for this sprite only") should have their data be stored in backpacked sprites. Local variables already do this.

### Actual Behavior

Instead, when a backpacked sprite is placed into a project, the local lists will be created with no values stored in them. However, if a sprite already has an identically named local list, the data from that will be copied over to the new sprite which can also be undesirable.

### Steps to Reproduce

Create a sprite and a local list in it. Add items to that list. Drag the sprite to the backpack. Now delete the old sprite or the local list (ensure that the list doesn't exist). Bring the backpacked sprite back into the project.

For the list data copied from another sprite, do the same as above but don't delete the sprite. Set the list values to something else instead. Then the backpacked sprite will be created using those changed values.

### Operating System and Browser

Tested on Chrome 96 on Windows 10.

**Comment by BryceLTaylor** [comment]
I am unable to reproduce the bug with the steps listed. I have seen an issue with the list monitors not being able to show the new sprite's list, but the list data remains for that sprite.  

I think that mostly has to do with blocks having the same ids.  We will file this issue separately and link back to this one.
