### ISSUE TITLE
How do I change Scratch's theme colour?

### ISSUE THREAD

**Issue by llunariis** [LLK/scratch-gui#7932]
Hi, I recently forked scratch-gui, and I noticed that some fellow forkers changed the theme of Scratch. Can you please tell me how?

**Comment by llunariis** [comment]
Hello?

**Comment by Brian586** [comment]
My solution was to edit the `colors.css` file 
File location: `scratch-gui\src\css\colors.css`

```
$motion-primary: hsla(215, 100%, 65%, 1); /* #4C97FF */
$motion-tertiary: hsla(215, 60%, 50%, 1); /* #3373CC */
$motion-transparent: hsla(215, 100%,65%, 0.35); /* 35% transparent version of motion-primary */
$motion-light-transparent: hsla(215, 100%, 65%, 0.15); /* 15% transparent version of motion-primary */
```

Just play around with the values above.
`$motion-primary` is used as the theme color.

**Comment by Mwalters75** [comment]
> My solution was to edit the `colors.css` file File location: `scratch-gui\src\css\colors.css`
> 
> ```
> $motion-primary: hsla(215, 100%, 65%, 1); /* #4C97FF */
> $motion-tertiary: hsla(215, 60%, 50%, 1); /* #3373CC */
> $motion-transparent: hsla(215, 100%,65%, 0.35); /* 35% transparent version of motion-primary */
> $motion-light-transparent: hsla(215, 100%, 65%, 0.15); /* 15% transparent version of motion-primary */
> ```
> 
> Just play around with the values above. `$motion-primary` is used as the theme color.

On the `gh-pages` branch?

**Comment by llunariis** [comment]
This isn't in the `gh-pages` branch. How can I make it for the `gh-pages` branch as well?
