### ISSUE TITLE
Rename "Save to your computer" to "Download"

### ISSUE THREAD

**Issue by Secret-chest** [LLK/scratch-gui#7968]
Title. It makes no sense to use such an obscure name.

**Comment by Chiroyce1** [comment]
> It makes no sense to use such an obscure name.

People might think `download` will download the entire editor, "Save to your computer" does make it seem more obvious that it will save the project.

**Comment by Secret-chest** [comment]
> > It makes no sense to use such an obscure name.
> 
> People might think `download` will download the entire editor, "Save to your computer" does make it seem more obvious that it will save the project.

"Download project"?

**Comment by kchadha** [comment]
The wording is intentional.
