### ISSUE TITLE
Code instructions are not rendered properly if page loaded in a hidden iframe

### ISSUE THREAD

**Issue by raquelhortab** [LLK/scratch-gui#7969]
### Expected Behavior

Scratch should be rendered normally

### Actual Behavior

If scratch (editor) is loaded in a hidden (`display:none`) iframe, once it is set to visible again, the code instructions are not rendered correctly. I guess it has something to do with the fact that it cannot calculate the size correctly if loaded while hidden.

### Steps to Reproduce

Load the editor in an iframe while it is set (or its container) to `display: none`. Then make it visible again, you should see something like the screenshot attached (note the code items section, the instructions are cut).

### System Details

Tried in Mozilla Firefox 96.0 (64-bit) for linux and in Google Chrome Version 97.0.4692.99 (Official Build) (64-bit).
Scratch version from the develop branch.

**Screenshots**
![Selection_141](https://user-images.githubusercontent.com/19463905/150745350-d3527ce2-fc74-4d4f-afee-dc5d95c00be3.png)

**Comment by kchadha** [comment]
> I guess it has something to do with the fact that it cannot calculate the size correctly if loaded while hidden.

This is correct. You'd need to reload the iframe to recalculate the size.

**Comment by raquelhortab** [comment]
It's not a nice way but the best I found: changed `display:none` to `visibility:hidden` and some other things to make my code look good according to this and it works now
