### ISSUE TITLE
Code Restructure

### ISSUE THREAD

**Issue by hacktronics** [LLK/scratch-gui#7984]
### Expected Behavior

In file: https://github.com/LLK/scratch-gui/blob/develop/src/components/menu-bar/account-nav.jsx
<MenuBarMenu in line 59 should be inside <div on line 36, it should be the children of div menu, not neighbor of div.
This actually causes menu css to be wrong, but because it is the last item, the effect is not visible, but still this is wrong.

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Go to 'https://scratch.mit.edu/...'

### System Details
_If the problem occurs in the browser, please provide operating system and browser e.g. Mac OS 10.11.6 Safari 10.0_

_If using one of the Apps please provide the app version and device details, e.g. Scratch 3.0.57, Android 9 on HP x360 Chromebook_

**Screenshots**

**Comment by BryceLTaylor** [comment]
Since there are no user visible issues we are going to close this.  If changes in the future cause this to be an issue we can fix it then.

**Comment by hacktronics** [comment]
Up to you, your code is not only used by MIT, but lot of others, and I wasted many hours for this really easy fix, as I was copying the accountNav to create another preference nav, and it was not working.
