### ISSUE TITLE
Negative numbers display incorrectly in monitor ranges for RTL/bidirectional text

### ISSUE THREAD

**Issue by matschaffer** [LLK/scratch-gui#8023]
This issue covers how they display incorrectly in monitoring range values.

### Expected Behavior

Numbers in RTL/bidirectional text should read left to right, including negation. 

### Actual Behavior

Numbers are shown RTL with the negation on the right which is incorrect.

**Screenshots**

![](https://user-images.githubusercontent.com/399209/77644775-f73bd780-6f37-11ea-864f-64b788d7d6a8.png)

**Comment by BryceLTaylor** [comment]
Tracking this in https://github.com/LLK/scratch-gui/issues/5483
