### ISSUE TITLE
How to create a extension or new blcok that can call an API and gets result

### ISSUE THREAD

**Issue by edwinjosechittilappilly** [LLK/scratch-gui#8024]
Hi all
I am using scratch for teaching kids,
I  had developed some REST API that returns some numbers. I  would Like to know how can I add an extension or a new block that accesses the REST API and returns the value.

**Comment by BryceLTaylor** [comment]
You can take a look at our extension documentation here: https://github.com/LLK/scratch-vm/blob/develop/docs/extensions.md
You can look at our translate extension, which does something similar: https://github.com/LLK/scratch-vm/blob/develop/src/extensions/scratch3_translate/index.js
