### ISSUE TITLE
Layer Problem with text cursor

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-gui#8033]
### Problem

I was adding a text element in the scratch costume editor, when I saw that the text cursor was behind the result view for the project.

In order to reproduce this bug, you have to create a text element in the far right side of the costume editor, and make sure the text goes out of the editor. The text cursor should appear outside the editor.

It's not neccesarily a scratch-breaking bug, just something I noticed.

### System Details
This occured on Chrome OS Version 98.0.4758.107, Scratch Version 3

**Screenshots**
![Screenshot 2022-02-27 11 18 21 AM](https://user-images.githubusercontent.com/74678692/155892514-1bbec858-f4dd-4240-8815-6212866b649d.png)

**Comment by BryceLTaylor** [comment]
This behavior is acceptable.

**Comment by ghost** [comment]
Got it. After writing this issue, I realized this wasn't necessarily a bug.
