### ISSUE TITLE
Multiple Scratch Gui instances

### ISSUE THREAD

**Issue by juliandierker** [LLK/scratch-gui#8049]
Dear Scratch-Gui-Team,

is there any way to provide multiple Scratch-Gui-Components with indipendent project-loading in 1 Dom-Tree?

I have made it to embed Scratch-Gui to my webapplication now but I have the problem, that every Scratch-GUI-Component loads the same project even with different Project-Ids.

Thx for the support.

**Comment by matschaffer** [comment]
@juliandierker I'd guess that this isn't a planned use case for scratch-gui. Are you able to share the code for your app? If I can run it in a debugger I might be able to see what's causing both embeds to load the same project id.

I'd guess there's maybe a global variable somewhere in the project loading code.

**Comment by juliandierker** [comment]
sure, i just wrote a small component which can be called more than 1's in a parent with a different project-code: 
(scratch-gui-pearup ist just a fork with some css changes)

`import React from "react";`
`import Scratch, { AppStateHOC } from "scratch-gui-pearup";`
`export default React.memo(function ScratchInfo({ code }: { code: string }) {`
`  const ScratchProject = new AppStateHOC(Scratch);`

 ` return <ScratchProject projectId={code} />;`
`});`
