### ISSUE TITLE
Project Player Corner Radius Issue in Chrome

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-gui#805]
### Expected Behavior

Corners of the project player are rounded with a grey background that matches the GUI background colour.

### Actual Behavior

Corners are rounded, but with a white background behind the rounded corners.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/6737342/31929964-d741e89e-b895-11e7-9500-92a250730d03.png)

I noted that this is not an issue in Firefox where the background is just as expected. This issue looks like a chrome bug rather than a styling issue. A work around is to set the background colour of the canvas to the same as the GUI grey, but it should have been unnecessary.

Interestingly with Chrome's 'hardware acceleration' turned off, the corners actually then go black! Also the entire canvas flashes black periodically as I click a block to execute it... Very weird.

![image](https://user-images.githubusercontent.com/6737342/31930377-732566cc-b897-11e7-9e47-b8196f03d831.png)

### Operating System and Browser

Chrome Version 62.0.3202.62 (Official Build) (64-bit) on windows 10 PC

**Comment by Kenny2github** [comment]
Interesting! I was able to repro this (Chrome 61.0.3163.100 (Official Build) (64-bit) on Windows 10) but it seems like there are four possible colors, disregarding the zoom:
White:
![corner white](https://user-images.githubusercontent.com/28599280/31932772-dec5d0be-b8d9-11e7-9b66-814d9e3deae6.PNG)
Blue:
![corner blue](https://user-images.githubusercontent.com/28599280/31932779-e3de5508-b8d9-11e7-8f4b-de478c0d9cbe.PNG)
Black:
![corner black](https://user-images.githubusercontent.com/28599280/31932791-ea549730-b8d9-11e7-9316-9d5fc168ed3f.PNG)
and GUI grey:
![corner good](https://user-images.githubusercontent.com/28599280/31932806-f00077a8-b8d9-11e7-9f7a-3a2e31402c27.PNG)
The color that appears seems to be random, but there are some constants:
* The color always changes when the amount of zoom is changed.
* The color *always* changes to black when you switch to a different tab then back.
* Overriding the previous points, 300% or less zoom is *always* white.
* The GUI grey seems to be less common than the other colors.

This definitely is a Chrome bug - Firefox shows the correct GUI color:
![firefox offset](https://user-images.githubusercontent.com/28599280/31933021-82c518e6-b8da-11e7-969c-f46a23369a2a.PNG)

This seems to be a problem with the way Chrome handles zoom - if you look at the two screencaps below they're obviously different:
Chrome:
![chrome zoom](https://user-images.githubusercontent.com/28599280/31933143-d7da257e-b8da-11e7-8cf6-6b932a4198a8.PNG)
Firefox:
![firefox zoom](https://user-images.githubusercontent.com/28599280/31933149-dde4cf14-b8da-11e7-9b50-83f07234afb2.PNG)

Versions:
Chrome 61.0.3163.100 (Official Build) (64-bit)
Firefox 47.0.2
Windows 10

**Comment by VutonDesign** [comment]
I can repro on Chrome 61.0.3163.100 (Official Build) (64-bit) using Windows 8.1 and Windows 7.

After checking with a few different browsers, It's definitely a Chrome bug.

**Comment by paulkaplan** [comment]
This is a strange one, I can find references to similar-ish bugs in chrome/webkit from a few years ago, but nothing recent. Welcome any fixes / ideas!

**Comment by griffpatch** [comment]
The only way I found to fix was to set the background colour of the canvas
to the desired gray colour... but that's not a nice fix!
