### ISSUE TITLE
Gray Question Mark does not show up in blocks workspace watermark

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#8101]
### Expected Behavior

Watermark should exist for all sprites (even with broken costumes) -- same as sprite selector item.

### Actual Behavior

If the sprite has a broken costume (e.g. gray question mark) there is no sprite watermark in the blocks workspace.

<img width="800" alt="Screen Shot 2022-03-14 at 5 42 01 PM" src="https://user-images.githubusercontent.com/1786240/158266234-111b1062-e1ae-4529-bbde-e30e1dd4cc32.png">

Stepping through in the console, the watermark does appear, so there is likely a race condition somewhere...

### Steps to Reproduce

Load a project with a broken or missing costume. See steps below to produce such a project:

1. In llk.github.io/scratch-gui/develop, create a project.
2. Draw your own costume or edit one from the library
3. Save the project to your computer
4. Unzip project
5. remove the image file for the costume you drew
6. Re-zip remaining contents and name it with .sb3 at the end
7. Upload the modified project.
8. Observe the gray question mark everywhere except the sprite watermark area

**Comment by BryceLTaylor** [comment]
I believe this is unrelated to the Gray Question Mark but is a duplicate of this issue: https://github.com/LLK/scratch-gui/issues/4703. Whatever the first costume you load is doesn't show a watermark.

**Comment by kchadha** [comment]
Yep! Definitely a dupe of #4703
