### ISSUE TITLE
Crash when creating a variable while cat blocks enabled

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#8106]
### Expected Behavior
Crash should not occur

### Actual Behavior
Crash occurs

### Steps to Reproduce

1. Go to [totally-normal-2022](https://llk.github.io/scratch-gui/hotfix/totally-normal-2022/) branch
2. Enable cat blocks via "Mode" -> "Show me cats"
3. Create a new variable or a list
4. See error on console (note, this consumes RAM as well, crashing my browser within a minute) - "TypeError: o is null"

### System Details
Windows 10, Firefox 98

**Comment by kchadha** [comment]
Thanks @apple502j! Turns out this is also a bug on develop if you switch languages in the editor (e.g. same repro steps above but switch languages instead of modes).
