### ISSUE TITLE
Remove Top Blocks Category

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#813]
"Top" blocks was used extremely infrequently during workshops. Based on this observations and discussions in yesterday's product meeting, the top category should be removed. 

![desktop - 1024 x 768](https://user-images.githubusercontent.com/3409578/32109071-9e9bd48c-bb01-11e7-80d2-f90e8d51d752.png)

**Comment by Kenny2github** [comment]
ah, well, it was a good idea while it lasted.
