### ISSUE TITLE
Add Extension Icons to Blocks and Category

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#815]
Carl to provide:
- [x] Spec for icons on blocks
- [x] Spec for icons in category menu
- [x] Icons for extensions
  - [x] Pen
  - [x] WeDo

**Comment by CosmicWebServices** [comment]
@carljbowman Design question: What happens when you have tons of extensions open... how will the toolbar handle them?

**Comment by carljbowman** [comment]
### Icon on bocks spec
This is a hi-res (300%) PNG for zooming on measurements. Extension Icons on blocks will need some special treatment when it comes to alignment and spacing.

In all cases the Vertical height of extension blocks will be taller than their "standard" block counter-parters. E.g. Command blocks with extension icons are 8px (2units) taller than a Command block without an extension icon.

**Something to Consider**
We will have similar needs to dynamically grow blocks vertically with "input first" blocks. Some languages reorder block parameters (e.g. Korean) and place inputs as the first element on a block. In these cases we will need to add addtional vertical padding so that the top notch does not overlap the input.

![r1_extension-icon-spec](https://user-images.githubusercontent.com/3409578/32376958-a8b1d13a-c07c-11e7-9833-e13701a0baf8.png)

**Comment by carljbowman** [comment]
@CosmicWebServices - Great question! This will be an ongoing issue as we think about multi-platform experiences. We are now facing the sea of varying screen sizes... 

Our initial thought was to make the category menu scrollable like the blocks palette. In addition to both spaces being scrollable we would like to make them have a dynamic relationship in displaying where you are in each. Forgive me as it's kind of awkward to describe in words...

So let's say you have small screensize and your category list extends off the bottom of the page. One could scroll the category list and click the bottom category and the blocks palette would jump to that category. Another way would be to scroll the blocks palette to the bottom, but we want to make sure that scroll is reflected in the category menu UI. The selected category indicator would slide to the bottom category and scroll the category menu to show you where you are in the larger blocks list.

Another way to think about it...  Because the blocks palette now includes all the blocks, the category menu will act as a navigation and a bird-eye's view of where you are in the blocks palette. Each space is representing the same list of blocks just at different scales. It's kinda similar to how "Contacts" on iOS and Android work. You have names are the most granular level and the alphabet scroll bar to quickly jump to that section of names.

We won't have this dynamic relationship anytime soon, but hope to explore this idea in the near future as we see this as a real need for the new extensions model.

**Comment by carljbowman** [comment]
## Pen & WeDo 2.0 Assets
<img width="424" alt="screen shot 2017-11-03 at 11 46 00 am" src="https://user-images.githubusercontent.com/3409578/32382802-969a0b88-c08c-11e7-8aee-54d48879bb17.png">

[pen-wedo2.zip](https://github.com/LLK/scratch-gui/files/1441593/pen-wedo2.zip)

**Comment by carljbowman** [comment]
## Icon in Category Menu
<img width="754" alt="screen shot 2017-11-03 at 11 52 20 am" src="https://user-images.githubusercontent.com/3409578/32383135-872c45a2-c08d-11e7-9627-99b3580b25a1.png">

**Comment by carljbowman** [comment]
Breaking into two issues: 
Ext Icon on Blocks: https://github.com/LLK/scratch-blocks/issues/1207
Ext Icon in Category Menu: https://github.com/LLK/scratch-gui/issues/855
