### ISSUE TITLE
Language dropdown looks like default html form on Firefox

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#816]
From mewtaylor during today's playtest

**Comment by Grinthy** [comment]
Can you provide more details? I don't understand.

**Comment by Kenny2github** [comment]
Same for Chrome:
![image](https://user-images.githubusercontent.com/28599280/33167123-82d27874-d077-11e7-93ef-52954fb50110.png)
This is not exactly a bug, it's more of a lack of a feature. The language dropdown is there as a test, it doesn't have any design yet.

**Comment by paulkaplan** [comment]
Looks ok to me in firefox now
