### ISSUE TITLE
Pen Extension only has one function, "erase all" 

### ISSUE THREAD

**Issue by Evil-Elvis** [LLK/scratch-gui#8166]
### Expected Behavior

Selecting the pen extension should load all functions. 

### Actual Behavior

Selecting the pen extension only loads one function, "erase all".

### Steps to Reproduce

I clicked Select Extensions, chose Pen.

1. Go to https://scratch.mit.edu/projects/666232301/editor/ (this is a remix of my daughter´s project
2. Click on Go Inside
3. Scroll down to Pen and click
4. See error of missing Pen tools

### System Details
Firefox 98.0.2, Win 10 Home, 21H2, Build 19044.1566

**Screenshots**

<img width="186" alt="Pen Tool" src="https://user-images.githubusercontent.com/64075103/160239172-6dfa84ab-db99-4276-880c-d5b975a8b241.PNG">

**Comment by Secret-chest** [comment]
You have selected the stage. Try to select a normal sprite.

**Comment by BryceLTaylor** [comment]
The pen has more functions on a sprite, but on the stage it only is supposed to have erase all.  This is because the stage doesn't move and the other functions require the sprite to move.
