### ISSUE TITLE
“say” block can't accept number input

### ISSUE THREAD

**Issue by felix2ch** [LLK/scratch-gui#817]
<img width="140" alt="screen shot 2017-10-29 at 10 09 01 pm" src="https://user-images.githubusercontent.com/6711220/32144587-d11e5006-bcf5-11e7-824a-963d6bf1849b.png">

### Expected Behavior
show “4” in stage

### Actual Behavior

nothing happened
### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by paulkaplan** [comment]
Thanks for the report! Fixing soon.
