### ISSUE TITLE
Can't turn the type bar when too much extensions are loaded

### ISSUE THREAD

**Issue by KingAgain** [LLK/scratch-gui#8187]
### Expected Behavior

Could turn the type bar when too much extensions are loaded

### Actual Behavior

Can't turn the type bar when too much extensions are loaded

### Steps to Reproduce

load a lot extensions

### System Details
Windows 7 Chrome 97

**Screenshots**

![image](https://user-images.githubusercontent.com/97130830/160805099-73b3f55a-aa56-42e8-9cd9-79b90191797d.png)

**Comment by BryceLTaylor** [comment]
Does it not scroll with a mouse wheel or two finger scrolling with a track pad?

**Comment by BryceLTaylor** [comment]
I'm closing for now.  You could refile it with more details if it remains an issue for you.
