### ISSUE TITLE
Trouble getting scratch-gui running locally

### ISSUE THREAD

**Issue by quachtina96** [LLK/scratch-gui#819]
### Expected Behavior
git clone [gui] && cd gui && npm install && npm start should result in seeing something like https://llk.github.io/scratch-gui/ upon visiting http://localhost:8601/.

### Actual Behavior
Visting http://localhost:8601/ presents a blank page and inspecting the developer tool console reveals an error:
![pasted image at 2017_10_29 10_29 am](https://user-images.githubusercontent.com/10423718/32146693-999ce050-bc98-11e7-9a5f-c444abb1e7b8.png)

### Steps to Reproduce
1. set version of node to be 6.0.0 using nvm
2. fork scratch-gui and clone fork
3. cd into clone of scratch-gui 
4. npm install
5. npm start
6. visit http://localhost:8601/
7. open developer tools console

I tried running "npm run build" and the gui built fine. But following that command with "npm start" still results in the same actual behavior presented above.

### Operating System and Browser
Mac OS 10.12.6 Chrome 61.0.3163.100

**Comment by rschamp** [comment]
The last build of `scratch-blocks` pushed a bad build up to `npm`. Sorry about that, it should be fixed now!
