### ISSUE TITLE
Eyedropper does not update sliders

### ISSUE THREAD

**Issue by gengshenghong** [LLK/scratch-gui#823]
### Expected Behavior

it should work.

### Actual Behavior

it does not work.

### Steps to Reproduce

1. Open https://llk.github.io/scratch-gui/develop/
2. in the "Sensing" category, find the block "color x is touching y?" block
3. change the value of "x" or "y" (the color argument)
4. click the color picker
5. Select a color on the stage
6. the value of "x" or "y" does not change to the selected color

### Operating System and Browser

It is a regression issue, as it works on https://llk.github.io/scratch-gui/
_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by gengshenghong** [comment]
Sorry, the value of "x" or "y" do changed, but the color value panel does not refreshed, seems like some refresh issues.

**Comment by paulkaplan** [comment]
Thanks for reporting this. I updated the name to be more specific.
