### ISSUE TITLE
Shouldn't show pop up when trying to delete last costume

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#824]
### Expected Behavior

Pop up should say "Can't delete the last costume", or maybe the X button shouldn't be there

### Actual Behavior

Pop up says "Are you sure you want to delete this sprite?" and no matter what you do it doesn't actually delete the costume. It's already kind of weird because it's a costume, not a sprite

### Steps to Reproduce

Try to delete all costumes from a sprite

### Operating System and Browser

Chrome on Windows

**Comment by thisandagain** [comment]
I would recommend that the "X" simply not appear.
