### ISSUE TITLE
Scratch 3.0 Preview Introduction Modal

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#828]
When we launch the Scratch 3.0 Preview we will need a modal to help contextualize the current state of 3.0, e.g. Calling out Features that are still in progress or that things might be a little buggy.

Info Considerations:
- Features in progress
- Things might be Buggy
- Link to Preview FAQ 
- Link to Feedback form ( to be put in the toolbar instead)

Initial UX Considerations / Questions:
- Does this open every time someone visits the Editor? Dismissible - "Do not show me again" check box type thing?
- We should also include links to the Preview FAQ and Feedback form in the Editor Toolbar
- It might be nice to include a Project ID load feature: simple a field to enter an ID or Project URL

**Comment by DeleteThisAcount** [comment]
May I ask what this is? Sounds exciting!

**Comment by carljbowman** [comment]
@DeleteThisAcount - Sure thing! This will be a model that will appear when you open the Scratch 3.0 Preview editor. It will help message this "preview" and things might be a little buggy to people who are new or haven't been following the progress of 3.0. We will also be providing a form so people can give feedback or report any issues.

**Comment by DeleteThisAcount** [comment]
even more exciting!!!

**Comment by VutonDesign** [comment]
@carljbowman Nice idea! 👍

**Comment by carljbowman** [comment]
## Overview
This modal should display when the Scratch 3.0 Preview is accessed.

## Mock
![preview modal](https://user-images.githubusercontent.com/3409578/33485382-2b9a6474-d674-11e7-9605-85bff324a725.png)

## Content
#### Illustration 
- [ ]  Illustration - @carljbowman

#### Copy
Header: `Welcome to the Scratch 3.0 Preview`
Copy: `We’re working on the next generation of Scratch.  We’re excited for you to try it!`

#### Buttons
`Not Now` - Should call the browsers Back command
`Try It!` 🐱 - Should dismiss the modal

#### Secondary Copy
Footer: `To learn more, go to the Preview FAQ.`
- [ ]  Preview FAQ page and content still being developed - @thisandagain @ChampikaF

**Comment by carljbowman** [comment]
@chrisgarrity - Updated my previous content with all the content except the Illustration, which I will provide once I have completed it.

For sizing purposes here is a **temporary** asset:
This asset is at 2x, it should be displayed at 494px x 208px (we can adjust that ratio as we see fit, but a good starting point).
![preview-illustration](https://user-images.githubusercontent.com/3409578/33901322-71b39b28-df3f-11e7-9cab-a448426fe194.png)

**Comment by chrisgarrity** [comment]
I have a functional version pending style/asset changes. Note that it shows the modal each time the preview is loaded.
