### ISSUE TITLE
Scratch 3.0 Preview "Coming Soon..." Tooltip

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#830]
## Overview
Not all 2.0 features will be present in the 3.0 Preview. We will need a component (possibly a tooltip type mechanism) to message that these features will be added in the future, but are still in progress.

## UI
In all cases we will need to have a inactive appearance to the feature. In some cases we may need to add an inactive element to convey that the feature will exists (e.g. "Convert to Bitmap"). See sketches (below) for inactive state reference. 
Icons & Assets: [tooltips-assets.zip](https://github.com/LLK/scratch-gui/files/1519314/tooltips-assets.zip)

## Langauge
The hope was to have a collection of general phrases that would be randomly assigned to a tooltip upon each interaction. The phrases should have a fun tone and communicate the state of the editor is "Work in Progress". 
#### Current phrases (we may add more)
- Don't worry, we're on it (scratch cat emoji)
- Coming Soon...
- We're working on it (scratch cat emoji)

## Initial List of Features
- [x] Save
- [x] Load
- [x] Language Selector 
- [x] Large Stage / Small Stage / Full Screen Toggles (currently always Large Stage)
- [ ] Text Tool in Vector Editor
- [ ] Convert to Bitmap (Bitmap Paint Editor in general)
- [x] Variable More Options (e.g. Local scoping)

### Save
![save](https://user-images.githubusercontent.com/3409578/33450889-4005101a-d5db-11e7-9914-405eb89ac973.png)

### Load
![load](https://user-images.githubusercontent.com/3409578/33450897-44db10b2-d5db-11e7-979a-0f8229b94c96.png)

### Language Selector
![language selector](https://user-images.githubusercontent.com/3409578/33450913-4dc29042-d5db-11e7-9a83-115339d787a9.png)

### Stage Sizing Toggles
![stage size](https://user-images.githubusercontent.com/3409578/33451616-9164621a-d5dd-11e7-89fb-87ec0c0dd724.png)

### Vector Editor Text Tool
![text tool](https://user-images.githubusercontent.com/3409578/33450964-6d76b94a-d5db-11e7-98bb-482b9977ab74.png)

### Convert to Bitmap
![convert to bitmap](https://user-images.githubusercontent.com/3409578/33450971-753aa20e-d5db-11e7-85db-2cd60b101e0c.png)

### Variable More Options (e.g. Local scoping)  
![local and cloud vars](https://user-images.githubusercontent.com/3409578/34169184-8b99e8e2-e4b4-11e7-9f02-a77cb8e90f7f.png)

**Comment by Grinthy** [comment]
How about this? [Click here](https://gist.github.com/Grinthy/2547cf1649651ca5f583e38583063550)

**Comment by mewtaylor** [comment]
@carljbowman should the `convert to bitmap` button be fixed to the bottom of the viewport, or should it just be below the canvas/zoom elements on the page? If we do the latter, we run the risk of it not being viewable on some screens, I think.

**Comment by thisandagain** [comment]
@carljbowman @mewtaylor For ease of implementation for now should we consider aligning the y position of the "Convert to Bitmap" button with the zoom controls?

**Comment by mewtaylor** [comment]
@thisandagain just looked at it with @carljbowman, and that looks great to both of us too, thanks for the suggestion!

**Comment by mewtaylor** [comment]
Close in https://github.com/LLK/scratch-paint/pull/240 and #1069
