### ISSUE TITLE
Can't rename variable; clicking "rename" item in context menu does nothing

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#832]
### Expected Behavior

Clicking "rename" item in context menu should prompt user to rename variable

### Actual Behavior

Clicking "rename" item in variable context menu does nothing.

![rename error](https://user-images.githubusercontent.com/3431616/32297384-67105cd6-bf25-11e7-85bf-dc48be70772b.gif)

### Steps to Reproduce

Create a variable; then right-click it and attempt to click the option to rename the variable

### Operating System and Browser

Mac OS 10.12.6 Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by paulkaplan** [comment]
Submitted a PR for this on scratch-blocks, https://github.com/LLK/scratch-blocks/pull/1204

Thanks for the thorough repro/animation, very useful! Out of curiosity, what do you use for making annotations on gifs like that?

**Comment by benjiwheeler** [comment]
Thanks.

I used Giphy Capture for Mac:
https://giphy.com/apps/giphycapture
