### ISSUE TITLE
<[] contains []> got removed?

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-gui#836]
I recall thisandagain opening an issue for the inclusion of a `<[] contains []>` Operators block - #601 
However, I see that it is no longer in the blocks palette...? When was it removed, and was it supposed to be?

**Comment by paulkaplan** [comment]
Woops, looks like it was lost when we moved the toolbox xml from blocks to GUI. Thanks for spotting this. Hard to catch that kind of thing in code reviews because there is no previous diff. I'll fix it quick.
