### ISSUE TITLE
侦测积木中的下拉选择框 field_dropdown 之间的联动有问题

### ISSUE THREAD

**Issue by OumCc** [LLK/scratch-gui#8361]
I'm sorry that my English is very poor. There may be ambiguity in English, so I wrote the question in Chinese.

in

https://scratch.mit.edu/projects/editor/?tutorial=getStarted

![May-31-2022 17-25-31](https://user-images.githubusercontent.com/10840542/171140881-09abe9a5-9ef3-4d37-83cd-9493a8ec3ece.gif)

### Expected Behavior

上面的 gif 中，该积木块如果在编辑区域的话，“舞台”、“角色 1”两个选项跟后面的选项之间的联动是正常的。

原本以为该积木在 flyout 中的表现跟在编辑区域的会一样，但实际上并不一样。

### Actual Behavior

如上图 gif，该积木在 flyout 中时，“舞台”、“角色 1”两个选项的切换无法联动后面的选项进行切换。

而且，如果在该积木在 flyout 中切换后，再拖到编辑区域的话，显示上会有问题。

**Comment by apple502j** [comment]
Duplicate of #6246

**Comment by OumCc** [comment]
@apple502j   thanks

But I use the latest code in the scratch-gui develop branch, there are still problems

**Comment by cwillisf** [comment]
Closing as a duplicate of #6246
