### ISSUE TITLE
Custom procedures shouldn't have duplicated proccode

### ISSUE THREAD

**Issue by alexcui03** [LLK/scratch-gui#8397]
### Expected Behavior

Custom procedures with duplicated proccode should not be created.

### Actual Behavior

Custom procedures with duplicated proccode can exist at the same time, which might cause unexpected runtime error.

### Steps to Reproduce

1. Create a custom procedure with name "test"
2. Create another new custom procedure with name "test"

### System Details

System: Windows 10
Browser: Chrome 103.0.5060.66

**Screenshots**
![image](https://user-images.githubusercontent.com/30141313/177138029-94e440b3-8db2-4196-9785-d302c357af98.png)

**Comment by cwillisf** [comment]
Thanks for the report! This is already filed as #1650 so I'll close this copy.
