### ISSUE TITLE
More formalized deploy/ test process as we approach release

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#840]
As came up in the Product Meeting (11/2/17), we need to have a more formal process for how we deploy to the master branch so we can keep it stable.

Details TBD.

- Manual tests?
- Automated tests?
- Observing behavioural diffs/ compatibility between 2.0 & 3.0?
  - Fatal exceptions can be caught by automated testing
  - Use the existing spreadsheet, but augment its current level of automation

**Comment by paulkaplan** [comment]
Implemented
