### ISSUE TITLE
Frequent "Project could not save" errors

### ISSUE THREAD

**Issue by q019278** [LLK/scratch-gui#8400]
### Expected Behavior

The project is unsaved everytime.

### Actual Behavior

-The 'Project Cannot Save" label is still appearing everytime I save a project.

**Screenshots**
![2022-07-07](https://user-images.githubusercontent.com/95750975/177757331-9c63728b-d56f-4e2b-9b58-2986f5b2db2b.png)

**Comment by cwillisf** [comment]
Sorry you're having trouble!

Here's some information that might help: https://mitscratch.freshdesk.com/en/support/solutions/articles/4000156807-common-reasons-you-can-t-save-a-project

If the problem continues, please try the "Get Help" option here: https://scratch.mit.edu/contact-us/

**Comment by cwillisf** [comment]
On further investigation, this seems to be affecting more projects and users than we thought. Reopening.

Thanks for reporting this!

**Comment by q019278** [comment]
Thanks @cwillisf

**Comment by q019278** [comment]
I got another one.
![2022-07-14](https://user-images.githubusercontent.com/95750975/178977397-f7dbed00-78d8-4cd8-8037-f4cc74140d92.png)

**Comment by cobaltt7** [comment]
@q019278 If you have browser extensions installed, could you try disabling the "Thumbnail setter" addon?

**Comment by cwillisf** [comment]
We believe we've fixed this on the server side. If you see this kind of trouble again, please let us know. Thanks!
