### ISSUE TITLE
Finally come to a conclusion for Scratch Labs.

### ISSUE THREAD

**Issue by PPPDUD** [LLK/scratch-gui#8414]
If you think this belongs somewhere else, please tell me.
Think that maybe, the ST could come to a conclusion for the Scratch Labs extensions and decide which ones will finally be in Scratch? I know what you are gonna say, "Scratch Labs stuff is still in development, blah blah blah...", but Scratch Labs can't wait forever for this!

Maybe, at say, maybe 8:30 PM on a weekend, the ST could temporarily lock up Scratch till 12:39 AM and have a discussion about the whole thing.

**Comment by PPPDUD** [comment]
Bump

**Comment by PPPDUD** [comment]
Bummp! iBump! eBump! ...eMate?

**Comment by Dhuls-Scratch** [comment]
> Bummp! iBump! eBump! ...eMate?

All bumping does on GitHub is spam emails, please don't do it.

> Maybe, at say, maybe 8:30 PM on a weekend, the ST could temporarily lock up Scratch till 12:39 AM and have a discussion about the whole thing.

So no moderation, and no development?
That's 4 hours, which is a lot of time for no moderation, and they could probably be doing other things than having a 4 hour conversation about 2 extensions

**Comment by PPPDUD** [comment]
Oh, you're right. Maybe there could be a vote or something? Also, thanks
for telling me that about bumps. That was quite kind of you to do.

**Comment by ericrosenbaum** [comment]
Thanks for asking! A lot of people are excited our Scratch Lab experiments. We've concluded based on the feedback that both of the current Scratch Labs (Animated Text and Face Sensing) would require some design and engineering work before they'd be ready to go into the community. Our team has had lots of other higher priority things to work on, so unfortunately there's no timeline for when that work might happen.

**Comment by PPPDUD** [comment]
That makes sense. You are very welcome! Thanks for responding to my issue!
Closing as soon as I get back on Github!
