### ISSUE TITLE
Revisit https://scratch.mit.edu/discuss/topic/80776/

### ISSUE THREAD

**Issue by PPPDUD** [LLK/scratch-gui#8457]
Think you could consider revisiting [this post](https://scratch.mit.edu/discuss/topic/80776/) now that Scratch 2.0 is out of the way? It is becoming increasingly important, now that the Scratch community has become so large. [Here](https://inf.ooo/g/B2l4OzMNJc) is an example project demonstrating how this would work. Note that you must manually enter in the above link or it won't work. I'm not sure why.

Thanks for reading and/or helping out with this! -PPPDUD, a fan of the cmlja3JvbGw.

**Comment by cwillisf** [comment]
Thanks for the report! I've moved this to: https://github.com/LLK/scratch-www/issues/6996
