### ISSUE TITLE
Suggestion: Block fourm titles that are a user's username

### ISSUE THREAD

**Issue by PPPDUD** [LLK/scratch-gui#8461]
Because people have been making random posts like this one about dogs using this method.

**Comment by cwillisf** [comment]
Sounds like you might be having some trouble with other Scratchers in the forums. If someone is not following the community guidelines, please report the post in the forums.

For suggestions or problems with the forum itself, please file issues here: https://github.com/LLK/scratch-www/issues/

**Comment by PPPDUD** [comment]
Doke!
