### ISSUE TITLE
ENA-142 Translation language monitor can be made to lag behind language selection

### ISSUE THREAD

**Issue by gorbyr** [LLK/scratch-gui#8499]
### Expected Behavior

Monitor label of extension blocks should be re-rendered in the new language when a new language is selected.

### Actual Behavior

Monitor label of extension blocks is re-rendered in the previous language when a new language is selected.
If changed value because a new language is selected, re-rendered in the new language.

### Steps to Reproduce

Assume the current language is English (en).

1. Add the Translate extension.
2. Check the language block.
3. Switch language to 日本語 (ja).
4. The language label are in 日本語 (ja). 
5. Switch language to にほんご (ja-Hira).
6. The language label are still in 日本語 (ja).

*If dose not reproduce, switch language a few times.

**Comment by benjiwheeler** [comment]
Here are some additional steps that produce unexpected behavior.

You can get the monitor to behave in strange ways that seem to lag behind the selection. This only seems to happen in these varieties of Japanese.

1. Add the Translate extension.

2. Check the language block.

3. Switch language to Français.

4. Switch language to 日本語 (ja).

5. Monitor appears with both text and language value in 日本語 (ja): 
<img width="133" alt="image" src="https://user-images.githubusercontent.com/3431616/189927511-f55744ac-cd83-442b-a7f0-9ceaddd50a0a.png">

6. Switch language to にほんご (ja-Hira).

7. Monitor still appears with both text and language value in 日本語 (ja): 
<img width="133" alt="image" src="https://user-images.githubusercontent.com/3431616/189927511-f55744ac-cd83-442b-a7f0-9ceaddd50a0a.png">

8. Switch language back to 日本語 (ja).

9. Monitor appears with text in にほんご (ja-Hira), but language value still in 日本語 (ja):
<img width="176" alt="image" src="https://user-images.githubusercontent.com/3431616/189927887-beb1c009-5d4e-40ed-97f9-b09cde2afdd5.png">
