### ISSUE TITLE
Add optional ads to the website by default for signed out users.

### ISSUE THREAD

**Issue by PPPDUD** [LLK/scratch-gui#8561]
They would be only on the front page. Also, they would make sure not to break COPPA law, or sell personal information. At the bottom of the page, there would be more ads and a button to disable/enable them. This would help the ST to get more money, which means more workers, and so on. Especially the much needed engineers you are looking for. By default, ads would be turned off for signed in users, however they could change this using the Account Settings.

**Comment by benjiwheeler** [comment]
Thanks for the suggestion! My guess is that Scratch will not choose to run ads. I'm closing this issue for now, but this is a possibility that could be considered in the future.

**Comment by PPPDUD** [comment]
Acceptable. I can go with that. Thanks for the update.

**Comment by ilikecereal1legacy** [comment]
Wait, Scratch is non-profit, and therefore it would become a profitable company and scratch will lose it’s status. This will kill scratch :(

**Comment by PPPDUD** [comment]
Oh. Right.
