### ISSUE TITLE
Problem with running this repo on web

### ISSUE THREAD

**Issue by zoraezimran** [LLK/scratch-gui#8562]
### Expected Behavior

Go to the scratch code editor as it normally should

### Actual Behavior

Showing this error 

![image](https://user-images.githubusercontent.com/82158378/195061650-e1511482-4b54-47ad-89ae-2ba24653e9b2.png)

### Steps to Reproduce

Unknown

### System Details

OS = Windows 10
Browser = Chrome

**Screenshots**

![image](https://user-images.githubusercontent.com/82158378/195061827-e39d9b9d-de42-45b1-9792-180b41a00b53.png)

**Comment by zoraezimran** [comment]
https://github.com/CoderEdits/CoderEdits.github.io/issues/10 mentioned here

**Comment by benjiwheeler** [comment]
@ZI-Youtuber could you please post more specific steps? For instance, start from cloning the repo, say what your npm version is, etc.

**Comment by zoraezimran** [comment]
@benjiwheeler  @cwillisf  look https://coderedits.github.io/Scratch-Code-Editor/master/

**Comment by benjiwheeler** [comment]
@ZI-Youtuber, that link doesn't seem to work -- feel free to reopen/recreate this issue, and please include specific steps to reach the problem.
