### ISSUE TITLE
Play sound block set to non-existant sound

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#857]
### Expected Behavior

The 'play sound' block should be set to the new sound

### Actual Behavior

The 'play sound' block still says meow, even though that's not a sound anymore. The dropdown only says the new sound.

### Steps to Reproduce

Pull a 'play sound meow' block to the workspace
Go to sounds
Add a new sound
Delete meow
Go back to workspace

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by kyleplo** [comment]
This can be closed

**Comment by paulkaplan** [comment]
Closing because we decided we will not automatically update blocks when assets are deleted.
