### ISSUE TITLE
Scratch 3 crashing when audio gets deleted

### ISSUE THREAD

**Issue by smj-edison** [LLK/scratch-gui#858]
### Expected Behavior
When the audio gets deleted (while playing), the audio should stop, be disconnected from all things that depend on it, and get deleted.

### Actual Behavior
Crashes when the audio gets deleted, because something still depends on it.

Error message:
Uncaught TypeError: Cannot read property 'soundId' of undefined
    at t.value (lib.min.js:6)
    at Function.B [as mapToProps] (lib.min.js:106)
    at o (lib.min.js:29)
    at s (lib.min.js:68)
    at u (lib.min.js:68)
    at lib.min.js:68
    at Object.run (lib.min.js:29)
    at c.onStateChange (lib.min.js:29)
    at Object.notify (lib.min.js:68)
    at e.notifyNestedSubs (lib.min.js:68)

### Steps to Reproduce

1. Select the default cat sprite (if it's not selected)
2. Go to the Sounds tab
3. Slow down the meow sound ~10 times
4. While it's playing, delete the sound

### Operating System and Browser
Ubuntu 14.04 (linux), Chrome 61

**Comment by fsih** [comment]
Scratch 3.0 crashes when a sound is deleted. (You don't have to edit it first, and it doesn't have to be playing to cause the crash). This was a pretty big issue during the playtest today.

**Comment by smj-edison** [comment]
It doesn't have a problem when the entire sprite gets deleted.

**Comment by smj-edison** [comment]
I think it happens at line 43 in src/containers/sound-editor.jsx

**Comment by Grinthy** [comment]
Hmmm, sounds interesting. I'll test it when I get home.

**Why if a sound is deleted, that whole thing crashes?**
