### ISSUE TITLE
Need infos on how to make a working scratch with save-to-server functionality

### ISSUE THREAD

**Issue by essedev** [LLK/scratch-gui#8591]
So to have a working copy of Scratch, with auto save functionality, the possibility to enbed in an iframe ecc.., I have to recreate the whole API system? I just installed scratch-gui but I'm not really understanding what else I need. Thanks, any help will be really appreciated!

_Originally posted by @doppiaesse in https://github.com/LLK/scratch-gui/issues/5158#issuecomment-1281073249_

**Comment by apple502j** [comment]
Yes, you need an API backend to save a project.

See https://github.com/LLK/scratch-gui/blob/develop/src/lib/storage.js for how the endpoint is registered.

**Comment by essedev** [comment]
What about saving the file project to server? Like the "save to computer" button, but make it automatic and save to server. Then auto load from file.

**Comment by apple502j** [comment]
That's what the code is for!

**Comment by essedev** [comment]
Okay but it's possible without creating an API server to contact ecc., just calling a function somewhere? I will be glad if you could give me some more information 🙏

**Comment by benjiwheeler** [comment]
We are not going to be able to fully address this question, but we encourage you to continue the conversation!
