### ISSUE TITLE
"New message" behaves like normal dropdown items (no dialog)

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-gui#861]
### Expected Behavior

Selecting the "new message" option from a broadcast-related block should open a dialog or prompt asking for the new name, and fill that into the input.

### Actual Behavior

The "new message" option behaves just like a normal dropdown item. When selected, it simply sets the input value to "new message". No dialog appears. Also, there is no error of any kind in the console.

### Steps to Reproduce

Select "new message" from any broadcast-related block (when I receive, broadcast, or broadcast and wait).

### Operating System and Browser

Debian (Testing), Firefox 57.0.

**Comment by mrjacobbloom** [comment]
A combo box here could be pretty cool too!

**Comment by kyleplo** [comment]
What if message creation was structured similarly to variable creation. In the events category, there would be a new message button. When a message was created, a "Boolean variable" would appear in events. This would be false except while message-related code was running.
### Example

1. Cat sprite broadcasts message "message1"
2. "message1" variable becomes true
3. Dog sprite gets message and runs some code
4. Cat continues with code, unless the "broadcast %m.broadcast and wait" block was used
5. Dog finishes code
6. "message1" variable becomes false
7. Cat continues if the "broadcast %m.broadcast and wait" block was used
