### ISSUE TITLE
Develop branch deploy page crashed

### ISSUE THREAD

**Issue by gengshenghong** [LLK/scratch-gui#863]
### Expected Behavior

Should work.

### Actual Behavior

Crashed.

### Steps to Reproduce

1. open https://llk.github.io/scratch-gui/develop/
2. cannot open it...console error as below:
lib.min.js:34You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.o @ lib.min.js:34(anonymous function) @ lib.min.js:34(anonymous function) @ lib.min.js:34t @ lib.min.js:29(anonymous function) @ lib.min.js:39t @ lib.min.js:29(anonymous function) @ lib.min.js:39t @ lib.min.js:29e.exports.Object.defineProperty.value @ lib.min.js:29t @ lib.min.js:29e.exports.Object.create.constructor.value @ lib.min.js:39t @ lib.min.js:29(anonymous function) @ lib.min.js:39t @ lib.min.js:29(anonymous function) @ lib.min.js:34t @ lib.min.js:29e.exports.e.__esModule.default @ lib.min.js:34t @ lib.min.js:29(anonymous function) @ lib.min.js:29(anonymous function) @ lib.min.js:29t @ lib.min.js:1(anonymous function) @ lib.min.js:68t @ lib.min.js:1(anonymous function) @ lib.min.js:29t @ lib.min.js:1137 @ index.jsx:4t @ lib.min.js:1window.webpackJsonp @ lib.min.js:1(anonymous function) @ gui.js:1
lib.min.js:39Uncaught TypeError: Object.values is not a function

### Operating System and Browser

All...

**Comment by towerofnix** [comment]
The editor runs correctly for me, though I get the same console error.

**Comment by griffpatch** [comment]
I am very sad that I can no longer build scratch-vm locally under windows
:( - Has anyone else got this issue?

npm start gives:

    ERROR in ../scratch-render/dist/node/scratch-render.js
    Module not found: Error: Can't resolve 'fs' in
'C:\Users\griffpatch\Documents\GitHub\scratch-render\dist\node'
     @ ../scratch-render/dist/node/scratch-render.js 10156:17-30
     @ ../scratch-render/dist/node/scratch-render.js
     @ multi (webpack)-dev-server/client?http://0.0.0.0:8073
stats.js/build/stats.min.js highlightjs/highlight.pack.min.js
scratch-blocks/dist/vertical.js scratch-audio scratch-render

**Comment by thisandagain** [comment]
@griffpatch I think that is a separate issue. Can you please file?

@gengshenghong I can see that error, but the editor on the `develop` branch loads for me on Chrome and Firefox. Can you please clarify that browser / OS you are using and exactly what you are seeing (screenshots are helpful)?

**Comment by gengshenghong** [comment]
it is an empty page. and it works for me previous. the master version works also. it is on Ubuntu 14.04 and chrome. i will check more oses and post more information. i thought it was an issue for all oses as it worked for a long time.

**Comment by gengshenghong** [comment]
@thisandagain Tested on multiple OSes, results as below.

Failed on:
1. Ubuntu 14.04, Chrome: Version 50.0.2661.94 (64-bit)
2. Windows 7, Chrome: Version 50.0.2661.102 m
3. Ubuntu 14.04, Firefox: Version 46.0
Works on:
4. Mac OS X Sierra (10.12.6), Chrome: Version 62.0.3202.75
5. Mac OS X Sierra (10.12.6), Safari

I guess it is an incompatibilities issues on lower version of browsers introduced recently (as it works for me previous).

To be mentioned, the "lib.min.js:34You are currently using minified code outside of NODE_ENV..." is not an issue (as I guess it is just some configurations of deploy). The key error is "lib.min.js:39Uncaught TypeError: Object.values is not a function", see below screenshot:
![image](https://user-images.githubusercontent.com/1018468/32478334-302f0354-c3bf-11e7-8b81-f555ab86191d.png)

**Comment by gengshenghong** [comment]
It is strange that I've built the develop branch locally (with a clean `npm install` and `npm start`) and run in the same browser. Everything just works....It seems like some deploy issues on github server?

**Comment by paulkaplan** [comment]
@gengshenghong yeah `Object.values` looks like it was only supported 1 year ago by some of the major browsers. It is actually only being used by scratch-paint, so i'll move this issue there.

**Comment by gengshenghong** [comment]
@paulkaplan Thanks for the clarification, that makes sense as local build will not use develop branch of scratch-paint.

I agree Chrome 50 is a little old, but this might be very common in users computers. We should try to make it work with polyfill as it does not have side-effect, and will only benefit more users.

Thanks,
Shenghong

**Comment by paulkaplan** [comment]
Yeah I agree @gengshenghong. I submitted https://github.com/LLK/scratch-paint/pull/196 to resolve it. 

@rschamp do you know if we can use eslint rules to prevent this? Or have babel transform things like this?

**Comment by rschamp** [comment]
Babel opts to provide a polyfill for these rather than transforming them: https://babeljs.io/docs/usage/polyfill/. I think it would be worth trying that out for this type of thing. I'm not sure what effect it has on file size/performance (though in some cases, the polyfilled implementation can outperform native browser implementations).
