### ISSUE TITLE
Squished "Add extension" button/ icon

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#864]
### Expected Behavior

There should be a little bit of space around the icon/ button that lets you add a new extension (at the bottom of the category menu).

### Actual Behavior

Currently it looks squished.

<img width="435" alt="screen shot 2017-11-03 at 1 04 20 pm" src="https://user-images.githubusercontent.com/1320456/32448470-f9840d1e-c2dc-11e7-99dd-32755437c407.png">

### Steps to Reproduce

Go to https://llk.github.io/scratch-gui/develop/ and look in the bottom left for the Add Extensions button.

### Operating System and Browser

_Mac OS El Capitan, Chrome_

**Comment by mrjacobbloom** [comment]
Could be worse in other languages too

**Comment by Grinthy** [comment]
Hmmm, I don't see anything.

Could your screen resolution be off, or your picture got distorted?

**Comment by paulkaplan** [comment]
Fixed by removing the text ;)
