### ISSUE TITLE
All code is hidden

### ISSUE THREAD

**Issue by byhal** [LLK/scratch-gui#8640]
### Expected Behavior

_I should be able to view all of the code with no issues._
### Actual Behavior

_All code is hidden on all sprites. Example:_

![image](https://user-images.githubusercontent.com/69502131/201504461-80ce4b02-471a-4059-92b3-4da7263c23d9.png)

### Steps to Reproduce

_Load the file I attached into TurboWarp (Normal Scratch will never load it, also make sure to change the extension to .sb3) _
[Main-wave Map Editor.zip](https://github.com/LLK/scratch-gui/files/9996455/Main-wave.Map.Editor.zip)

### Operating System and Browser

_Windows 11 latest build, Opera GX latest build_

**Comment by mxmou** [comment]
> Normal Scratch will never load it

If the file was saved using Scratch and doesn't load, that's a much more serious bug. If it was not made with Scratch, this isn't a Scratch bug.

**Comment by benjiwheeler** [comment]
@PerlinNoise-ops I'd love to see reproduce steps that start with a new project -- I'm not sure we can debug an existing project file if we don't know the steps to create it. Closing this for now, but feel free to add repro steps and tag me to reopen!
