### ISSUE TITLE
Add select multiple sprites feature

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#867]
This isn't an issue, more of a feature request. When I'm selecting sprites or costumes, I think it would be a good idea to allow you to select multiple sprites/costumes in just one click of the new sprite button.
## Example
Let's say you want to combine the cat and dog sprites
### Expected result
One sprite has all of the cat and dog costumes.
### Current Process

1. Add the cat sprite
2. Go to the costumes tab and click add costume from costume library
3. Select the first costume of the dog sprite
4. Repeat 2 and 3 until you have all of the dog costumes

### Future Process

1. Open the costume library and select the cat sprite
2. Hold shift and click on the dog sprite

**Comment by towerofnix** [comment]
Ahh, so multiple selection in the sprite/costume/sound/backdrop (media) libraries?

**Comment by redmangospros** [comment]
I argee with this. Maybe you cpuld select differnt sprites at  one time. 😀

**Comment by VutonDesign** [comment]
> Maybe you cpuld select differnt sprites at one time. 😀

That's basically what this issue is for...

**Comment by redmangospros** [comment]
Yeah, i acutully like this.

**Comment by thisandagain** [comment]
We currently do not have plans to support this feature as from testing we have found that the ability to single click on a sprite, costume, sound, or backdrop to add it is more intuitive than requiring a two-step process (as is used in Scratch 2.0). The removal of this confirmation step makes adding this feature difficult / unclear.
