### ISSUE TITLE
How do I make non-existent blocks?

### ISSUE THREAD

**Issue by itokt** [LLK/scratch-gui#8680]
Just a question, how do I make custom blocks that don't exist, not talking about the ones you make my going to the my blocks tab, but the blocks that look real but are fake.

**Comment by jorissaenen** [comment]
Your question is already answered on Stackoverflow: https://stackoverflow.com/questions/70234550/mit-scratch-build-how-to-create-custom-blocks-or-change-text

**Comment by hyperobject** [comment]
Thanks for handling this, @jorissaenen! That StackOverflow answer is a good resource for this.
