### ISSUE TITLE
ChromeDriver installation failed: fs.rmSync is not a function

### ISSUE THREAD

**Issue by a-turtle9302** [LLK/scratch-gui#8697]
### Expected Behavior

_Please describe what should happen_

Installs normally

### Actual Behavior

_Describe what actually happens_

```
npm ERR! code 1
npm ERR! path /home/jason/scratch-gui/node_modules/chromedriver
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
npm ERR! Downloading from file:  https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_linux64.zip
npm ERR! Saving to file: /tmp/107.0.5304.62/chromedriver/chromedriver_linux64.zip
npm ERR! Received 1040K...
npm ERR! Received 2080K...
npm ERR! Received 3120K...
npm ERR! Received 4160K...
npm ERR! Received 5200K...
npm ERR! Received 6240K...
npm ERR! Received 7280K...
npm ERR! Received 7434K total.
npm ERR! Extracting zip contents to /tmp/107.0.5304.62/chromedriver.
npm ERR! ChromeDriver installation failed TypeError: fs.rmSync is not a function
npm ERR!     at copyIntoPlace (/home/jason/scratch-gui/node_modules/chromedriver/install.js:314:6)
npm ERR!     at install (/home/jason/scratch-gui/node_modules/chromedriver/install.js:73:11)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jason/.npm/_logs/2022-12-05T22_45_32_320Z-debug.log
```

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

Install on crostini with node v12.22.12

### System Details
_If the problem occurs in the browser, please provide operating system and browser e.g. Mac OS 10.11.6 Safari 10.0_

_If using one of the Apps please provide the app version and device details, e.g. Scratch 3.0.57, Android 9 on HP x360 Chromebook_

Crostini on an
Acer Chromebook Spin 713 (CP713-3W)

**Screenshots**

![image](https://user-images.githubusercontent.com/105884277/205761396-c40e645f-6a3b-4ff8-8e44-5dd4d4c0882b.png)

**Comment by cwillisf** [comment]
Hello! Sorry for the trouble. This is an incompatibility between newer versions of `node-chromedriver` and older versions of Node.js. It should work if you upgrade to Node version 14.14.0 or above. I recommend the Node 16 series.
