### ISSUE TITLE
Costume editor doesn't resize 

### ISSUE THREAD

**Issue by OldGuy111** [LLK/scratch-gui#8708]
**NOTE: The bug is fixed in the official website.**
### Expected Behavior

The costume editor should resize to the screen.

### Actual Behavior

The costume editor stays at a fixed size.

### Steps to Reproduce

Just open the costume editor.

### Operating System and Browser

Windows 10 22H2 with Chrome 108.0.5359.99 64 bits

**Comment by CST1229** [comment]
If you're using https://llk.github.io/scratch-gui/master, that version is outdated. Use https://llk.github.io/scratch-gui/develop instead.

**Comment by OldGuy111** [comment]
Made that mistake. The "develop" version is the official website's. They should be inverted.

**Comment by benjiwheeler** [comment]
Sounds like the issue is just that the master branch is not up to date. Please comment if you're still seeing a problem with the editor on the develop branch.
