### ISSUE TITLE
Cannot Create A Project

### ISSUE THREAD

**Issue by q019278** [LLK/scratch-gui#8710]
### Expected Behavior

It supposed to be starting a project.

### Actual Behavior

It doesn't start a project or there's somethings wrong with my account.

### Steps to Reproduce

Those are the steps that I did

1. Go to 'https://scratch.mit.edu/...'
2. Click on 'new project'
3. And The Orange box reads 'Could Not Create The Project'
4. Reload A Few Times But Still No Use

**Screenshots**

![2022-12-13](https://user-images.githubusercontent.com/95750975/207256208-0b22ecf7-87fa-451f-84b9-906633455268.png)

**Comment by davdu81** [comment]
Same problem

**Comment by q019278** [comment]
OK. Does anybody who can help it out?

**Comment by CST1229** [comment]
The Scratch servers were probably down.

**Comment by benjiwheeler** [comment]
There was an outage, sorry you had this problem! It is fixed now!
