### ISSUE TITLE
-infinity is not smaller than any negative number

### ISSUE THREAD

**Issue by n3than** [LLK/scratch-gui#8711]
### Expected Behavior

-infinty < any negative number

### Actual Behavior

-infinity is not smaller than any negative number

### Steps to Reproduce

try it

1. Use scratch

### System Details
Windows 11, Latest Chrome.

**Comment by mxmou** [comment]
It works as expected for me.
![image](https://user-images.githubusercontent.com/51849865/207665664-40b0824d-1566-48fb-a2dc-a10b8997ca7f.png)
![image](https://user-images.githubusercontent.com/51849865/207665904-338d7684-a591-4d03-a900-dce426a89aee.png)

Note that it's case sensitive - lowercase "infinity" will be treated as text and compared using alphabetical order.

**Comment by n3than** [comment]
That is a problem too. The normal infinity does not come with the same properties.

**Comment by benjiwheeler** [comment]
Sounds like this specific issue is ok? Please comment if there's still a problem, and provide steps to reproduce the problem.
