### ISSUE TITLE
Scratch GUI React throws 403

### ISSUE THREAD

**Issue by juliandierker** [LLK/scratch-gui#8723]
`import Scratch, { AppStateHOC } from "scratch-gui";`

PSEUDO REACT CODE

`REACT COMPONENT`
`const ScratchProject = new AppStateHOC(Scratch);`

`return <ScratchProject projectId="773857055" />`

`</REACT COMPONENT>`

throws `GET https://projects.scratch.mit.edu/773857055 403`

leads to

throws `gui Unhandled Error: Error: Error in Scratch GUI [location=http://localhost:3000/material/teachingUnit/5fqqTukMo9zqZR6KW]: 403    at GUI.render (/node_modules/scratch-gui/dist/scratch-gui.js:357884:15)`

long version scratch-gui.js:357884 Uncaught Error: Error in Scratch GUI [location=http://localhost:3000/material/teachingUnit/5fqqTukMo9zqZR6KW]: 403
    at GUI.render (scratch-gui.js:357884:15)
    at finishClassComponent (modules.js?hash=bfb0dcaf5db6078cea5f7323d8f60e2ccfa99d11:75779:31)
    at updateClassComponent (modules.js?hash=bfb0dcaf5db6078cea5f7323d8f60e2ccfa99d11:75729:24)
    at beginWork (modules.js?hash=bfb0dcaf5db6078cea5f7323d8f60e2ccfa99d11:77239:16)
    at HTMLUnknownElement.callCallback (modules.js?hash=bfb0dcaf5db6078cea5f7323d8f60e2ccfa99d11:58807:14)
    at Object.invokeGuardedCallbackDev (modules.js?hash=bfb0dcaf5db6078cea5f7323d8f60e2ccfa99d11:58856:16)
    at invokeGuardedCallback (modules.js?hash=bfb0dcaf5db6078cea5f7323d8f60e2ccfa99d11:58911:31)
    at beginWork$1 (modules.js?hash=bfb0dcaf5db6078cea5f7323d8f60e2ccfa99d11:81822:7)
    at performUnitOfWork (modules.js?hash=bfb0dcaf5db6078cea5f7323d8f60e2ccfa99d11:80773:12)
    at workLoopSync (modules.js?hash=bfb0dcaf5db6078cea5f7323d8f60e2ccfa99d11:80749:22)

**Comment by juliandierker** [comment]
this behavior worked for over a year and is broken since 1-2 weeks

**Comment by juliandierker** [comment]
seems like project path changed to https://scratch.mit.edu/projects - is this not updated in scratch-gui package?
so it seems like project fetcher might not updated

**Comment by juliandierker** [comment]
https://github.com/LLK/scratch-gui/compare/develop...juliandierker:scratch-gui:patch-1

**Comment by juliandierker** [comment]
this maybe is not the solution but it shows the problem.. if i change the path here i get cors error for sure

**Comment by mxmou** [comment]
`projects.scratch.mit.edu/<id>` is still the correct URL, but scratch-gui now requires a `projectToken` to be set in addition to the `projectId`.

**Comment by juliandierker** [comment]
thx @mxmou where do i get and set this project token? 
or is scratch gui not meant for public use anymore?

**Comment by mindbicycles** [comment]
I'm getting the same cors error on the scratch-vm repo and scratch-gui. If I download the project file and change the code to load it from my local relative path it works. But I can't load from https://scratch.mit.edu/

 I'm trying to modify the vm loadProject() function to get the project_token like in this example I found on github:

https://github.com/PullJosh/leopard-website/blob/f7398c73b2e79854b732f3cc984eae1b06eac6d6/pages/api/%5BprojectId%5D/codesandbox.ts

but I still get a cors error trying to get the project data to extract the token

Will this never work on localhost due to cors?
Will it work if I upload to a website?  Loading does work for https://leopardjs.com/ but maybe the https://scratch.mit.edu/ cors configuration allows it?

**Comment by mxmou** [comment]
> thx @mxmou where do i get and set this project token? or is scratch gui not meant for public use anymore?

The token can be obtained by fetching `https://api.scratch.mit.edu/projects/<id>` - this has to be done every time the project is loaded because tokens expire. You can then pass it as a prop called `projectToken` to the GUI component.

> I'm trying to modify the vm loadProject() function to get the project_token like in this example I found on github:
> 
> https://github.com/PullJosh/leopard-website/blob/f7398c73b2e79854b732f3cc984eae1b06eac6d6/pages/api/%5BprojectId%5D/codesandbox.ts
> 
> but I still get a cors error trying to get the project data to extract the token

`api.scratch.mit.edu` doesn't accept requests from any origin other than `scratch.mit.edu`. Leopard works around this by converting projects on the server side. It's also possible to use a CORS proxy.

**Comment by juliandierker** [comment]
thx @mxmou this helps a lot :)

**Comment by juliandierker** [comment]
@mxmou one last question before closing this? is there any way to get informed of breaking changes? i maintane a big app for digital learning material and if something like this changes it would be important for me to notice

**Comment by mindbicycles** [comment]
@mxmou thanks a lot for taking the time to clarify that. Would be great to update the readme.md files of the gui and vm,  explaining this.

@juliandierker I've tried making a super basic proxy here: https://replit.com/@mindbicycles/scratchCorsProxy#server.js and it doesn't work on Replit but it works if I download the whole folder and run it on my computer

**Comment by juliandierker** [comment]
@mindbicycles you cant fetch this when client is involved this fetch has to be performed on a server only file on node js:

my code for that is: 

`const response = await fetch(`https://api.scratch.mit.edu/projects/${projectId}/`);
      const json = await response.json();
      return json.project_token;`

**Comment by juliandierker** [comment]
@mindbicycles can i see your project deployed somewhere? :D would be very interested

**Comment by mindbicycles** [comment]
sorry, I don't have a server, that's why I was trying replit. But you should be able to run it locally. Email me at gmail if you need help with that

**Comment by mindbicycles** [comment]
here's a CORS proxy that downloads the project using the token. https://gist.github.com/mindbicycles/c6186061a0b64c9e2026c85b20944f14
It's in PHP, in case your server doesn't easily support Express as in my example above.

to use it, add the php to your host, then modify this line on lib/project-fetcher-hoc.jsx
        projectHost: 'https://projects.scratch.mit.edu'
 replacing it by your server + the php + these params:
        projectHost: 'https://yourdomain.com/proxy.php?csurl=https://api.scratch.mit.edu/projects'
