### ISSUE TITLE
Sound editor trim handles are slightly weird

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#873]
### Expected Behavior

Trim handle growing bigger should indicate, "this is the trim handle you're currently editing"

### Actual Behavior

Trim handle grows smaller again when you drag it a bit too fast for it to follow, making it look flickery. The other trim handle grows bigger when you drag over it, even though it's not active. None of the trim handles is active if you drag past the other trim handle. (Since the other trim handle grew larger, I thought that it meant that that one would start being dragged when I went past it, but it doesn't)

### Steps to Reproduce
Click down on a trim handle, but then move the mouse quickly. Move the mouse over the other trim handle.
![trimhandle](https://user-images.githubusercontent.com/2855464/32572487-bb7eb682-c498-11e7-8542-c550871b44c0.gif)

### Operating System and Browser

Windows 10 on Chrome

**Comment by paulkaplan** [comment]
No more trim handles! Closing.
