### ISSUE TITLE
Accessibility features

### ISSUE THREAD

**Issue by SebCanet** [LLK/scratch-gui#8749]
Hello,
I'm a STEM teacher in France, and also a workshop leader for children, I've been bugging the Blockly team about accessibility issues for years, it's made good progress, but I'm still disappointed to see that very few solutions are available in this excellent software that is Scratch:

- change the colour themes for the blocks,
- chang, fonts,
- chang, font sizes in menus and blocks,
- make the blocks compatible with screen reading like NVDA,
- mini map.

Thank you in advance and especially a big thank you for all that has already been done!

**Comment by cwillisf** [comment]
Hi @SebCanet! I like your ideas! We're working on some accessibility features now. Stay tuned!

**Comment by SebCanet** [comment]
Hi,
what a great new! I really appreciate that you've done something for it, we were expecting this kind of work for so long now. Where can we test????
