### ISSUE TITLE
Consider moving the stage to left side

### ISSUE THREAD

**Issue by Secret-chest** [LLK/scratch-gui#8752]
You could explore moving the stage to the left, because it's more ergonomic:
![image](https://user-images.githubusercontent.com/74449186/215495298-ccaee6dd-02bb-4863-8fc6-acfec1522f09.png)
![image](https://user-images.githubusercontent.com/74449186/215496087-faf29c80-5c9c-4a95-b619-4edfe2353e8c.png)
The red area is where the user needs to move its eyes. Having all panes packed together while the getting the same script space means less eye movement, which is good.

This is in no way based on any study.

Used NonoWord to demonstrate.

**Comment by aoneill01** [comment]
Thank you for your feedback! We will continue to review ideas like this using design studies. We may do something like this in the future.

**Comment by Crispydogs101** [comment]
This looks good with the fact that a 2.0 user can still get used to the 2.0 screen position.

**Comment by CST1229** [comment]
> This looks good with the fact that a 2.0 user can still get used to the 2.0 screen position.

It's been over 3 years since 3.0 came out.

**Comment by Crispydogs101** [comment]
Yeah you can make this off topic then.

**Comment by Secret-chest** [comment]
So the ST left no feedback? Scratch 1.x and stage on the right were designed for 4/3 monitors. We now have 16/9 monitors, ergonomics are more important.

**Comment by Crispydogs101** [comment]
True.
