### ISSUE TITLE
Delete button

### ISSUE THREAD

**Issue by Bashamega** [LLK/scratch-gui#8781]
### Expected Behavior

The button should be big
### Actual Behavior

The button is very small
### Steps to Reproduce

You should maximize the button

**Screenshots**
![bug 1](https://user-images.githubusercontent.com/110662505/222361296-4aa65376-00ae-4c3b-91c6-c721ea392443.png)

![3](https://user-images.githubusercontent.com/110662505/222361969-4214902f-4e17-485c-af98-0e7cc2e5c37a.png)
on all buttons ![bug 2](https://user-images.githubusercontent.com/110662505/222361799-862595d5-e0f6-44a0-a341-48e193c90a6e.png)s

**Comment by CST1229** [comment]
The version you're using is outdated (likely https://llk.github.io/scratch-gui/master instead of https://llk.github.io/scratch-gui/develop).

**Comment by Bashamega** [comment]
Thanks
