### ISSUE TITLE
When you add the WeDo extension, the blocks menu should scroll to it

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#879]
### Expected Behavior

When you add the WeDo extension, the blocks menu should scroll down to show the WeDo blocks.

### Actual Behavior

This works for other extensions, but not for the WeDo extension.

It looks like this is because the GUI asks the blocks to scroll to a category using its name, and the names don't match. The blocks menu uses the category name that is displayed in the blocks menu (and in the category menu), and the GUI uses the name that is displayed in the extension library. In the case of "Pen" and "Music" for example, these exactly match. The WeDo extension is labeled "WeDo 2.0" in the blocks menu, and "Lego WeDo 2.0" in the extension library.

### Steps to Reproduce

Click the "extensions" button
Add the Lego WeDo 2.0 extension

**Comment by ericrosenbaum** [comment]
Actually... translation is probably going to break this completely. We should not be using the displayed text to select blocks categories! 

The best "id" value is probably the extension id, but the blocks category menu does not know about this id, and the GUI also needs to be able to trigger scrolling to non-extension categories. So I'm not clear yet on how to solve this.

**Comment by ericrosenbaum** [comment]
Talked it over with @rschamp, and we decided to use IDs instead of names. 

- In GUI, use the extension URL as the ID
- In GUI, add an ID to each category in make-toolbox-xml.js (e.g. id="motion")
- In scratch-blocks, recordCategoryScrollPositions_ should store those ids
- Maybe that's it?

**Comment by paulkaplan** [comment]
Done!
