### ISSUE TITLE
Block icon for music extension

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#881]
We need a block icon for the music extension, to appear on each block and in the category menu.

**Comment by carljbowman** [comment]
@ericrosenbaum - Here ya go 🎶

Assets: [music-ext-icon.zip](https://github.com/LLK/scratch-gui/files/1519630/music-ext-icon.zip)

Mock:
<img width="597" alt="screen shot 2017-11-30 at 3 31 09 pm" src="https://user-images.githubusercontent.com/3409578/33457459-8d69ae46-d5f0-11e7-8013-98f9d69e79d2.png">
