### ISSUE TITLE
Save / Load for 3.0 Preview

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#882]
Save / Load will not be feature complete for the upcoming 3.0 preview. We should think about ways of communicating that Save / Load as a feature is being built, while not setting the expectation that work is being saved. 

There has been frustration in workshops because folks expect save to work the same way as 2.0 and lost projects because of this expectation. 

This is related to this issue: https://github.com/LLK/scratch-gui/issues/830

**Comment by Grinthy** [comment]
Like, this?

###Sorry!

We can't save this because this is a beta! We are working on it!
