### ISSUE TITLE
Confirmation Alert when browser Reload or Back is called

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#883]
### Expected Behavior
Similarly to how we have an alert that confirms deleting a sprite (granted this is temporary until we have Undo/Redo), we should pup an alert to confirm Reloading the page or going back.

2.0 pops a save alert on these actions and 3.0 should do the same, but until we have Save / Auto-save in place, we should have a confirmation.

### Actual Behavior
Nothing happens when Reload or Back is called, this can resulting in losing work.

**Comment by paulkaplan** [comment]
Fixed.
