### ISSUE TITLE
Deleting a Sound in the Sound Editor crashes everything

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#884]
### Expected Behavior
Sound should be deleted.

### Actual Behavior
Deleting a Sound in the Sound Editor crashes the GUI.

### Steps to Reproduce
1. Open the Scratch Editor: https://llk.github.io/scratch-gui/develop/
2. Navigate to the Sounds tab (Sound Editor)
3. Select a Sound
4. Click the 'x' in the upper right hand corner
5. Confirm in the alert

### Operating System and Browser

OS: macOS 10.11.6
Browser: Chrome Version 61.0.3163.100

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/858
