### ISSUE TITLE
() contains () Bug

### ISSUE THREAD

**Issue by Grinthy** [LLK/scratch-gui#886]
### Expected Behavior

The () contains () block was supposed to report true if a variable contains "world". The variable's value was "hello world". 

### Actual Behavior

Apparently, the script didn't do anything. I had a stage monitor on, and if the variable ran true, it would set the variable to 0 and start adding 1 forever,

### Steps to Reproduce

First, get a "When green flag clicked block" and connect it with a "set (TEST) to (hello world)" block.
(You have to create a variable, I used TEST)
Then, get a "if <condition> else" statement, and use "<(TEST) contains (world)>" on it.
In the first space, put the following:
set (TEST) to (0)
forever {
change (TEST) by (1)
}
In the else slot, put this.
set (TEST) to [FAIL]

### Operating System and Browser
x64 Bit Windows 10 Home Build 15063.674
Microsoft Edge 40.15063.674.0

### Notes
- I had to dig around to find the OS Stats. 
- If I had an option to upload the document I would include it, but I'm doing a picture.

### Media
![capture](https://user-images.githubusercontent.com/26236870/32637496-bcb77db2-c57f-11e7-8d09-f63075db55e7.PNG)
The Script

**Comment by Kenny2github** [comment]
That script worked for me on Windows 8 Chrome 62. This might specifically be an Edge issue...

**Comment by mrjacobbloom** [comment]
I'm getting the correct result too:

![foo contains world](https://user-images.githubusercontent.com/2879020/32642399-530107a0-c591-11e7-839d-ea67df3005ae.PNG)

64-bit Win10 and Chrome, I think it probably is an Edge issue but I can't get Edge to work right now

**Comment by SillyInventor** [comment]
On windows 10, edge 40.15063.0.0 I get the error:
![image](https://user-images.githubusercontent.com/8440451/32675373-b7e78624-c624-11e7-9082-8773f05cbc1f.png)

**Comment by Kenny2github** [comment]
Weird! I cannot reproduce this with Edge 25.10586.672.0. I realize that that's a waaay earlier version of edge, so I wonder what changed that broke this.
I also noticed several other issues that are Edge 25-specific, but they probably won't be resolved since Edge 25 is oooooold

**Comment by Grinthy** [comment]
Ok, so let's put our thoughts together:

- So far, Chrome is working. Let's test it with Edge.
- Question: Kenny2GitHub, you are running a waaay earlier version of Edge, as you previously stated. Can you update and reply to me to see what version you are using (preferably the latest version) so I can tell thisandagain?
- Another Question: SillyInventer. how did you get that error?
- mrjacobbloom, try restarting your OS, and defragging your hard drive. If all else fails, lemme know.

If there's anything I missed, juat tell me, and I will make a new set of notes.

**Comment by Kenny2github** [comment]
@Grinthy I can't update edge :( anything Windows Store-related is broken on here, so Settings doesn't work and I can't run Windows Update.

**Comment by Grinthy** [comment]
OOH! I have a suggestion.

@Kenny2github Could you use a VM to recreate the conditions that I described?

**Comment by Kenny2github** [comment]
@Grinthy I don't have a VM, and I can't install one 😢 it also seems like too much of a pain, so I think we can just wait for someone else to repro this on Edge

**Comment by Grinthy** [comment]
@Kenny2github Ok, I'm sorry about that. Now, it the patience game. Ohhhh man.

**Comment by Grinthy** [comment]
HELLO? xD

**Comment by redmangospros** [comment]
Yes, Same Thing.

**Comment by Grinthy** [comment]
@redmangospros Can you elaborate?

**Comment by Grinthy** [comment]
@redmangospros Can you elaborate?

**Comment by redmangospros** [comment]
?

**Comment by Grinthy** [comment]
Hello?
