### ISSUE TITLE
Sprite Error

### ISSUE THREAD

**Issue by Grinthy** [LLK/scratch-gui#887]
### Actual Behavior
I clicked the "New Sprite" Button, and it didn't create the sprite. It _could_ be because of my lack of knowledge of the interface, but I didn't see anything change.  

### Expected Behavior
The sprite was supposed to show up, but it didn't.

### Steps to Reproduce

Click the "New Sprite" button, and select a sprite. The sprite doesn't show up in the interface... anyone have questions?
### Operating System and Browser

x64 Bit Windows 10 Home Build 15063.674
Microsoft Edge 40.15063.674.0

_This doesn't really need pictures._

**Comment by Kenny2github** [comment]
I was able to add a sprite normally - it appeared on the stage and in the sprites area. Which sprite in particular did you try to add?

**Comment by Grinthy** [comment]
I added the sprite "Drum2" or "Drum1"

**Comment by redmangospros** [comment]
Hi There,

i hAve Tested The Edge With the Gui, This Is A Edge Related Issue.

**Comment by Grinthy** [comment]
HA! Thanks for your support, I'll try different sprites. Apparently, I forgot.

--Results--
Yeah, all the sprites I tried, it failed.

**Comment by Grinthy** [comment]
@redmangospros Can you go to issue #886 and review?

**Comment by Grinthy** [comment]
WAITT, @Kenny2github what browser are you using?

**Comment by Kenny2github** [comment]
@Grinthy Chrome, always Chrome for me.

**Comment by Grinthy** [comment]
kk thanks.

**Comment by cwillisf** [comment]
Initial investigation notes:
- Seems to be specific to Edge (IE11 hits errors before it gets this far, so it may or may not have this bug too)
- The default Scratch Cat sprite doesn't load either: the project starts with no sprites
- There are no errors in the JS console
- Many (>100) asset requests got stuck "(Pending)" in the Network tab: 
![image](https://user-images.githubusercontent.com/7019101/33683120-acaa8a2c-da7e-11e7-8ac8-164494babe33.png)
  - Note that there are also many successful asset requests: it's not that ALL requests are getting stuck.

**Comment by Grinthy** [comment]
Quick hit:

> IE Support should be dropped. It's slow, buggy and full of holes.
-Me

> Scratch Cat should be in every project in the beginning.
-Me

Also, this discussion needs a hamster.


![Awwwww.](grinthy.github.io/images/hamster.jpg)
--

**Comment by Grinthy** [comment]
This has been fixed on preview.scratch.mit.edu, assuming it's fixed on llk.github.io/scratch-gui.
