### ISSUE TITLE
Detect and show friendly error message if WebGL is not supported

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#888]
### Expected Behavior

- GUI should present a friendly error message if WebGL is not supported

### Actual Behavior

- Fatal exception and stage fails to load

### Steps to Reproduce

- Use computer or browser without WebGL support
- Load https://llk.github.io/scratch-gui

**Comment by thisandagain** [comment]
@carljbowman Can we get a design for this that is similar to the IE warning?
/cc  @chrisgarrity @cwillisf

**Comment by carljbowman** [comment]
## Mock
Follows the same pattern as https://github.com/LLK/scratch-gui/issues/828 and https://github.com/LLK/scratch-gui/issues/982
![unsupported webgl modal](https://user-images.githubusercontent.com/3409578/34216450-584cef9e-e576-11e7-9408-d4ce9acadbd5.png)

## Content
#### Illustration
- [ ] Illustration - @carljbowman 
For sizing, there is a temp asset here: https://github.com/LLK/scratch-gui/issues/982#issuecomment-351143042

#### Copy
Header: `TBD` - @thisandagain 
Copy: `TBD` - @thisandagain 

#### Button
`Back` - Should call a browser Back command

#### Secondary Copy
Footer: `To learn more, go to the Preview FAQ.`
- FAQ URL`scratch.mit.edu/preview-faq`

**Comment by jalman** [comment]
@carljbowman I think there's a typo. The word "is" is missing between "Space Jam" and "one".

By the way, Space Jam is my favorite movie too! It's truly incomparable.

**Comment by carljbowman** [comment]
@jalman - This is exactly why I should not write copy.

**Comment by thisandagain** [comment]
Boring non-space-jam themed copy has been added. 🏀 👾

**Comment by carljbowman** [comment]
@chrisgarrity - Just added an illustration to my comment above.
