### ISSUE TITLE
Should we add IDs to all blocks?

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#890]
Before https://github.com/LLK/scratch-gui/commit/72dbf9f9979f0727f6e811efe4569cb4f9011674, we had a problem where if you made a block glow in the flyout, changed tabs, and then changed back to the blocks workspace, you got a crash. https://github.com/LLK/scratch-gui/pull/871 fixed the most easily reproduced cases, but there are edge cases for all blocks if you navigate away while they are glowing. For instance, you can get it to happen by typing a large number in the 'repeat n times' block, clicking it, and switching tabs.

Would it make sense to assign IDs to all blocks? Is there a reason we haven't?

**Comment by rachel-fenichel** [comment]
All blocks have IDs in scratch-blocks, and I thought that the same IDs were being used in scratch-vm.  Isn't that how changes in blocks (e.g. changes in a text field) propagate to the VM?

IDs of blocks attached to custom procedures may be fun--I will need to keep that in mind.

**Comment by paulkaplan** [comment]
@rachel-fenichel I think this issue is specifically about giving fixed IDs to the blocks in the toolbox. 

I think it makes sense, yeah. We can just give everything an ID corresponding to the opcode, and then the extensions toolbox xml builder can do this automatically.

**Comment by rachel-fenichel** [comment]
Ah gotcha.  Yes, everything in the toolbox should also have a fixed ID, for specifically this purpose.  But then does it need a different ID per sprite, or is it the VM's job to apply it to the right sprite when clicked?

**Comment by paulkaplan** [comment]
I think this can be closed because of the work on recycled blocks
