### ISSUE TITLE
New URL isn't on the link section

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-gui#9030]
It seems the username has changed from LLK to scratchfoundation. The link section still says "_**llk**_.github.io", which could confuse some people.
For this to be fixed, you would need to change the llk in the URL to scratchfoundation.
EDIT: The username wasn't changed, it was just moved to this account.

**Comment by ghost** [comment]
![image](https://github.com/scratchfoundation/scratch-gui/assets/90093071/384200a5-1431-40e8-be9e-298e2bc9b5ab)

**Comment by lankybox02** [comment]
https://scratch.mit.edu/discuss/topic/691618/

**Comment by cwillisf** [comment]
Thanks! Fixed.

**Comment by tutacat** [comment]
@githubcoderelatedstufflol

https://en.wikipedia.org/wiki/Wikipedia:Be_bold

PRs are easier to see because they contain already actionable contant, plus there are are loads of open issues.
