### ISSUE TITLE
No spaces in list variable when each cell is exactly one character long

### ISSUE THREAD

**Issue by CuriousG2** [LLK/scratch-gui#9043]
### Expected Behavior

The values of the cells in the list's variable format should have spaces between them, even when each cell has exactly 1 character.

### Actual Behavior

The values of the cells turn into a string with no spaces, when are supposed to be separating spaces

### Steps to Reproduce

1. Create a new project
2. Create a list
4. Add multiple items to that list, with each item being exactly 1 character long
5. Click on the variable representing the list
6. See the error (the values of the cells do not have spaces between them)

Browser: Firefox 64-bit Version 114.0.2

Also Occurs in Chrome 64-bit Version 116.0.5845.14
Also Occurs in Scratch Desktop 32-bit Version 3.29.1

OS: Windows 11 22H2

**Screenshots**

https://github.com/scratchfoundation/scratch-gui/assets/138255501/d6c3eec0-467d-429b-ba9d-9e52b1e1433a

**Comment by CST1229** [comment]
[This is intentional.](https://github.com/scratchfoundation/scratch-vm/blob/e4bb21f1817a2b7bbca9be19da6eba529291ed0c/src/blocks/scratch3_data.js#L107-L122)
