### ISSUE TITLE
'Add Sprite' and 'Add Backdrop' buttons overlap other UI on window resize.

### ISSUE THREAD

**Issue by quachtina96** [LLK/scratch-gui#906]
### Expected Behavior
Upon reducing the height of a window, 'Add Sprite' and 'Add Backdrop' buttons should resize and stay below other input areas.
![image](https://user-images.githubusercontent.com/10423718/32930819-f3cb93c4-cb2e-11e7-9434-8a49d5fe053c.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/10423718/32930745-740a60fc-cb2e-11e7-82fc-8232996de220.png)

### Steps to Reproduce
Reducing the height of the window.

### Operating System and Browser
Mac OS 10.12.6 Chrome 62.0.3202.89

**Comment by paulkaplan** [comment]
Fixed
