### ISSUE TITLE
Certain Blocks Still Exist in Backdrop Code Editor

### ISSUE THREAD

**Issue by Grinthy** [LLK/scratch-gui#909]
### Expected Behavior
Blocks that cannot be performed in Stage Programming View (programming with the stage) appear
Blocks like:
![capture](https://user-images.githubusercontent.com/26236870/32950693-e43b4d76-cb6c-11e7-83a3-1823a3
66706a.PNG)
Really, the whole motion catagory and: 
![capture2](https://user-images.githubusercontent.com/26236870/32950834-689827ec-cb6d-11e7-810e-f72817fd4dd0.PNG)

### Actual Behavior

All the blocks listed above are accessible in stage programming.

### Steps to Reproduce

Go into the motion category with out creating a sprite (_you're in stage programming_)
### Operating System and Browser
x64 Bit Windows 10 Home Build 15063.674
Microsoft Edge 40.15063.674.0

**Comment by towerofnix** [comment]
I definitely remember (most of) these being hidden when the stage was selected before. There's recently been some re-working of how the block lists work, so I wouldn't be surprised if this is a regression from that.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/682
