### ISSUE TITLE
When I did the npm start command it gave me this error code 'ERR_OSSL_EVP_UNSUPPORTED'

### ISSUE THREAD

**Issue by thugilthedeveloper** [LLK/scratch-gui#9103]
Expected Behavior: Give me the link to the playground

_It'll give the link_

### Actual Behavior

_It just gave an error_

### Steps to Reproduce

1. Go do all steps before npm start
2. Type then enter npm start
3. After it finished BOOM, error

**Comment by CST1229** [comment]
Downgrade to node.js 14.

**Comment by thugilthedeveloper** [comment]
Ok thanks I will try that today
