### ISSUE TITLE
Remove all bitmap sprites, costumes and backdrops

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#913]
Because our current paint editor does not support bitmaps, we should temporarily remove all bitmap assets: sprites, costumes and backdrops.

**Comment by ericrosenbaum** [comment]
Also we'll need to remove any vector assets that include bitmaps inside of them (e.g. the backdrop "neon tunnel")

**Comment by towerofnix** [comment]
I wrote a script to remove all non-SVGs and SVGs which contain `<image>` elements from the library files. The output is available in [this gist](https://gist.github.com/towerofnix/7ec4fbcb687a6e35472f8ed298a07ba3/revisions). I've published the script [here](https://github.com/towerofnix/scratch-library-filter); output files are also available in that repository for comparison (or, view the [revisions](https://gist.github.com/towerofnix/7ec4fbcb687a6e35472f8ed298a07ba3/revisions) tab of the gist).

**Comment by fsih** [comment]
That's awesome @towerofnix, thanks!

**Comment by thisandagain** [comment]
Amazing. Thanks @towerofnix !
