### ISSUE TITLE
Removing category menu from blocks?

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-gui#916]
What's the best way to modify scratch-gui to not show block categories? Is it possible to do through the call to scratch-blocks, or does it require changing scratch-blocks directly? 

When I try just updating the toolbox with an XML that doesn't have categories in it I get an error:
"vertical.js:2900 Uncaught Existing toolbox has categories.  Can't change mode." 

@rschamp @ericrosenbaum

**Comment by paulkaplan** [comment]
I believe it can't be done after scratch blocks has been initialized with a category toolbox (which is done by default, even if you pass in no toolbox in the workspace config). You need to include a category-less toolbox at the time the scratch blocks workspace is created (in gui, that is in blocks.jsx componentDidMount). https://github.com/LLK/scratch-gui/blob/develop/src/containers/blocks.jsx#L59-L64

The key is to make sure you are passing in a category-less toolbox at that point.
