### ISSUE TITLE
Backdrop list is wrong in 'when backdrop switches' block

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#919]
The menu in the `when backdrop switches to 'menu'` should be dynamically updated to include the current list of backdrops.

**Comment by amazinigmech2418** [comment]
Maybe the js array needs to be constantly updated with the rendering of the editor.

**Comment by apple502j** [comment]
I found the bug: scratch-blocks/blocks_vertical/event.js 105th line
The array only contains backdrop1 and BACKDROP1.

Looks block, "switch backdrop" block is OK.
It doesn't have "options" array, and type is "input_value".
I can fix!

pull request https://github.com/LLK/scratch-blocks/pull/1327

**Comment by apple502j** [comment]
https://github.com/LLK/scratch-blocks/pull/1330
