### ISSUE TITLE
Monitors display too many decimal places

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#924]
### Expected Behavior

In Scratch 2.0, monitors truncate values so that they display no more than six decimal places. They also round down to zero when the value is below this threshold:

![monitor-precision](https://user-images.githubusercontent.com/567844/33027712-e57f3a86-cde1-11e7-890e-eb1729a9836a.gif)

### Actual Behavior

In Scratch 3.0, the monitors show too many decimal places, and eventually switch to showing scientific notation:

![monitor-precision-3 0](https://user-images.githubusercontent.com/567844/33027815-2a6f2462-cde2-11e7-92ad-2f92e0264e2e.gif)

### Steps to Reproduce

Create a variable and set it to a verrrrrry small value, or one with many decimal places.
Check the box next to it to display the monitor.

**Comment by fsih** [comment]
For the example above, do scratch 2.0 and 3.0 have different behavior for when "very precise numberz = 0" is true?

**Comment by ericrosenbaum** [comment]
When the variable is set to exactly zero, the monitors in 2.0 and 3.0 both show "0"

**Comment by towerofnix** [comment]
Worth noting that, in 2.0, when a variable actually contains a string and not a number as its value, all decimal places are shown (in the normal JS representation, e.g. "0.12317312743124e-7"): https://scratch.mit.edu/projects/187702715/

Not showing decimal places has been a source of confusion in 2.0: https://scratch.mit.edu/projects/187703591/

**Comment by towerofnix** [comment]
This is now working as "expected", i.e., as it behaves in 2.0:

![working](https://user-images.githubusercontent.com/9948030/33522801-e2c3488a-d7ed-11e7-9eed-3794f5dc0061.png)

Fixed by #946 - this issue should be closed?
