### ISSUE TITLE
Cannot load old sb2 projects

### ISSUE THREAD

**Issue by chexbox** [LLK/scratch-gui#928]
### Expected Behavior
Scratch 3.0 should eventually be able to load sb2 files so they can still be used. there will be some unhappy people if it will never be able to. Based on the contents of sb2 files this should not be to hard

### Actual Behavior
load fails; nothing happens

### Steps to Reproduce
save your sb2 file and click load in the scratch 3 GUI select the save sb2 file.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/127

**Comment by chexbox** [comment]
thanks!
