### ISSUE TITLE
 Deleting a Costume or Sound Pop-Up

### ISSUE THREAD

**Issue by chexbox** [LLK/scratch-gui#929]
### Expected Behavior
When deleting a costume or sound  the pop-up asks "Are you sure you want to delete this costume/sound"
### Actual Behavior
When deleting a costume or sound  the pop-up asks "Are you sure you want to delete this sprite"

### Steps to Reproduce
Go into GUI and try to delete costume/sound

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-gui/issues/385

**Comment by chexbox** [comment]
Thanks.
