### ISSUE TITLE
Events/Control Color

### ISSUE THREAD

**Issue by chexbox** [LLK/scratch-gui#930]
### Expected Behavior
Events tab color should be cc8c33. 
![screenshot 2017-11-20 at 14 12 47](https://user-images.githubusercontent.com/31783961/33039268-fb508f8e-cdfc-11e7-8886-d3b8fc4d9b9d.png)
Control tab color should be ffbf00. 
![screenshot 2017-11-20 at 14 20 12](https://user-images.githubusercontent.com/31783961/33039576-0525b290-cdfe-11e7-93a3-1bdb0574b606.png)

### Actual Behavior
Events color is ffbf00.
Control color is ffab19

### Steps to Reproduce
go to GUI look at Event/control tabs

**Comment by thisandagain** [comment]
The colors in Scratch 3.0 will be changed. See below for more information:
https://github.com/LLK/scratch-blocks/wiki/Colors
https://github.com/LLK/scratch-blocks/issues/1032
https://github.com/LLK/scratch-blocks/issues/995

If you don't mind, please take a look at existing issues before filing new ones. Thank you!

**Comment by chexbox** [comment]
Thank you! I was hoping this would be fixed. I tried looking for other existing issues, but didn't find this.
