### ISSUE TITLE
input renders out of the block panel

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#933]
### Expected Behavior

it shouldn't happen

### Actual Behavior

but it happened

### Steps to Reproduce

Write something looooooooooooooooooooooooooooooooooooooooooooong in the inputs

### Operating System and Browser

Windows 8.1, Google Chrome 60.0.3112.78
![default](https://user-images.githubusercontent.com/31377746/33070750-09fcc5d2-cef4-11e7-9d03-b7f172334342.PNG)

**Comment by thisandagain** [comment]
Moved to LLK/scratch-blocks#1255
