### ISSUE TITLE
Order of sprites in sprite selector is different than 2.0

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-gui#939]
The order of the sprites should be the same as it is in Scratch 2.0, but it's not.

See https://scratch.mit.edu/projects/151573690/#editor vs. https://llk.github.io/scratch-gui/#151573690

2.0:
![image](https://user-images.githubusercontent.com/15109618/33137659-390d8844-cfb1-11e7-815e-1243e7f901aa.png)

3.0:
![image](https://user-images.githubusercontent.com/15109618/33137673-443777ac-cfb1-11e7-9c83-d6e725d93117.png)

**Comment by thisandagain** [comment]
Thanks @morantsur ! It's great to have this issue tracked. 😄

**Comment by redmangospros** [comment]
I Like The Update In Scratch 3.0 better than 2.0

**Comment by morantsur** [comment]
@thisandagain @paulkaplan  
Just adding some more info, not sure if it should be another bug or if expected - 
the layer each sprite is created on is determined by the sprites order in the sb2 file, which means that changing the order of the sprites (by manually changing the json file for now, and maybe later by dragging?) changes the layers things appear on.  

I think it's all related to two fields being ignored in the serialization of sb2 files (and then ignored in the rendering): 
* baseLayerID (for the layer)
* and indexInLibrary (for the order of sprites)

**Comment by thisandagain** [comment]
@morantsur Yup! That is a feature we haven't implemented yet. I've been holding off on scheduling this until #45 is resolved partially because we'll need figure out how to marshal this in the GUI / VM.

**Comment by paulkaplan** [comment]
Fixed in the VM
