### ISSUE TITLE
Implement list monitors

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-gui#942]
### Expected Behavior

List monitors should be like 2.0

### Actual Behavior

List monitors attempt to act like variable monitors, with strange results:
![image](https://user-images.githubusercontent.com/28599280/33167403-60930ba6-d078-11e7-9881-32c2a63fc3bc.png)

### Steps to Reproduce

1. Create a list
2. Look at the Stage

### Operating System and Browser

Chrome 62 Windows 10

**Comment by thisandagain** [comment]
Thanks @Kenny2github. This is a feature that hasn't been implemented yet.

**Comment by towerofnix** [comment]
See also #268:

>**Dropping text files onto lists to insert the text content into the list.** I'm bolding this because I think it'll otherwise be missed, and would be a surprisingly useful feature – for example, as a means of loading save files into a project with a custom save/load mechanic. It's already a feature of 2.0 to import/export list data by using the context menu, but a more obvious and robust way would be nice.

Definitely not a critical thing to implement, but maybe worth considering while designing.

Several Scratch games use lists exporting/importing as a save/load mechanic, but unfortunately it currently requires the user to see inside the project and right-click on the list monitor. It certainly doesn't need to be that complicated. So, adding onto that idea - should there be a way for the user to import or export a displayed list as a text file, just by clicking a button on the list monitor?

**Comment by thisandagain** [comment]
Yup! Agreed. We'll implement the CSV import/export in a separate issue / scope of work, but we are tracking it. 😄

**Comment by towerofnix** [comment]
>Yup! Agreed. We'll implement the CSV import/export in a separate issue / scope of work, but we are tracking it. :smile:

:tada:

> CSV import/export

..Does this mean you'll be implementing 2-dimensional lists? :stuck_out_tongue_winking_eye:

**Comment by thisandagain** [comment]
@towerofnix LOL. One step at a time. 😜

**Comment by DeleteThisAcount** [comment]
when can we expect 4d lists?

**Comment by picklesrus** [comment]
I know this isn't done yet, but here are couple of things to make sure to test when implementation is done:
- When a list is renamed, the monitor's name should be updated too
- Color of the monitor should match the color of the list category instead of the variable category.

**Comment by kyleplo** [comment]
bump

**Comment by rachel-fenichel** [comment]
Frequently reported in Scratch 3.0 feedback.
