### ISSUE TITLE
Scratch GUI link not working

### ISSUE THREAD

**Issue by biggiecheesetherat** [LLK/scratch-gui#9448]
### Expected Behavior

https://llk.github.io/scratch-gui/develop should open the Scratch GUI.

### Actual Behavior

It opens the Github Pages 404 page.

### Steps to Reproduce

1. Go to 'https://llk.github.io/scratch-gui/develop'
2. See error

### Fix

Replace the URL with https://scratchfoundation.github.io/scratch-gui/.

### System Details
Opera GX (Or just Opera) on Windows 11. 

**Screenshots**
![image](https://github.com/scratchfoundation/scratch-gui/assets/143027785/e4ae8fd6-2531-479b-abb7-ad53ffda08bb)

**Comment by dumorando** [comment]
because its the wrong url :trollface:

**Comment by biggiecheesetherat** [comment]
i know that

**Comment by tutacat** [comment]
Duplicate of #9030

**Comment by cwillisf** [comment]
Thanks! Fixed.
