### ISSUE TITLE
How do you add a block in a scratch- GUI by scratch-blcoks?

### ISSUE THREAD

**Issue by chaoqinf** [LLK/scratch-gui#945]
I added a block in scratch- blocks, but it doesn't show up in scratch- GUI.
I've recompiled scratch-blocks

**Comment by Kenny2github** [comment]
@mrjacobbloom you don't even add definitions for blocks in scratch-blocks, those go in scratch-vm. The block is added to the toolbox in scratch-blocks. Dropdown menus for the blocks (if needed) are added in scrach-gui.

**Comment by chaoqinf** [comment]
I 我在scratch-vm中也添加了，不过也不显示在scratch-gui中

**Comment by chaoqinf** [comment]
I also added it in scratch- vm, but not in scratch- GUI

**Comment by Kenny2github** [comment]
@chaoqinf the process is: add the code for the block in scratch-vm; add the block to the toolbox in scratch-blocks; add dropdowns in scratch-gui if necessary

**Comment by chaoqinf** [comment]
@Kenny2github where to add dropdowns in scratch-gui?

**Comment by Kenny2github** [comment]
@chaoqinf take a look at #634 where I added the dropdown for the "glide (secs) to [dropdown]" block.

**Comment by chaoqinf** [comment]
@Kenny2github I'll add...My challenge now is to not allow the added block to be displayed in the GUI's toolbox.
I've added a description to the default-toolbox

**Comment by chaoqinf** [comment]
@Kenny2github Can you tell me how a block can be created from scratch-blocks and scratch-vm into scratch- GUI?I might have missed some details...

**Comment by Kenny2github** [comment]
First, you add the actual code for the block in one of the files [here](https://github.com/LLK/scratch-vm/tree/develop/src/blocks) - it will depend on the category, but that's where you add the code.
Next, you add the block to the palette in one of the files [here](https://github.com/LLK/scratch-blocks/tree/develop/blocks_vertical) (again, use the correct category).
If you need to add a dropdown, do that in [this file](https://github.com/LLK/scratch-gui/blob/develop/src/lib/blocks.js).
You might want to take a look at precisely what I did to add the "glide (secs) to [dropdown]" in these three pulls: LLK/scratch-vm#662 LLK/scratch-blocks#1046 LLK/scratch-gui#634

**Comment by chaoqinf** [comment]
@Kenny2github Thank you very much

**Comment by Kenny2github** [comment]
No problem! :D
