### ISSUE TITLE
Idea: "toggle stage view to [v ]" block

### ISSUE THREAD

**Issue by Grinthy** [LLK/scratch-gui#947]
###Overview
It would be nice if there was a dropdown block called "toggle stage view to [v ]" For the dropdown, the possible values were "**code**" *(Editor)*, "**project**" *(project page)*, and "**fullscreen**" *(full screen view of project)*.
###Possible Usage
- If you want to start the project in fullscreen, you could use "toggle stage view to [v fullscreen]". If project page viewing was required, you'd use the "**project**" pram.
- At the end of an animation, you could show the code used to make the project, using the "**code**" pram.

###Questions?

@thisandagain Can you add this as a suggestion?

**Comment by mrjacobbloom** [comment]
This feels like a breach of user trust in the site, like an ad that autoplays music. I’d rather be able to expect the same UI every time I open a project. Plus I can see issues with people locking themselves out of the editor

**Comment by Grinthy** [comment]
Okay, thanks.

Wait:

> like an ad that autoplays music.
First of all, this is not an automatic "when page finishes load, click green flag" block. Also, I don't really get how this would be a breach of user trust.

>  Plus I can see issues with people locking themselves out of the editor.
Yeah, that's a possibility.

**Comment by Kenny2github** [comment]
@mrjacobbloom 

>Plus I can see issues with people locking themselves out of the editor.

This is a stack block, though - even if it were in a "forever" loop you could simply press the Stop button and then switch into the editor.

**Comment by thisandagain** [comment]
@Grinthy Unfortunately I can see a number of ways that this could be used that could be confusing and produce unexpected / undesirable behaviors. I can also see a few ways that this could be used for abuse:
```text
forever
    toggle stage view to [code]
    toggle stage view to [project]
    toggle stage view to [fullscreen]
```
