### ISSUE TITLE
Beta Test Site please?

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#954]
This isn't exactly an issue. I know that right before the release of Scratch 2.0, a beta site was launched at beta.scratch.mit.edu. Would it be possible to do a similar site for Scratch 3.0, with the entire community features instead of just the GUI?

**Comment by towerofnix** [comment]
I think the plan is to release those incrementally, just like they've been doing with all previous migrated pages. So, no need for a beta site; they're just slowly updating the current site. So there's no strict "3.0 site", but you could say that when all pages are migrated to 3.0, we're on the 3.0 site.

**Comment by thisandagain** [comment]
We are planning to do this early next year.

**Comment by thisandagain** [comment]
We are planning on releasing a preview of Scratch 3.0 early next year. As @towerofnix said, the entire website will not be updated all at once but has been getting updated incrementally for about the last year and a half.
