### ISSUE TITLE
I met a problem when I clicked on the “Costumes” button

### ISSUE THREAD

**Issue by varwym** [LLK/scratch-gui#957]
### Expected Behavior

i have started server successfully, but when i visit to http://localhost:8601/ , the have been some mistakes in the chrome console.

### Actual Behavior

error and warning

Ignoring non-existent input BROADCAST_OPTION in block event_broadcast
Ignoring non-existent input BROADCAST_OPTION in block event_broadcastandwait
Ignoring non-existent input BROADCAST_OPTION in block event_broadcast
Ignoring non-existent input BROADCAST_OPTION in block event_broadcastandwait

Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22

Uncaught TypeError: this.props.vm.getCostumeSvg is not a function
react-dom.development.js:8305 The above error occurred in the <PaintEditorWrapper> component:
    in PaintEditorWrapper (created by Connect(PaintEditorWrapper))
    in Connect(PaintEditorWrapper) (created by CostumeTab)
    in div (created by Box)
    in Box (created by AssetPanel)
    in div (created by Box)
    in Box (created by AssetPanel)
    in AssetPanel (created by CostumeTab)
    in CostumeTab (created by Connect(CostumeTab))
    in Connect(CostumeTab) (created by GUIComponent)
    in div (created by TabPanel)
    in TabPanel (created by GUIComponent)
    in div (created by UncontrolledTabs)
    in UncontrolledTabs (created by Tabs)
    in Tabs (created by GUIComponent)
    in div (created by Box)
    in Box (created by GUIComponent)
    in div (created by Box)
    in Box (created by GUIComponent)
    in div (created by Box)
    in Box (created by GUIComponent)
    in div (created by Box)
    in Box (created by GUIComponent)
    in GUIComponent (created by GUI)
    in GUI (created by Connect(GUI))
    in Connect(GUI) (created by VMListener)
    in VMListener (created by Connect(VMListener))
    in Connect(VMListener) (created by ProjectLoaderComponent)
    in ProjectLoaderComponent (created by AppStateWrapper)
    in IntlProvider (created by Connect(IntlProvider))
    in Connect(IntlProvider) (created by AppStateWrapper)
    in Provider (created by AppStateWrapper)
    in AppStateWrapper

Consider adding an error boundary to your tree to customize error handling behavior.
You can learn more about error boundaries at https://fb.me/react-error-boundaries.
logCapturedError$1 @ react-dom.development.js:8305
captureError @ react-dom.development.js:12993
performWork @ react-dom.development.js:12825
batchedUpdates @ react-dom.development.js:13244
performFiberBatchedUpdates @ react-dom.development.js:1646
stackBatchedUpdates @ react-dom.development.js:1637
batchedUpdates @ react-dom.development.js:1651
batchedUpdatesWithControlledComponents @ react-dom.development.js:1664
dispatchEvent @ react-dom.development.js:1874
react-dom.development.js:1345 Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1345)
    at invokeGuardedCallback (react-dom.development.js:1195)
    at performWork (react-dom.development.js:12800)
    at batchedUpdates (react-dom.development.js:13244)
    at performFiberBatchedUpdates (react-dom.development.js:1646)
    at stackBatchedUpdates (react-dom.development.js:1637)
    at batchedUpdates (react-dom.development.js:1651)
    at Object.batchedUpdatesWithControlledComponents [as batchedUpdates] (react-dom.development.js:1664)
    at dispatchEvent (react-dom.development.js:1874)
### Steps to Reproduce
git clone this project
npm install
npm start
open the http://localhost:8601

### Operating System and Browser

_e.g. Mac OS 10.12.1 chrome 62.0.3202.94_

**Comment by thisandagain** [comment]
I believe this is an issue that has been resolved in https://github.com/LLK/scratch-vm/pull/823. Can you please `rm -rf node_modules && npm install && npm start` and try again?

**Comment by focalhot** [comment]
Don't use cnpm, try to use npm registry
npm config set registry https://registry.npmjs.org
npm info underscore
