### ISSUE TITLE
Deleting a sprite does not delete its clones

### ISSUE THREAD

**Issue by owenkaplinsky** [LLK/scratch-gui#9576]
### Expected Behavior

Deleting a sprite deletes all of its clones

### Actual Behavior

Deleting a sprite does not delete all of its clones

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Open a sprite
2. Clone it, and make the clones not stack on top of each other
3. Delete the sprite
4. Observe how the clones are not deleted

### System Details
All

**Comment by Octostomp** [comment]
Can confirm on both the website and offline editor (3.29)

**Comment by mxmou** [comment]
Duplicate of #2931
PR with fix: scratchfoundation/scratch-vm#2358
