### ISSUE TITLE
Issue With ScratchBlocks going under the Extensions button but above everything else

### ISSUE THREAD

**Issue by dalearn** [LLK/scratch-gui#959]
When dragging Scratch Blocks the blocks appear above every component except for the title bar (in my opinion that one is questionable and should be discussed) and the "Extensions" button where they go underneath.  I have identified the offending line as `src/components/gui/gui.css` line `158` which states `z-index: 50; /** Force extension button above the ScratchBlocks flyout. */`.  
I don't understand the reasoning behind this behavior and after removing the above line it behaved normally.  Any Ideas?

On a similar note, blocks go under the title bar which should be discussed.  Should they go over everything except for the title bar or everything including the title bar?

**Comment by benjiwheeler** [comment]
related to z-index (adding this comment in hopes of improving search/findability of related issues)

**Comment by benjiwheeler** [comment]
Thanks for the report, @dalearn .

The extension part of this issue has been resolved.

The navbar part of this issue, I combined into https://github.com/LLK/scratch-gui/issues/1792
