### ISSUE TITLE
IE - Stage + Blocks panes do not display

### ISSUE THREAD

**Issue by lifeinchords** [LLK/scratch-gui#96]
Layout pane structure with sprite selector seems to render ok, though stage + blocks panes are not displaying. Sprite Selector is in the wrong position, so there might be flexbox issues specific to IE here as well.

Related to [IE - Unable to get property `length` of undefined or null reference](https://github.com/LLK/scratch-render/issues/85)

Tested on virtual image with:

MSEdge - Win10_preview
Edge version 38.14393.0.0
EdgeHTML 14.14393

<img width="1327" alt="screen shot 2017-02-14 at 11 19 24 pm" src="https://cloud.githubusercontent.com/assets/716168/22976276/189ab8d8-f358-11e6-8b56-b4aff093facf.png">

**Comment by TheBrokenRail** [comment]
Fixed
