### ISSUE TITLE
Bottom Edge of Tabs Looks Awkward

### ISSUE THREAD

**Issue by dalearn** [LLK/scratch-gui#960]
The bottom of the tabs when selected has a 1px white border on the bottom to cover up the gray border.  
![original](https://user-images.githubusercontent.com/16820599/33341257-5e49e3c4-d44c-11e7-8435-beb3c9f29c8d.png)

This looks particularly ugly when the second tab is selected because it looks like part of the border is missing.  To help I believe a bottom border color of the same color as the background behind the tabs should be added.

Reasons for this are:
a)  The border around the entire area remains unbroken yet allowing it to be visually obvious that the tab is connected to the displayed content
b)  There isn't a "half border" where the white background begins

I suggest that the border on the bottom of the tabs look like:
![new](https://user-images.githubusercontent.com/16820599/33341636-893d6640-d44d-11e7-99c5-3b6a6d655eb9.png)

**Comment by dalearn** [comment]
@thisandagain When can I resubmit my PR?  I'm new to the Github culture (I usually work alone) and am unsure of when I can submit this fix.

**Comment by thisandagain** [comment]
@dalearn No worries! 😄  I'd like @carljbowman to weigh in on the design of this before we consider a PR.

**Comment by paulkaplan** [comment]
Consulted @carljbowman, closed by https://github.com/LLK/scratch-gui/pull/970
