### ISSUE TITLE
(Request) Be Able To View a costume Of a srpite when chossing from the sprite  Libary

### ISSUE THREAD

**Issue by redmangospros** [LLK/scratch-gui#969]
My Request is To Be Able To View a Sprite costumes When Chosing From The Libary.
@thisandagain 
## Expected
View >Coustmes When Picking

## Actul
Be ABle To View Coustems And Look AT Perspectives when picking

**Comment by mrjacobbloom** [comment]
Kind of like scrubbing through the costumes on hover like a photo album of video thumbnail?

**Comment by redmangospros** [comment]
?

**Comment by mrjacobbloom** [comment]
oh never mind, the sprites library already does what I was imagining lol

**Comment by paulkaplan** [comment]
Hi @redmangospros, the sprite library shows the different costumes if you mouse over.

**Comment by redmangospros** [comment]
It ShowsThe # of Coustmes.
