### ISSUE TITLE
Scratch 1.4 Support

### ISSUE THREAD

**Issue by JuegOStrower** [LLK/scratch-gui#972]
When I try to open an Scratch 1.4, it doesn't load. You can try this in [this project](https://scratch.mit.edu/projects/1234) If you download that project json (from [this link](https://cdn.projects.scratch.mit.edu/internalapi/project/1234/get/)), you can check that it was uploaded from the scratch 1.4 editor

**Comment by thisandagain** [comment]
Yup! We haven't built out support for importing Scratch 1.4 projects yet. We plan to do this next year.

**Comment by rschamp** [comment]
Dupe of https://github.com/LLK/scratch-vm/issues/128
