### ISSUE TITLE
[Safari] Overflow scroll not working in SpriteSelector pane

### ISSUE THREAD

**Issue by lifeinchords** [LLK/scratch-gui#98]
### Expected Behavior

Person should be able to scroll the pane

### Actual Behavior

No scrollbar is present, can't scroll.

### Steps to Reproduce

Load a project with more items than visible in one page-full.

### Operating System and Browser

Safari 10.0.1 (12602.2.14.0.7)

<img width="573" alt="screen shot 2017-02-15 at 8 59 06 am" src="https://cloud.githubusercontent.com/assets/716168/22977539/0794623c-f35d-11e6-8ea4-3c040463df5f.png">

**Comment by bartljak** [comment]
Scrollbar is appearing on Safari 11.0 for me. 
![screen shot 2017-09-26 at 3 42 00 pm](https://user-images.githubusercontent.com/6947753/30880645-4bb212c4-a2d1-11e7-803a-45eecd6e6308.png)

**Comment by thisandagain** [comment]
Unable to repro in latest Safari
