### ISSUE TITLE
Integration test fails when window height is too small.

### ISSUE THREAD

**Issue by quachtina96** [LLK/scratch-gui#984]
### Expected Behavior
In test/integration/test.js, the 'Switching sprites updates the block menus' test should be able to simulate a click on the Stage Editor at any window size.

### Actual Behavior
When the window height is too small, the test cannot simulate the click on the Stage Editor because the "Add Backdrop" icon button blocks it (Issue #906 ). The test fails there.

The test expects:
![image](https://user-images.githubusercontent.com/10423718/33490573-991e09f4-d685-11e7-8a40-b8ebb8145d22.png)
The test fails on:
![image](https://user-images.githubusercontent.com/10423718/33490595-a9e996f4-d685-11e7-9506-d509c1e05116.png)

### Steps to Reproduce

1.  Run the 'Switching sprites updates the block menus' integration test with Scratch at smaller height such that the icon button overlaps with the 'Costumes' label of the Stage Editor (as pictured above).

### Operating System and Browser

 Mac OS 10.13.1 Chrome 62.0.3202.94

**Comment by dalearn** [comment]
One fix is to set the min height of the page.  The min width is currently taken care of but there doesn't appear to be any meaningful minimum height.

**Comment by amazinigmech2418** [comment]
The problem is that the sizes need to be relative to the screen size, not that the screen size isn't constant.
