### ISSUE TITLE
A Few Subtle Design Quirks

### ISSUE THREAD

**Issue by dalearn** [LLK/scratch-gui#988]
This isn't an "issue" per se but it is the only way I can find to contact the admins of this project.  Would it be ok if I were to fix a few small quirks with the design (mostly with missing borders on one side of a component) without filing an issue for each and every one?  Would a detailed PR be enough?

**Comment by thisandagain** [comment]
@dalearn We would prefer that you file issues for any design changes and only submit PRs for issues that have been marked as "help wanted".
