### ISSUE TITLE
When Changing Languages the Scratch Player Turns Black

### ISSUE THREAD

**Issue by dalearn** [LLK/scratch-gui#989]
### Expected Behavior

When changing languages all components of the page except for the text to be changed should remain exactly as it was previously with no flashes or noticeable changes.

### Actual Behavior

Many components "flash" briefly with the most notable be the scratch player turning black.

### Steps to Reproduce

Change language while watching the various components.

### Operating System and Browser

Mac OS 10.12.6 Safari 11.0.1

**Comment by Kenny2github** [comment]
Repro-ed on Chrome 62 Windows 10.

**Comment by davidaylaian** [comment]
Can confirm on Firefox 57.0.1 (64-bit) Linux.

**Comment by Kenny2github** [comment]
Welp, reproed on every OS and every major browser except Edge :P

**Comment by chrisgarrity** [comment]
Yup, the currently reloads when you change language. Tracking in #555
