### ISSUE TITLE
Editor becomes empty after deleting the only song in a sprite/on the stage.

### ISSUE THREAD

**Issue by Smrman** [LLK/scratch-gui#991]
### Expected Behavior
_When cross on the only sound is clicked (to delete it), the alert box of the browser shows up and ask if we want to delete the song. If yes, the song is deleted._

### Actual Behavior

_When cross on the only sound is clicked (to delete it), the alert box of the browser shows up and ask if we want to delete the song. If yes, the editor becomes white and empty_
See: http://i.cubeupload.com/1Bayz0.png

### Steps to Reproduce

_1. Go in the sound tab of a sprite / of the scene._
→ http://i.cubeupload.com/iHYK5H.png
_2. Make sure there is only 1 sound in the sound tab._
_3. Click on the cross to delete the sound._
→ http://i.cubeupload.com/abLnaE.png
_4. When Alert Bow with "Are you sure you want to delete this sprite?", click "Ok"._
→ http://i.cubeupload.com/KQAdd1.png

==> Editor is empty

### Operating System and Browser

_Windows 10 Pro Insider Preview build 17025.rs-prerelease.171020-1626_
_Google Crome 62.0.3202.94 (64 bits)_
_Javascript V8 6.2.414.42_
_Flash 27.0.0.187_

**Comment by Kenny2github** [comment]
Hi! Are you using the most updated branch? This issue doesn't appear on https://llk.github.io/scratch-gui/develop - only on https://llk.github.io/scratch-gui/
https://llk.github.io/scratch-gui/develop contains the most recent bugfixes and features.

**Comment by Smrman** [comment]
There is some progress, the screen doesn't remain empty but there is still something wrong...
http://i.cubeupload.com/pB0fjK.png

**Comment by Kenny2github** [comment]
Not for me...
![image](https://user-images.githubusercontent.com/28599280/33516211-ec32c5ec-d7a9-11e7-8a7d-d8a66f42c945.png)

**Comment by paulkaplan** [comment]
Closing because this can't be repro'd on develop.
