### ISSUE TITLE
Fatal error: Variable "message1" is already in use

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#994]
I can get a project-destroying error by doing the following:

1. On a fresh project, scroll down to the broadcast blocks and click "broadcast <message1>" to run it.
2. Now drag that block out into the workspace.
3. Switch to the stage.

The error is 
```
Uncaught Error: Variable "message1" is already in use and its id is "<crazy id>" 
which conflicts with the passed in id, "<different crazy id>".
```

**Comment by kchadha** [comment]
Resolved with [Broadcast Msg Bugfix #845](https://github.com/LLK/scratch-vm/pull/845) in scratch-vm.
