### ISSUE TITLE
Preload Assets

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#999]
### Expected Behavior

Sound plays when requested

### Actual Behavior

There is lag before sound plays. I am guessing this is because the sound has not been loaded.

### Steps to Reproduce

Try https://llk.github.io/scratch-gui#191054897

### Operating System and Browser

Windows 10 Chrome 62 Desktop

**Comment by ericrosenbaum** [comment]
We're now pre-loading the musical instrument and drum sounds. This change is on the "develop" branch, but not yet on the "master" branch. So the problem should be fixed if you view the project here- please confirm:

https://llk.github.io/scratch-gui/develop/#191054897
